### PR TITLE
Expose threshold argument of Jaro-Winkler similarity

### PR DESCRIPTION
**Pull request by zmbc**
Following up on #10345, but starting with Jaro-Winkler similarity. This PR adds an optional third argument to the Jaro and Jaro-Winkler functions that acts as a "threshold" -- similarities below the threshold are reported as zero. This was already implemented in the vendored implementation of Jaro-Winkler, just not exposed to the DuckDB user.

If this is received positively, I'd like to update the vendored RapidFuzz and use it for all string comparisons, which would allow exposing this argument for those as well.

**NOTE: I am not great at C++. I expect this will need a lot of cleanup.**

### CODE REVIEW

**Comment by zmbc** [comment]
Hi @Mytherin and @szarnyasg, does either of you have capacity to review this PR or find someone else who does?

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - could you just solve the merge conflicts? In particular, the `core_functions` has been moved to `extension/core_functions`.

**Comment by zmbc** [comment]
Thanks so much! I think Git avoided any conflicts when I turned on inexact rename detection 😃 Should be good to review now.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
