### PR TITLE
Adding geo extension

### PR DESCRIPTION
**Pull request by handstuyennn**
Hi @Mytherin

Relating to [this thread](https://github.com/duckdb/duckdb/issues/4118).
I have added a basic implementation of an extensible `GEOGRAPHY` type. If this looks good, I will continue building the different geography types and their functions.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Similar to the [sqlitescanner](https://github.com/duckdblabs/sqlite_scanner) and [postgresscanner](https://github.com/duckdblabs/postgres_scanner) the geom extension should also live in a separate repository. That way the development and issue tracking can happen separately from the core project. 

Perhaps you can co-ordinate with @Maxxen about that, as he is also planning on working on the geom stuff. We could create a `duckdblabs/geom` repository and move the work there, for example.

**Comment by Tishj** [comment]
Is the licensing of PostGIS not an issue when it's moved to a separate repository as well?

**Comment by Maxxen** [comment]
Cool! Hi!, Yes, as Mark mentioned my long term goal is to implement a "native" DuckDB geospatial extension. The plan is roughly to represent geometry using the built in nested types, to leverage the compression and eventually integrate better with the wider range of columnar formats popping up in the geospatial ecosystem (geoarrow, GeoParquet, etc). The work I've done so far implementing `UNION` "types" has partly been driven by the goal to be able to represent a base "geometry" type (that can be either polygon, point, line etc). Ideally we also manage to write/port a set of "vectorized" geometry functions without having to wrap GEOS/liblwgeom/s2 and pay the serialization costs, but before I get started on that I'd also like to implement some sort of spatial indexing, which will require more substantial work in the duckdb core to extend the indexing mechanisms.

I want to focus on the "core" first and lay out the groundwork required for effective geo operations, but I think this is still a good extension to use for comparison/testing later once I get started on the actual user-facing stuff (which I of course would love to develop openly and involve the community in).

**Comment by handstuyennn** [comment]
Hi @Mytherin  and @Maxxen ,

I have moved this extension to new repository. Please visit [https://github.com/handstuyennn/geo](geo) to get more and give me feedback if you have any.

Thanks

**Comment by Mytherin** [comment]
> Hi @Mytherin and @Maxxen ,
> 
> I have moved this extension to new repository. Please visit [geo](https://github.com/handstuyennn/geo) to get more and give me feedback if you have any.
> 
> Thanks

Looks great! Thanks!

I will close this PR for now.

**Pull request closed without merging**
