### PR TITLE
Parallel CSV Reader

### PR DESCRIPTION
**Pull request by pdet**
Experimental implementation of the Parallel CSV Reader.

We can currently parallelize cases where the quotation, escape, and delimiters are limited to one character.
The parallel CSV reader doesn't also doesn't support new lines inside strings nor the CSV Sniffer (A schema must be provided first).

Since the implementation is not yet integrated with the CSV Sniffer is currently hidden by the 
```sql 
SET experimental_parallel_csv=true;
```

The CSV reader works by default by throwing as many threads as possible to work on 32 Mb Chunks. The chunk size can be adjusted via the CSV Read function.
e.g., 
```sql 
SELECT sum(a) FROM read_csv('test/sql/copy/csv/data/test/multi_column_integer.csv',  COLUMNS=STRUCT_PACK(a := 'INTEGER', b := 'INTEGER', c := 'INTEGER'), auto_detect='false', delim = '|', buffer_size=5)
```

For TPC-H SF1:

 Latest DuckDB duckdb-0.5.1
SF:1 Threads: 1 Time:2.9291566249448806

This PR
SF:1 Threads: 1 Time:2.953550708014518
SF:1 Threads: 4 Time:0.8697507920442149

~3.6x faster with 4 threads.

### CODE REVIEW

**Comment by lnkuiper** [comment]
Awesome work @pdet !! This release is going to be awesome :)

**Comment by pdet** [comment]
Thanks @lnkuiper, yeah this release will be lit 🔥

We did some benchmarking yday and now we can load the clickbench csv file in ~400s in the same machine as their official benchmark [here](https://benchmark.clickhouse.com/#eyJzeXN0ZW0iOnsiQXRoZW5hIChwYXJ0aXRpb25lZCkiOnRydWUsIkF0aGVuYSAoc2luZ2xlKSI6dHJ1ZSwiQXVyb3JhIGZvciBNeVNRTCI6dHJ1ZSwiQXVyb3JhIGZvciBQb3N0Z3JlU1FMIjp0cnVlLCJCeXRlSG91c2UiOnRydWUsIkNpdHVzIjp0cnVlLCJjbGlja2hvdXNlLWxvY2FsIChwYXJ0aXRpb25lZCkiOnRydWUsImNsaWNraG91c2UtbG9jYWwgKHNpbmdsZSkiOnRydWUsIkNsaWNrSG91c2UiOnRydWUsIkNsaWNrSG91c2UgKHR1bmVkKSI6ZmFsc2UsIkNsaWNrSG91c2UgKHpzdGQpIjpmYWxzZSwiQ2xpY2tIb3VzZSBDbG91ZCI6dHJ1ZSwiQ3JhdGVEQiI6dHJ1ZSwiRGF0YWJlbmQiOnRydWUsImRhdGFmdXNpb24iOnRydWUsIkRydWlkIjp0cnVlLCJEdWNrREIiOnRydWUsIkVsYXN0aWNzZWFyY2giOnRydWUsIkVsYXN0aWNzZWFyY2ggKHR1bmVkKSI6ZmFsc2UsIkdyZWVucGx1bSI6dHJ1ZSwiSGVhdnlBSSI6dHJ1ZSwiSW5mb2JyaWdodCI6dHJ1ZSwiTWFyaWFEQiBDb2x1bW5TdG9yZSI6dHJ1ZSwiTWFyaWFEQiI6ZmFsc2UsIk1vbmV0REIiOnRydWUsIk1vbmdvREIiOnRydWUsIk15U1FMIChNeUlTQU0pIjp0cnVlLCJNeVNRTCI6dHJ1ZSwiUGlub3QiOnRydWUsIlBvc3RncmVTUUwiOnRydWUsIlF1ZXN0REIgKHBhcnRpdGlvbmVkKSI6dHJ1ZSwiUXVlc3REQiI6dHJ1ZSwiUmVkc2hpZnQiOnRydWUsIlNlbGVjdERCIjp0cnVlLCJTaW5nbGVTdG9yZSI6dHJ1ZSwiU25vd2ZsYWtlIjp0cnVlLCJTUUxpdGUiOnRydWUsIlN0YXJSb2NrcyAodHVuZWQpIjpmYWxzZSwiU3RhclJvY2tzIjp0cnVlLCJUaW1lc2NhbGVEQiAoY29tcHJlc3Npb24pIjp0cnVlLCJUaW1lc2NhbGVEQiI6dHJ1ZX0sInR5cGUiOnsic3RhdGVsZXNzIjp0cnVlLCJtYW5hZ2VkIjp0cnVlLCJKYXZhIjp0cnVlLCJjb2x1bW4tb3JpZW50ZWQiOnRydWUsIkMrKyI6dHJ1ZSwiTXlTUUwgY29tcGF0aWJsZSI6dHJ1ZSwicm93LW9yaWVudGVkIjp0cnVlLCJDIjp0cnVlLCJQb3N0Z3JlU1FMIGNvbXBhdGlibGUiOnRydWUsIkNsaWNrSG91c2UgZGVyaXZhdGl2ZSI6dHJ1ZSwiZW1iZWRkZWQiOnRydWUsIlJ1c3QiOnRydWUsInNlYXJjaCI6dHJ1ZSwiZG9jdW1lbnQiOnRydWUsInRpbWUtc2VyaWVzIjp0cnVlfSwibWFjaGluZSI6eyJzZXJ2ZXJsZXNzIjpmYWxzZSwiMTZhY3UiOmZhbHNlLCJMIjpmYWxzZSwiTSI6ZmFsc2UsIlMiOmZhbHNlLCJYUyI6ZmFsc2UsImM2YS40eGxhcmdlLCA1MDBnYiBncDIiOnRydWUsImM1LjR4bGFyZ2UsIDUwMGdiIGdwMiI6ZmFsc2UsImM2YS5tZXRhbCwgNTAwZ2IgZ3AyIjpmYWxzZSwiMTYgdGhyZWFkcyI6ZmFsc2UsIjIwIHRocmVhZHMiOmZhbHNlLCIyNCB0aHJlYWRzIjpmYWxzZSwiMjggdGhyZWFkcyI6ZmFsc2UsIjMwIHRocmVhZHMiOmZhbHNlLCI0OCB0aHJlYWRzIjpmYWxzZSwibTVkLjI0eGxhcmdlIjpmYWxzZSwiZjE2cyB2MiI6ZmFsc2UsImM2YS40eGxhcmdlLCAxNTAwZ2IgZ3AyIjpmYWxzZSwicmEzLjE2eGxhcmdlIjpmYWxzZSwicmEzLjR4bGFyZ2UiOmZhbHNlLCJyYTMueGxwbHVzIjpmYWxzZSwiUzI0IjpmYWxzZSwiUzIiOmZhbHNlLCIyWEwiOmZhbHNlLCIzWEwiOmZhbHNlLCI0WEwiOmZhbHNlLCJYTCI6ZmFsc2V9LCJjbHVzdGVyX3NpemUiOnsiMSI6dHJ1ZSwiMiI6dHJ1ZSwiNCI6dHJ1ZSwiOCI6dHJ1ZSwiMTIiOnRydWUsIjE2Ijp0cnVlLCIzMiI6dHJ1ZSwiNjQiOnRydWUsIjEyOCI6dHJ1ZSwic2VydmVybGVzcyI6dHJ1ZSwidW5kZWZpbmVkIjp0cnVlfSwibWV0cmljIjoibG9hZCIsInF1ZXJpZXMiOlt0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSx0cnVlXX0=)

**Comment by arjenpdevries** [comment]
So that's more than an order of improvement, impressive!

**Comment by Mytherin** [comment]
The single-threaded results are actually around 1200 seconds, the results on that page are from the previous DuckDB version that would load all data ingested in a single transaction uncompressed in memory prior to writing it out to disk, causing very poor performance when loading CSV files that were larger than memory as is the case in the benchmark (see #4996 for the PR that fixed that).

**Comment by arjenpdevries** [comment]
Still a great improvement!

**Comment by hatvik** [comment]
@pdet So this works with COPY from csv too?

**Comment by jaens** [comment]
Is it possible to load in parallel from multiple CSV files at once?

I am currently using datasets that are partitioned into Zstd-compressed fixed-row-count CSV chunks (since that makes it easy to process in parallel with arbitrary tools eg. just using GNU _parallel_).

**Comment by Alex-Monahan** [comment]
Hello! Using either the glob syntax or passing in a list of files should be run in parallel!

**Pull request merged**
