### PR TITLE
GH Actions: avoid upload on master, and try to fix codecov failures on master

### PR DESCRIPTION
**Pull request by Mytherin**

### CODE REVIEW

**Comment by l1t1** [comment]
when will the mater build restart?

**Comment by Mytherin** [comment]
Not anytime soon, since our current method was resulting in constant test failures we need to rethink this, and since few people are using it it is not a priority.

Can't you use the [build artifacts from the CI runs](https://github.com/duckdb/duckdb/actions/runs/1577461498)?

**Comment by l1t1** [comment]
could you tell me how to use the build artifacts from the CI runs to get the latest binary?

**Comment by l1t1** [comment]
I got it.  thank you.

**Pull request merged**
