### PR TITLE
Support for missing GZIP features (extra field in header and concatenated files) used in BGZF

### PR DESCRIPTION
**Pull request by rsund**
## Background 

Support for reading CSV from [BGZF-formatted GZIP-archives](https://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html) was requested in #6716. BGZF requires a few features for GZIP decompression that were not implemented in DuckDB. BGZF uses these features in order to allow fast random access to the archive for specialized readers keeping the file format still compatible with the [GZIP-specification](https://www.ietf.org/rfc/rfc1952.txt).

## Implementation

The first required feature is an extra field in the GZIP header. That was straightforward to add as it required only checking for extra field flag and then skipping over the field in the file. That worked fine with small example files.

With larger files, however, data was read only partially. That was because BGZF also utilizes the GZIP feature of concatenated archives meaning that in the GZIP specification it is allowed that several GZIP-files are concatenated to one big archive by simply copying them together, e.g. `cat part1.gz part2.gz > concat.gz`.

It was quite straighforward to check that if there is another GZIP in the decompression stream after the extraction of the first part was done. This worked easily as far as the new GZIP header was completely available in the input stream buffer, but that is not always the case. Implementing the header skipping in the edge cases, where more data were needed to input stream buffer during skipping, was more complicated thing to do, especially without touching anything else than the GZIP Read-function.

This PR shows the implementation I was able to put together. During the implementation it became evident that support for GZIP-archives could benefit from some refactoring as e.g. the GZIP-headers must be handled in at least three places (during initialization when reading from file, when new concatenated file is detected during the reading from file stream, and while reading from "stringstream"). I'm, however, feeling that making such larger changes are out of my possibilities and that the current PR is already much larger than I initially thought it would be, because of the edge cases with the input buffer.

I am also somewhat unsure whether my code is following the best practices of DuckDB or C++. I refer especially to the way of using flags and the need for a (currently fixed-size) help buffer to handle the edge cases. In any case, I tried to comment the code so that the logic should be easy to follow.

## Testing

The implementation seems to work fine for the cases I was able to test it with. The problem is that testing requires specially prepared GZIP-files and the ones that introduce edge-cases must be just slightly larger than the size of input buffer. Currently I have included only a few basic tests with small files. If it is OK to include several dummy GZIP files about the size of 32kB to the test data folder, also the edge cases could be tested.

## Real use case

Adding these features allows the reading of VCF-data format (tab-delimited text in GZIPs using BGZF features). Some [real data](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/gambian_genome_variation_project/release/20200217_biallelic_SNV/ALL_GGVP.chrX.shapeit2_integrated_snvindels_v1b_20200120.GRCh38.phased.vcf.gz) are available from e.g. [the International Genome Sample Resource](https://www.internationalgenome.org/faq/how-do-i-find-the-most-up-to-date-data/). That data also triggers some edge cases that require reading more data during header skipping. Just download [the file](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/gambian_genome_variation_project/release/20200217_biallelic_SNV/ALL_GGVP.chrX.shapeit2_integrated_snvindels_v1b_20200120.GRCh38.phased.vcf.gz) and read it with DuckDB: 
```sql
CREATE TABLE bgzf AS SELECT * FROM read_csv_auto('<file>.vcf.gz');
```

## Limitations

This PR implements only the missing GZIP-features required for BGZF. So if the actual uncompressed data is not in the CSV-format, more work is needed to read the data. This is the case e.g. for the BAM format (that was also mentioned in discussion of the feature request) that is a binary format within BGZF archive. Utilization of the enhanced random access reading possibilities would also require more work, the current implementation handles the files in a similar manner than any other GZIP-archives.

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great.

> If it is OK to include several dummy GZIP files about the size of 32kB to the test data folder, also the edge cases could be tested.

Yes, that is fine and adding these tests would be great as there seem to be a lot of edge-cases. It is also possible to write tests using `require httpfs` that read these types of files over a network connection from a different server.

Perhaps @hannes wants to have a look at this PR as well?

**Comment by rsund** [comment]
I realized that the edge cases and the utilization of separate help buffer can be avoided, if it would be possible to "refresh" the input buffer so that the currently remaining part of the buffer is moved to the beginning of the buffer and new input is read from the stream to fill up the buffer. After such "refresh" the header for the next gzip member is always at the beginning of the buffer and the whole buffer can be used for skipping over the header information without the need for reading new data from the stream in "wrong" places (that result in edge cases).

Changing the implementation to use that technique turned out to be relatively straightforward and the code should be much cleaner now. That also eliminates the need for those specially crafted files for testing.

**Comment by Ed2uiz** [comment]
Hey @rsund thanks for working on this. I was eager to try it out in R with the vcf file you linked and a .bam file I have on hand. I cloned your branch and installed the duckdb R package from source. I tried the following commands but I ran into an error. Do you know why this is the case? I'm still rather new to the duckDB and DBI APIs so apologies if I am overlooking something here. 

**Input code:**
```
library(duckdb)
library(dplyr)
vcf = 'ALL_GGVP.chrX.shapeit2_integrated_snvindels_v1b_20200120.GRCh38.phased.vcf'
con <- dbConnect(duckdb(), dbdir = "bam-test-rsund.duckdb")
```

**Error:**
```
> tbl(con, vcf)
Error in `db_query_fields.DBIConnection()`:
! Can't query fields.
Caused by error:
! Parser Error: 
LINE 2: FROM ALL_GGVP.chrX.shapeit2_integra...
             ^
Run `rlang::last_error()` to see where the error occurred.
```

**Session info**
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.0  duckdb_0.7.0 DBI_1.1.3  
```

**Comment by Mytherin** [comment]
> Hey @rsund thanks for working on this. I was eager to try it out in R with the vcf file you linked and a .bam file I have on hand. I cloned your branch and installed the duckdb R package from source. I tried the following commands but I ran into an error. Do you know why this is the case? I'm still rather new to the duckDB and DBI APIs so apologies if I am overlooking something here.
> 
> **Input code:**
> 
> ```
> library(duckdb)
> library(dplyr)
> vcf = 'ALL_GGVP.chrX.shapeit2_integrated_snvindels_v1b_20200120.GRCh38.phased.vcf'
> con <- dbConnect(duckdb(), dbdir = "bam-test-rsund.duckdb")
> ```
> 
> **Error:**
> 
> ```
> > tbl(con, vcf)
> Error in `db_query_fields.DBIConnection()`:
> ! Can't query fields.
> Caused by error:
> ! Parser Error: 
> LINE 2: FROM ALL_GGVP.chrX.shapeit2_integra...
>              ^
> Run `rlang::last_error()` to see where the error occurred.
> ```
> 
> **Session info**
> 
> ```
> > sessionInfo()
> R version 4.2.1 (2022-06-23)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Ventura 13.2.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] dplyr_1.1.0  duckdb_0.7.0 DBI_1.1.3  
> ```

That looks to me like the name is not properly quoted in the R package somewhere - likely unrelated to this PR. Try renaming your file to not contain any dots and retry.

**Comment by rsund** [comment]
If you want to use `tbl`, the following should work:
```r
con <- DBI::dbConnect(duckdb::duckdb())

vcf <- dplyr::tbl(con, "read_csv_auto('ALL_GGVP.chrX.shapeit2_integrated_snvindels_v1b_20200120.GRCh38.phased.vcf', compression='gzip')")

vcf |> dplyr::count()
```

**Comment by rsund** [comment]
> I was eager to try it out in R with the vcf file you linked and a .bam file I have on hand. I cloned your branch and installed the duckdb R package from source. I tried the following commands but I ran into an error. Do you know why this is the case?

 So the vcf-file is essentially a gzipped csv-file  and DuckDB can read such files after the additional features of gzip (in this PR) are supported. You could rename the vcf-file to something like `test-vcf.csv.gz` and it should work directly with your example. That is because DuckDB is then smart enough to recognize that it is not a table in the database and "launch" correct replacement scan.

Or then use the call for `read_csv_auto` instead of table name as in the other responses.


The BAM-file will mist likely give you an error that auto detection of csv columns was unsuccesful. That is because there is no csv within the gzip-archive, but a binary file. At the moment DuckDB is not able to read that binary and support for it should be implemented. That is considerably more work and an own DuckDB extension could be a good option for it.

**Comment by Ed2uiz** [comment]
Thanks @rsund and @Mytherin for the help! It turns out I was incorrectly using the uncompressed file (`*.vcf`). The code you both shared worked when I used the `*.vc.gz` file. 

@rsund I tried a .bam file with your PR and you were right. 
```
bam <- dbGetQuery(con, "SELECT * FROM read_csv_auto('sorted.P3_8_S16_L002.bam', compression='gzip')")
Error: rapi_prepare: Failed to prepare query SELECT * FROM read_csv_auto('sorted.P3_8_S16_L002.bam', compression='gzip')
Error: Invalid Input Error: Error in file "sorted.P3_8_S16_L002.bam": CSV options could not be auto-detected. Consider setting parser options manually.
```

Based on section 4 of the [SAM/BAM Specification](http://samtools.github.io/hts-specs/SAMv1.pdf) also mentioned in #6716     
I was under the impression that this implementation would work with both the .vcf and .bam file 🙈 

>  The goal of BGZF is to provide good compression while allowing efficient random access to the BAM file for indexed queries. The BGZF format is ‘gunzip compatible’, in the sense that a compliant gunzip utility can decompress a BGZF compressed file

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
