### PR TITLE
Feature: Add portable VARIANT format functions

### PR DESCRIPTION
**Pull request by chenxi8611**
I would like to add some functions for portable variant format. 
Actually, this format data is stored in BLOB type.
In this PR, I've added the following functions in excel extension.
These functions convert value type between BLOB type and it's real type.

           VARIANT(value)
           FROM_VARIANT(type, value)

For example, from the following dataset:

          `name`        `vf`
          tom            4
          alex           'abc'
          sarah         [1,2,3]
          bruno         {'x':4, 'y':'def'}

Make a table as following:

        CREATE TABLE example (name VARCHAR, vf BLOB);
        INSERT INTO example VALUES ('tom', VARIANT(4));
        INSERT INTO example VALUES ('alex', VARIANT('abc'));
        INSERT INTO example VALUES ('sarah', VARIANT([1,2,3]));
        INSERT INTO example VALUES ('bruno', VARIANT({'x':4, 'y':'def'}));

Being able to run queries like:

        SELECT * FROM (SELECT name, FROM_VARIANT('INTEGER', vf) AS vv FROM example) WHERE vv = 4;
        ----
        tom	4

        SELECT FROM_VARIANT('VARCHAR', vf) FROM example WHERE name = 'alex';
        ----
        abc

        SELECT * FROM (SELECT FROM_VARIANT('INTEGER[]', vf) AS va FROM example) WHERE va[1] = 1;
        ----
        [1, 2, 3]

        SELECT st.y FROM (SELECT FROM_VARIANT('STRUCT(x INTEGER, y VARCHAR)', vf) AS st FROM example) WHERE st.x = 4;
        ----
        def

@Mytherin -- please review it.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

The point of this function is to be able to store different data types in one column, correct?

I have a number of issues with the current implementation:

* This is using functions for something that should really be a type
* This is introducing *a lot* of code that does not seem safe, i.e. this seems like it could easily crash the system if you use wrong types or wrong data
* This is in the Excel extension, which does not seem like a good place for this

We have talked about adding a type like this before (`ANY`). But that should be implemented in the core system, be completely safe (you should never be able to crash the system from within SQL), and be more elegant to use (it should work using normal casts, have support for auto-casting to different types, throw errors when mis-used, work smoothly in storage, etc).

As it stands I'm not too keen on merging this into the main repository - this would need to be largely rewritten. Now that we have support for external extensions, perhaps it would be a good idea to move the Excel extension outside of the main repository? That way you would be able to add this functionality to the extension separate from the main repository, and we would not need to take over maintenance or responsibility for the code.

**Comment by chenxi8611** [comment]
Thanks for your review, I have a question.
What do you mean external extension? How do I use it?
Variant functions are independent of Excel extension, so I can move these functions from Excel extension to external extension as you pointed.

**Comment by Mytherin** [comment]
The excel extension is already a separate extension, but it is just stored inline in the tree. It is also possible to build extensions entirely separately, so they can be stored in e.g. their own github repository. For example, see [the example here](https://github.com/duckdb/duckdb/tree/master/test/extension). The extension can be loaded using the `LOAD` command, e.g.:

```sql
-- load directly from file
LOAD '__BUILD_DIRECTORY__/test/extension/loadable_extension_demo.duckdb_extension';

```

**Comment by chenxi8611** [comment]
Okay, but I think it is better to implement separate extension stored inline in the tree (for example, "variant" extension). How do you think about that? For code safety, I will add exception process as many as possible so that don't easily crash the system.

**Pull request closed without merging**
