### PR TITLE
Add support for SQL-level variables

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds support for SQL level variables that can be set using the `SET VARIABLE` statement, e.g.:

```sql
SET VARIABLE my_variable = 'value';
```

Variables can have any type - including nested types. They can be used in subsequent queries using the `getvariable` function, e.g.:

```sql
D SELECT getvariable('my_variable') AS result;
┌─────────┐
│ result  │
│ varchar │
├─────────┤
│ value   │
└─────────┘
```

We can list all of the variables using the `SHOW VARIABLES` command, or the `duckdb_variables()` function, e.g.:

```sql
SHOW VARIABLES;
┌─────────────┬─────────┬─────────┐
│    name     │  value  │  type   │
│   varchar   │ varchar │ varchar │
├─────────────┼─────────┼─────────┤
│ my_variable │ value   │ VARCHAR │
└─────────────┴─────────┴─────────┘
```

We can remove specific variables again using the `RESET VARIABLE` statement.

```sql
RESET VARIABLE my_variable;
```

Variables are expanded to constants during bind time. This is useful as this allows them to be used in places where only constants can be used. For example, we can use variables to read a list of CSV files that is stored in a table, e.g.:

```sql
-- write some CSV files
COPY (SELECT 42 AS a) TO 'test.csv';
COPY (SELECT 84 AS a) TO 'test2.csv';

-- add a list of CSV files to a table
CREATE TABLE csv_files(file VARCHAR);
INSERT INTO csv_files VALUES ('test.csv'), ('test2.csv');

-- initialize a variable with the list of csv files
SET VARIABLE list_of_files = (SELECT LIST(file) FROM csv_files);

-- read the CSV files
D SELECT * FROM read_csv(getvariable('list_of_files'), filename := True);
┌───────┬───────────┐
│   a   │ filename  │
│ int64 │  varchar  │
├───────┼───────────┤
│    42 │ test.csv  │
│    84 │ test2.csv │
└───────┴───────────┘
```

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Yes!!!!!! Thank you!

**Comment by hamilton** [comment]
Amazing! Given that this swaps in a constant for the variable function, will this give the correct `query_location` in the AST? Other rewrites do not seem to (I'll file an issue for that separately), so it'd be great if possible to make sure the location reflects the actual function in the query rather than a null sequence.

**Comment by Mytherin** [comment]
> Amazing! Given that this swaps in a constant for the variable function, will this give the correct `query_location` in the JSON serialized AST? Other rewrites do not seem to (I'll file an issue for that separately, I have a list), so it'd be great if possible to make sure the location reflects the actual function in the query rather than a null sequence.

I haven't checked - but that's somewhat orthogonal to the implementation here. If you can file an issue with more details we can definitely take a look.

**Comment by liquidcarbon** [comment]
This is awesome.

The example with filenames in v1.1 announcement is effectively equivalent to\
`FROM tbl, read_csv(tbl.file)` from #12505 or
`FROM table JOIN read_parquet(table.uri)` from #13750 

Would you consider adopting this syntax with SQL-level variables to unlock these "lateral joins"?

**Comment by liquidcarbon** [comment]
Thank you!  For my curiosity and education: how is the issue of knowing the schema in `FROM tbl, read_csv(tbl.file)` different from not knowing the schema in `FROM read_csv(getvariable('list_of_files'))`?  Which, presumably, would not be a problem to expand to `FROM read_csv(get_variable(...)) x JOIN y USING (a)` ?


Can a `FROM tbl, read_csv(tbl.file)` query be pre-processed, before executing anything, into `SET VARIABLE + getvariable` format?  Aren't there already queries that execute in stages?

**Comment by liquidcarbon** [comment]
Thank you very much for the explanation.  And for the feature :)

**Pull request merged**
