### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Realted to #1677. @hannesmuehleisen  could you please review this PR?

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Looks great, one small issue remains however that we are deploying the src tarball twice. Could you please address that?

**Comment by odidev** [comment]
@hannesmuehleisen Could you please have a look at this PR? Thanks in advance.

**Comment by Mytherin** [comment]
It seems that [this PR introduces a test failure here](https://github.com/duckdb/duckdb/pull/1678/checks?check_run_id=2692212845). There are some more test failures, but I am not sure if they are related to this PR.

**Comment by odidev** [comment]
> It seems that [this PR introduces a test failure here](https://github.com/duckdb/duckdb/pull/1678/checks?check_run_id=2692212845). There are some more test failures, but I am not sure if they are related to this PR.

Done.

**Review by Mytherin — APPROVED** [review]

**Pull request merged**
