### PR TITLE
Enhance bound parameters error message

### PR DESCRIPTION
**Pull request by michaeljohnalbers**
Small enhancement to provide some extra details when bound parameter types are inconsistent.

### CODE REVIEW

**Comment by hannes** [comment]
can you run `make format-fix` please?

**Comment by michaeljohnalbers** [comment]
> can you run `make format-fix` please?

Fixed

**Comment by michaeljohnalbers** [comment]
I'm not sure why the format check is failing. I've ran `make format-fix` and it makes no changes.

**Comment by Mytherin** [comment]
It's unrelated to your PR - this was an invisible merge conflict caused by a change to the format script (#3900) not being run on an older PR.

**Pull request merged**
