### PR TITLE
[R-package] updated handling of dependencies in the R package

### PR DESCRIPTION
**Pull request by jameslamb**
This is an awesome project! I heard about DuckDB earlier this week and I'm really excited about what it might be able to do.

I think that I can help with the project's R package. I hope you'll consider this PR as a start.

In this PR, I cleaned up the handling of R dependencies in the package to get them in line with the standards that CRAN enforces.

1. Added explicit `importFrom` statements to automatically generate imports in `NAMESPACE`
2. moved `testthat` out of `Imports` dependencies so users don't have build it
3. added roxygen for dynamic library registration so the `NAMESPACE` file can safely be automatically generated by `roxygen2::roxygenize()` or `devtools::document()`

Please let me know if you have any questions about these proposed changes.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Thanks for your PR, it seems the tests fail at the moment. Could you have a look?

**Comment by hannesmuehleisen** [comment]
@jameslamb could you have a look please?

**Comment by jameslamb** [comment]
Apologies for the delay. I took a look tonight and could not understand how the code in `tools/rpkg/tests/` works, so I have reverted the changes to `dbBind()` and added `testthat` back to `Imports` in `DESCRIPTION`.

Why have you chosen to pull down the `dbplyr` source at test time? In my opinion this makes it very difficult for contributors to reason about the tests and debug issues like this in CI.

[RPostgreSQL](https://github.com/r-dbi/RPostgres/tree/master/tests/testthat) and [RMariaDB](https://github.com/r-dbi/RMariaDB/tree/master/tests), to name two examples, have been able to build DBI-compliant R packages with `DBItest` and self-contained testing code.

**Comment by hannesmuehleisen** [comment]
> Why have you chosen to pull down the `dbplyr` source at test time? In my opinion this makes it very difficult for contributors to reason about the tests and debug issues like this in CI.

Because we want to run _their_ tests? Do you have a better way of doing that?

**Comment by jameslamb** [comment]
> > Why have you chosen to pull down the `dbplyr` source at test time? In my opinion this makes it very difficult for contributors to reason about the tests and debug issues like this in CI.
> 
> Because we want to run _their_ tests? Do you have a better way of doing that?

I do not have a better way. Why does this project's R package use `dbplyr`'s tests instead of implementing its own?

Apologies if the answer is obvious to you. [I did not see any documentation in this project](https://github.com/cwida/duckdb/search?q=dbplyr&unscoped_q=dbplyr) that `duckdb`'s R package wants to be a drop-in replacement for `dbplyr` or any explicit mention of `dbplyr`.

**Comment by hannesmuehleisen** [comment]
> Apologies if the answer is obvious to you. [I did not see any documentation in this project](https://github.com/cwida/duckdb/search?q=dbplyr&unscoped_q=dbplyr) that `duckdb`'s R package wants to be a drop-in replacement for `dbplyr` or any explicit mention of `dbplyr`.

No problem, what we want to ensure is that DuckDB can run the SQL queries that dbplyr generates. There is no specific adaption because none is needed, dbplyr can work with "vanilla" DBI connections.

**Comment by jameslamb** [comment]
> > Apologies if the answer is obvious to you. [I did not see any documentation in this project](https://github.com/cwida/duckdb/search?q=dbplyr&unscoped_q=dbplyr) that `duckdb`'s R package wants to be a drop-in replacement for `dbplyr` or any explicit mention of `dbplyr`.
> 
> No problem, what we want to ensure is that DuckDB can run the SQL queries that dbplyr generates. There is no specific adaption because none is needed, dbplyr can work with "vanilla" DBI connections.

ah ok, makes sense! I think it would be valuable to document that in `CONTRIBUTING.md`. I also think you will want to change the process to move that logic out of `testthat.R` and into some kind of setup script that is run only in CI. If you intend to eventually distribute this package via CRAN, I think you will find that the CRAN maintainers are not happy with files being downloaded from the internet at test time.

Thanks for taking the time to answer my questions. I will keep an eye on Travis here and be sure to get this PR working. I'm really curious about `duckdb` and I'd like to keep working on the R package.

**Comment by hannesmuehleisen** [comment]
Thanks!

**Pull request merged**
