### PR TITLE
Issue #6027: Explicit ROW_GROUP_SIZE no longer breaks IMPORT/EXPORT round-trip

### LINKED ISSUE #6027: Export/Import issue regarding parquet and ROW_GROUP_SIZE
### What happens?

When try to export with the next command:

EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
the 
IMPORT is not working.

This is a very minor issue
I only want to point out this

See reproduce section:

### To Reproduce

> EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);

The import is not working

> import database 'target_directory';
Error: Not implemented Error: Unsupported option for COPY FROM parquet: ROW_GROUP_SIZE

A workaround is to edit the 'load.sql'  command and remove the ROW_GROUP_SIZE

### OS:

Ubuntu 22.04

### DuckDB Version:

0.61

### DuckDB Client:

duckdb client

### Full Name:

Bert Tijhuis

### Affiliation:

Private interest in this project

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by jmeulemans**
fixes #6027

### CODE REVIEW

**Comment by Tishj** [comment]
The title for your PR is a little confusing, but after looking at the linked issue I get it.

Thanks for fixing this, if you put `fixes #6027` in the description it will actually auto-close when this gets merged, now it's just a mention

**Comment by jmeulemans** [comment]
> Maybe a better title would be: `explicit ROW_GROUP_SIZE no longer breaks IMPORT/EXPORT round-trip`

Thanks that's much better

**Comment by hannes** [comment]
Thanks for the fix

**Comment by BertTijhuis** [comment]
Thanks for resolving this issue

**Pull request merged**
