### PR TITLE
[Block Size] String block limit and a few other places

### PR DESCRIPTION
**Pull request by taniabogatsch**
As the PR title says, this PR removes the `STRING_BLOCK_LIMIT` constant by adapting it to the block size.

@samansmink, I ran all benchmarks in `benchmark/micro/compression/fsst*`, and did not notice a regression. So I assume reusing the same `vector` does not impact performance.

Note that there also a few other places in this PR where I removed `*_BLOCK_SIZE`

### CODE REVIEW

**Comment by taniabogatsch** [comment]
Nightly passed before merging the latest `main` branch: https://github.com/taniabogatsch/duckdb/actions/runs/9614995377. But I'll rerun with the latest version of this PR.

**Review by samansmink — APPROVED** [review]
looks good to me!

**Comment by taniabogatsch** [comment]
Latest nightly run: https://github.com/taniabogatsch/duckdb/actions/runs/9642358450

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
