### PR TITLE
R: Implement dbBind() according to specification

### LINKED ISSUE #741: R: Fix DBItest tests
https://github.com/cwida/duckdb/pull/738/commits/7b610e930071eb90fd3721d5cc358e9f88d7a92c and others.

### PR DESCRIPTION
**Pull request by krlmlr**
- Behavior in corner cases
- Multiple parameter sets

Contains #2119.

Closes #741.

### CODE REVIEW

**Comment by krlmlr** [comment]
This is now blocked by #2134, planning to reuse code from there.

**Comment by krlmlr** [comment]
I suspect we can remove the factor handling from the C++ code now, unless there are reasons to keep it there. Let's earmark this for a future pull request.

**Comment by krlmlr** [comment]
I have no idea why the checks are failing. Tests succeed on the Mac M1. Will try on Linux.

**Comment by krlmlr** [comment]
The Python failure is likely unrelated, rerunning just to be sure.

**Review by Mytherin — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks, looks good!

**Pull request merged**
