### PR TITLE
Support root type on expressions #4278

### LINKED ISSUE #4278: [substrait] Missing required field `root_type`
### What happens?

Serializing `SELECT l_suppkey FROM lineitem LIMIT 10` to substrait the required field `root_type` is missing from the message `Expression.FieldReference`

The full Substrait plan from `duckdb`:
```
relations {
  root {
    input {
      fetch {
        input {
          project {
            input {
              project {
                input {
                  read {
                    base_schema {
                      names: "l_orderkey"
                      names: "l_partkey"
                      names: "l_suppkey"
                      names: "l_linenumber"
                      names: "l_quantity"
                      names: "l_extendedprice"
                      names: "l_discount"
                      names: "l_tax"
                      names: "l_returnflag"
                      names: "l_linestatus"
                      names: "l_shipdate"
                      names: "l_commitdate"
                      names: "l_receiptdate"
                      names: "l_shipinstruct"
                      names: "l_shipmode"
                      names: "l_comment"
                    }
                    named_table {
                      names: "lineitem"
                    }
                  }
                }
                expressions {
                  selection {
                    direct_reference {
                      struct_field {
                        field: 2
                      }
                    }
                  }
                }
              }
            }
            expressions {
              selection {
                direct_reference {
                  struct_field {
                  }
                }
              }
            }
          }
        }
        count: 10
      }
    }
    names: "l_suppkey"
  }
}
```

The `FieldReference` has a second required field `root_type` defined as 

```
    // Whether this reference has an origin of a root struct or is based on the
    // ouput of an expression. When this is a RootReference and direct_reference
    // above is used, the direct_reference must be of a type StructField.
    oneof root_type {
      Expression expression = 3;
      RootReference root_reference = 4;
      OuterReference outer_reference = 5;
    }
```
https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L849-L856

Possibly unrelated but there also seems to be an additional layer of nesting that I don't think is required (`project->input->project->input`) and an empty `direct_reference`? (This is probably showing empty if the value is set to 0)

### To Reproduce

```sh
pip install duckdb==0.4.1.dev1155 ibis-substrait
```

```python
import duckdb
con = duckdb.connect()
con.execute("CALL dbgen(sf=0.1)")
con.install_extension("substrait")
con.load_extension("substrait")

out = con.get_substrait("select l_suppkey from lineitem limit 10;").fetchone()[0]

from ibis_substrait.proto.substrait import plan_pb2

plan = plan_pb2.Plan().FromString(out)
```

### OS:

Arch Linux

### DuckDB Version:

0.4.1-dev1155

### DuckDB Client:

Python

### Full Name:

Gil Forsyth

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
Fix: #4278 

@gforsyth can you confirm this is the intended behavior?

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @pdet  -- this looks correct to me!  And the substrait-validator likes the output (there's one error but that error is currently raised by every single substrait producer in existence and it's a non-issue for now)

**Comment by pdet** [comment]
Oh I remember the discussion about the validator, is it open-sourced? Maybe it's worth to see if we can integrate it in our testing suite :-)

**Comment by gforsyth** [comment]
yes!  it's here and is also available on pypi: https://github.com/substrait-io/substrait-validator

**Comment by pdet** [comment]
Cool! Ill have a look on it next week! Thanks for sharing! :-)

**Pull request merged**
