### PR TITLE
More extensive SQLLogicTest testing, and temporarily disable OR pushdown

### LINKED ISSUE #3659: different query results with optimizer on vs. off
#### What happens?
Working with @tiagokepe on ODBC driver in Windows. After running SQLite SqlLogicTests found a few queries that produced incorrect results:

```
SELECT pk FROM tab0 WHERE (col0 BETWEEN 67 AND 0 OR col0 > 17 AND (col0 > 3));
SELECT pk FROM tab0 WHERE 84 > col0 OR 8 > col0 ;
```

Disabling the optimizer gives the correct result. Also changing the order of the elements in the where clause can produce the correct result. See the attached sql script files for more details. 

#### To Reproduce
Attached are two SQL query script files. Open a CMD window and feed them to duckdb and each will generate an output txt file which are also attached.

```
duckdb < duckdb_issues_between.sql
duckdb < duckdb_issues_between.sql
```

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version:
```
┌─────────────────┬───────────┐
│ library_version │ source_id │
├─────────────────┼───────────┤
│ v0.3.5-dev164   │ e4ba94a4f │
└─────────────────┴───────────┘
```
 - DuckDB Client: command line

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
Yes.
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
Yes see attached .sql files. Note that I had to add .txt extension to upload to github. 

[duckdb_issues_between.sql.txt](https://github.com/duckdb/duckdb/files/8705268/duckdb_issues_between.sql.txt)
[duckdb_issues_comparison.sql.txt](https://github.com/duckdb/duckdb/files/8705269/duckdb_issues_comparison.sql.txt)
[between_issue.txt](https://github.com/duckdb/duckdb/files/8705283/between_issue.txt)
[comparison.txt](https://github.com/duckdb/duckdb/files/8705284/comparison.txt)

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #3659

* Enable many more SQLLogicTests - now that DuckDB has greatly expanded its functionality we don't need to disable quite as many tests
* For SQLLogicTests, pretend we are Postgres (by respecting `skipif postgresql` and `onlyif postgresql`). This allows us to run more tests that would otherwise need to be skipped because of SQLite implicitly adding the `FIRST` aggregate in the case of missing `GROUP BY` columns
* Run most SQLLogicTests with query verification enabled
* For query verification, sort both sides before doing the comparison between e.g. the unoptimized/optimized results
* Temporarily disable OR pushdown, since it is causing several problems in the SQLLogicTests
* Statistics propagation optimization for conjunctions

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Hey @Mytherin! One quick question on this. How impactful / in how many cases does the OR pushdown produce incorrect results? We are almost ready to upgrade production to 0.3.4,  but I'm wondering if we should wait for 0.3.5?

**Comment by Mytherin** [comment]
This bug occurs if you have multiple comparison predicates on the same column, e.g. queries in the form of `col1 > 5 OR col1 < 7`. In general it will still handle most correctly, but e.g. flipping the comparison causes problems (`5 < col1 OR 7 > col1`) and there are some problems with nested conjunctions on the same column being executed in an incorrect ordered (e.g. `(col1 > 5 OR col1 < 7) AND col1 > 4` might be executed as `col1 > 5 OR (col1 < 7 AND col1 > 4)`). So far I have only encountered this in generated tests, but it might be wise to see if you have any queries that have such predicates before upgrading.

**Comment by Alex-Monahan-Intel** [comment]
> This bug occurs if you have multiple comparison predicates on the same column, e.g. queries in the form of `col1 > 5 OR col1 < 7`. In general it will still handle most correctly, but e.g. flipping the comparison causes problems (`5 < col1 OR 7 > col1`) and there are some problems with nested conjunctions on the same column being executed in an incorrect ordered (e.g. `(col1 > 5 OR col1 < 7) AND col1 > 4` might be executed as `col1 > 5 OR (col1 < 7 AND col1 > 4)`). So far I have only encountered this in generated tests, but it might be wise to see if you have any queries that have such predicates before upgrading.

Thanks @Mytherin! One additional question... Does this only apply to inequality comparisons, or are equality comparisons also at risk? Ex:
```sql
select * from table where col1 = 2 or col1 = 5
```

**Comment by Mytherin** [comment]
Equality operators should be unaffected since flipping an equality operator is still an equality. The re-ordering might still happen in case of complex predicates (e.g. `(col1=2 OR (col1=5 AND col1=7)`) - but these types of complex predicates don't make much sense with equality anyway.

Like should be unaffected as well.

**Pull request merged**
