### PR TITLE
[Map] Map extract now properly uses the selection vectors of the `map` and `key` vectors

### LINKED ISSUE #4602: map[entry] return uncorrect result with "where" filter
### What happens?

map[entry] return uncorrect result with where filter:

```
select c1,v_map[k1][1] from t1  where c1> '2022-09-13'::date limit 10; 
```

it retrun empty value, but has value correctly. 

### To Reproduce

```
create table t1 (c1 date, k double[], v_map map(double, double)); 

insert into t1 
select c1, k, map(k, [random()*100,random()*100,random()*100,random()*100]) from 
( select  '2022-09-05'::date+(generate_series||' days')::interval as c1, 
[random()*100,random()*100,random()*100,random()*100] as k from generate_series(1,10000)
) t; 

select * from t1 limit 10; 
┌────────────┬────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│     c1     │                                       k                                        │                                       v_map                                        │
├────────────┼────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 2022-09-06 │ [82.17582534583654, 66.05622085417998, 39.07450315055309, 31.323415397508864]  │ {82.17582534583654=87.61564132003478, 66.05622085417998=43.33306938487409, 39.0... │
│ 2022-09-07 │ [28.769135318875577, 9.405185936345994, 73.94851133552113, 73.22148870984593]  │ {28.769135318875577=44.95443383812775, 9.405185936345994=99.80066651473769, 73.... │
│ 2022-09-08 │ [39.08535764531357, 82.68013752128, 31.026140281703825, 19.833194166383052]    │ {39.08535764531357=18.223565844405343, 82.68013752128=1.428188872856132, 31.026... │
│ 2022-09-09 │ [60.39429494654627, 31.0045225617952, 17.507085510880476, 93.31996564132162]   │ {60.39429494654627=12.308044268821376, 31.0045225617952=35.48072027868608, 17.5... │
│ 2022-09-10 │ [3.473523027141002, 24.658681923676905, 65.49516650044713, 72.20609548320205]  │ {3.473523027141002=72.03497911617974, 24.658681923676905=2.0152159039897883, 65... │
│ 2022-09-11 │ [98.1960644475641, 57.08468606627656, 76.35395451829628, 48.25278335443064]    │ {98.1960644475641=67.73236788989333, 57.08468606627656=33.13701370105544, 76.35... │
│ 2022-09-12 │ [96.87780395543152, 36.95240568764331, 84.76455690915803, 6.933931798425953]   │ {96.87780395543152=23.912184178808747, 36.95240568764331=45.9833704507871, 84.7... │
│ 2022-09-13 │ [54.40724234897812, 9.684392951821069, 12.837071021282364, 72.66230158802641]  │ {54.40724234897812=79.91778463588976, 9.684392951821069=86.49568115046613, 12.8... │
│ 2022-09-14 │ [73.11804431330367, 63.8459843732058, 0.4215751077098714, 7.315747720961401]   │ {73.11804431330367=72.78649596795125, 63.8459843732058=79.24279951938493, 0.421... │
│ 2022-09-15 │ [91.85159082800419, 7.1300141297117845, 45.744982209462904, 25.67358902321979] │ {91.85159082800419=24.709493137129932, 7.1300141297117845=54.1685098675472, 45.... │
└────────────┴────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘



select c1,v_map[array_sort(k,'DESC','NULLS LAST')[1]][1] from t1 limit 20;
┌────────────┬──────────────────────────────────────────────────┐
│     c1     │ v_map[array_sort(k, 'DESC', 'NULLS LAST')[1]][1] │
├────────────┼──────────────────────────────────────────────────┤
│ 2022-09-06 │ 40.62733066748533                                │
│ 2022-09-07 │ 99.3293300735134                                 │
│ 2022-09-08 │ 43.52874887258018                                │
│ 2022-09-09 │ 0.47893354214703043                              │
│ 2022-09-10 │ 50.447510753396784                               │
│ 2022-09-11 │ 7.450213378167295                                │
│ 2022-09-12 │ 55.02208286314786                                │
│ 2022-09-13 │ 1.9157652980451856                               │
│ 2022-09-14 │ 20.58395930113829                                │
│ 2022-09-15 │ 9.982456408902642                                │
│ 2022-09-16 │ 62.04548395752103                                │
│ 2022-09-17 │ 79.87326723054827                                │
│ 2022-09-18 │ 60.37558050834937                                │
│ 2022-09-19 │ 70.41631843205921                                │
│ 2022-09-20 │ 77.04330542521627                                │
│ 2022-09-21 │ 61.96975073823001                                │
│ 2022-09-22 │ 66.90977475766786                                │
│ 2022-09-23 │ 23.912062175551444                               │
│ 2022-09-24 │ 82.00998971751193                                │
│ 2022-09-25 │ 44.830818182050905                               │
└────────────┴──────────────────────────────────────────────────┘


select c1,v_map[array_sort(k,'DESC','NULLS LAST')[1]][1] from t1  where c1> '2022-09-13'::date limit 10; 
┌────────────┬──────────────────────────────────────────────────┐
│     c1     │ v_map[array_sort(k, 'DESC', 'NULLS LAST')[1]][1] │
├────────────┼──────────────────────────────────────────────────┤
│ 2022-09-14 │                                                  │
│ 2022-09-15 │                                                  │
│ 2022-09-16 │                                                  │
│ 2022-09-17 │                                                  │
│ 2022-09-18 │                                                  │
│ 2022-09-19 │                                                  │
│ 2022-09-20 │                                                  │
│ 2022-09-21 │                                                  │
│ 2022-09-22 │                                                  │
│ 2022-09-23 │                                                  │
└────────────┴──────────────────────────────────────────────────┘
```

also has problem in below: 
```
drop table t1;
create table t1 (c1 date, k double[], k1 double, v_map map(double, double)); 

insert into t1 (c1,k,v_map)
select c1, k, map(k, [random()*100,random()*100,random()*100,random()*100]) from 
( select  '2022-09-05'::date+(generate_series||' days')::interval as c1, 
[random()*100,random()*100,random()*100,random()*100] as k from generate_series(1,10000)
) t; 

update t1 set k1=array_sort(k,'DESC','NULLS LAST')[1] ;


select c1,v_map[array_sort(k,'DESC','NULLS LAST')[1]][1] from t1 limit 20;
select c1,v_map[k1][1] from t1  where c1> '2022-09-13'::date limit 10; 
```

### OS:

MacOS

### DuckDB Version:

0.4.1-dev commit_id: 109f932c41fba9d61189e01ab0e5496cb9749506

### DuckDB Client:

CLI

### Full Name:

Digoal Zhou

### Affiliation:

Alibaba

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4602

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! LGTM. Much improved with the addition of the `MapVector`.

**Comment by Mytherin** [comment]
Looks like there are still some issues remaining with the vector sizes test, could you have a look?

**Comment by Tishj** [comment]
Hmm it looks like the issue is somewhere else
the filter cuts off the keys in the map, but not in the right way
if the filter is meant to remove 4 rows, it's removing 4 rows from the child vector, not 4 list entries worth of rows

**Comment by Mytherin** [comment]
Hm, very strange. I will investigate.

**Comment by Tishj** [comment]
@Mytherin 
@taniabogatsch helped me, it's a bug in the optimizer, the filter is optimized away somehow

**Comment by Mytherin** [comment]
The filter is not optimized away but pushed into the scan (which is not correctly printed in the explain - side issue :)). There seems to be a bug in the execution of pushed down filters on structs of lists unrelated to the map type specifically. I am having a go at fixing that now.

**Comment by Mytherin** [comment]
Should be fixed in #4736, perhaps merge with that changeset and see if that fixes the problem here as well?

**Pull request merged**
