### PR TITLE
Add function for non-bias-corrected kurtosis

### PR DESCRIPTION
**Pull request by david-cortes**
This PR adds a version of kurtosis calculated without applying a bias correction according to sample size, named as "kurtosis_pop" like there is a "var_pop".

In order to verify that the numbers are actually correct, one can compare against for example `scipy.stats.kurtosis` with argument `bias=True` (which is the default there).

### CODE REVIEW

**Comment by carlopi** [comment]
Bias kurtosis should not be defined for any positive sample size? Not sure, but given there is no `/ ((n-1) * (n-2) * (n-3))`, formula seems to make sense for every value of `n` >= 1.

**Comment by david-cortes** [comment]
> Bias kurtosis should not be defined for any positive sample size?
> 
> Not sure, but given there is no `/ ((n-1) * (n-2) * (n-3))`, formula seems to make sense for every value of `n` >= 1.

Not quite. You could expand the formula to express it in terms of sums of powers from 1 to 4 plus the count, and see that if there's only 1 observation, it would lead to a division by zero.

**Comment by carlopi** [comment]
How about `n == 2` or `n == 3`?

```python
import scipy
a = scipy.stats.kurtosis([1,2], bias=True)
print (a)
```

**Comment by david-cortes** [comment]
> I stand corrected for `n == 1`. How about `n == 2` and `n == 3`?
> 
> ```python
> import scipy
> a = scipy.stats.kurtosis([1,2], bias=True)
> print (a)
> ```

Yes, that makes sense. I've updated the PR to output non-null values on `1 < n < 3` for the non-bias-corrected version.

**Comment by carlopi** [comment]
Given how currently CI works, PR get automatically downgraded to draft on any change, so you need to resubmit for evaluation by pressing "Ready for review" button in the web UI

**Comment by david-cortes** [comment]
> Given how currently CI works, PR get automatically downgraded to draft on any change, so you need to resubmit for evaluation by pressing "Ready for review" button in the web UI

Thanks for the hint. Clicked that button now.

**Comment by david-cortes** [comment]
I'm not sure how to fix the linter check. Running `make format-fix` resulted in the code that was commited here, but the linter is still not happy.

**Comment by carlopi** [comment]
I think the Windows CI failure was a random network failure, and the CodeQuality ones requires to add the relevant function to `src/core_functions/aggregate/distributive/functions.json` and then do `make generate-files`.

**Comment by carlopi** [comment]
Could you also rebase on main?

**Comment by david-cortes** [comment]
Thanks for the tips. Added the new function to the JSON file and ran `make generate-files`, but this call to `make generate-files` didn't modify any files. Rebased from the latest master too.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
