### PR TITLE
TPC-H: Use BIGINT for ID fields schema where required by the specification

### LINKED ISSUE #11339: The upper limit of the data type in the tpc-h table is not sufficient, resulting in a negative result set
### What happens?

The upper limit of the data type in the tpc-h table is not sufficient, resulting in a negative result set. When generating TPC-H test data, a negative result set will be generated when SF exceeds 358.

### To Reproduce

```sql
CALL dbgen(sf=1000, children=1000, step=358);
select o_orderkey from orders where o_orderkey < 0 limit 3;
```
```text
┌─────────────┐
│ o_orderkey  │
│    int32    │
├─────────────┤
│ -2146967295 │
│ -2146967294 │
│ -2146967293 │
└─────────────┘
```

### OS:

centos 8.x

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

v0.10.0 20b1486d11

### Full Name:

Yejr

### Affiliation:

GreatSQL

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #11339

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! LGTM

**Comment by szarnyasg** [comment]
Hold on, it still gets cast to int32 somewhere, resulting in negative numbers. Will investigate.

**Comment by Mytherin** [comment]
Probably in `append_value`:
```
void append_value(tpch_append_information &info, int32_t value) {
	info.appender->Append<int32_t>(value);
}
```

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
