### PR TITLE
refactor(fsspec): remove seekable flag

### PR DESCRIPTION
**Pull request by Mause**
no longer required due to https://github.com/fsspec/filesystem_spec/pull/1186

### CODE REVIEW

**Comment by Mause** [comment]
Requires https://github.com/duckdb/duckdb/pull/6582

**Comment by Mause** [comment]
> Will removing this flag cause issues for people that do not have the latest version of fsspec?

It will only affect people who use the ArrowFSWrapper class (who would have to work around the other bug in fsspec anyway), but there's no harm in leaving the flag in for now

**Comment by Mause** [comment]
@Mytherin I've reopened this as I've found some fsspec filesystems that throw an error if they get an unexpected keyword parameter

**Review by Mytherin — APPROVED** [review]
Alright - I think we can safely remove it now as well

**Pull request merged**
