### PR TITLE
 Arrow_scan using an exported RecordBatchReader of the C++ Arrow library

### PR DESCRIPTION
**Pull request by pdet**
This PR finalizes @ankoh test and adds it to the  CI.

The arrow compilation was conflicting with ccaches, if removing them is too bad, I can do the arrow test separately from the main Linux debug.

### CODE REVIEW

**Comment by pdet** [comment]
@ankoh, please let me know if I missed something :)

**Comment by ankoh** [comment]
Ah perfect. The `ArrowArrayStreamWrapper` looks good, thank you!

**Comment by ankoh** [comment]
Resolves https://github.com/duckdb/duckdb/issues/1760.

**Review by ankoh — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks, looks good to me.

**Pull request merged**
