### PR TITLE
Avoid amalgamation for R package

### PR DESCRIPTION
**Pull request by krlmlr**
to enable 32-bit builds later on.

Addresses #767.

Includes #763.

### CODE REVIEW

**Comment by krlmlr** [comment]
@hannesmuehleisen How do I build the Parquet extension without amalgamation?

**Comment by hannesmuehleisen** [comment]
Not sure this is a way we'd like to fix this. I have already started addressing this in a different way, by making separate amalgamations for src/ and third_party in the multipartamalgamation branch

**Comment by krlmlr** [comment]
What are the benefits of the amalgamation?

**Comment by hannesmuehleisen** [comment]
Enables additional optimisations by the compiler, see also here: https://www.sqlite.org/amalgamation.html

**Comment by krlmlr** [comment]
Is this still measureable with a modern compiler?

Anyway, looking forward to the improved amalgamation. The C++ compiler exits at ~50k lines of code when I tried it, does the new approach remain below that mark per source file?

**Pull request closed without merging**
