### PR TITLE
 fixes sqlite3_column_bytes nullptr access on some call ordering

### PR DESCRIPTION
**Pull request by TinyTinni**
This fixes sqlite3_column_bytes when the function is called before sqlite3_column_text or sqlite3_column_blob was called. In this case, the pointer to "current_text" is zero. The 2 functions initialize the "current_text" member variable and buffers the result in there.

Also, the return value was changed to match the sqlite return value of a NULL result. From the sqlite doc: "If the result is NULL, then sqlite3_column_bytes() returns zero."  [1]

Also from the sqlite documentation, it says that the "safest" way is to call the functions in a specific order. From the context, I read it that the order is just relevant if you want to mix utf8 and utf16 functions and have some kind of conversion and that the result can be broken. I cannot read that the function fails (and besides that, it shouldn't crash at all)

Quote from the doc [1]:
> Conversions between UTF-16be and UTF-16le are always done in place and do not invalidate a prior pointer, though of course the content of the buffer that the prior pointer references will have been modified. Other kinds of conversion are done in place when it is possible, but sometimes they are not possible and in those cases prior pointers are invalidated.

> The safest policy is to invoke these routines in one of the following ways:

    sqlite3_column_text() followed by sqlite3_column_bytes()
    sqlite3_column_blob() followed by sqlite3_column_bytes()
    sqlite3_column_text16() followed by sqlite3_column_bytes16()

> In other words, you should call sqlite3_column_text(), sqlite3_column_blob(), or sqlite3_column_text16() first to force the result into the desired format, then invoke sqlite3_column_bytes() or sqlite3_column_bytes16() to find the size of the result. Do not mix calls to sqlite3_column_text() or sqlite3_column_blob() with calls to sqlite3_column_bytes16(), and do not mix calls to sqlite3_column_text16() with calls to sqlite3_column_bytes().

[1] [sqlite3 doc for sqlite3_column_text/blob/bytes](https://www.sqlite.org/c3ref/column_blob.html)

P.S.: I am a bit confused about a failed github workflow, as the error just seems to be that something could not be uploaded, so I try a PR and pray it goes green ;)

### CODE REVIEW

**Comment by TinyTinni** [comment]
Thanks for your feedback!
The tests in `tools/sqlite3_api_wrapper/test/test_sqlite3_api_wrapper.cpp` use the wrapper while wrapping it again and do not specifically test the sqlite3 functions.

I would probably just add a plain sequence which calls the c functions or do you have something in mind? Would you prefer that I extend the C++ wrapper around the sqlite3 c functions?  
Or would be another file more appropriate in case of plain sqlite3 c functions?

I also ask because I have probably another PR which will change a sqlite3 wrapper c function, but it isn't done yet.

**Comment by TinyTinni** [comment]
Never mind my question. I saw that there are simple c function tests in `tools/sqlite3_api_wrapper/test/test_sqlite3_api_wrapper.cpp`. It seems like the string length assertions would fit fine in the "Basic prepared statement usage" test. I will add them.

**Comment by TinyTinni** [comment]
Can I somehow trigger the CI without another commit? An upload fail to CodeCov doesn't look like something caused by this PR.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
