### PR TITLE
Issue #2782: Non-Gregorian Calendars

### PR DESCRIPTION
**Pull request by hawkfish**
Allow the user to change the current calendar used by ICU via

```sql
Set Calendar='<name>';
```

Test it using the Japanese imperial eras.

### CODE REVIEW

**Comment by hawkfish** [comment]
I should know better than to [second guess](http://www.meijigakuin.ac.jp/~watson/ref/mtsh.html) ICU's time nerds... Think I should fix this before it ends up in our permanent code base.

**Comment by hawkfish** [comment]
In case anyone ever asks, I have a tsv that maps the era numbers to the Japanese (Kanji) names and the English transcriptions, along with the date boundaries.

**Comment by hawkfish** [comment]
The sanitiser failure looks unrelated?

**Comment by Mytherin** [comment]
Indeed it is. Thanks! Looks good.

**Pull request merged**
