### PR TITLE
JDBC - Add append method for LocalDateTime

### PR DESCRIPTION
**Pull request by Jens-H**
This PR adds an append method for Java's LocalDateTime and thus avoids going the string parsing way.

As a timestamp_t is necessary for the C API, everything down to JNI is touched.

To avoid breakage of existing code, the new Java method cannot be named "append(...)", as it would make the append(null) call ambiguous.

Btw.: For me the JDBC tests had an error unrelated to this PR. So not sure if this PR is passing the tests.

### CODE REVIEW

**Review by Mause — APPROVED** [review]

**Comment by Jens-H** [comment]
Looks like the append is broken for Windows arm64, but I have no way to see what is failing there.

**Comment by Jens-H** [comment]
Checking the log it is pretty sure the the upper half of the timestamp int64 got lost. As it only happens on Windows ARM, it is hard to tell the problem without access to this platform.

@Mause How to proceed here?

**Comment by Mause** [comment]
> Checking the log it is pretty sure the the upper half of the timestamp int64 got lost. As it only happens on Windows ARM, it is hard to tell the problem without access to this platform.
> 
> @Mause How to proceed here? 

The job name is actually incorrect here - it should be amd64, not arm64. Does that help with debug access?

**Comment by Jens-H** [comment]
I believe [e4](https://github.com/duckdb/duckdb/pull/9435/commits/e4008f05253f33c724559b88a24db92df335f830) is solving this.

**Comment by Mytherin** [comment]
Thanks!

**Comment by felipecrv** [comment]
#10736 extends the support for `java.time.LocalDateTime` in `DuckDBResultSet` to more DuckDB TIMESTAMP types — `TIMESTAMP_(MS|NS|S)`.

**Pull request merged**
