### PR TITLE
Fix #13237: fix .mode insert float column output

### LINKED ISSUE #13237: CLI - incorrect decimal representation in ".mode insert"
### What happens?

Decimals are being represented incorrectly in ".mode insert". It looks like there is an implicit cast to `float`.

### To Reproduce

```
create table t (a decimal(38,18));
insert into t values (3.14), (2.71);

from t;
```

Output (decimals are precise):
```
┌──────────────────────┐
│          a           │
│    decimal(38,18)    │
├──────────────────────┤
│ 3.140000000000000000 │
│ 2.710000000000000000 │
└──────────────────────┘

```

```
.mode insert

from t;
```

Output (decimals are imprecise):
```
INSERT INTO "table"(a) VALUES(3.1400000000000001243);
INSERT INTO "table"(a) VALUES(2.7099999999999999644);
```

### OS:

macOS 14.5 (M1)

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Milan Opath

### Affiliation:

independent

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by flashmouse**
this pr try to fix #13237

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! Could you add a test to `shell-test.py` for this?

**Comment by flashmouse** [comment]
ci said it has a format fail, but I execute  `make format-fix`  and  couldn't find any change.

**Comment by flashmouse** [comment]
it seems `src/include/duckdb.h` shoud be generated by template file  `src/include/duckdb/main/capi/header_generation/header_base.hpp.template` and currently they have different `duckdb_error_type` definition, should I modify this template file to solve ci fail? @Mytherin

**Comment by Mytherin** [comment]
Thanks!

The CI failure is unrelated and solved by a separate PR.

**Pull request merged**
