### PR TITLE
Create streaming result from a prepared statement.

### PR DESCRIPTION
**Pull request by Giorgi**
Implements https://github.com/duckdb/duckdb/discussions/9784

### CODE REVIEW

**Comment by Giorgi** [comment]
Not sure why `Java JDBC / Java Windows (arm64)` failed.

**Comment by Tishj** [comment]
> Not sure why `Java JDBC / Java Windows (arm64)` failed.

I think that's unrelated, has been failing on different PRs as well 👍

**Comment by Tishj** [comment]
Isn't this pretty much just combining these two steps into one?
```
duckdb_pending_prepared_streaming
duckdb_execute_pending
```

**Comment by Giorgi** [comment]
According to documentation `duckdb_pending_prepared_streaming` returns a _pending result represents an intermediate structure for a query that is not yet fully executed_ so I need to call `duckdb_pending_execute_task` until `duckdb_pending_execution_is_finished` returns true right? Or can I skip `duckdb_pending_execute_task` calls and call directly `duckdb_execute_pending`?

**Comment by Giorgi** [comment]
Even if I can use `duckdb_pending_prepared_streaming` followed by `duckdb_execute_pending`, it is weird for API consumers to have to use two different sets of interfaces to switch between streaming and non-streaming result.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
