### PR TITLE
[PySpark] Add dataframe methods drop_duplicates, intersectAll, exceptAll, toArrow

### PR DESCRIPTION
**Pull request by binste**

### CODE REVIEW

**Review by Tishj — APPROVED** [review]
Thanks! :+1:

**Comment by Tishj** [comment]
Not related to this PR, but I had an idea about making the behavior tests more reliable, by being able to switch out the library that is used

pytest allows you to create your own command line option, so I was thinking we could use this to influence whether `duckdb.experimental.spark.sql` or `pyspark.sql` gets loaded

Since we wrap the session in a `spark` fixture (in `conftest.py`) this is trivial, but the imports are more difficult
I tried doing this and didn't get anywhere, maybe you want to give that a try?

Also fine if you don't want to 👍

**Comment by binste** [comment]
Good idea! That would be very helpful. Happy to have a look at this, I'll keep you posted. I'll need to check other libraries who might do something similar, maybe the imports can also be in a fixture which returns a named tuple which acts as a namespace (`spark_imports` fixture with attributes `spark_imports.sql.types`, `spark_imports.sql.functions`, ...)

**Comment by Mytherin** [comment]
Thanks for the PR! Could you just resolve the merge conflicts?

**Comment by Tishj** [comment]
> Good idea! That would be very helpful. Happy to have a look at this, I'll keep you posted. I'll need to check other libraries who might do something similar, maybe the imports can also be in a fixture which returns a named tuple which acts as a namespace (`spark_imports` fixture with attributes `spark_imports.sql.types`, `spark_imports.sql.functions`, ...)

Yea I think that might be the only way
I looked into making a facade that gets influenced by the pytest config which then just delegates to pyspark/duckdb.experimental.spark, that would have required the least changes to the existing tests

But that didn't seem possible, so I think creating the `spark_imports` fixture and letting that do the delegating would be the next best step

**Comment by binste** [comment]
Rebased on `feature` and resolved all conflicts. While doing this, I realized that 

https://github.com/duckdb/duckdb/pull/13519 already implemented `crossJoin`, it was just not yet on the `main` branch -> I've left that implementation untouched and removed mine from this PR.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
