### PR TITLE
Add support for lambda functions to `COLUMNS`,  and allow COLUMNS to be used in the ORDER BY/WHERE clauses

### LINKED ISSUE #6332: Prepared statements fail when substituting into `COLUMNS`
### What happens?

When trying to create a prepared statement that uses the `SELECT COLUMNS(<regex>) FROM table` format, specifying any sort of substitution in place of the regex string causes an error. In other words, trying to prepare something like:
```
SELECT COLUMNS(?) FROM my_table;
```
results in an error.

### To Reproduce

In python, run:
```
import duckdb

duckdb_conn = duckdb.connect(":memory:")
duckdb_conn.execute(
    """
    create or replace table my_table as
        select 'test1' as column1, 1 as column2, 'quack' as column3
        union all
        select 'test2' as column1, 2 as column2, 'quacks' as column3
        union all
        select 'test3' as column1, 3 as column2, 'quacking' as column3
"""
)
duckdb_conn.execute(
    """
    prepare v1 as
        select
            COLUMNS(?)
        from my_table"""
)
```

### OS:

macOS 13.2, M2-architecture

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Nikhil Bhargava

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Mytherin**
Implements #6374, implements #5358, fixes #6332

This PR expands the `COLUMNS` syntax to allow using list operations/lambda expressions to select columns. For example:

```sql
FROM test;
┌───────┬───────┬───────┬───────┬───────┬───────┐
│  id   │  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┼───────┤
│     1 │    10 │    11 │    12 │    13 │    14 │
│     2 │    20 │    21 │    22 │    23 │    24 │
└───────┴───────┴───────┴───────┴───────┴───────┘
SELECT COLUMNS(x -> x SIMILAR TO '.*c\d') FROM test;
┌───────┬───────┬───────┬───────┬───────┐
│  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┤
│    10 │    11 │    12 │    13 │    14 │
│    20 │    21 │    22 │    23 │    24 │
└───────┴───────┴───────┴───────┴───────┘
SELECT COLUMNS(x -> x[-1] IN (1, 3, 5)) FROM test;
┌───────┬───────┬───────┐
│  c1   │  c3   │  c5   │
│ int64 │ int64 │ int64 │
├───────┼───────┼───────┤
│    10 │    12 │    14 │
│    20 │    22 │    24 │
└───────┴───────┴───────┘
```

The way this works is that the set of available columns is translated into a list of strings. For example, in the above example the list of strings is as follows:

```sql
['test.id', 'test.c1', 'test.c2', 'test.c3', 'test.c4', 'test.c5']
```

The expression/lambda function can take that list of strings and return a new list of strings that is then interpreted as the set of columns to expand. This allows us to use any of DuckDB's regular functions to filter out/select which columns we want to select. Note that we can also directly return a list - using a lambda function is not required:

```sql
SELECT COLUMNS(['c1', 'c5']) FROM test;
┌───────┬───────┐
│  c1   │  c5   │
│ int64 │ int64 │
├───────┼───────┤
│    10 │    14 │
│    20 │    24 │
└───────┴───────┘
SELECT COLUMNS(['c' || x for x in [1, 3, 5]]) FROM test;
┌───────┬───────┬───────┐
│  c1   │  c3   │  c5   │
│ int64 │ int64 │ int64 │
├───────┼───────┼───────┤
│    10 │    12 │    14 │
│    20 │    22 │    24 │
└───────┴───────┴───────┘
```

#### COLUMNS in WHERE clause
This PR also allows us to use the COLUMNS expression in the WHERE clause to construct filters. The columns are combined using `AND`, e.g. the following two expressions are identical:

```sql
SELECT * FROM test WHERE COLUMNS('.*c\d') >= 20;
┌───────┬───────┬───────┬───────┬───────┬───────┐
│  id   │  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┼───────┤
│     2 │    20 │    21 │    22 │    23 │    24 │
└───────┴───────┴───────┴───────┴───────┴───────┘
SELECT * FROM test WHERE c1 >= 20 AND c2 >= 20 AND c3 >= 20 AND c4 >= 20 AND c5 >= 20;
┌───────┬───────┬───────┬───────┬───────┬───────┐
│  id   │  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┼───────┤
│     2 │    20 │    21 │    22 │    23 │    24 │
└───────┴───────┴───────┴───────┴───────┴───────┘
```

This is useful when filtering out NULL values, for example we can filter out all NULL values on all rows using the following expression:

```sql
FROM test;
┌───────┬───────┬───────┬───────┬───────┬───────┐
│  id   │  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┼───────┤
│     1 │    10 │    11 │    12 │    13 │    14 │
│     2 │    20 │    21 │    22 │    23 │    24 │
│  NULL │     2 │     3 │     4 │     5 │     6 │
│     1 │  NULL │     3 │     4 │     5 │     6 │
│     1 │     2 │  NULL │     4 │     5 │     6 │
│     1 │     2 │     3 │  NULL │     5 │     6 │
│     1 │     2 │     3 │     4 │  NULL │     6 │
│     1 │     2 │     3 │     4 │     5 │  NULL │
└───────┴───────┴───────┴───────┴───────┴───────┘
FROM test WHERE COLUMNS(*) IS NOT NULL;
┌───────┬───────┬───────┬───────┬───────┬───────┐
│  id   │  c1   │  c2   │  c3   │  c4   │  c5   │
│ int64 │ int64 │ int64 │ int64 │ int64 │ int64 │
├───────┼───────┼───────┼───────┼───────┼───────┤
│     1 │    10 │    11 │    12 │    13 │    14 │
│     2 │    20 │    21 │    22 │    23 │    24 │
└───────┴───────┴───────┴───────┴───────┴───────┘
```

### CODE REVIEW

**Comment by earlev4** [comment]
This is excellent work, @Mytherin!!! Thanks so much!!!

**Comment by aborruso** [comment]
This is a great feature.

But often I have datasets with a lot of columns, and I have the goal to find all the rows, in which I have a specific string in all the columns that have a specific pattern in the field name. It would be extremely helpful to also have the OR option.

**Comment by Tishj** [comment]
Sounds like we need the ability to wrap this in an ALL or ANY, where it implicitly uses ALL?
```sql
SELECT * FROM test WHERE ANY COLUMNS('.*c\d') >= 20;
```

**Comment by aborruso** [comment]
> Sounds like we need the ability to wrap this in an ALL or ANY, where it implicitly uses ALL?

It would be great to have it, thank you

**Comment by aborruso** [comment]
> Sounds like we need the ability to wrap this in an ALL or ANY, where it implicitly uses ALL?
> 
> ```sql
> SELECT * FROM test WHERE ANY COLUMNS('.*c\d') >= 20;
> ```

@Mytherin @Tishj I didn't understand if there was a way to make it work in OR

Thank you

**Pull request merged**
