### PR TITLE
[Python] Skip the PandasAnalyzer if dtype is `'string'`

### LINKED ISSUE #12507: Importing from Pandas has incorrect column type for empty string/object columns
### What happens?

Importing data from a Pandas dataframe result in incorrect column if the column in Pandas is object or string types and the column is completely empty.

Documentation is not clear on the implicit casting which occurs when importing a dataframe, but I would expect that the column/string pandas type becomes `VARCHAR`. This is the case when there are values in the column, but not when the column is empty, instead returning `INTEGER`. 

In my limited testing this does not occur with other column types.

Both 1.0.0 and 1.0.1-dev122 results in this bug.

### To Reproduce

The following code will create example dataframes and relations and compare types, failing as per bug description when checking relation data types. Changing `use_string_type` allows testing of both `object` and `string` Pandas types.

```python
import random

import pandas as pd
import numpy as np
import duckdb

def get_filled_df(rows: int = 100, use_string_type: bool = False) -> pd.DataFrame:
    """Return dataframe filled with random data of specific types."""
    index = np.arange(rows)
    data: dict = {
        "int_column": [random.randint(0, 100) for _ in range(rows)],
        "bool_column": [random.choice([True, False]) for _ in range(rows)],
        "float_column": [random.uniform(0, 1) for _ in range(rows)],
        "string_column": [random.choice(["foo", "bar", "baz", "qux"]) for _ in range(rows)]
    }

    return pd.DataFrame(data=data, index=index).convert_dtypes(infer_objects=False, convert_string=use_string_type)

def get_empty_df(rows: int = 100, use_string_type: bool = False) -> pd.DataFrame:
    """Return dataframe with empty columns of specific types."""
    df: pd.DataFrame = pd.DataFrame(index=np.arange(rows))

    df["int_column"] = pd.Series(dtype="Int64")
    df["bool_column"] = pd.Series(dtype="boolean")
    df["float_column"] = pd.Series(dtype="Float64")
    if use_string_type:
        df["string_column"] = pd.Series(dtype="string")
    else:
        df["string_column"] = pd.Series(dtype="object")

    return df

print(f"Pandas version: {pd.__version__}") # 2.2.2
print(f"Numpy version: {np.__version__}") # 1.26.4
print(f"DuckDB version: {duckdb.__version__}") # 1.0.0

use_string_type: bool = True
filled_df: pd.DataFrame = get_filled_df(use_string_type=use_string_type)
empty_df: pd.DataFrame = get_empty_df(use_string_type=use_string_type)

# check df correctly constructed
assert len(filled_df) == len(empty_df)

# check dtypes match
for fdf_type, edf_type in zip(filled_df.dtypes, empty_df.dtypes):
    assert fdf_type == edf_type

with duckdb.connect(database=":memory:") as con:
    f_df_rel: duckdb.DuckDBPyRelation = con.from_df(filled_df)
    e_df_rel: duckdb.DuckDBPyRelation = con.from_df(empty_df)

    for fdf_col, edf_col in zip(f_df_rel.columns, e_df_rel.columns):
        assert fdf_col == edf_col, f"Filled column {fdf_col} does not match empty col {fdf_col}"

    # fails with empty string column being INTEGER type instead of VARCHAR
    for (fdf_col, fdf_type), (edf_col, edf_type) in zip(zip(f_df_rel.columns, f_df_rel.dtypes), zip(e_df_rel.columns, e_df_rel.dtypes)):
        assert fdf_type == edf_type, f"Filled column {fdf_col} type {fdf_type} does not match empty column {edf_col} type {edf_type}"
```

### OS:

Ubutu 20.04 WSL x64 (5.15.146.1-microsoft-standard-WSL2)

### DuckDB Version:

1.0.0, 1.0.1-dev122

### DuckDB Client:

Python

### Full Name:

Zander Horn

### Affiliation:

Stone Three

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #12507 

To explain why this is not fixable for `object`:
`object` can be *anything*, so we analyze it to figure out what it actually is.
If we only encounter NULL, we return the SQLNULL type, the binder is not a huge fan of that so it turns it into INTEGER.
That is what gets shown with `DuckDBPyRelation.types`.

When turning this back into a DataFrame (calling `.df()` on the created DuckDBPyRelation), we are dealing with an INTEGER column, with all nulls.
This creates a `np.ma.array` with everything masked.
Pandas decides to convert that into a column containing NaN with `float64` as dtype

### CODE REVIEW

**Comment by Tishj** [comment]
We might want to return VARCHAR instead of SQLNULL if all nulls are found, that might be less confusing than INTEGER

**Comment by H-SG** [comment]
Thanks for this fix! I checked out the source last night but I'm afraid my C++ is not so great, but your changes are exactly where I was thinking it might be an issue. Within the context of an object column from Pandas I do feel VARCHAR is a safer return for SQLNULL, as in most use cases I imagine end users will do some custom handling for resultant object columns in Pandas.

**Comment by Tishj** [comment]
I'm not going to push this change in this PR, I'm still not sure if it makes sense to make this change
Both are wrong, INTEGER and VARCHAR

```patch
diff --git a/tools/pythonpkg/src/pandas/scan.cpp b/tools/pythonpkg/src/pandas/scan.cpp
index 10424faab7..37808eead7 100644
--- a/tools/pythonpkg/src/pandas/scan.cpp
+++ b/tools/pythonpkg/src/pandas/scan.cpp
@@ -89,6 +89,12 @@ unique_ptr<FunctionData> PandasScanFunction::PandasScanBind(ClientContext &conte
 	} else {
 		Pandas::Bind(context, df, pandas_bind_data, return_types, names);
 	}
+	// Override columns that were detected as NULL
+	for (auto &type : return_types) {
+		if (type.id() == LogicalTypeId::SQLNULL) {
+			type = LogicalTypeId::VARCHAR;
+		}
+	}
 	auto df_columns = py::list(df.attr("keys")());
 
 	auto &ref = input.ref;
diff --git a/tools/pythonpkg/tests/fast/pandas/test_pandas_object.py b/tools/pythonpkg/tests/fast/pandas/test_pandas_object.py
index c00fcbc229..1bd6912bdf 100644
--- a/tools/pythonpkg/tests/fast/pandas/test_pandas_object.py
+++ b/tools/pythonpkg/tests/fast/pandas/test_pandas_object.py
@@ -17,7 +17,7 @@ class TestPandasObject(object):
         data = [None] * 10000  # Last element is 1, others are None
         pandas_df_2 = pd.DataFrame(data, columns=['c'], dtype=object)
         assert con.execute('FROM pandas_df_2 limit 1').fetchall() == [(None,)]
-        assert con.execute('select typeof(c) FROM pandas_df_2 limit 1').fetchall() == [('"NULL"',)]
+        assert con.execute('select typeof(c) FROM pandas_df_2 limit 1').fetchall() == [('VARCHAR',)]
 
     def test_object_to_string(self, duckdb_cursor):
         con = duckdb.connect(database=':memory:', read_only=False)
```

**Comment by Tishj** [comment]
@Mytherin should this maybe be targeting `main` ?

**Comment by Mytherin** [comment]
Thanks! LGTM - maybe the other change can be moved to a separate PR?

**Pull request merged**
