### PR TITLE
Add missing reset to EnableProgressBarPrintSetting

### PR DESCRIPTION
**Pull request by Maxxen**
This somehow slipped through to master.

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by Tishj** [comment]
Ah yea I know why this fails, I added a test for RESET in `test_reset.cpp`, this new option is missing from that test

**Comment by Tishj** [comment]
Ah yea I know why this fails, I added a test for RESET in `test_reset.cpp`, this new option is missing from that test

**Comment by Tishj** [comment]
I'm gonna make a PR to fix this, hopefully we can merge it first thing in the morning 👍 
sorry @Maxxen I also thought this was the only change needed but I forgot about this test I added 😅

**Comment by Maxxen** [comment]
argh, nerd-sniped again!

**Pull request closed without merging**
