### PR TITLE
Fix: correctly calculate the range of build side for perfect hash join

### PR DESCRIPTION
**Pull request by gitccl**
The probe side sits on the lhs, and the build side sits on the rhs. Therefore, the range of the build side should be calculated based on the rhs.
Also, we remove a piece of unused code in this pr.

### CODE REVIEW

**Comment by gitccl** [comment]
The `probe_min` and `probe_max` fields are never used, could we remove them?

**Review by hawkfish — COMMENTED** [review]
Code looks correct to me, but can we have a test that demonstrates the correct result? Something that outputs and checks the generated plan?

**Comment by gitccl** [comment]
> Code looks correct to me, but can we have a test that demonstrates the correct result? Something that outputs and checks the generated plan?

Sure. Can the `build_range` field be added to the output of the `explain` statement? Then check if the `build_range` in the generated physical plan is as expected?

**Comment by gitccl** [comment]
Hi, PTAL @hawkfish @Mytherin

**Comment by Mytherin** [comment]
Thanks for the PR! As @hawkfish mentioned, the code looks good to me, but I would like to see a test case that breaks before but works after this fix.

**Pull request merged**
