### PR TITLE
Read file in 100mb chunks in read_file/read_blob

### PR DESCRIPTION
**Pull request by Maxxen**
This PR modified the behavior of `read_file` and `read_blob` to split the underlying filesystem read command into multiple reads of at most 100MB. This allows reading files larger than e.g. 2,147,479,552 bytes on linux, as requesting more than that in a single `read()` call is not supported. 

Fixes an issue found internally.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

**Comment by Mytherin** [comment]
Actually thinking about this some more - the string max size is 4GB. This function should probably check that we are not reading more than that into the string.

**Comment by Mytherin** [comment]
Nevermind, `StringVector::EmptyString` will catch this and throw an error

**Comment by Maxxen** [comment]
I think AssertMaxFileSize is supposed to do that top

**Pull request merged**
