### PR TITLE
[WIP] Support dot notation for JSON

### PR DESCRIPTION
**Pull request by ankrgyl**
This is a draft first step towards making duckdb's JSON type act more like `SUPER` or `VARIANT`:

- [x] Dot syntax lets you extract from the object (e.g. a.b.c instead of a->'b'->>'c')
- [x] Type conversions (at least for comparisons) appear to extract scalar values from json instead of casting, i.e. json('{"a": "foo"}').a = 'foo' returns true

### CODE REVIEW

**Comment by ankrgyl** [comment]
CC @lnkuiper

**Comment by lnkuiper** [comment]
Hi, thanks for the PR! I think this is a great idea. I'm not sure if we want to use `json_extract_string` here.
I think we want to use `json_extract` instead.

The benefit of using `json_extract` is that the resulting type is still `JSON`, and then chained extractions, e.g., `j.x.y` will not have to be auto-cast from `VARCHAR` to `JSON` again, making the chained extractions more efficient.

Currently, the downside of using `json_extract` is that we cannot do this:
```sql
select json_extract('{"x":"42"}', 'x') = '42' as comp;
┌─────────┐
│  comp   │
│ boolean │
├─────────┤
│ false   │
└─────────┘
```

However, we can do this:
```sql
select json_extract('{"x":"42"}', 'x') = 42 as comp;
┌─────────┐
│  comp   │
│ boolean │
├─────────┤
│ true    │
└─────────┘
```

In the first case, we implicitly cast `"42"` to `VARCHAR`, but this doesn't actually do anything, so we get back `"42"`, which is not equal to the string `42`.

In the second case, we parse the JSON and implicitly cast `"42"` to `INTEGER`, allowing the comparison to succeed.

I think the first case should actually be changed. We should create a `CastJSONToVarchar` function in `json_functions.cpp` to handle this case instead of using `DefaultCasts::ReinterpretCast`.

I think that function should look something like this:
```c++
static bool CastJSONToVarchar(Vector &source, Vector &result, idx_t count, CastParameters &parameters) {
	auto &lstate = parameters.local_state->Cast<JSONFunctionLocalState>();
	lstate.json_allocator.Reset();
	auto alc = lstate.json_allocator.GetYYAlc();

	UnaryExecutor::Execute<string_t, string_t>(source, result, count, [&] (const string_t &input) {
		auto data = input.GetDataWriteable();
		const auto length = input.GetSize();

		auto doc = JSONCommon::ReadDocumentUnsafe(data, length, JSONCommon::READ_FLAG, alc);
		D_ASSERT(doc);
		const auto val = doc->root;

		if (unsafe_yyjson_is_str(val)) {
			return StringVector::AddString(result, unsafe_yyjson_get_str(val), unsafe_yyjson_get_len(val));
		}

		return input;
	});
	StringVector::AddHeapReference(result, source);
	return true;
}
```

And now register like this:
```c++
	// JSON to VARCHAR requires a cast to check whether the top-level JSON is a string
	// Let's make it 1 more than STRUCT to VARCHAR
	auto json_to_varchar_cost = casts.ImplicitCastCost(LogicalTypeId::STRUCT, LogicalTypeId::VARCHAR) + 1;
	BoundCastInfo info(CastJSONToVarchar, nullptr, JSONFunctionLocalState::InitCastLocalState);
	casts.RegisterCastFunction(JSONCommon::JSONType(), LogicalType::VARCHAR, std::move(info), json_to_varchar_cost);
```

Note that I haven't tested any of this code, this is just how I would start writing this. I hope this helps!

**Comment by ankrgyl** [comment]
@lnkuiper this was immensely helpful and mostly worked out of the box :)

I had to (hackily) change the type coercion rule (`LogicalType::MaxLogicalType`) to cast the aliased type (JSON) to VARCHAR, instead of the current semantic which is to always picked the aliased type.

Do you have any suggestions/opinions on how to best encode this semantic? Obviously JSON is an extension type, so I'd imagine you don't want to hardcode its existence in the binder too much.

**Comment by lnkuiper** [comment]
Awesome! Great that you were able to find the issue in `MaxLogicalType`.

Now when we cast a JSON like `"duck"` to VARCHAR, we get `duck`! However, it doesn't work the other way around, i.e., the cast from VARCHAR to JSON is a special case, where we parse the string as JSON.

Of course, we'd like to keep as much of the JSON functionality as possible in the extension, but I don't see any other option here. I think we want to add a function to `LogicalType`:
```c++
bool IsJSONType() {
    return id() == LogicalTypeId::VARCHAR && HasAlias() && GetAlias() == "JSON";
}
```

Then we can use that within DuckDB itself (not just within the extension), so this check isn't duplicated everywhere.

Since JSON can be cast to virtually any other type (not just VARCHAR!), and we prefer to use our own types over using JSON as they are more efficient, this should be placed at the top of `MaxLogicalType`:
```c++
if (left.IsJSONType() {
    return right;
} else if (right.IsJSONType() {
    return left;
}
```

This way, when you compare a JSON, e.g., `{"duck":42}` with a DuckDB struct `{duck:42}`, the JSON will be cast to a STRUCT, and then the comparison will be evaluated instead of the STRUCT being cast to JSON. In either case, it will return true (and it already does), but this is more efficient.

If you implement that, all we need is some tests. If you want, you can create a new test file, and copy a few tests from `test_json_extract.test`. Instead of using `json_extract` explicitly, you can use the new dot syntax. The result should be the same.

Thanks!

**Comment by ankrgyl** [comment]
Awesome -- will get that sorted in the next couple days

**Comment by ankrgyl** [comment]
@lnkuiper take a look now -- added some basic sanity tests for type conversion too.

**Review by lnkuiper — APPROVED** [review]
Looks great! Thanks for this. It's nice that the dot syntax works even for the more complex extract queries.

I wish I had foreseen this, but it looks now like an unintended side-effect of `CastJSONToVarchar` is that JSON strings like `"duck"` are now rendered as `duck` in our shell (even though internally, it's still `"duck"`). Example:
```python
$ ipython3
Python 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import duckdb

In [2]: con = duckdb.connect()

In [3]: con.sql("""select '{"duck":"goose"}'::JSON->'duck';""")
Out[3]: 
┌──────────────────────────────────────────────┐
│ (CAST('{"duck":"goose"}' AS JSON) -> 'duck') │
│                     json                     │
├──────────────────────────────────────────────┤
│ goose                                        │
└──────────────────────────────────────────────┘

In [5]: con.execute("""select '{"duck":"goose"}'::JSON->'duck';""").fetchall()
Out[5]: [('"goose"',)]
```
I don't think we can do anything about this, and I think the new functionality outweighs the changed behavior.

Thanks again!

**Comment by ankrgyl** [comment]
Yes I noticed that too -- it also affects the existing tests. Glad it's an acceptable tradeoff.

What are the next steps?

**Comment by lnkuiper** [comment]
The next step is to get all tests to pass. As you can see there are some failing tests, mostly related to the rendering as we discussed. You can run all fast tests locally using this:
```
./build/release/test/unittest
```

And if you want to run all tests (including slow tests), you will have to run:
```
./build/release/test/unittest "*"
```
If you need any help, please let me know!

**Comment by lnkuiper** [comment]
Hi @ankrgyl, I have some ideas for this PR, you can wait for now. I will look into this a bit

**Comment by ankrgyl** [comment]
Just added your changes!

**Comment by lnkuiper** [comment]
I think that now only a few tests need to be fixed. We are rendering JSON strings with `"` again. If that's fixed then I think the PR is ready to go. I can't modify your PR, so could you make sure that all tests are succeeding locally?

**Comment by lnkuiper** [comment]
Thanks for looking into this, sorry for the late reply, I'm pretty slammed for ~2 weeks.

From looking at the query, I'm not exactly sure where the cast is happening. There is only one JSON (`json('{}')`), which is apparently being cast to `NULL` somehow.

My guess would be that we need this at the top of `LogicalType::MaxLogicalType`:
```c++
	// We prefer not using the NULL type
	if (left.id() == LogicalTypeId::SQLNULL) {
		return right;
	} else if (right.id() == LogicalTypeId::SQLNULL) {
		return left;
	}
```
Hope this helps!

**Comment by ankrgyl** [comment]
> Hope this helps!

Yes this seems to work! I wasn't sure if we should try to create some json-specific cast logic to null or do something global like this. Thanks for the help.

**Comment by ankrgyl** [comment]
Interesting, now we have a different conversion-related side-effect:

In `test/sql/types/enum/test_enum_to_numbers.test`, some these conversions between timestamp types and varchar are no longer causing conversion errors. Happy to change the test of course but wanted to flag in case we should be conservative about changing this cast behavior too.

```
# in types.hpp logical type of timestamp_tz, time_tz, interval, and blob are all higher 
# than varchar, causing a direct cast from varchar to the type to happen. 

statement error
select count(*) from t1, t2 where t1.time_tz = t2.b;
----
Conversion Error

statement error
select count(*) from t1, t2 where t1.timestamp_tz = t2.b;
----
Conversion Error

statement error
select count(*) from t1, t2 where t1.interval = t2.b;
----
Conversion Error
```

**Comment by lnkuiper** [comment]
Hmm, we might need to add a JSON to NULL cast then. I'll look into this when I have some more time

**Comment by lnkuiper** [comment]
@ankrgyl There is still something I want to change about how JSON is rendered, so this needs a bit more work. I will look into it this week.

**Review by lnkuiper — APPROVED** [review]
This PR looks good to me now! Although I have made a bunch of changes myself, so now I'm reviewing my own code. Maybe @Mytherin can have a look?

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by ankrgyl** [comment]
@lnkuiper do you need anything else from me on this PR?

**Comment by Mytherin** [comment]
Could you resolve the merge conflicts?

**Comment by ankrgyl** [comment]
Done

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
