### PR TITLE
[Python (Relational)] Query now returns a DuckDBPyRelation

### PR DESCRIPTION
**Pull request by Tishj**
This PR addresses an issue brought up on Discord (not sure if there was ever a Github issue made for it)

The problem is described here:
```py
rel1 = duckdb.query('select * from range(10) tbl(i)')
rel2 = rel1.query('rel1', 'select * from rel1 limit 5')
rel3 = rel2.query('rel2', 'select * from rel2 limit 2')
rel3.df()
```
DuckDBPyConnection::RunQuery -> DuckDBPyRelation (rel1)
DuckDBPyRelation::Query -> DuckDBPyRelation (rel2)
DuckDBPyResult::Query -> ❌ (does not exist, line 3 causes the following error:)
`AttributeError: 'duckdb.DuckDBPyResult' object has no attribute 'query`

With this change, DuckDBPyRelation::Query produces a DuckDBPyRelation, so chains like these are now supported

### CODE REVIEW

**Comment by pdet** [comment]
That's pretty cool.

Could you add some tests using the produced result as a relation? (i.e., chaining it) and add some funky stuff as well (broken query, query that returns empty, ...)

**Comment by Mause** [comment]
You'll need to update the .pyi stubs too

**Comment by Mytherin** [comment]
Thanks, LGTM!

**Comment by wisp3rwind** [comment]
One thing that used to be possible, but isn't anymore (due to the additional validation done here, if I'm not mistaken) is running a `rel.query("t", "EXPLAIN SELECT * FROM t")` to fetch the query plan from python. `rel.explain()` generally appears to provide much less information, and in particular not the optimized plan.

**Pull request merged**
