### PR TITLE
Set version info for duckdb.dll

### PR DESCRIPTION
**Pull request by Giorgi**
This change sets FileVersion and ProductVersion for duckdb.dll

Implements #13445

image

### CODE REVIEW

**Comment by Giorgi** [comment]
I'm not sure why the test failed in the Windows (64 Bit) action, my changes don't touch any code at all.

**Comment by Mytherin** [comment]
Thanks!

> I'm not sure why the test failed in the Windows (64 Bit) action, my changes don't touch any code at all.

Agreed, that looks spurious.

**Comment by Maxxen** [comment]
Im having the spatial ci on windows arm64 rtools fail now due to something that looks like it could be related to some sort of version resource file built as part of duckdb itself but I don't know enough about windows to figure out what to do. Any advice? https://github.com/duckdb/duckdb_spatial/actions/runs/10574982389/job/29297740260

**Comment by carlopi** [comment]
The same was also on tonight nightly run: https://github.com/duckdb/duckdb/actions/runs/10569474152/job/29282367154#step:5:16734, so it should be easier to reproduce there.

**Comment by Mytherin** [comment]
Most likely this should be skipped for mingw builds

**Comment by Giorgi** [comment]
@Mytherin https://github.com/duckdb/duckdb/pull/13601

**Pull request merged**
