### PR TITLE
First iteration of ODBC driver

### PR DESCRIPTION
**Pull request by hannes**
This PR adds a very basic implementation of an ODBC driver for DuckDB. Loads of work to be done, but basic querying works.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
CC @tiagokepe

**Comment by tiagokepe** [comment]
> CC @tiagokepe

great ^^

**Comment by alanpaulkwan** [comment]
@hannesmuehleisen you forgot to @ me :) game changer!

**Comment by hannesmuehleisen** [comment]
@alanpaulkwan not going to be terribly useful yet I fear. But @tiagokepe is going to change that. This PR was more about basic structure and tests setup.

**Comment by moheikal79** [comment]
Hi
Very impressive. when the ODBC driver will be ready for download?

Regards

**Pull request merged**
