### PR TITLE
feat: Use pip to install and uninstall python client

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks, looks good to me!

**Comment by pdet** [comment]
LGTM.

Does this also mean we don't need the clean.py anymore? Or is that still necessary for other gunk the build might produce?

**Comment by Mytherin** [comment]
Could you also have a look at the CI that is now failing?

**Comment by Mause** [comment]
That's now been fixed @Mytherin

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
