### PR TITLE
[Fuzzer] Unset 'swizzled' flag in SortedData

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes point 31 of the list in issue #5984

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by PedroTadim** [comment]
I still get the assertion error

**Comment by lnkuiper** [comment]
> I still get the assertion error

I'm also getting it again. Which is very strange because the test was succeeding locally when I sent this PR, and the CI passed too. Maybe there was a hidden merge conflict?

**Comment by lnkuiper** [comment]
I think I just found the bug! I'll send another PR.

**Pull request merged**
