### PR TITLE
Issue #1658: QUANTILE variants

### PR DESCRIPTION
**Pull request by hawkfish**
Add `QUANTILE_DISC` alias for `QUANTILE` and implement `QUANTILE_CONT`.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks great. Could you add some tests that verify the correct interpolation behavior with values close to the maximum value of the domain for each of the supported types (e.g. 120/122 for tinyint, etc)? It seems like you accounted for this but would like some tests as verification :)

**Comment by hawkfish** [comment]
I'm not quite sure what you mean here. Do you mean literally just those two values to make sure there is no overflow/test the delta computation?

**Comment by Mytherin** [comment]
Yes, exactly.

**Comment by Mytherin** [comment]
Also to add to that, a testcase involving the maximum negative values of the domain would be good as well, e.g.

```sql
CREATE TABLE tinyints(t TINYINT);
INSERT INTO tinyints VALUES (-127), (-127);
SELECT quantile_cont(t, 0.5) FROM tinyints;
UPDATE tinyints SET t=-t;
SELECT quantile_cont(t, 0.5) FROM tinyints;
-- repeat for all integer types
```

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
