### PR TITLE
Track and log CSV schema mismatch errors when `read_csv(ignore_errors = true)`

### PR DESCRIPTION
**Pull request by Maxxen**
This PR changes the csv reader to log csv schema mismatch errors into an internal client-data structure, which can then be accessed with `read_csv_error_log()`

The error log is `STANDARD_VECTOR_SIZE` large by default, but you can change it with `SET csv_error_log_size = <integer>`. Any additional errors that occur after the log has reached max size will be ignored like the previous behaviour.

The error log is reset on every new read_csv query. We reset in the ReadCSVInitGlobal, but I'm not sure if this is the best place to do it.

The line numbers in the parallel case is probably borked, but I've been told that #7184 is going to fix this.

## Example
Given two csv files:
`bad.csv`
```csv
1,2,AAA,
4,BBB,9,
6,7,CCC,
```
`bad2.csv`
```csv
1,2,DDD,
4,5,9,
EEE,7,FFF,
```
We query them with the schema: `'col0': 'INTEGER', 'col1': 'INTEGER', 'col2': 'VARCHAR'`
```sql
SELECT * FROM read_csv('test/sql/copy/csv/data/error/mismatch/*.csv', columns = {'col0': 'INTEGER', 'col1': 'INTEGER', 'col2': 'VARCHAR'}, ignore_errors=true);
┌───────┬───────┬─────────┐
│ col0  │ col1  │  col2   │
│ int32 │ int32 │ varchar │
├───────┼───────┼─────────┤
│     1 │     2 │ AAA     │
│     6 │     7 │ CCC     │
│     1 │     2 │ DDD     │
│     4 │     5 │ 9       │
└───────┴───────┴─────────┘
```
Now we can get the errors.
```sql 
FROM read_csv_error_log();
┌─────────────┬───────────────┬─────────────┬──────────────┬─────────────────────────────────────────┬────────────────────────────────────────────────┐
│ line_number │ column_number │ column_name │ parsed_value │                  error                  │                   file_name                    │
│    int64    │     int64     │   varchar   │   varchar    │                 varchar                 │                    varchar                     │
├─────────────┼───────────────┼─────────────┼──────────────┼─────────────────────────────────────────┼────────────────────────────────────────────────┤
│           2 │             1 │ "col1"      │ BBB          │ Could not convert string 'BBB' to INT32 │ test/sql/copy/csv/data/error/mismatch/bad.csv  │
│           4 │             0 │ "col0"      │ EEE          │ Could not convert string 'EEE' to INT32 │ test/sql/copy/csv/data/error/mismatch/bad2.csv │
└─────────────┴───────────────┴─────────────┴──────────────┴─────────────────────────────────────────┴────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by douenergy** [comment]
@Maxxen  
What are your thoughts on renaming the function **read_csv_error_log()** to a more generic name(e.g. **read_csv_log()** )? 

Additionally, I propose adding 2 new columns, namely `query` and `log_type`, to the read_csv_log() function.

In this particular case, the value for the `query` column would be:

```sql
SELECT * 
FROM read_csv('test/sql/copy/csv/data/error/mismatch/*.csv', 
     columns = {'col0': 'INTEGER', 'col1': 'INTEGER', 'col2': 'VARCHAR'}, 
     ignore_errors=true);
```

As for the `log_type` column, it would have the value:

`error`

I think that using a more generic name for the function would enhance its extensibility.

**Comment by Mytherin** [comment]
I don't think the CSV error log is the correct place to put SQL queries. What we could perhaps consider is adding a separate query log, and having a `query_id` in the CSV error log that references to that separate query log. Then you can join them together to find information about the query if desired.

**Comment by douenergy** [comment]
> I don't think the CSV error log is the correct place to put SQL queries. What we could perhaps consider is adding a separate query log, and having a `query_id` in the CSV error log that references to that separate query log. Then you can join them together to find information about the query if desired.

I think this is a better way! 👍
`pg_stat_statements` or `duck_stat_statements` can also  joined from the query log in the future.

**Comment by Maxxen** [comment]
Closing this for now - needs more development.

**Pull request closed without merging**
