### PR TITLE
[Python] support for pandas experimental NA type

### PR DESCRIPTION
**Pull request by Tishj**
This PR adds support to our pandas object conversion logic for `pandas._libs.NAType` (pd.NA)
Recently mentioned in #5238 but also mentioned several times before.

I am still not a huge fan of supporting this value as it clutters the conversion even more, and since this also now needs to temporarily grab the GIL to check if the value is of this type, it's not a cheap change.
Might be able to avoid this by figuring out the validity mask during steps where we already have the GIL.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

I believe this can be done without grabbing the GIL. All that is needed here is a type check. You can get the type of a `PyObject` using the `Py_TYPE` macro which can be used without holding the GIL. This returns a pointer to the type object. The type objects should be globally unique, so a pointer comparison on the type object should be enough to verify that the type is of a specific instance.

I believe the `IsInstance` stuff is only necessary if inheritance is involved - which I don't think is the case here.

**Comment by Tishj** [comment]
Hmm I can't seem to get the same behavior this way
```c++
					if (Py_TYPE(val) == Py_TYPE(import_cache.pandas.libs.NAType().ptr())) {
						out_mask.SetInvalid(row);
						continue;
					}
```
or
```c++
					if (PyObject_TypeCheck(val, Py_TYPE(import_cache.pandas.libs.NAType().ptr()))) {
						out_mask.SetInvalid(row);
						continue;
					}
```

**Review by Mytherin — COMMENTED** [review]
Great that you got that to work! Could we just get some tests? Other than that, everything looks good to me.

**Comment by Tishj** [comment]
I looked into the Python3.9 failure, but I can't reproduce this locally
I installed duckdb with my branch through `python3.9 tools/pythonpkg/setup.py install` and ran the failing test but it completes just fine

**Comment by Mytherin** [comment]
The error is a bit odd - it looks like the result has leaked from another test:

```
         res = conn.execute("select * from df").fetchall()
 >       assert(res[0][0] == None)
 E       AssertionError: assert {'key': ['a', 'b', 'c', 'd'], 'value': ['1', '3', '3', 'test']} == None

```
Which is also used here:

```
    def test_map_value_upgrade(self, duckdb_cursor):
        x = pd.DataFrame(
            [
                [{'key': ['a', 'b', 'c', 'd'], 'value': [1, 3, 3, 'test']}],
                [{'key': ['a', 'b', 'c', 'd'], 'value': [1, 3, 3, 7]}],
                [{'key': ['a', 'b', 'c', 'd'], 'value': [1, 3, 3, 7]}],
                [{'key': ['a', 'b', 'c', 'd'], 'value': [1, 3, 3, 7]}],
                [{'key': ['a', 'b', 'c', 'd'], 'value': [1, 3, 3, 7]}]
            ]
        )

```

Are these tests run in parallel somehow? Both tests seem to use the default connection, perhaps there is some weird result caching going on there?

**Pull request merged**
