### PR TITLE
Provide support for continuous profiling

### PR DESCRIPTION
**Pull request by ywelsch**
DuckDB's profiler gives excellent insights into where time is being spent in a long-running query. It currently only exposes this information at the end of query execution, though. The PR here makes it possible to get profile information while the query is executing, providing a way to make this information externally visible during query execution (similar to query progress).

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! LGTM - I wonder if we need the recursive_mutex, or if we can make due with a regular mutex for public members by e.g. adding `Internal` methods?

**Comment by ywelsch** [comment]
> I wonder if we need the recursive_mutex, or if we can make due with a regular mutex for public members by e.g. adding Internal methods?

Thanks, I will investigate.

**Comment by ywelsch** [comment]
I've reworked the PR to no longer use recursive_mutex

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
