### PR TITLE
out of tree extension improvements

### PR DESCRIPTION
**Pull request by samansmink**
This PR introduces some changes that will make working with Out-Of-Tree Extensions easier.
- Specifying multiple extensions by name + path
- Specifying an out of tree extension should be linked into duckdb and loaded on starting duckdb
- Specifying a custom remote repo for extension binaries

These features exists besides the current way to build out of tree extensions using the EXTERNAL_EXTENSION_DIRECTORIES to easy transitioning the current OOTE's.

To pass out of tree extensions to DUCKDB, the variable `DUCKDB_OOT_EXTENSION_NAMES` can be set to a ';' separated list of extension names.

Then for each passed extension, the following variables can be used:
`DUCKDB_OOT_EXTENSION_<upppercase_ext_name>_PATH`
`DUCKDB_OOT_EXTENSION_<upppercase_ext_name>_INCLUDE_PATH`
`DUCKDB_OOT_EXTENSION_<upppercase_ext_name>_SHOULD_LINK`

defaults to resp. `_INCLUDE_PATH` and `_PATH` are: 
`${PROJECT_SOURCE_DIR}/extension/${OOTE_NAME}_clone/src/include` and `${PROJECT_SOURCE_DIR}/extension/${OOTE_NAME}_clone/src`

Note that the the `_SHOULD_LINK` variable can be used to statically link the extension in the duckdb binary and have it auto-loaded on startup.

The custom remote repository setting will override the default extensions.duckdb.org with a user-specified url. The idea here is that when combined with the upcoming extension boilerplate repository, installing third party extensions is simplified since the version. By default, the path we load extensions from is: `http://extensions.duckdb.org/${REVISION}/${PLATFORM}/${NAME}.duckdb_extension.gz/${REVISION}/${PLATFORM}/${NAME}.duckdb_extension.gz`. 
With the custom extension endpoint, third party extensions can be distributed as `http://some.domain.com/some/path/<extension version>/${DUCKDB_REVISION}/${PLATFORM}/${NAME}.duckdb_extension.gz`. To install a third party extension now, all that is required is:
```
SET custom_extension_repository='some.domain.com/some/path/v.X.Y.Z';
INSTALL <extension name>
LOAD <extension name>
```

To switch back to the default, repo the user can do:
`SET custom_extension_repository='';` or `SET custom_extension_repository='extensions.duckdb.org';`

Note that this requires switching manually between endpoints. We could consider expanding this to be able to have multiple repo's that are searched in order to smoothen this process.

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Once this is merged, it would be great to add some more information about out of tree extensions to the docs!

**Comment by samansmink** [comment]
@Alex-Monahan for sure! We're working on a boilerplate repository template that will ease the process of third party extension development/maintenance. With some good docs, the whole process of starting development/publishing/maintaining should be very smooth!

**Comment by carlopi** [comment]
Really cool feature, great work.

---

One idea/proposal: would it not be possible to specify / list extensions C++ side instead of using custom command line variables?

Very sketchy, I was thinking something along the lines of:

```c++
//// extension amalgamation file
#include "relative/path/to/duckdb/some_duckdb_cusom_header.h"
#include "relative/path/to/my_extension/folder/my_extension_include_header.h"
#include "relative/path/to/my_other/extension/somewhere/else/my_other_extension_include_header.h"

my_extension::ExtensionClass</*statically linked*/ true> instanceOfExtension;
my_other_extension::ExtensionClass</*statically linked*/false> instanceOfMyOtherExtension;


int main()
{
      instanceOfExtension.register("someName");
      instanceOfMyOtherExtension.register("someOtherName");
}
```

And then while building/linking this file, auto-magically things fall into place.

Advantage would be that the logic stays in a C++ file, that should be easier to check-in a repo / move around, and that errors would be handle by the build step. I think in theory this should give all necessary flexibility, as in it allows to specify (relatives or absolute) paths to extension plus optionally renaming / scoping, and errors would not to have been detected by us but will be handled uniformly by the C++ compiler / tooling.

This can (should?) be consider as next step / refinement, not really something to act on right now, also it might need some more thinking.

(and more of the same, a similar solution could also be conceived for in-tree extensions, going uniformly about it reducing the number of variables/dependencies implicitly passed around, and allowing even extensible extensions)

**Comment by samansmink** [comment]
@carlopi thanks for your comment, interesting idea! I'm not sure if fully understand the reasoning behind why this would be beneficial over the current setup i have here though. Also consider the case where you have 2 out-of-tree extensions A and B. Now imagine a user that wants to build a duckdb binary with both these extensions linked. Where would this cpp file specifying these two (unrelated) extensions live? wouldn't this require the user to write a cpp file to specify his build configuration? I feel like using a cpp file for the build specification is counter intuitive and having the build config params as cmake variables makes more sense there.

**Comment by carlopi** [comment]
I was probably thinking that extensions needs to be in a default discoverable path (say extensions/${{repo owner}}/${{repo name}} scheme to disambiguate + potentially falling back/requiring GitHub act as a registry of sort.

I don't completely see the full solution either, and don't want to block any work on this, also since this can be potentially (after some more thoughts) build next to / using the current building blocks.

---

What I was trying to figure out are workflows for situations like:
You have extension A, that itself is a combination/depends on extensions B and C.
Then you have to specify A, B, C, locations + or it can be that you just say "I want A" and the build systems figures out that B and C also needs to be pulled in?

And then when there are more that a handful, I can see things getting out of hands + having difficult to reproduce situations / bugs that are dependent on local state.

**Pull request merged**
