### PR TITLE
Fix fuzzer issue w.r.t. NULL values in generate_series

### PR DESCRIPTION
**Pull request by Mytherin**

### CODE REVIEW

**Comment by PedroTadim** [comment]
I expect it would be better to throw an error on NULL? Also, this could be generalized to other table UDFs.

**Comment by Mytherin** [comment]
This is the behavior that Postgres has - I would prefer to copy that behavior.

**Comment by PedroTadim** [comment]
Sure, that's a good reason

**Comment by PedroTadim** [comment]
`SELECT c0 FROM range(NULL) t3(c0);` goes on an infinite loop, maybe this is not expected.

**Comment by Mytherin** [comment]
Hah, maybe not no :)

**Pull request merged**
