### PR TITLE
[Python][Dev] Skip pyarrow `test_struct_filter_pushdown` on python3.8

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes https://github.com/duckdblabs/duckdb-internal/issues/1158

As the comment says, this doesn't become an ARROW_SCAN on python3.8

### CODE REVIEW

**Comment by Maxxen** [comment]
Why is this a problem for just the struct_pushdown test and not the other filter pushdown tests?

**Comment by Tishj** [comment]
Because for some reason it doesn't make an arrow table, it becomes a pandas df with an `object` column

**Comment by Tishj** [comment]
> Is it possible that only older pyarrow versions are available for py3.8, which causes this?

I'll reply with the installed versions of pyarrow and pandas on py3.8 where I reproduced this 👍

**Comment by Tishj** [comment]
```
>>> import pyarrow
>>> pyarrow.__version__
'15.0.0'
>>> import pandas
>>> pandas.__version__
'2.0.3'
```

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
