### PR TITLE
Fix python flaky test (potentially GET requests gets back 403)

### PR DESCRIPTION
**Pull request by carlopi**
Last few Python CI jobs failed due to this: https://github.com/duckdb/duckdb/actions/workflows/Python.yml.

### CODE REVIEW

**Comment by carlopi** [comment]
This will fail, again, not exactly sure what's the right catch, should be trivial but I don't see it, maybe some pythonista can take this further

**Comment by carlopi** [comment]
Actually decided on removing the test on the json, since failing CI is in any case not great, someone / me of the future can than add this back again.

**Comment by Mytherin** [comment]
Thanks! Best to leave it out if it is flaky indeed. Perhaps this can be moved to the Linux HTTPFS test suite?

**Comment by carlopi** [comment]
I was taking a look with @Tishj, he found also the second test in that file should be modified to catch a `duckdb.HTTPException` instead of `RuntimeError`, and I am not sure if users are expected to catch on what.

We can check later on how you want to address it / where should this be moved.

**Pull request merged**
