### PR TITLE
fix for ODBC issue with System.Data.Odbc GetSchema() #6321

### PR DESCRIPTION
**Pull request by bucweat**
This is a fix for errors when using the ODBC driver with .Net System.Data.Odbc GetSchema() version 4.8. The issue is described in #6321. I'll include the relevant parts here.

The change in statement.cpp fixes a problem where .NET System.Data.Odbc requests information about tables "TABLE,SYSTEM TABLE". DuckDB does not have a table called "SYSTEM TABLE" and the regex_replace() calls do not handle the extra table correctly. The solution is just to remove "SYSTEM TABLE" from the query and then continue processing as before. 

The change in api_info.cpp have to do with how GetAttribute() in [statement.cpp](https://github.com/duckdb/duckdb/blob/master/tools/odbc/statement.cpp#L408) handles SQL_COLUMN_PRECISION (set using desc_record->sql_desc_precision) and SQL_COLUMN_SCALE (set using sql_desc_scale ) for field type VARCHAR. In the current code these both return -1 which comes from [api_info.cpp](https://github.com/duckdb/duckdb/blob/master/tools/odbc/api_info.cpp#L95). 

From [this reference](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size?view=sql-server-ver16) I believe that sql_desc_precision should match the length of char array and not -1. In this case I selected 512 given UTF-8. To be honest this should probably be determined based on the size of the variable, but it is beyond my knowledge of DuckDB to figure that out. 

As for SQL_COLUMN_SCALE, this one was harder to find a good reference for. What I did note is that a fair amount of the other fields set MINIMUM_SCALE and MAXIMUM_SCALE to 0 instead of -1 used by VARCHAR (and CHAR too). So I tried using 0 for both, and code started working.

### CODE REVIEW

**Comment by bucweat** [comment]
It looks like one of the psqlodbc failed. It is failing on [CHECK_STMT_RESULT(rc, "SQLGetTypeInfo failed", hstmt);](https://github.com/Mytherin/psqlodbc/blob/402be53270c35ac8782d836540a3b56a85f5c7e3/src/catalogfunctions-test.cpp#L51) which makes sense as this "documents" the mod I made to api_info.cpp to make it work with .Net System.Data.Odbc. 

Looking at the [PostgreSQL ODBC driver catalogfunctions.out](https://git.postgresql.org/gitweb/?p=psqlodbc.git;a=blob_plain;f=test/expected/catalogfunctions.out;hb=15eba3aa7831e4343a96c55ec1acb6f3584ab6fa) it has a COLUMN_SIZE of 255 (I used 512 because I thought I might have to account for UTF-8 but happy to go with 255). The other difference is MINIMUM_SCALE and MAXIMUM_SCALE are both NULL which in C++ is 0. 

So I guess I'm wondering where the -1 values came from and why they were changed from the psqlodbc original values.

**Comment by Mytherin** [comment]
The psqlodbc tests are in [this fork](https://github.com/Mytherin/psqlodbc) with the [expected functions](https://github.com/Mytherin/psqlodbc/blob/main/expected/catalogfunctions.out). Perhaps just revert the change to the API info for now and move that to a separate PR?

**Comment by bucweat** [comment]
> The psqlodbc tests are in [this fork](https://github.com/Mytherin/psqlodbc) with the [expected functions](https://github.com/Mytherin/psqlodbc/blob/main/expected/catalogfunctions.out). 

Yeah found those and was comparing [catalogfunctions.out](https://github.com/Mytherin/psqlodbc/blob/main/expected/catalogfunctions.out) from there to the most recent version in [psqlodbc files](https://git.postgresql.org/gitweb/?p=psqlodbc.git;a=blob_plain;f=test/expected/catalogfunctions.out;hb=15eba3aa7831e4343a96c55ec1acb6f3584ab6fa) which I believe would work with my change. Trying to understand why @tiagokepe decided to not use the original psqlodbc file and instead changed the values for VARCHAR to -1...I looked for commit comments on  to place blame but found none...do you have any ideas?

> Perhaps just revert the change to the API info for now and move that to a separate PR?

GIven both changes are required to fix .Net System.Data.Odbc issue, and the query regex fix doesn't seem to affect other ODBC drivers and hence doesn't provide any benefit, I'm not sure separating them makes any sense.

**Comment by bucweat** [comment]
Here is an update of sorts WRT the second issue mentioned above in api_info.cpp. 

I was able to track down @tiagokepe. The BLUF is that he does not remember exactly why the changes to -1 were made (see comment below). He does mention "...on the DuckDB behaviour that might slightly be different from PostgreSQL." which is something I can't argue against as I don't understand the guts of DuckDB and I'm having a hard time tracking down how the -1 values are used internally in DuckDB. WRT the docs I have a bit of a leg to stand on...

Anyway,  are some snippets from email conversation (with very slight edits to my responses):

> @tiagokepe: About ODBC I don't remember exactly the reasons behind those changes, but what I can tell is that they were based on the ODBC Microsoft documentation and on the DuckDB behaviour that might slightly be different from PostgreSQL.
> Look at this point in the code and ODBC docs:
> - [api_info](https://github.com/duckdb/duckdb/blob/master/tools/odbc/include/api_info.hpp#:~:text=case%20SQL_VARCHAR%3A,return%20SQL_SUCCESS%3B)
> - [ODBC column-size](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size?view=sql-server-ver15#:~:text=%5Bb%5D%20If%20the%20driver%20cannot%20determine%20the%20column%20or%20parameter%20length%20for%20a%20variable%20type%2C%20it%20returns%20SQL_NO_TOTAL.)

WRT SQL_COLUMN_PRECISION:

> @tiagokepe: DuckDB doesn't have a fixed column size for VARCHAR, and the ODBC doc says that in this case the drivers can return SQL_NO_TOTAL, but this doesn't work for some applications, which is confusing because they should support that.

> @bucweat: I see that mentioned here [Column Size - ODBC API Reference ](https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size?view=sql-server-ver16) in (b) so understand your confusion. SQL_NO_TOTAL is defined as -4 in sqlext.h. Based on my interpretation of the doc, the two options available are "The defined or maximum column size in characters of the column or parameter" or SQL_NO_TOTAL, and if SQL_NO_TOTAL (-4) is not working then only option left would be defined or maximum column size. psqlodbc uses 256 in their unit tests. I did not dig into the code to see if there is any other option. 

As a follow up, I tried -4 (the value for SQL_NO_TOTAL) in place of -1 and it did not work for System.Data.Odbc.

WRT SQL_COLUMN_SCALE:

> @tiagokepe: You also can test the column_size with SQL_NULLABLE instead of -1, I'm not sure about the consequences here, so we must check the results on all test cases.
Look at: [ApiInfo::ODBC_SUPPORTED_SQL_TYPES](https://github.com/duckdb/duckdb/blob/master/tools/odbc/api_info.cpp#:~:text=%7B%22%27VARCHAR%27%22%2C%20SQL_VARCHAR%2C%20%2D1%2C)

> @bucweat:  GetColumnSize() from [api_info](https://github.com/duckdb/duckdb/blob/master/tools/odbc/include/api_info.hpp#:~:text=case%20SQL_VARCHAR%3A,return%20SQL_SUCCESS%3B) returns 256 which is works fine. 

> The issue is in statement.cpp [SQL_COLUMN_SCALE](https://github.com/duckdb/duckdb/blob/master/tools/odbc/statement.cpp#L546) and [SQL_COLUMN_PRECISION](https://github.com/duckdb/duckdb/blob/master/tools/odbc/statement.cpp#L558) which uses values set in [SetSqlDescType()](https://github.com/duckdb/duckdb/blob/master/tools/odbc/descriptor.cpp#L854) and those values come from [ApiInfo::ODBC_SUPPORTED_SQL_TYPES](https://github.com/duckdb/duckdb/blob/master/tools/odbc/api_info.cpp#:~:text=%7B%22%27VARCHAR%27%22%2C%20SQL_VARCHAR%2C%20%2D1%2C) (COLUMN_SIZE which you highlighted, and also two other columns MINIMUM_SCALE, and MAXIMUM_SCALE from VARCHAR entry.

> As for SQL_COLUMN_PRECISION (assigned from MAXIMUM_SCALE), the best reference I could find was [this](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetdescfield-function?view=sql-server-ver16). If you search for "SQL_DESC_PRECISION" it says "...This field is undefined for all other data types." and I'm not sure how to represent "undefined". For psqlodbc they use NULL which in C++ is 0. I used 0 and that worked.

> BTW those switch cases are not called when calling GetSchema() from ADO...only from .Net. Those are the only two implementations I have to test with.

As a followup, the DuckDB unit test will fail as the expected values are both -1. That is the only test that failed so not sure if the test coverage would bubble up an issue with any particular ODBC implementation.

**Comment by Mytherin** [comment]
Closing as this is most likely superseded by changes to the ODBC made by @maiadegraaf

**Pull request closed without merging**
