### PR TITLE
Date functions on Windows

### PR DESCRIPTION
**Pull request by chilarai**

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good. Could you fix the formatting issues?

**Comment by chilarai** [comment]
Sure

**Comment by Mytherin** [comment]
It seems the format tests are still failing. Could you run `make format-fix` or `python3 scripts/format.py` or do these not work for you?

**Comment by chilarai** [comment]
> It seems the format tests are still failing. Could you run `make format-fix` or `python3 scripts/format.py` or do these not work for you?

Sorry got busy somewhere. I will fix them. 
Yes, the Python scripts don't work on my machine as I haven't configured them properly.

Apart from that, I believe I have to work on some other issues on duckdb::Connection Query. They don't work with production mode with Qt. I Will need to check that as well. Could that be the related to #2023 ?

**Comment by Mytherin** [comment]
> Apart from that, I believe I have to work on some other issues on duckdb::Connection Query. They don't work with production mode with Qt. I Will need to check that as well. Could that be the related to #2023 ?

#2023 should be fixed and the CSV reader should not throw exceptions internally anymore (unless an actual error happens), but note that DuckDB requires exceptions to be enabled to be able to report errors correctly.

**Comment by chilarai** [comment]
> > Apart from that, I believe I have to work on some other issues on duckdb::Connection Query. They don't work with production mode with Qt. I Will need to check that as well. Could that be the related to #2023 ?
> 
> #2023 should be fixed and the CSV reader should not throw exceptions internally anymore (unless an actual error happens), but note that DuckDB requires exceptions to be enabled to be able to report errors correctly.

I should have mentioned my issue more clearly. I meant to say, duckdb::Connection Query doesn't allow the dll to go on production as my application immediately crashes. Does the duckdb::Connection also use the same Try/Catch block as the previous CSV reader code? Current, CSV reader is fine

**Comment by chilarai** [comment]
I will enable the CPP exceptions and check in detail though

**Comment by Mytherin** [comment]
Could you fix the remaining formatting problems?

**Pull request merged**
