### PR TITLE
[Dev] Python test random deadlock fix

### PR DESCRIPTION
**Pull request by Tishj**
This PR should fix the random deadlock on `test_to_csv.py`

The problem has manifested in a couple unrelated PRs, namely:
`https://github.com/duckdb/duckdb/actions/runs/4129399926/jobs/7141659107`

Steps taken to (hopefully) address the issue:
- make all tests use their own duckdb connection
- switching from using `tempfile` directly, make use of `tmp_path` fixture provided by `pytest`

### CODE REVIEW

**Comment by Tishj** [comment]
Actually.. looking at my local CI, the issue doesn't seem to be fixed

**Comment by Mytherin** [comment]
Good investigating! It is definitely that test. If I add a loop it gets stuck rather fast (within a few hundred iterations):

```py

    def test_to_csv_timestamp_format(self):
        i = 0
        while True:
            i += 1
            print(i)
            temp_file_name = os.path.join(tempfile.mkdtemp(), next(tempfile._get_candidate_names()))
            data = [datetime.time(hour=23, minute=1, second=34, microsecond=234345)]
            df = pd.DataFrame(
                {'0': pd.Series(data=data, dtype='object')}
            )
            rel = duckdb.from_df(df)
            rel.to_csv(temp_file_name, timestamp_format='%m/%d/%Y')

            csv_rel = duckdb.read_csv(temp_file_name, timestamp_format='%m/%d/%Y')

            assert rel.execute().fetchall() == csv_rel.execute().fetchall()
```

**Comment by Mytherin** [comment]
Ah, I think I know why. This line triggers execution, but does not contain the GIL release code:

```py
rel->WriteCSV(filename, std::move(options));
```

This can cause a deadlock when combined with the Pandas scan.

**Comment by Mytherin** [comment]
Working on a fix.

**Pull request closed without merging**
