### PR TITLE
Adding custom type

### PR DESCRIPTION
**Pull request by handstuyennn**
Hi @Mytherin,

Continuing from [this thread](https://github.com/duckdb/duckdb/pull/3068#issuecomment-1045250426) and conversation, I have pushed a PR for creating a `CUSTOM TYPE`. 

Could you please review PR this and let me know your suggestions?

Thank you.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

This seems to be editing an enormous amount of code, adding an extension, and pushing tons of code into the different client APIs. That all seems unnecessary for this feature.

Adding `CREATE TYPE` as described can re-use the existing type catalog entry, and can be tested without adding a new external extension. It should be a rather compact change that allows adding (named) aliases to structs. It should not require an enormous amount of code changes. Certainly changing so many internal structures and client APIs is unnecessary.

**Comment by handstuyennn** [comment]
Hi @Mytherin,

Thank you for the feedback. PR updated with your feedback.

**Comment by Mytherin** [comment]
This PR is still far too large and doing a lot of things that should not be required for this change as indicated before (e.g.. introducing the new `CUSTOM` type and catalog entry rather than using the existing infrastructure). This PR is not merge-able without a complete rework so I will close it.

**Comment by handstuyennn** [comment]
> It should be a rather compact change that allows adding (named) aliases to structs

@Mytherin,
I really want to finish adding type for duckdb.
I have investigated about structure of duckdb's types but I couldn't find the structs which can be adding (named) aliases to. Could you give me a name of struct or where can I find this struct?

**Comment by handstuyennn** [comment]
Do you mean that the **CUSTOM TYPE** should implemented as an alias to a STRUCT type such as:
`CREATE TYPE Person AS {name STRING, age INT};`
I had tried to implement a fully customizable type in the manner of the Postgres custom type to support arbitrarily complex types, including input/output functions. This was meant for providing the foundation to build a true GEO type on top of it, as I mentioned before. An example of a custom type that basically has first-class support would be this CUSTOM ltree TYPE from Postgres: https://www.postgresql.org/docs/current/ltree.html --> https://github.com/postgres/postgres/tree/master/contrib/ltree

**Comment by Mytherin** [comment]
I understand the goal, and appreciate the effort you have put in, but submitting large PRs is discouraged for outside contributors because reviewing such PRs is extremely difficult and a lot of work. Not to mention that in large PRs mistakes are much more likely to be missed.

Instead, it is a better idea to attack small pieces of the problem rather than trying to solve the entire problem in one giant PR that will take many iterations to review, fix and merge.

The way I see custom types is that you want to do a few different things with them:

* Provide a way of creating a (named) alias to an existing type (e.g. a struct)
* Provide a way of binding the type in functions, so functions can be created that take the type as input or output the type.
* Provide cast operators to and from this type (e.g. a way of going from this type to a string, or from a string to this type)

The first step should be relatively easy, and can use a lot of the existing infrastructure. You should be able to create a type using SQL, add regular SQL tests, use the existing `TypeCatalogEntry` to store it, etc. This is the starting point and what the first PR towards implementing this feature should contain.

After the first step is completed, I'm happy to discuss how we can implement the second and third steps and progressively get towards custom types being full first class citizens in DuckDB.

**Comment by handstuyennn** [comment]
@Mytherin 

For first step, I would like to add new `LogicalType` name `ALIAS` (like `ENUM`). Alias type stores internal logical type inside create info. I'm going to store `ALIAS` catalog in `TypeCatalogEntry` (like `ENUM` too).

Here is sample SQL query for create new alias:
`CREATE TYPE alias_name AS VARCHAR;`

Please give me your advise.

**Comment by Mytherin** [comment]
Rather than creating a new logical type `ALIAS`, I think it would be much easier/cleaner to add an optional alias inside the `ExtraTypeInfo`. If no `ExtraTypeInfo` is defined the alias is the empty string. Aliases can then be taken into account in the equality/hash of a logical type which causes the binding to work as expected.

**Pull request closed without merging**
