### PR TITLE
Fix #2301: ART Leaf Node shrink

### LINKED ISSUE #2301: The Leaf Node of ART needs to be shrunk dynamically.
Found in the comment: 

https://github.com/duckdb/duckdb/blob/7dd852e1dd7aa521e76cbf6f756da487e2e1a1cd/src/execution/index/art/leaf.cpp#L27

The leaf node is for the values having the same key. (each prefix byte of the key is the same).
The idea is similar to a C++'s STL `std::multimap`.
However, it is not clear, how many duplicates can exist in a leaf node.
Thus, the leaf node should dynamically grow and shrink.
(The dynamical grow part is a must and is already implemented.)

### PR DESCRIPTION
**Pull request by JigaoLuo**
Fix #2301 
However, as said, the shrinking of ART leaf node is not a must, while the growing of it is a must.

### CODE REVIEW

**Comment by pdet** [comment]
I think it looks good, although you can probably replace the for+copy loops for memcpy.

Can you also add a test where you create x elements, delete less than x/2, check sum, delete more to force the shrinking, and check again? Also, this test shouldn't be in the test_slow suit, it looks like it should be fairly fast to run it, so there is no reason to only run it on the optimized build of the CI.

**Comment by cakebytheoceanLuo** [comment]
Thanks for the comments.

> replace the for+copy loops for memcpy.

- Done.

> Can you also add a test where you create x elements, delete less than x/2, check sum, delete more to force the shrinking, and check again?

- Test Updated.

> this test shouldn't be in the test_slow suit

- Renamed to `.test`

**Comment by cakebytheoceanLuo** [comment]
A simple ART-relevant TODO:
https://github.com/duckdb/duckdb/blob/7dd852e1dd7aa521e76cbf6f756da487e2e1a1cd/src/execution/index/art/node16.cpp#L13

This part is mentioned in the ART paper as well as in [Viktor's Code](http://www-db.in.tum.de/~leis/index/ART.tgz)
However, it is discouraged to write explicit SIMD intrinsics in DuckDB: https://github.com/duckdb/duckdb/issues/855#issuecomment-676602791

So I think I can remove this TODO. Is that okay?

**Review by pdet — CHANGES_REQUESTED** [review]
The test you've added is only inserting and deleting a new value, no?

I meant more something like (with the proper checks)

``` sql

create table t as select range a, 1 b from range(64);

create index b_index ON t(b)

select sum(b) from t

delete from t where a < 10

select sum(b) from t

delete from t where a < 35

select sum(b) from t

```

**Comment by pdet** [comment]
@cakebytheoceanLuo yeah, I think at the time was not clear if we would allow explicit SIMD, I think it can be removed now.

**Comment by pdet** [comment]
@cakebytheoceanLuo the format checker is breaking, you might have to run
``` make format-fix ```

 and commit/push again.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
