### PR TITLE
Add relational tests back

### PR DESCRIPTION
**Pull request by Tmonster**
To get CI passing, we took out some relational tests. Looked into the issue and I think I've solved it so that we can run `test_relational.R` once again.

@krlmlr, @hannes any guesses as to why this error is appearing now?

### CODE REVIEW

**Review by carlopi — COMMENTED** [review]
I am not able to give any feedback on this

**Comment by krlmlr** [comment]
Not sure why we need to do that much. Tests seem to pass if we only remove the `skip()` call?

To run an individual test file, use:

```r
testthat::test_local(filter = "^relational$")
```

**Comment by krlmlr** [comment]
I was mistaken: we can remove the `skip()` call on the latest version of your branches combined. But we could do that separately, I still don't think changing the tests should be necessary at all.

**Comment by Tmonster** [comment]
@krlmlr I don't want to change the tests, but without the change in this PR (i.e `as.data.frame.duckdb_relation`) we continue to get the following error during CI. Do you have an idea as to why this is?

image

**Comment by krlmlr** [comment]
I've seen this too in #6048, but not when applying to your latest WIP PRs. Maybe it's worth enabling the tests in one of those?

**Comment by Tmonster** [comment]
The error happens in CI or when you run the tests on an ubuntu image. I can't recreate the error locally either. It makes me think that there has been some update somewhere in the dependencies where we now have to specify the extra `.duckdb_relation`

**Pull request merged**
