### PR TITLE
`OR`/`IN` filter pushdown for `VARCHAR`

### PR DESCRIPTION
**Pull request by lnkuiper**
This was only implemented for integral types, so this PR adds support for strings (also works for dynamic join filter pushdown!).

To prevent regressions in IMDB, I had to add a special case for `OPTIONAL_FILTER`s in `row_group.cpp` so that these are skipped for scanning vectors (they are only used for row group checking anyway).

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! Could we add a benchmark as well that checks the performance improvement?

I don't see any changes related to the dynamic filter pushdown - did that already work previously or am I missing something?

**Comment by lnkuiper** [comment]
@Mytherin Thanks for the review! I've added a few benchmark files that test the behavior:
```
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/release/benchmark/benchmark_runner benchmark/micro/pushdown/or_varchar_pushdown.benchmark
name	run	timing
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	1	0.149487
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	2	0.152318
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	3	0.150304
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	4	0.154057
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	5	0.156211
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/release/benchmark/benchmark_runner benchmark/micro/pushdown/in_varchar_pushdown.benchmark 
name	run	timing
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	1	0.149813
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	2	0.150118
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	3	0.151343
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	4	0.151153
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	5	0.152979
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/release/benchmark/benchmark_runner benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark 
name	run	timing
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	1	0.260337
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	2	0.260146
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	3	0.259904
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	4	0.263196
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	5	0.261264
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/reldebug/benchmark/benchmark_runner benchmark/micro/pushdown/or_varchar_pushdown.benchmark
name	run	timing
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	1	0.001852
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	2	0.002059
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	3	0.001909
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	4	0.001988
benchmark/micro/pushdown/or_varchar_pushdown.benchmark	5	0.001868
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/reldebug/benchmark/benchmark_runner benchmark/micro/pushdown/in_varchar_pushdown.benchmark 
name	run	timing
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	1	0.001907
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	2	0.001908
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	3	0.001958
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	4	0.002131
benchmark/micro/pushdown/in_varchar_pushdown.benchmark	5	0.002057
(my-venv) [laurens@mac] ~/git/duckdb/duckdb (or_varchar*)
$ ./build/reldebug/benchmark/benchmark_runner benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark 
name	run	timing
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	1	0.258381
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	2	0.257439
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	3	0.256559
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	4	0.257359
benchmark/micro/pushdown/join_filter_varchar_pushdown.benchmark	5	0.259957
```

You are right, the dynamic filter pushdown was working before - this confirms it.

**Comment by arjenpdevries** [comment]
Anecdotal evidence from a single query in text retrieval context: `SELECT termid, df FROM dict WHERE term IN ( 'radboud', 'university');` has become 3x as fast with this pull request. Before, I had to turn the query into a union by term before getting acceptable timings, now I can just use the query as it should be. Thanks!

**Comment by lnkuiper** [comment]
@Mytherin Forgot to push those yesterday. They are in now

**Comment by Alex-Monahan** [comment]
Amazing!!!! Thanks folks!!! This will be so helpful for the crazy queries out there...

**Pull request merged**
