### PR TITLE
R package: Add ability to specify output timezone

### PR DESCRIPTION
**Pull request by ateucher**
Recently, @krlmlr made a [great addition to the RPostgres R package](https://github.com/r-dbi/RPostgres/pull/276), which added a `timezone_out` argument to the `dbConnect()` method, allowing a user to specify a timezone in which `TIMESTAMP` columns would be returned to R.

This PR adds that functionality to the duckdb R package, and additionally adds a `tz_out_convert` argument, controlling the conversion from `UTC` to the timezone specified in `timezone_out`. Options for `tz_out_convert` are `"with"` (default), which shows the timestamp in the desired timezone, or `"force"` which overrides the timestamp timezone with the desired timezone. With default arguments, the behaviour is the same as current, so this is non-breaking.

A comprehensive test suite is included.

Example of the new behaviour:

``` r
library(duckdb)

# Default behaviour (unchanged):
con <- dbConnect(duckdb())
query <- "SELECT '1970-01-01 12:00:00'::TIMESTAMP AS ts"
dbGetQuery(con, query)[[1]]
#> [1] "1970-01-01 12:00:00 UTC"
dbDisconnect(con, shutdown = TRUE)

# Specify a timezone_out, leaving tz_out_convert = 'with' (default)
con <- dbConnect(duckdb(), timezone_out = "America/Vancouver")
query <- "SELECT '1970-01-01 12:00:00'::TIMESTAMP AS ts"
dbGetQuery(con, query)[[1]]
#> [1] "1970-01-01 04:00:00 PST"
dbDisconnect(con, shutdown = TRUE)

# Specify a timezone_out, setting tz_out_convert = 'force'
con <- dbConnect(duckdb(), timezone_out = "America/Vancouver", tz_out_convert = "force")

query <- "SELECT '1970-01-01 12:00:00'::TIMESTAMP AS ts"
dbGetQuery(con, query)[[1]]
#> [1] "1970-01-01 12:00:00 PST"
dbDisconnect(con, shutdown = TRUE)
```

<sup>Created on 2021-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note: This adds the `lubridate` package as a dependency in "Imports", and `withr` to "Suggests" for testing.

I know this was unsolicited, so I won't be offended if you're not keen on taking it. The use case is: I have a large dataset (csv) that was collected and stored in `"PST"` - loading it into `duckdb` assumes it is UTC and stores it as such, so when querying the database the results returned to R are in UTC. This added functionality allows a user to specify the timezone in which the data are returned, and whether or not the clock time should be adjusted or if timezone should be just overridden.

Thanks very much for duckdb!

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Thanks for the PR, I wonder whether it might make sense to normalise dates on the way into DuckDB as well, so they are correctly stored as UTC there and you can then indeed convert them back into another TZ on querying.

**Comment by ateucher** [comment]
It probably does make sense to normalize datetimes to UTC on their way in to DuckDB - I think this could be fairly straightforward to do when writing an existing R data.frame into DuckDB (i.e., using `dbWriteTable`), though I don't think it's currently possible when the csv is loaded directly to DuckDB (e.g., using `duckdb_read_csv())`, since DuckDB itself doesn't currently support that functionality. Is that right?

If that is correct, I see a potential risk in there being different behaviours for different ways of loading data into DuckDB from R. A user could initally load a csv into DuckDB using `duckdb_read_csv()` where the data is treated as UTC, and could then append to that table from a data.frame in R using `dbWriteTable()`, where the timestamps are normalized to UTC... thus ending up with a mismatch in timezones, potentially without the user realizing it...

**Comment by ateucher** [comment]
Hi @hannesmuehleisen - is there anything you need from me on this?

**Comment by hannesmuehleisen** [comment]
Sorry for the delay. Would it be possible to add this parameter without adding the `lubridate` dependency? We are quite hesitant to add hard dependencies. Lubridate also depends on RCpp, adding yet another heavy transitive dependency.

**Comment by ateucher** [comment]
No problem about the delay. You've merged some big (and very welcome) enhancements recently. 

That's a good point, I'll see what I cam do.

**Comment by hannesmuehleisen** [comment]
Looks great, thanks!

**Comment by ateucher** [comment]
Fantastic, thank you! Sorry I didn't ping you that I was done - I was going to check the performance of this approach using base R vs lubridate (lubridate is often faster)... would you like me to do that?

**Pull request merged**
