### PR TITLE
feature: add maven config

### PR DESCRIPTION
**Pull request by Mause**
This will make it far easier to work on the jdbc bindings, allow us to improve the tests as well, and is another step in the direction of publishing prerelease builds of the jdbc client

Many thanks to @jonathanswenson who helped sort out some of the CMake configuration

Some of work is still to be done on the [jdbc_maven_deploy.py](https://github.com/duckdb/duckdb/blob/master/scripts/jdbc_maven_deploy.py) to support snapshots as well as to use the javadoc and sources companion jars built as part of this work

This will also hopefully unblock https://github.com/duckdb/duckdb/pull/4071

### CODE REVIEW

**Comment by hannes** [comment]
Hm, I think this needs a little more discussion

**Comment by Mause** [comment]
> Hm, I think this needs a little more discussion

Sure, which part?

**Comment by hannes** [comment]
Ah I remembered. This inserts maven into the build process, which was not required so far, it was only needed it to upload releases. I am a bit apprehensive to add this to the default build. What's the rationale for doing this? Could we not just as before use the existing upload script, just also to push SNAPSHOT releases?

**Comment by Mause** [comment]
As discussed via Zoom, going to flip this around to invoke cmake from Maven instead, in another pr

**Comment by jonathanswenson** [comment]
@Mause Let me know if I can help in any way here!

**Pull request closed without merging**
