### PR TITLE
Implement JNI class, method and field caching

### PR DESCRIPTION
**Pull request by Jens-H**
This PR implements caching of Java classes, method and field IDs for the JNI. It is based on the IBM best practices for JNI [1] and answers on stackoverflow [2]. I could see a performance increase of about 30% in an ideal situation (only varchars), but particularly with the JVM your mileage may vary anyway.  

The changes touch basically every function, but things are just moved around.

[1] https://developer.ibm.com/articles/j-jni/ 
[2] https://stackoverflow.com/questions/10617735/in-jni-how-do-i-cache-the-class-methodid-and-fieldids-per-ibms-performance-r/13940735#13940735

### CODE REVIEW

**Comment by rkennedy-mode** [comment]
Fabulous. I was working on similar changes as part of some other enhancements I was working on (829a64bf9a6e529e54ca87ea8d9be54b0d6a5a39). But that effort was largely abandoned and my version of the same optimization was left behind.

**Comment by hannes** [comment]
Oops, did not see the failing Windows 32 Bit run there.

**Comment by hannes** [comment]
trying to fix in https://github.com/hannes/duckdb/tree/jnifix

**Comment by Jens-H** [comment]
Thanks Hannes for helping out ...

**Pull request merged**
