### PR TITLE
Fix the `lineitem` table schema definition error of TPC-H

### LINKED ISSUE #7098: TPC-H `lineitem` table schema definition error
### What happens?

In the [TPC-H documentation](https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v2.17.1.pdf), `l_quantity` of `lineitem` table is defined as a `decimal` type.
However, duckdb incorrectly defines it as an `INTEGER` type:
```shell
> parquet-schema ./data/tpch_1/lineitem.parquet
Metadata for file: ./data/tpch_1/lineitem.parquet

version: 1
num of rows: 6001215
created by: DuckDB
message duckdb_schema {
  OPTIONAL INT32 l_orderkey (INT_32);
  OPTIONAL INT32 l_partkey (INT_32);
  OPTIONAL INT32 l_suppkey (INT_32);
  OPTIONAL INT32 l_linenumber (INT_32);
  OPTIONAL INT32 l_quantity (INT_32);  ## <-- this
  OPTIONAL INT64 l_extendedprice (DECIMAL(15,2));
  OPTIONAL INT64 l_discount (DECIMAL(15,2));
  OPTIONAL INT64 l_tax (DECIMAL(15,2));
  OPTIONAL BYTE_ARRAY l_returnflag (UTF8);
  OPTIONAL BYTE_ARRAY l_linestatus (UTF8);
  OPTIONAL INT32 l_shipdate (DATE);
  OPTIONAL INT32 l_commitdate (DATE);
  OPTIONAL INT32 l_receiptdate (DATE);
  OPTIONAL BYTE_ARRAY l_shipinstruct (UTF8);
  OPTIONAL BYTE_ARRAY l_shipmode (UTF8);
  OPTIONAL BYTE_ARRAY l_comment (UTF8);
}
```

### To Reproduce

As can be seen in the duckdb source code: https://github.com/duckdb/duckdb/blob/eaf507009fd06573d74cc5742a8643481883a0ff/extension/tpch/dbgen/dbgen.cpp#L405-L415

### OS:

macOS

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

r.4ntix

### Affiliation:

Alibaba Cloud

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by r4ntix**
Close #7098

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Have you tested this locally? Just changing the type is not sufficient as now the incorrect data is being generated. You will need to modify the append code in `append_line` by multiplying `quantity` by 100 and using `append_decimal` instead.

**Comment by r4ntix** [comment]
> Thanks for the PR! Have you tested this locally? Just changing the type is not sufficient as now the incorrect data is being generated. You will need to modify the append code in `append_line` by multiplying `quantity` by 100 and using `append_decimal` instead.

Thanks for the feedback! 
I did a `make unit` test locally and it doesn't look like that's enough. I'll take this PR as a draft and open it after I verify it locally, thanks!

**Comment by Mytherin** [comment]
Ah yes, `make unit` only runs the faster unittests which likely don't include the TPC-H tests. You can run `make allunit` to run all unit tests, or alternatively run the specific failing tests as marked by the CI.

**Comment by Mytherin** [comment]
Hm, that is interesting, I have not seen these issues before. On what OS/CPU architecture are you running these tests? These seem like odd floating point issues.

**Comment by r4ntix** [comment]
> Hm, that is interesting, I have not seen these issues before. On what OS/CPU architecture are you running these tests? These seem like odd floating point related issues.

This three test cases will fail every time in my environment, my environment is:
```
CPU: Apple M1 Pro
OS: macOS 13.3.1
```

**Comment by r4ntix** [comment]
> Try merging with master - they should be fixed now

Now that all the checks have passed, could you help review it?

**Comment by Mytherin** [comment]
Thanks for the updates! LGTM

**Pull request merged**
