### PR TITLE
[Explain] Add the `HTML` format for `EXPLAIN` statements

### PR DESCRIPTION
**Pull request by Tishj**
`EXPLAIN (FORMAT HTML) SELECT ...`

Will output (the source code of) an HTML page rendering the tree using [treeflex](https://dumptyd.github.io/treeflex/)

The final result will look something like this:
image

### Collapsing/Expanding Children

Every node that has at least one child will have a button underneath that can be used to collapse/expand the children.
By default all nodes are expanded.

The above output with a couple children collapsed looks more manageable:
image

### Jupyter

In the Python client, when using Jupyter, the `explain()` method of the `DuckDBPyRelation` will automatically use the HTML format and render the result using `IPython.display.HTML`:

image

### CODE REVIEW

**Comment by jeewonhh** [comment]
This look very cool! I tried it out and if you set explain_output='all' then the query plans overlap.

**Comment by Tishj** [comment]
> This look very cool! I tried it out and if you set explain_output='all' then the query plans overlap.

Ah that is something that I haven't tested, thanks for pointing this out, I'll have a look

**Comment by Tishj** [comment]
@jeewonhh issue should be fixed now :)

**Comment by Mytherin** [comment]
Thanks - LGTM. Could you just resolve the merge conflicts with the other PR?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
