### PR TITLE
Account for presence of varargs when casting table function arguments

### LINKED ISSUE #7244: Segmentation Fault when Invoking a Table Function that accepts Varargs
### What happens?

When invoking a table function that accepts varargs, a segmentation fault occurs.

The segmentation faults occurs on [this line](https://github.com/duckdb/duckdb/blob/master/src/planner/binder/tableref/bind_table_function.cpp#L260) where there is for loop over the vector supplied arguments with the goal of casting them to their expected types.  The current index of the loop is then used to index into the function's vector of defined arguments. Because of the use of varargs, this vector will be smaller, resulting in an out of bounds access.

### To Reproduce

I am working on an extension which includes a table function that allows passing arguments via varargs. I attempted to produce a minimal reproduction using an existing table function. However, I have not been able to find another table function that supports varargs argument calling semantics. I acknowledge that "use my table function" is not as succinct instruction as would be desired. Happy to work with folks on how best to provide minimal reproduction steps if this is not sufficient.

### OS:

Linux

### DuckDB Version:

HEAD

### DuckDB Client:

CLI

### Full Name:

Mark Roddy

### Affiliation:

launchit.ai

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by MarkRoddy**
Fixes [issue #7244](https://github.com/duckdb/duckdb/issues/7244)

### CODE REVIEW

**Comment by Tishj** [comment]
Thanks for the fix, it looks correct to me, I'm just wondering if maybe this requires adding a dummy table function that utilizes the varargs.
Wouldn't `summary` (`src/function/table/summary.cpp`) be a candidate to trigger this issue, since it has varargs support?
Or is the problem that this is a table-in-out function and not a regular table function?

**Comment by MarkRoddy** [comment]
Oh, I wasn't aware of `src/function/table/summary.cpp`. Let me take a look if that'll work for a reproduciton.

**Comment by MarkRoddy** [comment]
If I'm understanding this correctly (admittedly I'm not familiar with table-in-out functions), the varargs feature isn't used in case of the summary function. FWIW, I added test case that passes in extra values to the summary function, and it failed with this error:

```shell
Query unexpectedly failed (test/sql/function/generic/test_table_param.test:39)
================================================================================
SELECT * FROM summary((SELECT * FROM a), 2);
================================================================================
Actual result:
Binder Error: Subquery returns 2 columns - expected 1
```
I'm poking at enable varargs for that function atm. Let me know if I'm understanding this incorrectly though.

**Comment by MarkRoddy** [comment]
I just pushed a new function named `repeat_row()` which performs a similar operation as the `repeat()` function, except it does so on an arbitrary number of input values. I considered modifying the `repeat()` function to add this, but was worried about breaking backwards compatibility by changing its argument signature (the `repeat()` function assumes the second argument is the number of rows to repeat, where as this new function uses a named parameter to distinguish from the values to be repeated).

I reverted a2b441559afda81ee0b77f8e7b43a2a161054b40 locally and ran the included test. Can confirm this resulted in a segmentation fault reproducing the issue:
```bash
mark@ip:~/development/duckdb$ ./build/release/test/unittest --test-dir . "[generic]"
Filters: [generic]
[8/19] (42%): test/sql/function/generic/table_func_varargs.test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/function/generic/table_func_varargs.test
-------------------------------------------------------------------------------
/home/mark/development/duckdb/test/sqlite/test_sqllogictest.cpp:178
...............................................................................

/home/mark/development/duckdb/test/sqlite/test_sqllogictest.cpp:178: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:   9 |   8 passed | 1 failed
assertions: 232 | 231 passed | 1 failed

Segmentation fault (core dumped)
```

**Comment by MarkRoddy** [comment]
Fixed a failing test (was due to a network time out installing packages). Let me know if there any other thoughts or feedback on how to proceed.

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM

**Pull request merged**
