### PR TITLE
feat: `Relation::Query()` creates a temporary view on a read-only database

### PR DESCRIPTION
**Pull request by krlmlr**
From https://github.com/duckdb/duckdb-r/pull/138.

### CODE REVIEW

**Review by Tmonster — APPROVED** [review]

**Comment by Tmonster** [comment]
I think if the database is not read only, creating a persistent view might still be desirable behavior no?

**Comment by Mytherin** [comment]
In fact I would argue maybe this shouldn't create a view at all, but use a CTE instead?

**Comment by Mytherin** [comment]
The view is created here because the user can pass in an alias for the object that they want to query, as shown here:

```py
>>> q.query('my_view', 'select * from my_view')
```

But I think it would be cleaner to instead internally rewrite the SQL query by prepending a CTE, so we would get this:

```sql
WITH my_view AS (SELECT 42)
select * from my_view
```

That would have the same effect but in a stateless manner.

**Comment by krlmlr** [comment]
Thanks, Tom and Mark. Does this mean that

```cpp
unique_ptr<QueryResult> Relation::Query(const string &name, const string &sql);
```

shouldn't even exist?

On a second glance, I no longer understand the implementation of `rapi_rel_sql()` in the R client:

```cpp
[[cpp11::register]] SEXP rapi_rel_sql(duckdb::rel_extptr_t rel, std::string sql) {
	auto res = rel->rel->Query("_", sql);
	if (res->HasError()) {
		stop("%s", res->GetError().c_str());
	}
	return result_to_df(std::move(res));
}
```

This creates a view (is that view ever used used?), executes the query, and converts the result to a data frame. No ALTREP, nothing.

I'll work on the implementation in the R client.

**Comment by Tishj** [comment]
I also think `query` should not create a persistent view, a CTE indeed sounds much cleaner, having no side effects

**Pull request closed without merging**
