### PR TITLE
Use ccache action

### PR DESCRIPTION
**Pull request by krlmlr**
This speeds up build time for the debug build from > 7 to just shy of 2 minutes.

Build with cold cache: https://github.com/krlmlr/duckdb/actions/runs/514705674

Build with warm cache: https://github.com/krlmlr/duckdb/actions/runs/514741712

We should consider one of the following options, to avoid corruption of the GitHub action used here:

- Fork https://github.com/hendrikmuhs/ccache-action in the cwida organization and use our forked action
- Embed the action in this repository, use with the syntax `./.github/actions/ccache-action`
- Use a full SHA1 to refer to the current state of the action

We also need to enable ccache for the other builds. The size of the cache for the debug build is ~200 MB, this means there's enough space to store caches for other build variants. (The limit is 5 GB per repository, after that caches are evicted.)

CC @pat-s.

### CODE REVIEW

**Comment by krlmlr** [comment]
The "R package Windows" workflow consistently fails, also on the main branch. I'll take a look.

**Comment by hannesmuehleisen** [comment]
For some reason the tests did not run on the last commit?

**Comment by krlmlr** [comment]
Works now, the Valgrind failure looks like a false positive.

Build time still at < 1:30, plus ~10 seconds for fetching and storing the cache.

**Comment by krlmlr** [comment]
I wonder if it's possible to run the tests in parallel?

**Comment by hannesmuehleisen** [comment]
> I wonder if it's possible to run the tests in parallel?

They run in parallel no? And indeed the valgrind looks like a false positive

**Comment by krlmlr** [comment]
When I run `make unit`, `build/debug/test/unittest` consumes only one CPU core.

**Comment by hannesmuehleisen** [comment]
Ah the unit tests indeed they are single threaded

**Comment by hannesmuehleisen** [comment]
Otherwise this can be merged yes?

**Comment by hannesmuehleisen** [comment]
Thanks!

**Pull request merged**
