### PR TITLE
Optimize performance of jaccard function

### PR DESCRIPTION
**Pull request by ucasfl**
Use `supplier.tbl` of ssb with column NAME and ADDRESS to test(2 million rows).

Before optimize:
```sql
D explain analyze select jaccard(column1, column2) from 'data.csv';

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
explain analyze select jaccard(column1, column2) from 'data.csv';
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 0.687s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────_─────────────┘                              
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ jaccard(column1, column2) │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (13.97s)         │
└─────────────_─────────────┘                              
┌─────────────┴─────────────┐
│READ_CSV_AUTO (MULTI-T...  │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          column1          │
│          column2          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        EC: 4916324        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (6.58s)          │
└───────────────────────────┘          
```

After optimize:
```sql
D explain analyze select jaccard(column1, column2) from 'data.csv';                                                                                                                                                 
                                                                                                                                                                                                                    
┌─────────────────────────────┐                                                                                                                                                                                     
│┌───────────────────────────┐│                                                                                                                                                                                     
│└───────────────────────────┘│                                                                                                                                                                                     
└─────────────────────────────┘                                                                                                                                                                                     
┌─────────────────────────────────────┐                                                                                                                                                                             
│┌───────────────────────────────────┐│                                                                                                                                                                             
││    Query Profiling Information    ││                                                                                                                                                                             
│└───────────────────────────────────┘│                                                                                                                                                                             
└─────────────────────────────────────┘                                                                                                                                                                             
explain analyze select jaccard(column1, column2) from 'data.csv';                                                                                                                                                   
┌─────────────────────────────────────┐                                                                                                                                                                             
│┌───────────────────────────────────┐│                                                                                                                                                                             
││         Total Time: 0.298s        ││                                                                                                                                                                             
│└───────────────────────────────────┘│                                                                                                                                                                             
└─────────────────────────────────────┘                                                                                                                                                                             
┌───────────────────────────┐                                                                                                                                                                                       
│      EXPLAIN_ANALYZE      │                                                                                                                                                                                       
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                                                                                                                                                                                       
│             0             │                                                                                                                                                                                       
│          (0.00s)          │                                                                                                                                                                                       
└─────────────_─────────────┘                                                                                                                                                                                       
┌─────────────┴─────────────┐                                                                                                                                                                                       
│         PROJECTION        │                                                                                                                                                                                       
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                                                                                                                                                                                       
│ jaccard(column1, column2) │                                                                                                                                                                                       
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                                                                                                                                                                                       
│          2000000          │                                                                                                                                                                                       
│          (0.69s)          │                                                                                                                                                                                       
└─────────────_─────────────┘                                                                                                                                                                                       
┌─────────────┴─────────────┐                                                                                                                                                                                       
│READ_CSV_AUTO (MULTI-T...  │                                                                                                                                                                                       
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │                                                                                                                                                                                       
│          column1          │
│          column2          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        EC: 4916324        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (5.51s)          │
└───────────────────────────┘      
```

### CODE REVIEW

**Comment by carlopi** [comment]
We can likely get another order of magnitude faster using `std::bitset<MAX_SIZE>` instead of `std::array<char, MAX_SIZE>`.

**Comment by ucasfl** [comment]
> We can likely get another order of magnitude faster using `std::bitset<MAX_SIZE>` instead of `std::array<char, MAX_SIZE>`.

Not see improvement but degrade with `bitset`:

```
D explain analyze select jaccard(column1, column2) from 'data.csv';

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
explain analyze select jaccard(column1, column2) from 'data.csv';
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 0.262s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────_─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ jaccard(column1, column2) │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (2.47s)          │
└─────────────_─────────────┘                             
┌─────────────┴─────────────┐
│READ_CSV_AUTO (MULTI-T...  │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          column1          │
│          column2          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        EC: 4916324        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (5.04s)          │
└───────────────────────────┘     
```

**Comment by carlopi** [comment]
Can you share how to generate `data.csv`?

**Comment by ucasfl** [comment]
> Can you share how to generate `data.csv`?

https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema

```
 ./dbgen -s 1000 -T s
```

**Comment by carlopi** [comment]
I was exagerating, but this (on my machine!!) is somehow faster (20-30%), and I would expect this to be generally faster / arguably more readable:
```c++
static inline void GetSet(const string_t &str, std::bitset<MAX_SIZE> & array_set) {
        array_set.reset();

        idx_t str_len = str.GetSize();
        auto s = str.GetData();

        for (idx_t pos = 0; pos < str_len; pos++) {
                array_set.set(static_cast<unsigned char>(s[pos]));
        }
}

static double JaccardSimilarity(const string_t &str, const string_t &txt) {
        if (str.GetSize() < 1 || txt.GetSize() < 1) {
                throw InvalidInputException("Jaccard Function: An argument too short!");
        }
        std::bitset<MAX_SIZE> m_str, m_txt;

        GetSet(str, m_str);
        GetSet(txt, m_txt);

        std::bitset<MAX_SIZE> m_and = m_str;
        m_and &= m_txt;

        std::bitset<MAX_SIZE> m_or = m_str;
        m_or |= m_txt;

        idx_t size_intersect = m_and.count();
        idx_t size_union = m_or.count();

        return static_cast<double>(size_intersect) / static_cast<double>(size_union);
}
```

**Comment by ucasfl** [comment]
I was wrong, it has better performance:
```sql
explain analyze select jaccard(column1, column2) from 'data.csv';
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 0.196s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────_─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ jaccard(column1, column2) │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (0.25s)          │
└─────────────_─────────────┘                             
┌─────────────┴─────────────┐
│READ_CSV_AUTO (MULTI-T...  │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          column1          │
│          column2          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        EC: 4916324        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          2000000          │
│          (5.22s)          │
└───────────────────────────┘  
```

**Review by carlopi — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
