### PR TITLE
Internal #164: Single Partition Sorting

### PR DESCRIPTION
**Pull request by hawkfish**
* Special case when there is one partition to just sort instead of copying to a single partition and then sorting.
* Handle empty sorts unpartitioned on both left and right.
* Clean up yielding and check for interrupted threads.

### CODE REVIEW

**Review by lnkuiper — COMMENTED** [review]
Thanks for the PR, looks great. Making the distinction between unpartitioned/unordered window specifications allows for nice optimizations.

I don't see any `.test` or `.benchmark` file changes. Is this well-tested/benchmarked already?

**Comment by hawkfish** [comment]
Not per se but I do have a horrible 11R x 1.2GR bitcoin AsOf price lookup example from a user that took over 96GB in memory before the change and now runs in 50GB.

**Review by lnkuiper — APPROVED** [review]
OK, then I think it's ready to go

**Comment by hawkfish** [comment]
Pulled in window CI fixes from yesterday.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
