### PR TITLE
avoid double-writing the index data

### PR DESCRIPTION
**Pull request by jkub**
It seems that index data is getting written twice. Once via WriteTableData, and then again in WriteIndexData.

With this change, the data is written only once (via WriteTableData, which is guaranteed to get invoked first), and WriteIndexData only rewrites the pointer.

There should be no detectable change in file-format, in either direction.

### CODE REVIEW

**Review by pdet — CHANGES_REQUESTED** [review]
Hi @jkub, great catch! Thanks for the PR as well!

The code LGTM, could you just add a test that checks the total number of blocks? 
e.g., `SELECT total_blocks<x FROM pragma_database_size()` so we ensure this problem does not happen again.,

**Comment by jkub** [comment]
Hey @pdet, I'm not sure what's up with this unit test. It passes when I run it.

**Comment by Mytherin** [comment]
It seems to break sporadically, try running it in a loop, e.g.:

```
while true; do build/release/test/unittest test/sql/storage/test_index_checkpoint.test; done
```

**Comment by jkub** [comment]
Hmm... I'm surprised this result is nondeterministic. I'll dig some more.

**Comment by jkub** [comment]
The 32-bit test appears to have failed because it ran out of memory. 😑

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
