### PR TITLE
add sha512 scalar function

### PR DESCRIPTION
**Pull request by euiko**
Added by adding new `SHA512State` in the `MbedTlsWrapper` following segmented API implemented in #8636 and mentioned in previous PR #7592.
Seems I found that it doesn't need to use segmented API as like in the `sha256`, but to keep the style consistent and nice I just implement it with the same style.

Tests implemented in `test/sql/function/string/sha256.test` following tests from #8723 .

Usage :
```
D select sha512('hello');
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                         sha512('hello')                                                          │
│                                                             varchar                                                              │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca72323c3d99ba5c11d7c7acc6e14b8c5da0c4663475c2e5c3adef46f73bcdec043 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

This is my first time contributing to this project, feel free gives feedback/comments.

### CODE REVIEW

**Review by carlopi — CHANGES_REQUESTED** [review]
There are 2 failures connected to what headers are included, see: https://github.com/duckdb/duckdb/actions/runs/6944678818/job/18892339787?pr=9749

```
Traceback (most recent call last):
  File "/__w/duckdb/duckdb/scripts/amalgamation.py", line 579, in <module>
-----------------------
-- Writing src/amalgamation/duckdb.hpp --
-----------------------
------------------------
-- Writing src/amalgamation/duckdb.cpp --
------------------------
    generate_amalgamation(source_file, header_file)
  File "/__w/duckdb/duckdb/scripts/amalgamation.py", line 323, in generate_amalgamation
    sfile.write(write_dir(compile_dir))
  File "/__w/duckdb/duckdb/scripts/amalgamation.py", line 248, in write_dir
    text += write_file(fpath)
  File "/__w/duckdb/duckdb/scripts/amalgamation.py", line [21](https://github.com/duckdb/duckdb/actions/runs/6944678818/job/18892339787?pr=9749#step:11:22)4, in write_file
    (statements, includes) = get_includes(current_file, text)
  File "/__w/duckdb/duckdb/scripts/amalgamation.py", line 132, in get_includes
    raise Exception(f"duplicate include {x[0]} in file {fpath}")
Exception: duplicate include #include "mbedtls/sha[25](https://github.com/duckdb/duckdb/actions/runs/6944678818/job/18892339787?pr=9749#step:11:26)6.h" in file third_party/mbedtls/mbedtls_wrapper.cpp
```

Once those are sorted out, this is good to go for me.

**Comment by euiko** [comment]
Thanks for the review @carlopi, @Mytherin.
Already fixed the amalgamation error on duplicated include of `#include "mbedtls/sha256.h"`.
But then, there are more amalgamation error within another pipeline which I think should not be related to the PR.
Any suggestion?

**Comment by carlopi** [comment]
This I think it's something we have to fix our side, there is some problem with the Linux Amalgamation job.

**Comment by Mytherin** [comment]
It does look like these failures are related to the code changes in the PR - the errors all come from changes made explicitly to the `mbedtls` library here. Are these changes required?

**Comment by szarnyasg** [comment]
@euiko there are some test failures in CI, could you please fix them?

```
[0/1] (0%): test/sql/function/string/sha512.test                                
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/function/string/sha512.test
-------------------------------------------------------------------------------
/__w/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:201
...............................................................................

/__w/duckdb/duckdb/test/sqlite/sqllogic_parser.cpp:115: FAILED:
explicitly with message:
  test/sql/function/string/sha512.test:46: Failed to parse statement: statement
  error needs to have an expected error message
```

**Comment by Mytherin** [comment]
Closing as this has not seen activity in a while

**Pull request closed without merging**
