### PR TITLE
feat(breaking): improve python exceptions

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by Mause** [comment]
Still need to update the various tests that throw exceptions, but want to get the exception hierarchy sorted first. So feedback on that would be appreciated 😁

**Comment by Tishj** [comment]
Could we possibly create more exception classes that derive from `duckdb.Error`?

I'm mostly thinking about how currently this change would lose some of the precision some of our current tests have, for example:
`with pytest.raises(Exception, match='No function matches the given name'):`

While I agree that it isn't great having to rely on a specific string value to be thrown with the exception, it does test that the expected exception is thrown, whereas without this even an altogether different category of exception would pass this test, when it shouldn't.

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good to me. @pdet any comments?

**Review by Mytherin — APPROVED** [review]

**Comment by pdet** [comment]
LGTM, I think the tests should also be updated on this PR (I don't think there are that many?), and probably match the exception type instead of the exception message? (or both?)

**Comment by pdet** [comment]
The DuckDB exception types are the following:

```
enum class ExceptionType {
	INVALID = 0,          // invalid type
	OUT_OF_RANGE = 1,     // value out of range error
	CONVERSION = 2,       // conversion/casting error
	UNKNOWN_TYPE = 3,     // unknown type
	DECIMAL = 4,          // decimal related
	MISMATCH_TYPE = 5,    // type mismatch
	DIVIDE_BY_ZERO = 6,   // divide by 0
	OBJECT_SIZE = 7,      // object size exceeded
	INVALID_TYPE = 8,     // incompatible for operation
	SERIALIZATION = 9,    // serialization
	TRANSACTION = 10,     // transaction management
	NOT_IMPLEMENTED = 11, // method not implemented
	EXPRESSION = 12,      // expression parsing
	CATALOG = 13,         // catalog related
	PARSER = 14,          // parser related
	PLANNER = 15,         // planner related
	SCHEDULER = 16,       // scheduler related
	EXECUTOR = 17,        // executor related
	CONSTRAINT = 18,      // constraint related
	INDEX = 19,           // index related
	STAT = 20,            // stat related
	CONNECTION = 21,      // connection related
	SYNTAX = 22,          // syntax related
	SETTINGS = 23,        // settings related
	BINDER = 24,          // binder related
	NETWORK = 25,         // network related
	OPTIMIZER = 26,       // optimizer related
	NULL_POINTER = 27,    // nullptr exception
	IO = 28,              // IO exception
	INTERRUPT = 29,       // interrupt
	FATAL = 30, // Fatal exception: fatal exceptions are non-recoverable, and render the entire DB in an unusable state
	INTERNAL =
	    31, // Internal exception: exception that indicates something went wrong internally (i.e. bug in the code base)
	INVALID_INPUT = 32, // Input or arguments error
	OUT_OF_MEMORY = 33, // out of memory
	PERMISSION = 34     // insufficient permissions
};
```

I think we have exceptions, that would cover more than one option of the PY DB API, and we do have a lot of exceptions that are mostly internal operation errors, I think an initial draft of the hierarchy would be something like this (Maybe @Mytherin can have a quick look on this as well):


Regarding the hierarchy, my guess would be something of the likes:

(I'm not exactly sure where INTERRUPT and PERMISSION would fit)

 |__DataError (Exception raised for errors that are due to problems with the processed data like division by zero, numeric value out of range, etc.)
* OUT_OF_RANGE
* CONVERSION
* UNKNOWN_TYPE (Can this be triggered by user input? or should be an __OperationalError?)
* DECIMAL 
* MISMATCH_TYPE
* DIVIDE_BY_ZERO 
* INVALID

 |__OperationalError (Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc. )
*  TRANSACTION
*  OUT_OF_MEMORY
*  OBJECT_SIZE 
* NULL_POINTER
* INTERNAL (Maybe also __InternalError?)
* OBJECT_SIZE 
* FATAL
* IO 
* CONNECTION
* SERIALIZATION
* PLANNER
* SCHEDULER
* EXECUTOR
* INDEX 
* STAT 
* SETTINGS
*  NETWORK
* OPTIMIZER 

 |__IntegrityError (Exception raised when the relational integrity of the database is affected, e.g. a foreign key check fails. )
 * CONSTRAINT
 
|__InternalError (Exception raised when the database encounters an internal error, e.g. the cursor is not valid anymore, the transaction is out of sync, etc. )


|__ProgrammingError ( errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified)
* PARSER
* SYNTAX 
* BINDER 
* INVALID_INPUT 
* INVALID_TYPE 
* EXPRESSION 
* CATALOG 

 |__NotSupportedError (Exception raised in case a method or database API was used which is not supported by the database)
* NOT_IMPLEMENTED

**Comment by Mause** [comment]
Okay, I can work with that - I'll look at updating the pr and associated tests over the next couple of days

**Comment by Mause** [comment]
@pdet @Mytherin if you're both happy with how I've fitted the exceptions into the hierarchy (keeping in mind that not all the types in the enum actually exist as exception classes), I can look into updating the (many) tests

**Comment by Mytherin** [comment]
Looks good from my side

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
