### PR TITLE
Implementing Approximate Quantile Functions

### PR DESCRIPTION
**Pull request by pdet**
This PR has two different implementations for approximate quantiles. 
Besides that, I've also added the PCG library to generate random numbers (https://www.pcg-random.org/)
The first one is the approx_quantile(data, quantile), which uses a T-Digest, and the second one is reservoir_quantile(data, quantile,sample_size=8192) which performs a reservoir sampling step before the quantile calculation.

The approx_quantile guarantees a 1% error and is faster than the exact quantile function on parallel. In comparison, reservoir quantile tends to be the fastest (ofc this will depend a bit on the sample size) but with no error guarantees.

Single Thread:
exact_quantile: 0.1s
approx_quantile: 0.4s
reservoir_quantile (default sample size) : 0.04s

8 Threads:
exact_quantile: 0.1s
approx_quantile: 0.06s
reservoir_quantile (default sample size) : 0.01s

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Very nice, one question: Why did you add this random library? Was there no way doing this with the stdlib?

**Comment by pdet** [comment]
I don't think the library was strictly necessary for this task, Lemire actually has quite a nice/concise/fast way of doing what I wanted, but @Mytherin suggested adding this library since its a fast way of generating good random numbers on a bunch of different scenarios and  could be used here and in other places of duckdb

**Comment by Mytherin** [comment]
To expand on that, the PCG random library is very fast, very lightweight in terms of code and has a very small intermediate state (as opposed to e.g. mersenne twister, which requires >1KB of state). As an added bonus using our own random library means we get consistent results regardless of platform; AFAIK the standard library does not guarantee that using the same seed across different standard library implementations always results in the same numbers being generated.

I wanted to add this library before for my sampling implementation but didn't get around to it, so I suggested it to Pedro when he found out that random number generation was a large bottleneck here.

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks dynamite. I just have two minor notes:

**Comment by Mytherin** [comment]
Looks tremendous now, thanks!

**Comment by hannesmuehleisen** [comment]
The R test failures were my bad.

**Pull request merged**
