### PR TITLE
Added `MAP<key_type, value_type>` type to parser

### PR DESCRIPTION
**Pull request by hannes**
This type can not yet be used but is there for unspecified other people who want to use the DuckDB parser. For now it just transforms to a list of structs.

### CODE REVIEW

**Comment by mbasmanova** [comment]
@hannesmuehleisen To clarify, this syntax will be supported now: "cast(x as map<bigint, array<double>>)" ?

**Comment by hannesmuehleisen** [comment]
So this parses: select cast(NULL as map(bigint, list(int)));

**Comment by hannesmuehleisen** [comment]
This also works: select cast(NULL as map(bigint, int[]));

**Comment by hannesmuehleisen** [comment]
@mbasmanova if this was not called map but something else would that also be okay for you? We would like to have a map operator at some point perhaps.

**Comment by mbasmanova** [comment]
> @mbasmanova if this was not called map but something else would that also be okay for you? We would like to have a map operator at some point perhaps.

What is map operator? In Presto we have multiple "map"s, e.g. SELECT map(array[1, 2, 3], array[10, 20, 30]) as well as SELECT cast(x as map(bigint, double)).

**Comment by hannesmuehleisen** [comment]
like applying an expression to every entry of a list?

**Comment by mbasmanova** [comment]
> like applying an expression to every entry of a list?

In Presto, this function is called "transform" - https://prestodb.io/docs/current/functions/array.html . We also have a "map" function that takes an array of keys and array of values and makes a map. These coexist with "map" type just fine.

Why can't we have both "map" function and "map" type in DuckDB? These appear in different contexts and therefore can be distinguished. Having a "map" type called "mapf" would be a bit strange.

**Comment by hannesmuehleisen** [comment]
@Mytherin can you have a look whether `MAP` needs to be a reserved keyword here?

**Comment by Mytherin** [comment]
I have solved it now so that this passes our parser:
```sql
create table map(map map(map(integer,integer), integer) default map());
```

Because Postgres supports user-defined types, the parser has support for parsing arbitrary type names. This means that making `MAP` a completely unreserved keyword leads to an ambiguity in the grammar. Previously the Postgres' keywords were defined in four groups:

* Reserved (i.e. can only be used as quoted identifier, e.g. create table "reserved")
* Unreserved (i.e. can be used mostly anywhere)
* col_name (i.e. can be used as identifier without being quoted, but cannot be used as a function or type name)
* type_func_name (i.e. can be used as function or generic type name, but not as an identifier without being quoted)

The problem is that we wanted MAP to be able to be used as a column name and a function name, but NOT as a generic type name, which these four disjunct lists do not support.

I have now split up the keyword lists so that keywords can be in one of three groups:
* Reserved (i.e. can only be used as quoted identifier, e.g. create table "reserved")
* Unreserved (i.e. can be used anywhere)
* A combination of col_name, type_name and func_name

The last part can now be mixed and matched, so we can make MAP both a col_name and a func_name keyword, without having to also make it a type_name keyword.

**Comment by mbasmanova** [comment]
Thank you, @Mytherin

**Pull request merged**
