### PR TITLE
clean up and update node bindings

### PR DESCRIPTION
**Pull request by domoritz**
* use @mapbox/node-pre-gyp
* remove unused variables
* update dependencies
* format readme
* move developer dependencies into dev dependencies
* remove unused dependencies

### CODE REVIEW

**Comment by Y--** [comment]
Hi @domoritz ! I'm curious about why the change to `@mapbox/node-pre-gyp`? Thanks!

**Comment by domoritz** [comment]
https://www.npmjs.com/package/node-pre-gyp says the unscoped package is deprecated.

**Comment by Y--** [comment]
> https://www.npmjs.com/package/node-pre-gyp says the unscoped package is deprecated.

Got it! Thanks!

**Comment by domoritz** [comment]
Tested locally and build works.

**Comment by hannesmuehleisen** [comment]
Great, could you please have a look at the ci failure? Looks like some path problem 
‘ ./scripts/node_build.sh: line 13: node-pre-gyp: command not found’

**Comment by domoritz** [comment]
Should be fixed with [`4b78554` (#1454)](https://github.com/cwida/duckdb/pull/1454/commits/4b78554e43cf365ae2ff0dc21ff38b905b52a675).

**Comment by domoritz** [comment]
The windows failure looks unrelated. Let me know if there is anything else.

**Comment by hannesmuehleisen** [comment]
Looks good thank you

**Comment by lucasl84** [comment]
Sorry to the late party but I'm getting this and I have no idea how to fix it:

```
lucas@zenbook:~/NewProjects/svelte-proj$ npm run dev

> svelte-template@0.0.1 dev
> vite dev


  VITE v5.4.9  ready in 886 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
[]
✘ [ERROR] No loader is configured for ".html" files: node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

    node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21:
      86 │       return require('./' + command)(self, argvx, callback);
         ╵                      ~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │   const AWS = require('aws-sdk');
         ╵                       ~~~~~~~~~

  You can mark the path "aws-sdk" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

11:40:28 AM [vite] error while updating dependencies:
Error: Build failed with 4 errors:
node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21: ERROR: No loader is configured for ".html" files: node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22: ERROR: Could not resolve "aws-sdk"
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"
    at failureErrorWithLog (/home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:1472:15)
    at /home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:945:25
    at /home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
✘ [ERROR] No loader is configured for ".html" files: node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

    node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21:
      86 │       return require('./' + command)(self, argvx, callback);
         ╵                      ~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │   const AWS = require('aws-sdk');
         ╵                       ~~~~~~~~~

  You can mark the path "aws-sdk" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

11:40:28 AM [vite] error while updating dependencies:
Error: Build failed with 4 errors:
node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21: ERROR: No loader is configured for ".html" files: node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22: ERROR: Could not resolve "aws-sdk"
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"
    at failureErrorWithLog (/home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:1472:15)
    at /home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:945:25
    at /home/lucas/NewProjects/svelte-proj/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (x2)
```

Why is even a require to `aws-sdk`? I had no idea that this was coming from DuckDB until it occurred to me to delete the `node_modules/@mapbox` dependency. Is there a way to fix this? I'm currently on `"duckdb": "^1.1.1"` and `"duckdb-async": "^1.1.1"`.

Thanks.

**Pull request merged**
