### PR TITLE
R: Only quote non-syntactic and reserved words

### PR DESCRIPTION
**Pull request by krlmlr**
Rebased, resolved conflicts, and fixed coverage failures.

Should we compute keywords eagerly, when connecting?

Closes #3718.

### CODE REVIEW

**Comment by hannes** [comment]
I'm fine with eager

**Comment by krlmlr** [comment]
Eager now.

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by hannes** [comment]
CC @Hadley

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
