### PR TITLE
[PySpark] Add a lot more functions incl. some regexp ones

### PR DESCRIPTION
**Pull request by binste**
As always, opening a new draft PR to provide visibility on what I'm working on. Will mark it for review once I've accumulated a few more functions.

Btw, `LambdaExpression` is super helpful! :)

### CODE REVIEW

**Review by Tishj — APPROVED** [review]
Thanks, looks good to me 👍

**Comment by Mytherin** [comment]
Could you just resolve the merge conflicts?

**Comment by binste** [comment]
Resolved :)

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
