### PR TITLE
Add Initial DuckDB Swift API

### PR DESCRIPTION
**Pull request by tcldr**
### Contents

An initial version of the Duck DB Swift API:

Includes:
- Native Swift versions of Database/Connection/Result types
- Basic querying via textual SQL interface.
- Extraction of results for all the primitive types (plus string).
- Basic Testing

In addition, for CI:
- Tests automatically run for Apple platforms (iOS, macOS, watchOS, tvOS)
- Auto commit/push updates on master to swift specific repository.
- Auto tag the Swift repo on the creation of a release in the main repo.

### Setup

If building from a fork, first you'll need to sync the upstream tags:

```
git remote add upstream https://github.com/duckdb/duckdb.git
git fetch upstream
git push -f --tags origin master
```

Then, generate the package by running:
```
python3 tools/swiftpm/create_package.py tools/swiftpm/
```

You should then be able to open the `tools/swiftpm/swift-duckdb/DuckDB.xcworkspace` file in Xcode to explore the Package.

### CODE REVIEW

**Comment by hannes** [comment]
I'm getting 
```
➜  duckdb-tristan git:(duckdb-swift) python3 tools/swiftpm/create_package.py tools/swiftpm/
fatal: No names found, cannot describe anything.
```

**Comment by hannes** [comment]
Ah the fork does not have any tags, fixed it by adding one

**Comment by tcldr** [comment]
> Ah the fork does not have any tags, fixed it by adding one

Ah yes, forgot about that, I'll update the notes.

**Comment by hannes** [comment]
Looks great already!

**Comment by hannes** [comment]
`Check its safe to always assume UInt64 instead of idx_t` - it is :)

**Pull request merged**
