### PR TITLE
Add support for a pluggable storage and catalog back-end, and add support for a SQLite back-end storage

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds support for a pluggable storage, catalog and transaction system to DuckDB. This allows databases of different *database types* to be attached. This PR, together with duckdblabs/sqlite_scanner#25, allows DuckDB to read and write to SQLite databases as if they are standard DuckDB databases (using the `sqlite` extension).

Here is an example of how this works:

```sql
ATTACH 'sqlite_file.db' AS sqlite (TYPE SQLITE);

CREATE TABLE sqlite.tbl(i INTEGER);
INSERT INTO sqlite.tbl VALUES (1), (2), (3);
SELECT * FROM sqlite.tbl;
┌───────┐
│   i   │
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```

Everything works as if this is a DuckDB database - but the storage back-end is actually powered by a SQLite file:

```sql
$ > sqlite3 sqlite_file.db 
sqlite> SELECT * FROM tbl;
i
-
1
2
3
```

We can query the `duckdb_databases` view to get a list of attached databases - including their types.

```sql
D SELECT * EXCLUDE (database_oid) FROM duckdb_databases;
┌───────────────┬────────────────┬──────────┬─────────┐
│ database_name │      path      │ internal │  type   │
│    varchar    │    varchar     │ boolean  │ varchar │
├───────────────┼────────────────┼──────────┼─────────┤
│ sqlite        │ sqlite_file.db │ false    │ sqlite  │
│ memory        │ NULL           │ false    │ duckdb  │
└───────────────┴────────────────┴──────────┴─────────┘
```

We can also change which database is the default database using the `USE` command:

```sql
USE sqlite;
SELECT * FROM tbl;
┌───────┐
│   i   │
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```

# What Is Supported

* Creating tables
* Inserting data into tables
* Updating tables
* Deleting data from tables
* Copy statements
* Altering tables (adding/dropping columns, renaming columns, renaming tables)
* Creating views
* Creating indexes
* Dropping catalog entries
* Full transaction support (BEGIN, COMMIT, ROLLBACK work as expected)
* Metadata queries work as expected (e.g. you can use `DESCRIBE` on SQLite tables, they appear in `duckdb_tables`, etc)

The following features are not supported by SQLite - but are supported by the extensible catalogs:

* Creating schemas
* Creating functions/macros
* Creating sequences
* Creating types

# How Does It Work

This PR enables virtualization of the catalog and transaction manager. This is a follow-up to #5764 which has done work on enabling multiple catalogs/transaction managers to exist, and moving the catalog and transaction manager to separate attached databases.

In this PR the `Catalog`, `TransactionManager`, `Transaction`, `SchemaCatalogEntry`, `TableCatalogEntry` (and other catalog entries) now become virtual classes that extensions can inherit from. Methods and members that are specific to the DuckDB implementations have been virtualized, and moved to separate `Duck` classes - e.g. there is now a `DuckCatalog`, `DuckTransaction`, etc.

The virtual catalog entries are entirely separate from DuckDB's own transaction and storage infrastructure. As such, they can implement their own methods of transaction management and storage and are not tied to DuckDB's way of handling this. In the SQLite extension - for example - SQLite's storage and transaction mechanisms are used. The virtualization results in certain callbacks being made related to starting transactions, committing, rolling back, checkpointing, etc.

All other parts of the queries go through the regular DuckDB system as per usual - so you can load data from Parquet files into SQLite tables, move data between SQLite tables and DuckDB tables, export SQLite tables to Parquet, use DuckDB functions on data stored in SQLite tables, etc.

### CODE REVIEW

**Comment by snth** [comment]
Amazing! Will you be doing the same for the `postgres` extension and `postgres_scanner`?

**Comment by snth** [comment]
No problem, but such an amazing prospect. In total awe of you folks!

**Comment by buremba** [comment]
@Mytherin This is fascinating! Is there any plan to support predicate & aggregate & join pushdown for the storage layer?

**Comment by Mytherin** [comment]
Predicate pushdown is already supported. Pushdown of more operators is not immediately in the pipeline but is certainly a future possibility.

**Pull request merged**
