### PR TITLE
Support read_csv_auto from /dev/stdin

### LINKED ISSUE #1417: Feature: support read_csv_auto reading from the '/dev/stdin' file
The duckdb CLI command can read from a file using read_csv_auto():

```bash
duckdb mydb "create table mytable as select * from read_csv_auto('mydata.csv', HEADER=TRUE);"
```

When I try to send the same data to the /dev/stdin file and have duckdb load it from there, it fails:

```bash
cat mydata.csv | duckdb mydb "create table mytable as select * from read_csv_auto('/dev/stdin', HEADER=TRUE);" 
```

The error is:

```bash
Error: Invalid Input Error: Error in file "/dev/stdin": CSV options could not be auto-detected. Consider setting parser options manually.
```

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #1417

i.e. this now works:

```bash
cat data/csv/issue2471.csv | duckdb -c "select * from read_csv_auto('/dev/stdin')"
```

### CODE REVIEW

**Review by hawkfish — APPROVED** [review]

**Comment by aborruso** [comment]
Hi @Mytherin I have tested it using [this CSV](https://gist.github.com/cbf2b87a5cdde6cb3590fa71ef30b76b).

If I run this, it works.

```
cat input.csv | duckdb -c "select * from read_csv_auto('/dev/stdin')"
```

If I run SUMMARIZE on the CSV file it works

```
duckdb --csv  -c "SUMMARIZE SELECT * FROM read_csv_auto('input.csv')"
```

If I run SUMMARIZE on stdin it does not work

```
cat input.csv | duckdb -c "SUMMARIZE select * from read_csv_auto('/dev/stdin')"
```

The error is

```
Error: Invalid Input Error: Error in file "/dev/stdin": CSV options could not be auto-detected. Consider setting parser options manually.
```

How to use summarize with stdin ?

**Comment by derekmahar** [comment]
Another method that DuckDB can use to read a CSV file from the standard output of another command is to read this output from a named FIFO to which the other command writes:

```
# duckdb_read_csv_from_stdin
function duckdb_read_csv_from_stdin {
  local work_directory=$(mktemp --directory --tmpdir duckdb-XXXXXXXXXX)
  local input_fifo=$work_directory/input_fifo
  mkfifo $input_fifo 
  cat > $input_fifo &
  duckdb -c "SELECT * FROM read_csv_auto('$input_fifo');"
  rm -rf $work_directory
}
```

```
$ source duckdb_read_csv_from_stdin
$ printf "name,age\nJohn,10\n" | duckdb_read_csv_from_stdin 
┌─────────┬───────┐
│  name   │  age  │
│ varchar │ int32 │
├─────────┼───────┤
│ John    │    10 │
└─────────┴───────┘
```

This method is obviously more verbose than reading from `/dev/stdin`, but it would work on systems which support named pipes (`mkfifo`), but where `/dev/stdin` is not available.

**Comment by pkoppstein** [comment]
@Mytherin - Is this no longer supported?  On my Mac:
```
$ duckdb --version
v1.0.0 1f98600c2c

$ duckdb -c "select * from read_csv_auto('/dev/stdin');"
IO Error: No files found that match the pattern "/dev/stdin"

$ file /dev/stdin
/dev/stdin: character special (16/9)\```

Similarly with 1.0.1; and with read_csv()

**Comment by aborruso** [comment]
Hi @pkoppstein I'm using duckdb v1.0.0 1f98600c2c in linux and it works

```
printf "name,age\nJohn,10\n" | duckdb -c "select * from read_csv_auto('/dev/stdin');"
```

image

**Comment by pkoppstein** [comment]
@aborruso - Yes, your example works on Mac OS too.  What about mine on Linux?  

In any case, the problem appears to be twofold: (1) misleading error message; (2) impatience (compare, for example, how `cat` is stream-oriented).

Thanks.

**Comment by aborruso** [comment]
@pkoppstein I believe  /dev/stdin only exists when there's an input stream. But I'm not sure.
Without an actual input being provided, like through a pipe or redirection, I think the command might not work as expected. So, in this case, you'd probably need to generate a stream by piping some data into it.

What's the input stream in your command `duckdb -c "select * from read_csv_auto('/dev/stdin');"`

**Comment by derekmahar** [comment]
Like `cat``, DuckDB might consider treating the special file name `-`  or some other symbol or identifier as an alias for standard input.

**Comment by derekmahar** [comment]
Using a variation of a solution that makes [SQLite read CSV files from standard input](https://unix.stackexchange.com/a/642362/5783) and Bash [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html), a simpler workaround than using [named pipes](https://github.com/duckdb/duckdb/pull/2844#issuecomment-1345671049) is to replace `/dev/stdin` with `<(cat)` or `<(cat -)`.  For example, after replacing `/dev/stdin` with `<(cat)`,

```
$ printf "name,age\nJohn,10\n" | duckdb -c "select * from read_csv_auto('/dev/stdin');"
┌─────────┬───────┐
│  name   │  age  │
│ varchar │ int64 │
├─────────┼───────┤
│ John    │    10 │
└─────────┴───────┘
```

becomes

```
$ printf "name,age\nJohn,10\n" | duckdb -c "select * from read_csv_auto('"<(cat)"');"
┌─────────┬───────┐
│  name   │  age  │
│ varchar │ int64 │
├─────────┼───────┤
│ John    │    10 │
└─────────┴───────┘
```

Not that this approach should work on any operating system that can run a version of Bash that supports process substitution, including Windows running [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) or [Cygwin](https://en.wikipedia.org/wiki/Cygwin).

**Comment by derekmahar** [comment]
Here is how some other CSV processing tools behave with empty standard input.  Of these, only [Miller](https://miller.readthedocs.io/) behaved like `cat` and blocked on empty standard input.

[csvq](https://mithrandie.github.io/csvq/)

```
$ csvq --format csv "SELECT * FROM STDIN"
[L:1 C:15] STDIN is empty
```

[csvtk](https://bioinf.shenwei.me/csvtk/)

```
$ csvtk concat
[WARN] csvtk concat: skipping empty input file: -

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/shenwei356/csvtk/csvtk/cmd.glob..func5(0x12e40a0?, {0x1341758, 0x0, 0x0})
        /home/shenwei/go/src/github.com/shenwei356/csvtk/csvtk/cmd/concat.go:129 +0x784
github.com/spf13/cobra.(*Command).execute(0x12e40a0, {0x1341758, 0x0, 0x0})
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x12e3520)
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/shenwei356/csvtk/csvtk/cmd.Execute()
        /home/shenwei/go/src/github.com/shenwei356/csvtk/csvtk/cmd/root.go:72 +0x24
main.main()
        /home/shenwei/go/src/github.com/shenwei356/csvtk/csvtk/main.go:59 +0x1c
```

[Miller](https://miller.readthedocs.io/)

```
$ mlr --csv cat

```

[qsv](https://qsv.dathere.com/)

```
$ qsv cat rows
No data on stdin. Please provide at least one input file or pipe data to stdin.
```

**Pull request merged**
