### PR TITLE
Rework `union_by_name` so that files are no longer kept open

### LINKED ISSUE #11334: Spill-to-disk does not work as expected: Out-of-Memory Errors Raised
### What happens?

When running a SQL script to process larger-than-memory set of CSV files, `duckdb` fails with 

```bash
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: could not allocate block of size 30.5 MiB (12.3 GiB/12.3 GiB used)
``` 

#### Little update: Still fails with DuckDB 0.10.1:

If I run DuckDB in-memory mode with 4 GB ram:

```bash
    duckdb.sql("""
duckdb.duckdb.Error: std::bad_alloc
```

If I run DuckDB persistent file mode 4 GB ram:

```bash
duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 32002048 bytes (bad allocation)
```

### To Reproduce

0. Install Poetry in Python 3.11
1. Check out this repo: https://github.com/oneturkmen/experiments-with-olap-triad
2. To have all packages for the benchmark, run `poetry shell` and `poetry install`. For quick reproduction `pip install duckdb` suffices.
3. Download [hard drive failure data](https://www.backblaze.com/cloud-storage/resources/hard-drive-test-data#downloadingTheRawTestData) from 2022 Q1 and Q2, and all of 2023 data for our setup:

    ```bash
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q1_2022.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q2_2022.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q1_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q2_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q3_2023.zip
    wget https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_Q4_2023.zip
    unzip '*.zip'
    ```

4. It should look like this:

    ```bash
    $ du -sh data_* --total
    
    6.2G	data_Q1_2022
    7.1G	data_Q1_2023
    6.4G	data_Q2_2022
    7.6G	data_Q2_2023
    8.6G	data_Q3_2023
    9.0G	data_Q4_2023
    45G	total
    ```

5. Run:
    ```bash
    (ulimit -v 4000000; python duckdb_main.py)
    ```
    or
    ```bash
    (ulimit -v 4000000; python duckdb_persistentmode_main.py)
    ```
    inside the poetry environment with `ulimit` helping limit RAM to 4GB.

The python script contains the following code:

```python
import duckdb
import time


def duckdb_test():
    duckdb.sql("""
        SET preserve_insertion_order = false;
        SET temp_directory = './temp';
        CREATE VIEW metrics AS 
        SELECT date, SUM(failure) as failures
        FROM read_csv('*/*.csv', union_by_name = true)
        GROUP BY date;
    """)

    duckdb.sql("""
        COPY metrics TO 'results_duckdb.csv';
    """)

start_time = time.time()
duckdb_test()
end_time = time.time()
print(f"It took {end_time - start_time} seconds to run DuckDB test.")
```

Reference blog post: https://batyr.dev/tech/2024/03/17/data-analysis-with-less-memory.html

### OS:

x86_64

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Batyr

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes https://github.com/duckdb/duckdb/issues/11334

When running `read_csv` or `read_parquet` with `union_by_name=true`, we need to open all files that are part of the query during bind time in order to determine the result schema, as any file that is part of the file list can modify the schema (by adding columns or changing types of existing columns). Previously we would cache all of these file handles in order to speed up subsequent reads. However, when running `union_by_name` over many files, these cached file handles could lead to issues:

* Too many open file handles as operating system limits are exceeded
* Out-of-memory errors as each of the open file handles also kept the first few megabytes of the file cached (in case of the CSV reader)

This PR reworks the `union_by_name` flag so that it opens the files, and then closes them again. Only the first file handle is kept cached. Subsequent files are re-opened and re-read during the actual scan. Instead we only cache a subset of the information for each file (e.g. the CSV reader options, types and names for the file).

### CODE REVIEW

**Comment by Mytherin** [comment]
@samansmink perhaps you can double-check that the changes in the Parquet reader don't conflict with the delta extension?

**Comment by Mytherin** [comment]
We actually cache the CSV reader options and don't run the auto-detect a second time:

```cpp

	static unique_ptr<CSVUnionData> StoreUnionReader(unique_ptr<CSVFileScan> scan_p, idx_t file_idx) {
		auto data = make_uniq<CSVUnionData>();
		if (file_idx == 0) {
			data->file_name = scan_p->file_path;
			data->options = scan_p->options;
			data->names = scan_p->names;
			data->types = scan_p->types;
			data->reader = std::move(scan_p);
		} else {
			data->file_name = scan_p->file_path;
			data->options = std::move(scan_p->options);
			data->names = std::move(scan_p->names);
			data->types = std::move(scan_p->types);
		}
		data->options.auto_detect = false;
		return data;
	}
```

I think the adaptive reading won't work with `union_by_name` (yet?), given that we don't pass any state of previous reads to subsequent reads (see `union_by_name.hpp`)

**Comment by Mytherin** [comment]
Actually we did re-sniff after all, should be fixed now.

**Comment by pdet** [comment]
> Actually we did re-sniff after all, should be fixed now.

On that note, should we add regressions tests?

**Comment by Mytherin** [comment]
Sure, I've added a benchmark

**Review by samansmink — APPROVED** [review]
LGTM, delta extension is unaffected by this

**Comment by Alex-Monahan** [comment]
Is `read_json` fixed with this PR as well, or is it affected by this issue at all?

**Comment by Mytherin** [comment]
`read_json` does not use the same `union_by_name` infrastructure as the CSV/Parquet readers. I'm not sure if it is affected by the issue - but if it is it has to be fixed separately.

**Pull request merged**
