### PR TITLE
Feature: Allow binary-formatted strings to be cast to integers

### LINKED ISSUE #5196: Support binary integer notation
In the same trend as #5074 

We should also support :
```sql
select b'01010100'::int;
-- 84
```

Or as a first step, similar to #5160 we can add a casting rule for it first
```sql
select '0b01010100'::int;
-- 84
```

For no reason whatsoever I made this cursed (probably not very efficient) sql query to do this conversion for anyone looking for this functionality before it's implemented into the system:
```sql
with binary_string as (select '011010110101' as str)
select list_sum([ (CASE WHEN str[i+1] = '0' THEN 0 ELSE 1 END) * (2 ** (len(str)-(i+1))) for i in range(len(str))]) from binary_string
-- 1717.0
```

### PR DESCRIPTION
**Pull request by Maxxen**
Partially closes #5196. 

Ideally a proper literal syntax should be reserved to create bit-strings, like in Postgres, but since we don't have a proper bit-string type yet that will have to wait.

This implementation also allows underscores to be used as digit separators, which greatly help when working with larger binary numbers.

### CODE REVIEW

**Comment by Maxxen** [comment]
I just merged with master... Don't know if that's gonna complicate things now that we have a feature branch

**Comment by Mytherin** [comment]
Probably not, we should merge the master into the feature branch with some frequency anyway

**Comment by Maxxen** [comment]
Ah ok, good to know, made a force revert anyway to keep the history clean.

**Comment by Maxxen** [comment]
@Mytherin CI issues aren't related right?

**Comment by Tishj** [comment]
Yea that's definitely just a spurious http error

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
