### PR TITLE
Remove packaging for Python 3.6

### PR DESCRIPTION
**Pull request by carlopi**
Python 3.6 is already unsupported since end 2022, and now there are some build problem on Windows that I haven't found a workaoround to

### CODE REVIEW

**Comment by carlopi** [comment]
Support policy for Python here: https://devguide.python.org/versions/

**Comment by carlopi** [comment]
Python on Windows job has failed for 2 weeks in a row due to this failure on version 3.6: https://github.com/duckdb/duckdb/actions/runs/5862130274/job/15894080518
To me the simplest solution now seems to just drop 3.6 also on Windows, but open to fixing the bug for real.

If we go this way, and since Linux is already dropped, we can consider for uniformity removing also from OSX. Or otherwise wait until some problem pops up.

**Review by Mause — APPROVED** [review]
I think for completeness we should remove the OSX builds as well, and update our `setup.py` to include  `python_requires='>=3.7.0',` or similar

**Comment by carlopi** [comment]
Changes to `tools/pythonpkg/setup.py` (https://github.com/duckdb/duckdb/pull/8577/files#diff-608521909520afae03d3521283535b13782b4ccee56cfd0462d40f8314bcb8c2) are the weaker part, CI side I am more confident that's I am actually only skipping 3.6.

Then the main question is whether it would be nicer to support it somehow.

**Pull request merged**
