### PR TITLE
CI: Swap cron for repository_dispatch

### PR DESCRIPTION
**Pull request by carlopi**

### CODE REVIEW

**Comment by Mause** [comment]
What's the rationale here? What are we going to use to trigger these events?

**Comment by carlopi** [comment]
Problem: cron-scheduled workflows implies that on every fork, all workflows are run. We could detect (after they are started) and kill them, but seems anyhow ugly to have someone that forks duckdb have it's github to be polluted.

Tentative Solution: there is a secondary repo (https://github.com/duckdb/duckdb-workflow-trigger) that has a single scheduled workflow whose job is triggering the duckdb/duckdb workflows.

I used the same solution @pdet (??) put in place for [ExtensionTrigger.yml](https://github.com/duckdb/duckdb/blob/master/.github/workflows/ExtensionTrigger.yml).

Potential problems: you have a fork, and want your workflows to be run?
I'd say you could add back the scheduled or, now that I think of it, even better by cloning the duckdb-workflow-trigger repo on your own user / organisation.
[First I will check this works, then will try to have it a bit more general / without hardcoded names]

**Comment by carlopi** [comment]
I used indirection to get out of the problem here, but if there is a more standard solution, happy to hear.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
