### PR TITLE
python: Add missing global options to write_csv

### PR DESCRIPTION
**Pull request by jzavala-gonzalez**
Addresses one of the points in https://github.com/duckdb/duckdb/discussions/8896 .
Adds the following parameters to write_csv:
- overwrite
- per_thread_output
- use_tmp_file
- partition_by

Stubs are also edited to include said parameters.

Relevant docs: https://duckdb.org/docs/sql/statements/copy.html#copy--to-options

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good to me. Could you just merge with master so the CI can re-run? @Tishj can you also have a look?

**Review by Tishj — CHANGES_REQUESTED** [review]
Thanks for adding the options, could you add some tests for the options?
The only thing we really need to verify with these tests is that they are passed correctly to the csv writing method.

But that will properly mean we need to check for the effects of the options on the resulting CSV

There exist a couple of tests for the existing option: `tools/pythonpkg/tests/fast/api/test_to_csv.py`

**Comment by jzavala-gonzalez** [comment]
Added some tests. Note that for "partition_by", reopening is done through `duckdb.sql` since `read_csv` does not yet implement the hive_partitioning argument. "overwrite" is tested both that it works when enabled and throws when it isn't. "per_thread_output" and "use_tmp_file" tests both just check that the resulting file can be opened successfully.

**Review by Tishj — APPROVED** [review]
Thanks, LGTM now 👍

**Comment by jzavala-gonzalez** [comment]
Thank you!!

**Pull request merged**
