### PR TITLE
Fix bug where an ALTER .. RENAME after a DROP fails

### PR DESCRIPTION
**Pull request by jwills**
Hit this issue in my dbt testing; fix was easy and I added a couple of tests that will fail without the fix.

### CODE REVIEW

**Comment by Mytherin** [comment]
I think this issue might be a bit more complex than it seems at first glance. The mapping is a global mapping, it's not transaction-controlled. That means that overwriting an entry in the mapping replaces that entry for *all* transactions. Now suppose you have the following situation:

```sql
statement ok con1
CREATE TABLE t1(i INTEGER);

statement ok con2
CREATE TABLE t2(s VARCHAR);

statement ok con2
BEGIN TRANSACTION

statement ok con2
DROP TABLE t2;

statement ok con2
ALTER TABLE t1 RENAME TO t2;

-- Eek!  t2 now refers to to t1 for con1 as well
statement ok con1
SELECT s FROM t2;
```

To handle this properly the mapping needs to be transaction controlled as well, because the mapping now depends on which transaction is running.

**Comment by jwills** [comment]
Ah, that is indeed an issue. So the fix would essentially involve making the entries in the `mapping` into a linked list of transaction-aware entities as well? Or is there a better way to do this that I'm not seeing?

**Comment by Mytherin** [comment]
The mapping needs to be transaction-aware indeed. Having thought about it a bit I think that that's the best option if we want to support this behavior. The mapping would need to have a similar structure to the catalog entries, where the idx_t it points to depends on the transaction.

**Comment by jwills** [comment]
Yep, I see it. So on my side, the hack I have in this PR fixes my issue enough for me to make progress on other dbt stuff. I am happy to take a crack at this if you are otherwise occupied, but I would certainly be more confident as a user of DuckDB if this was something you implemented. ;-)

**Comment by Mytherin** [comment]
I will open an issue and get to it later on, but feel free to tackle it yourself. I don't think it's crazy difficult, but it's not entirely trivial either and requires some knowledge of how the MVCC works.

**Comment by jwills** [comment]
Sounds great- thanks!

**Comment by Mytherin** [comment]
Will close this PR for now, feel free to re-open if you want to work on the MVCC-related adjustments :)

**Pull request closed without merging**
