### PR TITLE
Rigger Test Fixes

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds tests for issues #489, #490, #491, #493, #495 and #497.

Notes:
#489, #491, #493 - These bugs I could not reproduce using the C++ interface, perhaps related to the JDBC?
#490 - Caused by Filter Pushdown optimizer (fixed)
#497 - Missing implementation of BOOLEAN type for merge join (fixed)
#495 - Test currently commented out, @pde will look at it when he has time.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Could not reproduce #491 either but added a test in the JDBC client. Will have look at #489 and #493

**Comment by mrigger** [comment]
Just a note: I can still reproduce #491 and the other issues using `duckdb_cli`. Could this be a compiler-related problem?

**Comment by Mytherin** [comment]
> Just a note: I can still reproduce #491 and the other issues using `duckdb_cli`. Could this be a compiler-related problem?

That is indeed possible! If it is a compiler related problem Travis should catch it as that tests a bunch of different compilers.

**Comment by hannesmuehleisen** [comment]
> > Just a note: I can still reproduce #491 and the other issues using `duckdb_cli`. Could this be a compiler-related problem?
> 
> That is indeed possible! If it is a compiler related problem Travis should catch it as that tests a bunch of different compilers.

That would be rather worrying.

**Comment by hannesmuehleisen** [comment]
Looks like #500 is the only thing left here. will have a look tomorrow.

**Comment by mrigger** [comment]
> Looks like #500 is the only thing left here. will have a look tomorrow.

Great, thanks! After the recent changes have been merged to master, I'll resume testing.

**Pull request merged**
