### PR TITLE
Fix deadlock in BufferManager PurgeQueue

### PR DESCRIPTION
**Pull request by lnkuiper**

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
I vote to ignore the codecov failure here :)

**Comment by lnkuiper** [comment]
I'm kind of at a loss of what to do here. I've tried to put `PurgeQueue` in all possible places in the buffer manager, and now I've found a place where Thread Sanitizer won't complain even without a `lock_guard<mutex>`, but the CI still ends up in a deadlock and times out after 6 hours. Locally it works fine. Any ideas?

**Comment by Mytherin** [comment]
> I'm kind of at a loss of what to do here. I've tried to put PurgeQueue in all possible places in the buffer manager, and now I've found a place where Thread Sanitizer won't complain even without a lock_guard<mutex>, but the CI still ends up in a deadlock and times out after 6 hours. Locally it works fine. Any ideas?

I'm suspecting the dead lock is caused not by the PurgeQueue, but rather by the verification code, since the thread sanitizer is run in reldebug mode and the verification code has many locks. Perhaps try looking at that, or even removing that entirely?

**Comment by lnkuiper** [comment]
The verification code passed the CI before. Thanks for your suggestion though, because I went back to this commit, and found that I changed something unintendedly! I changed this back, hoping CI will succeed now 🙏🏻

**Comment by lnkuiper** [comment]
Looks like it worked!

**Pull request merged**
