### PR TITLE
Fix #9360, fix #9466: grab a lock before creating directories to fix race condition on Windows in partitioned write

### LINKED ISSUE #9360: "IO Error: Could not create directory" when writing hive partitioned parquet files
### What happens?

When writing hive partitioned parquet Files, you often get an IO Error, stating that one of the partitioned folders cannot be created:

```
v0.9.2-dev23 6eeb6826bb
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D copy (select * from 'C:\temp\Flights-1m.parquet')
> to 'C:\temp\flights' (FORMAT 'PARQUET', CODEC 'ZSTD', PARTITION_BY(FL_DATE), OVERWRITE_OR_IGNORE 1);
Error: IO Error: Could not create directory: 'C:\temp\flights\FL_DATE=2006-01-09'
D
```

When executing the command multiple times, the folder is usually different (e.g. first time is `FL_DATE=2006-01-09`, next time is `FL_DATE=2006-01-04`, kind of random...).

However, it does not happen when the source file is read via the httpfs module (could be a timing issue?).

No issue:

```sql
copy (select * from 'https://www.tablab.app/sample-datasets/flights-1m.parquet')
to 'C:\temp\flights' (FORMAT 'PARQUET', CODEC 'ZSTD', PARTITION_BY(FL_DATE), OVERWRITE_OR_IGNORE 1);
```

Fails ~90% of the time if you download the .parquet File first and then execute:

```sql
copy (select * from 'C:\temp\Flights-1m.parquet')
to 'C:\temp\flights' (FORMAT 'PARQUET', CODEC 'ZSTD', PARTITION_BY(FL_DATE), OVERWRITE_OR_IGNORE 1);
```

I also noticed that the error does **not** occur, if I set the threads to 1:

```
SET threads TO 1;
```

### To Reproduce

- Download https://www.tablab.app/sample-datasets/flights-1m.parquet to `C:\temp\` folder
- Execute the following SQL with DuckDB:
   ```sql
   copy (select * from 'C:\temp\Flights-1m.parquet')
   to 'C:\temp\flights' (FORMAT 'PARQUET', CODEC 'ZSTD', PARTITION_BY(FL_DATE), OVERWRITE_OR_IGNORE 1);
   ```
- You get errors like `Error: IO Error: Could not create directory: 'C:\temp\flights\FL_DATE=2006-01-09'` most of the time (be sure to delete `C:\temp\flights\` before the next try)

### OS:

Windows x64

### DuckDB Version:

v0.9.2-dev23 6eeb6826bb

### DuckDB Client:

CLI

### Full Name:

Fabian Krüger

### Affiliation:

IBIS Prof. Thome AG

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### LINKED ISSUE #9404: copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_ym' (FORMAT PARQUET, PARTITION_BY (y,m)); missing some data
### What happens?

when do `copy to parquet partition by` operate ,some data missing with some error.

### To Reproduce

```sql
.timer on
create or replace table orders(m int,v int,j int);
insert into orders select i%12+1,i,j from range(360)t(i),range(1000)s(j);
copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_m' (FORMAT PARQUET, PARTITION_BY (m));
copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_y' (FORMAT PARQUET, PARTITION_BY (y));
copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_ym' (FORMAT PARQUET, PARTITION_BY (y,m));
```
each of the three copy raises an error,and missing data.
```sql
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_m' (FORMAT PARQUET, PARTITION_BY (m));
Run Time (s): real 0.093 user 0.109201 sys 0.015600
Error: IO Error: Could not create directory: 'orders_m\m=2' <---------------------
```
```sql
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_y' (FORMAT PARQUET, PARTITION_BY (y));
Run Time (s): real 0.145 user 0.140401 sys 0.031200
Error: IO Error: Could not create directory: 'orders_y\y=2013' <---------------------
```
```sql
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_ym' (FORMAT PARQUET, PARTITION_BY (y,m));
Run Time (s): real 0.995 user 1.123207 sys 0.405603
Error: IO Error: Could not create directory: 'orders_ym\y=2010\m=6' <---------------------
```
```sql
D select count(*) from orders;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       360000 │
└──────────────┘
Run Time (s): real 0.009 user 0.000000 sys 0.000000
```
```sql
D select count(*) from 'orders_ym/*/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       126000 │
└──────────────┘
Run Time (s): real 0.159 user 0.296402 sys 0.015600
```
```sql
D select count(*) from 'orders_y/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       276000 │
└──────────────┘
Run Time (s): real 0.028 user 0.015600 sys 0.000000
```
```sql
D select count(*) from 'orders_m/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       247120 │
└──────────────┘
Run Time (s): real 0.014
```

### OS:

windows7 x64

### DuckDB Version:

0.9.1

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### LINKED ISSUE #9466: Possible race-condition when using `COPY` with `PARTITION_BY`
### What happens?

When running:

```python
import duckdb
input = duckdb.sql('SELECT year(time) as year, month(time) as month FROM "updates.parquet"')
duckdb.sql('''COPY input TO 'output' (FORMAT PARQUET, COMPRESSION ZSTD, PARTITION_BY (year, month), OVERWRITE_OR_IGNORE 1)''')
```

Results in:

> duckdb.duckdb.IOException: IO Error: Could not create directory: 'output\year=2023'

### To Reproduce

It is difficult to reproduce with static data and seems to only happen with a specific input.

```
import duckdb
input = duckdb.sql('SELECT year(time) as year, month(time) as month FROM "updates.parquet"')
duckdb.sql('''COPY input TO 'output' (FORMAT PARQUET, COMPRESSION ZSTD, PARTITION_BY (year, month), OVERWRITE_OR_IGNORE 1)''')
```

It only happens if the directory has not previously been created.

Saving the `input` variable into a new parquet file, and then using it as the source of `COPY` does not trigger the error.

### OS:

Windows

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Colin Breame

### Affiliation:

Statkraft Germany GmbH

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #9360
Fixes #9404
Fixes #9466

### CODE REVIEW

**Comment by l1t1** [comment]
I tried the artifacts of https://github.com/duckdb/duckdb/actions/runs/6641418919 ,https://github.com/duckdb/duckdb/issues/9404 not fixed yet
```sql
v0.9.2-dev173 ef4d54e9f6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .timer on
D create or replace table orders(m int,v int,j int);
Run Time (s): real 0.000 user 0.000000 sys 0.000000
D insert into orders select i%12+1,i,j from range(360)t(i),range(1000)s(j);
Run Time (s): real 0.035 user 0.046800 sys 0.000000
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_m' (FORMAT PARQUET, P
ARTITION_BY (m));
Run Time (s): real 0.165 user 0.265202 sys 0.000000
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_y' (FORMAT PARQUET, P
ARTITION_BY (y));
Run Time (s): real 0.080 user 0.078001 sys 0.046800
Error: IO Error: Cannot open file "orders_y\y=2015\data_1.parquet": ????????????
·????

D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_ym' (FORMAT PARQUET,
PARTITION_BY (y,m));
Run Time (s): real 1.266 user 0.421203 sys 1.123207
Error: IO Error: Cannot open file "orders_ym\y=2029\m=8\data_2.parquet": ???????
?????·????

D select count(*) from 'orders_ym/*/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       331000 │
└──────────────┘
Run Time (s): real 0.317 user 0.764405 sys 0.171601
D select count(*) from 'orders_y/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       240000 │
└──────────────┘
Run Time (s): real 0.025 user 0.015600 sys 0.000000
D select count(*) from 'orders_m/*/*.parquet';
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       360000 │
└──────────────┘
Run Time (s): real 0.021 user 0.015600 sys 0.000000
```

**Comment by killerfurbel** [comment]
The errors of @l1t1 actually look like a different error, since they occur on writing the .parquet **files**, not the **folders**.

**In my tests, all the folder specific errors are gone with the build artefact.**

One possible reason for not being able to write files, which I already ran into, was: If the total path length exceeds ~260 characters, it is not possible to read/write those files for most programs in windows. Maybe @l1t1 could check if that is the case? To use paths with length > 260 characters on windows, there must be a registry setting being set and also the application needs to implement some little details (mostly, application manifest must include a longPathAware setting): https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by l1t1** [comment]
> The errors of @l1t1 actually look like a different error, since they occur on writing the .parquet **files**, not the **folders**.
> 
> **In my tests, all the folder specific errors are gone with the build artefact.**
> 
> One possible reason for not being able to write files, which I already ran into, was: If the total path length exceeds ~260 characters, it is not possible to read/write those files for most programs in windows. Maybe @l1t1 could check if that is the case? To use paths with length > 260 characters on windows, there must be a registry setting being set and also the application needs to implement some little details (mostly, application manifest must include a longPathAware setting): https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

I tried again, still failed, the path length is much less than 260
```
v0.9.2-dev173 ef4d54e9f6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .system cd
C:\Users\LD\AppData\Local\Temp\Rar$EXa22776.35094
D create or replace table orders(m int,v int,j int);
D insert into orders select i%12+1,i,j from range(360)t(i),range(1000)s(j);
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_m' (FORMAT PARQUET, P
ARTITION_BY (m));
D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_y' (FORMAT PARQUET, P
ARTITION_BY (y));
Error: IO Error: Cannot open file "orders_y\y=2009\data_0.parquet": ????????????
·????

D copy (select 2000+(v//12)y,m,v,j from orders) TO 'orders_ym' (FORMAT PARQUET,P
ARTITION_BY (y,m));
Error: IO Error: Cannot open file "orders_ym\y=2009\m=2\data_0.parquet": ???????
?????·????

```

**Comment by bucweat** [comment]
Coming from #9360. 

I ran my example script from #9360 which makes csv files. Output shown below.

Agree with what @killerfurbel mentioned above that the reported error is file related `Cannot open file "customer\h=21\data_0.csv"` where before it was directory related `IO Error: Could not create directory: 'customer\h=3'`. However, it does appear that the issue is still that a couple of folders did not get created...in example below, folder `customer\h=21` was not created which leads to file creation error `customer\h=21\data_0.csv`. 

Running with threads=1 works fine, and 24 folders are created: h=0 to h=23.

```
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.9.2-dev231   │ 182b824f28 │
└─────────────────┴────────────┘

┌────────────────────────────┐
│ current_setting('threads') │
│           int64            │
├────────────────────────────┤
│                          4 │
└────────────────────────────┘

build the customer table (will fail if it already exists which is ok)
Error: near line 12: Catalog Error: Table with name "customer" already exists!

show the count, min and max duedate for customer table
┌──────────┬─────────────────────┬───────────────────────┐
│ count(1) │        start        │          end          │
│  int64   │      timestamp      │       timestamp       │
├──────────┼─────────────────────┼───────────────────────┤
│   864000 │ 2022-01-02 00:00:00 │ 2022-01-02 23:59:59.9 │
└──────────┴─────────────────────┴───────────────────────┘

make sure the customer folder is empty

check that customer folder is empty/doesn't exist

 Volume in drive M is Shared Folders
 Volume Serial Number is 0000-0000
File Not Found
System command returns 1

*****************************************************************
*****************************************************************
*****************************************************************
first time copy to empty partition customer folder (expect error)
Error: near line 50: IO Error: Cannot open file "customer\h=21\data_0.csv": The system cannot find the path specified.


read the resulting partition folder and get count (expect 864000)
┌──────────┐
│ count(1) │
│  int64   │
├──────────┤
│   648072 │
└──────────┘

display the contents of customer
 Volume in drive M is Shared Folders
 Volume Serial Number is 0000-0000

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer

10/31/2023  06:28 AM    <DIR>          h=0
10/31/2023  06:28 AM    <DIR>          h=1
10/31/2023  06:28 AM    <DIR>          h=10
10/31/2023  06:28 AM    <DIR>          h=11
10/31/2023  06:28 AM    <DIR>          h=12
10/31/2023  06:28 AM    <DIR>          h=13
10/31/2023  06:28 AM    <DIR>          h=14
10/31/2023  06:28 AM    <DIR>          h=17
10/31/2023  06:28 AM    <DIR>          h=2
10/31/2023  06:28 AM    <DIR>          h=20
10/31/2023  06:28 AM    <DIR>          h=23
10/31/2023  06:28 AM    <DIR>          h=3
10/31/2023  06:28 AM    <DIR>          h=4
10/31/2023  06:28 AM    <DIR>          h=5
10/31/2023  06:28 AM    <DIR>          h=6
10/31/2023  06:28 AM    <DIR>          h=7
10/31/2023  06:28 AM    <DIR>          h=8
10/31/2023  06:28 AM    <DIR>          h=9
               0 File(s)              0 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=2

10/31/2023  06:28 AM         2,520,821 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,520,881 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=5

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM         2,584,820 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=4

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM         2,584,820 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=3

10/31/2023  06:28 AM         1,053,524 data_0.csv
10/31/2023  06:28 AM         1,503,316 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,556,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=10

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM           629,012 data_2.csv
10/31/2023  06:28 AM         1,991,828 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=17

10/31/2023  06:28 AM         2,446,100 data_0.csv
10/31/2023  06:28 AM           174,740 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=11

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM         2,620,820 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=20

10/31/2023  06:28 AM         1,258,004 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM         1,362,836 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=8

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM         2,584,820 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=6

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM         2,136,788 data_1.csv
10/31/2023  06:28 AM           448,052 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=1

10/31/2023  06:28 AM         2,512,820 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,512,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=0

10/31/2023  06:28 AM         2,501,714 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,501,774 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=7

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM         2,584,820 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=9

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM         2,584,820 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,584,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=14

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM         2,620,820 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM                20 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=13

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM           908,564 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM         1,712,276 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=12

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM                20 data_2.csv
10/31/2023  06:28 AM         2,620,820 data_3.csv
               4 File(s)      2,620,880 bytes

 Directory of M:\Scripts\appDuckDbEvaluation\dev\partition_example\customer\h=23

10/31/2023  06:28 AM                20 data_0.csv
10/31/2023  06:28 AM                20 data_1.csv
10/31/2023  06:28 AM         2,341,268 data_2.csv
10/31/2023  06:28 AM           279,572 data_3.csv
               4 File(s)      2,620,880 bytes

     Total Files Listed:
              72 File(s)     46,568,735 bytes
              18 Dir(s)  343,931,244,544 bytes free

```

**Comment by l1t1** [comment]
since the problem is creating directories,I have an idea. divide the work into two parts: first create all directories depand on `select distinct columns used for partition` serially, then copy each of the data files into a directory in parallel?
eg, PARTITION_BY (y,m)
```
.headers off
.mode c
.output a.bat
select distinct 'mkdir "ym\y='||2000+(v//12)||'\m='||m||'"' from orders;
.output
.system a.bat
copy (select 2000+(v//12)y,m,v,j from orders) TO 'ym' (FORMAT PARQUET,PARTITION_BY (y,m), OVERWRITE_OR_IGNORE 1);
```

**Comment by carlopi** [comment]
Thanks @l1t1 and all, I have a reproduction, also this secondary problem will be addressed.

**Comment by carlopi** [comment]
The fix should be in https://github.com/duckdb/duckdb/pull/9535.

**Pull request merged**
