### PR TITLE
CI: Add workflow to check new issues for code formatting

### PR DESCRIPTION
**Pull request by szarnyasg**
On occasion, users open issues which contain some code (e.g., SQL or Python) but the code is not formatted properly, making it difficult to read. I usually format this manually by editing the posts but this can be tedious.

I propose to add a feature to our GitHub Actions workflow, which reads the post, detects if it lacks formatting and submits a comment asking the user for format the code if necessary.

The current detection threshold is very conservative: it requires the post to have SQL keywords (`SELECT`, `FROM`, `WHERE`) and _zero_ code formatting. So if there's a single inline code snippet or a code block, it does not send a warning.

I tested this under my own account, which resulted in the following:

Screenshot 2024-01-05 at 16 04 42

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! While I agree this is annoying I wonder if detecting keywords is the right way to go about doing this. Generally this matters more when there are many lines of copy pasted code especially when that code includes special characters that get parsed by markdown. Perhaps there's a better way of doing the detection?

**Comment by szarnyasg** [comment]
Indeed there's a library called [guesslang](https://guesslang.readthedocs.io/en/latest/), available in [PyPI](https://pypi.org/project/guesslang/).

**Comment by Mytherin** [comment]
Sounds good, I would also add that the blocks of text should be at least a few lines (as it gets more annoying the more lines there are).

**Comment by szarnyasg** [comment]
I tried a number of alternatives:

### guesslang

[Guesslang](https://pypi.org/project/guesslang/) does what it says on the tin. Unfortunately, it is no longer maintained and only supports Python 3.9. Even worse, it requires a very outdated Tensorflow version which cannot be installed anymore from PyPI.

### Pygments

The Pygments syntax highlighter also has a language detector. Regrettably it doesn't work very well.

* Simple SQL queries (such as the the one below) are detected as "Text only":
    ```sql
    SELECT x AS w
    WHERE x < 32
    GROUP BY y
    HAVING count(z) > 5;
    ```
* Some complex SQL queries, e.g. the [recent query by Lloyd](https://github.com/duckdb/duckdb/issues/10269#issue-2088546646, are detected incorrectly as "CSS+Lasso"

**Comment by szarnyasg** [comment]
Bump

**Comment by Mytherin** [comment]
Let's give it a shot

**Comment by szarnyasg** [comment]
Thanks!

**Pull request merged**
