### PR TITLE
Fix for CI Regression Failure

### PR DESCRIPTION
**Pull request by maiadegraaf**
PR #11101 changed the names of several profiling names. As a result `plan_cost_runner.py` no longer correctly runs. 

This PR adjusts the scripts to correctly correspond to the new names.

I also noticed the profiling output was still outputting the old name in one location so that has been fixed as well. Since this has been adjusted (in `profiling_info.cpp`), the regression CI still fails, but this PR should fix that.

### CODE REVIEW

**Review by Tmonster — CHANGES_REQUESTED** [review]
Don't know how, but it looks like the Join Order Regression tests are still failing? Otherwise looks good to me 👍 

https://github.com/duckdb/duckdb/actions/runs/9258039460/job/25467379590?pr=12273

Edit: Under Regression / Regression Tests the Join order regression failed

Edit 2: Oh wait, it is because current main doesn't have `operator_cardinality`?

**Comment by maiadegraaf** [comment]
> Edit 2: Oh wait, it is because current main doesn't have `operator_cardinality`?

Yes, that's why it still fails. Should pass after it's merged.

**Review by Tmonster — APPROVED** [review]
lgtm

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
