### PR TITLE
Fix various BufferManager issues

### PR DESCRIPTION
**Pull request by lnkuiper**
Summary:
1. Make `BufferManager::RegisterMemory` private; use `BufferManager::Allocate` instead. This ensures that the created block is always pinned once, adding it to the eviction queue. Previously, a block created with `RegisterMemory` would use memory until it was deleted, even if it was never used. I don't think this was a problem anywhere in the codebase, but now we're sure it will never be a problem in the future.
2. Correct an assertion that checked for equal sizes when re-using a block. The assertion now properly accounts for alignment with `Storage::SECTOR_SIZE`
3. Use `BufferAllocator` instead of `BufferManager::Allocate` for allocations with non-regular sizes, such as the hash map in the `JoinHashTable`. Allocations of these sizes are _very_ unlikely to be re-used, so there is no point in allocating this on a buffer-managed page.
4. Use `BufferAllocator` for various usages of `StringHeap` / `ArenaAllocator`. The `BufferAllocator` has a slightly higher overhead than using the default `Allocator`, but this is not really an issue for these kinds of allocations because they are only a few large allocations. Routing these allocations through the `BufferManager` allows us to keep track of the size `StringHeap` in buffer-managed `ColumnDataCollection`s, which is useful when we need to materialize data.
5. Add some verification to `RowDataCollection` to ensure that the memory usage of the buffer-managed blocks aligns with the capacity. I've also changed `RowDataCollection::SizeInBytes` to be more accurate, which should help with deciding when to do out-of-core processing.
6. Add a few tests to `test_buffer_manger.cpp` to make sure we don't break the buffer manager in the future. I've also corrected some `D_ASSERT` here to `CHECK` so that checks are run in release mode too.
7. I ran `make format-fix` which formatted a bunch of files.

### CODE REVIEW

**Comment by Mytherin** [comment]
I would say downgrade your version for now.

**Comment by lnkuiper** [comment]
The CI failures were unrelated, just merged with master and pushed to re-run

**Comment by lnkuiper** [comment]
I think this is good to go. The failures are unrelated.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
