### PR TITLE
Adjust the logic for adding type dependencies to temp tables

### LINKED ISSUE #8062: Cannot insert JSON values into TEMPORARY tables (Conversion Error)
### What happens?

Inserting a string value into a _temporary_ table that has a JSON-typed column fails with a conversion error. (Non-temporary tables work fine.)

### To Reproduce

```
CREATE TEMP TABLE foo (c_array json);
INSERT INTO foo VALUES ('[1, 2, 3]');
```

The insert statement will throw the error: ```Error: Conversion Error: Could not convert string '[1, 2, 3]' to UINT8```

### OS:

OS X

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI and Python

### Full Name:

Josh Wills

### Affiliation:

Unaffiliated

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by jwills**
Fixes #8062

### CODE REVIEW

**Comment by jwills** [comment]
y'all this is one of my standard PRs where I try to come up with the smallest possible fix for the problem I am encountering, but as always if there is a better way to do this I am happy to update this PR and/or close it out, just let me know. 🙇

**Comment by Mytherin** [comment]
@pdet could you have a look at this PR?

**Review by pdet — APPROVED** [review]
LGTM!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
