### PR TITLE
Fix issue related to duplicate columns in using clause

### LINKED ISSUE #4561: [Fuzzer] Binding assertion error
Originally discovered in #4152

```
CREATE TABLE t1(c0 INT);
SELECT * FROM (t1 JOIN t1 t2 USING (c0, c0)), (SELECT 2);
```

Actual:
src/planner/bind_context.cpp:513: void duckdb::BindContext::AddContext(duckdb::BindContext): Assertion `other_alias->bindings.find(col) == other_alias->bindings.end()' failed

Expected:
An error about duplicate "c0" reference in using clause expected.

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #4561 

We were allowing duplicates in the `using_columns`, this caused an assertion to be triggered.
I changed it to skip duplicates, because logically that makes sense to me (`USING (a,a)` == `USING(a)`)

And this didn't break any tests which surprised me, because there is code that deals with `if (using_bindings->size() > 1) {` in GetUsingBinding.

I hope someone can review this and give me some insight into the inner workings of this clause, because it's a little unclear to me what every component is for.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Can we add a bunch of tests for this, including at least the test from the PR, but ideally also more tests involving e.g. chains of multiple joins on the same column:

```sql
create table tbl as select 42 AS i;
select * from tbl t1 join tbl t2 using (i, i) join tbl t3 using (i, i, i);
```

Or joins on duplicate columns mixed with non-duplicate columns:

```sql
create table tbl as select 42 AS i, 84 as j;
select * from tbl t1 join tbl t2 using (i, j, i) join tbl t3 using (i, i, i, j, i);
```

**Comment by Tishj** [comment]
Thanks for the suggestions, those are indeed problematic.
The first query now triggers:
```c++
   126          if (entry == using_columns.end()) {
-> 127                  throw InternalException("Attempting to remove using binding that is not there");
   128          }
```

So I guess that answers my question, "What is the reason we allow duplicate USING clauses"

**Comment by Tishj** [comment]
Hmm even without my changes this is giving an error
```c++
select * from tbl t1 join tbl t2 using (i, i) join tbl t3 using (i, i, i);
================================================================================
Actual result:
Binder Error: Ambiguous column reference: column "i" can refer to either:
[t2.i, t1.i][t2.i, t1.i]
```

**Comment by Mytherin** [comment]
Superseded by #4737

**Pull request closed without merging**
