### PR TITLE
Extension linking fix

### PR DESCRIPTION
**Pull request by samansmink**
The extension loading mechanism was not working as intended. The extensions were linked with the duckdb library which made them require a duckdb shared object. This does not work in most cases actually but was not caught by any tests as the shared library was always present.

## This pr
- removes the dependency on libduckdb for extensions in macos and linux, windows already worked
- removes shared duckdb lib from after build in extension CI to confirm extensions do not require it
- changes the way the node c++ binary is loaded (RTLD_GLOBAL flag added to dlopen) this fix is required for extensions to work on linux where RTLD_LOCAL is the default. 
- adds an extension loading test to the node tests that confirms extensions can be loaded and work in node.
- adds a BUILD_MAIN_DUCKDB_LIBRARY flag that can be used to disable main duckdb compilation to be able to quickly build the loadable extensions  for testing
- the NodeJS.yml CI now runs the extension test on the tpch and httpfs extensions for linux, osx and windows.

## potential followup
- add similar extension loading test to R and python?
- test other extensions in node?

### CODE REVIEW

**Comment by Mytherin** [comment]
This might also fix #3048

**Comment by Mytherin** [comment]
Could you have a look at the failing NodeJS Windows tests?

**Comment by samansmink** [comment]
The node extension loading tests have been disabled on the windows ci for now due to an issue with delay loading in the node addon. Extension loading ci does work on linux and mac os.

**Comment by samansmink** [comment]
I think this PR can be merged? The two tests that fail seem unrelated to the changes: Codecov is a negligible difference and the python failure seems to be the same as was fixed in https://github.com/duckdb/duckdb/pull/3221

**Comment by Mytherin** [comment]
Indeed it can be, thanks!

**Pull request merged**
