### PR TITLE
Test docker images: improvement and connected fixes

### PR DESCRIPTION
**Pull request by carlopi**
Few changes connected to build system (and tests of the build system):

1. Bump all cmake_minimum_required instructions to use a range between whatever was specified to 3.29. Given this was source of warning / noise and potentially source of errors given 2.8.12 is not supported anymore by recent CMake's (that require at least 3.5 support)

2. Move from fatal errors to cmake's WARNING when info about commit and version can't be fetched. This allows to remove the dependency on git. A strict mode can be enable passing `-Werror` to CMake.

3. Minor ART code change around reserve on vector<bool>. It caused a warning during compilation on gcc.

4. Add dockerized tests for: `amazonlinux:latest`, `ubuntu:20.04`, `ubuntu:devel`, `alpine:latest`, `centos`. Those act also as blueprints for how to compile duckdb in such platforms

5. Revert a recent unwanted change that fixed polars version (with @Tishj)

### CODE REVIEW

**Comment by carlopi** [comment]
CI failure on [Linux HTTPFS](https://github.com/duckdb/duckdb/actions/runs/9062070381/job/24900125817?pr=12026#logs) is non-deterministic and happening also on main.

**Comment by Mytherin** [comment]
Thanks! Could you expand a bit on why the upper bound of 3.29 on CMake is added/chosen?

**Comment by carlopi** [comment]
> Thanks! Could you expand a bit on why the upper bound of 3.29 on CMake is added/chosen?

Sure, minimal changes to remove warning / unsound behaviour would be move from `cmake_minimum_required(VERSION 2.8.12)` to `cmake_minimum_required(VERSION 2.8.12...3.5)`, that translates as: accept any cmake standard between those. Note that having at least 3.5 in the range is a requirement for recent CMake version that are discontinuing some older compatibility models.

Moving away from `2.8.12` when not forced is not great, since some older distribution (that might still be of interested) support recent CMake versions only by basically compiling them from source. This means that for example `amazonlinux:2` can't work using ready available tools, and has been commented out.
Unsure if effort should be put in fixing that, possibly support can be there only for building main library / CLI binary, but with no support for building loadable extensions. Unsure if that might have enough value.

The latest that is currently tested in the Docker setup is 3.27, so for that one there is some signal that it does work, possibly it would be better to use 3.27 as upper bound of confidence, and the tests would be the Docker test `alpine:latest`.

**Comment by Mytherin** [comment]
I still don't follow - why include the upper bound at all?

**Comment by carlopi** [comment]
> I still don't follow - why include the upper bound at all?

Cmake_minimum_required is a big mess, I find, https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html, but I guess that's the price of compatibility.

Basically having a single value (instead of a range) means that there is a trade off between working on older versions of CMake VS being flagged as non-compliant by newer versions.

The idea of the range is saying that whatever is in the range does work.
Remaining questions are then:
What's to put as lower value, and I though of preserving information already present.
What to put as high value? The highest version of CMake that is existing (that is also what we have on work laptop via brew).
Top of the range needs to be >= 3.5 to be compliant with recent versions of CMake, I though then 3.29 would also work.

**Comment by Mytherin** [comment]
Could we put eg 3.99 as the highest value?

**Comment by carlopi** [comment]
> Could we put eg 3.99 as the highest value?

That we can't do, I skipped an important part, but we assume future versions will be compatible with older cmake standards / stuff will not be properly deprecated.

On the other side, if cmake devs decide that version X introduces a bunch of breaking changes, writing X implies being aware (and compatible) with those changes, so can't be done for non-existing versions.

**Comment by Mytherin** [comment]
Alright, let's keep it like this then

**Pull request merged**
