### PR TITLE
Support for Brace Expansion in FileSystem

### PR DESCRIPTION
**Pull request by douenergy**
We currently support glob patterns for filename expansion, which is a great feature. However, filesystem support for retrieving all files varies. For instance, some systems like `S3  ListObjectsV2` offer this capability, while others, like GitHub and HuggingFace , do not.

I believe implementing bash-style brace expansion would be highly beneficial for several reasons:

1. Even when a filesystem supports listing files, this operation can sometimes be expensive. By supporting brace expansion, we can avoid these heavy operations.

2. It's quite common to encounter URLs with simple, repetitive patterns within a group of datasets. For example:

https://huggingface.co/datasets/vivym/midjourney-messages/resolve/main/data/000000.parquet
https://huggingface.co/datasets/vivym/midjourney-messages/resolve/main/data/000001.parquet
https://huggingface.co/datasets/vivym/midjourney-messages/resolve/main/data/000002.parquet

With brace expansion, accessing these files becomes more efficient. For instance, we can use a command like 
```sql 
SELECT Count(*) FROM 
'https://huggingface.co/datasets/vivym/midjourney-messages/resolve/main/data/00000{0..4}.parquet' 
```
image

to process multiple files in a simplified manner.

I believe that both [Databend](https://github.com/datafuselabs/databend) and [ClickHouse](https://github.com/ClickHouse/ClickHouse) also support some form of this expansion.

@Mytherin  @samansmink  Please take a took !

### CODE REVIEW

**Comment by douenergy** [comment]
cc @severo

**Comment by carlopi** [comment]
Just a note, this already can be made sort of work, in a more verbose version, by doing for example:
```sql
SELECT count(*)
    FROM read_parquet([('https://huggingface.co/datasets/vivym/midjourney-messages/resolve/main/data/{:06d}.parquet').format(n) for n in range(5)]);
```

---

And another comment, current implementation seems to imply that globs and brace expansions are exclusives, I am not sure they can't be made work in combination (in some cases), but in any case I would it make it more clear with a specific error (and test) that combinations of `{}` and `*` are not handled (not that it's a big deal, given currently they are also not handled).

And maybe also a test like `SELECT count(*) FROM glob('test/file/path/t{0..1}.parquet')`.

Thanks for the PR.

**Comment by Mytherin** [comment]
Thanks for the PR! I think that this is a great idea. I do agree with Carlo keeping the implementation together with globs would be preferable. Globs already have support for wildcards (`?`) and square brackets (`[]`) that can be mixed in with the regular syntax, for example:

```bash
$ mkdir t1
$ mkdir t2
$ mkdir t1/a 
$ mkdir t2/b
$ duckdb -c "copy (select 42 as a) to 't1/a/f.parquet'"
$ duckdb -c "copy (select 84 as a) to 't2/b/g.parquet'"
```

```sql
SELECT * FROM read_parquet('t*/[ab]/*.parquet', filename=true);
┌───────┬────────────────┐
│   a   │    filename    │
│ int32 │    varchar     │
├───────┼────────────────┤
│    84 │ t2/b/g.parquet │
│    42 │ t1/a/f.parquet │
└───────┴────────────────┘
```

Extending globbing to include support for [brace expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) seems like it would be the most natural extension to the system. For brace expansion, braces are expanded first, *followed* by (potentially) running multiple globs. For example, this brace expression:

```bash
t*/{a,b}/*.parquet
```

Is equivalent to running the following two globs and concatenating the resulting files:

```bash
t*/a/*.parquet
t*/b/*.parquet
```

I also think that if we are going to support brace expansion, we should support it fully similar to bash/zsh. This includes:

* Support for comma-separated lists (e.g. `{pat1,pat2}`
* Nested braces (e.g. `{{0..9}{0..9}}`)
* Ranges of all (ASCII?) characters (e.g. `{a..z}`, `{A..Z}`, `{0..A}`)
* Increments (`{0..10..2}`)
* Different integer expansions based on leading zeros (e.g. `{0..99}` vs `{00..99}`, and `{0..999}` vs `{00..999}` vs `{000..999}`)
* Reverse ranges (e.g. `{9..0}`)
* Escaping (e.g. `\{0..9\}` results in the literal string `{0..9}`)
* Combinations of these (e.g. `{{0..9},{1..9}{0..9}}`)

**Comment by szarnyasg** [comment]
Hi @douenergy, thanks for opening this PR. It seems to be stale without any recent activity. Would you be interested in picking it up?

**Comment by douenergy** [comment]
@szarnyasg  Sure, but this can be merged between 0.10.0 and 1.0.0. It seems there will be no new features before 1.0.0. Am I correct ?

**Comment by Mytherin** [comment]
We have a `feature` branch where new features can go to, that will be merged into main (albeit after 1.0). Then it will be part of v1.1.

**Pull request closed without merging**
