### PR TITLE
Allow untyped parameters in queries

### PR DESCRIPTION
**Pull request by krlmlr**
such as `SELECT (? = ...)`

Are there any downsides here?

Required for DBItest. What's a good way to test this?

Includes #1239.

### CODE REVIEW

**Comment by Mytherin** [comment]
In general prepared statement parameters should have a known type. Right now we indeed throw an error message if we can't determine the type from the query, but we could default that type to `VARCHAR` instead (e.g. `SELECT ?`). Not sure how @hannesmuehleisen feels about that.

**Comment by krlmlr** [comment]
DBItest works much better with this patch. I think in this location we only need to reserve space large enough, type assignment happens elsewhere. It passes all tests.

What's the best was to move forward?

**Comment by krlmlr** [comment]
Could the Linux failure be related to this patch?

**Comment by hannesmuehleisen** [comment]
I think this patch is not the way forward. its possible we should derive types for prepared statements in more places, if you could give specific cases where the type is not inferred i'm happy to do so.

**Pull request closed without merging**
