### PR TITLE
[Python] Compatibility with `pandas==2.2.0`

### PR DESCRIPTION
**Pull request by Tishj**
1. `pybind11` can't know that we're assigning to an accessor, so it uses `__getitem__` which will create a copy of the column requested with `df['a']`, making changes to that copy does not affect the original dataframe.
We now use `df.__setitem__('a', ...)` directly to fix this.

2. `pandas._testing.getTimeSeriesData` has been removed, we used this in a couple places so now it's part of `conftest.py`

### CODE REVIEW

**Comment by Tishj** [comment]
The outstanding issue is out of our control, I've submitted an issue to Arrow for it:
<https://github.com/duckdblabs/duckdb-internal/issues/1101>

**Comment by Mytherin** [comment]
Thanks for the PR! Can we skip the failing tests for now for `pandas==2.2.0` with a comment on this? I would prefer not to have CI fail until the next arrow release.

**Comment by Tishj** [comment]
> Thanks for the PR! Can we skip the failing tests for now for `pandas==2.2.0` with a comment on this? I would prefer not to have CI fail until the next arrow release.

Yea I agree 👍

**Comment by Tishj** [comment]
> Thanks for the PR! Can we skip the failing tests for now for `pandas==2.2.0` with a comment on this? I would prefer not to have CI fail until the next arrow release.

Do you want to skip indefinitely for now, or should I just skip until the next major arrow release, then we'll deal with it again when the time comes
Just so we don't forget about the skipped test(s)

**Pull request merged**
