### PR TITLE
add httpfs support to python package

### PR DESCRIPTION
**Pull request by pkit**

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good, but it seems like the included test also publishes and deploys a package with HTTPFS enabled. Could you remove the deployment code from that CI job? We would prefer to publish the HTTPFS as a separate package as described in the previous PR so we can avoid shipping/linking to OpenSSL as it is not required for the core library to function.

**Comment by pkit** [comment]
Do I just remove the `Deploy` stanza and that's it?

**Comment by Mytherin** [comment]
Yeah I think just removing that is sufficient. No other builds necessary for now.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
