### PR TITLE
Support for Recursive Common Table Expressions

### PR DESCRIPTION
**Pull request by kryonix**
This PR ~partially~ solves issue #239 by adding support for recursive CTEs ~that use UNION ALL semantics~.

Edit: UNION and UNION ALL is now supported.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thank you very much for the contribution!

The code looks very good. I mainly would like to see more tests before merging, particularly w.r.t. subqueries (as they can be very nasty). I would also add some tests with strings. Looking at your test I would suggest for example the following testcases (but more is always better!):

```sql
-- strings and multiple columns
with recursive t as (select 1 as x, 'hello' as y union all select x+1, y || '-' || 'hello' from t where x < 3) select * from t;
-- referencing same CTE multiple times
with recursive t as (select 1 as x union all select x+1 from t where x < 3) select min(a1.x) from t a1, t a2;
-- nested uncorrelated subquery
with recursive t as (select 1 as x union all select x+(SELECT 1) from t where x < 3) select * from t;
-- nested correlated subquery
with recursive t as (select 1 as x union all select (SELECT x+1) from t where x < 3) select * from t;
-- use with recursive in table creation
create table integers as with recursive t as (select 1 as x union all select x+1 from t where x < 3) select * from t;
-- more complex uncorrelated subquery
with recursive t as (select (select min(x) from integers) as x union all select x+1 from t where x < 3) select * from t;
```

Also perhaps some tests with non-recursive queries, e.g.:
```sql
-- t is not referenced in the recursive part
with recursive t as (select 42 as x union all select 42) select * from t;
-- no recursive part at all
with recursive t as (select 42) select * from t;
```

And with infinite recursive queries:
```sql
-- infinite recursive query, maybe we want to set a maximum recursion depth?
with recursive t as (select 42 as x union all select * from t) select * from t;
```

Thanks again for the effort :) Very exciting to have recursive queries in DuckDB!

**Comment by kryonix** [comment]
Thank you for the suggested test cases. I have found and fixed some issues during testing. But I was not able to get correlated queries to work.

```SQL
with recursive t as (select 1 as x union all select (SELECT x+1) from t where x < 3) select * from t;

-- Physical Plan:
PROJECTION[x]
REC_CTE
    PROJECTION[1]
        DUMMY_SCAN
    PROJECTION[SUBQUERY]
        DELIM_JOIN[SINGLE x=x]
            FILTER[x<3]
                CHUNK_SCAN
```

This query fails with:
```
Assertion failed: (!finalized), function Build, file /duckdb/src/execution/join_hashtable.cpp, line 136.
[1]    99886 abort      ./duckdb_cli
```

The physical plan looks fine as far as I can tell. I think the problem here is that it is not possible – or intended? – to _rescan_ a DELIM_JOIN (this could also be the case with other operators). In order to evaluate recursive CTEs I have no other option than to iteratively rescan the recursive term.
Currently that is done by getting a new operator state [physical_recursive_cte.cpp#L61](https://github.com/kryonix/duckdb/blob/64e0f48d0ffd840ba662b8057eae7706e1607757/src/execution/operator/set/physical_recursive_cte.cpp#L61) after each iteration. But maybe that is not the right way?

**Comment by hannesmuehleisen** [comment]
I also really like this test case: https://gist.github.com/janickr/58fab629ee3ea7e5638a

**Comment by Mytherin** [comment]
@kryonix 

I looked into it and it seems that the problem doesn't lie with the subquery but rather with the hash join. As the hash table is not part of the operator state but of the join operator it does not get reset when you request a new operator state. The assertion is triggered when you try to insert into a hash table that has already been completely constructed.

I would say for now it would be better to just throw an error if a join is encountered in the recursive CTE. This is not so difficult to fix, however,  I plan to rework the infrastructure of the operator states entirely soon. We plan to move to a pipeline-based model to enable parallel execution, which will involve a rework of where the hash tables are stored anyway. For that reason I think it's better to just leave the fix for later.

Please leave in the tests and add a `REQUIRE_FAIL` around them, then I can fix them later on when I rework the hash table placement.

**Comment by kryonix** [comment]
I've updated this pull request, because now both recursive CTE semantics are supported.

> I looked into it and it seems that the problem doesn't lie with the subquery but rather with the hash join

Thanks for having a look. That's kind of what I expected since the second query worked fine. The rework of the state infrastructure sounds great, just about the right timing to add recursive evaluation into consideration for the new design I think.


> And with infinite recursive queries:
> -- infinite recursive query, maybe we want to set a maximum recursion depth?
> ```with recursive t as (select 42 as x union all select * from t) select * from t;```

Limitation of the maximum recursion depth is something many DBMS do these days. I don't like the idea too much personally, because there are applications that need an arbitrary number of recursive steps. IFF you decide to add this limitation, I would strongly suggest to make it configurable in a way that permits unlimited recursive steps.

**Comment by Mytherin** [comment]
Great news, good that the HT approach worked. 

> Limitation of the maximum recursion depth is something many DBMSs do these days. I don't like the idea too much personally, because there are applications that need an arbitrary number of recursive steps. IFF you decide to add this limitation, I would strongly suggest to make it configurable in a way that permits unlimited recursive steps.

I checked how other systems do it, and it seems that SQLite and Postgres don't have a maximum recursion depth, MySQL has a limit of 1000 by default. However, one nice thing that SQLite has is that it streams out the results, so if you do for example the infinite query:
```sql
with recursive t as (select 42 as x union all select * from t) select * from t;
```
It would output a stream of "42"s into the terminal. Postgres will just loop forever on constructing the result set. Perhaps it would be possible for us to emulate this behaviour and also stream results as they are constructed? That might be problematic when we have multiple references to the same CTE, however.

**Comment by kryonix** [comment]
Oracle also limits the recursion depth to 1000, Microsoft SQL Server to 100 by default, but it is configurable in both systems. SQL Server added an `OPTION (MAXRECURSION n)`-_hint_ which can be appended to any recursive CTE. This allows to set the recursion depth locally. There is no limit if n is set to zero. I still prefer the Postgres way, though ;-)

> It would output a stream of "42"s into the terminal. Postgres will just loop forever on constructing the result set. Perhaps it would be possible for us to emulate this behaviour and also stream results as they are constructed? 

Postgres' implementation of recursive CTEs is non blocking. New tuples are immediately returned to the parent operator. I think the reason why you do not see a stream of "42"s is related to psql, but I'm not sure about that.

The implementation in DuckDB should behave the way you describe it, theoretically. Similar to the Postgres implementation, new DataChunks are immediately returned to the parent operator. That's the reason why it is possible to make your query terminate by just adding a `LIMIT`-clause:

```
with recursive t as (select 42 as x union all select * from t) select * from t limit 10;
```

> That might be problematic when we have multiple references to the same CTE, however.

Postgres uses a second physical operator `CTE SCAN` to buffer the result of a CTE. It should be an easy task to add something similar to DuckDB. A bit more logic would be required for binding base table references in this case. That should improve the performance of both, recursive, and regular CTEs with multiple references. Inlining could still be applied in case there is just a single reference.

**Comment by Mytherin** [comment]
> Postgres' implementation of recursive CTEs is non blocking. New tuples are immediately returned to the parent operator. I think the reason why you do not see a stream of "42"s is related to psql, but I'm not sure about that.

Yeah that could indeed just be a client-side limitation.

> The implementation in DuckDB should behave the way you describe it, theoretically. Similar to the Postgres implementation, new DataChunks are immediately returned to the parent operator. That's the reason why it is possible to make your query terminate by just adding a LIMIT-clause:

Excellent. I think that is more than enough then, as long as the result streams out. The user can then manually cancel the query when it waits forever. An iteration limit can potentially be added later, but for now is not necessary.

I took another look at the code and I think this is ready to merge. Let me know if you think it is ready, then I will merge it in.

**Comment by kryonix** [comment]
Awesome! Thanks for the merge.

**Pull request merged**
