### PR TITLE
Fix #4677. Correctly set_not_null when table contains generated column

### LINKED ISSUE #4677: [Fuzzer] heap-buffer-overflow on ALTER statement
### What happens?

Run the following statements:
```
CREATE TABLE t0(c0 AS (1), c1 INT);
ALTER TABLE t0 ALTER c1 SET NOT NULL;
```
The address sanitizer will report a heap-buffer-overflow.

The alter statement should succeed.

### To Reproduce

Run the statement above.

### OS:

Linux

### DuckDB Version:

latest from sources

### DuckDB Client:

Shell

### Full Name:

Pedro Ferreira

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by zippond**
Symptom
===============
Fix Issue #4677. heap-buffer-overflow when set not null against table with generated column presented.

	
Root Cause
===============
Related to generated columns. TableCatalogEntry::columns contains all columns include the generated columns, while DataTable::column_definitions contains the real columns only. 
The index of Constraint and BoundConstraint doesn't match after bounding. And the NotNullConstraint.index might overflow the DataTable::column_definitions' size() which cause a segfault.

Fix
===============
Use BoundNotNullConstraint to check new added constraint. And the BoundNotNullConstraint::index can be get from ColumnDefinition::StorageOid()

Test 
===============
Tests has been added to add/drop not_null with generated column being presented.

Other Info
===============
With generated column presented, I see similiar issues with "alter type", "update table", "remove column", etc. 
I'm not sure if there could be a fix in generated_column logic to fix all of them. Anyway, I'll open seperated issues for now.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good to me. Could we also add a test where we run `SET NOT NULL` on the generated column directly, i.e.:

```sql
ALTER TABLE t0 ALTER c0 SET NOT NULL;
```

(This can fail with an unsupported message for now)

**Comment by Mytherin** [comment]
Here is the test I created while working on this issue, perhaps you can also include this in the PR?


```sql
# name: test/fuzzer/pedro/alter_column_generated.test
# description: Issue #4677: heap-buffer-overflow on ALTER statement
# group: [pedro]

statement ok
PRAGMA enable_verification

statement ok
CREATE TABLE t0(c0 AS (1), c1 INT);

statement ok
ALTER TABLE t0 ALTER c1 SET NOT NULL;

statement ok
ALTER TABLE t0 ALTER c1 SET NOT NULL;

statement error
ALTER TABLE t0 ALTER c0 SET NOT NULL;

statement error
INSERT INTO t0 VALUES (NULL);

statement ok
DROP TABLE t0;

statement ok
CREATE TABLE t0(c0 AS (1), c1 INT);

statement ok
INSERT INTO t0 VALUES (NULL);

statement error
ALTER TABLE t0 ALTER c1 SET NOT NULL;

```

**Comment by zippond** [comment]
Sure. Just added these tests.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
