### PR TITLE
For range joins use NL join when the LHS or RHS side is tiny

### PR DESCRIPTION
**Pull request by Mytherin**
For range joins - when the cardinality estimator figures out that one of the two sides of the join is very small (less than 5 rows) - we now switch to using the nested loop join instead of the IE Join or the Merge join.

The reason for that is that the IE join and merge join both introduce significant costs that depend on the size of both sides of the table:

* The merge join sorts chunks on both sides
* The IE join materializes both sides

As such, when one of the sides is tiny and the other side is gigantic, the NL join performs significantly better.

The following query (found by @pdet) triggered this optimization:

```sql
SELECT
    (SUM(trip_distance * fare_amount) - SUM(trip_distance) * SUM(fare_amount) / COUNT(*)) /
    (SUM(trip_distance * trip_distance) - SUM(trip_distance) * SUM(trip_distance) / COUNT(*)) AS beta,
    AVG(fare_amount) AS avg_fare_amount,
    AVG(trip_distance) AS avg_trip_distance
FROM 
    yellow_tripdata_2016_01,
    (
        SELECT 
            AVG(fare_amount) + 3 * STDDEV_SAMP(fare_amount) as max_fare,
            AVG(trip_distance) + 3 * STDDEV_SAMP(trip_distance) as max_distance
        FROM yellow_tripdata_2016_01
    ) AS sub
WHERE 
    fare_amount > 0 AND
    fare_amount < sub.max_fare AND 
    trip_distance > 0 AND
    trip_distance < sub.max_distance
```

In this query we do a range join between a big table and an ungrouped aggregate. The ungrouped aggregate always has a cardinality of 1. This query experienced a large regression because of the IE join (and previously because of the merge join). 

We have added a similar query on synthetic data to the benchmark runner, and this optimization speeds up the query from `14` seconds to `0.35` seconds (around 40X faster).

### CODE REVIEW

**Comment by pdet** [comment]
This was fast :-)

**Comment by Mytherin** [comment]
Yes, we could indeed turn this into a setting

**Comment by SartorialOffense** [comment]
That would be fantastic.  Should I open an issue on this?

**Comment by Mytherin** [comment]
Sure, just link this issue and say we discussed it (e.g. “as discussed in #5399”)

**Pull request merged**
