### PR TITLE
[Dev] Change internals of `StringUtil::GenerateRandomName`

### LINKED ISSUE #12541: duckdb segv seg faults depending on python import order
### What happens?

Running any duckdb sql command segfaults depending on what order duckdb is imported.

The error doesn't occur if a line in socketify, cffi.dlopen another C++ library (uWebsockets) is commented out.

What could be the problem? 

### To Reproduce

Works:
``` python
import duckdb
import socketify
duckdb.sql('select 1') 
```

Doesn't work
``` python
import socketify
import duckdb
duckdb.sql('select 1')
```

### OS:

x64, ubuntu

### DuckDB Version:

Current

### DuckDB Client:

Python

### Full Name:

Anthony Leung

### Affiliation:

Intelligent Calculations

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #12541 

The crash has been traced down to the use of `std::hex`.
I've replaced it with a hex character string.

```py
import socketify
import duckdb

duckdb.sql("select 42").fetchall()
```

### CODE REVIEW

**Comment by carlopi** [comment]
I think usage of naked `rand()` are basically forbidden if you want to comply to CRAN rules, given those modify externally visible global state.

**Comment by Tishj** [comment]
That sounds fun, then I'm out of ideas.
It seems like the solution might be to statically link the stdlib instead, at least in the python package

**Comment by carlopi** [comment]
I would assume the problem is not the usage of the wrapper (`std::mt19937`), but how entropy is generated, that is via the call to `rd()`.

I would either swap usage of mt19937 with duckdb/common/random_engine.hpp, or swap the call to `rd()` with RandomEngine (that though its' still using `random_device` under the hood, so I am not sure how that would solve it)

**Comment by Mause** [comment]
Fwiw, random_device is related to the rocksdb crash, so it's not without issue

**Comment by Mytherin** [comment]
Indeed we should not use `rand`. Perhaps we should just ban `<random>` altogether? We have `pcg_random` that we use elsewhere for random number generation - I would vote for replacing `<random>` with `"duckdb/common/random.hpp"` everywhere in the code and providing some helper methods that make the transition easier.

**Comment by Mytherin** [comment]
Ah I missed the part about it using `random_engine` still. I suppose that's still better than using `<random>` altogether though.

**Comment by Tishj** [comment]
> Fwiw, random_device is related to the rocksdb crash, so it's not without issue

@Mause we actually had another look and in this case at least it's not related to `std::random_device`, the culprit was `std::hex` for some unknown reason

**Review by carlopi — APPROVED** [review]
Thanks, I think this makes sense, and solves the problem at hand.

More in general there is something weird where we mix up symbols between default c++ standard libraries and the standard libraries that `socketify` statically links in and then partially re-export.
I think this is a problem on `socketify` end, we might want to raise it, but we will just have to work around this.

**Comment by Tishj** [comment]
@Mytherin please restart <https://github.com/duckdb/duckdb/actions/runs/9777140115/job/26997333726?pr=12806>

```
Processing triggers for dbus (1.12.2-1ubuntu1.4) ...
 The most current stable version of Git for Ubuntu.

For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .

╔═════════════════════════════════════════════════════════╗
║ NOTE ABOUT THE “WEAK ALGORITHM” WARNING IN UBUNTU 24.04 ║
╚═════════════════════════════════════════════════════════╝
For details about the warning “W: https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/dists/noble/InRelease: Signature by key E1DD270288B4E6030699E45FA1715D88E1DF1F24 uses weak algorithm (rsa1024)”, see:

https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854
https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/2065932

There’s nothing that PPA owners can do about this for now, as the key is fully controlled internally by Launchpad.
 More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
Error: retrieving gpg key timed out.
```

**Comment by Mytherin** [comment]
Thanks!

**Comment by leunga1000** [comment]
Thanks!

**Pull request merged**
