### PR TITLE
Consistent formatting of GHA workflow files

### PR DESCRIPTION
**Pull request by krlmlr**
With VS Code and "prettier", no automation yet.

Mostly whitespace changes, to simplify refactoring.

### CODE REVIEW

**Comment by Mause** [comment]
Might be worth adding pre-commit.ci as a plugin?

**Comment by krlmlr** [comment]
I'm not too familiar with it, how can that help here?

**Comment by Mause** [comment]
> I'm not too familiar with it, how can that help here?

Could be used to automatically fix formatting issues in pr's (that's the service I linked to) and the tool it's based on, is primarily a git hook for local use. I use both heavily and they're quite convenient

**Comment by krlmlr** [comment]
We'll need to work on automation.

From what I remember, pre-commit is a whole framework that would require substantial changes. Maybe worth discussing first?

**Comment by Mause** [comment]
> We'll need to work on automation.
> 
> From what I remember, pre-commit is a whole framework that would require substantial changes. Maybe worth discussing first?

Not sure what you mean by "whole framework"? It has a single config file that you commit into the repo

**Pull request closed without merging**
