### PR TITLE
Issue #8674: Interrupt Work Stealing

### PR DESCRIPTION
**Pull request by hawkfish**
Check the work stealing loop for aborts so it doesn't loop forever.

fixes duckdblabs/duckdb-internal#140

### CODE REVIEW

**Comment by carlopi** [comment]
Confirm that fixes the issue, and makes sense to me.

I took a look at the code, question is whether this should not use some sort of general locking mechanism to avoid threading issues.

Say 2 threads both call StealWork (that internally has a lock, so will serve only one at a time), then the one that gets out throws right away, and the other will go into yielding.

Something like:
```
while (true) {
      {
          lock_guard<mutex> steal_guard(built_lock);
          if ((!context.interrupted && tasks_remaining) == false)
              break;
           auto result = StealWork();   // now StealWork don't need the guard anymore
           if (result.second) {
                 return result; 
           }
      }
       //      If there is nothing to steal but there are unfinished partitions,
       //      yield until any pending builds are done.
      TaskScheduler::GetScheduler(context).YieldThread();
}
```
or something.

**Comment by hawkfish** [comment]
`tasks_remaining` is atomic, so it doesn't need a guard, and `interrupted is a single byte read, so it doesn't need one either.

**Review by carlopi — APPROVED** [review]

**Comment by carlopi** [comment]
> `tasks_remaining` is atomic, so it doesn't need a guard, and `interrupted` is a single byte read, so it doesn't need one either.

I am not sure that helps. Say two threads both passed the check on `!interrupted && tasks_remaining`. Then one gets a task and throws, and the other will fail to steal work. What happens then?

**Comment by hawkfish** [comment]
When it fails, it will yield and the next loop will find the interrupt.

**Review by samansmink — APPROVED** [review]
lookin good!

**Comment by hannes** [comment]
@hawkfish good to go from your side?

**Pull request merged**
