### PR TITLE
Fix #9455 - avoid calling filter pushdown on partial plan from within statistics propagation

### LINKED ISSUE #9455: Error: INTERNAL Error: Attempted to access index 7 within vector of size 7
### What happens?

duckdb 0.9.1 CLI client crashes with the following error when executing some queries:

Error: INTERNAL Error: Attempted to access index 7 within vector of size 7

### To Reproduce

Start duckdb CLI client from command line (no need to attach any db)

Paste the following DDL + insert statements to generate small reproducer db:

```sql
BEGIN TRANSACTION;
CREATE TABLE visit_occurrence(visit_occurrence_id BIGINT, person_id BIGINT, visit_concept_id BIGINT, visit_start_date DATE, visit_start_datetime TIMESTAMP, visit_end_date DATE, visit_end_datetime TIMESTAMP, visit_type_concept_id BIGINT, provider_id BIGINT, care_site_id BIGINT, visit_source_value VARCHAR, visit_source_concept_id BIGINT, admitted_from_concept_id BIGINT, admitted_from_source_value BIGINT, discharge_to_source_value BIGINT, discharge_to_concept_id BIGINT, preceding_visit_occurrence_id BIGINT, line_num INTEGER, fileid BIGINT);;
INSERT INTO visit_occurrence VALUES(1,1,9201,'2012-07-02','2012-07-02 00:00:00','2012-07-02','2012-07-02 00:00:00',32035,1,1,'Triage',0,0,0,0,0,0,1831,46);
INSERT INTO visit_occurrence VALUES(2,1,9201,'2012-12-26','2012-12-26 00:00:00','2012-12-26','2012-12-26 00:00:00',32035,1,1,'Triage',0,0,0,0,0,0,2380,46);
INSERT INTO visit_occurrence VALUES(3,1,581477,'2011-01-01','2011-01-01 00:00:00','2011-01-01','2011-01-01 00:00:00',32035,1,1,'Demographics',0,0,0,0,0,0,2550,46);
INSERT INTO visit_occurrence VALUES(4,4,9202,'2011-01-01','2011-01-01 00:00:00','2011-01-01','2011-01-01 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2551,46);
INSERT INTO visit_occurrence VALUES(5,4,9202,'2011-01-01','2011-01-01 00:00:00','2011-01-01','2011-01-01 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2552,46);
INSERT INTO visit_occurrence VALUES(6,4,9201,'2011-01-02','2011-01-02 00:00:00','2011-01-02','2011-01-02 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2553,46);
INSERT INTO visit_occurrence VALUES(7,4,9201,'2011-01-02','2011-01-02 00:00:00','2011-01-02','2011-01-02 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2554,46);
INSERT INTO visit_occurrence VALUES(8,8,581477,'2011-01-02','2011-01-02 00:00:00','2011-01-02','2011-01-02 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2555,46);
INSERT INTO visit_occurrence VALUES(9,8,581477,'2011-01-03','2011-01-03 00:00:00','2011-01-03','2011-01-03 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2556,46);
INSERT INTO visit_occurrence VALUES(10,9,32693,'2011-01-03','2011-01-03 00:00:00','2011-01-03','2011-01-03 00:00:00',32035,1,1,'Non-billable',0,0,0,0,0,0,2557,46);
INSERT INTO visit_occurrence VALUES(11,9,32693,'2010-01-02','2010-01-02 00:00:00','2010-01-02','2010-01-02 00:00:00',32035,1,1,'Substance Evaluation',0,0,0,0,0,0,54589,46);
CREATE TABLE procedure_occurrence(procedure_occurrence_id BIGINT, person_id BIGINT, procedure_concept_id BIGINT, procedure_date DATE, procedure_datetime TIMESTAMP, procedure_end_date DATE, procedure_end_datetime TIMESTAMP, procedure_type_concept_id BIGINT, modifier_concept_id VARCHAR, quantity VARCHAR, provider_id BIGINT, visit_occurrence_id BIGINT, visit_detail_id VARCHAR, procedure_source_value BIGINT, procedure_source_concept_id BIGINT, modifier_source_value VARCHAR, line_num BIGINT, fileid BIGINT);;
INSERT INTO procedure_occurrence VALUES(1,1,2314342,'2012-07-02','2012-07-02 10:20:00','2012-07-02','2012-07-02 10:37:00',45754686,NULL,NULL,282900027,1,NULL,99000,2795855,NULL,2790447,232);
INSERT INTO procedure_occurrence VALUES(2,4,2314342,'2011-01-01','2011-01-01 10:20:00','2011-01-01','2011-01-01 10:37:00',45754686,NULL,NULL,282900027,4,NULL,99000,2795841,NULL,2790447,232);
CREATE TABLE procedure_vocab(procedure_concept_id BIGINT, procedure_name VARCHAR, procedure_concept_type VARCHAR, parent_snomed_concept_id BIGINT, service_type VARCHAR, service_type_vocab VARCHAR);;
INSERT INTO procedure_vocab VALUES(2314342,'Handling and/or conveyance of specimen for transfer from the office to a laboratory','CPT4',4203132,'Administrative transfer procedure','SNOMED');
INSERT INTO procedure_vocab VALUES(2314342,'Handling and/or conveyance of specimen for transfer from the office to a laboratory','CPT4',4296818,'Specimen care','SNOMED');
INSERT INTO procedure_vocab VALUES(2314342,'Handling and/or conveyance of specimen for transfer from the office to a laboratory','CPT4',NULL,'Handling and/or conveyance of specimen for transfer from the office to a laboratory','CPT4');
COMMIT;
```

Then paste the following query, which should fail with an error
```sql
SELECT
    vo.person_id,
    vo.visit_start_date,
    vo.visit_end_date,
    pm.service_type
FROM
    visit_occurrence AS vo
    JOIN procedure_occurrence po USING(visit_occurrence_id, person_id)
    JOIN procedure_vocab pm ON po.procedure_concept_id = pm.procedure_concept_id
WHERE vo.person_id IN (1,2,3,4,5,6,7,8,9,10,12);
```

Expected: query works
Actual: results in an error:
Screenshot from 2023-10-24 11-26-50

### OS:

Linux, fedora 36

### DuckDB Version:

v0.9.1 401c8061c6

### DuckDB Client:

CLI

### Full Name:

Jan Hrček

### Affiliation:

Holmusk

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #9455

### CODE REVIEW

**Comment by jhrcek** [comment]
Is there any update on this?
We would like to update to 9.x but we're hitting https://github.com/duckdb/duckdb/issues/9455
It seems that test are failing because the fix is causing some slowdown
```
Old timing geometric mean: 0.4562274915986726, roughly 9% faster
New timing geometric mean: 0.5014604624233199
```

Is the slowdown a necessary price for correctness? Or is there a better fix to be found?

**Comment by Mytherin** [comment]
The current fix disables a specific optimization entirely which causes the slowdown. A better fix would be to rework the way the optimization is done so the issue isn't caused but that's a bit harder. I will revisit this in the future.

**Comment by Mytherin** [comment]
The bug has been resolved in a better way

**Comment by louisnow** [comment]
@Mytherin Which PR has the fix for this? I can't seem to find it linked to any of the parent issues

**Pull request closed without merging**
