### PR TITLE
[Python] Add missing options for `read_csv`

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes https://github.com/duckdblabs/duckdb-internal/issues/2455

Like the recent PR that added options for `read_json`, this is the `read_csv` variant.
This includes all the MultiFileReader options.

Full list (not including the MultiFileReader options):
- new_line (lineterminator)
- columns
- auto_type_candidates
- max_line_size
- ignore_errors 
- store_rejects
- rejects_table
- rejects_scan
- rejects_limit
- force_not_null
- buffer_size
- decimal_separator (decimal)
- allow_quoted_nulls

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - aside from the rather odd CI failure. Not sure what is going on there -  too many parameters in a function maybe?

```
2024-07-07T21:31:49.7887039Z       duckdb_python.cpp:706:40:   required from here
2024-07-07T21:31:49.7888540Z       /tmp/pip-build-env-lshxaj86/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/detail/../detail/common.h:687:8: fatal error: template instantiation depth exceeds maximum of 900 (use ‘-ftemplate-depth=’ to increase the maximum)
2024-07-07T21:31:49.7890054Z         687 | struct make_index_sequence_impl : make_index_sequence_impl<N - 1, N - 1, S...> {};
2024-07-07T21:31:49.7890596Z             |        ^~~~~~~~~~~~~~~~~~~~~~~~
2024-07-07T21:31:49.7890938Z       compilation terminated.
```

**Comment by Tishj** [comment]
> Thanks! LGTM - aside from the rather odd CI failure. Not sure what is going on there - too many parameters in a function maybe?
> 
> ```
> 2024-07-07T21:31:49.7887039Z       duckdb_python.cpp:706:40:   required from here
> 2024-07-07T21:31:49.7888540Z       /tmp/pip-build-env-lshxaj86/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/detail/../detail/common.h:687:8: fatal error: template instantiation depth exceeds maximum of 900 (use ‘-ftemplate-depth=’ to increase the maximum)
> 2024-07-07T21:31:49.7890054Z         687 | struct make_index_sequence_impl : make_index_sequence_impl<N - 1, N - 1, S...> {};
> 2024-07-07T21:31:49.7890596Z             |        ^~~~~~~~~~~~~~~~~~~~~~~~
> 2024-07-07T21:31:49.7890938Z       compilation terminated.
> ```

Yea I noticed that as well, I hoped it was a fluke, because I can't figure out what's happening here.
But the pybind code is heavily templated, so it is probably too many parameters, or at the very least too many parameters in the `py::arg` of the definition.

**Comment by Tishj** [comment]
> LGTM.
> 
> One small comment but feel free to ignore:
> 
> I do wonder if, for some options, we could use Python ENUMs.
> 
> e.g., for compressions, or newline delimiters.

That's a good suggestion, I think we can, the compression is kind of a no-op currently though, we just throw if it's not `utf8`
But for newlines and others it could definitely make sense

**Comment by Mytherin** [comment]
Does `pybind` perhaps have a way of constructing a Python method programmatically to avoid the templating limit from being reached?

**Comment by Tishj** [comment]
> Does `pybind` perhaps have a way of constructing a Python method programmatically to avoid the templating limit from being reached?

I think we're already using that:
```c++
	m.def(
	    "from_csv_auto",
	    [](const py::object &name, const Optional<py::object> &header = py::none(),
	       const Optional<py::object> &compression = py::none(), const Optional<py::object> &sep = py::none(),
	       const Optional<py::object> &delimiter = py::none(), const Optional<py::object> &dtype = py::none(),
	       const Optional<py::object> &na_values = py::none(), const Optional<py::object> &skiprows = py::none(),
	       const Optional<py::object> &quotechar = py::none(), const Optional<py::object> &escapechar = py::none(),
	       const Optional<py::object> &encoding = py::none(), const Optional<py::object> &parallel = py::none(),
	       const Optional<py::object> &date_format = py::none(),
	       const Optional<py::object> &timestamp_format = py::none(),
	       const Optional<py::object> &sample_size = py::none(), const Optional<py::object> &all_varchar = py::none(),
	       const Optional<py::object> &normalize_names = py::none(),
	       const Optional<py::object> &null_padding = py::none(), const Optional<py::object> &names = py::none(),
	       const Optional<py::object> &lineterminator = py::none(), const Optional<py::object> &columns = py::none(),
	       const Optional<py::object> &auto_type_candidates = py::none(),
	       const Optional<py::object> &max_line_size = py::none(),
	       const Optional<py::object> &ignore_errors = py::none(),
	       const Optional<py::object> &store_rejects = py::none(),
	       const Optional<py::object> &rejects_table = py::none(),
	       const Optional<py::object> &rejects_scan = py::none(),
	       const Optional<py::object> &rejects_limit = py::none(),
	       const Optional<py::object> &force_not_null = py::none(),
	       const Optional<py::object> &buffer_size = py::none(), const Optional<py::object> &decimal = py::none(),
	       const Optional<py::object> &allow_quoted_nulls = py::none(),
	       const Optional<py::object> &filename = py::none(),
	       const Optional<py::object> &hive_partitioning = py::none(),
	       const Optional<py::object> &union_by_name = py::none(), const Optional<py::object> &hive_types = py::none(),
	       const Optional<py::object> &hive_types_autocast = py::none(),
	       shared_ptr<DuckDBPyConnection> conn = nullptr) {
		    if (!conn) {
			    conn = DuckDBPyConnection::DefaultConnection();
		    }
		    return conn->ReadCSV(name, header, compression, sep, delimiter, dtype, na_values, skiprows, quotechar,
		                         escapechar, encoding, parallel, date_format, timestamp_format, sample_size,
		                         all_varchar, normalize_names, null_padding, names, lineterminator, columns,
		                         auto_type_candidates, max_line_size, ignore_errors, store_rejects, rejects_table,
		                         rejects_scan, rejects_limit, force_not_null, buffer_size, decimal, allow_quoted_nulls,
		                         filename, hive_partitioning, union_by_name, hive_types, hive_types_autocast);
	    },
	    "Create a relation object from the CSV file in 'name'", py::arg("path_or_buffer"), py::kw_only(),
	    py::arg("header") = py::none(), py::arg("compression") = py::none(), py::arg("sep") = py::none(),
	    py::arg("delimiter") = py::none(), py::arg("dtype") = py::none(), py::arg("na_values") = py::none(),
	    py::arg("skiprows") = py::none(), py::arg("quotechar") = py::none(), py::arg("escapechar") = py::none(),
	    py::arg("encoding") = py::none(), py::arg("parallel") = py::none(), py::arg("date_format") = py::none(),
	    py::arg("timestamp_format") = py::none(), py::arg("sample_size") = py::none(),
	    py::arg("all_varchar") = py::none(), py::arg("normalize_names") = py::none(),
	    py::arg("null_padding") = py::none(), py::arg("names") = py::none(), py::arg("lineterminator") = py::none(),
	    py::arg("columns") = py::none(), py::arg("auto_type_candidates") = py::none(),
	    py::arg("max_line_size") = py::none(), py::arg("ignore_errors") = py::none(),
	    py::arg("store_rejects") = py::none(), py::arg("rejects_table") = py::none(),
	    py::arg("rejects_scan") = py::none(), py::arg("rejects_limit") = py::none(),
	    py::arg("force_not_null") = py::none(), py::arg("buffer_size") = py::none(), py::arg("decimal") = py::none(),
	    py::arg("allow_quoted_nulls") = py::none(), py::arg("filename") = py::none(),
	    py::arg("hive_partitioning") = py::none(), py::arg("union_by_name") = py::none(),
	    py::arg("hive_types") = py::none(), py::arg("hive_types_autocast") = py::none(),
	    py::arg("connection") = py::none());
```

There is `py::kwargs` as well, where we don't get unrolled arguments but instead we get a dictionary we can do lookups into.
That kind of messes with the code generation we do for this

**Comment by Mytherin** [comment]
> I think we're already using that:

This uses varargs that `pybind` then expands using templating. I think the problem that's being run into here is that there are too many parameters causing this templating magic to blow up.  What I meant was more something like (not sure if this exists):

```sql
PyBindMethod method;
method.add_parameter(py::arg("header"), py::none());
method.add_parameter(py::arg("delimiter"), py::none());
....
```

**Comment by Tishj** [comment]
> > I think we're already using that:
> 
> This uses varargs that `pybind` then expands using templating. I think the problem that's being run into here is that there are too many parameters causing this templating magic to blow up. What I meant was more something like (not sure if this exists):
> 
> ```sql
> PyBindMethod method;
> method.add_parameter(py::arg("header"), py::none());
> method.add_parameter(py::arg("delimiter"), py::none());
> ....
> ```

Maybe that's possible, the body of this just looks like:
```c++
    template <typename Func, typename... Extra>
    module_ &def(const char *name_, Func &&f, const Extra &...extra) {
        cpp_function func(std::forward<Func>(f),
                          name(name_),
                          scope(*this),
                          sibling(getattr(*this, name_, none())),
                          extra...);
        // NB: allow overwriting here because cpp_function sets up a chain with the intention of
        // overwriting (and has already checked internally that it isn't overwriting
        // non-functions).
        add_object(name_, func, true /* overwrite */);
        return *this;
    }
```

So it's not being expanded in here

**Comment by Mytherin** [comment]
LGTM - perhaps @pdet wants to have a final look?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
