### PR TITLE
[JDBC] Improve type-safe handling of timestamp types

### PR DESCRIPTION
**Pull request by felipecrv**
Having only `java.sql.Timestamp` and `java.time.LocalDateTime` consistently supported in the appender and result-set classes forces all manipulation of typed timestamp values to go through unnecessary timezone conversions between UTC and system default — `java.sql.Timestamp` extends `java.util.Date` which implicitly assumes system timezone.

Many have suggested the use of raw `long` for dealing with timestamps in the JDBC driver, but that can be very error-prone.  Modern Java should avoid time-related classes in `java.util` and stick to using only `java.time.*`.

This PR adds support for appending/retriving `DuckDBTimestamp` and improves the existing `java.time.LocalDateTime` suppport in the `DuckDBResultSet`.

## Tests

`test_appender_date_and_time` was extended to exercise the use of all the Java types against all the internal DuckDB timestamps.

## Future Ideas

The best type for raw timestamp manipulation since Java 8 is `java.time.Instant` (JSR-310 [1]) as all conversions between instants, durations, and zoned times are checked by the type system and you never have to deal with raw integers unless you're passing them over I/O or IPC boundaries.

`java.time.Instant` and other `java.time.*` classes like `java.time.LocalDateTime` are represented using 64+32 bits -- `{seconds: int64, nanos_of_second: int32}` -- so it's not yet possible to losslessly pass them via `DuckDBNative.duckdb_jdbc_appender_append_timestamp` as that (1) requires truncating to micros and (2) has to fit in 64 bits. At the moment of the call to `DuckDBNative.duckdb_jdbc_appender_append_timestamp` the type of the vector isn't known, so even if a variation that takes nanoseconds was available, the caller would be forced to perform a multiplication with a risk of overflow and fail unnecessarily when the vector type requires truncation to some type less precise than nanoseconds.

This limitation is also why `java.data.LocalDataTime` instances pushed into the database lose their nanoseconds part even when the DuckDB table column is a `TIMESTAMP_NS`.

[1] https://jcp.org/aboutJava/communityprocess/pfd/jsr310/JSR-310-guide.html

### CODE REVIEW

**Comment by felipecrv** [comment]
@Mause please take a look.

**Comment by Mytherin** [comment]
@Mause could you still do a pass over this PR when you have time?

**Comment by felipecrv** [comment]
@Mause should I rebase?

**Comment by Mause** [comment]
The java interface has actually been moved to https://GitHub.com/DuckDB/DuckDB-java, but yes

**Comment by Mytherin** [comment]
The JDBC interface is no longer in this repo - feel free to open a PR in https://github.com/duckdb/duckdb-java if you wish to continue developing this

**Pull request closed without merging**
