### PR TITLE
Bump excel extension

### PR DESCRIPTION
**Pull request by Maxxen**
Now includes the new `xlsx` read/write functionality and `.xlsx` replacement scan!

### CODE REVIEW

**Review by carlopi — CHANGES_REQUESTED** [review]
Problem in failed test is that copy functions are not autoloadable, to unblock this solution is adding a line:
```
require no_extension_autoloading "FIXME: make copy to functions autoloadable"
```
in https://github.com/duckdb/duckdb_excel/blob/main/test/sql/excel/xlsx/bignum.test.

**Comment by Maxxen** [comment]
@carlopi I don't get it though, the unattested has `require excel` which should load it no?

**Comment by carlopi** [comment]
I think there are 3 kind of tests:
* extensions statically linked in
* extensions dynamically loaded on `require NAME`
* extensions autoloaded on usage (`require NAME` is used only to know a given test is relevant)

I think extension CI mostly test code-path 1 (that is, extension bundled with duckdb), and duckdb CI tests a combination of above. Problem I think is from last case, given autoloading do not kick in on COPY TO.

I think easy solution is just skip testing the autoloading here, long term we might want to autoload on COPY TO.

**Comment by carlopi** [comment]
I haven't checked, but if this is the case, I think it should be testable like:

Add a `DONT_LINK` to excel in `.github/config/out-of-tree-extension-config.cmake`
```
EXTENSION_STATIC_BUILD=1 ENABLE_EXTENSION_AUTOLOADING=1 ENABLE_EXTENSION_AUTOINSTALL=1 CORE_EXTENSIONS=excel GEN=ninja make
```
then:
```
LOCAL_EXTENSION_REPO='build/release/repository' build/release/test/unittest path/to/name.test
```
This says: build excel, and build duckdb with autoinstall + autoloading enabled, then test using LOCAL_EXTENSION_REPO instead of the remote repository.

**Review by carlopi — APPROVED** [review]
Nice!

(2 CI failures are networking / random & unconnected)

**Comment by Mytherin** [comment]
Nice, thanks!

**Comment by ericemc3** [comment]
Very happy to see an effective `read_xlsx()` coming !
 
Only one little option missing, if i dare : `skip`, (as with read_csv), since many xlsx sheets display some metadata at the top.
The `range `option is not the more convenient for that use case.

And also `normalize_names`

**Pull request merged**
