### PR TITLE
[Python/Dev] Add implicit conversion from None -> duckdb.default_connection

### PR DESCRIPTION
**Pull request by Tishj**
Previously our `connection_wrapper.cpp` code looked like:
```c++
Optional<py::tuple> PyConnectionWrapper::FetchOne(shared_ptr<DuckDBPyConnection> conn) {
	if (!conn) {
		conn = DuckDBPyConnection::DefaultConnection();
	}
	return conn->FetchOne();
}
```
After this PR:
```c++
Optional<py::tuple> PyConnectionWrapper::FetchOne(shared_ptr<DuckDBPyConnection> conn) {
	return conn->FetchOne();
}
```

This reduces the amount of boilerplate in the python client drastically :D

### CODE REVIEW

**Comment by Tishj** [comment]
I think we can also use this to check if the connection has been closed already, which would remove even more boilerplate in `pyrelation.cpp`

**Comment by Mause** [comment]
Ooo very clever, nice!

**Comment by carlopi** [comment]
There seems to be other cases with the same pattern, like in `pyrelation.cpp`, that probably should be also removed as well for clarity, and a word of caution that this means that behaviour of broken code will change (from error being throw to getting an additional connection).

**Comment by Tishj** [comment]
> There seems to be other cases with the same pattern, like in `pyrelation.cpp`, that probably should be also removed as well for clarity, and a word of caution that this means that behaviour of broken code will change (from error being throw at runtime to getting an additional connection).

It's not a broken connection, the purpose of these wrappers is to be able to use the same methods directly on `duckdb` that you can also use on a connection. These methods have an optional connection, since it's optional we use the default connection if it's not provided.
This just removes the duplicates of that logic.

As for the pyrelation, I'm currently cleaning that, moving these functions to connection_wrapper.
The other thing I want to do is related to closed connections, whenever we receive a connection, we should check if the it's still open - which isn't happening everywhere yet.

**Pull request merged**
