### PR TITLE
Initial set of commits to add support for zOS (an IBM mainframe operating system)

### PR DESCRIPTION
**Pull request by v1gnesh**
Hello!

These are mostly pre-processor directives added to support building on zOS.
I'm working on an incredibly slow zOS machine, so progressing slowly but surely.
However, I'd like to get these merged as they won't get in the way of anything else.

Thanks for this excellent product. 
It's ducking hilarious seeing arbitrary tasks go from 'x' seconds to 0.x seconds, like in the 0.8 version announcement.
I heap praises on DuckDB at work whenever I get a chance.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! I'm fine with merging in these changes as they don't conflict with anything else - but as we don't have any of these machines (neither ourselves nor in the CI) there's a good chance this will be broken again in the future. I also noticed you are making several changes in third party libraries we have inlined ([moodycamel's concurrentqueue](https://github.com/cameron314/concurrentqueue), [httplib](https://github.com/yhirose/cpp-httplib), [fast_float](https://github.com/fastfloat/fast_float)). You may want to upstream these changes - otherwise once we update to a newer version the fixes will be lost.

**Comment by v1gnesh** [comment]
@Mytherin, thanks again for accepting these changes.

> but as we don't have any of these machines (neither ourselves nor in the CI) there's a good chance this will be broken again in the future.

Yes, I'll try to keep it in a working state. Do tag me in case anything gets broken because of this.
If it's something urgent, don't even hesitate to yank it out :)

Upstream PRs for reference. If you have time, could you see if these look ok?
https://github.com/yhirose/cpp-httplib/pull/1581
https://github.com/cameron314/concurrentqueue/pull/346
https://github.com/fastfloat/fast_float/pull/207

**Comment by v1gnesh** [comment]
Hi @Mytherin, could you pull this in please?

**Comment by v1gnesh** [comment]
Thank you very much, apologies if I was rushing it.
I'm pretty new to contributing to the open source world 😅

**Pull request merged**
