### PR TITLE
Shell: Provide a summary of numbers if we are rendering only a single row

### PR DESCRIPTION
**Pull request by Mytherin**
Many result sets contain only a single row (or single value), for example, when running `SELECT COUNT(*) FROM tbl` or similar summaries. In those cases, we often receive a single (often big) number. This PR adds support for a human readable rendering of these numbers, e.g.:

Screenshot 2024-11-29 at 16 00 02
Screenshot 2024-11-29 at 16 00 32

This option can be disabled using `.large_number_rendering off`:

```sql
D . large_number_rendering off
D select sum(l_extendedprice), sum(l_discount) from lineitem;
┌──────────────────────┬─────────────────┐
│ sum(l_extendedprice) │ sum(l_discount) │
│    decimal(38,2)     │  decimal(38,2)  │
├──────────────────────┼─────────────────┤
│     2293813156773.36 │      2999373.24 │
└──────────────────────┴─────────────────┘

```

In addition, this can be applied to all numeric values using `.large_number_rendering all`

Screenshot 2024-11-30 at 13 35 41

### CODE REVIEW

**Comment by Maxxen** [comment]
Love it!

**Comment by carlopi** [comment]
I love both of you, but ... I don't get it, I don't like (at all) the fact that this is not composable / special cased.

Apart from taste, I think one connected feedback is that it would be cool to have a way to persist this setting across sessions directly FROM the cli. Either a modifier on a given command, say `.persist '.timer on'`, or like: `.edit_rc` that goes into editing `~/.duckdbrc` (or whatever file we load by default).

Then it becomes simpler to add stuff, while making it easy for people to remember setting.

**Comment by Mytherin** [comment]
It's a contextual rendering that provides an easier way to see what a result means. The point of `duckbox` is to provide human-readable snapshots of result sets. That's also why we e.g. truncate rows/columns so that they fit the terminal window. 

I guess we could optionally enable it for multiple rows (which is what I assume you mean with "it is not composable"?) - but that gets very busy very quickly since it doubles the size of the result set. I think the single-row is a good compromise, since single-row queries are very common (especially for `COUNT(*)` which is the main purpose of this rendering).

**Comment by Mytherin** [comment]
Maybe a good compromise is to leave it out by default when `stdout` is not a terminal?

**Comment by carlopi** [comment]
Thanks for the deeper explanation! I sounded more certain than I am, and it's right that duckbox is not used by tools (that can do `-md`) / what not that is easier to parse, I guess trust your (and Max) judgment, we can always have it in first and experiment with it, we are not releasing tomorrow.

**Comment by Mytherin** [comment]
Thinking about this a bit more, maybe it would be nice to offer this at three levels:

* `off` - all numbers are printed using regular formatting
* `footer` - what this PR implements, for single row results large numbers are augmented with the readable format
* `all` - replace all large numbers with readable format

**Pull request merged**
