### PR TITLE
[PythonDev] Fix failing `test_statement_bind.py` test

### PR DESCRIPTION
**Pull request by Tishj**
Test was made for `adbc_driver_manager==0.4.0`, the version was not locked and `0.6.0` seems to break some expected error messages.

I've updated the test for 0.6.0 and locked the version of adbc driver manager to 0.6.0 so we don't get randomly failing tests in the future

### CODE REVIEW

**Review by pdet — COMMENTED** [review]
Thanks for the update! Looks great!
I think we generally do not lock versions of these libraries on purpose. So they don't silently break without us knowing.

**Comment by Tishj** [comment]
> Thanks for the update! Looks great! I think we generally do not lock versions of these libraries on purpose. So they don't silently break without us knowing.

Yea I'm also not sure if locking is a good idea here

**Review by Mause — APPROVED** [review]

**Comment by Mause** [comment]
> > Thanks for the update! Looks great! I think we generally do not lock versions of these libraries on purpose. So they don't silently break without us knowing.
> 
> Yea I'm also not sure if locking is a good idea here

Could swap it to a lock to the minor version? Less chance of random breakage

Dependabot is also an option here

**Comment by pdet** [comment]
> > > Thanks for the update! Looks great! I think we generally do not lock versions of these libraries on purpose. So they don't silently break without us knowing.
> > 
> > 
> > Yea I'm also not sure if locking is a good idea here
> 
> Could swap it to a lock to the minor version? Less chance of random breakage
> 
> Dependabot is also an option here

I fully agree with Mause, lets lock with a minor version and add dependabot in a different PR

**Pull request merged**
