### PR TITLE
Out-of-tree Extension Builds

### PR DESCRIPTION
**Pull request by hannes**
This PR adds the capabilities to build extensions that are not part of the main DuckDB source tree to the CMake configuration as well as a centralised unified build through the main CI

### CODE REVIEW

**Comment by hannes** [comment]
This will also enable usage of the SQLite and Postgres scanners though the `INSTALL` mechanism

**Comment by hannes** [comment]
This fails because of warnings in the Postgres scanner, will fix

**Review by Mytherin — APPROVED** [review]
LGTM

**Review by samansmink — APPROVED** [review]
lgtm!

**Comment by Alex-Monahan** [comment]
Do the Postgres and SQLite extensions support Windows now? I can build us some guides!

**Comment by hannes** [comment]
Windows is a separate PR, working on it

**Pull request merged**
