### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by zhouliqi**
Maybe it is `write` rather than `read` in comment.

### CODE REVIEW

**Comment by Tishj** [comment]
Thanks, I suppose you're right
If the buffer that's read from would be too small that would probably just cause a segfault instead

Could you change it to `written` instead of `write` please?

**Comment by zhouliqi** [comment]
>

**Comment by zhouliqi** [comment]
> Thanks, I suppose you're right If the buffer that's read from would be too small that would probably just cause a segfault instead
> 
> Could you change it to `written` instead of `write` please?

No problem

**Comment by Mytherin** [comment]
Thanks

**Pull request merged**
