### PR TITLE
Possibly fixing R strict barrier issue

### PR DESCRIPTION
**Pull request by hannes**
CC @krlmlr can you check if this solves your crashing issue?

### CODE REVIEW

**Comment by krlmlr** [comment]
Reviewing now. Does this close #6508 when successful?

**Comment by krlmlr** [comment]
I can no longer reproduce the short example in #6508. I'd like to rerun the full test suite to be sure, but this PR looks good.

**Review by krlmlr — APPROVED** [review]

**Comment by krlmlr** [comment]
The "experimental string handling works" test still freezes with the strict barrier. I'll follow up with a reprex.

**Comment by krlmlr** [comment]
Failing with:

```r
library(duckdb)

con <- dbConnect(duckdb())
on.exit(dbDisconnect(con, shutdown = TRUE))
df <- data.frame(a=c(NA, as.character(1:30)))

duckdb_register(con, "df", df, experimental=TRUE)

dbGetQuery(con, "SELECT a FROM df")
#> Fatal error: Wrong thread calling 'Rf_protect'
#> Fatal error: Wrong thread calling 'RunFinalizers'
#> ... (repeated many times)
```

Try values larger than 30 if needed.

All other tests seem good, rerunning to double-check.

**Comment by krlmlr** [comment]
All other tests ran successfully.

**Comment by hannes** [comment]
Since this is not about experimental but the "classic" way of handling strings, it should in any case not create any new problems.

**Pull request merged**
