### PR TITLE
Make CSV error line numbers 1-indexed

### PR DESCRIPTION
**Pull request by Maxxen**
*title*

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by Maxxen** [comment]
@Mytherin Any idea of what went wrong in the windows extension CI? I am unable to reproduce locally.

**Comment by Mytherin** [comment]
Hm, looks like there might spuriously be an issue remaining with the parallel CSV reader not correctly detecting that there are quoted newlines and the file is not supported for reading with the parallel reader. Perhaps an off-by-one in the detection code or so?

This is somewhat problematic because the file is read incorrectly - there are supposed to be `10100 rows`.

```
Query unexpectedly failed! (test/sql/copy/csv/parallel/test_parallel_error_messages.test:72)!
================================================================================
SELECT * FROM read_csv('data/csv/error/quotednewlines.csv', parallel=true, sep=',', buffer_size=200, columns={'h1': int, 'h2': varchar}, header=True);
================================================================================
Invalid Error: Deserialized V2 statement differs from original result!
Original Result:
Invalid Input Error: CSV File not supported for multithreading. This can be a problematic line in your CSV File or that this CSV can't be read in Parallel. Please, inspect if the line 10012 is correct. If so, please run single-threaded CSV Reading by setting parallel=false in the read_csv call.
Deserialized V2:
h1    h2   
INTEGER    VARCHAR   
[ Rows: 10196]
```

Of course this example is super contrived (tiny buffer size, lines containing quoted newlines that themselves contain valid CSV file lines) so it is extremely unlikely that anyone will encounter this on a real file - but still a good idea for @pdet to look into.

**Comment by carlopi** [comment]
I ran in a potentially related issue locally, where I have regularly 2 CSV tests failing (both release and debug):
```
carlo@ScroogeMcDuck duckdb2 % ./build/release/test/unittest 
[2081/2386] (87%): test/sql/copy/csv/parallel/csv_parallel_new_line.test        ================================================================================
Query unexpectedly succeeded! (test/sql/copy/csv/parallel/csv_parallel_new_line.test:102)!
================================================================================
select * from read_csv('test/sql/copy/csv/data/test/multi_column_string.csv',  COLUMNS=STRUCT_PACK(a := 'INTEGER', b := 'INTEGER', c := 'INTEGER', d := 'VARCHAR'), auto_detect='false', delim = '|', new_line = '\r\n');
================================================================================

[2142/2386] (89%): test/sql/copy/csv/null_padding_big.test                      ================================================================================
Query failed, but error message did not match expected error message: CSV File not supported for multithreading (test/sql/copy/csv/null_padding_big.test:47)!
================================================================================
SELECT COUNT(*) FROM read_csv_auto('data/csv/nullpadding_big_mixed.csv', parallel=True, buffer_size=55);
Actual result:
================================================================================
Invalid Input Error: Error in file "data/csv/nullpadding_big_mixed.csv" on line 2445: expected 3 values per row, but got 2.
```
I have probably a slightly different / unsupported CMake configuration, since I am the only one seeing this (even git config potentially), but if it seems related / interesting (= simpler to reproduce) I can try to make it reproducible or dig a bit further.

**Comment by pdet** [comment]
> Hm, looks like there might spuriously be an issue remaining with the parallel CSV reader not correctly detecting that there are quoted newlines and the file is not supported for reading with the parallel reader. Perhaps an off-by-one in the detection code or so?
> 
> This is somewhat problematic because the file is read incorrectly - there are supposed to be `10100 rows`.
> 
> ```
> Query unexpectedly failed! (test/sql/copy/csv/parallel/test_parallel_error_messages.test:72)!
> ================================================================================
> SELECT * FROM read_csv('data/csv/error/quotednewlines.csv', parallel=true, sep=',', buffer_size=200, columns={'h1': int, 'h2': varchar}, header=True);
> ================================================================================
> Invalid Error: Deserialized V2 statement differs from original result!
> Original Result:
> Invalid Input Error: CSV File not supported for multithreading. This can be a problematic line in your CSV File or that this CSV can't be read in Parallel. Please, inspect if the line 10012 is correct. If so, please run single-threaded CSV Reading by setting parallel=false in the read_csv call.
> Deserialized V2:
> h1    h2   
> INTEGER    VARCHAR   
> [ Rows: 10196]
> ```
> 
> Of course this example is super contrived (tiny buffer size, lines containing quoted newlines that themselves contain valid CSV file lines) so it is extremely unlikely that anyone will encounter this on a real file - but still a good idea for @pdet to look into.

I'll try to get it during this week in a different PR.

**Pull request merged**
