### PR TITLE
[Fix] Silent constraint violation error when destroying the appender in the C API

### PR DESCRIPTION
**Pull request by taniabogatsch**
Before this PR, we advised users against using `duckdb_appender_flush` and `duckdb_appender_close` instead of `duckdb_appender_destroy`. However, we did not return `DuckDBError`, if `duckdb_appender_destroy` failed to close the appender. Furthermore, getting insights into any error when appending the internal data is impossible with `duckdb_appender_destroy`, as it also destroys the wrapper to access that error.

**Changes and fixes in this PR**
- Encourage users to use `duckdb_appender_flush` or `duckdb_appender_close` before `duckdb_appender_destroy` to retrieve a possible `DuckDBError`.
- Return `DuckDBError` if `duckdb_appender_close` fails during `duckdb_appender_destroy.` This ensures that any error does not stay silent.
- Updating an existing test and adding a new test to ensure that constraint violations don't go unnoticed.

### CODE REVIEW

**Comment by Giorgi** [comment]
Can we also get a way to discard the data that is the causing error? I [suggested discarding data](https://github.com/duckdb/duckdb/discussions/5743) when `duckdb_appender_end_row` but since I moved my implementation to `duckdb_append_data_chunk` for better performance and composite type support,  I guess my original suggestion doesn't cover this scenario.

**Comment by taniabogatsch** [comment]
Replying to @Giorgi.

The appender serves as a buffer. It buffers all to-be-appended data, either via `append_data_chunk` or the less recommended older `append_row` calls.  As the appender only buffers the data, it is not possible to detect a constraint violation with existing table data before flushing the data to the table (`flush`, `close`, or `destroy` all flush). The appender is more efficient than repeated `INSERT INTO` calls exactly because it attempts to append an entire such buffer.

> Can we also get a way to discard the data that is the causing error?

Discarding the data happens when destroying the appender with `duckdb_appender_destroy`. If you have a reproduction causing a leak or data that is otherwise not being discarded/destroyed, then that is a separate issue that we should fix. Or maybe I am misunderstanding what you mean by discarding the data?

> When duckdb_append_data_chunk returns an error, it would be great if we could retrieve which rows/columns cause the error and discard the chunk without losing the whole appender data.

We should address this in a per-issue basis. I.e., if you have a reproduction in C with an unclear or unexpected error message, then we can see how to improve that error.

**Comment by taniabogatsch** [comment]
We can leave this PR as intended to solve the silent error scenario. Since we already encourage users to call `close` or `flush` before destroying the appender to obtain a more insightful error, we can improve its usability and error messages in follow-up PRs.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
