### PR TITLE
Adding std:: to every move

### PR DESCRIPTION
**Pull request by hannes**

### CODE REVIEW

**Comment by Tishj** [comment]
I was just thinking, is it maybe possible to explicitly create a macro called `move` that expands to `std::move` ?
Maybe that's considered dirty, but that allows us to not have to alter all of the existing code, and also change a very ingrained coding pattern

**Comment by Mytherin** [comment]
> I was just thinking, is it maybe possible to explicitly create a macro called `move` that expands to `std::move` ? Maybe that's considered dirty, but that allows us to not have to alter all of the existing code, and also change a very ingrained coding pattern
> 
> (if it even works) actually nvm, that won't work because there are places that use std::move explicitly in the codebase, and that would now be mangled even worse, it breaks std:: internals 😂

We have tried that one as well and unfortunately it is not possible indeed. We have also tried defining our own `move` in the duckdb namespace - which also does not work because it leads to ambiguity. I think this is the only solution sadly.

**Comment by hannes** [comment]
Adding a new Makefile flag DEBUG_MOVE to the main build and DUCKDB_DEBUG_MOVE to the R package build to enable the complaining.

**Review by Mytherin — APPROVED** [review]
Good idea - LGTM

**Pull request merged**
