### PR TITLE
[Export] Write `macro` before other catalog items that might depend on it

### LINKED ISSUE #6120: export database - create macro after view
### What happens?

export database generate the ddl of every macros after the views.
if a view use the macro the import command will not work.

Suggestion: order the ddl generation of macro before the view 

### To Reproduce

EXPORT DATABASE 'target_directory' (FORMAT PARQUET, COMPRESSION ZSTD);
IMPORT DATABASE 'target_directory';

### OS:

windows

### DuckDB Version:

6.1

### DuckDB Client:

dbeaver (JDBC)

### Full Name:

alessio

### Affiliation:

myself

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6120

Title says it all really

Side note, this PR contains #6117 - needed it to build debug 😅

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Unfortunately I'm not sure if it will be this simple - because a macro might also depend on a view. Could we add a test where we have two macros (`m1` and `m2`) and a view (`v1`) - where `v1` depends on `m1`, while `m2` depends on `v1`. e.g. something like this:

```sql
CREATE MACRO m1(a) AS a+42;
CREATE VIEW v1 AS SELECT m1(42);
CREATE MACRO m2(a) AS (SELECT * FROM v1);
```

**Comment by Tishj** [comment]
Hmm I thought of this, but I figured macros are only bound when used, so this should still work?
I'll add a test for it 👍

**Comment by Tishj** [comment]
We're probably going to have to try binding things with a limited catalog, or keep track of dependencies between functions/macros -> views/tables, so we can write them in the right order.

Or just in general add creation metadata to catalog items, so we can use that to order the entries for export

**Comment by Tishj** [comment]
Maybe I could use the DependencyManager of the DuckCatalog to figure out the order of creation we need to not break things
Could be a virtual method on Catalog, returning a bool to indicate if we could get an explicit creation order from the Catalog (since only DuckCatalog has a DependencyManager) and then fall back to the current order if we couldn't?

**Comment by Mytherin** [comment]
Closing this for now

**Pull request closed without merging**
