### PR TITLE
Issue #1367: Window pipeline

### PR DESCRIPTION
**Pull request by hawkfish**
Convert `PhysicalWindow` to a assume single sort and replace the local parallelisation with expansions to `Sink` and `GetChunkInternal`. The plan compiler for `LogicalWindow` now emits multiple `PhysicalWindow` nodes and a `PhysicalProjection ` to restore the output column order.

Assuming I did this correctly, this should supersede the previous pull request. If not...

### CODE REVIEW

**Comment by hawkfish** [comment]
I don't believe the failure is in the new windowing code because the crash occurs before the `PhysicalWindow` operator is invoked.

**Comment by Mytherin** [comment]
> I don't believe the failure is in the new windowing code because the crash occurs before the PhysicalWindow operator is invoked.

Indeed, rerunning the tests seems to have fixed it.

**Comment by Mytherin** [comment]
So in this PR you create multiple window nodes that are stacked on top of each other, one for each unique OVER clause, correct?

In principle this should work, and I think this is elegant. One note, however, is that in order for the parallelism to have any effect you will need to turn the window operator into a parallel source. Right now the window is only a parallel sink. This means that any pipeline involving the window operator as a source will run single threaded (such as the WINDOW -> WINDOW pipelines you are now creating).

Parallel source registration happens at `pipeline.cpp:139`, you can look at how this is done for the table scans as an example.

**Comment by hawkfish** [comment]
I had a look at this and tried to make a quick change, but it didn't go well. It looks like `PhysicalWindow` is going to need something like the `TableFunction` API to make this work? Is there any documentation on the `Pipeline` architecture?

**Comment by hawkfish** [comment]
Also, it looks to me like there is a race condition in `PhysicalTableScan::GetChunkInternal` because the initialisation branch is not thread-safe. `state.operator_data` can be set multiple times before `state.initialized` guards that block of code?

**Comment by Mytherin** [comment]
> I had a look at this and tried to make a quick change, but it didn't go well. It looks like PhysicalWindow is going to need something like the TableFunction API to make this work? Is there any documentation on the Pipeline architecture?

Regrettably there is not much documentation for that yet. @lnkuiper just implemented this behavior for the ORDER BY operator in PR #1580, you can have a look there.

> Also, it looks to me like there is a race condition in PhysicalTableScan::GetChunkInternal because the initialisation branch is not thread-safe. state.operator_data can be set multiple times before state.initialized guards that block of code?

`PhysicalOperatorState` is always thread-local, the state is initialized once per thread. The only state that is shared between threads is the explicitly marked global state (as is used in the sink interface).

**Comment by hawkfish** [comment]
Ah thanks for the example. I thought I had convinced myself that `PhysicalOperatorState` was shared, but maybe that was the sink state. I also wasn't clear on whether chunks got pulled while the operator was still in sink mode.

**Comment by Mytherin** [comment]
GetChunk should only be called after the operator is finalized (i.e. after Finish is called).

**Comment by hawkfish** [comment]
Hmm SQLancer is failing locally but not here? The query doesn't look like it has windowing in it either.

**Comment by Mytherin** [comment]
Depending on how you run it SQLancer might run a different set of queries (e.g. if the seed is not fixed or you are using a different version). It's entirely possible there is a recent SQLancer failure that we haven't caught that is unrelated to your PR.

**Comment by hawkfish** [comment]
I did find a bug in the new order code where it was making buffer that was too small. I don't think it had been tested with multiple input threads that can all produce chunks that a re not full?

**Comment by hawkfish** [comment]
Are there any other concerns?

**Comment by Mytherin** [comment]
Looks good from my side. Thanks!

**Pull request merged**
