### PR TITLE
[Python] Add `read_excel` method

### PR DESCRIPTION
**Pull request by Tishj**
This PR adds `read_excel`

It just delegates the work to Pandas, then creates a Relation from the resulting dataframe

### CODE REVIEW

**Comment by Tishj** [comment]
@Mause Hey Elliana, can you please help me figure out what I'm doing wrong here?
I can't seem to skip the read_excel tests

I have added the dependencies to the requirements-dev.txt + cibw.toml and also added `importorskip` for pandas >= 1.5.3 to the test file (the minimum version `read_excel` was added at)

**Comment by Mause** [comment]
> @Mause Hey Elliana, can you please help me figure out what I'm doing wrong here?
> I can't seem to skip the read_excel tests
> 
> I have added the dependencies to the requirements-dev.txt + cibw.toml and also added `importorskip` for pandas >= 1.5.3 to the test file (the minimum version `read_excel` was added at)

Don't you want to add an importorskip on the xlrd dependency for this?

**Review by Mause — CHANGES_REQUESTED** [review]

**Comment by Tishj** [comment]
> > @Mause Hey Elliana, can you please help me figure out what I'm doing wrong here?
> > I can't seem to skip the read_excel tests
> > I have added the dependencies to the requirements-dev.txt + cibw.toml and also added `importorskip` for pandas >= 1.5.3 to the test file (the minimum version `read_excel` was added at)
> 
> Don't you want to add an importorskip on the xlrd dependency for this?

That is a good idea, I figured since it's installed as an "extra" we don't want to have an explicit dependency on it, and instead just let pandas take care of depending on the right xls parsing packing

**Comment by bjornasm** [comment]
How are the status here, and is there something that can be contributed by others to get this feature in?

**Pull request closed without merging**
