### PR TITLE
Support for SQL `interval`

### PR DESCRIPTION
**Pull request by mdashti**
Before this PR, there was no syntactic support for SQL `interval` (e.g., `SELECT COUNT(*) FROM lineitem where l_shipdate <= date '1998-12-01' - interval '77' day`).

This PR aims to add this construct, which is necessary for fully supporting the TPC-H queries generated via [`dbgen`](https://github.com/dragansah/tpch-dbgen).

The current state of this PR adds `INTERVAL` data type and it works all the way down to the logical plan. However, I might need some help with applying optimizations on it (e.g., constant folding) and execution of the queries that involve an interval.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Thanks, could you please add test cases for this as well?

**Comment by mdashti** [comment]
Sure, I will. I first wanted to ask for your opinion if it's on the right track, and whether you've already another branch that did the same. If not, I will continue with adding test cases.

BTW, I also get some build failures on [`travis-ci`](https://travis-ci.com/RelationalAI-oss/duckdb/builds/134798409) for Windows. Can you help with fixing the build issues?

**Comment by Mytherin** [comment]
Apologies, it has been some time since this PR has been opened. I just had another chance to look at it. It looks good, however, some notes:

* It looks like you are pulling in internal Postgres parser structures in ` src/common/operator/cast_operators.cpp`. We want to avoid doing this anywhere in our code base besides in the transformer to avoid having the Postgres defines and such leak everywhere. Instead, I would recommend creating the equivalent DuckDB structures (e.g. an interval enum that has DAY/MONTH/YEAR) and performing the transformation inside the transformer class.
* I would prefer not requiring a target SQLType in the Cast::Operator, as only the Interval needs it. Instead, wouldn't it be possible to run a different loop to do the cast to and from interval that takes the desired scale as input?
* It looks like right now you are only supporting date intervals, what about time intervals?
* As Hannes mentioned, please add tests!

Thanks for the contribution, again apologies for only commenting now. It has been a busy few weeks.

**Comment by Mytherin** [comment]
@mdashti
Since it's been some time since this PR, I think merging it will be very difficult as many changes have occurred at this point. I suggest closing the PR, and then maybe somebody else can pick up implementation of the interval type. Any objections?

**Pull request closed without merging**
