### PR TITLE
[Arrow] Fix segfault in appending list data

### PR DESCRIPTION
**Pull request by Tishj**
I came across this bug while investigating some memory usage issues with record batches

```python
import duckdb
import pyarrow as pa

conn = duckdb.connect()

conn.execute("""
    create or replace table tbl as select * from (select {'a': [5,4,3,2,1]}), range(10000000)
""")

query = "SELECT * FROM tbl"
chunk_size = 1_000_000

batch_iter = conn.execute(query).fetch_record_batch(chunk_size)
for batch in batch_iter:
    del batch
```

The first batch always completes fine, but in subsequent batches we apply the Slice again which is a problem, in `ArrowScalarBaseData::Append` `auto source_idx = format.sel->get_index(i);` gives us back random uninitialized memory.

### CODE REVIEW

**Review by pdet — APPROVED** [review]
LGTM!

**Comment by Mytherin** [comment]
Thanks!

**Comment by Tishj** [comment]
@Mytherin
I was experiencing a weird unreproducable crash on Win32 in `test_capi_arrow.cpp` SECTION "null schema"
I went through the logic and it looked like my changed should have no effect at all on that codepath, but never the less I'm not sure if the crash isn't reproducable on Win32 as it had only gone through one CI run.

**Comment by Mytherin** [comment]
Oh whoops - I thought the only CI failure here was the flaky test in #8074. It seems there is also a failure in CodeCov now. Could you have a look and submit a follow-up PR that fixes those?

**Comment by Tishj** [comment]
Sure, but I touched none of those files
<https://github.com/Tishj/duckdb/actions/runs/5363302214/jobs/9730780442>

I could "fix" the coverage by removing this <https://github.com/duckdb/duckdb/compare/feature...Tishj:duckdb:arrow_record_batch_segfault>

Because it's not used anywhere

**Pull request merged**
