### PR TITLE
Add Train Benchmark queries

### PR DESCRIPTION
**Pull request by szarnyasg**
I took at porting the Train Benchmark MySQL/SQLite implementation to DuckDB.

I co-designed & co-developed Train Benchmark during my PhD. There is an [OA journal paper](https://link.springer.com/article/10.1007%2Fs10270-016-0571-8) describing its specification.

In essence, it is a "model validation" benchmark, i.e. it performs OLAP-style queries on a model graph to check certain well-formedness properties in the graph. The set of features used by the queries is fairly small. The queries express subgraph matching with lots of joins and a few antijoins (when the query looks for the absence of an edge). They also use projection and filtering but there are no outer joins, aggregations, path queries, etc.

The difficulty of this benchmark is two-fold:

1. The queries are global, so their complexity increases linearly with the data set size (or worse).

    Antijoin queries were particularly problematic for MySQL at the time, it [timed out](https://link.springer.com/article/10.1007/s10270-016-0571-8/figures/10) even for mid-sized graphs (1.1M nodes+edges) on the queries that have an antijoin (RoutSensor, SwitchMonitored, SemaphoreNeighbor).

    SQLite performed better, here's what we wrote:

    > [...] However, SQLite is surprisingly fast in several configurations. This may indicate that other technologies still have a lot of potential for performance enhancements.

2. The full benchmark measures a "continuous model validation" scenario, i.e. the model graph is continuously updated (with both insert and deletes) and implementations need to return the current results for the query. Naturally, this favours incremental view maintenance approaches.

    The changes are issued by a Java/Groovy-based benchmark framework, so testing DuckDB with changes would require adding a DuckDB driver to the benchmark framework. This is doable but it needs a bit of work.

So far, my experience has been the following:

* Porting the schema was fairly easy, I used the same tricks like the ones in LDBC SNB loader.
* The queries worked out of the box.
* The SF1 test data set is fairly small (64 kB), so I included it in the PR.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR again! More tests/benchmarks are always welcome. Perhaps these could be added to the benchmark runner directly by creating .benchmark files for the interpreted benchmarks? See e.g. [here](https://github.com/cwida/duckdb/blob/master/benchmark/micro/cast/strftime.benchmark) for an example of one of these.

**Comment by szarnyasg** [comment]
Sure. Can you give me a point for how to test a `.benchmark` file?

**Comment by Mytherin** [comment]
To run a benchmark file you need to compile the benchmark runner, which can be done by passing `-DBUILD_BENCHMARKS=1` to CMake (or compiling with `BUILD_BENCHMARK=1 make` if you are using the makefile). You can then run `build/debug/benchmark/benchmark_runner relative/path/to/benchmark` (or `build/release/...` if you made a release build).

To run the strftime benchmark I linked above you would run `build/debug/benchmark/benchmark_runner benchmark/micro/cast/strftime.benchmark`

**Comment by szarnyasg** [comment]
> Perhaps these could be added to the benchmark runner directly by creating .benchmark files for the interpreted benchmarks? 

@Mytherin I added a `.benchmark` file for each query, see e.g. https://github.com/szarnyasg/duckdb/blob/trainbenchmark/benchmark/trainbenchmark/routesensor.benchmark

However, the current solution uses quite a lot of code duplication. Would it be better to implement a C++ file, similarly to the TPC-* benchmarks such as [TPC-DS](https://github.com/cwida/duckdb/blob/master/benchmark/tpcds/sf1.cpp)?

**Comment by Mytherin** [comment]
I would prefer not to add C++ files, but you are correct that there is a lot of duplication. In the TPC-H and TPC-DS benchmarks we support benchmark templates (see e.g. [the template](https://github.com/cwida/duckdb/blob/master/benchmark/tpch/sf1/tpch_sf1.benchmark.in) and [the file that uses the template](https://github.com/cwida/duckdb/blob/master/benchmark/tpch/sf1/q22.benchmark)). These could be used. One problem there is that they currently only support single-line replacements (e.g. the parameters cannot span multiple lines).

I think a nicer solution would be to extend the `load` and `run` commands to optionally take a file as parameter instead of the inlined query, similar to the `result` now. So the repeated load command could be replaced by `load trainbenchmark.sql` which should avoid most of the duplication; or a template could be used that has e.g. `run queries/q${LOAD_QUERY}.sql`

**Comment by szarnyasg** [comment]
I tried templating and passing the query as a parameter but noticed that the parser has some limitation.
Namely, the following works:
```
template benchmark/trainbenchmark/trainbenchmark.in
QUERY=SELECT id FROM Sensor
```
But this query fails with `Expected a template parameter in the form of X=Y` (presumably the parser picks up the equality sign in the query as something else).
```
QUERY=SELECT id FROM Sensor INNER JOIN monitoredBy ON monitoredBy.Sensor_id = Sensor.id
```
Loading these from a file as [`result` allows](https://github.com/szarnyasg/duckdb/blob/c4ce3a0ccb392ac7c065ad9181c9c462c18807f6/benchmark/interpreted_benchmark.cpp#L117-L135) is certainly a better option.

**Comment by Mytherin** [comment]
Indeed the templates were not designed for full query replacement. I think loading queries/scripts from files is a more elegant solution for this problem. I will merge in this PR and loading queries/scripts from files can be done in a separate PR, which can also update these benchmarks to reduce unnecessary duplication.

**Pull request merged**
