### PR TITLE
Allow DESCRIBE/SHOW/SUMMARIZE to be used as a subquery

### PR DESCRIPTION
**Pull request by Mytherin**
Partially implements #8150

This PR allows `DESCRIBE/SHOW/SUMMARIZE` statements to be used as subqueries in SELECT statements. For example, the following is now valid SQL:

```sql
D SELECT column_name FROM (DESCRIBE SELECT 42 AS a);
┌─────────────┐
│ column_name │
│   varchar   │
├─────────────┤
│ a           │
└─────────────┘
D CREATE TABLE tbl AS SELECT * FROM (SUMMARIZE lineitem);
```

This is achieved by removing the `ShowStatement` entirely, and instead adding a new `ShowRef` that is a table reference that contains information about the describe/show/summarize statement.

#### New Reserved Keywords

In order to enable this change, `DESCRIBE`, `SHOW` and `SUMMARIZE` are now RESERVED keywords instead of UNRESERVED keywords.

### CODE REVIEW

**Comment by szarnyasg** [comment]
Will add docs for this.

**Comment by Mytherin** [comment]
Thanks!

**Comment by jexp** [comment]
Quick question @Mytherin 
Are the selected columns also used as "pushdown selections" (or whatever that's called) e.g. that expensive columns like null_percentage or the quantiles are not computed in summarize when I don't select them?

Thanks!

**Comment by Mytherin** [comment]
Currently the optimizer doesn't prune unused aggregates yet but it would certainly be possible in the future.

**Pull request merged**
