### PR TITLE
Support to other arrow timestamp types 

### PR DESCRIPTION
**Pull request by pdet**

### CODE REVIEW

**Comment by hawkfish** [comment]
It looks like the subtype added here has no internal physical or semantic meaning - it is just used to round-trip from Arrow?

**Comment by pdet** [comment]
Yeah, you are correct, this extra info is basically used in the arrow conversion only, but I think we eventually would want these types in duckdb anyway, in the end, they would all be int64 with casts when comparing different sub-type timestamps.

With that said, I'm not opposed to simplifying this with some char flag for now.

**Comment by pdet** [comment]
Hum, I think I'll actually add these types properly.

**Comment by hawkfish** [comment]
I guess I'm just concerned about how it might interact with #1680

**Comment by hawkfish** [comment]
One thought I had was that internally DuckDB represents `TIMESTAMP`s with µs precision, so another way of looking at this issue is that the data can come in in four(?) Arrow time formats, but should only go out in the one DuckDB uses internally?

**Comment by pdet** [comment]
Well, that is surely possible, but then it becomes a matter of what is desirable from a user perspective.
When doing a round-trip I would expect both input and output arrow tables to be the same. (Not sure what @hannesmuehleisen thinks here)

Adding these sub-types will surely increase the complexity of the interaction with other functions. The idea would be to extend the timestamp to get the subtype as a parameter, having µs precision as default, and for the functions that already operate o timestamps having µs precision , an auto-cast could be added. 

I guess in the end, the question is how much we want to integrate with arrow on these types. I'm also not aware of any other systems that have this sub-type representation of timestamps.

Also, all data types for timestamps are int64, so I'm not sure how #1680 would be affected by it since the is no type promotion.

**Comment by hawkfish** [comment]
I can totally see the desirability of round-trip with Arrow (or other systems) and the Tableau metadata system did just that for that same reason. It gets tricky when complex operations happen (e.g., divide a `TIMESTAMP` into `DATE` and `TIME` columns, perform some operation and. then merge them back together??) so it will never be perfect.  I think what was making me nervous was that this is the first "metadata-only" typing I have seen in `LogicalType` and I thought that was worth discussing.  

I think I was also concerned about the default internal type no longer being implicit (default argument? single-argument constructor?)

**Comment by pdet** [comment]
I think it's a very fair point. I will just create new logical types for the other timestamp sub-types, then no more metadata only typing ;-)

**Comment by hawkfish** [comment]
Do you mean there will now be multiple `TIMESTAMP` representations? That seems like it would result in a combinatorial explosion of casting and templates.  If we need this, the metadata-only typing seem far preferable.

Maybe the right approach is to have some kind of "external type hint" metadata outside of the `LogicalType` system? That sounds like a lot of work. I'm starting to agree that the subtype with no physical or semantic meaning may be the path of least resistance. In that case, I think we just need the assert and a single-argument constructor (was there one already?) That default constructor would be needed anyway so that we could write `TIMESTAMP`s into  Arrow files that originated somewhere else (e.g., line 303 in `arrow.cpp`).

**Comment by Mytherin** [comment]
We had some discussion on this and the separate timestamp representations seems to me like a cleaner way of enabling the loss-free interop, and will also enable zero-copy interop with other systems (e.g. R and NumPy/Pandas) that use different time representations. Since one of our goals as an embedded system is "playing nice" with others having separate timestamp representations seems like a good idea here.

I'm not such a fan of the metadata hints, since this information will likely be lost somewhere along the way and generally is unstructured/not as rigid as types themselves. It also does not help in allowing for zero-copy transfer, since we will then still need to do conversions for the interop.

This change will not be as huge/breaking as you might initially suspect because of the separation of logical and physical types. All of the timestamp types (s, ms, us and ns) will map to `timestamp_t` (`int64` internally), and will work as-is without any code changes for anything that operates on the physical type directly (storage, joins, sorts, window functions, etc). 

The main difficulty then becomes functions that actually interpret the value of the timestamp (e.g. date_part, date_trunc, etc), since they need to know the actual semantic value of the timestamp ("what does 1619617372000 mean"). However, this is solved by our function overloading framework. We have currently defined these functions for our default timestamp type (microseconds). Rather than re-define them for all the different timestamp types we will simply add autocasting from the other timestamp types to our default timestamp type (`timestamp_ms -> timestamp`, `timestamp_ns -> timestamp`, etc.)

This means that when you use a timestamp_ms in e.g. date_part, the system will simply automatically push a cast to timestamp before executing the date_part function. If we ever find that one of these casts becomes a performance problem/bottleneck, we could always later on add a specialization for these types, but I don't foresee this being a serious problem. 

All in all the code footprint of this change should not be very large, and you won't even really need to be aware of the other timestamp types when developing new functions or capabilities for timestamps because of the autocast functionality.

**Comment by hawkfish** [comment]
That makes sense. I also want to understand how this ill interact with #1680 for which I have finally found all the inconsistent type aliasing in the code?

**Pull request closed without merging**
