### PR TITLE
Add support for regexp matches in relational API

### PR DESCRIPTION
**Pull request by Tmonster**
If users wish to perform regex matches on R strings, we need to be able to implicitly cast r_string types to VARCHARS. To do this we add a cost to the `RegisterCastFunction`. We add a high cost since it is an expensive cast, however, it is the only cast available. 

A test has also been added.

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by rsund** [comment]
Is this required only for the experimental string handling (`experimental=TRUE` in `duckdb_register()`, i.e. that this is or has not been a problem with a "standard" string handling in `duckdb_register()` (that should also be zero copy)?

**Comment by Tmonster** [comment]
@rsund Yes, it is only required for experimental string handling in `Duckdb_register()` I haven't experienced any issues with "standard" string handling using `duckdb_register` as of yet. This should work with string handling when using `duckd::rel_from_df`

**Comment by Mytherin** [comment]
Perhaps you can change the R test to use a different string function (`substring` or so). We shouldn't use RE2 in R tests because it causes false positives in the setup that CRAN uses causing problems with our CRAN upload.

**Comment by Tmonster** [comment]
Sounds good. I think there might be an issue with the `duckdb_register` function that I am also going to look into. I keep getting `invalid permission errors`

**Comment by Tmonster** [comment]
Closing here to stop triggering tests on master while I fix the issue. Will use a PR on my own fork to check CI

**Pull request closed without merging**
