### PR TITLE
External merge sort

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR implements external merge sort for the PhysicalOrder operator. This builds upon the Radix sort implemented earlier.

Data arriving at the operator is serialized into row format on buffermanaged blocks. When a certain amount of data arrives, the data is sorted, and stored away. When all data has arrived and is sorted, the merge sort starts. All intermediates are written to buffermanaged blocks. This means that the operator is able to sort more data than fits in memory!

Blocks are merged in parallel, however there is still work to be done here. It is a cascaded merge sort, but the parallelism falls apart as the blocks are merged. Full parallelism will be fixed in a later PR.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks great to me. Perhaps we could add some more tests with larger sorts (e.g. sorting lineitem of TPC-H)?

**Comment by lnkuiper** [comment]
I added a test that sorts TPCH lineitem, and the test found a memory leak that was caused by an earlier change to hash aggregations. Detective Muhleisen figured it out, and I think the tests should be good now

**Review by hawkfish — COMMENTED** [review]
Is this guaranteed to work? Window can scan and append in parallel, so there is no guarantee that the `LAG` computation will do what you expect here.

**Comment by lnkuiper** [comment]
l_extendedprice is unique, therefore a window function over an order by l_extendedprice (without partitions) should always give the same results no?

I thought it would be a good verification to compare the window and order by sorting

**Comment by hawkfish** [comment]
What I meant was that the blocks will come out of the `PhysicalOrder` operator in the specified order but the `PhysicalWindow` operator may not *assemble* them in that same order because it scans in parallel. So the first N blocks may get read by N threads, but they may not finish [computing other values](https://github.com/duckdb/duckdb/blob/ecc804c73b58ddec4824430a6b88a3817a460913/src/execution/operator/aggregate/physical_window.cpp#L1042) at the same time (think a string column with a nasty collation). So I think this test will pass 99% of the time, but it is not guaranteed. Does that make sense?

**Comment by Mytherin** [comment]
Since the GetChunkInternal flows directly to a result rather than into another pipeline the scanning should always be performed in sequential order. However, perhaps to be absolutely sure we could push a `rowsort` onto the Window function tests?

**Comment by hawkfish** [comment]
Thanks for the off-line explanation. To sum up, final pipelines are executed sequentially for predictability and early termination, so my concern can't actually happen.

**Comment by lnkuiper** [comment]
Thanks for clearing that up Mark!

As for your suggestion: does adding a row sort on top of the window function output not defeat the purpose of the test? If we do this we are comparing the row sort with the row sort, rather than comparing the row sort with the window function sort.

**Comment by Mytherin** [comment]
The row sort should only sort the output on `l_extendedprice`. If the window function does not compute the `lag` correctly (e.g. when the window function sort has a bug) the result should still be different.

**Comment by lnkuiper** [comment]
I've added the sort on `l_extendedprice`, could you take another look?

**Comment by Mytherin** [comment]
Thanks, looks good to me now!

**Pull request merged**
