### PR TITLE
Add table function information_schema_columns()

### PR DESCRIPTION
**Pull request by jwills**
This PR implements the `information_schema_columns` table function as a more-involved follow-on to PR #899 to implement issue #658. I'm going to start this one out in draft form since there are a number of issues to address before this is ready-ready for review.

The main thing I would like feedback on is the testing model: in particular, iterating through the complete list of columns is trickier than iterating through the list of schemas (in `information_schema_schemata()`) or tables/views (in `information_schema_tables()`) because I need to keep track of a) which table/view the function is currently processing (via the `offset` state variable) as well as b) which _column_ inside of that table/view needs to be processed next (via the `column_offset` state variable.) I think the logic for doing this tracking is correct, but testing it formally will mean that I need to automatically generate a number of tables, some of which would have > 1024 columns: what is the best way to do that in the current testing framework?

Second, there are a couple of fields that FIXMEs associated with them around the need to check constraints (specifically, not-null checks for all columns and length checks for varchar(n) columns), similar to the checks that need to be implemented for `pragma_table_info`: I'm happy to do those implementations here, or in other PR, or defer to someone who is more familiar with the details of the constraint logic. I played around with this a bit and felt strange getting so deep into the weeds of the `Constraint` class hierarchy inside of this metadata function, but maybe that is the best approach here?

Finally, I wrote some helper classes to handle the differences between tables and views for column names, types, and default values; I felt a little weird about doing this too, so if it's not the right approach here, please let me know and I can take it in a different direction. This was a lot more C++ than I am use to writing and wasn't nearly as copy-and-paste as the last PR was, so feedback is greatly appreciated. :)

### CODE REVIEW

**Comment by Mytherin** [comment]
> The main thing I would like feedback on is the testing model: in particular, iterating through the complete list of columns is trickier than iterating through the list of schemas (in information_schema_schemata()) or tables/views (in information_schema_tables()) because I need to keep track of a) which table/view the function is currently processing (via the offset state variable) as well as b) which column inside of that table/view needs to be processed next (via the column_offset state variable.) I think the logic for doing this tracking is correct, but testing it formally will mean that I need to automatically generate a number of tables, some of which would have > 1024 columns: what is the best way to do that in the current testing framework?

So rather than create a big table, an alternative is to change the vector size. You can do this in `src/include/duckdb/common/vector_size.hpp` by changing `#define STANDARD_VECTOR_SIZE`. On the PR we already run tests where the vector size is set to 2 and 512, rather than the default 1024. A vector size of 2 catches bugs of this nature rather effectively because it already triggers on tables with 3 columns, rather than only on tables with 1025 columns.

Testing a table with 1025 columns is not so excessive, though. I wouldn't mind if you add a test containing a table with that amount of columns. I would just generate a CREATE TABLE statement using e.g. a python script, and then copying that into a test. 

> Second, there are a couple of fields that FIXMEs associated with them around the need to check constraints (specifically, not-null checks for all columns and length checks for varchar(n) columns), similar to the checks that need to be implemented for pragma_table_info: I'm happy to do those implementations here, or in other PR, or defer to someone who is more familiar with the details of the constraint logic. I played around with this a bit and felt strange getting so deep into the weeds of the Constraint class hierarchy inside of this metadata function, but maybe that is the best approach here?

Yeah, you need to look at the table constraints to figure this out. VARCHAR(n) length checks are currently not implemented, so those you can ignore. NOT NULL checks should not be very difficult. Just check the set of constraints for a `BoundNotNullConstraint`, which has a column index pointing to which column is affected by the constraint.

> Finally, I wrote some helper classes to handle the differences between tables and views for column names, types, and default values; I felt a little weird about doing this too, so if it's not the right approach here, please let me know and I can take it in a different direction. This was a lot more C++ than I am use to writing and wasn't nearly as copy-and-paste as the last PR was, so feedback is greatly appreciated. :)

The helpers look fine to me.

**Comment by Mytherin** [comment]
Looks fine to me now. Don't worry about the codefactor failure. Shall I merge it?

**Comment by jwills** [comment]
Yes please!

**Comment by hannesmuehleisen** [comment]
Thanks again for this PR, it enabled #907

**Pull request merged**
