### PR TITLE
Add ordering to to underspecified tests

### PR DESCRIPTION
**Pull request by lnkuiper**
After merging #8475 and #8593, some queries' output order changed. Some of our tests were underspecified and relied on a specific output order. This mostly caused problems for our vector size = 2 tests.

I've added ordering to the tests so that they are deterministic again.

### CODE REVIEW

**Comment by lnkuiper** [comment]
Failures are unrelated, I think this is ready to go

**Comment by lnkuiper** [comment]
`test/sql/parallelism/intraquery/test_parallel_nested_aggregates.test` was also fixed on `main`, conflicts are resolved _again_.

**Comment by lnkuiper** [comment]
requested your review @pdet since we worked together on these vector size 2 tests

**Review by pdet — APPROVED** [review]
LGTM

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
