### PR TITLE
Fixes issue #4365 - Not null constraint is no longer duplicated

### LINKED ISSUE #4365: Multiple NOT NULL constraints in `duckdb_constraints()`
### What happens?

Each foreign key to a primary key adds an *additional* `NOT NULL` constraint. In the example below, the third row shouldn't be added.

### To Reproduce

```sql
create table x (c1 integer, primary key (c1));
create table y (c1 integer, foreign key (c1) references x (c1));
select * from duckdb_constraints();
```

```
schema_name  schema_oid  table_name  table_oid  constraint_index  constraint_type  constraint_text                    expression  constraint_column_indexes  constraint_column_names
-----------  ----------  ----------  ---------  ----------------  ---------------  ---------------------------------  ----------  -------------------------  -----------------------
main         1           x           1287       0                 PRIMARY KEY      PRIMARY KEY(c1)                                [0]                        [c1]                   
main         1           x           1287       1                 NOT NULL         NOT NULL                                       [0]                        [c1]                   
main         1           x           1287       2                 NOT NULL         NOT NULL                                       [0]                        [c1]                   
main         1           y           1284       0                 FOREIGN KEY      FOREIGN KEY (c1) REFERENCES x(c1)              [0]                        [c1] 
```

### OS:

macOS

### DuckDB Version:

#4346

### DuckDB Client:

CLI

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
As the title says, fixes #4365

### CODE REVIEW

**Comment by Tishj** [comment]
Ah so there's an existing test requesting this behavior?
I'd say this is a bug, but if it's been tested for, I'm not sure anymore..

**Comment by Mytherin** [comment]
The test just contains the copy pasted output of `duckdb_constraints`, feel free to edit with the new output. Removing the duplicated constraints is a great idea.

**Comment by Tishj** [comment]
Alright, thanks for the quick reply, I'll adjust the test!

**Review by krlmlr — APPROVED** [review]
Nice, thanks!

**Pull request merged**
