### PR TITLE
Typo was making ignore warnings of extensions to be ignored

### LINKED ISSUE #4392: IGNORE_WARNINGS flag in extension build in CMake is not handled correctly
There is a typo in the definition:

```
set(INGORE_WARNINGS OFF)
build_loadable_extension(json ${JSON_EXTENSION_FILES} ${IGNORE_WARNINGS})
```

This causes the flag to be empty, and because CMake is CMake it does not crash on an unknown variable but instead passes in an empty string. It is also passed in as a source file (as the `build_loadable_extension` is a varargs function that uses everything after the extension name as a source file), so fixing the typo breaks the build as well.

### PR DESCRIPTION
**Pull request by pdet**
Fixes: #4392

### CODE REVIEW

**Comment by krlmlr** [comment]
Extensions build just fine with warnings enabled on gcc 9.4, mostly. Should we try to keep warnings enabled and perhaps disable selectively?

**Comment by Mytherin** [comment]
That is exactly what this flag is for, no?

**Comment by krlmlr** [comment]
Oh, I see: we want to ignore warnings for substrait and icu, and see them for everything else.

I propose keep the icu settings as `OFF`, will open a separate PR after this is merged.

**Comment by Mytherin** [comment]
In general I would say fixing warnings in third party code, especially code as well-tested as ICU, is very low priority. Feel free to push this fix if it is a small/simple fix - but I would much rather just disable the warnings if they give any more trouble.

**Comment by Mytherin** [comment]
Superseded by #4866

**Pull request closed without merging**
