### PR TITLE
[Internals] Fix key/value name in MAP produced by `map_entries`

### LINKED ISSUE #8459: [Unnest] Internal Exception triggered by simple query involving a MAP
### What happens?

Below query causes the following exception:
```
Error: INTERNAL Error: Assertion triggered in file "/root/Source/cpp/duckdb/src/execution/operator/projection/physical_unnest.cpp" on line 136: child_vector.GetType() == result.GetType()
```

### To Reproduce

```sql
create table integers(i integer);
INSERT INTO integers VALUES (1),(1),(3),(20),(20),(20);
select unnest(map_entries(histogram(i))) FROM integers; 
```

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

-

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #8459 

`map_entries` produced a MAP with "k" and "v" as struct fields, other maps use "key" and "value".
This caused a type mismatch

I also took the opportunity to reduce some of the nesting in `physical_unnest`, the diff looks horrible but no actual changes were made.

------------------------

Invariant checking for MapVerify has been restored, has been broken since we switched the internal representation
Also added a new invariant there, on the fields of the internal struct, they have to be "key" and "value" to ensure type equality does not fail.

This invariant has been enforced in `Value::MAP` and `LogicalType::MAP`

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

I'm not sure if changing the struct type equality is the right fix here. Structs with different column names should not be equal to one another. All that we currently do is we allow adding implicit casts between structs with different column names (although we should remove that as well soon).

**Comment by Tishj** [comment]
Ah then I misunderstood, I thought this propagated through the system, but this only applies to the binding phase then?

I'll have another look at this issue then, see what's actually the problem

**Comment by Tishj** [comment]
Just noticed that the VerifyMap function wasn't called anywhere because it was still under the STRUCT code block, so this has been broken since we switched the internals from struct -> list

**Comment by Tishj** [comment]
Seems like this is causing an issue:
```sql
query I
SELECT MAP_FROM_ENTRIES(ARRAY[([1,2], 2), ([3,4], 4)]);
----
{[1, 2]=2, [3, 4]=4}
```

If I disable the optimizer it works, and more specifically it's caused by ConstantFolding rule.
I can't figure out why that is, but it dies here:
```
INTERNAL Error: Assertion triggered in file "/Users/thijs/DuckDBLabs/duckdb/src/storage/statistics/struct_stats.cpp" on line 86: stats.GetType() == other.GetType()
```

**Comment by Tishj** [comment]
@hannes Could you have a look to see if this can be merged?

**Pull request merged**
