### PR TITLE
CSV Loader would wrongly assume column with all sample values null to be Bool

### PR DESCRIPTION
**Pull request by pdet**
Just defaulting this case to VARCHAR

### CODE REVIEW

**Comment by tdoehmen** [comment]
Thanks for fixing this! This works well unless a column is actually of  `bool ` type, no? But since the bool detection is very premature I'd say it's okay for now. Maybe an idea would be to add the `NULL` type to the `type_candidates` and **then** default to `VARCHAR ` if `best_sql_types_candidates[col].size() == type_candidates.size()`.

**Comment by pdet** [comment]
@tdoehmen spot on, I've added a test for that, can you please check it? ;-)

**Comment by tdoehmen** [comment]
Looks good to me! I noticed now when running the unit tests, that testing of the CSV functionality takes up a lot of time. Maybe one way to reduce the time is to use more minimal test cases. Is it feasible to reduce the size of the voter.tsv file and still test for the same things? When it's only about the null-columns then I think a 200-line file or so would do. If you want to test what happens when the CSV sniffer misses certain rows on a small file, you could manually set the sample_size to 10 or so. I know it's not only this test case which takes up a lot of time but also old ones. When I find the time, I'll have a look into them as well.

**Comment by Mytherin** [comment]
> Looks good to me! I noticed now when running the unit tests, that testing of the CSV functionality takes up a lot of time. Maybe one way to reduce the time is to use more minimal test cases. Is it feasible to reduce the size of the voter.tsv file and still test for the same things? When it's only about the null-columns then I think a 200-line file or so would do. If you want to test what happens when the CSV sniffer misses certain rows on a small file, you could manually set the sample_size to 10 or so. I know it's not only this test case which takes up a lot of time but also old ones. When I find the time, I'll have a look into them as well.

As long as the tests are marked with `.test_slow` it is not too much of a problem, these are only run in release mode so they complete rather fast. The CSV tests are only a small fraction of the total test suite there right now, so no need to optimize this for now. If it becomes a significant bottleneck we can have a look at optimizing them.

**Pull request merged**
