### PR TITLE
R: Update duckplyr tests

### PR DESCRIPTION
**Pull request by krlmlr**
This is code generated from https://github.com/duckdblabs/duckplyr.

### CODE REVIEW

**Review by Tmonster — APPROVED** [review]
lgtm. Why the change from expression references describe as 
```
groups = list(expr_reference("b"), expr_reference("g")),
```
to
```
    groups = list(
      b = {
        tmp_expr <- expr_reference("b")
        expr_set_alias(tmp_expr, "b")
        tmp_expr
      },
      g = {
        tmp_expr <- expr_reference("g")
        expr_set_alias(tmp_expr, "g")
        tmp_expr
      }
    ),
```
?
Just curious is all

**Comment by krlmlr** [comment]
Because `duckdb:::expr_reference()` doesn't have an `alias` argument yet.

**Comment by hannes** [comment]
Maybe we can add that argument. Not this PR though.

**Comment by krlmlr** [comment]
Or `expr_set_alias()` could return the first argument, invisibly.

**Comment by hannes** [comment]
I think the set_alias should return a copy with the alias or we add the alias argument to the constructor. Depends a bit what is easier for calling code.

**Comment by Tmonster** [comment]
`expr_reference` doesn't have an alias yet, but technically the first argument (the name) becomes the alias from what I see in relational.cpp. But this automatic assignment should be changed eventually, I remember it causing an issue earlier with macros and names argument lists. 

```
[[cpp11::register]] SEXP rapi_expr_reference(std::string name, std::string table) {
	if (name.size() == 0) {
		stop("expr_reference: Zero length name");
	}
	if (!table.empty()) {
		auto res = make_external<ColumnRefExpression>("duckdb_expr", name, table);
		res->alias = name; // TODO does this really make sense here? <--- this line
		return res;
	} else {
		return make_external<ColumnRefExpression>("duckdb_expr", name);
	}
}
```

**Pull request merged**
