### PR TITLE
Use difftime_str instead of hms class

### PR DESCRIPTION
**Pull request by krlmlr**
@Mytherin: I wonder why #2150 introduced use of the hms class here, it's not even a suggested dependency of duckdb.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
No idea where the `hms` comes from there.

**Comment by hannesmuehleisen** [comment]
No idea where the `hms` comes from, too

**Comment by krlmlr** [comment]
I'll rework to use plain difftime.

**Comment by Sergio6690** [comment]
Nice

**Comment by krlmlr** [comment]
Done.

**Pull request merged**
