### PR TITLE
In LocalFileSystem::FileExists  - throw on access/stat errors

### PR DESCRIPTION
**Pull request by Mytherin**

### CODE REVIEW

**Comment by Mytherin** [comment]
I think that's unrelated - if the callsites don't handle errors in `FileExists`, they also don't handle errors in the subsequent `OpenFile`, hence this will go wrong regardless of this changeset.

**Comment by carlopi** [comment]
Yes, in some cases, but there are also cases where FileExists is checked before reading the file, like:
```
optional_idx CGroups::GetCGroupV2MemoryLimit(FileSystem &fs) {
        const char *cgroup_self = "/proc/self/cgroup";
// ....
        if (!fs.FileExists(cgroup_self)) {
                return optional_idx();
        }

        string cgroup_path = ReadCGroupPath(fs, cgroup_self);
        if (cgroup_path.empty()) {
                return optional_idx();
        }
//....
}
```
This does OK with reduced permissions if FileExists fail cleanly.

**Comment by Mytherin** [comment]
That's fair. I would say we should add a new flag to `OpenFile` in the vein of `ReturnNullOnError` and use that instead in those places.

**Comment by Mytherin** [comment]
Needs more work

**Pull request closed without merging**
