### PR TITLE
Add basic support for GeoSpatial type

### PR DESCRIPTION
**Pull request by handstuyennn**
Please see issue https://github.com/duckdb/duckdb/issues/2836

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR and the work you put in here!

Perhaps I was not entirely clear in the issue, but we do not want the `geom` code to be part of the main library. Instead, we want it to be part of a `geom` extension (similar to how PostGIS is itself an extension to Postgres). That means that any code relating to the `geom` module should be in the `extension/geom` folder, and in general the `src` folder should not be modified.

This is including Postgis as well. While this is fine for the extension (and means the extension has to be licensed under GPL) - we do not want this to be included along with the main DuckDB source code. All of the Postgis code should be included **only** within the extension directory (`extension/geom`) to make this clear. 

Could you have a look at refactoring this PR so that it does not touch any code in the `src` directory, and instead creates these functions and methods as part of a `geom` extension in the `extension` folder (with the appropriate license)?

**Comment by hannesmuehleisen** [comment]
We might also consider putting this into a separate repo

**Comment by handstuyennn** [comment]
Hi @Mytherin,

Thanks for the feedback. As I see it, we have two options:

1. The first option would extract all functions and miscellanea into an extension, but we would need to **keep** the core type-related `GEO` stuff within `src`. This would be the simpler approach in terms of development. 
2. The second approach would be to allow an interface to create custom types via C-like functions, in a manner [similar to Postgres](https://www.postgresql.org/docs/9.0/sql-createtype.html#:~:text=The%20parameters%20can,low%2Dlevel%20language) and then build on top of that. 

The second approach seems like it would be a bit complex, so I would suggest the first approach. Looking forward to your feedback on the above.

**Comment by handstuyennn** [comment]
Hi @Mytherin

Just following up on the above. Let me know if you'd prefer I go ahead with implementing with the GEO type in the src/ folder or begin implementing the custom type system similar to this: https://www.postgresql.org/docs/current/extend-type-system.html.

**Comment by Mytherin** [comment]
> Hi @Mytherin,
> 
> Thanks for the feedback. As I see it, we have two options:
> 
> 1. The first option would extract all functions and miscellanea into an extension, but we would need to **keep** the core type-related `GEO` stuff within `src`. This would be the simpler approach in terms of development.
> 2. The second approach would be to allow an interface to create custom types via C-like functions, in a manner [similar to Postgres](https://www.postgresql.org/docs/9.0/sql-createtype.html#:~:text=The%20parameters%20can,low%2Dlevel%20language) and then build on top of that.
> 
> The second approach seems like it would be a bit complex, so I would suggest the first approach. Looking forward to your feedback on the above.

We would need to go with the second approach. It is a lot cleaner and much preferred since it allows the `geom` extension (and all similar extensions) to exist completely independently from the main code base. You are correct that this is indeed more complex. Note that we are quite close to supporting `CREATE TYPE` already, so it is not too far off. However, there is more work remaining to create a truely extensible type system. One of the big pain points there right now is that there is no way of defining casts. This will need to be resolved before externally defined types can have the same power as internal types. 

If you are interested in working on this perhaps you could have a look at adding the generic `CREATE TYPE` statement? Note that we already have support for adding custom types to the catalog as part of the `ENUM` types that @pdet has added (#2347).

**Comment by Mytherin** [comment]
As described above, this PR cannot be merged currently, so I am closing it for now.

**Pull request closed without merging**
