### PR TITLE
Add option to limit parallel compile

### PR DESCRIPTION
**Pull request by ashish01**
Could be useful for memory limited systems like Raspberry Pi Model 3

### CODE REVIEW

**Comment by ashish01** [comment]
I would like to test this locally. Is there a way to do pip install but with local source code? Thanks!

**Comment by ashish01** [comment]
>  CodeQuality / CodeCov (standard) (pull_request) Failing after 93m 

From the logs looks like this test is flaky.

```
[2023-01-18T22:21:47.174Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov' failed with exit code 255
```

**Comment by Tishj** [comment]
Yea CodeCov upload often has issues sadly

**Comment by Mytherin** [comment]
Thanks

**Pull request merged**
