### PR TITLE
use connections pane just in interactive sessions

### PR DESCRIPTION
**Pull request by pachadotdev**
very minimal change, but this prevents unexpected problems with connection pane customization, such as the censo2017 package that uses duckdb

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Thanks, could you please remove the changes that are strictly formatting? Hard to see the actual change there. Is this just about the icon?

**Comment by pachamaltese** [comment]
sorry, let me clear those weird indentation changes

**Comment by pachamaltese** [comment]
ok, ready
the change is a clever trick that I adapted from ODBC pkg, which only opens a connection on interactive sessions and when the connection is called from top level, not inside functions, and it prevents this:
image

**Comment by pachadotdev** [comment]
Hi. Just a follow up. Can this be merged? it eases a lot of things with censo2017 pkg.

**Comment by hannesmuehleisen** [comment]
There is still a failing test, need to see if this can be re-run

**Comment by pachadotdev** [comment]
I saw the error, was https://github.com/duckdb/duckdb/pull/1780/checks?check_run_id=2688290480#step:6:559, which is that testthat can't be installed on i386

**Comment by hannesmuehleisen** [comment]
I integrated some of this PR into #2044, could you have a look there please?

**Comment by pachadotdev** [comment]
> I integrated some of this PR into #2044, could you have a look there please?

awesome !! works perfect

**Pull request closed without merging**
