### PR TITLE
Issue #13525: Window Local States

### LINKED ISSUE #13525: Regression: query that runs instantly on GA release hangs indefinitely on the last few nightlies
### What happens?

A query of moderate complexity and based on small-ish datasets hangs indefinitely on the past few nighty builds. The same query finishes correctly instantly on the GA release.

### To Reproduce

```sql
  select      row_number() over ()
  ,           count(distinct upper_ch1_ch2) over()::int  as num_bigrams
  ,           sum(count_ch1_ch2) over ()            as bigram_count_all
  ,           count_ch1_ch2 / bigram_count_all         as actual_bigram_frequency
  ,           ch1.actual_frequency * ch2.actual_frequency as expected_bigram_frequency
  from        read_csv('stat_bigrams.csv')    as stat_bigrams
  inner join  read_csv('stat_stat_chars.csv') as ch1
  on          stat_bigrams.ascii_upper_ch1  = ch1.ascii_upper_ch
  inner join  read_csv('stat_stat_chars.csv') as ch2
  on          stat_bigrams.ascii_upper_ch2 = ch2.ascii_upper_ch;
```
[stat_bigrams.csv](https://github.com/user-attachments/files/16726998/stat_bigrams.csv)
[stat_stat_chars.csv](https://github.com/user-attachments/files/16726999/stat_stat_chars.csv)

### OS:

windows 11 enterprise

### DuckDB Version:

v1.0.0 1f98600c2c (duckdb_cli-windows-amd64)

### DuckDB Client:

CLI 

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Count the local states instead of assuming
we get all the available threads.

fixes: duckdb/duckdb#13525
fixes: duckdblabs/duckdb-internal#2830

### CODE REVIEW

**Comment by hawkfish** [comment]
The regression failures are across the board, so I think they are unrelated.

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM.

The regression seems to be in q51, which does have a number of window functions:

```
benchmark/tpcds/sf1/q51.benchmark
Old timing: 0.298049
New timing: 0.407633
```

I've re-run the regression suite - might be worth at least briefly looking at.

**Comment by hawkfish** [comment]
The problem was the repeated rebuilding of the task list. After moving things around so the task list was only built once again, the benchmark is back where it used to be.

I also accidentally ran the SF-100 benchmark, and it also got twice as fast!

```sh
name	run	timing
benchmark/large/tpcds-sf100/q51.benchmark	1	26.001757
benchmark/large/tpcds-sf100/q51.benchmark	2	25.864159
benchmark/large/tpcds-sf100/q51.benchmark	3	25.879309
benchmark/large/tpcds-sf100/q51.benchmark	4	25.752803
benchmark/large/tpcds-sf100/q51.benchmark	5	26.240130

name	run	timing
benchmark/large/tpcds-sf100/q51.benchmark	1	12.720996
benchmark/large/tpcds-sf100/q51.benchmark	2	12.177067
benchmark/large/tpcds-sf100/q51.benchmark	3	13.006717
benchmark/large/tpcds-sf100/q51.benchmark	4	12.708615
benchmark/large/tpcds-sf100/q51.benchmark	5	12.892784
```

**Comment by hawkfish** [comment]
The only regression failure is `benchmark/csv/ignore_errors.benchmark`, which doesn't use windowing. Looks spurious.

**Comment by Mytherin** [comment]
Thanks! Great results :)

**Pull request merged**
