### PR TITLE
Lazyload dll bugfix

### PR DESCRIPTION
**Pull request by chilarai**
PR for issue #1701

### CODE REVIEW

**Comment by chilarai** [comment]
@hannesmuehleisen, there is a formatting issue due to which the PR is failing. I tried to run the `format.py` script to fix that but can't seem to run the Python script. Else it has passed the test and also compiling fine on Windows
Can this be accepted as a valid PR?

**Comment by Mytherin** [comment]
Could you manually fix the formatting issues? The exact issues are shown in the [CI run](https://github.com/duckdb/duckdb/pull/1705/checks?check_run_id=2491578663):

```
----------------------------------------
----------------------------------------
Found differences in file test/extension/CMakeLists.txt
----------------------------------------
----------------------------------------
--- 
+++ 

@@ -14,7 +14,9 @@

 endif()

 if(WIN32)
-  set_target_properties(loadable_extension_demo PROPERTIES LINK_FLAGS_RELEASE "/DELAYLOAD:duckdb.dll")
-  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}  /DELAYLOAD:duckdb.dll")
+  set_target_properties(loadable_extension_demo
+                        PROPERTIES LINK_FLAGS_RELEASE "/DELAYLOAD:duckdb.dll")
+  set(CMAKE_EXE_LINKER_FLAGS_RELEASE
+      "${CMAKE_EXE_LINKER_FLAGS_RELEASE}  /DELAYLOAD:duckdb.dll")
 endif()

```

**Comment by chilarai** [comment]
Thanks. I referred from above and changed it manually. The format check has passed

**Comment by Mytherin** [comment]
Thanks! Once the CI runs pass we can merge the change.

**Pull request merged**
