### PR TITLE
Update reduce_sql script to have a max time

### PR DESCRIPTION
**Pull request by Tmonster**
Fixes https://github.com/duckdblabs/duckdb-internal/issues/2434

### CODE REVIEW

**Comment by Tmonster** [comment]
Have a fuzzing CI job here 
https://github.com/Tmonster/duckdb-fuzzer-ci/pull/3
and 
eventually here
https://github.com/Tmonster/duckdb-fuzzer-ci/actions/runs/9760569496

**Comment by Tmonster** [comment]
Looks like there are some other failures, will try to clean them up as well

**Comment by Mytherin** [comment]
This should be moved to the sqlsmith repo right? The fuzzer scripts have been removed from here.

**Comment by Tmonster** [comment]
PR has been moved to the sqlsmith repository
https://github.com/duckdb/duckdb_sqlsmith/pull/10/files

**Pull request closed without merging**
