### PR TITLE
Allow to load extensions through compiler variable definitions

### PR DESCRIPTION
**Pull request by pdet**
This facilitates the development of out of tree extensions (mostly it's testing and clion integration), since it allows them to be loaded through variables defined on their root cmake file.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Should this not also include changes in the CMake? It is a bit unclear to me how to use this (without modifying the root CMake file directly).

It might be nice to allow this to be used by just passing parameters to the Makefile, e.g.:

```sql
OUT_OF_TREE=~/Programs/sqlite_scanner make
```

**Comment by pdet** [comment]
Yeah, the out-of-tree cmakefile will have to have something like

e.g., 
```
add_compile_definitions(OUT_OF_TREE)
add_compile_definitions(EXTENSION_CLASS=SubstraitExtension)
add_compile_definitions(EXTENSION_HEADER="substrait_extension.hpp")
```

The problem with having these defined on the makefile, is that you have to manually set them up on clion as well, on the cmake file things just work. Including with the built-in debug/release modes of clion.

I'm finishing up my PR for the substrait repo, then I'll link it here and things can be more clear on the full context of it.

**Comment by Mytherin** [comment]
Ah, yes that is fair enough. Can we prefix the defines with DUCKDB_?

**Comment by pdet** [comment]
@Mytherin I've linked the repo that uses this, I think the main goal of these extensions is to build an infrastructure where a developer doesn't have to mess around with these cmakefiles, it still needs a bit of work, but I think this is a step on the right direction :-)

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
