### PR TITLE
[Python] UDFs now produce the correct result when used together with `range`

### LINKED ISSUE #7773: Scalar UDFs assume Idempotency?
### What happens?

When using the Scalar Functions [PR7171](https://github.com/duckdb/duckdb/pull/7171), the same values are returned for the same inputs. 

If by design, then this should be clearly documented, but it seems more like a bug or unintended consequence of another optimization. 

### To Reproduce

```
import duckdb
from duckdb.typing import *
from faker import Faker
def random_date():
	fake = Faker()
	return fake.date_between()
duckdb.create_function('random_date', random_date, [], DATE)
res = duckdb.sql('select random_date() from range(10)').fetchall()
print(res)
```
returns the same date, repeated 10 times: 
> [(datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),), (datetime.date(2012, 7, 10),)]

#### Using a parameter to ensure different results for each pass:

Modifying the function to take an incrementing int returns the expected result:
```
import duckdb
from duckdb.typing import *
from faker import Faker
def random_date(x):
	fake = Faker()
	return fake.date_between()
duckdb.create_function('random_date2', random_date, [BIGINT], DATE)
res = duckdb.sql('select random_date2(x) from range(10) t(x)').fetchall()
print(res)
```
> [(datetime.date(2012, 3, 21),), (datetime.date(2009, 2, 28),), (datetime.date(2021, 11, 16),), (datetime.date(2008, 12, 17),), (datetime.date(2011, 11, 26),), (datetime.date(2017, 7, 24),), (datetime.date(2014, 12, 7),), (datetime.date(1994, 2, 8),), (datetime.date(2014, 1, 17),), (datetime.date(1999, 6, 23),)]

### OS:

Windows

### DuckDB Version:

0.8.1-dev194

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7773 

The title might be too narrow, but I was struggling to find a good concise explanation of what the issue was.

Because the function was not marked as having side effects, ConstantFolding caused us to only execute the function once.
After that was fixed though, in the c++ wrapper for the python udf execution we turned it into a ConstantVector if all the inputs are constant, which made udfs like this produce the wrong result:

```py
fake = faker.Faker()
def generate_date():
    return fake.date_between()

con.create_function(
    'generate_date', 
    generate_date,
    [],
    'DATE'
)

rel = con.sql("""
select *
FROM (
    SELECT generate_date() AS random_date 
    FROM range(100)
)
""")
```

### CODE REVIEW

**Comment by Tishj** [comment]
@Mytherin should we add a `side_effects: bool` keyword arg instead of assuming every UDF will have side effects?

**Comment by Mytherin** [comment]
> @Mytherin should we add a `side_effects: bool` keyword arg instead of assuming every UDF will have side effects?

That sounds good yes

**Review by Mytherin — APPROVED** [review]
Thanks for the fix! LGTM

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
