### PR TITLE
Add shortcut to unindent

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #1041 (=extends it).

### CODE REVIEW

**Comment by krlmlr** [comment]
#1041 is simpler to review, the extra commit here uses a shortcut to avoid an extra indent.

**Comment by hannesmuehleisen** [comment]
So this still needs merged after #1041 is merged or not?

**Comment by krlmlr** [comment]
This is optional, depends on coding style. I tend to favor early returns.

**Comment by krlmlr** [comment]
Your call.

**Pull request merged**
