### PR TITLE
not export deletes to allow crosscompile

### PR DESCRIPTION
**Pull request by kimmolinna**
I have to comment these two lines to allow crosscompile from WSL2/Ubuntu to Windows with Zig. After this `zig build`is working for Ubuntu and `zig build -Dtarget=x86_64-windows-gnu` is working for Windows.

### CODE REVIEW

**Comment by Mytherin** [comment]
Those deletes are there for a reason (these objects should not be copied because it is not necessarily safe to do so). Where exactly does the code/compilation fail if the copy constructors are deleted?

**Comment by kimmolinna** [comment]
When I'am crosscompiling for Windows I will get the following error message:
```cpp
error(compilation): clang failed with stderr: In file included from /home/kimmo/duckdb/extension/parquet/parquet_writer.cpp:1:
In file included from /home/kimmo/duckdb/extension/parquet/include/parquet_writer.hpp:11:
In file included from /home/kimmo/duckdb/src/include/duckdb.hpp:11:
In file included from /home/kimmo/duckdb/src/include/duckdb/main/connection.hpp:14:
In file included from /home/kimmo/duckdb/src/include/duckdb/function/udf_function.hpp:11:
In file included from /home/kimmo/duckdb/src/include/duckdb/function/scalar_function.hpp:11:
In file included from /home/kimmo/duckdb/src/include/duckdb/common/vector_operations/binary_executor.hpp:12:
/home/kimmo/duckdb/src/include/duckdb/common/types/vector.hpp:72:13: error: attribute 'dllexport' cannot be applied to a deleted function
```

**Comment by Mytherin** [comment]
The fix is likely to remove the `DUCKDB_API` from those lines, rather than remove those lines entirely.

**Comment by kimmolinna** [comment]
I can confirm that crosscompiling with MinGW is working with the lines without DUCKDB_API.

**Pull request merged**
