### PR TITLE
[Python] Rework default behavior of `duckdb.connect`

### PR DESCRIPTION
**Pull request by Tishj**
This PR addresses a part of #5407

Namely this addresses:
- > Handle the DuckDBPyConnection as a shared_ptr everywhere, as recommended by https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr
- >  Don't create a new connection if connect is called without arguments (i.e con = duckdb.connect()) will just return the set default_connection.

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! Everything looks good to me. Perhaps @Mause or @pdet also wants to have a look?

**Comment by pdet** [comment]
LGTM,
Just as a clarification
```
() -> default_connection
(:memory:) -> non-cached new memory connection
(:memory:bla) -> cached named memory connection
```
Can we add tests with some funky setups? 
User closing default connection with other connections pointing to it
User closes default connection and reopens it
...

**Comment by Tishj** [comment]
> LGTM, Just as a clarification
> 
> ```
> () -> default_connection
> (:memory:) -> non-cached new memory connection
> (:memory:bla) -> cached named memory connection
> ```
> 
> Can we add tests with some funky setups? User closing default connection with other connections pointing to it User closes default connection and reopens it ...

Yes, good call, had not thought about closing the connection, though that was already possible as `default_connection` was always public.
I will add the tests

**Comment by Mytherin** [comment]
> > Thanks for the PR! Everything looks good to me. Perhaps @Mause or @pdet also wants to have a look?
> 
> I'm not sure about this `.connect()` change - it feels like quite a surprising difference in behaviour, especially given we're changing a given interface. What's the underlying rationale here?

The rationale is that we want to make it easier for people to work with a single (default) connection - as that is usually what people want to do when not working with an on-disk database. As we are now planning to streamline the Python interface this might create odd situations otherwise, e.g. people might do something like:

```py
import duckdb
duckdb.sql('CREATE TABLE integers')

con = duckdb.connect()
con.execute('SELECT * FROM integers') # table does not exist
```

Having the default `connect` refer to the default connection streamlines this process and makes working with a single connection less confusing. Starting up multiple databases has to now be done explicitly, by passing in the `:memory:` flag to the system (similar to what SQLite requires).

**Comment by Tishj** [comment]
Yea I agree

**Comment by Mause** [comment]
This is a pattern we could also consider which is commonly used in python libraries that have a default instance of things? See the very popular `requests` library

```python
# library code (in python, would probably be in C++ for real)
import duckdb

class DuckFrames():
    conn: duckdb.DuckDBPyConnection
    
    def __init__(self, conn):
        self.conn = conn
    
    # methods go here...

duckframes = DuckFrames(duckdb.default_connection)


# user code
from duckdb import duckframes, DuckFrames


duckframes.execute('select 42').df()

duckframes.begin()
duckframes.execute('create table integers(i integer)')
duckframes.rollback()


other_frame = DuckFrames(duckdb.connect('./on_disk.duckdb'))

other_frame.execute()
```

**Pull request closed without merging**
