### PR TITLE
[Python] Add pyspark null functions

### PR DESCRIPTION
**Pull request by mariotaddeucci**
Adding some functions to work with nulls.

I tried to add the `coalesce` function directly and use it on `nvl` and `ifnull` but I got the error saying the `coalesce` function is not a scalar function.

This PR could be converted to a draft and then adding a issue and just merge when the `coalesce` be added to python relational api.

### CODE REVIEW

**Comment by Tishj** [comment]
Thanks!
Feel free to make a PR extending our native python expression API as well when necessary.
Taking <https://github.com/duckdb/duckdb/pull/11941> as an example shows how easy these additions can be :)

**Comment by Tishj** [comment]
Please merge with main and address the colesce todo, the linked PR has been merged

Thanks for your efforts to extend the support of the spark API!

**Comment by mariotaddeucci** [comment]
Hey @Tishj , I synced the branch but still getting the same error, now I don’t know what to do.

**Comment by Tishj** [comment]
Please look at the PR, it's not a function expression, it has its own method

**Comment by mariotaddeucci** [comment]
Got it, now it worked.  
@Tishj  thanks for all the support o/

**Review by Tishj — APPROVED** [review]
Thanks for the PR, in the future please try to not make unnecessary changes, like the formatting ;)

**Comment by Mytherin** [comment]
Could you just have a look at the merge conflicts?

**Comment by mariotaddeucci** [comment]
@Mytherin done o/

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
