### PR TITLE
Add TPCDS sf-100 benchmarks

### PR DESCRIPTION
**Pull request by ZuleykhaPavlichenkova-TomTom**
As it was mentioned by @Tmonster, for TPCDS regression tests, we also need to add the large benchmarks to the duckdb/duckdb repository.

This PR adds 22 TPCDS sf100 benchmarks (with answers).

UPD. Some queries showed INCORRECT result because of ordering by NULL (q18, q71, q72, q73) and couple of them TIMEOUT (q22, q67), so after discussing it with @Tmonster I modified also their queries (`ORDER BY ALL`) and updated answers.
Answers on the modifies queries were also updated for the sf1 and sf0.01.
For the time outing queries support of `--disable-timeout` parameter in `scripts/regression_test_runner.py` had been added.

### CODE REVIEW

**Comment by hmeriann** [comment]
@Tmonster please take a look at this PR. I've added the rest of the queries and answers and closed the previous PR since it was branches from the wrong version of main

**Comment by hmeriann** [comment]
Some of the queries failing. Reasons are `TIMEOUT` or `INCORRECT`.
`INCORRECT` ones are more likely need `order by all` in their queries (checked with q65).

**Review by Tmonster — COMMENTED** [review]
@hmeriann on second thought, maybe we just disable result checking for the queries with inconsistent results (18, 22, 67, 71, 72). The benchmark files for these queries can just look like

then we also don't have to change the answers for the other scale factors

```
# name: ${FILE_PATH}
# description: ${DESCRIPTION}
# group: [tpcds-sf100]

name Q${QUERY_NUMBER_PADDED}
group tpcds
subgroup sf100

require tpcds

cache tpcds_sf100.duckdb

load benchmark/large/tpcds-sf100/load.sql

run extension/tpcds/dsdgen/queries/${QUERY_NUMBER_PADDED}.sql
```

**Comment by hmeriann** [comment]
> the queries with inconsistent results (18, 22, 67, 71, 72). The benchmark files for these queries can just look like
> 

and also a q73.
I reverted some commits and changed the mentioned queries. All of them run good now, except for the `q22` - it does `TIMEOUT`

**Review by Tmonster — APPROVED** [review]
looks good to me! 👍

**Comment by Tmonster** [comment]
@Mytherin this is ready to merge

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
