### PR TITLE
Fix distinct aggregate race: insert next event before scheduling tasks

### PR DESCRIPTION
**Pull request by Mytherin**
We need to insert the next event BEFORE scheduling the tasks. Otherwise we might finish all tasks before the next event is correctly scheduled, causing the subsequent event to be incorrectly skipped. 

This is very rare but has already happened on CI. Adding a sleep and running the TPC-H SF0.1 test makes it easily reproducible on Q16:

```cpp
		SetTasks(move(tasks));
...
		std::this_thread::sleep_for(std::chrono::milliseconds(1000));

		//! Now that all tables are combined, it's time to do the distinct aggregations
		auto new_event = make_shared<HashDistinctAggregateFinalizeEvent>(op, gstate, *pipeline, client);
		this->InsertEvent(move(new_event));

```

No results are output because the finalize is never called:

```
Wrong row count in query! (test/sql/tpch/tpch_sf01.test_slow:21)!
Expected 2762 rows, but got 0 rows
================================================================================
PRAGMA tpch(16);
================================================================================
Expected result:
================================================================================
Brand#14	SMALL ANODIZED NICKEL	45	12
...
Brand#53	MEDIUM BURNISHED BRASS	49	3
================================================================================
Actual result:
================================================================================
p_brand	p_type	p_size	supplier_cnt	
VARCHAR	VARCHAR	INTEGER	BIGINT	
[ Rows: 0]


```

### CODE REVIEW

**Comment by Tishj** [comment]
Ah I didn't realize that would happen, I moved it down because logically it makes sense to me to only queue the next event once this one is finished initializing.
I think adding this to the FinishEvent hook would have the same effect and the order of execution would be more obvious that way

**Comment by Mytherin** [comment]
> I think adding this to the FinishEvent hook would have the same effect and the order of execution would be more obvious that way

That's a good idea indeed.

**Comment by Mytherin** [comment]
Moved it to the finish

> Ah I didn't realize that would happen, I moved it down because logically it makes sense to me to only queue the next event once this one is finished initializing.

It was not that obvious to me either :) The thread sanitizer helped me track this one down.

**Review by Tishj — APPROVED** [review]

**Comment by Rockbag** [comment]
I think this also fixes https://github.com/duckdb/duckdb/issues/4815 as we have seen the same behavior there.

**Comment by Mytherin** [comment]
Yes, that seems likely indeed. You would see mostly empty results by this data race if it triggered.

**Pull request merged**
