### PR TITLE
R-Dataset: Add flag to enable async scanner

### PR DESCRIPTION
**Pull request by bigbohne**
This PR adds the use_async flag
when registering an arrow dataset to duckdb.

This should speed up querying S3 datasets.

### CODE REVIEW

**Comment by bigbohne** [comment]
Hi, this is my first pull request to an open source repository. I will take any help I can get :)

**Comment by hannesmuehleisen** [comment]
Happy to merge this if it works. Would you mind adding a test case, too please?

**Comment by bigbohne** [comment]
Added testcase ... waiting for checks ...

**Comment by hannesmuehleisen** [comment]
Thanks!

**Comment by bigbohne** [comment]
you're welcome!

**Pull request merged**
