### PR TITLE
[Dev] Initialize new buffers with garbage data if `DESTROY_UNPINNED_BLOCKS` is set

### PR DESCRIPTION
**Pull request by Tishj**
This PR extends the use of `DESTROY_UNPINNED_BLOCKS`.

What it currently does is replace the buffer of an unpinned block, and fill the old buffer with garbage data, to find issues where buffers were being used after they had been unpinned.

What this PR adds is filling newly allocated buffers with garbage data, to find issues where we implicitly rely on new buffers being clean (zero initialized).

Thankfully it has found no issues when I enabled this and ran the fast tests on release mode, but none the less I think it's good to add this memory verification.

### CODE REVIEW

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Good idea. Could we perhaps unify the `memset` code? It's now implemented 3x, once in `VerifyZeroReaders`, once in `RegisterSmallMemory`, and once in `RegisterMemory`.

**Comment by Mytherin** [comment]
Nightly CI that actually runs the verification here - https://github.com/Tishj/duckdb/actions/runs/8362180952

**Comment by Tishj** [comment]
https://github.com/Tishj/duckdb/actions/runs/8493017123

**Comment by Tishj** [comment]
Sneaky CI failure:
```
[1244/2989] (41%): test/sql/table_function/duckdb_keywords.test                 
/home/runner/work/duckdb/duckdb/src/common/vector_operations/generators.cpp:70:61: runtime error: signed integer overflow: 9223372036854775807 * 2 cannot be represented in type 'long int'
[1245/2989] (41%): test/sql/table_function/test_range_function.test
```

Cant reproduce this locally or in my "local" Linux VM (both are ARM)
It might only reproduce on x86_64?

It looks like it should be deterministic if we look at the values it's triggering on

**Review by lnkuiper — APPROVED** [review]
LGTM

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
