### PR TITLE
Common aggregate expression

### PR DESCRIPTION
**Pull request by aris-koning**
Introducing a new optimizer class `CommonAggregateOptimizer` that optimizes duplicate aggregate expressions by rewritting simultaneously the column indices in a `LogicalProjection` and the expressions in a `LogicalAggregate`.

A prototypical application of this rewrite rule looks like:

```
select sum(i), sum(i) from foo;
PROJECTION[#0, #1](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0)](GET(foo)))
=>
PROJECTION[#0, #0](AGGREGATE_AND_GROUP_BY[SUM(0.0)](GET(foo)))
```

It is still a work in progress. It does not yet work on groups in a group by expression:

```
select i, sum(i), i, sum(i) from foo group by i;
PROJECTION[#0, #1, #0, #2](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0)][0.0](GET(foo)
=>
PROJECTION[#0, #1, #0, #1](AGGREGATE_AND_GROUP_BY[SUM(0.0)][0.0](GET(foo)
```

 And I am not sure yet about other cases that should use this optimizing mechanism outside the combination of a `LogicalProjection` and a `LogicalAggregate`. And of course I need to add some unit tests for it. But at leas my work can now be tracked.

PS Somewhere along the line, I have had the need for a `const` version of the `Expression::Copy()` method. Then I was thinking, a method with such a name and purpose should imply `const` membership. So I have changed that for all `Expression` subtypes. I hope everybody agrees on that being a good idea. Let me know otherwise.

### CODE REVIEW

**Comment by aris-koning** [comment]
I think `GROUP BY` expressions are working in their simplest form:

```
select i, sum(i), i, sum(i) from foo group by i;
PROJECTION[#0, #1, #0, #2](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0)][0.0](GET(foo)
=>
PROJECTION[#0, #1, #0, #1](AGGREGATE_AND_GROUP_BY[SUM(0.0)][0.0](GET(foo)
```

Next step is to get `GROUP BY ... HAVING ...` to work:

```
select i, sum(i), i, sum(i) from foo group by i having sum(i) < 80;
PROJECTION[#1, #0, #2, #0](FILTER[#3<40](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0), SUM(0.0)][0.0](GET(foo))))
=>
PROJECTION[#1, #0, #1, #0](FILTER[#1<40](AGGREGATE_AND_GROUP_BY[SUM(0.0)][0.0](GET(foo))))
```

**Comment by hannesmuehleisen** [comment]
I see lots of printout in the logs
````
BEFORE OPTIMIZING:
PROJECTION[#0](AGGREGATE_AND_GROUP_BY[COUNT(*)](GET(integers)))
AFTER OPTIMIZING:
PROJECTION[#0](AGGREGATE_AND_GROUP_BY[COUNT(*)](GET(integers)))
````
Could you please fix that?

**Comment by aris-koning** [comment]
> I see lots of printout in the logs
> 
> ```
> BEFORE OPTIMIZING:
> PROJECTION[#0](AGGREGATE_AND_GROUP_BY[COUNT(*)](GET(integers)))
> AFTER OPTIMIZING:
> PROJECTION[#0](AGGREGATE_AND_GROUP_BY[COUNT(*)](GET(integers)))
> ```
> 
> Could you please fix that?

Sorry about that. I'll make sure to remove it with the upcoming push.

**Comment by Mytherin** [comment]
Hey Aris, soon I will merge my branch (subqueryflatten) into the default. I have changed a number of things in how the binder works (as the old binder was quite broken wrt subqueries). I suspect this will give you some conflicts, however, I think the new binder will actually make this task significantly easier.

In the old binder, "BoundExpressions" were generated to refer to groups and aggregates. The same for the ORDER BY clause and such. This gave a bunch of problems and was generally quite finicky to work with, as the BoundExpression relies on the index of the column in the result, which is not very "logical" and more "physical". BoundExpression is still used, but **only** in the Physical phase.

Instead, the new binder generates "BoundColumnRefExpression" to refer to groups, aggregates, window functions, etc. The way it works is that before, only the LogicalGet (tables) had table indexes. Now, also the LogicalAggregate has a "group_index" and an "aggregate_index". The LogicalProjection has a "projection_index" and the LogicalWindow has a "window_index".

I suspect in the new binder it will be much easier to remove duplicate aggregates, because now you can look for BoundColumnRefExpressions that point to the "aggregate_index" and aggregate # instead of having to decipher BoundExpressions.

I'm not sure yet when I will merge, but hopefully this week or weekend. Let me know if you have any questions/doubts.

**Comment by aris-koning** [comment]
@Mytherin sure thing. Sound like some good progress. Does it have any influence on aliases?

For my side, I'm pretty sure I can get the following chain of operators
```
PROJECTION FILTER AGGREGATE_AND_GROUP_BY 
```
to work this week based on the old `BoundExpression`s. I am not suspecting much problems with that pipeline of operators. Once you have pushed, I'll try to merge your stuff as soon as possible in my pull request. If there are any merge problems, we'll work it out then.

I am a bit more suspicious about window functions. As far as I can tell from the plan generator, the most generic chain of operators that I need to deal with looks like this

```
PROJECTION WINDOW FILTER AGGREGATE_AND_GROUP_BY 
```
But I don't feel completely comfortable with the typical 'syntax' of a generated plan involving a window function. But that's probably for next week.

**Comment by Mytherin** [comment]
Aliases should all be handled inside the binder, i.e. after the binding phase you should not need to consider aliases at all. 

I think in the new setup you can do this without having to make special cases for any operators. 

Suppose in we have this query:

`SELECT SUM(i)+SUM(i) FROM integers;`

This will be planned as `GET() -> AGGR(SUM(#0.0), SUM(#0.0)) -> PROJ((#1.0)+(#1.1))`

(Where `#0.0` is a BoundColumnRef pointing to `"i"`, and `"#1.0"` and `"#1.1"` are BoundColumnRefs pointing to the aggregates).

When removing a common aggregate, it should suffice to rewrite the references, i.e. if we remove the second aggregate we can rewrite all BoundColumnRefs `"#1.1"` to BoundColumnRefs `"#1.0"`. This will give the following query:

`GET() -> AGGR(SUM(#0.0)) -> PROJ((#1.0)+(#1.0))`

Note that the table_index is unique per query, hence just looking for "all BoundColumnRefs with the binding `"#1.1"`will find references to that aggregate, and then rewriting them to reference the common aggregate should suffice.

In the old case this was significantly more difficult because the BoundExpressions were messy to work with, relying on the position in the physical plan. This was also part of the reason for no longer creating any BoundExpressions until the actual physical planning phase, where the ColumnBindingResolver will turn BoundColumnRefs into BoundExpressions.

**Comment by aris-koning** [comment]
@Mytherin 
I have rebased my stuff on the latest master branch that includes the new subquery stuff. I am trying to get my head around the new boundcolumnref administration:

`select sum(i), j, sum(i), j from foo group by j having j < 10;`

this is how my plan looks like

`PROJECTION[#[3.0], #[2.0], #[3.1], #[2.0]](FILTER[#[2.0]<10](AGGREGATE_AND_GROUP_BY[SUM(#[0.1]), SUM(#[0.1])][#[0.0]](GET(foo))))`

I am a little confused about the workings of the actual table indices. for instance why is there a jump in table indices 0.x, (where is 1.x) 2.x 3.x and to which intermediate tables are the (left) indices pointing exactly?

**Comment by Mytherin** [comment]
Hey Aris,

The "table indexes" don't refer just to tables anymore, but to any operator that produces data that can be referenced. This means that not just the LogicalGet has a table index, but also the LogicalProjection. The LogicalAggregate actually has **two** indexes. The **group index** and the **aggregate index**.

Let's look at your query:

```sql
select sum(i), j, sum(i), j from foo group by j having j < 10;
```

The operator tree will look like this:

PROJECTION
-> FILTER
----> AGGREGATE
---------> GET

The generated table indexes will be:
**GET:** [0]
**PROJECTION:** [1]
**AGGREGATE:** **GROUP** [2], **AGGREGATE** [3]
**WINDOW:** [4] (but not used, only if there are WINDOW expressions)

Table indexes are generated in simple ascending order, and there can be unused or unreferenced table indices generated as well. The reason table index [1] is not shown in the plan is because there is nothing that refers to the output of the **PROJECTION**, if you would add an **ORDER** there would be a reference to the table index [1]. 

It's important to note that table indexes cannot be used all over the plan. After an **AGGREGATE** operation, for example, *all table indexes below it in the plan cannot be referenced anymore.* This means that referencing table index **[0]** in the **FILTER** (or in the **PROJECTION** for that matter) will lead to an error when resolving the bindings. Instead, the **FILTER** can only refer to index **[2]** or **[3]** (the indices of the **AGGREGATE** node). 

If we look a bit closer at the plan we can see what exactly the column bindings represent:

------> AGGREGATE [SUM(#[0.1]), SUM(#[0.1])][#[0.0]]
**SUM** over the second column of **foo** (i), GROUP BY the first column of **foo** (j)

---> FILTER [#[2.0]<10]
**FILTER** on the first group of the aggregate

->PROJECTION [#[3.0], #[2.0], #[3.1], #[2.0]]
**PROJECT** the first aggregate, the first group, the second aggregate, the first group

This should simplify your life a bit because if you are looking for any reference to an aggregate, in this case it will have table index **[3]** (which is the **aggregate_index** in the **LogicalAggregate**).

**Comment by aris-koning** [comment]
@Mytherin 
I think I have the `ca_optimizer` working using the `BoundColumnRef` assuming it passes the current running travis build. Now I was looking at Window functions. Take for instance this query
```
select j, avg(i) over (partition by j) from foo;
```
It produces the following plan (as far as I can tell from the `LogicalProjection::ToString()` method):
```
PROJECTION[#[0.0], #[4.0]](WINDOW[WINDOW](GET(foo)))
```

**So where is the aggregate?**

Furthermore performing the following query, gives me an error
```
select j, avg(i), avg(i) over (partition by j) from foo;

Query Error: Unknown: column j must appear in the GROUP BY clause or be used in an aggregate function
Error: Unknown error
```
Is that a bug or correct behavior? On which dbs do you base your window function logic on?

**Comment by Mytherin** [comment]
@aris-koning 

**Q1**
```sql
select j, avg(i) over (partition by j) from foo;
```

This query does not have an aggregate; it has a projection and a window function.```AVG``` looks like an aggregate function but it is not, it is part of the window function.  Window functions are different from aggregate functions because they do not change the cardinality of the result set, i.e. the cardinality of this query will be the cardinality of ```foo```.

You **can** however reference an aggregate from **inside** a window function, e.g. the following is valid SQL:

```sql
select j, avg(sum(i)) over (partition by j) from foo group by j;
```

The aggregate is ```SUM(i)```, the window function is ```AVG(#aggr) over partition by #group```.

**Q2**
```sql
select j, avg(i), avg(i) over (partition by j) from foo;
```

This query fails correctly. Note that you have an actual aggregate here (```avg```) which turns the query into an aggregate; however, you are not grouping by anything. Any reference to ```i``` or ```j``` correctly throws this error. Note that this query will also fail:

```sql
select avg(i), avg(i) over () from foo;
```

Because the window function references ```i``` inside the window function ```avg```, and ```i``` is neither a grouping column nor an aggregate.

**Comment by Mytherin** [comment]
Ah forgot to mention, the window functions are based on PostgreSQL but we also have test cases from SQL server for them (not sure if we have the SQLite test cases for window functions, I don't think we do).

**Comment by aris-koning** [comment]
I hate window functions.\

**Comment by Mytherin** [comment]
Haha, they are a bit difficult to wrap your head around but they can be quite useful from a user perspective. Anyway, I don't think you really need to consider window functions for this issue. Eliminating duplicate window functions is a separate optimization in my opinion.

**Comment by aris-koning** [comment]
Thanks for the explaination. And I was just kidding of course. I just have to understand there is more to it then I thought there was. But let me then rephrase my question in my practical context: what would be a nice query involving window functions and aggregates to check if my ca_optimizer is handling it correctly.

**Comment by Mytherin** [comment]
Perhaps something like this:

```sql
CREATE TABLE vals(i INTEGER, j INTEGER);
INSERT INTO vals VALUES (1, 1), (2, 2), (3, 3), (NULL, NULL);
SELECT i, SUM(j), AVG(SUM(j)+SUM(j)) OVER (PARTITION BY SUM(j) ORDER BY SUM(j)) FROM integers GROUP BY i ORDER BY i;
```
Should return:
```
 i | sum |        avg         
---+-----+--------------------
   |     |                   
 1 |   1 | 2.0000000000000000
 2 |   2 | 4.0000000000000000
 3 |   3 | 6.0000000000000000
(4 rows)
```

The original plan looks like this:

```
PROJECTION[i, SUM, Unknown]
    WINDOW[WINDOW]
        AGGREGATE_AND_GROUP_BY[SUM(j), SUM(j), SUM(j), SUM(j), SUM(j)][i]
            GET(integers)
```

**Comment by aris-koning** [comment]
Thanks for the explaination. And I was just kidding of course. I just have to understand there is more to it then I thought there was. But let me then rephrase my question in my practical context: what would be a nice query involving window functions and aggregates to check if my ca_optimizer is handling it correctly.

> Perhaps something like this:
> 
> ```sql
> CREATE TABLE vals(i INTEGER, j INTEGER);
> INSERT INTO vals VALUES (1, 1), (2, 2), (3, 3), (NULL, NULL);
> SELECT i, SUM(j), AVG(SUM(j)+SUM(j)) OVER (PARTITION BY SUM(j) ORDER BY SUM(j)) FROM vals GROUP BY i ORDER BY i;
> ```
> 
> Should return:
> 
> ```
>  i | sum |        avg         
> ---+-----+--------------------
>    |     |                   
>  1 |   1 | 2.0000000000000000
>  2 |   2 | 4.0000000000000000
>  3 |   3 | 6.0000000000000000
> (4 rows)
> ```
> 
> The original plan looks like this:
> 
> ```
> PROJECTION[i, SUM, Unknown]
>     WINDOW[WINDOW]
>         AGGREGATE_AND_GROUP_BY[SUM(j), SUM(j), SUM(j), SUM(j), SUM(j)][i]
>             GET(integers)
> ```

Thanks that really helps I'll take a look at it.

**Comment by Mytherin** [comment]
Hey Aris, just wondering if you know how to use our unittest framework, since I see you haven't created any tests yet. You can run unittests using the `build/debug/test/unittest` program, or specific tests by passing a test name (e.g. `build/debug/test/unittest "Test name"`). The tests are located in the `test` directory, you can create new tests there as well. Creating tests is relatively straightforward, just look at one of the existing tests (e.g. `test/sql/simple/test_groupby.cpp`) and copy that.

**Comment by aris-koning** [comment]
Yes, I wanted to ask you about that. I have noticed that one of the test utility functions is called  `ParseLogicalPlan`. But as far as I can tell it is not used anywhere.  The way I wanted to test this is basically (string) comparing the optimized plans to some expectation. So Ideally I would like to stuff a couple of a aggregate queries into this function and then check the output of the plan's `ToString` method. Should that work?

**Comment by Mytherin** [comment]
Yeah that test function was created to test optimizers before, but then the infrastructure around optimizers changed and the function was not updated. I think the ToString() method is not a good way of checking it as it ties you down to how the plans are printed. Better to inspect the actual plans, then if something internally breaks them the test cases can be updated more easily. I will update the infrastructure to test the optimizers today, then you can use that infrastructure to write a test case as well.

**Comment by aris-koning** [comment]
Sounds great. Let me know once I can use it.

**Comment by Mytherin** [comment]
I added tests for the current CSE optimizer, you can find them in `test/optimizer/test_cse_optimizer.cpp`. Your tests can have a similar format.

**Comment by aris-koning** [comment]
Well I have put this thing to the test and it has survived it.

I think it is time to merge this one.

**Comment by Mytherin** [comment]
Yes I think it is ready to merge. Looking at the code everything looks fine. I will merge it in.

**Comment by aris-koning** [comment]
@Mytherin 
It was my pleasure!
I am really busy the next couple of months. But I hope to pick something up again after that. I hope there is something on the kernel level just to give me some practical experience with your low level architecture.

**Comment by Mytherin** [comment]
Looking forward to it! Thanks for your help. It's great to have someone (sort of) external work on the project and have some practice with handling contributors/pull requests. And of course your contribution is much appreciated as well.

**Pull request merged**
