### PR TITLE
jemalloc "extension" for Linux

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR adds the jemalloc "extension", that we will for 64-bit Linux builds. The default allocator on Linux creates memory fragmentation, which eventually causes allocations to fail (see #3969). jemalloc should do a better job at this. We do not use jemalloc as a global allocator, only our `Allocator` class calls into jemalloc.

I've put "extension" between quotation marks, because jemalloc can only be loaded statically (no `INSTALL`/`LOAD` possible). We've chosen to do this because switching between allocators dynamically causes a bunch of issues with blocks that are allocated while the switch happens.

This was much more work than expected, because I've converted jemalloc to C++, and wrapped it in a namespace to prevent conflicts. jemalloc also has a bunch of platform-specific optimizations, which I had to rip out to make it portable.

Somehow this has caused a regression in TPC-DS q72 in my CI runs, which I cannot reproduce locally. Not sure what is going on there.

Happy to receive any feedback!

P.S.: jemalloc works on macos too, but not (yet) on windows, but we will probably not include it on macos since the default allocator is OK

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great! 

A few questions/comments:

* Should we perhaps enable jemalloc by default on Linux, or do you think this will likely cause problems?
* Does it work on GCC-4.9?
* `jemalloc` is not yet integrated into the Python/R clients, correct? Could you perhaps integrate it into the `package_build.py` script as well?

**Comment by lnkuiper** [comment]
Enabling by default on Linux seems like a good idea, then no one has to deal with the default Linux allocator, ever.

I'll try GCC 4.9 and integrate in the Python/R clients.

Thanks for the review!

**Comment by lnkuiper** [comment]
Have tried manually, and GCC 4.9 seems to be happy. I also added to the Python/R builds, let's wait what and see what CI does

**Comment by lnkuiper** [comment]
Thanks for the tip!

**Comment by lnkuiper** [comment]
R is now happy! Think this is done (python test failures should be unrelated, I think it failed to install arrow)

**Comment by Mytherin** [comment]
On closer inspection the Python failure does not appear to be unrelated. The arrow build failure is a warning - the actual error is a crash in the tests:

```
    + sh -c 'python -m pytest /project/tests/fast'
/bin/bash: line 138:  1482 Floating point exception(core dumped) env HOSTNAME=9dd84a299eda SSL_CERT_FILE=/opt/_internal/certs.pem OLDPWD=/ LC_ALL=en_US.UTF-8 LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib/dyninst PATH=/tmp/tmp.YcG2sL9cLR/venv/bin:/opt/python/cp37-cp37m/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin *** LANG=en_US.UTF-8 CIBUILDWHEEL=1 AUDITWHEEL_ARCH=i686 DEVTOOLSET_ROOTPATH=/opt/rh/devtoolset-10/root HOME=/root SHLVL=2 LANGUAGE=en_US.UTF-8 AUDITWHEEL_PLAT=manylinux2014_i686 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig AUDITWHEEL_POLICY=manylinux2014 _=/usr/bin/env PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_ROOT_USER_ACTION=ignore PIP_CONSTRAINT=build-constraints.txt sh -c 'python -m pytest /project/tests/fast'
##[endgroup]
##[error]Command ['sh', '-c', 'python -m pytest /project/tests/fast'] failed with code 136. 
```

This appears to be triggered in the 32-bit build of Python. I think the reason for this is that the 32-bit build runs the setup.py script on a 64-bit architecture, so `jemalloc` is incorrectly included (see https://github.com/duckdb/duckdb/blob/master/.github/workflows/Python.yml#L198). The script runs `python setup.py sdist` to get a list of all source files, and then passes those source files to cibuildwheel which does the actual building inside separate VMs.

I see two possible solutions to this:
* We can either disable jemalloc through an environment variable on the cibuildwheel build CI action when running for `i686`
* We can disable jemalloc through an `#Ifdef` in the actual code so that it will not be used for 32-bit systems even if it is compiled in

**Comment by lnkuiper** [comment]
Sorry about that, shows you just how much I know about our Python builds.

Checking bitness is something that is really annoying to do in conditional directives. Especially if you want to do so in a portable way. For some reason it is not possible to use `sizeof` in a conditional directive.

Anyways, we can select the appropriate functions at compile time, which I've implemented like this:
```c++
#if defined(BUILD_JEMALLOC_EXTENSION) && !defined(WIN32)
static constexpr allocate_function_ptr_t GetAllocateFunction() {
	return sizeof(data_ptr_t) == 4 ? Allocator::DefaultAllocate : JEMallocExtension::Allocate;
}

static constexpr free_function_ptr_t GetFreeFunction() {
	return sizeof(data_ptr_t) == 4 ? Allocator::DefaultFree : JEMallocExtension::Free;
}

static constexpr reallocate_function_ptr_t GetReallocateFunction() {
	return sizeof(data_ptr_t) == 4 ? Allocator::DefaultReallocate : JEMallocExtension::Reallocate;
}

Allocator::Allocator() : Allocator(GetAllocateFunction(), GetFreeFunction(), GetReallocateFunction(), nullptr) {
}
#else
Allocator::Allocator()
    : Allocator(Allocator::DefaultAllocate, Allocator::DefaultFree, Allocator::DefaultReallocate, nullptr) {
}
#endif
```

Fingers crossed for the CI now :)

**Comment by Mytherin** [comment]
We have code that does it here: https://github.com/duckdb/duckdb/blob/2507243a2c0fc8014a4c9485707ede9f08f852d8/src/function/table/version/pragma_version.cpp#L57

**Comment by Mytherin** [comment]
Ah but the current implementation is fine as well.

**Comment by lnkuiper** [comment]
Seems like the current implementation is still causing jemalloc to be used in one of the python CI runs. Not sure why. I will try your approach instead

**Comment by lnkuiper** [comment]
Same issue after changing to your approach. Seems like intptr_max == int64_max despite being 32bit? Or I am misunderstanding something.

Might need to switch to the env variable approach

**Comment by Mytherin** [comment]
It could be that the crash is happening in the jemalloc start-up code or so, which might still break even if none of the code is actually used as long as it is compiled in. Perhaps excluding the code entirely is a better idea indeed

**Comment by lnkuiper** [comment]
All green! @Mytherin

**Comment by Mytherin** [comment]
Awesome! Thanks for all the hard work :)

**Pull request merged**
