### PR TITLE
R: Enable more DBItest tests

### PR DESCRIPTION
**Pull request by krlmlr**
Part of a series of fixes for DBItest.

### CODE REVIEW

**Comment by krlmlr** [comment]
Looks like DBItest fails to test some of the new branches. The code has been copied from RSQLite, should be good.

**Comment by krlmlr** [comment]
@hannesmuehleisen: Can you please take a look? Next in line: `dbAppendTable()`, currently only on my machine. In the meantime I'll refactor DBItest so that it tests most of `dbBind()` for single-row parameters, so that we can work incrementally towards multi-row support.

**Comment by hannesmuehleisen** [comment]
Looks good to me!

**Review by Mytherin — APPROVED** [review]

**Comment by krlmlr** [comment]
Happy to send more after this is merged.

**Pull request merged**
