### PR TITLE
 [Python]  Allow create spark dataframe using Polars or PyArrow

### PR DESCRIPTION
**Pull request by mariotaddeucci**
Officially, pyspark does not have support to read Polars or PyArrow data.

This is an amazing feature available in the python API. 
On the other hand, this breaks the pyspark API contract.

I'd actually like to see this feature available, but I don't know if it makes sense.
So, does it make sense to allow `createDataFrame` to support PyArrow and Polars?

### CODE REVIEW

**Comment by Tishj** [comment]
I don't think we're interested in this, because as you mentioned, this would break compatibility with Spark.
I'm curious, why are you interested in this functionality?

The Spark API is not a whole lot more than a wrapper on top of our existing relational API, the purpose of the Spark API is only to create a bridge between existing spark code and duckdb

**Comment by Mytherin** [comment]
Thanks for the PR! As mentioned breaking Spark compatibility is not desirable here. We could perhaps consider adding an orthogonal API call for this, but perhaps this is already possible by combining existing APIs. If you have any concrete ideas here feel free to open a discussion or a separate PR.

**Comment by djouallah** [comment]
it is coming soon to Pyspark API
https://github.com/apache/spark/pull/46529

**Comment by mariotaddeucci** [comment]
@djouallah Thanks, I subscribe the PR so after it releases I'll reopen it filtering Arrow dataset

**Pull request closed without merging**
