### PR TITLE
Override git hash / git version

### PR DESCRIPTION
**Pull request by carlopi**
Some shuffling around the CMake code to make so it's possible to fully specify, via Makefile of CMake variables, the value that allows to compute DUCKDB_VERSION, DUCKDB_[MAJOR|MINOR|PATCH]_VERSION and GIT_COMMIT_HASH.

This is useful when building from sources that are NOT a git repository.

Usage is like:

Providing `OVERRIDE_GIT_DESCRIBE` corresponding to `git describe --tags --long:
```
$ git describe --tags --long
v0.10.0-843-g09ea97d0a9
$ OVERRIDE_GIT_DESCRIBE=v0.10.0-843-g09ea97d0a9 GEN=ninja make
$ ./build/release/duckdb
v0.10.1-dev843 09ea97d0a9

D PRAGMA version;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.1-dev843  │ 09ea97d0a9 │
└─────────────────┴────────────┘
```
Providing no OVERRIDE_GIT_DESCRIBE will be equivalent to providing OVERRIDE_GIT_DESCRIBE equal to `$(git describe --tags --long)`, as per computed by the CMake code:
```
$ GEN=ninja make
$ ./build/release/duckdb
v0.10.1-dev843 09ea97d0a9
```
Providing nonsensical OVERRIDE_GIT_DESCRIBE is also possible:
```
$ OVERRIDE_GIT_DESCRIBE=v3.0.0-0-gdead00beef GEN=ninja make
carlo@ScroogeMcDuck duckdb % ./build/release/duckdb                                   
v3.0.0 dead00beef
```

Note that providing broken values is checked best effort, use the override with care.

This PR should be particularly useful for packagers of duckdb (see for example https://github.com/Mause/duckdb_ppa), given they might not have `git` available or they might prefer to reduce download size by avoiding cloning the repository history.

I demo the usage of this in the changes to .github/workflows/Main.yml, where the first job compute the git descriptions and pass it on to the other jobs to use.

This should supersede https://github.com/duckdb/duckdb/pull/10718, if @xhochy could check whether this will works on their setup it would be amazing.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

**Comment by a-n-n-a-l-e-e** [comment]
thanks! will this work with the full commit sha rather than the truncated one provided with the git log? eg:

```bash
#!/bin/bash
tag=$(curl -s "https://api.github.com/repos/duckdb/duckdb/releases/latest" | jq -r .tag_name)
sha=$(curl -s "https://api.github.com/repos/duckdb/duckdb/git/ref/tags/$tag" | jq -r .object.sha)

# OVERRIDE_GIT_DESCRIBE=v0.10.0-0-20b1486d1192f9fbd2328d1122b5afe5f1747fce GEN=ninja make
OVERRIDE_GIT_DESCRIBE="${tag}-0-${sha}" GEN=ninja make
```

is there a way to set this for the python build as well?

**Comment by carlopi** [comment]
I was cleaning up this PR slightly, with your provided example it will error with:
```
$ OVERRIDE_GIT_DESCRIBE="${tag}-0-${sha}" GEN=ninja make
CMake Error at CMakeLists.txt:262 (message):
  Provided OVERRIDE_GIT_DESCRIBE
  'v0.10.0-0-20b1486d1192f9fbd2328d1122b5afe5f1747fce' do not match supported
  versions, either fully specified 'vX.Y.Z-N-gGITHASH123' or version only
  'vX.Y.Z'
```
while doing (the `g` is relevant):
```
$ OVERRIDE_GIT_DESCRIBE="${tag}-0-g${sha}" GEN=ninja make
$ ./build/release/duckdb
carlo@ScroogeMcDuck duckdb % ./build/release/duckdb
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D 
```
After the PR lands will shorten the hash to 10, making uniform.

---

Python side it should be similar, but I need to review the build instructions there.

**Comment by carlopi** [comment]
Here the PR implementing it: https://github.com/duckdb/duckdb/pull/10994

**Comment by xhochy** [comment]
Sorry for not looking into this earlier. It dropped from my list 🙈 Tge solution looks good. I will try it out on the next release and will report back. Thanks!

**Comment by carlopi** [comment]
Great, thanks!

**Pull request merged**
