### PR TITLE
A refactoring around FileSystem

### PR DESCRIPTION
**Pull request by omo**
Could you take a look?
This series of commits are for #2257 and also addresses the problem discussed at #2256.
Thanks for your help!

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks a lot for the PR! This looks great. I am rerunning the tests as there seemed to have been some problems unrelated to this PR, but I think this is ready to merge.

**Comment by omo** [comment]
Great! Thanks for the review Mark!

**Comment by omo** [comment]
Not sure why this one fails while other PRs seem to be fine. Rebased as a random fix attempt.

**Comment by Mytherin** [comment]
Looks like random noise to me, those tests have been acting a bit weird for a while. Thanks again!

**Pull request merged**
