### PR TITLE
Move Windows workflows from windows-latest (= 2022) to 2019

### PR DESCRIPTION
**Pull request by carlopi**
Connected to https://github.com/actions/runner-images/issues/10004#issuecomment-2153305472

### CODE REVIEW

**Comment by carlopi** [comment]
It's not obvious if this is going to work, waiting for CI to actually test this.

**Comment by carlopi** [comment]
This fails earlier, basically at the very end of the Build step. Unsure how to read that, but this is not functional at this moment.

**Comment by Mytherin** [comment]
I've tried this as well but no cigar - this work-around is more promising (but Windows extensions still fails) - https://github.com/duckdb/duckdb/compare/feature...Mytherin:duckdb:windows

**Comment by Mytherin** [comment]
Opened a PR here - https://github.com/duckdb/duckdb/pull/12447

**Comment by carlopi** [comment]
Windows extension problem can be solved by either: https://github.com/duckdb/duckdb/pull/12426 (avoid hardcoding) or https://github.com/duckdb/duckdb/pull/12402 (detection), both are better than hardcoding the version to a random one.

**Pull request closed without merging**
