### PR TITLE
Implement substring slice semantics from SQLite

### PR DESCRIPTION
**Pull request by hawkfish**
New work in #193.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! We should also add an alias from "substring" to "substr", which is what the function is called in SQLite.

**Comment by hawkfish** [comment]
Should I add the alias before we merge?  Also, it looks like the failure was unrelated to my changes (the `age` function).

**Comment by Mytherin** [comment]
Would be nice to do it with this PR, but not essential. The failure with the Age function indeed seems unrelated, as does the Arrow failure. The SQLancer failure is related but is a matter of teaching SQLancer about the new error message.

Some more test cases would be nice, including triggering the negative length error and some non-inlined strings (i.e. strings with strlen > 12). Otherwise I think the PR is fine.

**Comment by hawkfish** [comment]
The alias was already there, but I added a test for the negative length.

**Comment by hawkfish** [comment]
The remaining error is caused by a change in the error message not being reflected in `sqlancer`.  How should we make changes like that?

**Comment by Mytherin** [comment]
Could you send a PR with the new error message to [this repo](https://github.com/hannesmuehleisen/sqlancer/pull/2)? That should fix the problem.

**Comment by hawkfish** [comment]
Done. But I haven't tested it on my OSX box - is there documentation on how to do that?

**Comment by Mytherin** [comment]
I'm not exactly a Java expert, I haven't ran any of this locally either :)

The best documentation is probably the travis entry:

```
    - os: linux
      dist: bionic
      name: SQLancer
      if: (branch !~ ^r/.*$ AND head_branch !~ ^r/.*$) AND ((type = push AND branch = master) OR type = pull_request OR tag =~ /^v\d+\.\d+\.\d+$/)

      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10 openjdk-11-jdk openjdk-11-jre

      env:
        - JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64'
        - CC=gcc-10
        - CXX=g++-10
        - MAKEFLAGS=

      script:
        - export PATH=$JAVA_HOME/bin:$PATH
        - mkdir -p build/release
        - python3 scripts/amalgamation.py
        - (cd build/release && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DJDBC_DRIVER=1 -DBUILD_UNITTESTS=FALSE -DAMALGAMATION_BUILD=1 ../.. && travis_wait 30 cmake --build .)
        - java -cp build/release/tools/jdbc/duckdb_jdbc.jar org.duckdb.test.TestDuckDBJDBC
        - git clone https://github.com/hannesmuehleisen/sqlancer.git
        - (cd sqlancer && mvn package -q -DskipTests)
        - cp build/release/tools/jdbc/duckdb_jdbc.jar sqlancer/target/lib/duckdb_jdbc-*.jar
        - java -jar sqlancer/target/SQLancer-*.jar --num-queries 1000 --num-threads 1 --random-seed 0 --timeout-seconds 600 duckdb
```

But in this case I think it won't be necessary to run it locally. Usually SQLancer reports on the failing queries and makes it obvious why it is failing, so it's reproducible elsewhere.

**Pull request merged**
