### PR TITLE
Add support for parallel scanning of pandas data frames

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds support for parallel scans of pandas dataframes, so queries running with pandas dataframes as a source can also benefit from intra-pipeline parallelism.

### CODE REVIEW

**Comment by Mytherin** [comment]
@Alex-Monahan @tdoehmen

**Comment by Mytherin** [comment]
Simple benchmark running TPC-H Q1 on SF1 from a pandas dataframe:

|     threads     | Timing (s) |
|-----------------|------------|
| Single-Threaded | 0.60       |
| 8 Threads       | 0.11s      |

Script:
```python
import duckdb
import time

con = duckdb.connect()
df = con.execute("select * from read_csv_auto('lineitem-colname.csv')").fetchdf()
con.register('lineitem_df', df)

start = time.time()
print(con.execute('''SELECT
     l_returnflag,
     l_linestatus,
     sum(l_quantity) AS sum_qty,
     sum(l_extendedprice) AS sum_base_price,
     sum(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
     sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
     avg(l_quantity) AS avg_qty,
     avg(l_extendedprice) AS avg_price,
     avg(l_discount) AS avg_disc,
     count(*) AS count_order
 FROM
     lineitem_df
 WHERE
     l_shipdate <= CAST('1998-09-02' AS date)
 GROUP BY
     l_returnflag,
     l_linestatus
 ORDER BY
     l_returnflag,
     l_linestatus;
 ''').fetchdf())
end = time.time()
print('Single threaded ', end - start)

con.execute('pragma threads=8')

start = time.time()
print(con.execute('''SELECT
     l_returnflag,
     l_linestatus,
     sum(l_quantity) AS sum_qty,
     sum(l_extendedprice) AS sum_base_price,
     sum(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
     sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
     avg(l_quantity) AS avg_qty,
     avg(l_extendedprice) AS avg_price,
     avg(l_discount) AS avg_disc,
     count(*) AS count_order
 FROM
     lineitem_df
 WHERE
     l_shipdate <= CAST('1998-09-02' AS date)
 GROUP BY
     l_returnflag,
     l_linestatus
 ORDER BY
     l_returnflag,
     l_linestatus;
 ''').fetchdf())
end = time.time()
print('8 Threads ', end - start)
```

Data generation (needs TPC-H extension):
```sql
CALL dbgen(sf=1);
COPY lineitem TO 'lineitem-colname.csv' (HEADER);
```

**Comment by hannesmuehleisen** [comment]
Also CC @tdoehmen

**Comment by Mytherin** [comment]
Some profiling output for those interested:

```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 5.92s         ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│          EXECUTE          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
│           #1 ASC          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│       HASH_GROUP_BY       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
│          sum(#2)          │
│          sum(#3)          │
│          sum(#4)          │
│          sum(#5)          │
│          avg(#6)          │
│          avg(#7)          │
│          avg(#8)          │
│        count_star()       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (1.60s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        l_returnflag       │
│        l_linestatus       │
│         l_quantity        │
│      l_extendedprice      │
│             #4            │
│ *(#4, +(1.000000, l_tax)) │
│         l_quantity        │
│      l_extendedprice      │
│         l_discount        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.40s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        l_returnflag       │
│        l_linestatus       │
│         l_quantity        │
│      l_extendedprice      │
│   *(l_extendedprice, -(1  │
│   .000000, l_discount))   │
│           l_tax           │
│         l_discount        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.40s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
│             #2            │
│             #3            │
│             #4            │
│             #5            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.04s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ l_shipdate<=1998-09-02 00 │
│           :00:00          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.11s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #4            │
│             #5            │
│             #6            │
│             #7            │
│             #8            │
│             #9            │
│            #10            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59986052         │
│          (0.03s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│        PANDAS_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_quantity        │
│      l_extendedprice      │
│         l_discount        │
│           l_tax           │
│        l_returnflag       │
│        l_linestatus       │
│         l_shipdate        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59986052         │
│          (3.29s)          │
└───────────────────────────┘
```

It seems that Pandas string conversions are still (relatively) expensive, but not crazily so. I also just realized the pandas scan doesn't do projection pushdown yet, will add that next.

**Comment by Mytherin** [comment]
Now with projection pushdown:

```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         Total Time: 4.14s         ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│          EXECUTE          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
│           #1 ASC          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│       HASH_GROUP_BY       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
│          sum(#2)          │
│          sum(#3)          │
│          sum(#4)          │
│          sum(#5)          │
│          avg(#6)          │
│          avg(#7)          │
│          avg(#8)          │
│        count_star()       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             4             │
│          (1.66s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        l_returnflag       │
│        l_linestatus       │
│         l_quantity        │
│      l_extendedprice      │
│             #4            │
│ *(#4, +(1.000000, l_tax)) │
│         l_quantity        │
│      l_extendedprice      │
│         l_discount        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.45s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        l_returnflag       │
│        l_linestatus       │
│         l_quantity        │
│      l_extendedprice      │
│   *(l_extendedprice, -(1  │
│   .000000, l_discount))   │
│           l_tax           │
│         l_discount        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.47s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
│             #2            │
│             #3            │
│             #4            │
│             #5            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.03s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ l_shipdate<=1998-09-02 00 │
│           :00:00          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59142609         │
│          (0.10s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│        PANDAS_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_quantity        │
│      l_extendedprice      │
│         l_discount        │
│           l_tax           │
│        l_returnflag       │
│        l_linestatus       │
│         l_shipdate        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          59986052         │
│          (1.40s)          │
└───────────────────────────┘ 
```

**Comment by Alex-Monahan** [comment]
Great news! Our use case transfers in and out of Pandas frequently, so this is a huge help for us!

**Pull request merged**
