### PR TITLE
Fixing hugeint cast to varint

### LINKED ISSUE #13239: Casting Varint to Varchar prints wrong result
### What happens?

As discussed on Discord, casting Varint to Varchar prints wrong result

image

### To Reproduce

```sql
Select 85070591730234614260976917445211069672::VARINT ;
```

### OS:

Windows 11 x64

### DuckDB Version:

1.0.1-dev3550

### DuckDB Client:

CLI

### Full Name:

Giorgi Dalakishvili

### Affiliation:

Space International

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix: #13239

### CODE REVIEW

**Comment by carlopi** [comment]
Failure is a pre-existing problem in Hugeint::NegateInPlace now uncovered by those tests, I think it should be fixed by applying this diff:
```
diff --git a/src/common/types/hugeint.cpp b/src/common/types/hugeint.cpp
index c701f7cda0..b19a03b70c 100644
--- a/src/common/types/hugeint.cpp
+++ b/src/common/types/hugeint.cpp
@@ -64,7 +64,7 @@ const hugeint_t Hugeint::POWERS_OF_TEN[] {
 
 template <>
 void Hugeint::NegateInPlace<false>(hugeint_t &input) {
-       input.lower = NumericLimits<uint64_t>::Maximum() - input.lower + 1;
+       input.lower = NumericLimits<uint64_t>::Maximum() - input.lower + 1ull;
        input.upper = -1 - input.upper + (input.lower == 0);
 }

```
( `uint64_t(A) + 1` performs signed addition, that is undefined behaviour when overflowing )

**Comment by xuke-hat** [comment]
> ( `uint64_t(A) + 1` performs signed addition, that is undefined behaviour when overflowing )

I've investigated [cppreference](https://en.cppreference.com/w/cpp/language/usual_arithmetic_conversions), it seems 1 will be casted to `uint64_t` before addition.

> Otherwise, one type between T1 and T2 is an signed integer type S, the other type is an unsigned integer type U. Apply the following rules:
> If the integer conversion rank of U is greater than or equal to the integer conversion rank of S, C is U.

**Comment by carlopi** [comment]
@xuke-hat: you are very right. Problem is elsewhere. Sorry everyone (and @pdet in particular) for the noise.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
