### PR TITLE
Maintain names in COLUMNS(*) expression, and allow aliasing multiple columns using {column}

### PR DESCRIPTION
**Pull request by Mytherin**
Implements https://github.com/duckdb/duckdb/discussions/7107
Implements https://github.com/duckdb/duckdb/discussions/7898

This PR makes it so that names are maintained in the COLUMNS(*) expression - instead of replaced by a stringified version of the expression, e.g.:

#### Old Behavior
```sql
D select columns(*)::VARCHAR FROM (select 42 a, 84 b);
┌──────────────────────────────────────┬──────────────────────────────────────┐
│ CAST(unnamed_subquery1.a AS VARCHAR) │ CAST(unnamed_subquery1.b AS VARCHAR) │
│               varchar                │               varchar                │
├──────────────────────────────────────┼──────────────────────────────────────┤
│ 42                                   │ 84                                   │
└──────────────────────────────────────┴──────────────────────────────────────┘
```
#### New Behavior
```sql
D select columns(*)::VARCHAR FROM (select 42 a, 84 b);
┌─────────┬─────────┐
│    a    │    b    │
│ varchar │ varchar │
├─────────┼─────────┤
│ 42      │ 84      │
└─────────┴─────────┘
```

This makes the `COLUMNS(*)` expression more useful and composable - since the names are maintained and predictable. 

#### Regex Extract with Aliases
Previously providing an alias to a `COLUMNS(*)` expression would apply that alias to all expanded expressions, e.g.:

```sql
D SELECT MIN(COLUMNS(*)) AS x FROM (select 42 a, 84 b);
┌───────┬───────┐
│   x   │   x   │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
```

This is not particularly useful since we lose the ability to disambiguate between them. In this PR - we extend this with the ability to extract elements from the supplied regex using the regex extract syntax (`\{digit}`). `\0` can always be used to insert the full column name, even if no regex is supplied. For example:

```sql
-- extract the full column name using \0
D select MIN(COLUMNS(*)) AS "min_\0" FROM (select 42 a, 84 b);
┌───────┬───────┐
│ min_a │ min_b │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
-- extract the first capture group using \1
D select MIN(COLUMNS('([a-zA-Z_]+)[0-9]+')) AS "min_\1" FROM (select 42 first_col42, 84 second_col84);
┌───────────────┬────────────────┐
│ min_first_col │ min_second_col │
│     int32     │     int32      │
├───────────────┼────────────────┤
│            42 │             84 │
└───────────────┴────────────────┘
-- we need to supply a regex to use anything except for \0
D select MIN(COLUMNS(*)) AS "min_\1" FROM (select 42 a, 84 b);
--Binder Error: Only the backslash escape code \0 can be used when no regex is supplied to COLUMNS(*)

```

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
This is amazing!! Super excited for this!

The templating of the alias is fantastic. The syntax you have designed will certainly work great. There is however a very similar syntax that is widely used in dbt, Python's Flask framework, and elsewhere (using the Jinja templating language). Jinja uses two curly braces on either side instead of 1. Ex:
```sql
select 
    MIN(COLUMNS(*)) AS "min_{{column}}"
FROM (select 42 a, 84 b);
```

Would it be better to be distinct from jinja, or to align with it? Up to you of course, I will use it either way! :-) Here are some docs from dbt: https://docs.getdbt.com/docs/build/jinja-macros

**Comment by Mytherin** [comment]
I think being distinct is better since otherwise there will be conflicts potentially. It seems that a single brace works, and I suppose is also likely to continue working since Python similarly supports single braces in f-strings.

**Comment by Mytherin** [comment]
I've changed it now to square brackets, i.e. `[column]`

**Comment by Alex-Monahan** [comment]
That will work great! I did want to float one additional idea over to you in case you like it!

What about using a `%` instead of `[column]`? It is less explicit for sure, but it aligns with the concept of a wildcard that folks will already know. It does mean that folks will have to escape percents to use them directly, and you might not be able to reuse logic from the like operator since it also looks at `_` wildcards. Just an idea!

**Comment by Tishj** [comment]
My proposed solution was
```
select COLUMNS('^(a)[0-9]{1}$') as '$2_postfix' from test;
```
Where `$1` would be equivalent to `[column]` in this PR
Also allowing you to substitute in subsets of the column name with additional capture groups

**Comment by Alex-Monahan** [comment]
I think the `$` could work! Either way works for me - I don't have a strong opinion on square brackets vs. `$`. It looks like the C API uses `$1, $2`, etc. for prepared statements. Other than that, I don't think I have seen dollar signs used for parameters in Python-land, but that's the only area I have used prepared statements in the past.

**Comment by Mytherin** [comment]
> My proposed solution was
> 
> ```
> select COLUMNS('<regex>') as '$2_postfix' from test;
> ```
> 
> Where `$1` would be equivalent to `[column]` in this PR Also allowing you to substitute in subsets of the column name with additional capture groups

I like that idea - our regexes use [backslashes for replacement codes]https://duckdb.org/docs/sql/functions/patternmatching.html#using-regexp_replace), so it would be:

```sql
select 
    MIN(COLUMNS(*)) AS "min_\1"
FROM (select 42 a, 84 b);
┌───────┬───────┐
│ min_a │ min_b │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
```

Or, with a capture group:

```sql
select 
    MIN(COLUMNS('([a-zA-Z]+).*')) AS "min_\2"
FROM (select 42 a42, 84 b84);
┌───────┬───────┐
│ min_a │ min_b │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
```

**Comment by Alex-Monahan** [comment]
The regex idea is interesting! I'm trying to understand the example a little bit better. If I use DuckDB's `regexp_extract` function, I don't see anything returned with a capture group of 2. Could it just be a typo in the example? Sorry to be picky, just trying to squash a bug before it exists! 
```sql
D select regexp_extract('a42','([a-zA-Z]+).*',0) as regex_test;
┌────────────┐
│ regex_test │
│  varchar   │
├────────────┤
│ a42        │
└────────────┘
D select regexp_extract('a42','([a-zA-Z]+).*',1) as regex_test;
┌────────────┐
│ regex_test │
│  varchar   │
├────────────┤
│ a          │
└────────────┘
D select regexp_extract('a42','([a-zA-Z]+).*',2) as regex_test;
┌────────────┐
│ regex_test │
│  varchar   │
├────────────┤
│            │
└────────────┘
```

**Comment by Mytherin** [comment]
Ah yes, it should be \0 and \1 indeed

**Comment by Mytherin** [comment]
I've now changed it to the regex syntax

**Pull request merged**
