### PR TITLE
Fix some fuzzer issues

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes:
1. duckdb/duckdb-fuzzer#290 - Hashing constants should yield a constant vector
2. duckdb/duckdb-fuzzer#294 and duckdb/duckdb-fuzzer#319 - (JSON) `NULL` input should yield all `NULL` output
3. duckdb/duckdb-fuzzer#324 and duckdb/duckdb-fuzzer#861 - Do not use uninitialized memory in reservoir sample

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the fixes! LGTM. I don't quite follow why the explicit handling of `SQLNULL` is necessary in the JSON functions though - shouldn't #3866 handle this as well?

As an aside - generally when we return a constant `NULL` in other functions we return it as a constant vector. e.g. this is the pattern used elsewhere in the code:

```cpp
vec.SetVectorType(VectorType::CONSTANT_VECTOR);
ConstantVector::SetNull(vec, true);
```

**Comment by lnkuiper** [comment]
@Mytherin, somehow I forgot about #3866. The issue here was that the fuzzer found cases where `NULL` was cast to another type. Therefore, the check for default `NULL` handling wasn't triggered. I've changed the check now to:
```c++
child->return_type == LogicalTypeId::SQLNULL ||
    (child->IsFoldable() && ExpressionExecutor::EvaluateScalar(context, *child).IsNull())
```
Now, the tests succeed without needing special `NULL` handling in the JSON functions.

**Comment by Mytherin** [comment]
Thanks - LGTM. The CI failure in `test/sql/types/uuid/test_uuid.test_slow` looks related - could you have a look?

**Comment by lnkuiper** [comment]
The test should be properly fixed now

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
