### PR TITLE
Implement `map_extract_first`

### LINKED ISSUE #14167: Dot notation for json field extraction is no longer working in v1.1.*
### What happens?

`SELECT columns.v4_c6 FROM read_ndjson_auto(...)` is no longer working in DuckDB v1.1.* for the following JSON structure:
```
{"location":"67/820/data/1777410541745082368/854288f7-7e80-40ea-b43f-64e382462e74.dat","columns":{"v4_c21":{"statistics":{"nonNullCount":"0"}},"v4_c23":{"statistics":{"nonNullCount":"0"}},"v4_c22":{"statistics":{"nonNullCount":"0"}},"v4_c29":{"statistics":{"nonNullCount":"0"}},"v4_c6":{"statistics":{"nonNullCount":"0"}}, ...}}
```

DuckDB CLI and duckdb-java report the following error:

```
Binder Error: Cannot extract field 'v4_c6' from expression "columns" because it is not a struct, union, or json
```

My current workaround is switching to the bracket notation: `SELECT columns['v4_c6']`.

### To Reproduce

[4128-3fcd48a5-2c6f-4536-ac6d-1dfb837d8094.json](https://github.com/user-attachments/files/17183393/4128-3fcd48a5-2c6f-4536-ac6d-1dfb837d8094.json)

```sh
$ duckdb
v1.1.1 af39bd0dcf
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select columns.v4_c6 from read_ndjson_auto('4128-3fcd48a5-2c6f-4536-ac6d-1dfb837d8094.json');
Binder Error: Cannot extract field 'v4_c6' from expression "columns" because it is not a struct, union, or json
D select "columns"."v4_c6" from read_ndjson_auto('4128-3fcd48a5-2c6f-4536-ac6d-1dfb837d8094.json');
Binder Error: Cannot extract field 'v4_c6' from expression "columns" because it is not a struct, union, or json
D select columns['v4_c6'] from read_ndjson_auto('4128-3fcd48a5-2c6f-4536-ac6d-1dfb837d8094.json');
┌─────────────────────────────────────────────────────┐
│                 "columns"['v4_c6']                  │
│ struct("statistics" struct(nonnullcount varchar))[] │
├─────────────────────────────────────────────────────┤
│ [{'statistics': {'nonNullCount': 0}}]               │
└─────────────────────────────────────────────────────┘
```

### OS:

macOS aarch64

### DuckDB Version:

1.1.1

### DuckDB Client:

CLI, Java

### Hardware:

_No response_

### Full Name:

Fan Yang

### Affiliation:

ApeCloud

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes https://github.com/duckdb/duckdb/issues/14167 - not a bug, but behavior is now different.

We used to auto-detect `STRUCT`, but we now auto-detect `MAP`, and dot-notation for extracting fields no longer works for certain inputs.

However, if we implement `map_extract_first` and rewrite dot-notation on `MAP`s to this function we can still do the previous behavior.

Since this is not a bugfix but somewhat of a feature we could consider pointing this to the `feature` branch instead.

### CODE REVIEW

**Comment by Tishj** [comment]
`map_extract` should actually not return a LIST, the returned list is either empty or of size 1, which is kind of nonsense.
I'm not sure if we want to make that change though.

Creating `map_extract_first` would kind of cement this into place

**Comment by Tishj** [comment]
> @Tishj I thought the point of map_extract returning a list was to differentiate between a value being NULL and not present at all. Although I agree that it does add a lot of friction, now that we have map_contains and `IN` support you can check for missing values separately.

Hmm that makes some sense, I hadn't thought of that

**Comment by Tishj** [comment]
Also, I'm not sure if it has an impact here, but the difference between struct extract and map extract in case-insensitivity (highlighted in (???, can't find the recent issue...))

struct keys are case-insensitive, map keys aren't, since they're regular varchars, not identifiers, they are case-sensitive

**Comment by lnkuiper** [comment]
Also, we also cannot differentiate between `list_extract` returning `NULL` due to the index being out-of-range, or a `NULL` being returned from the specified position in the list. We could extend this logic to `map_extract`, and conclude that `map_extract` shouldn't return a list for the sole reason to be able to differentiate. I'm pretty sure that, e.g., Presto also doesn't return a list, but just a scalar value. Maybe we should just change `map_extract` then instead of adding this function?

**Comment by Tishj** [comment]
Yea I agree, but like I said that would break backwards compatibility, so it's a question if we want to do that.
Right now we're in between, adding `map_extract_first` would move us much further in the direction of having this `map_extract` behavior be permanent I feel.

I think either Hannes or Mark should make this call, I'd be in favor of having `map_extract` return a scalar

**Comment by Mytherin** [comment]
Thanks for the PR!

I think the reason `map_extract` returns a list is because maps in their original implementation were actually multimaps that could hold duplicate keys. That is no longer the case since https://github.com/duckdb/duckdb/pull/3760 - as such I would argue `map_extract` returning a list is no longer required/a good idea either.

I would be in favor of changing `map_extract` - but we need to be a bit careful w.r.t. backwards compatibility here.

**Comment by lnkuiper** [comment]
I've added the "Needs documentation" label as this PR now changes the behavior of `map_extract`.

**Comment by Mytherin** [comment]
Thanks! LGTM - we just need to make sure to mention this change in behavior in the release notes

**Pull request merged**
