### PR TITLE
Implement Brotli compression for Parquet reading & writing

### PR DESCRIPTION
**Pull request by hannes**
The Parquet spec [defines](https://github.com/apache/parquet-format/blob/master/Compression.md#brotli) [Brotli](https://github.com/google/brotli) support. This PR inlines a heavily patched derivate of the latest Brotli library to add support for Brotli to DuckDB's Parquet reader and writer.

### CODE REVIEW

**Comment by hannes** [comment]
This probably should go into feature

**Comment by hannes** [comment]
Windows failure looks unrelated

**Comment by hannes** [comment]
@Mytherin the failures here look unrelated.

**Comment by Mytherin** [comment]
Yes agreed

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
