### PR TITLE
NULLs sort last in relational

### LINKED ISSUE #5831: Relational API orders NAs first, how can we order them last?
### What happens?

In the relational API, `rel_order()` does the same as `ORDER BY` in SQL -- `NULL`s are ordered first. How can we make them appear last, for compatibility with data frames?

### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

df <- data.frame(a = c(1:2, NA))

dplyr::arrange(df, a)
#>    a
#> 1  1
#> 2  2
#> 3 NA

con <- dbConnect(duckdb())

rel <- duckdb:::rel_from_df(con, df)

exprs <- list(duckdb:::expr_reference("a"))

out <- duckdb:::rel_order(rel, exprs)
out
#> DuckDB Relation: 
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Order [a ASC]
#>   r_dataframe_scan(0x1104eb860)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - a (INTEGER)

duckdb:::rapi_rel_to_df(out)
#> # A tibble: 3 × 1
#>       a
#>   <int>
#> 1    NA
#> 2     1
#> 3     2
```

<sup>Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOs aarch64

### DuckDB Version:

2dcdc245566bb9a0fc717bc9d2c3867f911abc6d

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #5831.

### CODE REVIEW

**Comment by krlmlr** [comment]
I'm a fan of line breaks at EOF. Should we add `.R` files to the `.editorconfig` ?

**Review by Tmonster — APPROVED** [review]
This looks good to me. I wonder if it is also possible to remove the `OrderByNullType` parameter and then the connection uses the default defined by the [PRAGMA](https://duckdb.org/docs/sql/pragmas#default_null_order-default_order).

I can look into this. 

As for adding .R files to the editor. I think we can open up a separate PR for that to modify the .editorconfig

**Comment by krlmlr** [comment]
The dplyr semantics are fixed. Later, we might want to use an arbitrary connection, we should not rely on the PRAGMA.

Would you like to edit `.editorconfig` ?

**Comment by Tmonster** [comment]
I can edit the `.editorconfig`

**Pull request merged**
