### PR TITLE
WIP: R extension loading with pkgload compatibility

### PR DESCRIPTION
**Pull request by krlmlr**
This is a version of #3416, taken from the r-attempt-3 branch, plus using `dyn.load(local = TRUE)` instead of manual symbol registration. Works* for devtools, haven't checked with extension loading yet.

*Currently crashes RStudio when reloading several times. Maybe we still need to reassign the (potentially new) entry points after our manual `dyn.load()`? I'll experiment more later.

@samansmink: How do I test the extension loading mechanism locally?

### CODE REVIEW

**Comment by samansmink** [comment]
@krlmlr Testing loading an extension manually is best done by building an extension using eg. `BUILD_HTTPFS=1 make` which will build the httpfs extension to `./build/release/extension/httpfs/httpfs.duckdb_extension`. then from R try to run the following SQL in duckdb: `INSTALL {path}` where path is the full path to the built extension. 

With the current code it will not work however since the local param of dyn.load is set to TRUE, the whole point is that we need this variable to be set to false to load the duckdb symbols with RTLD_GLOBAL for them to be available to any extension that we load. 

I also just noticed that the R CI is not running for both this PR and https://github.com/duckdb/duckdb/pull/3416, there seems to have gone something wrong with the CI while moving the extension build to an action. I'll check this out later today.

**Comment by krlmlr** [comment]
Thanks. Of course we need `local = FALSE`, but we might need to do a bit more to avoid the crash.

**Comment by hannes** [comment]
Maybe this does not have to be a PR just yet, CI runs can also happen in your fork?

**Comment by krlmlr** [comment]
It's not about CI, but to simplify review. I'll keep pushes to a minimum.

Just a heads-up: I have identified the "testthat helpers" as a source of the crashes. Now testing if the repeated `dyn.load(local = FALSE)` actually helps finding the plugins, as @samansmink suggests.

Are you open to investigating alternative mechanisms for letting plugins communicate with duckdb directly?

**Comment by hannes** [comment]
Let me put it this way: We are not going to rewrite all extensions just to make devtools happier. I think it might be better to investigate why load_all is not working and work around that. In general, it looks like there are very limited options to expose a large (huge) API surface such as the DuckDB C++ classes to plugins loaded via dlopen that works on Linux, OSX and Windows (!).

**Comment by krlmlr** [comment]
I hear you, it looks like we can make devtools happy with the current approach.

I was thinking about a more controlled way of doing things, as relying on `RTLD_GLOBAL` seems to be fragile. For instance, R looks for an `R_init_duckdb()` entry point (and only for this), which populates internal data structures ("registration of native routines"). This allows R to work with `RTLD_LOCAL`. If duckdb pursued a similar approach, we could revert to "default loading" for Node, Python, R, and whatever other environments might come.

**Comment by krlmlr** [comment]
@samansmink: I'm having trouble compiling with `BUILD_HTTPFS=1` or `BUILD_VISUALIZER=1` on macOS M1, I'm seeing:

```
   CMake Error at /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
     system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
     OPENSSL_INCLUDE_DIR)
   Call Stack (most recent call first):
     /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     /opt/homebrew/Cellar/cmake/3.21.4/share/cmake/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
     CMakeLists.txt:506 (find_package)
     src/main/extension/CMakeLists.txt:9 (add_extension_definitions)
```

Does that ring a bell?

I already ran `brew install openssl` .

**Comment by hannes** [comment]
Yes, you may have to manually set OPENSSL_ROOT_DIR

**Comment by krlmlr** [comment]
Thanks, works better after a local `git clean -fdx` . Sorry for the noise.

**Comment by krlmlr** [comment]
This code now works with `devtools::load_all()`. @samansmink: Does loading of extensions work with this code?

I could run `INSTALL '<extension-path>'`, but it seems that this also works with the CRAN version on macOS.

``` r
con <- DBI::dbConnect(duckdb::duckdb())
DBI::dbExecute(con, "INSTALL '/Users/kirill/git/R/duckdb/build/debug/extension/visualizer/visualizer.duckdb_extension'")
#> [1] 0
```

<sup>Created on 2022-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by samansmink** [comment]
@krlmlr, ah my bad, its should be `LOAD 'path'`. I think your code is working though! I've confirmed that the httpfs extension works on your branch:

```
pkgload::load_all("tools/rpkg")
con <- dbConnect(duckdb::duckdb())
dbExecute(con, "LOAD '/tmp/duckdb/build/release/extension/httpfs/httpfs.duckdb_extension';")
res <- dbGetQuery(con, "SELECT id, first_name, last_name FROM PARQUET_SCAN('https://raw.githubusercontent.com/cwida/duckdb/master/data/parquet-testing/userdata1.parquet') LIMIT 3;")
res
```
prints:
```
   id first_name last_name
1  1     Amanda    Jordan
2  2     Albert   Freeman
3  3     Evelyn    Morgan
```

I've cherry picked your commits onto the original PR https://github.com/duckdb/duckdb/pull/3416. The CI should now be running with load_all and the extension test! I think we can close this PR and continue in the original PR?

**Comment by krlmlr** [comment]
Now integrated in the other PR.

**Pull request closed without merging**
