### PR TITLE
Test dockerized compilation in Alpine:latest and Ubuntu:20.04

### LINKED ISSUE #11703: Builds on Alpine linux are failing
### What happens?

PR #11663 introduced a [magical line](https://github.com/duckdb/duckdb/blob/v0.10.2/src/common/local_file_system.cpp#L43) that fixes builds on some linux setups but apparently it breaks builds on alpine linux (at least in Docker).

### To Reproduce

**Broken:**
```Dockerfile
FROM alpine:latest AS duckdb-build

ARG DUCKDB_REPO https://github.com/duckdb/duckdb.git
ARG DUCKDB_VERSION v0.10.2

RUN apk add git
RUN git clone \
  --depth 1 \
  --branch "${DUCKDB_VERSION}" \
  "${DUCKDB_REPO}" \
  /duckdb
WORKDIR /duckdb

RUN apk add \
  build-base \
  cmake \
  ninja \
  python3

RUN GEN=ninja make clean release
```

**"Fixed":**
```Dockerfile
FROM alpine:latest AS duckdb-build

ARG DUCKDB_REPO https://github.com/duckdb/duckdb.git
ARG DUCKDB_VERSION v0.10.2

RUN apk add git
RUN git clone \
  --depth 1 \
  --branch "${DUCKDB_VERSION}" \
  "${DUCKDB_REPO}" \
  /duckdb
WORKDIR /duckdb

# "fix"
RUN apk add sed
RUN sed -i \
  's/#include <linux\/falloc.h>//g' \
  /duckdb/src/common/local_file_system.cpp

RUN apk add \
  build-base \
  cmake \
  ninja \
  python3

RUN GEN=ninja make clean release
```

### OS:

x86_64

### DuckDB Version:

v0.10.2

### DuckDB Client:

build system?

### Full Name:

Tim Fischer

### Affiliation:

Universtity of Tübingen

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by carlopi**
Adding CI workflow for testing DuckDB compilation in dockerized environments.

Script currently provided for Alpine:latest and Ubunutu:20.04.
Those double down also as blueprints for how to compile and build DuckDB main binaries in those architectures / what dependencies are needed.

More tests are very welcome, it's a matter of adding a line per distribution to `scripts/test_docker_images.sh`.

Adding a partial revert of https://github.com/duckdb/duckdb/pull/11663 where I propose a different fix to https://github.com/duckdb/duckdb/discussions/11640 via providing a define, unsure whether this will be sufficient. Asking @zmbc if he could either provide a docker script showing the problem, I haven't managed to reproduce, and/or testing in its configuration with this alternative solution.

In the current form fixes https://github.com/duckdb/duckdb/issues/11703, otherwise merging only the first commit this should at the very least provide a reproduction and means to avoid similar regressions.

### CODE REVIEW

**Comment by carlopi** [comment]
Push for these tests is by @szarnyasg, adding in as reviewer.

**Comment by carlopi** [comment]
Also pinging @Flogex, since a PR of theirs (https://github.com/duckdb/duckdb/pull/11635) introduced the CMAKE_CURRENT_FUNCTION_LIST_DIR that is malfunctioning in the docker setup.

I have yet to check on their setup, at https://github.com/Flogex/duckdb-extension-template/commit/7aa87de2b2cf7c7160a04ffdb2f16c623e9fae52, to double check whether this change might work for everyone.

**Comment by Flogex** [comment]
@carlopi Looks like `CMAKE_CURRENT_FUNCTION_LIST_DIR` is new in CMake 3.17, the minimum required version for DuckDB is 3.5. I didn't check this, sorry.

Using `DUCKDB_MODULE_BASE_DIR` as introduced in this PR also works in a setup that includes the DuckDB CMake project as subdirectory and it the nicer approach IMO. 👍

**Comment by Mytherin** [comment]
Thanks!

**Comment by zmbc** [comment]
Unfortunately, this fix doesn't work in a conda environment, in the same way as described in #11640. What it was replaced with is enough to call `fallocate` but does not include the flags. I am a bit out of my depth as to why it seems that in many setups, the falloc headers are included automatically, apparently including Alpine, although a linux-headers package is available for Alpine. Any pointers?

**Comment by carlopi** [comment]
> Unfortunately, this fix doesn't work in a conda environment, in the same way as described in #11640. It is enough to call `fallocate` but does not include the flags. I am a bit out of my depth as to why it seems that in many setups, the falloc headers are included automatically, apparently including Alpine, although a linux-headers package is available for Alpine. Any pointers?

I am happy to dig deeper, would it be possible for you to share instructions on how to reproduce your setup? Basically something in the form like:
```
docker run -i --rm -v $(pwd):/duckdb --workdir /duckdb ubuntu:20.04 <<< "apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install g++ git make cmake ninja-build -y && GEN=ninja make && make clean" 2>&1
```
where instead you provide how to install conda + how to fetch dependencies + what exact packages are needed ?
I am happy to dig further, but I think you are in a better place to provide description of the exact steps you are following / your setup.

Once I can reproduce, it should be easy(er) to find a way out plus have a way to test no regression will happen for relevant setups.

**Pull request merged**
