### PR TITLE
Implement Map Type Detection for JSON Reader

### PR DESCRIPTION
**Pull request by ZiyaZa**
Proposed in #11159, partially adds the discussed functionality.

This PR adds a new `map_inference_threshold` option (with default value 100) to the `read_json[_auto]` function. If JSON schema auto-detection would infer a `STRUCT` type for a field that has more than this threshold number of subfields, it tries to infer a `MAP` type instead if all the value types are equal.

The option can be set to -1 to disable `MAP` inference.

It doesn't handle all possible `MAP`s. For instance, if the map values are Structs and these Structs are not 100% consistent, the current implementation cannot detect `MAP` type. Consider the following small example where this fails:
```json
{"map": {"key1": {"a": 1, "b": 1}, "key2": {"a": 1}, "key3": {"a": 1}, ...}}
```

I believe this PR is a good starting point for handling simple/consistent `MAP`s, but more complicated detection can be implemented in the future, where compatible and sufficiently similar `STRUCT`s are merged together.

### CODE REVIEW

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Hi @ZiyaZa, thanks for the pull request! I really like this idea!

This looks mostly good already. There's one thing that I think should be addressed still. What if I have a JSON file like this:
```json
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
{"col1": 1, "col2": 2, "col3": 3, "col4": 4, "col5": 5, "col6": 6, "col7": 7, "col8": 8, "col9": 9, "col10": 10}
```
There are 10 columns, which are all compatible with each other, so your `MAP` inference will try to convert this to a map. However, the keys are consistent, so the user will probably want to read them as a `STRUCT`, not a `MAP`.

Maybe this should only trigger if we would default to `JSON` due to `field_occurrence_threshold`? If we were going to default to `JSON` anyway, we could perhaps try to salvage it by trying to infer the `MAP` type. Maybe if we're using that parameter, we don't need the extra `map_inference_threshold` parameter.

We could also use `IsNumeric` and `MaxNumericType` to infer `MAP`s that contain different numeric types, so that the detection is more flexible.

What do you think @ZiyaZa? Does this make sense? I'm open to have a discussion here to figure out the best way to infer `MAP`. We can also discuss in person on tuesday.

P.S.: this PR should go to the `feature` branch, not `main`.

**Comment by ZiyaZa** [comment]
Hi @lnkuiper. Thank you for your comments!

It is a bit tricky to decide when the user would want a `STRUCT` instead of a `MAP`. I agree with you in your example that `STRUCT` is perhaps better. But imagine if instead of `BIGINT` values, we had some deeply nested `STRUCT`s as values. Would the user still want `STRUCT` in this case? If we have 10 `STRUCT`s with the same structure, I would think it is a `MAP`, but again, it perhaps depends on the specific data.

I decided to add the new `map_inference_threshold` to give the user some control over this, but I am also open to suggestions. I initially had it default to 100, but then it seemed too high and decreased to 10. Maybe we can increase the default. Maybe we can also consider the value type of the `MAP` we are inferring: if it is not a nested type, we try not to infer `MAP` unless there are a lot of subfields.

For my specific use case, I use the JSON reader to detect the complete schema of (structured) JSON files, and hence I set `field_occurrence_threshold` to 0 to disable defaulting to `JSON`. I don't know how common my use case would be, but it would mean we never detect `MAP`s in this case.

As a side note, since this implementation requires all subfields to have the exact same type, it is not flexible enough for the majority of the cases where the value type of the `MAP` would contain a `STRUCT` (a single null field inside a `STRUCT` is enough to stop us). Hence, I am currently looking into making this implementation more flexible: trying to merge types together recursively and then deciding if the final type is similar enough to individual types not to infer the `MAP` type too frequently. I'll see how it goes; it might be too complicated to implement for me.

**Comment by ZiyaZa** [comment]
Hi @lnkuiper.

I pushed my latest changes, where I implemented a recursive type similarity support. Here is a brief explanation of the current algorithm:
- If we have more than 10 children, map detection is triggered (This magic number 10 is currently hardcoded. I didn't want to add another parameter for this option, but I couldn't find any other solution for this. I am interested to hear if you know a better way to handle this number.)
- Initially, all the value types are merged recursively. Some special handling is required for `JSON` and `NULL` types. Merging lists/structs/maps is relatively straightforward.
- After we have the merged type, we calculate its similarity to the individual value types. If merging failed (e.g., due to incompatible types), we set the similarity to -1.
- If the average similarity is above 0.8 (80% similarity, by default, configurable option), we infer the map type with the merged value type.
- Since we don't want any field with the `NULL` type in the final result, we need to recursively replace all `NULL`s with the `JSON` type (or `null_type` in the source code).

I added a couple more test cases where it can detect maps successfully (I also tested on some datasets I have been working with). It still doesn't handle your example of where we would want struct instead of map. I couldn't come up with something clever to handle that case. I think in majority of scenarios where we have many similar children inside a struct, map makes more sense.

**Comment by ZiyaZa** [comment]
I changed the map detection according to our last discussion. It now should work as follows:
- `{}` gets detected as `MAP(VARCHAR, JSON)` (instead of `JSON`)
- "Inconsistent" objects are always inferred as `MAP(VARCHAR, <merged type>)` (instead of `JSON`)
  - The definition of "inconsistent" is the same as before. I changed the default `field_appearance_threshold` to 0.25 (instead of 0.1) according to the JSON data I experimented with.
- If a consistent object has more than `map_inference_threshold` (default 25) subfields, AND the average similarity of the merged value type to individual types is at least 80% (hard-coded parameter), we infer `MAP(VARCHAR, <merged type>)`
- Otherwise, we infer `STRUCT`

I also changed the code, as you suggested, to merge `JSONStructureNode`s and re-use `LogicalType` detection.

I tested it with the real JSON datasets, and in most cases, the default parameter values were enough to correctly identify the `MAP`s. For some obscure cases, I had to increase `field_appearance_threshold` to get the expected result, but I think the defaults capture the most common scenarios.

**Review by lnkuiper — APPROVED** [review]
Hi @ZiyaZa, thanks so much for implementing the changes! I thought our discussion was interesting, and I'm happy to see the results of it implemented here.

It's great to hear that type inference is now more effective on the data sets you tested. The implementation looks good to me now. Thanks again!

**Comment by ZiyaZa** [comment]
Hi. After experimenting some more with the new implementation, I decided to rollback my change to the default value of `field_appearance_threshold` and set it to 0.1 again. With 0.25, Map type was being detected where it did not make much sense.

**Comment by Mytherin** [comment]
Could you look at the merge conflicts?

**Comment by ZiyaZa** [comment]
Conflicts resolved. The CI failure seems to be unrelated.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
