### PR TITLE
Lookup parent frames for replacement scans

### LINKED ISSUE #2966: Table with name _ does not exist when using duckdb.query on a pandas dataframe in IPython unless wrapped in print or .to_df()
#### What happens?

Suppose I have a pandas dataframe called `mydf` and I'm _using IPython_.
If I evaluate a query directly, using `duckdb.query` I get:

```
---------------------
-- Expression Tree --
---------------------
Subquery [select sum(a) from mydf]

---------------------
-- Result Columns  --
---------------------
- sum(a) (HUGEINT)

---------------------
-- Result Preview  --
---------------------
Catalog Error: Table with name mydf does not exist!
```
If I do exactly the same thing in a standard Python repl instead of IPython, it works:

```
---------------------
-- Result Preview  --
---------------------
sum(a)
HUGEINT
[ Rows: 1]
6
```

Alternatively, if I stay in IPython and wrap the call to `duckdb.query` inside `print()`, or if I append `.to_df()`, then it also works!

#### To Reproduce

**Run this in IPython**. It works without issue in the default Python interpreter.

``` python
### In IPython ###
import pandas as pd
import duckdb

mydf = pd.DataFrame({'a': [1, 2, 3]})
duckdb.query("select sum(a) from mydf")
# Catalog Error: Table with name mydf does not exist!

print(duckdb.query("select sum(a) from mydf"))
# ---------------------
# -- Result Preview  --
# ---------------------
# sum(a)
# HUGEINT
# [ Rows: 1]
# 6

duckdb.query("select sum(a) from mydf").to_df()
#    sum(a)
# 0     6.0
```

**EDIT**: IPython uses the [display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display) function to render Python objects in the repl. You can replicate this issue in a standard Python repl as follows:

``` python
### In standard Python repl ###
import pandas as pd
import duckdb
from IPython.display import display

mydf = pd.DataFrame({'a': [1, 2, 3]})
display(duckdb.query("select sum(a) from mydf"))
# Catalog Error: Table with name mydf does not exist!
```

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.1
 - DuckDB Client: IPython 7.30.1 with Python 3.8.7

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

### PR DESCRIPTION
**Pull request by pdet**
Fix: #2966 

@davidwales if possible can you check if this fixes ur problem?

### CODE REVIEW

**Comment by davidwales** [comment]
@pdet Is there a build artifact I can try? Or do I need to build from source?

**Comment by Mytherin** [comment]
Is there any way to add a test for this, e.g. could we run ipython in the CI somehow?

**Comment by Mytherin** [comment]
> Task: #2966

Also minor note, github doesn't seem to recognize "Task:" as a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). If you could use "fixes" (or another term from that list) the PR will be automatically linked to the issue.

**Comment by pdet** [comment]
> Is there any way to add a test for this, e.g. could we run ipython in the CI somehow?

We add Ipython as a dependency, I'm not entirely sure how to capture the return value of the display function in order to assert that the query succeded

**Comment by Mytherin** [comment]
```
Traceback (most recent call last):
16
  File "scripts/regression_test.py", line 179, in <module>
17
    regression_test(0.15,benchmark)
18
  File "scripts/regression_test.py", line 167, in regression_test
19
    regression_status = run_h2oai(repetitions, threshold)
20
  File "scripts/regression_test.py", line 149, in run_h2oai
21
    load_h2oai(duckdb_conn,duckdb_current_conn)
22
  File "scripts/regression_test.py", line 108, in load_h2oai
23
    duckdb_current_conn.execute("CREATE TABLE x_group as SELECT * FROM 'G1_1e7_1e2_5_0.csv.gz'")
24
RuntimeError: AttributeError: 'NoneType' object has no attribute 'f_locals'
25
```

Could you look at the test failure? This seems related to the changes made in this PR.

**Pull request merged**
