### PR TITLE
list_sort function support

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR adds support for the `list_sort` function. This function takes either on argument (list) or three arguments (list, order, NULL order). It then sorts the elements of each list according to the specified sorting and NULL sorting order (or the default).

E.g.
```sql
SELECT list_sort([1, 4, NULL, -2, 2]);
-- [NULL, -2, 1, 2, 4]

SELECT list_sort([1, 4, NULL, -2, 2], 'DESC', 'NULLS LAST');
-- [4, 2, 1, -2, NULL]
```
An alias is `array_sort`. I also added rewriting rules for `list_reverse_sort` and `array_reverse_sort`.

This further expands the list function support (#1940).

### CODE REVIEW

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Looks good! Some nitpicks, and a request for a larger test, but other than that, this looks good! :)

**Review by lnkuiper — APPROVED** [review]
I think this PR is good to go now :)

**Comment by bucweat** [comment]
Currently synced up to commit 7eab6f3697003942d68f5413cb06b417628cd8ab. Trying build windows VS2019 32/64 bit and getting an error for both in list_sort.cpp. 

>...src\function\scalar\list\list_sort.cpp(30): error C3668: 'duckdb::ListSortBindData::Copy': method with override specifier 'override' did not override any base class methods

which is new file introduced here. Sorry my C++ fu is weak and outdated these days so cannot easily recommend a fix, but VS2019 is probably to blame :-)

**Comment by bucweat** [comment]
You are correct sir :-)

**Pull request merged**
