### PR TITLE
Fix for #8440

### PR DESCRIPTION
**Pull request by pdet**

### CODE REVIEW

**Comment by Tishj** [comment]
I never thought that this caused a bug but I did think it was dirty to preserve the arrow data if direct conversion could not be performed 👍

**Comment by pdet** [comment]
> 

Strings don't really go through the `DirectConversion` method, or do I misunderstand your comment?

**Comment by Tishj** [comment]
> > 
> 
> Strings don't really go through the `DirectConversion` method, or do I misunderstand your comment?

Currently we create the AuxiliaryData to preserve the arrow array before we scan the column, we only need to preserve this arrow array though if DirectConversion was used, otherwise we will have made a copy of the input anyways.

In cases where we don't need to preserve the arrow array, we currently still do

**Comment by pdet** [comment]
> > > 
> > 
> > 
> > Strings don't really go through the `DirectConversion` method, or do I misunderstand your comment?
> 
> Currently we create the AuxiliaryData to preserve the arrow array before we scan the column, we only need to preserve this arrow array though if DirectConversion was used, otherwise we will have made a copy of the input anyways.
> 
> In cases where we don't need to preserve the arrow array, we currently still do

That's not true for strings. I could move it to direct conversion and string conversion, but I think that's dirtier, no?

**Comment by Tishj** [comment]
Hmm true, it's not hurting anyone but it is a little wasteful to keep this memory alive needlessly

**Comment by Mytherin** [comment]
Thanks!

**Comment by Tishj** [comment]
The more I look at it I'm afraid this is a bandaid for the actual problem?

Creating the ArrowAuxiliaryData from a `shared_ptr<ArrowArrayWrapper>` held in the ArrowScanLocalState should have the exact same behavior as this new change.
The `ArrowScanLocalState` will overwrite it with a new chunk, decreasing the refcount, but we stored it inside the auxiliary data so it shouldn't go out of scope.

The only difference this makes is that the *first* chunk (ONLY the first chunk) is kept alive longer, for the duration that the ArrowScanLocalState stays alive.

That would indicate that the ArrowAuxiliaryData is not being kept alive long enough

**Pull request merged**
