### PR TITLE
Fix subtraction overflow problem in hugeint_t

### PR DESCRIPTION
**Pull request by MingjiHan99**
https://github.com/duckdb/duckdb/issues/1724

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! Looks good again. Will merge after the tests pass :)

**Comment by Mytherin** [comment]
The undefined behavior sanitizer seems to be triggered [here](https://github.com/duckdb/duckdb/pull/1728/checks?check_run_id=2528225189#step:4:575). Could you have a look?

**Comment by MingjiHan99** [comment]
```
/Users/runner/work/duckdb/duckdb/src/common/types/hugeint.cpp:353:24: runtime error: signed integer overflow: 9223372036854775807 - -1 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/runner/work/duckdb/duckdb/src/common/types/hugeint.cpp:353:24 in 
/Users/runner/work/duckdb/duckdb/src/common/types/hugeint.cpp:353:36: runtime error: signed integer overflow: -9223372036854775808 - 1 cannot be represented in type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/runner/work/duckdb/duckdb/src/common/types/hugeint.cpp:353:36 in 
```

Looks like the subtraction leads to  undefined behaviors but the result is correct.
`9223372036854775807 - -1` is equalvient to `0 7fffffffffffffff` minus `ffffffffffffffff ffffffffffffffff`. The upper part causes the undefined behavior.

**Comment by Mytherin** [comment]
We really want to avoid any undefined behavior, even if the result might be correct on some compiler configurations. While wrapping on integer overflow is common, it is undefined behavior and we cannot rely on it.

Could you perhaps have a look at how the undefined behavior could be avoided while still computing the correct result?

**Comment by hawkfish** [comment]
@MingjiHan99 You might want to have another look at this now that we have removed sentinel `NULL`s. Those were causing some strange boundary conditions near the large values.

**Comment by Mytherin** [comment]
Thanks for the work, I have moved the fix to #1826. Closing this.

**Pull request closed without merging**
