### PR TITLE
Issue #15069: Postgres CURRENT_XXX Compatibility

### LINKED ISSUE #15069: current_date & current_time PostgreSQL incompatibility
### What happens?

I opened a PR to the duckdb docs (https://github.com/duckdb/duckdb-web/pull/4206) stating current incompatibilty in the `current_date` and `current_time` pseudo-columns.

Usually, when duckdb differs from PostgreSQL it's for reasons I support. In this case, I think PostgreSQL's behavior is clearly better, so I wanted to raise this as an issue before it's enshrined into the docs.

DuckDB isn't even consistent within itself! `current_timestamp` returns a `TIMESTAMPTZ` and `current_localtimestamp()` a `TIMESTAMP` -- perfect --, but `current_time` returns a `TIME` while `current_localtime()` correctly returns a `TIME`. Clearly, `current_time` should return a `TIMETZ` like PostgreSQL does.

Also, there is no `current_localdate()` to get the correct local date (and that'd be perfectly fine if `current_date` did what it was supposed to; nobody needs to know the `current_date` in UTC, and if they were sure they absolutely did need to know, they could achieve that by setting their timezone or by using `timezone('UTC', current_timestamp)::DATE`)

### To Reproduce

```sql
SET TimeZone = 'Asia/Novosibirsk';
SELECT current_date, current_time, current_timestamp 
```
```
┌──────────────┬──────────────┬────────────────────────────┐
│ current_date │ current_time │     current_timestamp      │
│     date     │     time     │  timestamp with time zone  │
├──────────────┼──────────────┼────────────────────────────┤
│ 2024-11-30   │ 21:13:31.918 │ 2024-12-01 04:13:31.918+07 │
└──────────────┴──────────────┴────────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by hawkfish**
Move current_date/time to ICU so we can make then TZ aware.
This required tweaking some tests that assumed they were
in the main code base.

fixes: duckdb/duckdb#15069
fixes: duckdblabs/duckdb-internal#3605

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR!

I wonder if we can implement them as macros that refer to `CURRENT_TIMESTAMP` instead? e.g.:

```sql
CREATE MACRO current_date AS current_timestamp::DATE;
CREATE MACRO current_time AS current_timestamp::TIMESTAMP::TIME;
```

That way we don't need to move them to `ICU`.

**Comment by hawkfish** [comment]
The first one works. The second one should be `current_timestamp::TIMETZ`, which I think is incorrect (it drops the offset).

**Comment by hawkfish** [comment]
```sql
D set timezone='NZ';
D select current_timestamp::DATE as curent_date;
```
| curent_date |
|-------------|
| 2024-12-05  |

```sql
D select current_timestamp::TIMETZ as current_time;
```
|  current_time   |
|-----------------|
| 17:19:35.403+00 |

**Comment by hawkfish** [comment]
PG does this correctly:

```sql
hawkfish=# set timezone='NZ';
SET
hawkfish=# select current_timestamp::TIMETZ as current_time;
   current_time    
-------------------
 06:22:42.01224+13
(1 row)
```

**Review by Mytherin — COMMENTED** [review]
Thanks for the changes! LGTM - can you just look at the Python CI failure?

**Comment by hawkfish** [comment]
> Thanks for the changes! LGTM - can you just look at the Python CI failure?

Yeah I fixed that yesterday in the office (just a value change) but never pushed it bc I was waiting for other failures. Coming shortly.

**Comment by hawkfish** [comment]
The failure here appears to be a mismatch between the main code and the Windows extensions. The cast was not needed before (it was a function) but now that it is a macro with a cast, it seems that ICU is not being loaded for this test, even though it is explicitly loaded just before the test.

**Comment by hawkfish** [comment]
(The cast is in ICU, which is why the `require icu` line was added.)

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
