### PR TITLE
Support for all PostgreSQL CSV import options

### PR DESCRIPTION
**Pull request by taniabogatsch**
**Care**: `make unittest` passes, but Travis CI does not pass.

Options that are now supported and covered by test cases:
- `FORMAT 'csv'`
- `DELIMITER 'delimiter_string'`
- `NULL 'null_string'`
- `HEADER [ boolean ]`
- `QUOTE 'quote_string'`
- `ESCAPE 'escape_string'`
- `FORCE_QUOTE { ( column_name [, ...] ) | * }`, only in `COPY TO`
- `FORCE_NOT_NULL ( column_name [, ...] )`, only in `COPY FROM`
- `ENCODING 'utf-8'`

**Note**: If the value contains the delimiter character, the `QUOTE` character, the `NULL` string, a carriage return, or line feed character, then the whole value is prefixed and suffixed by the `QUOTE` character, and any occurrence within the value of a `QUOTE` character or the `ESCAPE` character is preceded by the escape character. A `NULL` is output as the `NULL` parameter string and is not quoted, while a non-`NULL` value matching the `NULL` parameter string is quoted.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the contribution! It looks like there is a problem in test_tpch.cpp:52. There the CSV reader is used for result verification. Please have a look there when you have the time. I will take a look at the code soon and leave more in-depth comments.

**Comment by Mytherin** [comment]
Thanks for the fix, looks like there is still a problem in the R Windows version:
```
C:/Users/travis/AppData/Local/Temp/RtmpolvgXY/R.INSTALL12ec2a034760/duckdb/src/duckdb/src/execution/operator/persistent/buffered_csv_reader.cpp:336:35: error: 'strcpy' was not declared in this scope
730    strcpy(str_val, new_val.c_str());
```
Looks like a missing include in that file, can you fix that?

**Comment by Mytherin** [comment]
I'm also wondering about multi-character delimiters and escapes, does it work properly if they are substrings of each other? e.g. what if my delimiter is 'AAA' and my escape is 'AA', I suppose the delimiter will always be escaped no? i.e. if I put the string 'AAA', it will instead result in a constant 'A'. Perhaps we should throw an exception on this. 

Another question is what if they have overlapping substrings, e.g. what if my delimiter is 'AAA' and my escape is 'AAB'. Specifically at the end of a buffer this is interesting: what if I match just the substring 'AA' at the end of my buffer? Does it work properly? A testcase for this would be nice.

**Comment by taniabogatsch** [comment]
I'll take a look at that missing include. Also, I need to add a fix and a test case for correctly parsing quoted null strings as string values, not as null.

> I'm also wondering about multi-character delimiters and escapes, does it work properly if they are substrings of each other? e.g. what if my delimiter is 'AAA' and my escape is 'AA', I suppose the delimiter will always be escaped no? i.e. if I put the string 'AAA', it will instead result in a constant 'A'. Perhaps we should throw an exception on this.

Because of '_any occurrence within the value of a QUOTE character or the ESCAPE character is preceded by the escape character_' 'AAA' (delimiter) and 'AA' (escape) wouldn't be a problem, if the value is 'AAA'. However, the problem probably arises when using 'AAAA' as a value. I'll add an additional exception and a test case.

> Another question is what if they have overlapping substrings, e.g. what if my delimiter is 'AAA' and my escape is 'AAB'. Specifically at the end of a buffer this is interesting: what if I match just the substring 'AA' at the end of my buffer? Does it work properly? A testcase for this would be nice.

I'll add an additional test case. Though I don't hope that that will cause problems, because control strings are only detected if all their characters match.

**Comment by hannesmuehleisen** [comment]
Thanks!

**Pull request merged**
