### PR TITLE
[Compression] ALP Compression (float/double)

### PR DESCRIPTION
**Pull request by lkuffo**
# ALP: Floating-Point Compression

This PR introduces ALP as a compression method in DuckDB. The details about ALP can be found in the [publication](https://ir.cwi.nl/pub/33334/33334.pdf).

## TL;DR 
ALP has two compression modes: `ALP` for doubles/floats which were once decimals, and `ALPRD` for true double/floats (e.g. the ones which stem from calculations).
Within DuckDB we implemented the two compression modes as separate encodings to improve code readability and maintainability. 
`ALP` transforms doubles/floats to integer values to BitPack them in only the necessary bits.
`ALPRD` splits the doubles/floats bitwise representations into two parts (left and right). The left part is encoded with a Dictionary compression and the right part is Bitpacked to just the necessary bits. 
Both encodings operate in vectors of 1024 values at a time and leverage in-vector commonalities to achieve higher compression ratios than other methods.  

ALP uses DuckDB BitPacking implementation (`PackBuffer`) and the code follows a similar structure found in Patas and Chimp implementations.

### The Analyze Step
The Analyze step in DuckDB determines the suitability of a compression method against the other methods available for a data type. The analyse step is divided into two main procedures: `Analyze` and `FinalAnalyze`.   
- `Analyze` is called for every DuckDB vector (i.e. 2048 values) within a segment. Usually, per-value methods (Patas, Chimp), start compressing the data in this step. Since ALP needs to take samples from the whole data, we do not execute compression in the `Analyze` step; but we only collect the needed samples from the data. Getting the sampling to work as intended in ALP was a challenge since we never have access to the entire segment at a time.
- `FinalAnalyze` is called when all the calls to `Analyze` are finished. In this step, we call our encoding algorithm using the collected samples and return an estimated compression size for the segment (in bytes).

### The Compress Step
There is a `Compress` and a `FinalizeCompress` step which work like Analyze and FinalAnalyze. Since we can transfer the algorithm state from the Analyze step, we do not need to take samples again and we can go directly to the encoding in every call to `Compress`. In here, the written code follows a very similar structure to the one found in Patas and Chimp.

### Other implementation details

- The data layout: We implemented a similar layout to the one in Patas. We store the pointers to the start of each group (ALP vector) data at the end of the segment. Thus, vectors can be skipped 1024 values at a time.
- Predicated Comparisons:  Within the code, we tried to avoid conditionals (if-else) within loops. Thus, we use Predicated Comparisons to detect the values which are not valid within a DuckDB vector.
- Block Compacting: We implemented a TODO stated in the Patas code, in which we only compact a segment data and metadata if both fulfil a certain size threshold.
- Unit Tests: We incorporated (for both `ALP` and `ALPRD`) all the tests in Patas plus additional tests with datasets containing values such as Infinity, -Infinity & NaN.

## Custom Benchmarks
We performed some custom benchmarks on DuckDB to compare Patas and Chimp vs ALP and ALPRD.
TBD

### CODE REVIEW

**Comment by lkuffo** [comment]
Sorry, opened this by mistake!! My apologies

**Comment by Tishj** [comment]
Thanks for the write up, even if this is still work-in-progress, I wanted to clarify one thing:

> Usually, per-value methods (Patas, Chimp), start compressing the data in this step

I understand what you mean but it can be interpreted in a different way.
The point of Analyze is to determine if the algorithm can be used on the data of the segment at all.
The purpose of Final Analyze is to output an expected compressed size.

To estimate this Final Analyze result value we usually perform a dry-run of the compression algorithm (not writing anything to disk) during the Analyze step.
This dry-run essentially performs the algorithm so I assume that's what you are referring to :)

**Comment by lkuffo** [comment]
Hi Tishj,
Yes! My bad on the wording I used. I agree. We are aware of the dry-run that the algorithms perform during the Analyze step; essentially using an "EMPTY" writer. We also did something similar.

Sorry once again for opening this work-in-progress PR. It was meant to be inside a fork

**Comment by JAicewizard** [comment]
@lkuffo I got a link to this, and just read the article. But I can't stop wondering why you chose to do the compression base 10? When using base 2 you could be much more efficient: unpack the float, add `e` and `f` to the exponent, and use a bitshift on the fraction? This would also avoid premature rounding issues you get with floating-point multiplication as well.

This is probably not the best place to ask, but I hope you don't mind.

**Comment by lkuffo** [comment]
Hi @JAicewizard 
Sorry for the late response, 
We are a bit confused by your idea. Would you mind sharing a small concrete example so we can have a better grasp of it?
Maybe we can also continue this discussion through email (lxkr@cwi.nl)

Looking forward to it,
Thanks

**Pull request closed without merging**
