### PR TITLE
[CI] Diff against the right remote + branch in `Regressions.yml` - `Regression Test new micro benchmark`

### PR DESCRIPTION
**Pull request by Tishj**
This PR aims to fix CI of PRs made to `feature`:

```
Run git diff --name-only origin/main | (grep "benchmark/micro/*" || true) > .github/regression/updated_micro_benchmarks.csv
Detected the following modified benchmarks. Running a regression test
benchmark/micro/csv/ignore_errors.benchmark
benchmark/micro/csv/multiple_small_files.benchmark
benchmark/micro/csv/time_type.benchmark
benchmark/micro/result_collection/batched_stream_query.benchmark
```

```
benchmark/micro/csv/ignore_errors.benchmark
Old timing: 2.205773
New timing: Failed to run benchmark benchmark/micro/csv/ignore_errors.benchmark

benchmark/micro/csv/multiple_small_files.benchmark
Old timing: 0.244721
New timing: Failed to run benchmark benchmark/micro/csv/multiple_small_files.benchmark

benchmark/micro/csv/time_type.benchmark
Old timing: 0.921153
New timing: Failed to run benchmark benchmark/micro/csv/time_type.benchmark

benchmark/micro/result_collection/batched_stream_query.benchmark
Old timing: 7.897132
New timing: Failed to run benchmark benchmark/micro/result_collection/batched_stream_query.benchmark
```

By only running this job if the event is a PR, and diffing against the target branch instead of hardcoding this to `main`

### CODE REVIEW

**Comment by Tmonster** [comment]
Why are we doing only on pull request? What was wrong with `always()`? The other regression tests also run always

**Comment by Tishj** [comment]
As said before, there is no way to know what branch this has to diff against for a push
if you mark the PR as ready for review it will trigger this step

**Review by Tmonster — APPROVED** [review]
true, forgot about that detail. LGTM!

**Comment by carlopi** [comment]
I just realized looking at this: why do we have the push block at all? (I know why we used to have it, but I think it can be probably just removed everywhere)

**Comment by Mytherin** [comment]
After merging and getting a merge conflict when propagating this to feature - I wonder if there is any added functionality here over what was already done in https://github.com/duckdb/duckdb/pull/11762

**Comment by Mytherin** [comment]
I've left feature with only https://github.com/duckdb/duckdb/pull/11762 for now, feel free to open a new PR to feature with whichever changes are relevant there.

**Pull request merged**
