### PR TITLE
add nix flake with devshell

### PR DESCRIPTION
**Pull request by rupurt**
- builds reproducible development environment with nix
- enter a nix devshell with `nix develop -c $SHELL`
- build with `make`

### CODE REVIEW

**Comment by Maxxen** [comment]
@samansmink @carlopi if your vcpackage/patch adventure doesn't work out, building on top of this/working with nix might be of interest to integrate into the CI for greater stability and easier cross-compiling.

**Comment by rupurt** [comment]
@Maxxen sweet 😄 Happy to modify to make it fit the needs of the build.

Have you looked into zig for cross compiling? I'm currently working on converting the cmake build for duckdb extensions to zig + nix. I've never used zig to compile such a big C++ project but initial results are super promising. Compilation times are super fast.

**Comment by rupurt** [comment]
@Maxxen [this](https://github.com/rupurt/record-duckdb-extension/pull/1) is the progress so far if you want to use it as a starting point or for research. Once I figure out how to pass through the path to `libssl` I feel like the it should be smooth sailing.

**Comment by rupurt** [comment]
@Maxxen it's alive 😄 I managed to build the shell with Nix & Zig https://github.com/rupurt/record-duckdb-extension/pull/1.

Next step is to build the extensions and try to match the existing cmake build steps. https://github.com/rupurt/record-duckdb-extension/pull/2

**Comment by hannes** [comment]
Thanks for the PR, but at the moment I'd prefer not to add configuration for external tooling to the main repo that we would have to maintain. Cheers

**Pull request closed without merging**
