### PR TITLE
Replacing move with std::move because clang recently added a warning

### PR DESCRIPTION
**Pull request by hannes**
See CRAN warnings at https://cran.r-project.org/web/checks/check_results_duckdb.html
Also see llvm mailing list discussion https://www.mail-archive.com/cfe-commits@lists.llvm.org/msg266167.html
Some background discussion (interesting!) https://reviews.llvm.org/D119670

### CODE REVIEW

**Comment by hannes** [comment]
It may be better to use `duckdb::move` instead of `std::move`, happy to hear opinions on this

**Comment by Tishj** [comment]
@hawkfish pushed a PR for this recently adding the option to ignore this warning I believe.
I can see both sides, but like Max mentioned, it's essentially part of the language now, I don't think anyone will make a function called `move`

**Comment by hannes** [comment]
We can't suppress the warning on CRAN so its not a solution regrettably

**Comment by hannes** [comment]
How about `duckdb::Move` so you can usually just write `Move`?

**Comment by hannes** [comment]
So how about this
```C++
namespace duckdb {
template< class T >
typename std::remove_reference<T>::type&& Move(T&& t) noexcept {
	return std::move(t);
}

#ifdef DEBUG
template< class T >
typename std::remove_reference<T>::type&& move(T&& t) noexcept {
	// using this will also trigger an error (call to 'move' is ambiguous)
	throw std::runtime_error("Use `Move` instead of `move`");
}
#endif
}
````

The nice thing that using unqualified move will now trigger a compilation error due to ambiguity.

**Comment by hannes** [comment]
`Move` turned out to also be problematic because a few classes (e.g. DataChunk) have their own `Move` methods.

**Comment by hannes** [comment]
`Move` seems to be the best option, I renamed the conflicting methods.

**Comment by Mytherin** [comment]
Thanks for the PR! That is a rather annoying addition and a very unnecessary warning, in my opinion, but well. 

Can't we use our own implementation of `std::move` to trick the compiler here, e.g.:

```cpp
namespace duckdb {
template< class T >
typename std::remove_reference<T>::type&& move(T&& t) noexcept {
	return std::move(t);
}
}
```

Or does that still trigger the warning?

**Comment by hannes** [comment]
> Thanks for the PR! That is a rather annoying addition and a very unnecessary warning, in my opinion, but well.
> 
> Can't we use our own implementation of `std::move` to trick the compiler here, e.g.:
> 
> ```c++
> namespace duckdb {
> template< class T >
> typename std::remove_reference<T>::type&& move(T&& t) noexcept {
> 	return std::move(t);
> }
> }
> ```
 
> Or does that still trigger the warning?

Worse, it triggers an `error: call to 'move' is ambiguous`

**Pull request closed without merging**
