### PR TITLE
[CI] Re-enable ART zero initialisation verification

### PR DESCRIPTION
**Pull request by taniabogatsch**
Fixes https://github.com/duckdblabs/duckdb-internal/issues/286.
Fixes https://github.com/duckdblabs/duckdb-internal/issues/1856.

### CODE REVIEW

**Comment by taniabogatsch** [comment]
Nightly run: https://github.com/taniabogatsch/duckdb/actions/runs/10937518362

**Comment by taniabogatsch** [comment]
The nightly still fails on a Linux machine, so this should not be merged.

**Comment by taniabogatsch** [comment]
Nightly run: https://github.com/taniabogatsch/duckdb/actions/runs/10991397926

**Review by samansmink — APPROVED** [review]

**Comment by taniabogatsch** [comment]
I just found another related issue.
I added it and I am rerunning the nightly tests here: https://github.com/taniabogatsch/duckdb/actions/runs/10995764389

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
