### PR TITLE
PR2 for zOS support

### PR DESCRIPTION
**Pull request by v1gnesh**
I done goof'd with `lightweightsemaphore.h` in the first PR.
Have verified that it builds fine with the unix block, so just using that.
My upstream PR to concurrentqueue does this correctly.

There's a situation with `jemalloc_internal_types.h`.
For example, here's the related command from compiler_commands.json:

```json
{
  "directory": "/v1g/zopen/dev/duckdbport/duckdb/extension/jemalloc/jemalloc",
  "command": "/usr/lpp/IBM/oelcpp/v2r0/bin/clang++ -DDUCKDB_BUILD_LIBRARY -DJEMALLOC_NO_PRIVATE_NAMESPACE -DJEMALLOC_NO_RENAME -I/v1g/zopen/dev/duckdbport/duckdb/src/include -I/v1g/zopen/dev/duckdbport/duckdb/third_party/fsst -I/v1g/zopen/dev/duckdbport/duckdb/third_party/fmt/include -I/v1g/zopen/dev/duckdbport/duckdb/third_party/hyperloglog -I/v1g/zopen/dev/duckdbport/duckdb/third_party/fastpforlib -I/v1g/zopen/dev/duckdbport/duckdb/third_party/fast_float -I/v1g/zopen/dev/duckdbport/duckdb/third_party/re2 -I/v1g/zopen/dev/duckdbport/duckdb/third_party/miniz -I/v1g/zopen/dev/duckdbport/duckdb/third_party/utf8proc/include -I/v1g/zopen/dev/duckdbport/duckdb/third_party/miniparquet -I/v1g/zopen/dev/duckdbport/duckdb/third_party/concurrentqueue -I/v1g/zopen/dev/duckdbport/duckdb/third_party/pcg -I/v1g/zopen/dev/duckdbport/duckdb/third_party/tdigest -I/v1g/zopen/dev/duckdbport/duckdb/third_party/mbedtls/include -I/v1g/zopen/dev/duckdbport/duckdb/third_party/jaro_winkler -I/v1g/zopen/dev/duckdbport/duckdb/extension/jemalloc/include -I/v1g/zopen/dev/duckdbport/duckdb/extension/jemalloc/jemalloc/include -DNSIG=42 -D_XOPEN_SOURCE=600 -D_ALL_SOURCE -D_OPEN_SYS_FILE_EXT=1 -D_AE_BIMODAL=1 -D_ENHANCED_ASCII_EXT=0xFFFFFFFF  -DZOSLIB_OVERRIDE_CLIB=1 -fzos-le-char-mode=ascii -mnocsect -fno-short-enums -Wno-error -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -O3  -fgnu-keywords -I/v1g/zopen/prod/zoslib-zopen/include -O3 -DNDEBUG -O3 -DNDEBUG   -fPIC -w -std=c++11 -o CMakeFiles/jemalloc.dir/src/ctl.cpp.o -c /v1g/zopen/dev/duckdbport/duckdb/extension/jemalloc/jemalloc/src/ctl.cpp",
  "file": "/v1g/zopen/dev/duckdbport/duckdb/extension/jemalloc/jemalloc/src/ctl.cpp"
},
```

ctl.cpp is being built with clang++, ok.
However, it refers to the internal types header file, which looks for `__STDC_VERSION__`.
At least on zOS, clang++ doesn't know about `__STDC_VERSION__`, so it goes down this path of thinking it's < `199901L`.

Have addressed this, but wanted to check if this requires any further investigation.

### CODE REVIEW

**Comment by v1gnesh** [comment]
With the patches in this PR, it goes through OK.
What's left is to figure out linking errors.. see if static linking is needed.

**Comment by v1gnesh** [comment]
@Mytherin Wise words indeed.
After disabling jemalloc extensions and the address sanitizer, it builds & works ok.

**Comment by Mytherin** [comment]
Thanks - looks fine to me. Could you just fix the failing CI?

**Comment by v1gnesh** [comment]
CodeQuality - I'll push a commit for the format-check

Windows - I see you were working on the ODBC tests, and the error is probably related to that (?)

LinuxRelease - Fails on Deploy with `amalgamation.py` unable to find `zos-tls.h`, which is generally available [here](https://github.com/ibmruntimes/zoslib/blob/main/include/zos-tls.h). 


```python
for x in regex_include_statements:
    included_file = x[1]
    if skip_duckdb_includes and 'duckdb' in included_file:
        continue
+   if ('pg_functions.cpp' or 'src_backend_parser_scansup.cpp' in fpath) and included_file == 'zos-tls.h':
+       continue
    if 'extension_helper.cpp' in fpath and (included_file.endswith('_extension.hpp') or included_file == 'generated_extension_loader.hpp'):
        continue
```

With the first and then this PR, DuckDB compiles & works on zOS, but some tests from the unittest fail.
Ex: radix sort.
Any pointers on where BE-related review will be required will be super helpful.

Assuming that this is not the end of zOS support work, is the above solution acceptable?

**Comment by Mytherin** [comment]
For the amalgamation builds the wrong include tags are likely used. `#include <...>` should be used for system headers to prevent them from being inlined into the amalgamation (and leave the #include statements as-is).

**Comment by v1gnesh** [comment]
Awesome, thank you. Bringing this back to 'ready for review'.

**Comment by v1gnesh** [comment]
The current failures look unrelated to this PR.

**Comment by Mytherin** [comment]
Could you merge with master so that the CI can run again?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
