### PR TITLE
feat(python): build for CPython 3.12

### PR DESCRIPTION
**Pull request by Mause**
Take two of 3.12 support

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks - LGTM. Could you maybe merge with master? I doubt the Windows failure is related but there have been some ADBC fixes that might make it succeed.

**Comment by Mause** [comment]
> As the CI currently works, it means that most of the Python workflow is actually untested in this case.
> 
> I rebased on main + got my CI to run a set as-if this was already merged, results will be eventually here: https://github.com/carlopi/duckdb/actions/runs/6428853614

I mean, yeah, this intentional - we generally don't need to run against every single Python version on branch builds. Are there particular changes here you expect to cause problems?

**Comment by yoonghm** [comment]
Hi, I have reinstalled Python 3.12.0 today.  I have VS2022 too. `pip install duckdb` still give me this error:

```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iduckdb_build/src/include -Iduckdb_build/third_party/fmt/include -Iduckdb_build/third_party/fsst -Iduckdb_build/third_party/re2 -Iduckdb_build/third_party/miniz -Iduckdb_build/third_party/utf8proc/include -Iduckdb_build/third_party/utf8proc -Iduckdb_build/third_party/hyperloglog -Iduckdb_build/third_party/fastpforlib -Iduckdb_build/third_party/tdigest -Iduckdb_build/third_party/libpg_query/include -Iduckdb_build/third_party/libpg_query -Iduckdb_build/third_party/concurrentqueue -Iduckdb_build/third_party/pcg -Iduckdb_build/third_party/httplib -Iduckdb_build/third_party/fast_float -Iduckdb_build/third_party/mbedtls -Iduckdb_build/third_party/mbedtls/include -Iduckdb_build/third_party/mbedtls/library -Iduckdb_build/third_party/jaro_winkler -Iduckdb_build/third_party/jaro_winkler/details -Iduckdb_build/extension/parquet/include -Iduckdb_build/third_party/parquet -Iduckdb_build/third_party/snappy -Iduckdb_build/third_party/thrift -Iduckdb_build/third_party/zstd/include -Iduckdb_build/extension/icu/include -Iduckdb_build/extension/icu/third_party/icu/common -Iduckdb_build/extension/icu/third_party/icu/i18n -Iduckdb_build/extension/fts/include -Iduckdb_build/third_party/snowball/libstemmer -Iduckdb_build/third_party/snowball/runtime -Iduckdb_build/third_party/snowball/src_c -Iduckdb_build/extension/tpch/include -Iduckdb_build/extension/tpch/dbgen/include -Iduckdb_build/extension/tpcds/include -Iduckdb_build/extension/tpcds/dsdgen/include -Iduckdb_build/extension/tpcds/dsdgen/include/dsdgen-c -Iduckdb_build/extension/json/include -Iduckdb_build/extension/json/yyjson/include -Iduckdb_build/extension/jemalloc/include -Iduckdb_build/extension/jemalloc/jemalloc/include -Iduckdb_build -IC:\Users\yhm2\AppData\Local\Temp\pip-install-8a5_i_wf\duckdb_af0e6d4a24b44ca7ae705676c3d3f8ce\src\include -IC:\Users\yhm2\AppData\Local\Temp\pip-build-env-xl6loiri\normal\Lib\site-packages\pybind11\include -IC:\Users\yhm2\AppData\Local\Temp\pip-build-env-xl6loiri\normal\Lib\site-packages\pybind11\include -ID:\Python\include -ID:\Python\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpduckdb_build/extension/fts/fts_extension.cpp /Fobuild\temp.win32-cpython-312\Release\duckdb_build/extension/fts/fts_extension.obj /wd4244 /wd4267 /wd4200 /wd26451 /wd26495 /D_CRT_SECURE_NO_WARNINGS /utf-8 -DDUCKDB_PYTHON_LIB_NAME=duckdb -DDUCKDB_BUILD_LIBRARY -DWIN32 -DDUCKDB_EXTENSION_PARQUET_LINKED -DDUCKDB_EXTENSION_ICU_LINKED -DDUCKDB_EXTENSION_FTS_LINKED -DDUCKDB_EXTENSION_TPCH_LINKED -DDUCKDB_EXTENSION_JSON_LINKED -DDUCKDB_EXTENSION_AUTOLOAD_DEFAULT=1 -DDUCKDB_EXTENSION_AUTOINSTALL_DEFAULT=1
      fts_extension.cpp
      C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for duckdb
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects
```

**Comment by Bidek56** [comment]
Is 3.12 support going to be released soon? thx

**Pull request closed without merging**
