### PR TITLE
Add floatdiv alias

### PR DESCRIPTION
**Pull request by tanner-lai**
Added a feature request here: https://github.com/duckdb/duckdb/discussions/10394

There is no function that computes x / y.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Could you expand on why the `/` operator isn't sufficient here and an extra function is desirable? Note that it can also be used as a function:

```sql
D select "/"(42.5, 3);
┌────────────────────┐
│     /(42.5, 3)     │
│       double       │
├────────────────────┤
│ 14.166666666666666 │
└────────────────────┘
```

**Comment by tanner-lai** [comment]
Ahh, that I did not know! I think that serves my use case, thanks for the info.

**Comment by Mytherin** [comment]
No problem.

As an extra piece of info, you can also create your own functions:

```sql
D create function floatdiv(x, y) as x / y;
D select floatdiv(42.5, 3);
┌────────────────────┐
│ floatdiv(42.5, 3)  │
│       double       │
├────────────────────┤
│ 14.166666666666666 │
└────────────────────┘
```

**Comment by tanner-lai** [comment]
I love it, thanks!

**Pull request closed without merging**
