### PR TITLE
Name and affiliation should not be required by the form validation

### PR DESCRIPTION
**Pull request by domoritz**
The comment even says that the issue will be closed if they are not given but I have to give them even if my affiliation is obvious.

### CODE REVIEW

**Comment by Tishj** [comment]
Sorry but the wording on this kind of threw me off for a minute.
Your issue is with the field being required, even though the comment states:
>  .. and is not obvious from your GitHub profile page

Your issue is not with the fact that we require users to disclose their identity when making an Issue, correct?

**Comment by domoritz** [comment]
Right, I wasn't clear. I have no issues with the fact that a disclosure is required. I was merely confused that the form required them when the text says they aren't needed when the GitHub profile is clearly indicating the name and affiliation.

**Comment by eaubin** [comment]
No comment on the contents of the PR, but I find the requirement to disclose identity/affiliation when making an Issue very off putting.  To me the [justification](https://berthub.eu/articles/posts/anonymous-help) reads as unconvincing and rude. Even if identify and affiliation is really necessary it should be removed or replaced.

**Comment by Mytherin** [comment]
> No comment on the contents of the PR, but I find the requirement to disclose identity/affiliation when making an Issue very off putting. To me the [justification](https://berthub.eu/articles/posts/anonymous-help) reads as unconvincing and rude. Even if identify and affiliation is really necessary it should be removed or replaced.

Perhaps you could provide some arguments as to why it is unconvincing? Making an issue generally amounts to asking for us to work to solve your problem. The least you could provide us with is your identity. Allowing people to file issues anonymously allows for abuse, as explained in the linked article. Anonymity has often been abused by people in the past to act rude and entitled, which is why we initially added this requirement. People tend to be more respectful when their real name is attached.

In practice we don't close issues purely because of the lack of name and affiliation. If the issue is a bug-report that is short, reproducible and formulated in a polite manner we will leave it open. We have this rule primarily so we can close issues of people that act entitled or rude without filling it in.

**Comment by Mytherin** [comment]
On the topic of the PR, perhaps we could add a required checkbox that states "I have provided my name and affiliation, or they are obvious from my profile"?

**Comment by domoritz** [comment]
I don't think a form is a solution to a social problem. Rude people will find a way and you may have to close issues regardless of what's in the form. A checkbox has the same issue: adding friction for nice people and not being a real deterrent for jerks. 

Of course this is your oss project so you are free to ask for whatever information you want. My question would be through, whether this has been an issue in the past or it's anticipating a problem?

All I wanted to address in this pr is that it's not necessary to require name and affiliation for every issue when they are already obvious from the profile (as stated in the comment on the issue  form).

**Comment by Mytherin** [comment]
> Of course this is your oss project so you are free to ask for whatever information you want. My question would be through, whether this has been an issue in the past or it's anticipating a problem?

This has been an issue in the past, and requiring affiliation helps because you can close an issue with a clear justification. Otherwise closing an issue might be seen as trying to hide a problem - rather than as not wanting to deal with rude people.

Have you read [the linked post](https://berthub.eu/articles/posts/anonymous-help)? I think it quite nicely summarizes why this is desirable for several reasons.

> All I wanted to address in this pr is that it's not necessary to require name and affiliation for every issue when they are already obvious from the profile (as stated in the comment on the issue form).

Agreed, but I think clicking a check-box is pretty low-effort, no? The problem with getting rid of requiring it entirely is that people will consistently not fill it in/pretend not to have seen it.

**Comment by domoritz** [comment]
Yes, I skimmed it. I changed this pull request to use a checkbox instead.

And I'm sorry to hear this has been an issue in the past.

**Comment by eaubin** [comment]
Sure, first why particular Berts justification page rubs me the wrong way and what parts I agree with.

Most importantly it's  needlessly confrontational, implying that non-publicly identified are only scammers trying to trick you into providing free techninal support or development. He has some bizarre personal philosophical distinction between people who "really need anonymity" for personal safety and people who don't really need it.

Bit by bit, from 'So why do I care?'

```
First, I just consider it rude. You come at me hiding who you are but still expect me to do free 
work for you. Try doing that in real life. What were you thinking? Not introducing yourself AND
using a fake identity?
```

Pseudonymity is normal on the internet and not an affront. I don't see filing an issue is "coming at you" or expecting free work.  It would be better to explicitly have a document including expectations statements like: "Issues that abusive violate our [Code of Conduct](https://duckdb.org/code_of_conduct) will be closed without comment."


```
Second, I have found that this anonymity also means respondents feel free to simply walk away 
with no damage to their reputation. You report a complicated bug, I spend some time 
investigating, ask about details, and I get no response. Some weeks later a very similar question 
comes in from a fresh email address, likely the same person, still not wanting to do the work to 
get help.
```

This confuses anonymity with reputation and has strange expectations about work, although I agree with the general point that its good to have some reputation on the line.

IMO, If there's a bug in the software it should always be reported even if its immediately closed and not investigated.  Its valuable to other users who encounter the same bug later, potentially valuable for developers, although clarifying issues and triage has a real cost. Expectations could be clearly stated somewhere "DuckDB is an open source project with no obligation to investigate or resolve any issue.  Please contact DuckDB labs for commercial support".

```
Third, my software and other products can be used for good or evil. If I don’t know who you
are, am I enabling you to build the new Turkish censorship infrastructure, or helping you 
implement the Роскомнадзор block list more efficiently? These are two examples that actually 
happened by the way.
```

This is merely unconvincing. If I'm really using your software for nefarious purposes, I don't believe knowing a supposed name and affiliation will help you determine that.

Sections of `What’s next, send a copy of photo ID?` seem reasonable. 

From `Our corporate policy does not allow us to disclose our use of open source software`

```
While I have sympathy for the pain this will cause you individually, my open source policy does 
not allow me to offer free help to corporations who do not even have the decency to admit that 
they use my software.
```

This section is kind of surprising to me. I'd expect something like disclosure to be handled by licensing terms rather than ugly moralizing language: "even have decency to admit that they use my software". I'm skeptical github issues with affiliation give projects credibility. 


```
While I am grateful for your report, I have no moral obligation to fix your every bug. Life is short, 
many things need to be done. If you truly want to upset an open source developer, tell them what
they “should” be doing - safely behind your anonymous email address or single use GitHub account.
```

The logic is fine but the text is rude. Maybe expectations could be clarified. "Open source 
developers of DuckDB have no obligation to implement enhancements or provide support. 
Please contact DuckDB Labs for commercial development."

```
What about people that really need anonymity

These exist, and I help them. I have extended family living in oppressive regimes. And you know, 
I can tell if the need for secrecy derives from worries about personal safety. But the vast majority 
of anonymous users have no such worries - not sharing who they are is mere convenience for 
them, allowing them to forego the risk of looking stupid under their real name, while making my 
life harder.
```

Why is Bert the judge of reasons people want anonymity?


IMO, regardless of whether or not you want name and affiliation the justification should be replaced.  

Mark writes:
```
Perhaps you could provide some arguments as to why it is unconvincing? Making an issue 
generally amounts to asking for us to work to solve your problem. The least you could provide 
us with is your identity. Allowing people to file issues anonymously allows for abuse, as explained 
in the linked article. Anonymity has often been abused by people in the past to act rude and 
entitled, which is why we initially added this requirement. People tend to be more respectful 
when their real name is attached.

In practice we don't close issues purely because of the lack of name and affiliation. If the issue is a 
bug-report that is short, reproducible and formulated in a polite manner we will leave it open. We 
have this rule primarily so we can close issues of people that act entitled or rude without filling it 
in.
```

As someone not triaging issues or developing so I respect your motivation and decisions and agree it's good way to encourage people to file better issues and act in more excellent way, but I don't understand how its actually useful or why it's needed beyond encouraging good behavior.

**Comment by eaubin** [comment]
After posting this I realized that I very well might be out of line hijacking PR instead of opening a new discussion and doing some of the behavior in the linked post ("tell them what they “should” be doing - safely behind your anonymous [...] GitHub account.")  As Dominik said, this is your project, ask for whatever information you want.

**Comment by Mytherin** [comment]
> Pseudonymity is normal on the internet and not an affront. I don't see filing an issue is "coming at you" or expecting free work. It would be better to explicitly have a document including expectations statements like: "Issues that abusive violate our [Code of Conduct](https://duckdb.org/code_of_conduct) will be closed without comment."

I agree that pseudonymity is normal, but going above and beyond to hide your identity is not. If you read the previous paragraph you would see that Bert is talking specifically about people trying to hide their identity. I would likely not answer emails from `123094242@temp-mail.com` either, for example. We have gotten plenty of opened issues from single-issue github accounts created specifically to open that issue. 

Bert also directly states that a pseudonym with a reputation is more than acceptable:

> Similarly, many internet users are pseudonymous - we may not know exactly who they are, but they have developed a reputation by being part of the community. I love to work with them.

Generally people sign off emails with their name. Some form of introducing yourself is just general human politeness, even on the internet, would you not say so?

> IMO, If there's a bug in the software it should always be reported even if its immediately closed and not investigated. Its valuable to other users who encounter the same bug later, potentially valuable for developers, although clarifying issues and triage has a real cost. Expectations could be clearly stated somewhere "DuckDB is an open source project with no obligation to investigate or resolve any issue. Please contact DuckDB labs for commercial support".

That sounds nice, and I agree in principle, but when you get bug reports like "the software does not work" then there is no value to be had for neither users nor developers. Many issues opened are also just not bug reports, but rather feature requests, often for complex to build features. People also often confuse bugs and feature requests - where people mistake "it does not do what I want it to do" for a bug, when it is often also just a lack of a feature that they desire.

If bug reports are reproducible and clear I have no issue addressing the problem regardless of whether or not the user is anonymous. But issues exist on a wide range of usefulness and quality. In my experience requesting people to disclose their identity pushes the usefulness and quality of issues up and stops people from hastily opening up bug reports. When a substantial amount of issues are opened daily, those differences add up and do matter.

> This section is kind of surprising to me. I'd expect something like disclosure to be handled by licensing terms rather than ugly moralizing language: "even have decency to admit that they use my software". I'm skeptical github issues with affiliation give projects credibility.

At a minimum it is nice to know what people use your software for and why. Licensing seems like a worse solution to this problem. Licensing would introduce additional restrictions on people using the software, whereas requiring affiliation disclosure only introduces restrictions when people ask for your time and attention with their issues.

> Why is Bert the judge of reasons people want anonymity?

He is not the judge of why people want anonymity, he is the judge of what he spends his time on. If all that is required to get free support from a world class software engineer is to introduce yourself - that seems like quite a bargain to me.

**Comment by eaubin** [comment]
> I agree that pseudonymity is normal, but going above and beyond to hide your identity is not. If you read the previous paragraph you would see that Bert is talking specifically about people trying to hide their identity. I would likely not answer emails from `123094242@temp-mail.com` either, for example. We have gotten plenty of opened issues from single-issue github accounts created specifically to open that issue. I imagine that Bert has gotten many more than us.
> 
> Bert also directly states that a pseudonym with a reputation is more than acceptable:

I don't think there's any disagreement on what I think you and Bert mean, although I don't like text from the justification. The issues page right now requests your 'Full Name', and you've got to dig into the post to understand that you're okay with established pseudonyms and not full names.  If your one of the people in the small set who don't want to put their full name and still write something its probably reasonable to read a justification.
 

> Generally people sign off emails with their name. Some form of introducing yourself is just general human politeness, even on the  internet, would you not say so?

Sure for general cases, IRL, or email. For issues I've actually wondered about the etiquette of given background on myself or a given project vs just getting the content.  I take it that your point is really using an intentionally obscured identity is inarguably rude.  I've not been in your shoes as a os maintainer, I had never considered the possibility of not adding a name to an issue (beyond my gh account) to potentially be rude.

> That sounds nice, and I agree in principle, but when you get bug reports like "the software does not work" then there is no value to be had for neither users nor developers. Many issues opened are also just not bug reports, but rather feature requests, often for complex to build features. People also often confuse bugs and feature requests - where people mistake "it does not do what I want it to do" for a bug, when it is often also just a lack of a feature that they desire.

Agree, triaging lots of low quality issues is rough.

> If bug reports are reproducible and clear I have no issue addressing the problem regardless of whether or not the user is anonymous. But issues exist on a wide range of usefulness and quality. In my experience requesting people to disclose their identity pushes the usefulness and quality of issues up and stops people from hastily opening up bug reports. When a substantial amount of issues are opened daily, those differences add up and do matter.

The above two paragraphs are a great and defensible justification, better than Berts.

> At a minimum it is nice to know what people use your software for and why. Licensing seems like a worse solution to this problem. Licensing would introduce additional restrictions on people using the software, whereas requiring affiliation disclosure only introduces restrictions when people ask for your time and attention with their issues.

I wasn't really suggesting anything regarding licensing, just general surprise that you might want it at all for an issue.

> He is not the judge of why people want anonymity, he is the judge of what he spends his time on. If all that is required to get free support from a world class software engineer is to introduce yourself - that seems like quite a bargain to me.

Indeed, its an amazing time when one can talk for free with world class people and agree to the extent that name and affiliation a good proxy for an introduction. Another take would be to explicitly add that to the issue template, allow people to say who they are and what their context is.

**Comment by hannes** [comment]
I think we're generally happy the way things are. Thanks for the discussion, but closing for now.

**Pull request closed without merging**
