### PR TITLE
enable callback with checkpoint lock

### PR DESCRIPTION
**Pull request by jkub**
It would be nice to execute code after checkpoint completes, but before the checkpoint lock is dropped.

There are two ways to achieve this.
1) Have Checkpoint() return the CheckpointLock, and let the caller destroy it after running the relevant code.
2) Run code as a callback, passed in parameter to checkpoint().

The latter seemed simpler, so that's what this PR does.

### CODE REVIEW

**Comment by jkub** [comment]
It looks like this will require changes to the sqlite_scanner extension as well before this lands, but does the approach make sense?

**Comment by jkub** [comment]
Another way of doing this would be to store the callback in the DB config. That would have the advantage of:
- Not breaking the extension interface.
- Invoked in all checkpoint paths, rather than just the explicit checkpoint.

I'd be happy to update PR to do that if it sounds better.

**Comment by Mytherin** [comment]
> Another way of doing this would be to store the callback in the DB config. That would have the advantage of:
> 
> * Not breaking the extension interface.
> * Invoked in all checkpoint paths, rather than just the explicit checkpoint.
> 
> I'd be happy to update PR to do that if it sounds better.

I think this approach would be better - also to avoid polluting the checkpoint interface (which is also used by the SQLite extension).

**Comment by Mytherin** [comment]
Closing for now - feel free to re-open if you want to discuss this again

**Pull request closed without merging**
