### PR TITLE
Fuzzer #215: Timestamp Arithmetic Overflow

### PR DESCRIPTION
**Pull request by hawkfish**
Use overflow testing for timestamp_t arithmetic.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM. Could you just have a look at coverage tests for the overflows and remove the trailing `;`?

**Comment by hawkfish** [comment]
Looks like two of them (`operator+` and `operator+=`) are not called anywhere.

**Comment by hawkfish** [comment]
Amusingly, the third one (`operator-=`) _shouldn't_ be called! I will fix it and add a test.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
