### PR TITLE
Cast INTERVAL and UUID to VARCHAR

### LINKED ISSUE #7: Unimplemented type for cast (INTERVAL -> TIME)
In the ODBC spec (see [sqlext.h](https://github.com/microsoft/ODBC-Specification/blob/4dda95986bda5d3b55d7749315d3e5a0951c1e50/Windows/inc/sqlext.h#L466)), the data type `INTERVAL` has the same data type identifier as `TIME`. When casting a DuckDB `INTERVAL` to an ODBC `INTERVAL`, I get the following error:

```
ODBC: ERROR [22007] ODBC_DuckDB->GetDataStmtResult Not implemented Error: Unimplemented type for cast (INTERVAL -> TIME)
```

Repro steps:
1. Create a new DuckDB database with an `INTERVAL` variable:
```
create or replace table test AS (
    select
        x * (INTERVAL 5 HOUR) as customer_interval_field
    from generate_series(1, 10) g(x)
);
```

2. Load the data into Power Query with the following script:
```
let
    Database = "path\to\test.db",
    OdbcDatasource = DuckDB.Contents(Database)
in
    OdbcDatasource{[Item="test"]}[Data]
```

3. This throws the error:
```
ODBC: ERROR [22007] ODBC_DuckDB->GetDataStmtResult Not implemented Error: Unimplemented type for cast (INTERVAL -> TIME)
```

This may need to be addressed in the DuckDB ODBC driver.

Related to #5 .

### PR DESCRIPTION
**Pull request by guenp**
Fixes https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/issues/7.

Power Query/Power BI currently does not support `INTERVAL` and loading data with this type results in an error:
```
ODBC: ERROR [22007] ODBC_DuckDB->GetDataStmtResult Not implemented Error: Unimplemented type for cast (INTERVAL -> TIME)
```

Similarly, implementing a cast to `TIME` also won't work because in Power Query, valid values for `TIME` hours are 0-23.

`UUID` has a similar problem that it throws an "Unimplemented type for cast (UUID -> DOUBLE)` error.

This PR casts `INTERVAL` and `UUID` to `VARCHAR` by default. The `INTERVAL` value can be parsed separately in Power Query, for instance by using `Duration.FromText` (see [docs](https://learn.microsoft.com/en-us/powerquery-m/duration-functions)).

image

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! I wonder what the Postgres ODBC clients' behavior is, as they have the same interval type that we do. Do they just cast to VARCHAR as well or do something different? We should likely do what they do here.

**Comment by Mytherin** [comment]
Looks like [they have an ifdef](https://github.com/hiinoue/psqlodbc/blob/f28b1dcc197c8775d6a34a419d73a0cfa97fa643/pgtypes.c#L127) and likely turn it into varchar in regular releases as some applications don't handle the interval type correctly.

**Comment by guenp** [comment]
thanks @Mytherin for taking a look!
Indeed, it looks like Postgres doesn't offer interval support for the ODBC driver either:
https://github.com/hiinoue/psqlodbc/blob/f28b1dcc197c8775d6a34a419d73a0cfa97fa643/pgtypes.h#L82
```
/*
 *	SQL_INTERVAL support is disabled because I found
 *	some applications which are unhappy with it.
 *
#define	PG_INTERVAL_AS_SQL_INTERVAL
 */
```

I can't find anywhere in the code that they convert `INTERVAL` to `VARCHAR` so I wonder if it's simply not supported.

**Comment by maiadegraaf** [comment]
Hi Guen, thanks for your PR, could you reopen it on the new [ODBC repo](https://github.com/duckdb/duckdb-odbc)?
Thanks!

**Pull request closed without merging**
