### PR TITLE
Optionally allow for queries to start with FROM, instead of with SELECT

### PR DESCRIPTION
**Pull request by Mytherin**
The following SQL queries are now valid:

```sql
-- SELECT clause is optional, SELECT * is implied (if not included)
FROM tbl;

-- first 5 rows of the table
FROM tbl LIMIT 5;

-- select comes right after the from, after that the query follows the usual order
FROM tbl SELECT SUM(col) GROUP BY grp;

```

### CODE REVIEW

**Comment by domoritz** [comment]
In the last query, what happens with grp in the select? Is it implicit?

**Comment by Mytherin** [comment]
Ah no, it is equivalent to the query with SELECT in the front. You don’t need to mention all groups in the SELECT (although not doing so is nearly always a mistake, as it was here :))

**Comment by djouallah** [comment]
got an error here 
From'lineitem' sum(L_quantity)  group by l_shipmode;
BinderException: Binder Error: column "L_quantity" must appear in the GROUP BY clause or be used in an aggregate function

**Comment by Mytherin** [comment]
You are missing a `SELECT`:

```sql
From'lineitem' SELECT sum(L_quantity) group by l_shipmode;
```

Strangely enough, your query is still passes our parser. It is equivalent to the following:

```sql
SELECT * FROM 'lineitem' AS sum(l_quantity) GROUP BY l_shipmode;
```

**Comment by djouallah** [comment]
sorry, don't shoot at me :), can we get read of select :)

**Comment by Mytherin** [comment]
That doesn't work because of ambiguities in the grammar (as your own query demonstrated).

**Pull request merged**
