### PR TITLE
bump spatial + VCPKG Commit

### PR DESCRIPTION
**Pull request by Maxxen**

### CODE REVIEW

**Comment by carlopi** [comment]
This is failing on Linux, likely due to VCPKG version mismatch, waiting on the [windows CI](https://github.com/duckdb/duckdb/actions/runs/12196884377/job/34027623952?pr=15158) to check also there, this might be blocked on bumping default vcpkg (that might be requiring moving a bunch of extensions out of core). 

Thanks, either way I think this might not work in the current status.

**Comment by carlopi** [comment]
Actually solution might be just bump vcpkg AND remove anything that is not compatible with newer VCPKG, and integrating that over time.

**Review by carlopi — APPROVED** [review]
Thanks!! I think it does make sense.

Linux CI passes, waiting for the other ones, but removing `iceberg` might be the only needed to be removed.

This means that, `iceberg` would not be able to be mixed-and-matched with other extensions, or built in an trivial way via `CORE_EXTENSIONS`, so we should aim at bringing support back, but that can be experiment on that extension's CI.

Note that we could also always build it on a side, if needed, I'd say this is not a blocker.

I would add a note to `.github/config/out_of_tree_extensions.cmake`, maybe first waiting for CI to go through also on other platforms.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
