### PR TITLE
feat: refactor getting tie_break_offset in SelectBestMatch

### PR DESCRIPTION
**Pull request by stephaniewang526**
We have a case where we need access to the tie break offset of different secret storages when we do `LookupSecrets` in one secret storage (the one on the server side). This refactor adds "tie break offset" of a secret storage to the parameter list of `SelectBestMatch` method so that this function can be more flexibly used without needing to rely on the class it belongs to (GetTiebreakOffset()). As a result, I'm also changing this function to `static` (still `protected`) in SecretStorage to make it clear that it's not tied to any class instance and adding `tie_break_offset` to be a const parameter when instantiating a SecretStorage class to ensure that this value doesn't get modified after initialization.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

There's still a few CI failures remaining here - could you have a look?

**Comment by stephaniewang526** [comment]
I took a look at the ["Tidy Check" failures](https://github.com/duckdb/duckdb/actions/runs/12358477146/job/34489183135?pr=15235). Those are irrelated to the code changes in this PR (even adding a comment in the secret_storage.hpp file will trigger the same failures when running `make tidy-check-diff`). However, I pushed a fix in https://github.com/duckdb/duckdb/pull/15235/commits/5518fe09546b8b6a68f1ec3e2ef1aceeeeedddfa. Hope it's reasonable.

**Review by samansmink — APPROVED** [review]
LGTM!

**Comment by hannes** [comment]
Thanks!

**Pull request merged**
