### PR TITLE
Prepare documentation for CRAN release

### LINKED ISSUE #740: R: Split documentation
The following functions should get their own man page:

- [x] `src_duckdb()` (unless #739)
- [ ] `duckdb_register()` and `duckdb_unregister()`
- [ ] `read_csv_duckdb()`

I'm not sure we need to redocument all DBI methods here, perhaps a link to DBI documentation is sufficient?

After #738.

### PR DESCRIPTION
**Pull request by krlmlr**
Also implement `duckdb_read_csv()` consistently with `duckdb_register()`.

Closes #740.

### CODE REVIEW

**Comment by krlmlr** [comment]
The commits are good for individual review. The first three commits are technical, https://github.com/cwida/duckdb/pull/865/files/9e4dba0874cec6eff1f0f8f952944de40b428229..e5470d8ded0076ef54bb25dae4117ac9ca4a57b5 (the last four commits) is also a good subset for review.

**Comment by krlmlr** [comment]
Ouch. I'll look into the check failures.

**Comment by krlmlr** [comment]
Tests pass now.

**Comment by hannesmuehleisen** [comment]
thanks!

**Pull request merged**
