### PR TITLE
CI: Skip any CI on branches named 'feature' or 'master'

### PR DESCRIPTION
**Pull request by carlopi**
master will be run nightly, feature as required

### CODE REVIEW

**Comment by Mause** [comment]
If we want the ability to run jobs on demand you need to add the workflow dispatch trigger?

**Comment by Mause** [comment]
Which we'll probably want for the 'feature' branch

**Comment by carlopi** [comment]
We were discussing earlier with @Mytherin, we were aware of the dispatch trigger, but decided to start adding the basic setup "just no checks".

Currently there are a few potential workaround, like having the checks run on on forks, that should make it doable on the short term, I will add workflow's trigger to the list of CI 'nice to have' list, and probably would be cool to have in general that any given commit could be tested independently with the click of a button, ideally even having a no-code way of choosing a single workflow.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
