### PR TITLE
Add httpfs to python conda package

### PR DESCRIPTION
**Pull request by snoe925**
I use this with S3 and on premise Ceph S3.  Having it in Conda would be a help to me.
I do not think this increases the dependency footprint at all.  It is all handled by cmake so hopefully condaforge just works.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

We explicitly removed HTTPFS as a default extension because of the (rather unavoidable) dependency on OpenSSL, which caused building/linking problems for several people. You should be able to install the HTTPFS extension using the built-in extension management system, by running the following SQL statements:

```sql
INSTALL 'httpfs';
LOAD 'httpfs';
```

Does this not work for you?

**Comment by snoe925** [comment]
I am running in the conda-forge install.  Here is my attempt at the install and load commands above.
```
$ python
Python 3.8.5 (default, Aug  3 2020, 16:08:50)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> con = duckdb.connect(database=':memory:')
>>> con.execute("INSTALL 'httpfs';")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/5aebf7dac/linux_amd64/httpfs.duckdb_extension.gz
>>>
(duckdb2) snoe@hc25:~/git/rdm-code.bbg_price$ wget 'http://extensions.duckdb.org/5aebf7dac/linux_amd64/httpfs.duckdb_extension.gz'
--2022-02-26 17:09:02--  http://extensions.duckdb.org/5aebf7dac/linux_amd64/httpfs.duckdb_extension.gz
Resolving extensions.duckdb.org (extensions.duckdb.org)... 108.156.91.14, 108.156.91.72, 108.156.91.46, ...
Connecting to extensions.duckdb.org (extensions.duckdb.org)|108.156.91.14|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-02-26 17:09:02 ERROR 403: Forbidden.
```
Can I set the URI to a local resource? Ideally I would also get the gz file from the Conda install also.

**Comment by snoe925** [comment]
There is no particular reason for the conda-forge to use the build script, tools/pythonpkg/setup.py, exactly from the duckdb repo for conda.  There is already one patch.  Adding httpfs could be patched in that build.
I could see perhaps a conda specific one.  I don't know who manages the Conda scripts.
https://github.com/conda-forge/python-duckdb-feedstock/blob/78c2a2b6429a974c8319d5ad4eb19234cd314030/recipe/meta.yaml#L17

**Comment by snoe925** [comment]
I am going to explore following up with the Conda build process.

**Pull request closed without merging**
