### PR TITLE
[PythonDev] Remove version lock on `adbc_driver_manager`

### PR DESCRIPTION
**Pull request by Tishj**
As discussed in #8711 we should not lock this version, it also breaks CI because 0.6.0 is not available on 3.7 it seems:
https://github.com/duckdb/duckdb/actions/runs/6019011030/job/16328603698

### CODE REVIEW

**Review by Mause — CHANGES_REQUESTED** [review]
If we don't have 0.6.0 on 3.7, we'll need to update the exception message assertion - it's a regex, so just use | with the two messages I guess?

**Comment by carlopi** [comment]
Python 3.7 (and 3.8) worked fine inside the Python.yml, https://github.com/duckdb/duckdb/actions/runs/6019011035.
The failure is somehow relevant only to the "Python 3 tarbal" job as run by the Nightly.yml workflow: https://github.com/duckdb/duckdb/actions/runs/6019011030/job/16328603698, unsure what the differences might be there.

Also to note that here: https://pypi.org/project/adbc-driver-manager/ it says it supports only Python >= 3.9, just to add confusion.

**Comment by Tishj** [comment]
> If we don't have 0.6.0 on 3.7, we'll need to update the exception message assertion - it's a regex, so just use | with the two messages I guess?

I think they both contain "INVALID INPUT" so it should be fine, though I admit, not ideal

**Comment by Tishj** [comment]
@carlopi they might have different behavior for the requirements?

Looks like the tarball build fails if the requirement isn't met
Maybe the other just doesnt install

The test contains
`adbc_driver_manager = pytest.importorskip("adbc_driver_manager")` so it should just get skipped if it cant be installed eitherway

**Comment by Tishj** [comment]
Of course `requirements-dev.txt` does not have the option to make a package optional :upside_down:

We might just want to look into improving our python build workflow, I think Elliana has mentioned some ideas for this in the past

**Comment by Tishj** [comment]
I don't think this fixes it in its current state, the problem I think is adding `adbc_driver_manager` to the `requirements-dev.txt`

**Comment by carlopi** [comment]
Is this ready to be merged?

**Comment by Tishj** [comment]
failures seem unrelated

**Comment by Tishj** [comment]
Every `adbc_driver_manager` version 0.4.0 and up are supported
0.3.0 is not supported because:
```
AttributeError: 'adbc_driver_manager._lib.AdbcStatement' object has no attribute 'get_parameter_schema'
```

**Pull request merged**
