### PR TITLE
Python/JSON-Style Struct & List Syntax 

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds Python/JSON style syntax support for STRUCT and LIST entries, i.e. the following statements are now valid:

```sql
SELECT {'i': 3, 'j': 4};
-- equivalent to STRUCT_PACK(i := 3, j := 4)
SELECT [1,2,3];
-- equivalent to LIST_VALUE(1, 2, 3)
SELECT {'i': [1,2, 3], 'j': 4};
-- equivalent to STRUCT_PACK(i := LIST_VALUE(1,2,3), j := 4)

-- quotes are optional
SELECT {i: 3, j: 4};
-- double quotes are also allowed
SELECT {"i": 3, "j": 4};
```

This PR also changes the struct -> string conversion to follow the same style, so the string conversion can be round-tripped easily:

```sql
SELECT {'i': 3, 'j': 4}::VARCHAR;
-- {'i': 3, 'j': 4}
```

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
This looks really great! I think the string_agg(struct_pack, ',') type of syntax may be enough for us to stop recommending SQLite for JSON manipulation!  

I had one quick question. You mentioned double quotes above, but if I were to use double quotes around the column identifiers, would the values (if strings) also be wrapped in double quotes? That would allow us to essentially "cast as JSON", right?

**Comment by Mytherin** [comment]
> I had one quick question. You mentioned double quotes above, but if I were to use double quotes around the column identifiers, would the values (if strings) also be wrapped in double quotes? That would allow us to essentially "cast as JSON", right?

> Essentially, if I cast a struct as a varchar, can I choose to use double quotes across the board in some way?

Sadly no, this will require some other form of casting outside of the parser. Double quotes in SQL-land are used for column identifiers, and interpreting that as a string at times would create weird situations, e.g. consider the following piece of SQL:

```sql
SELECT {'i': "j"} FROM tbl;
```

What does "j" mean? Currently this will always refer to the column "j" and has no ambiguity, i.e. this is equivalent to:

```sql
SELECT {'i': j} FROM tbl;
```

Parsing the "j" as a string in certain situations seems like asking for trouble.

Instead, we will add support for actual JSON parsing in the future that should allow for this type of conversion (so you could do e.g. `SELECT json_parse('...')`).

**Comment by Alex-Monahan** [comment]
Yes, that makes a lot of sense. I guess that would make round trips from struct to varchar fail, even if maybe it were possible to go from struct to varchar with double quoted values. It would be a 1 way ticket!

**Comment by wizzard0** [comment]
Wow, that is seriously cool. I assume `SELECT {"i": 5}` uses the value of the column named 'i' as the dictionary key, right?

**Comment by Mytherin** [comment]
`SELECT {'i': 5}` creates a single struct that contains as key the literal string "i" and as value the value 5. Structs are required to have a consistent schema across rows, so you can vary the value provided, but not the keys.

```sql
SELECT {'i': range} FROM range(3);
┌────────────────────┐
│ struct_pack(range) │
├────────────────────┤
│ {'i': 0}           │
│ {'i': 1}           │
│ {'i': 2}           │
└────────────────────┘
```

Consider this similar to the `struct` type in C/C++, e.g. this will be similar to:
```cpp
struct {
   int i;
};
```

And a table is then defined as a set of those structs.

If you want to create a dictionary that has a non-fixed schema (i.e. the schema can be different on a per-row basis) you can use the MAP type instead. 

```sql
SELECT MAP([case when range % 2 == 0 then 'i' else 'j' end], [range + 2]) m FROM range(3);
┌───────┐
│   m   │
├───────┤
│ {i=2} │
│ {j=3} │
│ {i=4} │
└───────┘
```

You can use the subscript to extract from the map, which will provide you with the entry if one exists:

```sql
SELECT MAP([case when range % 2 == 0 then 'i' else 'j' end], [range + 2])['i'] m FROM range(3);
┌─────┐
│  m  │
├─────┤
│ [2] │
│ []  │
│ [4] │
└─────┘
```

For now maps cannot yet be stored persistently in the database, but that is being worked on and will most likely be part of the next release (#1904).

**Comment by wizzard0** [comment]
I see. Always impressed by the details of your examples. Maybe it makes sense to disallow double-quotes in keys for clarity?

**Comment by Mytherin** [comment]
I agree that it would be more clear, but in general we try to be rather permissive on issues where there is no semantic ambiguity, e.g. we also allow `SELECT * FROM 'table'` or `SELECT 1 AS 'myname'` (inspired by SQLite which allows the same syntax). For now I think I will keep it as-is. Perhaps we will switch it around if it ends up being confusing to many others.

**Pull request merged**
