### PR TITLE
feat: rewrite which_secret() into a table function

### PR DESCRIPTION
**Pull request by stephaniewang526**
This will allow us to return more information from which_secret() while also facilitate us greatly in allowing this to be executed in a hybrid fashion.

cc @samansmink @bleskes

### CODE REVIEW

**Comment by stephaniewang526** [comment]
The [CI test failure](https://github.com/duckdb/duckdb/actions/runs/8746171515/job/24003132292?pr=11726#step:5:14557) is addressed by: https://github.com/duckdb/duckdb_aws/pull/40
Not sure if I need to bump the submodule at this time also somewhere?

**Review by samansmink — COMMENTED** [review]
Hey @stephaniewang526! thanks for the PR, looks good! 

Regarding the CI failure; in DuckDB CI we also run the tests for the out-of-tree extensions on every PR. This means that any change breaking an out-of-tree extension's build OR tests will fail CI. The solution is to add a patch file in your PR here. So basically you would add the patch file applying https://github.com/duckdb/duckdb_aws/pull/40 in this PR, then apply the patch in duckdb_aws later. For more details check https://github.com/duckdb/duckdb/tree/main/.github/patches/extensions

**Comment by stephaniewang526** [comment]
Hi @samansmink , thanks for the pointer. I added the patch.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
