### PR TITLE
Add Constant Segment Compression to Storage

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds support for constant segments to the storage layer. During a checkpoint when the system detects that all the rows in a column segment have the same value by looking at the statistics (e.g. min=3, max=3 for numeric segments, or has_null=false for a validity segment) we avoid writing the segment entirely. We only write the metadata to the file (mainly the statistics) together with a block_id of `-1`. 

When reading the file we can create constant segments for any segment that has this invalid block_id. The constant segment will emit constant vectors when scanned and doesn't need to read any actual data from disk (besides the metadata upon construction). 

While this is rather limited it does work nicely with validity segments, since we can avoid writing any null values for column (segments) that do not have any values, and can avoid writing any values at all when columns have only NULL values.

```sql
-- 1 billion values
create table integers as select null i from range(1000000000);
pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 10.7MB        │ 262144     │ 41           │ 41          │ 0           │ 0 bytes  │ 0 bytes      │ 13.7GB       │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘

-- before (without compressed segments)
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 6.4GB         │ 262144     │ 24457        │ 24457       │ 0           │ 0 bytes  │ 2.1GB        │ 13.7GB       │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
```

It's also a good pre-cursor to getting actual compression working since it detects/fixes several assumptions of having uncompressed vectors come out of the storage.

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Does this compress varchar column segments if the entire vector-sized segment is a single value? So should I order my string columns before insertion to get some compression? Exciting stuff!

**Comment by Mytherin** [comment]
> Does this compress varchar column segments if the entire vector-sized segment is a single value? So should I order my string columns before insertion to get some compression? Exciting stuff!

Right now this is only for numerics and validity segments (i.e. null masks). It's also not really traditional compression yet - it only works if there are many of the exact same values in a row (e.g. you need to have at least 65K 4-bit integers of the same value). It will reduce your database size if you have columns without null values or columns that are very constant but in general it won't do too much.

Actual compression hopefully to follow :)

**Comment by Alex-Monahan** [comment]
Makes sense! I bet it helps a lot with those validity segments! 
I was confused and thinking that it would only require vector-sized constants in a row (1024), so what parameter governs the 65K that you mentioned? Just the size of a block of storage?

Thanks as always!

**Comment by Mytherin** [comment]
> Makes sense! I bet it helps a lot with those validity segments!
> I was confused and thinking that it would only require vector-sized constants in a row (1024), so what parameter governs the 65K that you mentioned? Just the size of a block of storage?
> 
> Thanks as always!

Yes indeed, the size of a complete block (or column segment) on storage. This is 256KB, so for a 4-byte integer this will fit around 65K values.

**Pull request merged**
