### PR TITLE
Implement sharable Buffer Pool across DatabaseInstances

### PR DESCRIPTION
**Pull request by jkub**
This separates priority-eviction from everything else BufferManager does, into a new class called BufferPool. A BufferPool can be set on a DBConfig, enabling many DatabaseInstances to share a memory limit and priority eviction queue.

Meanwhile, the EvictBlocks method is virtual, which enables an extension to implement dynamic memory limits.

I also changed IncreaseUsedMemory and DecreaseUsedMemory to just call ReserveMemory and FreeReservedMemory, respectively, since they seemed to do the same thing.

### CODE REVIEW

**Comment by Tishj** [comment]
This is going to make for some fun merge conflicts in #5683 

But besides that I do like the sound of these changes 👍 !

**Comment by jkub** [comment]
@Mytherin this ODBC workflow failure repros consistently but looks unrelated to my change. It also failed on my fork.

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! Looks great to me. Could you just merge with the feature branch and resolve the merge conflicts?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
