### PR TITLE
[httpfs] Add HTTPGetRequest & HTTPPostRequest functions

### PR DESCRIPTION
**Pull request by ahuarte47**
This PR adds two functions to the httpfs extension, to send HTTP Get & Post requests.

Description & sample usage [here](https://www.linkedin.com/pulse/querying-stac-load-satellite-imagery-sentinel2-duckdb-alvaro-huarte-yjuzf/)

### CODE REVIEW

**Comment by lmangani** [comment]
👋 @ahuarte47 this PR got quite old and I guess it won't likely be merged but I thought it was useful so - just for fun - we are recreating functions similar to this PR into a [stand-alone extension](https://github.com/quackscience/duckdb-extension-httpclient) if you'd like to continue please jump in! Thanks for sharing!

**Comment by ahuarte47** [comment]
@lmangani thanks for this! 
I was waiting for any feedback, but maybe it did not seem as interesting to get merged. Having a specific extension for that methods really seems a great option.

**Comment by lmangani** [comment]
> @lmangani thanks for this! I was waiting for any feedback, but maybe it did not seem as interesting to get merged. Having a specific extension for that methods really seems a great option.

I'm happy if you are! I already got the GET function working and have some issues left to work on with POST. We can then simplify a few aspects and add some parameters to control settings (follow redirects, etc). If you'd like to work on this just fire up an issue in the new repo and I'll give you full access.

**Comment by ahuarte47** [comment]
Obviously the downside is that the extension duplicates existing code from another extension, but it gets the job done.

**Comment by lmangani** [comment]
I'm certain the DuckDB team will come up with ways to help us avoid this in the future, but since we're using the existing httplib.hpp there's nothing extra being introduced to the codebase other than the two custom GET/POST functions. Let's continue the discussion on the new repo, I just invited you 👋

**Comment by ahuarte47** [comment]
> I'm certain the DuckDB team will come up with ways to help us avoid this in the future, but since we're using the existing httplib.hpp there's nothing extra being introduced to the codebase other than the two custom GET/POST functions. Let's continue the discussion on the new repo, I just invited you 👋

Thanks, but I am wondering if we should have another copy of the [httpfs.cpp](httpfs.cpp). They are updating it.
@carlopi

**Comment by lmangani** [comment]
> Thanks, but I am wondering if we should have another copy of the [httpfs.cpp](https://github.com/duckdb/duckdb_httpfs/blob/main/extension/httpfs/httpfs.cpp). They are updating it. FYI: @carlopi

The file is in the repo only as reference for certain parts of the implementation and can be imported (if needed) from the main repo, but its best to discuss this where the issue is rather than in this PR?

**Comment by ahuarte47** [comment]
Closing this in favor of extension by @lmangani

**Pull request closed without merging**
