### PR TITLE
[Relation API] Dont push DISTINCT modifier for EXCEPT/INTERSECT ALL

### LINKED ISSUE #12592: `DuckDBPyRelation.intersect()` (Python function API) implicitly performs `.distinct()` operation (i.e. deduplicates for set semantics)
### What happens?

Python function API `.intersect()` method "*promises*" bag semantics (as suggested in documentation, and as shown by `.sql_query()` method.
However, it actually *delivers* set semantics (i.e. implied `.distinct()`).

### To Reproduce

```python
import duckdb
test = duckdb.sql("SELECT 1 from range(5)")
test
```
```
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
│     1 │
│     1 │
│     1 │
│     1 │
└───────┘
```
i.e. `test` is a table with duplicates.
Intersection with itself should leave it unchanged:
```python
test.intersect(test).sql_query()
```
```sql
'(SELECT 1 FROM range(5)) INTERSECT ALL (SELECT 1 FROM range(5))'
```
i.e. `sql_query()` promises bag semantics (`ALL`), which indeed is provided via `sql()` (DB API):
```python
duckdb.sql(test.intersect(test).sql_query())
```
```
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
│     1 │
│     1 │
│     1 │
│     1 │
└───────┘
```
However, using the function API deduplicates:
```python
test.intersect(test)
```
```
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
└───────┘
```

### OS:

Windows 11

### DuckDB Version:

1.0

### DuckDB Client:

Python (3.12)

### Full Name:

Olaf

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #12592 

The ALL variation of a SET OPERATION should have bag semantics.
Previously we pushed a DISTINCT for all except/intersect SetOpRelations, presumably this is because `setop_all` did not exist at the time.

### CODE REVIEW

**Comment by Tishj** [comment]
@Tmonster I imagine this will also have effects in the R repo?

**Comment by Tishj** [comment]
@Mytherin could you restart this? <https://github.com/duckdb/duckdb/actions/runs/9583961444/job/26426417615?pr=12599>

**Comment by Mytherin** [comment]
LGTM - perhaps indeed @Tmonster wants to have a look as well

**Review by Tmonster — APPROVED** [review]
I ran the R tests locally with this branch. I did not observe any breakages.
R users can only create 
- `union_all` (with setup_all=true), 
- `set_diff`
- `set_intersect`

the creation of set_diff and set_intersect are created with `setop_all=false`  by default, so the distinct is still pushed and the functionality remains the same. This is in line with R functionality. 


So LGTM 👍

**Comment by Tishj** [comment]
@Mytherin is this ready to merge?

**Comment by Mytherin** [comment]
Yep, thanks!

**Pull request merged**
