### PR TITLE
Fix an issue where parameters would be promoted to `NULL`, incorrectly causing `PREPARE` to fail

### PR DESCRIPTION
**Pull request by Mytherin**
e.g. the following query would fail because of the mixing of `NULL` and `UNKNOWN` turning into `NULL`, which would then bind the division operator to `INTERVAL / BIGINT` causing a strange error.

```sql
D PREPARE v1 AS SELECT COALESCE(COALESCE(NULL, $1) / 42::BIGINT, 0.5);
-- Binder Error: Cannot mix values of type INTERVAL and DECIMAL(2,1) in COALESCE operator - an explicit cast is required
```

This PR changes the behavior so that `COALESCE(NULL, UNKNOWN)` results in `UNKNOWN`, which then causes a rebind to happen when the parameter type is known.

In addition, we also fix an issue in `ToString()` of functions so that functions that contain special characters are correctly quoted.

### CODE REVIEW

**Comment by Mytherin** [comment]
I'm somewhat puzzled by the regression failure in Pandas analyze, but it seems to reproduce. @Tishj could you perhaps have a look? I suppose this is related to the changes in `CombineUnequalTypes` which is used in `LogicalType::TryGetMaxLogicalType` - but I don't see how this could lead to this performance regression (or even how this code affects the pandas analyze)

**Comment by Tishj** [comment]
17 to 217 seconds o.o
I'll have a look, I also have no idea what could be causing this

**Comment by Tishj** [comment]
I am suspecting that these are no longer skipped:
`data = [None] * 9999999 + [1]  # Last element is 1, others are None`

**Comment by Tishj** [comment]
@Mytherin I profiled it, and it looks like all the time is going into `SetValue`:
```c++
void ScanNumpyObject(PyObject *object, idx_t offset, Vector &out) {

	if (object == Py_None) {
		SetInvalidRecursive(out, offset);
		return;
	}

	auto val = TransformPythonValue(object, out.GetType());
	out.SetValue(offset, val); // <---- here
}
```

I'll look into why this is not heading into `(if object == Py_None)` for everything but 1 of them.

For reference, the script I'm using to replicate the benchmark is:
```py
import pandas as pd
import duckdb

con = duckdb.connect()

data = [None] * 9999999 + [1]  # Last element is 1, others are None
pandas_df = pd.DataFrame(data, columns=['Column'], dtype=object)
res = con.execute("""select * from pandas_df""").df()
```

**Comment by Tishj** [comment]
So it's not going in there because the value is in fact `nan`, not `None`.

I think the regression here can be traced down to `vector.SetValue(val)` where `val.IsNull()` is true

**Comment by Mytherin** [comment]
That's strange - that code path should not be affected. Are we perhaps returning `LogicalTypeId::UNKNOWN` somewhere in the Python code instead of `LogicalTypeId::NULL` which is now causing `nan` to be generated?

**Comment by Tishj** [comment]
> That's strange - that code path should not be affected. Are we perhaps returning `LogicalTypeId::UNKNOWN` somewhere in the Python code instead of `LogicalTypeId::NULL` which is now causing `nan` to be generated?

I meant that the python value is `nan`, so we enter TransformPythonValue, which comes back with:
```c++
		if (nan_as_null && std::isnan(PyFloat_AsDouble(ele.ptr()))) {
			return Value();
		}
```

**Comment by Mytherin** [comment]
Thanks @Tishj  - seems to have been fixed

**Pull request merged**
