### PR TITLE
Add handling for duckdb-wasm extensions in extension-upload-from-nightly

### PR DESCRIPTION
**Pull request by carlopi**
I think this should be about it.

It can then be tested with the soon to get published on nightly sqlite_scanner extension.

### CODE REVIEW

**Review by samansmink — COMMENTED** [review]
@carlopi I believe this will not work for the versioned paths (when specifying an extension commit) At least the paths i see for the quack extension in s3 don't match this script, i think the BASE_NIGHTLY_DIR is different for the wasm paths

**Comment by carlopi** [comment]
This indeed do not work for versioned paths, but good side is that they are currently never generated, given it's unclear to me how the convention should be generalized.

Recap on the situation:
non-wasm extensions: `${extension_repository} / ${duckdb_version} / ${platform} / ${name}.duckdb_extension.gz`
non-wasm versioned extensions: `${extension_repository} / ${name} / ${extension_version} / ${duckdb_version} / ${platform} / ${name}.duckdb_extension.gz`
wasm extensions: `${extension_repository} / duckdb-wasm / ${duckdb_version} / ${platform} / ${name}.duckdb_extension.wasm`

Natural extension would be for wasm versioned extensions to be at:
`${extension_repository} / duckdb-wasm / ${name} / ${ extension_version} / duckdb-wasm / ${duckdb_version} / ${platform} / ${name}.duckdb_extension.wasm`
This is doable, needs only an extra switch, but looks somewhat clunky to me.

Probably my preferred way out would be dropping the `duckdb-wasm` prefix completely, and make it uniform (where it's the extension suffix that dictates compression & metadata).

**Comment by carlopi** [comment]
I think changes should have been addressed now, will need to double check with @samansmink, but this PR + https://github.com/duckdb/extension-template/pull/49 should work together.

**Review by samansmink — APPROVED** [review]
Looks good!

**Pull request merged**
