### PR TITLE
Incremental Checkpointing

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds incremental checkpointing to the storage. That means that checkpoints no longer involve rewriting the entire database, but now rewrite only new tuples that have been introduced or blocks that have been altered/changed. This PR also changes when checkpoints are run:

* Checkpoints are no longer run on startup. 
* Checkpoints are automatically triggered on committing a transaction when the WAL exceeds a certain size (set by `PRAGMA checkpoint_threshold=X`, default `PRAGMA checkpoint_threshold='16MB'`).
* Checkpoints are automatically triggered when shutting down the database, unless `PRAGMA disable_checkpoint_on_shutdown` is used. When the system shuts down successfully the WAL is also deleted, meaning the database is fully contained within the database file.
* Checkpoints can now be manually run using the `(FORCE) CHECKPOINT` commands.

Checkpoints operate using "stop-the-world" (for now?), meaning that while checkpointing all clients are locked and no new transactions can be initiated. Checkpoints also cannot be performed when there are transaction local changes present in the database. If there are transactions running concurrently:

* Checkpoints that are automatically triggered will not be performed (no error will be thrown - but the WAL might grow much larger than the `checkpoint_threshold` if no checkpointing is possible).
* The regular `CHECKPOINT` command will throw an error message if there are other concurrently running transactions present.
* `FORCE CHECKPOINT` can be used to force a checkpoint, but be warned that this will **abort** any concurrently running transactions as a work-around.

In addition this PR introduces `PRAGMA database_size` that reveals various storage-related stats about the currently running database, for example:

```sql
$ build/release/duckdb test.db
-- empty database
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 0 bytes       │ 262144     │ 0            │ 0           │ 0           │ 0 bytes  │ 0 bytes      │ Unlimited    │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
-- create a small table (below checkpoint threshold)
D create table integers as select * from range(10000) tbl(i);
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 0 bytes       │ 262144     │ 0            │ 0           │ 0           │ 80KB     │ 262KB        │ Unlimited    │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
-- insert a small amount of data (still below checkpoint threshold)
D insert into integers select * from range(100000);
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 0 bytes       │ 262144     │ 0            │ 0           │ 0           │ 882KB    │ 1.0MB        │ Unlimited    │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
-- insert a large amount of data (now a checkpoint will occur)
D insert into integers select * from range(10000000);
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 84.1MB        │ 262144     │ 321          │ 321         │ 0           │ 0 bytes  │ 0 bytes      │ Unlimited    │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
```

Note that there are still some limitations to the checkpointing:

* Deleted tuples will not be vacuumed yet, meaning they will remain as "ghost tuples" within the system (even if large amounts of tuples are deleted).
* Updates require rewriting entire (256KB) blocks, even if only individual tuples are updated.
* Blocks cannot be split up between different columns yet, meaning even small tables will take up at least `256KB` per column.

This PR should address #49, #926, #1341, #420, #973, #1257 (and perhaps others I have missed).

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
This is fantastic news! All of the limitations you mention are not an issue for my use case. I also think that they'll be minor or a total non-issue for the core analytical workloads that DuckDB is focused on. This will be a huge performance advance for me!

**Comment by Mytherin** [comment]
> This is fantastic news! All of the limitations you mention are not an issue for my use case. I also think that they'll be minor or a total non-issue for the core analytical workloads that DuckDB is focused on. This will be a huge performance advance for me!

Great that it will be useful to you! When it's merged into master it would be very useful if you could test it out to check if I missed any potential issues, before we push it into the next release :)

**Comment by Mytherin** [comment]
Some performance numbers for lineitem TPC-H SF10, for reference:

```sql
D PRAGMA checkpoint_threshold='10TB';
D select count(*) from lineitem;
┌──────────────┐
│ count_star() │
├──────────────┤
│ 59986052     │
└──────────────┘
-- adding 100K rows and checkpointing
D insert into lineitem select * from lineitem limit 100000;
D checkpoint;
┌───────────────────────────┐
│         CHECKPOINT        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.21s)          │
└───────────────────────────┘  
-- adding a column and checkpointing
D alter table lineitem add column l_newcolumn integer default 3;
D checkpoint;
┌───────────────────────────┐
│         CHECKPOINT        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (1.04s)          │
└───────────────────────────┘    
-- updating an entire column
D update lineitem set l_newcolumn=l_discount+l_orderkey;
D checkpoint;
┌───────────────────────────┐
│         CHECKPOINT        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (1.18s)          │
└───────────────────────────┘   
-- writing the entire table again
D create table lineitem2 as select * from lineitem;
┌───────────────────────────┐
│         CHECKPOINT        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (36.21s)         │
└───────────────────────────┘ 
```

**Comment by Alex-Monahan** [comment]
I am seeing huge performance benefits from this! Thank you! 

It is only taking 2 minutes to do a complex join against a 200 million row table and a > 200 million row table, and insert about 20 million rows of results. I have to do that task 100 times (to trace the manufacturing genealogy of our products), and it is not taking longer and longer each time like it did before. I am fairly certain that I am storage-bottlenecked because I am running on a Cloudera Data Science Workbench cluster, so it could likely be even faster when running "bare metal" on an SSD equipped machine.

**Pull request merged**
