### PR TITLE
CI: Use ccache and clang-tidy-cache

### PR DESCRIPTION
**Pull request by jonashaag**
Use Ccache in CI to speed up builds. Use clang-tidy-cache to speed up clang-tidy. Saves ~ 10–50% of CI time for each workflow, and almost 100% for the clang-tidy workflow.

### CODE REVIEW

**Comment by jonashaag** [comment]
TODO for another PR: Windows and Emscripten support

**Comment by krlmlr** [comment]
Thanks. Is there an easy way to obliterate the build cache? Previously, ccache has been removed due to spurious build failures. It seems important to be able to start afresh when needed.

Does this close #2153?

**Comment by jonashaag** [comment]
Yes, we can add a counter to the cache keys that we can simply increment to invalidate the cache.

**Comment by jonashaag** [comment]
I think it fixes #2153

**Review by samansmink — APPROVED** [review]
lgtm!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
