### PR TITLE
Hawkfish distributive

### PR DESCRIPTION
**Pull request by hawkfish**
Refactor the existing aggregate functions to be first-class schema-resident objects similar to function objects.

### CODE REVIEW

**Comment by Mytherin** [comment]
Looks good, thanks for the contribution! I will take a closer look on Monday. Could you take a look at the compilation issue on travis if you have time? Cheers.

**Comment by hawkfish** [comment]
Looks like I accidentally removed a `#include <math>` from `distributive.cpp`. I can fix that on Monday.

**Comment by hannesmuehleisen** [comment]
Thanks so much for this huge amount of refactoring you put in there. Overall this looks great. We do have some comments though:

1. The transformer gained a client context, this is not desirable, the parser should not be aware of the catalog. A better way for this would be to create a generic function regardless of whether or not it's an aggregate and then have the binder perform the catalog lookup. Related to this is issue
2. There should not be a hard distinction between the different function types (scalar and aggregate) by using different catalog sets; rather they should use the same. An additional enum can be use to distinguish. Are there valid cases where there is both an aggregate and a scalar function with the same name? Perhaps we're missing something here. 
3. We also noticed that there is a catalog lookup in the physical planner, the catalog lookups should all happen in the binder.
4. Should the average be rewritten to SUM(x)/COUNT(x) or not? At the moment we do this as it also allows re-using the either results from other expressions in the aggregate.

Could you please address these? Again, thanks a lot,

Mark & Hannes

**Comment by hawkfish** [comment]
Thanks for looking at my rather large pile of a first submission! I shared a number of these concerns, so here are my thoughts.

1. Cutting that hole into `Transformer` was the saddest moment of the effort. I had a similar thought - that this should just be a parsed function node and it should be checked at binding time - but I am not very familiar with the code base and thought someone else should look at it and make suggestions. The fact that `AVG` was special-cased in there also made me loath to mess with it without further consultation.
2. I have to disagree here:  Aggregate functions are fundamentally different from scalar functions in that they have _state_. This is why Postgres has a separate `CREATE AGGREGATE` [DDL statement](https://www.postgresql.org/docs/9.4/sql-createaggregate.html). I tried to make them similar, but it was hopeless.  I do agree that there should be some common functions (argument checking, etc.) but I believe the function classes need separate catalog entries.  Windowing function APIs (which are my ultimate goal) are going to be even worse, but even there there are clearly shared pieces of functionality.  Related to all this is the problem that there are (currently) _two_ physical aggregation operators which necessitated two initialize/update API pairs. I've been trying to think if we can unify them, but nothing yet.
3. The binder calls in the physical planner are because the physical planner is creating new bound aggregates and I don't know what to do about that. It wasn't clear to me that they were all being used yet because one `COUNT` binding was not referencing a column to count(!), so I don't see how it could be live?
4. `AVG` is the simplest example of an algebraic aggregate, and I was leaving them for the next pass. The new object was just added to make the catalog complete, and I left the existing hard-coded rewrite in place. Eventually, I'd really like to enable aggregates to request and reference other component aggregates to make this data-driven.

I'm about to fix the silly compilation error on travis, but I will likely have less time to work on this in the near term, so I was hoping to get this in so we have a "stake in the ground" on the aggregate function architecture. We could then add one or two follow on issues (especially point #1) to be addressed in the next couple of weeks as time permits?

**Comment by Mytherin** [comment]
> Cutting that hole into Transformer was the saddest moment of the effort. I had a similar thought - that this should just be a parsed function node and it should be checked at binding time - but I am not very familiar with the code base and thought someone else should look at it and make suggestions. The fact that AVG was special-cased in there also made me loath to mess with it without further consultation.

Fair enough, I can take a look at this later this week. I think the special casing of the AVG function can move to the binder as well. The current approach of doing this in the transformer is quite a hacky one and it should be moved away from there.

> I have to disagree here: Aggregate functions are fundamentally different from scalar functions in that they have state. This is why Postgres has a separate CREATE AGGREGATE DDL statement. I tried to make them similar, but it was hopeless. I do agree that there should be some common functions (argument checking, etc.) but I believe the function classes need separate catalog entries. Windowing function APIs (which are my ultimate goal) are going to be even worse, but even there there are clearly shared pieces of functionality. 

I think indeed they should be separate catalog *entries*, but the question is more whether or not they should be in the same catalog set, i.e. should we allow a user to create a SUM(...) scalar function, and what exactly would the binding functionality be in this case? e.g. what would this signify:

```sql
SELECT SUM(x) FROM tbl
```

And would this then be legal?
```sql
SELECT SUM(SUM(SUM(x))) FROM tbl;
```

If Postgres allows it perhaps we should allow it as well, but we should just consider that we handle these binding cases correctly.

>Related to all this is the problem that there are (currently) two physical aggregation operators which necessitated two initialize/update API pairs. I've been trying to think if we can unify them, but nothing yet.

Indeed it would be cleaner to unify them, and I think it could be done in a (relatively) clean manner. The main issue would be performance, but that is not yet a really large concern and can be optimized again later if required.

**Comment by hawkfish** [comment]
Ah, yes I agree the objects need to share a namespace, so maybe they should be combined into a single catalog.  I was working from the table function implementation, though, so maybe there is an issue there too?

**Comment by Mytherin** [comment]
I think it is fine for table producing functions to live in their own shared namespace; as table-producing functions only exist in the FROM clause it is easy to spot when a function is a table-producing function or a scalar/aggregate function. The same applies to window functions because of the OVER() clause (although I personally find it a bit ugly that e.g. ```SELECT SUM(SUM(i)) OVER () FROM table``` is valid SQL, it is at least possible to distinguish the window and aggregate functions).

**Comment by hawkfish** [comment]
That makes sense. 

So the question now is:  Do you want me to switch to a single function object now or on a second pass?

**Comment by Mytherin** [comment]
I don't think these issues block the PR. Unless you want to fix them yourself I can fix those issues as they are fairly straightforward and shouldn't take much time.

**Comment by hawkfish** [comment]
Awesome!  I may have a look at implementing `COVAR` next, just to get a multi-argument example in place.

**Comment by Mytherin** [comment]
Thanks again for the PR, I added the changes we suggested in #257. Feel free to take a look.

> Awesome! I may have a look at implementing COVAR next, just to get a multi-argument example in place.

Great, note that currently multi-argument aggregates are not supported in the binder yet. It should not be so difficult to add there though.

**Comment by hawkfish** [comment]
The function unification in #257 makes it possible to have multi-argument aggregates like `COVAR`, `STRING_AGG` and `PERCENTILE`, which is where I was wanting to go.

**Pull request merged**
