### PR TITLE
capi: duckdb_interrupt & duckdb_query_progress

### PR DESCRIPTION
**Pull request by Virgiel**
Introduces two C functions to interrupt queries and get queries progress

### CODE REVIEW

**Comment by carlopi** [comment]
Hi @Virgiel

We changed slightly the way CI works, instead of triggering CI on any change now changes automatically classify any PR as "draft" and you have to say "ready for review" (clicking via web UI) to get a go at the CI.

I will add soon some documentation.

**Comment by Virgiel** [comment]
I am not sure these functions need to be tested, as they are already tested elsewhere. I got the progress from the connection as it was only publicly accessible there, but it might make more sense to get it from the pending result.

**Comment by Mytherin** [comment]
We would prefer if they are tested yes - could you add tests to the C API tests?

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
