### PR TITLE
CI: NighlyTests to be run also on pull requests with specific label

### PR DESCRIPTION
**Pull request by carlopi**
I would propose that PR with label 'stress test'* have NightlyTests.yml executed together (and in the same cases) than when regular CI are triggered.

Proposal is that as long as something is NOT tagged 'stress test', behaviour is the same as today.
If a PR is tagged 'stress test', then whenever CI is triggered also NightlyTests.yml will be executed.

This would solve the problem that if one is committing wide changes, having a run on full test set might be beneficial, and currently we miss a mechanism to do that in a nice way (having stuff run on forks is brittle / not easy to track down).
Also if a PR aims to solve a problem with testing itself, it would be good to have a more visible proof that a given problem has been actually solved.

Responsibility to add (and also potentially remove) the 'stress test' label is on whoever opened a PR and/or reviewers that might feel more extensive checks are needed.

I am not sold on the name 'stress test', if anyone has a better one, very welcome! (@taniabogatsch?)

### CODE REVIEW

**Comment by carlopi** [comment]
Note that CI, funnily enough, will fail, but that's unrelated to this PR.

**Comment by Mytherin** [comment]
Thanks for the PR!

Good idea - but it looks like the CI is currently skipped because `NightlyTests` is modified (which triggers the workflow), but there is no `stress test` label (which skips the test).

**Comment by carlopi** [comment]
Could try adding a 'stress test' label? (label needs to be created first)
Just to check that side.

I have to think/check the proper syntax to express:
trigger either on label being present OR changes to the yml file.

**Comment by Tishj** [comment]
We could just document in the yml that the PR that modifies it should be labeled as stress test, no?

**Comment by carlopi** [comment]
#8403 should have the solution via indirect workflow.

> We could just document in the yml that the PR that modifies it should be labeled as stress test, no?
Yes, that works, but I guess some automatic solutions should lower the details that ones has to keep in memory.
Cost of that is extra infrastructure, but I could not come up with a better alternative.

**Pull request closed without merging**
