### PR TITLE
Run R CMD check on Linux and macOS

### PR DESCRIPTION
**Pull request by krlmlr**
Windows already taken care of in #757.

### CODE REVIEW

**Comment by krlmlr** [comment]
@pat-s: Similarly to `build-win`, should we `build-mac` and `build-linux` scripts which we then could refactor independently of `.travis.yml`?

**Comment by hannesmuehleisen** [comment]
This currently removes most of travis config. Could you put it back before the merge please?

**Comment by pat-s** [comment]
R builds are passing.

**Review by krlmlr — COMMENTED** [review]
Looks good. `build-*` need to be in `.Rbuildignore`.

**Comment by hannesmuehleisen** [comment]
Could you merge with master again? I fixed an issue there so the build should pass now

**Comment by hannesmuehleisen** [comment]
Great, thanks. Merging squashed due to the usual travis back and forth required.

**Pull request merged**
