### PR TITLE
Add Jaro Winkler

### PR DESCRIPTION
**Pull request by lnkuiper**
Implements #4217

I spent a bunch of time trying to write a custom iterator to get it to work, but I ended up changing some of the source code of the library so that we can call the function on raw char pointers without copying to a std::string.

### CODE REVIEW

**Comment by mamonu** [comment]
Hi! Thanks for doing this. It will be really useful for our project [splink](https://github.com/moj-analytical-services/splink).

BTW some canonical tests for the Jaro-Winkler algorithm can be found [here](https://commons.apache.org/proper/commons-text/apidocs/src-html/org/apache/commons/text/similarity/JaroWinklerSimilarity#line.54)  from the Apache Commons library jw implementation

**Comment by lnkuiper** [comment]
I think the CI is running into an issue where the Jaro Winkler implementation in the library we are using is not deterministic. Most of the time, it returns the same similarity, but some tests fail because of a different similarity for the same query.

**Comment by Mytherin** [comment]
Should the similarity measure be non-deterministic?

**Comment by lnkuiper** [comment]
I believe it should. Also, it should be a value between 0 and 1. The issue in the CI is that when the test fails it's due to the similarity being higher than 1. What's even stranger is that this happens for one of the tests that I copied from the library's tests

**Comment by Mytherin** [comment]
The Python failures look unrelated but the symbol leakage test is failing due to the changes in this PR. Could you have a look at that when you have time?

**Comment by lnkuiper** [comment]
I think I've fixed the issue by changing namespace `jaro_winkler` to `duckdb_jaro_winkler`.

On accident I ran the `exported_symbols_check.py` script locally on duckdb that was compiled with `BUILD_JSON=1` and `BUILD_ICU=1`, which reported a bunch of leaked symbols.

Should we at some point wrap the third party code in our extensions in a separate namespace?

**Comment by Mytherin** [comment]
Thanks! Could you also update the documentation with the new functions?

> Should we at some point wrap the third party code in our extensions in a separate namespace?

Yes, that's probably a good idea, although the core library is the most important.

**Pull request merged**
