### PR TITLE
[Python] Fix issue with `dtype` parameter in the `read_csv` method.

### LINKED ISSUE #8209: [Python] relation.types and relation.columns values incorrect after creating relation with read_csv()
### What happens?

When using `duckdb.read_csv` to load a CSV file that has a date column in a format that uses an explicit date parsing template for, the value of the `types` property of the resulting relation is showing that the date column has type `VARCHAR`, even though inspecting the relation shows the parsing to have worked and produced a `DATE`.

### To Reproduce

```python
with open("test.csv", "w") as f:
    f.write("date,greeting\n")
    f.write("July 11 2023,quack\n")

rel = duckdb.read_csv(
    "test.csv", dtype={"date": duckdb.typing.DATE}, date_format="%B %d %Y"
)
print(rel)
rel.types
```

Resulting output:
```
┌────────────┬──────────┐
│    date    │ greeting │
│    date    │ varchar  │
├────────────┼──────────┤
│ 2023-07-11 │ quack    │
└────────────┴──────────┘

[VARCHAR, VARCHAR]
```

### OS:

Ubuntu 23.04

### DuckDB Version:

0.8.2.dev1435

### DuckDB Client:

Python

### Full Name:

Ned Letcher

### Affiliation:

Thoughtworks

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #8209, #8421, #8434

Relations are bound twice, one to get the names+types, and the second time to execute.
the `dtype` parameter was only handled after the first bind, so its effects were not visible in the `columns` and `types` attributes of the produced relation.

Also now we only `auto_detect` during the first phase, capturing the options detected by the sniffer and forwarding them to the second bind as named parameters.

i.e if a quote was detected, we forward this option as `read_csv(quote=<detected_quote>)`

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR!

I had a quick look at the problem and I think it goes a bit deeper than what this fix addresses. I think the problem should actually be solved in `ReadCSVRelation`. The issue is here in the constructor:

```cpp

ReadCSVRelation::ReadCSVRelation(const std::shared_ptr<ClientContext> &context, const string &csv_file,
                                 BufferedCSVReaderOptions options, string alias_p)
    : TableFunctionRelation(context, "read_csv_auto", {Value(csv_file)}, nullptr, false), alias(std::move(alias_p)),
      auto_detect(true) {

	if (alias.empty()) {
		alias = StringUtil::Split(csv_file, ".")[0];
	}

	// Force auto_detect for this constructor
	options.auto_detect = true;
	BufferedCSVReader reader(*context, std::move(options));

	auto &types = reader.GetTypes();
	auto &names = reader.GetNames();
	for (idx_t i = 0; i < types.size(); i++) {
		columns.emplace_back(names[i], types[i]);
	}

	AddNamedParameter("auto_detect", Value::BOOLEAN(true));
}
```

The options that are set get passed in to the `BufferedCSVReader`, which then uses those options to run auto-detection and obtain the columns and types. This means only flags set in the `BufferedCSVReaderOptions` are considered for the initial binding. However, any parameters provided here are subsequently lost. 

Afterwards, the actual table function is constructed and `AddNamedParameter` is called to add new parameters as named parameters. These parameters are then considered for the actual execution of `read_csv`.

All of this is to say this is quite messy - we have two avenues of providing options (`BufferedCSVReaderOptions` and `AddNamedParameter`) and both affect the relation in different ways. In addition, auto-detection is run multiple times unnecessarily.

Ideally we would only have one way of providing options (`AddNamedParameter` - which could be used with the `BufferedCSVReaderOptions` using the `SetReadOption` function). The auto-detection would run once when creating the relation, and the found columns and types would be saved in the relation (by for example adding a `dtypes=[...]` parameter). This would prevent the auto-detection from running again in subsequent iterations.

**Comment by Tishj** [comment]
Yea I agree this is really messy, and error-prone.

It's not immediately clear how to fix this in the ReadCSVRelation, but I'll have a look soon using the helpful pointers you provided 👍

**Comment by Mytherin** [comment]
I think #8421 is related to this as well

**Review by Mytherin — APPROVED** [review]
Thanks for the changes! LGTM now

**Comment by Tishj** [comment]
@Mytherin I think this can also be merged

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
