### PR TITLE
clean.py deleting correct directory and asks confirmation

### PR DESCRIPTION
**Pull request by JimStam**
The clean.py, which cleans artifacts of Python builds, now deletes a higher level directory than it should. This pull request addresses this. Only the folder where the Python package exists is now deleted. The deletion first has to be confirmed by the user.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Could you have a look at the failure in the CI?

**Comment by pdet** [comment]
Do we actually want a user input/confirmation on this?
Since I'm constantly building the python pkg, I think that might be a bit annoying (cleanups are actually pretty frequent)

**Comment by JimStam** [comment]
> Do we actually want want the ~user~ developer to give input/confirmation on this? Since I'm constantly building the python pkg, I think that might be a bit annoying (cleanups are actually pretty frequent)

This was triggered when I encountered a bug in the script, which meant it deleted a top level directory and any directories with "duckdb" in the name, instead of just the python package. So I believe it's good for the developer to see which directory will be deleted, since the whole directory and its content will be deleted.

Perhaps we could have a version without the input? I don't think that should be the standard script that is run when you use `./clean.sh` though.

**Comment by Mytherin** [comment]
Perhaps we could have a `-f` or `--force` parameter that skips the input check?

**Comment by Mytherin** [comment]
Alternatively we could flip it and add a `--check` option that displays the check instead, @pdet whatever you prefer

**Comment by JimStam** [comment]
Just pushed a version with the `--force` / `-f` flag, also fixing CI. But can also easily flip it to `--check`

**Comment by Mytherin** [comment]
@JimStam could you perhaps have a look at if using `pip uninstall duckdb` works as well, and replace the script with that command?

**Comment by Tishj** [comment]
```
➜  duckdb git:(pandas_analyze) ✗ python3 -m pip uninstall duckdb         
Found existing installation: duckdb 0.4.1.dev841+g8d478dde9
Uninstalling duckdb-0.4.1.dev841+g8d478dde9:
  Would remove:
    /opt/homebrew/lib/python3.9/site-packages/duckdb-0.4.1.dev841+g8d478dde9-py3.9-macosx-12-arm64.egg
Proceed (Y/n)? y
  Successfully uninstalled duckdb-0.4.1.dev841+g8d478dde9
  ```
  seems like it does
  
I've verified that it's actually removed by opening up `python3` and trying to import duckdb - which fails after running this

**Comment by JimStam** [comment]
> @JimStam could you perhaps have a look at if using `pip uninstall duckdb` works as well, and replace the script with that command?

I've also verified that pip uninstall works in the script. I see that @Mause also made a [pull request](https://github.com/duckdb/duckdb/pull/4199/files) with a similar change. So this pull request could also be closed if that is merged.

**Comment by Mytherin** [comment]
Superseded by #4199, thanks for the effort though!

**Pull request closed without merging**
