### PR TITLE
yyjson bump version to 2020

### PR DESCRIPTION
**Pull request by carlopi**
2 PR landed at the same time:
- bumping yyjson in iceberg https://github.com/duckdb/duckdb_iceberg/pull/50
- moving yyjson in duckdb (https://github.com/duckdb/duckdb/pull/11998)

This PR bumps yyjson version in duckdb to the same commit as it was done in https://github.com/duckdb/duckdb_iceberg/pull/50

### CODE REVIEW

**Review by lnkuiper — APPROVED** [review]
Looks good! Thanks

**Comment by carlopi** [comment]
Not mergeable in the current form, there is a:
```
D SELECT json_structure('{"duck":"goose"}'->'duck');
INTERNAL Error: Unexpected yyjson tag in ValTypeToLogicalTypeId
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```
raised, haven't looked (yet) at what's going on.

**Comment by carlopi** [comment]
This might require another look from @lnkuiper, given due to bumping the version the implementation of json_merge_patch changed, and we are just forwarding to it so it changed also for us

Relevant commit (that changes the tests to have them pass) is here: https://github.com/duckdb/duckdb/pull/12072/commits/697771230e1b6e4409f9ed6b14429682647be0fd

**Review by Maxxen — APPROVED** [review]

**Review by lnkuiper — APPROVED** [review]
I've had another look, and I think you've properly adjusted for the yyjson changes. Thanks!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
