### PR TITLE
Use correct hms value

### PR DESCRIPTION
**Pull request by krlmlr**
difftime and hms are represented internally as number of seconds. If I read the code correctly, we should keep dividing by 1000 (and not overwrite with the millisecond value).

Reference: https://github.com/duckdb/duckdb/pull/2150/files#r781756316.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Can you add a test please?

**Comment by krlmlr** [comment]
How would I tickle this code from R?

**Comment by hannesmuehleisen** [comment]
Ah so this is used for filter pushdown when scanning Arrow tables, so having an Arrow table with a time column, and running a sql query with a filter on said time column should do the trick.

**Comment by krlmlr** [comment]
Current behavior with the CRAN version:

``` r
library(duckdb)
#> Loading required package: DBI
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp

arrow_table <- arrow::arrow_table(time = hms::hms(10^(0:6)))
tibble::as_tibble(arrow_table)
#> # A tibble: 7 × 1
#>   time     
#>   <time>   
#> 1  00:00:01
#> 2  00:00:10
#> 3  00:01:40
#> 4  00:16:40
#> 5  02:46:40
#> 6  27:46:40
#> 7 277:46:40

conn <- duckdb::dbConnect(duckdb::duckdb())

dbWriteTable(conn, "df", as.data.frame(arrow_table))
dbGetQuery(conn, "SELECT * FROM df WHERE time <= '00:00:10'")
#>      time
#> 1  1 secs
#> 2 10 secs

duckdb_register_arrow(conn, "arrow", arrow_table)
duckdb_list_arrow(conn)
#> [1] "arrow"

dbGetQuery(conn, "SELECT * FROM arrow WHERE time <= '00:00:10'")
#>         time
#> 1 1e+00 secs
#> 2 1e+01 secs
#> 3 1e+02 secs
#> 4 1e+03 secs
#> 5 1e+04 secs
#> 6 1e+05 secs
#> 7 1e+06 secs
```

<sup>Created on 2022-01-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
With this patch:

``` r
library(duckdb)
#> Loading required package: DBI
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp

arrow_table <- arrow::arrow_table(time = hms::hms(10^(0:6)))
tibble::as_tibble(arrow_table)
#> # A tibble: 7 × 1
#>   time     
#>   <time>   
#> 1  00:00:01
#> 2  00:00:10
#> 3  00:01:40
#> 4  00:16:40
#> 5  02:46:40
#> 6  27:46:40
#> 7 277:46:40

conn <- duckdb::dbConnect(duckdb::duckdb())

dbWriteTable(conn, "df", as.data.frame(arrow_table))
dbGetQuery(conn, "SELECT * FROM df WHERE time <= '00:00:10'")
#>      time
#> 1  1 secs
#> 2 10 secs

duckdb_register_arrow(conn, "arrow", arrow_table)
duckdb_list_arrow(conn)
#> [1] "arrow"

dbGetQuery(conn, "SELECT * FROM arrow WHERE time <= '00:00:10'")
#>      time
#> 1  1 secs
#> 2 10 secs
```

<sup>Created on 2022-01-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Still working on a formal test.

**Comment by krlmlr** [comment]
The failures look unrelated to this PR.

**Comment by Mytherin** [comment]
Indeed a broken test snuck into the master. This looks good to merge to me if the R tests pass.

**Review by hawkfish — APPROVED** [review]

**Comment by krlmlr** [comment]
Turns out we can tweak an existing test to use a native Arrow table instead of one exposed by duckdb.

**Comment by hannesmuehleisen** [comment]
Thanks!

**Pull request merged**
