### PR TITLE
Support defining column names in CTAS

### PR DESCRIPTION
**Pull request by douenergy**
Implementing support for explicit column name definition in `CREATE TABLE AS` (CTAS) statements 

```sql 
CREATE TABLE tbl(col1, col2) AS 
SELECT 1, 'hello';
```
| col1 | col2  |
|-----:|-------|
| 1    | hello |

Additionally, this implementation adheres to PostgreSQL behavior when column name definitions and query result counts do not match.
```sql
CREATE TABLE tbl(col1) AS 
SELECT 4 ,'mismatch';
```
| col1 | 'mismatch' |
|-----:|------------|
| 4    | mismatch   |

When the number of defined column names is less than the query result columns, we first use the specified column names, then adopt the query result column names for the remaining columns, starting from where the defined names left off.

```sql
CREATE TABLE tbl(col1, col2) 
AS SELECT 5;
```
**Binder Error: Target table has more colum names than query result.**

### CODE REVIEW

**Comment by douenergy** [comment]
There some commit from main branch. i will reopen another pull request

**Comment by Tishj** [comment]
No need, you can just wait until main gets merged into feature, which is regular

The other way around would have been a problem :)

**Comment by douenergy** [comment]
Thanks @Tishj. You're right about the merging approach.
 I've opened https://github.com/duckdb/duckdb/pull/14327. Which PR do you think we should focus on now?

**Comment by Tishj** [comment]
Either is fine, lets focus on the new one then :+1:

**Pull request closed without merging**
