### PR TITLE
Extension loading by statically linking DuckDB

### PR DESCRIPTION
**Pull request by samansmink**
This PR presents a second attempt to solve the extension loading issues that we initially tried to solve through hacking in the RTLD_GLOBAL for the different clients (see PRs  https://github.com/duckdb/duckdb/pull/3416 and https://github.com/duckdb/duckdb/pull/3381). Here a different approach is taken where DuckDB is statically linked during each extension build. This resolves the need for any RTLD_GLOBAL hacks and make extension loading just work® on linux even when duckdb itself is loaded with RTLD_LOCAL.

The main downside of this approach is an increased extension binary size as each extension contains a copy of duckdb. To help reduce this overhead, on linux we use the compiler flags `-ffunction-sections -fdata-sections` together with the linker flag `-gc-sections` to only include the code that the extension actually needs. On windows a similar flag `/Gy`. Even with these optimizations, size does increase quite significantly. As an indication, here's the before and after for linux x86: 

extension | size before | size after 
--- | --- | ---
excel.duckdb_extension | 332K | 12M
fts.duckdb_extension | 1.0M | 13M
httpfs.duckdb_extension | 4.3M | 5.8M
icu.duckdb_extension | 18M | 30M
json.duckdb_extension | 533K | 12M
tpcds.duckdb_extension | 2.3M | 14M
tpch.duckdb_extension | 1.1M | 13M
visualizer.duckdb_extension | 740K |  12M

To get this to work on Python, i've had to switch the python extension builds to the [manylinux2014](https://github.com/pypa/manylinux) image that are also used for building the linux python binaries. In doing so i broke the 32bit extension builds which i ended up removing for now as i could not get it to run.

With this PR i've also re-enabled the python extension loading test that was disabled for last release. Also, I think this PR should also fix the extension upload for the Centos7 (now called manylinux-extensions) as there was some issue there with git that prevented uploading to the correct s3 url.

### CODE REVIEW

**Comment by hannes** [comment]
Thanks for taking on this herculean task, Sam

**Comment by Mytherin** [comment]
Thanks for the PR! This looks excellent.

**Comment by pdet** [comment]
@samansmink Thanks for your work on the extensions, this is really great stuff! :-)

**Comment by krlmlr** [comment]
To be more precise, I'm seeing:

``` r
duck <- DBI::dbConnect(duckdb::duckdb())

DBI::dbExecute(duck, "LOAD 'json'")
#> Error: rapi_execute: Failed to run query
#> Error: IO Error: File "/Users/kirill/.duckdb/extensions/45bae641b/osx_arm64/json.duckdb_extension" not found
DBI::dbGetQuery(duck, r"(SELECT json_array_length('["duck","goose","swan",null]');)")
#> Error: rapi_prepare: Failed to prepare query SELECT json_array_length('["duck","goose","swan",null]');
#> Error: Catalog Error: Scalar Function with name json_array_length does not exist!
#> Did you mean "array_length"?
#> LINE 1: SELECT json_array_length('["duck","goose","swa...
#>                ^
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is with a version that *should* have this PR brought in, but I'm not entirely sure.

How do I need to build the R package so that the extensions are available?

**Comment by samansmink** [comment]
@krlmlr as soon as the CI finishes uploading, you should be able to just run `install <extension>` followed by `load <extension>`, I'll do some testing and give you a ping when it works!

**Comment by rsund** [comment]
This is a very nice feature I have been waiting for.

I tested this on Windows 10 with the DuckDB version built with R toolchain in [R Universe](https://rsund.r-universe.dev/ui#package:duckdb).

That version already includes all extensions that can be easily compiled together with the actual DuckDB R-package (excel, fts, json, visualizer, (parquet)) using R toolchain and therefore also used even without running install/load, but for the rest of extensions installing and loading is required.

It seems that `install` works fine and extensions is downloaded, but unfortunately `load` crashes the R session. As the R package is a custom build, I would have expected to get an error stating that the versions are not matching or that extension cannot be loaded, but the crash was unexpected.

This may be related to different toolchains in building actual package and extensions, but in that case this could be a problem also with the later CRAN version of the package.

Here is a reprex to to reproduce the crash:

``` r
# Enable repository from rsund
options(repos = c(
  rsund = 'https://rsund.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))
# Download and install duckdb in R
install.packages('duckdb')
#> Installing package...

con <- DBI::dbConnect(duckdb::duckdb())

# json extension works out of the box
DBI::dbGetQuery(con, r"(SELECT json_array_length('["duck","goose","swan",null]');)")
#>   json_array_length('["duck","goose","swan",null]')
#> 1                                                 4

# Install and load httpfs-extension
DBI::dbExecute(con, "INSTALL 'httpfs'")
#> [1] 0
DBI::dbExecute(con, "LOAD 'httpfs'")
#> CRASH
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by krlmlr** [comment]
Thanks. I'm seeing, on a macOS M1:

```
> DBI::dbExecute(con, "INSTALL 'httpfs'")
[1] 0
> DBI::dbExecute(con, "LOAD 'httpfs'")
Error: rapi_execute: Failed to run query
Error: IO Error: File "/Users/kirill/.duckdb/extensions/2ca8707ca/osx_arm64/httpfs.duckdb_extension" could not be loaded: dlopen(/Users/kirill/.duckdb/extensions/2ca8707ca/osx_arm64/httpfs.duckdb_extension, 5): no suitable image found.  Did find:
	/Users/kirill/.duckdb/extensions/2ca8707ca/osx_arm64/httpfs.duckdb_extension: mach-o, but wrong architecture
	/Users/kirill/.duckdb/extensions/2ca8707ca/osx_arm64/httpfs.duckdb_extension: stat() failed with errno=57
```

**Pull request merged**
