### PR TITLE
Fix reusable workflow for OOTE building

### PR DESCRIPTION
**Pull request by samansmink**
This PR fixes an issue I ran into where you can't pass secrets to a reusable workflow that is outside the organisation for security reasons. The solution is to split the build and deploy steps. The deploy workflow will need to live in each extension repo, which is unfortunately some code duplication. However this step is quite simple so the problem is not too big.

To test/demo this, There is a demo PR up in my fork of the Azure extension here: [here](https://github.com/samansmink/duckdb_azure/pull/1), with CI using this passing [here](https://github.com/samansmink/duckdb_azure/actions/runs/6419011216?pr=1) . For the reviewer: the ci of this pr demonstrates the workflow in action, I've setup the correct keys in my fork there, so the extensions are actually installable from it. When checking duckdb out to the duckdb version that the azure demo pr targets, you are able to do: `install 'azure' from 'http://duckdb-extensions-nightly.s3.us-east-2.amazonaws.com';`

This PR also fixes an issue where the `exclude_archs` was not working. The problem is that the includes are handled after the excludes basically undoing them. Now we have a matrix generation script that can handle all the pain and a central matrix config file that holds the config for generating the matrix variables. This concept could in the future also be interesting for other places of DuckDB CI I think.

### CODE REVIEW

**Review by carlopi — APPROVED** [review]
My basic comment is whether this extra flexibility is actually needed and if it needs to be provided in this way, but I don't have any alternative viable proposal.

**Comment by samansmink** [comment]
Thanks @carlopi. Let me elaborate a bit here (for future reference, we discussed this in person)

The main idea here is that we want to provide a reusable workflow that is simple to use from extension repos. The features I would like here are:

- building extension for all archs supported by the targeted duckdb version
- allow excluding archs in case extension is incompatible with one
- automatically include new archs / changed archs when updating duckdb
- Abstract away the environment from extension development
   - extension dev should only need to look at this when a specific environment fails to build

The main complexity here are the generated matrices for Github actions. These are required because there is no nice way to represent this config in a clear way without them while also providing the ability to exclude architectures. I think this is worth the small amount of CI time paid to run the generate matrix jobs.

**Comment by samansmink** [comment]
@Mytherin I think this is good to go. This touches no CI and should not be used by anything but test branches and the extension template.

note that it should go in master, not feature. We can then use this for clean extension fixes for 0.9.1

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
