### PR TITLE
Create NamingConvention.md, with @samansmink

### PR DESCRIPTION
**Pull request by carlopi**
Putting in written form what has been sketched with @samansmink and others around what conventions DuckDB currently follows around extensions.

DuckDB C++ codebase, scripts and CI jobs implements these conventions, but we tough that making assumptions and constraints explicit would be of use.

This document is probably also a better place to discuss eventual changes to be made, and can be linked from extension-template or documentations as a reference.

There are probably also other valuable informations to be added, feel free to comment on the PR and propose changes.

### CODE REVIEW

**Review by samansmink — APPROVED** [review]
Looks good, nice to have more of these implicit conventions written down explicitly!

**Comment by Mytherin** [comment]
Thanks - good idea to document this, but I think the term `NamingConventions` is a bit of a misnomer. If I saw this as a user I would think it relates to the naming of extensions only. Instead this seems to talk primarily about the directory structure in which extensions are installed

**Comment by carlopi** [comment]
Checked with @Mytherin and @samansmink, renamed to `ExtensionDistribution.md`.
Better, thanks!

**Comment by Mytherin** [comment]
Thanks - made some more minor changes/fixes, looks great otherwise

**Pull request merged**
