### PR TITLE
More row unification

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR is more of a refactor than anything and contributes to the whole row unification started by @hawkfish.

`RowDataCollection` offers a way of storing fixed- and variable-size row data, but had many non-static methods that pertained to sorted and scattering variable-sized data. I've made these methods static and moved them to `RowOperations`. Now `RowDataCollection` is a single-purpose class, and is more widely usable e.g. for storing the fixed-size row blocks of `PhysicalHashJoin`.

This results in less code duplication, and more row unification!

### CODE REVIEW

**Comment by Mytherin** [comment]
Fantastic! Thanks. Out of curiosity I ran TPC-H with 4T using the old & new row layout.

|     name      | oldtiming | newtiming |
|---------------|-----------|-----------|
| q01.benchmark | 0.097     | 0.096     |
| q02.benchmark | 0.04      | 0.045     |
| q03.benchmark | 0.054     | 0.053     |
| q04.benchmark | 0.101     | 0.098     |
| q05.benchmark | 0.045     | 0.044     |
| q06.benchmark | 0.017     | 0.018     |
| q07.benchmark | 0.12      | 0.118     |
| q08.benchmark | 0.045     | 0.044     |
| q09.benchmark | 0.475     | 0.469     |
| q10.benchmark | 0.099     | 0.095     |
| q11.benchmark | 0.012     | 0.011     |
| q12.benchmark | 0.107     | 0.103     |
| q13.benchmark | 0.165     | 0.165     |
| q14.benchmark | 0.026     | 0.026     |
| q15.benchmark | 0.045     | 0.045     |
| q16.benchmark | 0.077     | 0.076     |
| q17.benchmark | 0.112     | 0.108     |
| q18.benchmark | 0.186     | 0.205     |
| q19.benchmark | 0.085     | 0.085     |
| q20.benchmark | 0.069     | 0.072     |
| q21.benchmark | 0.279     | 0.273     |
| q22.benchmark | 0.046     | 0.04      |

 Looking good!

(As a minor side-note, DuckDB is pretty good at combining CSV files!)

```sh
make
build/release/benchmark/benchmark_runner .*/sf1-parallel/.* 2> old.csv
git checkout -b lnkuiper-hashjoin-rowdatacollection master
git pull https://github.com/lnkuiper/duckdb.git hashjoin-rowdatacollection
make
build/release/benchmark/benchmark_runner .*/sf1-parallel/.* 2> new.csv
```

Then `build/release/duckdb` and:

```sql
.mode markdown
select string_split(name, '/')[-1] AS Name, round(avg(old.timing),3) OldTiming, round(avg(new.timing),3) NewTiming from 'old.csv' old join 'new.csv' new using (name) group by 1;
```

**Review by Mytherin — APPROVED** [review]

**Comment by lnkuiper** [comment]
Good idea comparing the performance before and after! (manual continuous benchmarking hehe) - I should do this more often.

I did not expect any major performance differences, as this was more of a refactor than anything, but good to know that I didn't break anything!

This was the first step in making the sorting code more modular. Right now it's all packed into `PhysicalOrder`, and it's impossible to use it outside of that operator. I think it will need some more refactoring because I want to use the sorting code in `PhysicalTopN`, and eventually `PhysicalWindow`.

**Comment by Mytherin** [comment]
> Good idea comparing the performance before and after! (manual continuous benchmarking hehe) - I should do this more often.

Yes, we need to get that properly working at some point, hah.

> I did not expect any major performance differences, as this was more of a refactor than anything, but good to know that I didn't break anything!

Always a good idea after some big refactors :)

> This was the first step in making the sorting code more modular. Right now it's all packed into PhysicalOrder, and it's impossible to use it outside of that operator. I think it will need some more refactoring because I want to use the sorting code in PhysicalTopN, and eventually PhysicalWindow.

Excellent!

**Comment by hawkfish** [comment]
image

**Comment by Mytherin** [comment]
The CI error is unrelated to this PR and has been fixed in another PR.

**Pull request merged**
