### PR TITLE
[Python]  Add some numeric and string functions to spark API

### PR DESCRIPTION
**Pull request by mariotaddeucci**
Add extra numeric and string operations available on pyspark api do duckdb python experimental package

### CODE REVIEW

**Review by usabuts — APPROVED** [review]

**Review by Tishj — APPROVED** [review]
Thanks for exposing these additional functions 👍

**Comment by Mytherin** [comment]
Thanks!

**Comment by cmdlineluser** [comment]
Thanks for adding this.

I was just trying out `isnull()` but I get:

```python
Catalog Error: Scalar Function with name isnull does not exist!
```

Can anybody replicate this?

(I had been looking for `is null` / `is not null` functionality in the [Expression API](https://duckdb.org/docs/api/python/expression.html) but can't locate any.)

**Comment by Mytherin** [comment]
Indeed it looks like the `IS NULL`/`IS NOT NULL` functionality is missing. The added functionality here doesn't work as they are not functions but operators - so they should be created similar to `DuckDBPyExpression::Not` in `tools/pythonpkg/src/pyexpression.cpp`. Could you perhaps open an issue for this?

**Pull request merged**
