### PR TITLE
[Python] Get rid of DuckDBPyResult (merged functionality into DuckDBPyRelation)

### PR DESCRIPTION
**Pull request by Tishj**
This PR addresses part of #5407 

Namely this addresses:
- > Merge the DuckDBPyResult module into the DuckDBPyRelation.

Essentially what this means is that you wont have to deal with confusing problems caused by switching from DuckDBPyRelation -> DuckDBPyResult, but nothing should change about the way you use duckdb, just the `__class__` of returned objects are different :)

### CODE REVIEW

**Comment by Mause** [comment]
Looks like something went wrong with the feature/master merge here?

**Comment by Tishj** [comment]
Yep, I'll check it out

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. One question/comment:

Perhaps @Mause also wants to have a look at this PR?

**Comment by Tishj** [comment]
This CI failure is fixed in #5650

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
