### PR TITLE
Fix parquet serialization

### PR DESCRIPTION
**Pull request by Maxxen**
This PR adds the missing fields in ParquetCopyBind to de/serialization.

Additionally I had to implement a new case in the Deserializer to handle deserialization of unique_ptr's whose element types do not implement `::Deserialize` themselves as a static member method, e.g. `unique_ptr<unordered_set<idx_t>>`.

Also had to format some java class or coequality would fail(?).

Closes https://github.com/duckdblabs/duckdb-internal/issues/572

### CODE REVIEW

**Comment by Maxxen** [comment]
I cannot reproduce this test succeeding locally, will try with an AWS box tomorrow.

**Comment by Maxxen** [comment]
Introduced a std::sort in the glob branch of the MultiFileReader and it seemed to fix the CSV reader problem on my fork, lets see if it works here too.

**Comment by carlopi** [comment]
For consistency, should the sort be added also here:
```
		for (auto &val : ListValue::GetChildren(input)) {
			if (val.IsNull()) {
				throw ParserException("%s reader cannot take NULL input as parameter", name);
			}
			if (val.type().id() != LogicalTypeId::VARCHAR) {
				throw ParserException("%s reader can only take a list of strings as a parameter", name);
			}
			auto glob_files = fs.GlobFiles(StringValue::Get(val), context, options);
+++++++                 std::sort(glob_files.begin(), glob_files.end());
			files.insert(files.end(), glob_files.begin(), glob_files.end());
		}
```
so that `read_csv('some/glob/**')` behave the same as `read_csv(['some/glob/**'])` ?

**Comment by Maxxen** [comment]
@carlopi Good catch, fixed now!

**Review by carlopi — APPROVED** [review]
I was curious and have given a proper look, LGTM!

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
