### PR TITLE
Add Mod function

### PR DESCRIPTION
**Pull request by sreeharshar84**
Issue:
------
Mod is available in Mysql.
https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_mod

Fix:
----
Mod function returns a BIGINT when both numbers are integer-types. It returns
DOUBLE in other cases. When 0 is the divisor, a NULL is returned.

### CODE REVIEW

**Comment by sreeharshar84** [comment]
Looking for some help here. 

The code in this patch is similar to the one for Round function. 

Would it help if I break "bool mod_matches_arguments(vector<SQLType> &arguments)" into multiple functions?

**Comment by Mytherin** [comment]
Hey, thanks for your contribution! We already have support for the modulo using the standard modulo operator (%). It is a good idea to support the MOD function, however, creating a new function for that should be avoided. Instead, the transformer should transform the MOD function into the modulo operator. This can be done in the `transform_function.cpp` file by checking if the function name is MOD and then generating an OperatorExpression with type OPERATOR_MODE . The rest of the code looks good, it is good to have mod support for the floating point types as well.

**Comment by sreeharshar84** [comment]
> Hey, thanks for your contribution! We already have support for the modulo using the standard modulo operator (%). It is a good idea to support the MOD function, however, creating a new function for that should be avoided. Instead, the transformer should transform the MOD function into the modulo operator. This can be done in the `transform_function.cpp` file by checking if the function name is MOD and then generating an OperatorExpression with type OPERATOR_MODE . The rest of the code looks good, it is good to have mod support for the floating point types as well.

Thank you for the comments @Mytherin . The MOD function's parameter types decide whether we use fmod or the % operator. So it won't be possible to do this transformation in transform_function.cpp. But the same can be done in "VectorOperations::Mod" based on the return type. Thus eliminating the need for a ModInt.

**Comment by sreeharshar84** [comment]
> I would say the modulo operator and the MOD function should behave identically, i.e. if we call fmod for floating point inputs in the MOD function then we should do the same in the modulo operator. The rewriting of the MOD function in the `transform_function.cpp` to the modulo operator should then be sufficient.

Are you sure this is the best way to go? Because fmod always returns a double/float type. There's really no good reason "SELECT 23 % 5 ;" should return a double value.  

I've checked the Mysql code also on this, they internally use "%" operator in the MOD function for integer values and for others they fmod. (See Mysql code: Item_func.cpp file "Item_func_mod::int_op()" and "Item_func_mod::real_op()".

**Comment by Mytherin** [comment]
Indeed `23 % 5` should return an integer value. What I mean is that the modulo operator should behalve identically to the `MOD` function, i.e. follow the same code path. That means that `SELECT 2.5 % 2` should return the same as `SELECT MOD(2.5, 2)`. The operator can also return a double value depending on its parameters. This can be configured in `bind_operator.cpp`.

**Comment by sreeharshar84** [comment]
> Indeed `23 % 5` should return an integer value. What I mean is that the modulo operator should behalve identically to the `MOD` function, i.e. follow the same code path. That means that `SELECT 2.5 % 2` should return the same as `SELECT MOD(2.5, 2)`. The operator can also return a double value depending on its parameters. This can be configured in `bind_operator.cpp`.

True. That would bring the behavior in line with what Mysql has. 

I misunderstood your earlier statement to mean that fmod should be used for all datatypes. This helps clear it up. I will submit a follow-up patch.

**Comment by sreeharshar84** [comment]
Looking for some help here. 

There seems to be a problem with the homebrew build on travis. But I can't figure out a way to fix this.

**Comment by Mytherin** [comment]
Looks like it was just a temporary issue with the build, restarting fixed it. Thanks for the effort! I will merge it as it is.

**Pull request merged**
