### PR TITLE
Internal #751: Shared Window Partition

### PR DESCRIPTION
**Pull request by hawkfish**
* Extend the partitioning and window internals to handle multiple partial sorts.
* Add CSE and and fix BoundWindowExpression::Equals in the process.
* Add partition fusion.

### CODE REVIEW

**Comment by hawkfish** [comment]
fixes: duckdblabs/duckdb-internal#751

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Could we add some tests with shared partitions/orderings? I'm not sure if this is tested enough by the base set of tests. I've tried this myself and found what I believe to be at least one incorrect result:

```sql
CALL dbgen(sf=0.01);
select l_extendedprice, l_partkey, l_orderkey, sum(l_extendedprice) over(order by l_partkey), sum(l_extendedprice) over (order by l_partkey, l_orderkey) from lineitem order by l_partkey, l_orderkey;

```

#### This PR
```
┌─────────────────┬───────────┬────────────┬───────────────┬────────────────┐
│ l_extendedprice │ l_partkey │ l_orderkey │   sum_part    │ sum_part_order │
│  decimal(15,2)  │   int32   │   int32    │ decimal(38,2) │ decimal(38,2)  │
├─────────────────┼───────────┼────────────┼───────────────┼────────────────┤
│        29733.00 │         1 │       2883 │      29733.00 │       29733.00 │
│         1802.00 │         1 │       5121 │      31535.00 │       31535.00 │
│         4505.00 │         1 │       6179 │      36040.00 │       36040.00 │
│            ·    │         · │         ·  │          ·    │           ·    │
│            ·    │         · │         ·  │          ·    │           ·    │
│            ·    │         · │         ·  │          ·    │           ·    │
│        20746.00 │      2000 │      58916 │ 2152182544.47 │  2152182544.47 │
│         7216.00 │      2000 │      59269 │ 2152189760.47 │  2152189760.47 │
├─────────────────┴───────────┴────────────┴───────────────┴────────────────┤
│ 60175 rows (5 shown)                                            5 columns │
└───────────────────────────────────────────────────────────────────────────┘

```

#### 0.9.2
```
┌─────────────────┬───────────┬────────────┬───────────────┬────────────────┐
│ l_extendedprice │ l_partkey │ l_orderkey │   sum_part    │ sum_part_order │
│  decimal(15,2)  │   int32   │   int32    │ decimal(38,2) │ decimal(38,2)  │
├─────────────────┼───────────┼────────────┼───────────────┼────────────────┤
│        29733.00 │         1 │       2883 │     607274.00 │       29733.00 │
│         1802.00 │         1 │       5121 │     607274.00 │       31535.00 │
│         4505.00 │         1 │       6179 │     607274.00 │       36040.00 │
│            ·    │         · │         ·  │         ·     │           ·    │
│            ·    │         · │         ·  │         ·     │           ·    │
│            ·    │         · │         ·  │         ·     │           ·    │
│        20746.00 │      2000 │      58916 │ 2152189760.47 │  2152182544.47 │
│         7216.00 │      2000 │      59269 │ 2152189760.47 │  2152189760.47 │
├─────────────────┴───────────┴────────────┴───────────────┴────────────────┤
│ 60175 rows (5 shown)                                            5 columns │
└───────────────────────────────────────────────────────────────────────────┘

```

**Comment by hawkfish** [comment]
Even worse, this still gives the right answer:

```sql
select 
	l_extendedprice, 
	l_partkey, 
	l_orderkey, 
	sum(l_extendedprice) over (order by l_partkey), 
from lineitem 
order by l_partkey, l_orderkey
```

**Comment by hawkfish** [comment]
Sorry about that! Dumb problem in an unexpected place. Restricting to `l_partkey = 1` gives a simple repro.

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
