### PR TITLE
Handle s3_endpoint that includes path

### PR DESCRIPTION
**Pull request by tom-s-powell**
Addresses https://github.com/duckdb/duckdb/issues/9917.

A custom `s3_endpoint` cannot currently be configured with a path:
1. `s3_endpoint` is currently used to determine the `Host` header but host header should simply be `<host>:<port>` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host). If the `Host` header includes a path it can cause requests to be rejected (interpreted as a malformed request).
2. The path used when constructing the canonical request for signature verification needs to be the entire request path. If you have a path in `s3_endpoint` this is omitted from `ParsedS3Url#path` which leads to incorrect signature.

This change:
1. Ensures a path in `s3_endpoint` is included as the prefix in `ParsedS3Url#path`, such that `ParsedS3Url#path` represents the full request path.
3. Strips the path from `ParsedS3Url#host` to ensure it conforms to `<host>:<port>` syntax.
4. Introduces `key` in `ParsedS3Url`. This makes code like `AWSListObjectV2` a bit cleaner since it can rely on the `key` rather than needing to make use of `ParsedS3Url#url_style` to substring `ParsedS3Url#path` appropriately (where it would otherwise also now need to handle the path in `s3_endpoint`).

If you had `s3_endpoint` of `http://localhost:8080/s3` and a query:
```
SELECT * FROM 's3://my-bucket/path/to/file.parquet'
```

For path-style URLs, you'd get `ParsedS3Url` with:
* `prefix`: `s3`
* `host`: `localhost:8080`
* `bucket`: `my-bucket`
* `key`: `path/to/file.parquet`
* `path`: `/s3/my-bucket/path/to/file.parquet`

For virtual-style URLs, you'd get `ParsedS3Url` with:
* `prefix`: `s3`
* `host`: `my-bucket.localhost:8080`
* `bucket`: `my-bucket`
* `key`: `path/to/file.parquet`
* `path`: `/s3/path/to/file.parquet`

### CODE REVIEW

**Review by samansmink — CHANGES_REQUESTED** [review]
Hey @tom-s-powell thanks for the PR! While being certainly a bit of an edge case, i could see this provide some utility so adding this is fine with me!

For the PR could you include some test cases that confirm your feature is working as expected? Our minio based test cases are run in the linux-httpfs job in `.github/workflows/LinuxRelease.yml`, following that job will help you set up the tests.
checkout the other s3 tests in `test/sql/copy/s3/` for inspiration!

**Comment by tom-s-powell** [comment]
@samansmink I've added tests. It's a bit artificial but you can demonstrate the new behaviour by using `s3_url_style=path` and `s3_endpoint='${DUCKDB_S3_ENDPOINT}/test-bucket'` (including the bucket as the path in the endpoint).

If you now run a query and omit the bucket (i.e. `s3://s3_query_params/test.parquet`), the full URL is still going to be `http://duckdb-minio.com:9000/test-bucket/s3_query_params/test.parquet` thus showing we're correctly handling the path in the endpoint.

**Comment by tom-s-powell** [comment]
One thing I can't easily add a test for is globbing since in the MinIO case, that should only by `/<bucket>?prefix=<path>`.

**Review by samansmink — APPROVED** [review]
LGTM!

**Comment by tom-s-powell** [comment]
@samansmink is this ready to merge? I don't have permissions.

**Comment by samansmink** [comment]
@Mytherin

**Comment by Mytherin** [comment]
Thanks

**Pull request merged**
