### PR TITLE
Issue #1426: EXTRACT INTERVAL/TIME

### PR DESCRIPTION
**Pull request by hawkfish**

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good. I'm wondering if there is maybe a better solution for the templating problem with dtime_t. I'm not so sure about the struct; I wonder if this could give problems on different architectures/compilers as we are interpreting a dtime_t array as a DTime array. Since it's an 8-byte type this would not be very problematic on most architectures, but perhaps struct padding could cause problems in some corner cases.

Would it not be possible to use a separate operator for the time type, to avoid having to use this struct, e.g. a DTimeYearOperator?

Or, perhaps what might be even cleaner, is to create a "holding" operator for each of the types, e.g.

```cpp
struct TimeDatePart {
    struct YearOperator {
	template <class TA, class TR>
	static inline TR Operation(TA input) {
		throw NotImplementedException("\"time\" units \"year\" not recognized");
	}
    }
    ....
};

struct DateDatePart {
    struct YearOperator {
	template <class TA, class TR>
	static inline TR Operation(TA input) {
		return Date::ExtractYear(input);
	}
    }
    ....
};
```

Then we can pass around this meta struct (`DateDatePart` or `TimeDatePart`) and access sub-structs using e.g. `OP::YearOperator`. That way we avoid having to template on type for the overloads, and all the operators for a single type are close together.

**Comment by hawkfish** [comment]
Should I do this now or should we wait until lit is an issue?

**Comment by Mytherin** [comment]
It's not required for this PR, I think the current solution works fine. I wouldn't mind merging and having a look at refactoring this myself later on. Up to you.

**Comment by hawkfish** [comment]
Why don't you merge it and I'll look at refactoring it now while I'm fresh.  It will end up moving some stuff around (all the template specialisations will no longer be by the class). I'll submit another PR if I get it done.

**Comment by Mytherin** [comment]
Sounds good to me, thanks again for the PR!

**Comment by hawkfish** [comment]
I'm a wimp - it wasn't so bad. Coming soon!

**Pull request merged**
