### PR TITLE
fix: don't install anything from third_party

### PR DESCRIPTION
**Pull request by chybz**
Hey @Mytherin, here's the PR for issue #1503 I created a bit earlier. I tested it locally and it's fine. Let's hope it won't break anything ;)

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Maybe @ankoh and @xhochy could comment on this PR?

**Comment by ankoh** [comment]
An alternative would probably be to just prefix all third_party libraries with `duckdb_`.
This could be done with the cmake target property `OUTPUT_NAME`.
Or `EXPORT_NAME` if you don't want the rename the library names in the local build directories.

E.g. with this:
[0001-Prefix-OUTPUT_NAMES-of-third_party-libraries.txt](https://github.com/cwida/duckdb/files/6162127/0001-Prefix-OUTPUT_NAMES-of-third_party-libraries.txt)

You'd get:
```
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb.so
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_static.a
-- Installing: /tmp/duckdb/installdebug/bin/duckdb
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_fmt.a
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_pg_query.a
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_re2.a
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_miniz.a
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_utf8proc.a
-- Installing: /tmp/duckdb/installdebug/lib/libduckdb_hyperloglog.a
```

**Comment by hannesmuehleisen** [comment]
Not using this installation path myself I am curious about the reason to install the .a files in the first place? @ankoh any insight on that?

**Comment by ankoh** [comment]
You still have to link `libduckdb_static.a` against `libduckdb_fmt.a` without the amalgamation build, don't you?

E.g. the explicitly instantiated `snprintf` for floats of `libduckdb_fmt.a` is still undefined in libduckdb_static.a:
```
> nm libduckdb_static.a | grep snprintf
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U vsnprintf
                 U snprintf
                 U vsnprintf
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U _ZN10duckdb_fmt2v68internal14snprintf_floatIeEEiT_iNS1_11float_specsERNS1_6bufferIcEE
                 U vsnprintf
                 U vsnprintf
```

**Comment by Mytherin** [comment]
I have just tried this locally and @ankoh is completely right that in order to use the static library `libduckdb_static.a` we will need all of the other static libraries as well. I suggest changing this PR to rename the libraries to be prefixed with `duckdb_`, instead of not installing them at all. That should resolve issue #1503 while still leaving the static library in a usable state.

**Comment by chybz** [comment]
I initially thought the other static libraries were added to `libduckdb_static.a`, but this does not seems to be the case. So yes, installing them is mandatory for the static version. But this raises another question (I'm checking this at the moment) about symbol clashing, that is a renamed third-party library with original namespace/scoping conflicting with another version of that library already installed in the environment.

**Comment by xhochy** [comment]
In the Arrow projects we bundle all third-party libs into a single static library: https://github.com/apache/arrow/blob/5b14d53680f6931f9b2a71e3e38e03da6e341323/cpp/src/arrow/CMakeLists.txt#L525-L535 You should probably be able to reuse that code here. Grepping for `ARROW_BUNDLED_STATIC_LIBS` in the Arrow CMake sources should provide you with all the necessary information.

**Comment by hannesmuehleisen** [comment]
I agree with the prefixing solution as outlined by @Mytherin . Could you please update the PR accordingly?

**Comment by hannesmuehleisen** [comment]
No response, closing. Feel free to reopen on updates

**Pull request closed without merging**
