### PR TITLE
[Fix] Vector verification for dictionary expressions

### PR DESCRIPTION
**Pull request by taniabogatsch**
This PR fixes most failing tests in `Vector Verification Tests (dictionary_expression)`.

We can open separate issues for the remaining failures.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! LGTM after CI passes

**Comment by taniabogatsch** [comment]
I'll have a look at that `any_value` test. It was failing in the verification test (prior) as well.

**Comment by taniabogatsch** [comment]
I'm also running the nightly tests here: https://github.com/taniabogatsch/duckdb/actions/runs/9871689830

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
