### PR TITLE
Fixing some issues flagged by ossfuzz

### LINKED ISSUE #1757: `select struct''` triggers assertion
**What does happen?**
This was found by oss-fuzz, `select struct''` triggers an assertion.

Their reports:
https://oss-fuzz.com/testcase-detail/5239305812443136
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34234

**What should happen?**
Probably an error should be thrown.

### LINKED ISSUE #1759: `select''from currEnt_time` triggers assertion
Found by oss fuzz

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34277
https://oss-fuzz.com/testcase-detail/6131030948970496

`Error: near line 1: INTERNAL Error: Assertion triggered in file "/Users/hannes/source/duckdb/src/parser/transform/tableref/transform_table_function.cpp" on line 25: call_tree->type == duckdb_libpgquery::T_PGFuncCall`

### PR DESCRIPTION
**Pull request by hannes**

### CODE REVIEW

**Review by hawkfish — APPROVED** [review]
Can we add the ossfuzz tests easily?

**Review by hawkfish — APPROVED** [review]
I'm so sad you had to type `depth+1` all over the place. Can we include the ossfuzz test that caused this?

**Review by hawkfish — APPROVED** [review]

**Review by hawkfish — APPROVED** [review]

**Comment by hawkfish** [comment]
Love the way you made it possible to just drop in future test cases.

**Comment by hannesmuehleisen** [comment]
Yeah they come out of their system like that and I'd just add them into the folder as-is, also because some have rather strange encoding. The tests that prompted the depth check are in there, too.

**Pull request merged**
