### PR TITLE
Transitive filters followed by constant comparisons

### PR DESCRIPTION
**Pull request by tiagokepe**
Hey all,

This PR adds transitive filters followed by constant comparisons. For filters like` j >= i AND i>10`, the optimizer will generate another extra filter `j >= 10`.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks Tiago! Looks good. Could you perhaps add some tests that verify that the new conditions get added in `test/optimizer`? For an example you can look at `test/optimizer/table_filter_pushdown.test`. You can have a test such as e.g.:

```sql
PRAGMA explain_output='optimized';
EXPLAIN SELECT * FROM (VALUES (1, 2)) tbl(col0,col1) WHERE col0=col1 AND col0=3;
```

In this case I see that a transitive filter `col1=3` is generated and present in the explain output, even though it wasn't in the original query:

```sql
logical_opt	PROJECTION[col0, col1]
PROJECTION[col0, col1]
    FILTER[col0=3, col1=3, col0=col1]
        EXPRESSION_GET
            DUMMY_SCAN	
```
Now I can add a test that verifies this condition is present using a regex (note the `.*` at the beginning and end of the regex to match the rest of the explain).

```sql
query II
EXPLAIN SELECT * FROM (VALUES (1, 2)) tbl(col0,col1) WHERE col0=col1 AND col0=3;
----
logical_opt	<REGEX>:.*col1=3.*
```

Note that I explicitly use a `VALUES` statement rather than a base table here to avoid the table filter pushdown.

**Comment by tiagokepe** [comment]
@Mytherin I have thought before how to test whether the optimizer created the new filter. Certainly, I will write more tests using the explain, nice trick BTW.

**Comment by tiagokepe** [comment]
The last commits added more test cases and also treated the case of transitive filters from the left column.

Filters like `WHERE i>9 AND j>= i AND k>= j` will be optimized regardless of the transitivity order, .e.g., `j>=i and  k>=j`  are dependent transitive filters, such dependency is treated now.

P.S. I guess the Travis job shall be triggered manually.

**Comment by Mytherin** [comment]
Thanks! Looks good now.

**Pull request merged**
