### PR TITLE
Imdb benchmark validation and benchmark improvements

### PR DESCRIPTION
**Pull request by Tmonster**
This PR has 2 separate improvements, and basically re-opens https://github.com/duckdb/duckdb/pull/5493

1. Create a benchmark to run and verify IMDB. We weren't doing this before, the results were gathered using a script I set up here (https://github.com/Tmonster/verify_db_scripts). I plan on adding more to this repository when needed. In order to properly verify with postgres, I had to modify the IMDB queries to return all lines (and not a min), with an order so that the COLLATE and the languages wouldn't produce different results.

2. Allow benchmarks to create and connect to a cached duckdb instance so that cached data doesn't need to be exported to parquet and imported for every query for every benchmark run. Results on improvements can be found in the table below. Timing information excludes the cost to download benchmark data, as that is very network dependent. 

A benchmark template can call connect {db_path}. The benchmark runner will then attempt to connect to the db at {db_path}. If an error is thrown, this is most likely because of storage format instability. When this is the case, the db is removed, and a connection is made to a clean instance. If no exception is thrown, the database is checked for tables. If no tables exist, data will be loaded in from duckdb_benchmark_data/{{cache}}.

If tables do exist, the benchmark will run as normal. If the data is incorrect, the benchmarks will report incorrect results and fail. At this point it is up to the user to fix the data or answers, most likely by deleting the cached database.

| Benchmark  | Cached DB size | largest cached parquet file (uncompressed to CSV) | with "connect" | without "connect" |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| TPC-H (sf=1) | 262MB  | 719MB  | 9.507s  | 20.465s  |
| TPC-DS (sf=1)| 313MB  | 381MB  | 1:06 min  | 2:00 min  |
| h2oai-join  | 1.1G  | 440MB  | 19s  | 20.335s  |
| h2oai-group  | 584MB  | 466MB  | 17.139  | 18.806  |
| JOB  | 2GB | 915MB  | 3:11 min  | 7:05 min  |

TPC-H, TPC-DS, and IMDB all have significant improvements while h2oai improvements are minor.

### CODE REVIEW

**Comment by Tmonster** [comment]
Imdb regression test on master will fail because the data can't be all be loaded into memory. Once this merges the benchmark will pass again

**Review by Mytherin — APPROVED** [review]
Thanks for all the fixes! Looks great!

**Comment by Mytherin** [comment]
Hm - looking at the CI failure on the regression test it seems a file was perhaps not checked in?

```
FileNotFoundError: [Errno 2] No such file or directory: '.github/regression/imdb.csv'
```

**Comment by Tmonster** [comment]
Ahh yes, I was missing it. Just added it

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
