### PR TITLE
Rcpp17

### PR DESCRIPTION
**Pull request by carlopi**
Adapt to CRAN's "NOTE: Specified C++11: please update to current default of C++17"

Note that we are disabling a test, to be worked on independently from this.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

**Comment by krlmlr** [comment]
This might hurt R 3.6.0 and R 4.0.0.

**Comment by krlmlr** [comment]
To be more precise, not hurting old R versions, but old OSes and compilers that don't support C++17. So, unless we need it, it seems better to require C++11 and not mention it, as in my other PR.

**Comment by carlopi** [comment]
One thing that we need to do is move the default to CXX17, since we have to be compliant with CRAN's rules, probably SystemRequirements line we can do without, I will give it a try.

**Pull request merged**
