### PR TITLE
Serialize DuckDB source version and git hash in header of storage format

### PR DESCRIPTION
**Pull request by Mytherin**
This allows us to determine which version of DuckDB wrote the file

### CODE REVIEW

**Comment by koenvo** [comment]
When different duckdb versions support the same file format this could give false information?

Version X creates the file
Version Y does an update

Version in file is X?

**Comment by Mytherin** [comment]
It would currently indeed give the version with which the file is created. I wouldn't say that is false information. We could change that to the last-written version in the future (which is IIRC what SQLite stores).

**Comment by koenvo** [comment]
> It would currently indeed give the version with which the file is created. I wouldn't say that is false information. We could change that to the last-written version in the future (which is IIRC what SQLite stores).

In what cases would you use the created version? I can imagine you can do a quick check if data is written by a version containing a bug for example.

**Comment by Mytherin** [comment]
Yes, it is extra information that might assist in debugging/tracking down issues.

**Pull request merged**
