### PR TITLE
Issue #3444: Approximate quantile lists 

### PR DESCRIPTION
**Pull request by hawkfish**
* Add lists implementations for approximate and reservoir quantiles
* Add missing bindings for reservoir quantiles

### CODE REVIEW

**Comment by taniabogatsch** [comment]
So this implementation does `approx_quantile(decimal, list) -> list`, where `list` is a list of quantiles, right? So it does not actually compute on list elements, but just multiple different quantiles for the provided column?

**Comment by hawkfish** [comment]
> So this implementation does `approx_quantile(decimal, quantiles_list) -> result_list`, right? So it does not actually compute on list elements, but just multiple different quantiles for the provided column?

Exactly. It's a common extension because computing any one of the quantiles requires collecting a sample or all the values, so it is relatively cheap to compute them all at once.

**Review by taniabogatsch — APPROVED** [review]
I think this looks good. :) Only thing I noticed is that most of the code is basically the same for the approximate quantile and the reservoir quantile, so more templating would be possible. But I guess that they are just very similar and it isn't really worth the effort at the moment.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
