### PR TITLE
[pystubs] Fix type of `proto` parameter in `from_substrait` methods.

### PR DESCRIPTION
**Pull request by ingomueller-net**
The generated signature for the two `from_substrait` methods make the `proto` parameter a `str`. However, if called with a value of that type, the following error is thrown:

```
TypeError: from_substrait(): incompatible function arguments. The following argument types are supported:
    1. (self: duckdb.duckdb.DuckDBPyConnection, proto: bytes) -> duckdb.duckdb.DuckDBPyRelation
```

This PR thus changes the type to `bytes` and adds a `stubgen` comment to document why.

### CODE REVIEW

**Comment by Tishj** [comment]
please run `make format-main` to fix the CI issues

**Comment by ingomueller-net** [comment]
> please run `make format-main` to fix the CI issues

It's not `make format-main` that fails but `make generate-files`.

The problem was that the function signatures are defined in `connection_methods.json` and need to be changed there rather than with `stubgen override` comments as I had assumed from such comments in the rest of the file. The latest comment uses the right approach (at least CI passes now).

**Review by Tishj — APPROVED** [review]
Thanks 👍

**Comment by ingomueller-net** [comment]
Cool, thanks for the reviews! To be sure: I can't merge; someone else will have to.

**Comment by Mytherin** [comment]
Thanks

**Pull request merged**
