### PR TITLE
Add support for S3 session token (STS)

### PR DESCRIPTION
**Pull request by dforsber**
Add support for temporary AWS access credentials (e.g. EC2 instance roles) by adding support for access token parameter and using it if present.

- [x] formatting, linting, etc.
- [x] unit test

### CODE REVIEW

**Comment by dforsber** [comment]
Ready for review.

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! This looks good to me. @hannesmuehleisen perhaps you want to have a look?

**Comment by dforsber** [comment]
Not sure why this apprears:
`.github/workflows/main.yml / Python 3 Linux with HTTPFS support (pull_request)`

Maybe the amalgamation?

```
    duckdb/extension/httpfs/s3fs.cpp: In static member function ‘static void duckdb::S3FileSystem::Verify()’:
    duckdb/extension/httpfs/s3fs.cpp:180:34: error: qualified-id in declaration before ‘(’ token
      bool S3FileSystem::CanHandleFile(const string &fpath) {
                                      ^
    duckdb/extension/httpfs/s3fs.cpp:182:2: error: expected ‘}’ at end of input
      }
      ^
    duckdb/extension/httpfs/s3fs.cpp:137:29: note: to match this ‘{’
     void S3FileSystem::Verify() {
                                 ^
```

**Comment by Mytherin** [comment]
The file doesn't seem to compile at all. There is a missing curly bracket (`}`) at the end of the Verify function. This doesn't break most of the tests since the HTTPFS extension is only compiled in a few of them.

**Comment by dforsber** [comment]
> The file doesn't seem to compile at all. There is a missing curly bracket (`}`) at the end of the Verify function. This doesn't break most of the tests since the HTTPFS extension is only compiled in a few of them.

Hehe, the manual merge went south on GitHub. Will fix this.

**Comment by Mytherin** [comment]
Thanks!

**Comment by Dobatymo** [comment]
This feature should also be added to the S3 Parquet Import docs.

**Pull request merged**
