### PR TITLE
Fuzzer #2490: Generate NULL TIMESTAMPTZ

### LINKED ISSUE #2490: ABORT THROWN BY INTERNAL EXCEPTION: Calling GetValueInternal on a value that is NULL
Issue found by DuckFuzz on git commit hash [00924](https://github.com/duckdb/duckdb/commit/00924b709c247932fa07f2a99126bbb695648b7f) using seed 538784972.
### To Reproduce
```sql
create table all_types as select * exclude(small_enum, medium_enum, large_enum) from test_all_types() limit 0;
SELECT NULL FROM (SELECT 4767 FROM generate_series(CAST('290309-12-22 (BC) 00:00:00+00' AS TIMESTAMP WITH TIME ZONE), NULL, NULL) AS t6(c1, c2, c3, c4, c5)) AS t64

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Calling GetValueInternal on a value that is NULL
```

### PR DESCRIPTION
**Pull request by hawkfish**
Check for NULL bounds when generating a series of TIMESTAMPTZ values.

fixes: duckdb/duckdb-fuzzer#2490

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! LGTM - just looks like there are some CI failures. Could you have a look?

**Comment by hawkfish** [comment]
@Mytherin @carlopi I don't understand why the new test is failing - it looks like the CI is not loading ICU even though there is a `require icu` line at the top of the test and it succeeds on my local build?

**Comment by Mytherin** [comment]
Ah - I think this is failing in the autoload tests. Extension autoloading doesn't work yet for added function overloads. You could add a `require no_extension_autoloading` to the test to fix that.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
