### PR TITLE
Issue #1367: Parallel window hashing

### PR DESCRIPTION
**Pull request by hawkfish**
Compute the hashes in parallel.

I'd like to see if we can remove the local parallel task generation and rewrite `PhysicalWindow` as a pipelined operator. To do that we need to do a few things:

* Break `LogicalWindow` operators up into a sequence of `PhysicalWindow`s that share a common hashing and sorting between their functions
* Move the hash and over (partition+sort) key computations into `Sink`
* Move the window function computations into `GetChunkInternal`
* Order the physical windows using [Cao et al.](http://vldb.org/pvldb/vol5/p1244_yucao_vldb2012.pdf)'s algorithm?

### CODE REVIEW

**Comment by hawkfish** [comment]
I tried the pipeline rewrite, but it is crashing, and I suspect the pipeline architecture is not expecting stacked pipeline breakers? hawkfish-window-pipeline if anyone wants to have a look.

**Comment by Mytherin** [comment]
What do you mean with stacked pipeline breakers? Pipeline breakers following one another (e.g. `AGGREGATE -> ORDER`)? This should be supported.

**Comment by hawkfish** [comment]
I'm working on integrating `PhysicalWindow` into the parallelism system, and step 1 was decomposing `LogicalWindow` into multiple operators with common sorts.  This seemed straightforward, but I ran into a strange problem as I was leaving that looked like the `gstate` had been deleted already in the second operator. Since I'm 9 hours off, I thought I'd ask, but I'll dig into it in a bit.  But as far as you know, it should be possible to stack `PhysicalWindow` operators and have each one computed in parallel?

**Comment by hawkfish** [comment]
My bad - I was not clear on how operators trigger completion and when empty chunks get passed around.

**Comment by hannesmuehleisen** [comment]
Is this superseded now?

**Comment by hawkfish** [comment]
I expect so, but I was having strange problems making `PhysicalWindow` into a parallel source. The other PR is derived from this one, so it doesn't matter aa whole lot.

**Pull request closed without merging**
