### PR TITLE
More read_json(_auto) bugfixes

### LINKED ISSUE #6249: read_json_auto: duckdb.IOException: IO Error: Cannot open file "xxx": Too many open files
### What happens?

When reading about 1000 json files, I recieve the following error:

    read_json_auto: duckdb.IOException: IO Error: Cannot open file "xxx": Too many open files

The same works when reading 1000 csv files (see example below).

### To Reproduce

```python
import shutil
from pathlib import Path

import duckdb
import pandas as pd

if __name__ == "__main__":
    mode = "json"  # "json", "csv"

    data_dir = Path("data")
    if data_dir.exists():
        shutil.rmtree(data_dir)
    data_dir.mkdir(exist_ok=True)

    for i in range(1000):
        df = pd.DataFrame({"a": [1, 2, 3]})

        if mode == "json":
            df.to_json(data_dir / f"file_{i}.json", lines=True, orient="records")
        else:
            df.to_csv(data_dir / f"file_{i}.csv")

    data = duckdb.sql(f"SELECT COUNT(*) FROM read_{mode}_auto('{data_dir}/*.{mode}');")

    print(data.fetchone())
```
When setting `mode="csv"`, the code works as expected.

### OS:

macOS

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Timon Schmelzer

### Affiliation:

grandcentrix

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes #6249. Also fixes a bunch of bugs I encountered while doing more stress tests.

Most notably this fixes `TransformStringToLogicalType(const string &str, ClientContext &context)`, so that custom types such as the `JSON` type which is created in the extension, can be properly parsed into the correct type. This also required some tests to be changed.

I've also added a band-aid fix for for a [yyjson issue](https://github.com/ibireme/yyjson/issues/103).

### CODE REVIEW

**Comment by lnkuiper** [comment]
Failure is unrelated, this can be merged. I'm going to squash more bugs today so we can also wait until I push more fixes.

**Comment by Mytherin** [comment]
There seems to be a deadlock in read_json.test - are you sure that’s unrelated?

**Comment by lnkuiper** [comment]
> There seems to be a deadlock in read_json.test - are you sure that’s unrelated?

That was indeed a bug! I've fixed this bug and a few more, and I've implemented `format='array_of_objects'` as well, so people can now read this JSON format as a table too.

**Comment by lnkuiper** [comment]
I think this is good to go! The failures seem to be from a csv/httpfs issue

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
