### PR TITLE
Close JSON files when possible

### PR DESCRIPTION
**Pull request by lnkuiper**
Fixes a bug found by @Mytherin , accidentally introduced while fixing other JSON bugs

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good. Looks like this causes the stdin test to fail, however. Could you have a look?

**Comment by lnkuiper** [comment]
This indeed broke reading from stdin. Should be fixed now, and I've also added a test that reads JSON from stdin within a recursive CTE.

**Comment by lnkuiper** [comment]
This is ready to go!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
