### PR TITLE
Add LDBC SNB Interactive queries

### PR DESCRIPTION
**Pull request by szarnyasg**
This PR contains a few queries from the LDBC SNB Interactive workload. While this is primarily an OLTP workload, implementing its queries can still be beneficial for testing features in DuckDB, and a DuckDB implementation can be useful for validating the SQL reference implementation of the Interactive workload.

This PR contains all 'short' queries (1-7) and the following 'complex' queries: 2 3 5 6 7 8 9 10 11 12.

The reasons for omitting the rest of the queries are the following:

* 1: needs `array`
* ~4: uses `not exists` (probably possible to rewrite to an antijoin)~
* 13: uses `not exists`, needs recursive views, runs into an infinite loop
* 14: needs `array`

To elaborate on Q13, other than missing clauses, one of its subqueries runs into an infinite loop (presumably caused by the graph having cycles):

```sql
WITH RECURSIVE search_graph(link, depth) AS (
		SELECT 17592186044856, 0 -- the big number is the start person Id
		UNION ALL
		(SELECT distinct k_person2id, x.depth+1
		FROM knows, search_graph x
		WHERE x.link = k_person1id)
)
select * from search_graph
```

Interestingly, the same code terminates under Postgres (v12.4):
```console
      link      | depth 
----------------+-------
 17592186044856 |     0
(1 row)
```

Do you have any advice on how to stop infinite loops caused by recursive queries? (Checked PR #404 but it doesn't seem conclusive regarding this.)

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! I actually already ported some LDBC queries, but running on an empty database (see [here](https://github.com/cwida/duckdb/blob/master/test/ldbc/ldbc-empty.test)). For testing purposes, it would be nice if there were unittests with data as well. We could either add tests using a small subset of the data, or add something similar to the sqllogictests which gets downloaded separately using `make sqlite` (which is hosted in a separate repo, [here](https://github.com/cwida/sqllogictest)). That way we can get notified if something breaks in the CI.

For benchmarking purposes it might be nice to actually add the queries to the benchmark runner (see e.g. the [strftime benchmark](https://github.com/cwida/duckdb/blob/ef8385f0b9b26fb10a1f3ca314baa196f7a3f47a/benchmark/micro/cast/strftime.benchmark) file we have).

As for the non-working queries:

> 1: needs array
> 14: needs array

We do support arrays (we call them lists), but the syntax needs to be extended to match the syntax of PostgreSQL. I noticed this before when running the LDBC queries as well. The main offender seems to be that we don't support the syntax `ARRAY[]::bigint[]` for creating empty arrays, which is used in the benchmark. This is primarily a parser/transformer issue, and shouldn't require big changes in the engine. We do support `array_agg` and `string_to_array`, which seems to be the other functions that are used.

> 4: uses not exists (probably possible to rewrite to an antijoin)

NOT EXISTS is supported by DuckDB and should work. In fact, it should be rewritten to an anti-join internally. Could you share the exact error you get here?

> 13: uses not exists, needs recursive views, runs into an infinite loop

The infinite loop smells like a bug to me. As far as I know Postgres doesn't have any special infinite loop handling either (i.e. if it's actually an infinite loop, Postgres would not terminate either). This needs some more investigation.

Thanks again for the effort!

**Comment by Mytherin** [comment]
> My mistake, Q4 indeed works. I just pushed it.

Great!

> Now I'm working to adapt the SNB update (=insert) queries as they are defined over the schema used in LDBC which used a common message table that contained both post and comment nodes. I'll definitely need those for the completeness of the LDBC benchmark but I'm not sure whether they belong to this repository. WDYT?

I assume these are relatively large (>5MB), right? In that case I would prefer not to add them to the main repository to avoid unnecessary bloat from test data. For TPC-H/TPC-DS we have added the data generators directly to the project. This is one possibility. Another is to create a separate repo that can be cloned during testing of the queries like we do for the [SQLite Logic Tests](https://github.com/cwida/sqllogictest) (as they contain around 1.2GB of test data).

**Comment by szarnyasg** [comment]
> I assume these are relatively large (>5MB), right?
With all the data, sure. But the queries themselves with a few example parameters are just a couple of kB.

**Comment by szarnyasg** [comment]
@Mytherin I turned the infinite loop problem to a separate issue #1088. The queries in this PR work as intended, so I think this PR is good to go.

**Comment by Mytherin** [comment]
Thanks again for the PR and thanks for filing the issue. Will merge this one then!

**Pull request merged**
