### PR TITLE
Ingestion benchmark framework

### PR DESCRIPTION
**Pull request by Tmonster**
Adds a new benchmark directory to our regression scripts to test ingestion performance. Some questions I still have

- Should we also test ingestion TPCH/TPCDS from csv?
- Should we test ingesting larger scale factors during nightlies?

These things can also be added in a future PR.

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! I'm not so certain if there's much of a benefit to benchmarking all of the tables. Many of these tables are tiny (e.g. `nation` has 25 rows?). Furthermore having lots of benchmarks means the chance of false negatives is higher which generates noise in the CI.

Can we perhaps limit this to the largest tables, and try to go for more of a variety of benchmarks? e.g. reading from Parquet, reading from CSV, copying from a separate table, running in-memory, running with persistent storage, etc.

**Comment by Tmonster** [comment]
The now benchmarks the following matrix

Format: CSV, PARQUET, NATIVE
Instance type: In memory, persistent

Getting In-memory native storage to work is not super straightforward in the current benchmark framework. I saw two options,

1. Open an in memory connection and generate the data for each benchmark
Or
2. add a command to the interpreted benchmark script so that allows you to do the following 
            1.  require the presence of a db file, 
            2. If the db file doesn't exist, use the provided load script to create the data and export it (if necessary)
            3. destroy the old connection and create a new in memory connection
            Then with another command
            4. Use another load command to import the data from the required db into the new in memory connection

(2) seems confusing and potentially error prone. I implemented a cache {db_file} no_reconnect function to do steps 1-3. This works for benchmarking ingestion of csv and parquet files since you don't need to data natively.

**Comment by Tmonster** [comment]
This fails regression now because the current duckdb doesn't have the new cache {db_file} no_connect command

**Comment by Mytherin** [comment]
Thanks for the updates! Looks good - could we perhaps just remove the ingestion benchmarks that aren't run (i.e. leaving only lineitem, store_sales, inventory and orders)? I think adding the small tables - even if they are not run - adds a lot of noise to when you want to run these benchmarks and I can't really see a scenario in which we want to run them.

**Comment by Tmonster** [comment]
> Thanks for the updates! Looks good - could we perhaps just remove the ingestion benchmarks that aren't run (i.e. leaving only lineitem, store_sales, inventory and orders)? I think adding the small tables - even if they are not run - adds a lot of noise to when you want to run these benchmarks and I can't really see a scenario in which we want to run them.

sure 👍

**Pull request merged**
