### PR TITLE
support arrow in c-api

### LINKED ISSUE #1921: Define duckdb_prepared_statement as struct so we can add error_message into it
Currently we don't the reason if duckdb_prepare failed

### PR DESCRIPTION
**Pull request by wangfenjin**
1. Support arrow API
2. Add duckdb_prepare_error to get prepared error message, close #1921

### CODE REVIEW

**Comment by wangfenjin** [comment]
@hannesmuehleisen Please help review the code. Thanks

**Comment by Mytherin** [comment]
@pdet could you have a look at the arrow stuff here?

**Comment by pdet** [comment]
I think it looks fine. Nitpicking, there are some small typos in the comments.

Considering is just exposing the arrow API to transform duckdb chunks to Arrow Arrays, I think there is enough testing as well.

**Comment by wangfenjin** [comment]
Ha! I’m not a native English speaker, so if there are any wording issue pls point out I’ll fix that.😄

**Comment by wangfenjin** [comment]
@pdet BTW, from your github bio, "Currently working on integrating Apache Arrow and DuckDB", may I know what exactly you are going to do? Quite interesting to me as seems duckdb already support arrow

**Comment by wangfenjin** [comment]
I'm working on [duckdb rust wrapper](https://github.com/wangfenjin/duckdb-rs), after this PR merged, I'll add arrow support in the rust wrapper, so other user can use [arrow-rs](https://github.com/apache/arrow-rs) to process the data if they want.

**Comment by pdet** [comment]
Hey @wangfenjin 

We have a project in collaboration with the Arrow people to support their format in our execution engine.

This basically means we can use DuckDB's vectorized engine and optimizer to read (and run SQL on :D) arrow objects. And we can do that in parallel as well (:

If you check the files on tools/pythonpkg/tests/arrow you can get a more comprehensive view of this integration.

I tend to use issue #1742 to track missing arrow types and/or bugs, but I think the most important ones are already supported.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
