### PR TITLE
Temporarily skip arrow, azure and iceberg builds due to missing lzma repo

### PR DESCRIPTION
**Pull request by carlopi**
See https://github.com/microsoft/vcpkg/issues/37839 and connected issues

Tested on my fork, this seems to be the minimum subset that will not cause LZMA to be pulled in. I think for development is easier if this band-aid is in, so that there is less pressure given both CI will not fail on PRs and nightly will still produce somehow workable artifacts (although missing the 3 extensions).

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

**Comment by carlopi** [comment]
Failure in the "Check extensions entries" job makes sense, given there is a mismatch between `src/include/duckdb/main/extension_entries.hpp` and the available extensions.

Possibly the cleanest way forward is just disabling the check (and re-enabling it when reverting the PR).

**Comment by Mytherin** [comment]
Makes sense - could you push that change?

**Comment by carlopi** [comment]
Done.

**Comment by carlopi** [comment]
Actually it might just be better to fix this properly:
https://github.com/duckdb/duckdb_azure/pull/54 and a follow up PR on duckdb-side should fix this problem more properly.

**Comment by carlopi** [comment]
Properly solved by https://github.com/duckdb/duckdb/pull/11476

**Pull request closed without merging**
