### PR TITLE
[Python] Adjust `relation.df()` to output microsecond precision for `DATE` types.

### LINKED ISSUE #8837: DATE -> Pandas Dataframe returns error with DATE that are out of bounds for pandas/numpy datetime64[ns]
### What happens?

Conversion to pandas dataframe returns an error for DATEs that are out of bounds for datetime64[ns] https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-oob

That makes working with databases/files  store DATEs such as "9999-12-31" problematic. Such dates are surprisingly common in financial data to indicate products with no expiring date.

Possible options might include:

Option 1: Returning a warning instead (https://github.com/duckdb/duckdb/issues/4026#issuecomment-1413851125 problem persists, but users are warned)
Option 2: https://github.com/duckdb/duckdb/issues/4026 Using microsecond precision

### To Reproduce

```python
>>> import duckdb
>>> duckdb.sql("select '9999-01-01'::DATE").df()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.ConversionException: Conversion Error: Could not convert DATE (9999-01-01) to nanoseconds
```

### OS:

W10

### DuckDB Version:

0.8.2-dev4025

### DuckDB Client:

Python

### Full Name:

Alessandro Martinello

### Affiliation:

Danmarks Nationalbank

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #8837, #6298

Since pandas 2.0.0 it now accepts datetime precisions other than nanosecond.
Before this, when fed a non-nanosecond datetime numpy array, it would silently be converted to nanoseconds.

Now we emit microseconds, which maps directly to our internal representation.
On pandas versions < 2.0.0 this should still work, but will cause extra overhead as pandas will silently convert it to nanoseconds still.

In the tests pandas < 2.0.0 is skipped because the tests that are now successful would cause an overflow exception on those versions.

### CODE REVIEW

**Comment by Tishj** [comment]
Locally my timings for the failed regression test are fine, not sure why it's consistently 1.8 seconds slower in the CI

Theoretically it should just be faster, we're no longer convert from US -> NS and then when scanning back from NS -> US

**Comment by alippai** [comment]
How about using actual date dtype eg `date32[day][pyarrow]`? Not sure how good pandas support today is, but this https://pandas.pydata.org/pdeps/0010-required-pyarrow-dependency.html shows that's the way forward.

**Comment by Tishj** [comment]
> How about using actual date dtype eg `date32[day][pyarrow]`? Not sure how good pandas support today is, but this https://pandas.pydata.org/pdeps/0010-required-pyarrow-dependency.html shows that's the way forward.

Thanks for the suggestion, last time I checked though the pyarrow integration into pandas is still experimental (?).
Also for pandas < 2.0.0 this would not work at all, so with backwards compatibility in mind this would be better.

I do think it might be time to start thinking about adding an optional `dtype_backend` option to `fetchdf` to produce a PyArrow-backed DataFrame instead

**Comment by alippai** [comment]
Agree that <2.1.0 support might be horrible unfortunately, so considering using only the pyarrow type doesn’t work. On the other hand it shouldn’t be experimental anymore, but likely it’s not used extensively yet and might yield more bugs than datetime64[ns] (even pyarrow operators are missing)

**Comment by Tishj** [comment]
Sadly the regression seems to be consisted.

Gonna have to dive deeper into the blackbox that is Pandas

**Comment by Tishj** [comment]
@Mause I'm pinging you because I'm updating the python version we use in the regression test, was wondering if you had any comments about the version I picked.

The context for that change is that python3.7 only supports to up to pandas 1.3.5, and the change I made enables functionality for pandas >= 2.0.0 because microsecond precision timestamps are supported since then.

On 3.7 the regression is caused by pandas only supporting nanosecond precision, because we feed them microseconds they do a transform to nanoseconds

**Review by Mytherin — APPROVED** [review]
LGTM

**Pull request merged**
