### PR TITLE
Helper c-api functions for maps and unions (*)

### PR DESCRIPTION
**Pull request by prashanthellina**
While Maps are internally lists of structs (key, val) and Unions are Structs and hence can be accessed directly just using the existing exposed C-API functions, these helpers make it more obvious to an API user who may not know the internal representation of these types.

### CODE REVIEW

**Comment by prashanthellina** [comment]
@Tishj @samansmink I accidentally wiped out my changes to my previous PR (https://github.com/duckdb/duckdb/pull/14536) by syncing my fork to main (because I incorrectly thought it was already merged!) and that is why I issued this new PR. Sorry about the confusion.

**Review by Tishj — APPROVED** [review]

**Comment by prashanthellina** [comment]
@Tishj I don't mean to hurry you but is there any chance this can be merged soon? The reason I ask is that I've finished exposing filter pushdown and table filter functionality in my local repo and would love to get that PR out to you for review. (I wrote the code in the same local branch as this PR and it will be somewhat more convenient to make PR from the same).

If merging is bound to take time, just let me know and I will redo my local changes on a separate branch that is forked from duckdb:main. Thank you!

**Comment by Giorgi** [comment]
@prashanthellina It would be great if you could also add map and union functions for creating duckdb_values similar to `duckdb_create_struct_value` and `duckdb_create_list_value`

https://duckdb.org/docs/api/c/value

**Comment by prashanthellina** [comment]
> @prashanthellina It would be great if you could also add map and union functions for creating duckdb_values similar to `duckdb_create_struct_value` and `duckdb_create_list_value` from [Values Interface](https://duckdb.org/docs/api/c/value)

@Giorgi I can check that out for sure and send a separate PR. Can this one be merged in?

**Comment by Giorgi** [comment]
I'm an outsider contributor like you, I can't merge PRs.

**Comment by Mytherin** [comment]
Thanks! LGTM - could you just resolve the merge conflicts?

**Comment by prashanthellina** [comment]
Screwed the PR up while attempting to resolve conflicts and the PR got closed!. Opened a fresh one here - https://github.com/duckdb/duckdb/pull/14602

**Pull request closed without merging**
