### PR TITLE
Force aggregate state to be `is_trivially_move_constructible`

### PR DESCRIPTION
**Pull request by lnkuiper**
Follow-up of https://github.com/duckdb/duckdb/pull/14615

### CODE REVIEW

**Comment by Maxxen** [comment]
https://gcc.gnu.org/onlinedocs/gcc-4.8.3/libstdc++/manual/manual/status.html#status.iso.2011

Not available on GCC 4.8 :(

**Comment by carlopi** [comment]
As suggested by @Mytherin, it might need to be ifdef'd, possibly behind a DUCKDB_COMPATIBILITY_MODE that we can then enable CMake side depending on compiler

**Comment by Mytherin** [comment]
Thanks for the PR! With this change we should also be able to remove many `::LEGACY` aggregate destructor states (maybe even all of them?). Perhaps you can try and see which ones can go?

**Comment by lnkuiper** [comment]
> Not available on GCC 4.8 :(

I can see that the GCC 4.8 run has failed. Do we actually distribute any GCC 4.8 binaries? Maybe we can just `#ifdef` to skip the check on GCC 4.8? Alternatively, we can implement [`is_trivially_move_constructible`](https://github.com/gcc-mirror/gcc/blob/master/libstdc++-v3/include/std/type_traits#L1402) ourselves, doesn't seem too difficult, although it's rather annoying.

**Comment by Mytherin** [comment]
I would say this check is mostly for ourselves so that we don't accidentally define aggregate states that cannot be move constructed - we can just #ifdef it out for older compilers.

**Comment by lnkuiper** [comment]
I've added the `#ifdef` for GCC 4.8, but the assertion tripped over the same aggregate states as before, so I couldn't remove any `LEGACY`. Oh well, at least the assertion is now _slightly_ more flexible and correct.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
