### PR TITLE
Merge arrow_register into register function

### PR DESCRIPTION
**Pull request by pdet**
There is no need to have a specialized function for this.

### CODE REVIEW

**Comment by pdet** [comment]
Hey @akdor1154 thanks for your work on the stubs! 
I'm breaking the tests and in need of a word of wisdom. 
I've tried re-generating them with the regenerate_python_stubs.sh, but it is still breaking? Maybe I missed something?

e.g.,
``` bash
(cd tools/pythonpkg; pip install -e .)
scripts/regenerate_python_stubs.sh
```

**Comment by akdor1154** [comment]
Yeah.. the autogeneration is pretty good, but not perfect, so the current overrides in the file need to be re-added after re-generation.
My workflow for doing that looked like
 - finish work on cpp/py
 - commit
 - regenerate stubs: this updates stubs to work with your new cpp/py structure, but also nukes overrides.
 - use git add -p to choose the changes to the stubs you want to keep (here i guess the from_parquet override) and reject the changes you don't want (the overrides getting nuked)

**Comment by akdor1154** [comment]
that process results in https://github.com/akdor1154/duckdb/commits/arrow_register_stubs which passes stub tests (locally... i haven't run in ddb ci), only the last commit differs from your branch, if you drop your HEAD commit it should ff cleanly.

**Comment by Mytherin** [comment]
Thanks! Everything looks good now.

**Pull request merged**
