### PR TITLE
fix for ODBC driver issues #4887 and #3801 

### PR DESCRIPTION
**Pull request by bucweat**
Fix for `ODBC driver lacks support for LogicalTypeId::DECIMAL #4887`. With this fix the example code from https://duckdb.org/docs/sql/introduction (the cities table has lat and lon of type DECIMAL) now works with ODBC driver at least for my test case (see below). 

Also "fixes" `Complex data types used by extensions not supported in ODBC #3801` based on @Mytherin comment: "If there is no support in ODBC for these types then returning and converting to VARCHAR sounds good to me.". With this fix the JSON examples https://duckdb.org/docs/extensions/json#json-scalar-functions now work.

Note my test case for both fixes is using ADODB in a vbscript, but I would expect anyone using ODBC driver to have these issues. I unfortunately do not understand the testing implementation used in the ODBC code to implement a proper test case there.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good to me.

There are some simple tests in `tools/odbc/test/test_odbc.cpp`, which you can run using the `unittest` program, e.g. `build/debug/test/unittest "Basic ODBC usage"`. It would be great if you could add tests. Otherwise this code is simple enough that I'm happy to merge it as-is as well.

**Comment by bucweat** [comment]
It’s only my second pull request and first for DuckDB. I’m not in a hurry and doesn’t seem like others have seen this issue so I’m happy to spend some more time trying to figure out the tests. Feel free to merge now and I can submit another pull request with tests if I figure it out. 

WRT tests, it seems they are all for Linux and none for Windows? Still figuring it out. When I was working with tiagokepe he mentioned integrating my VBScript example into the testing but AFAICT it’s not here.

**Comment by Mytherin** [comment]
Most tests are run on both Windows and Linux, see the [Windows CI](https://github.com/duckdb/duckdb/blob/master/.github/workflows/Windows.yml#LL184C2-L184C6).

**Comment by bucweat** [comment]
Note that I'm building on Windows 11 with VS2019. I built using a batch file very similar to CI build:
```
cmake -S ..\.. -B . -GNinja ^
    -DCMAKE_BUILD_TYPE=Release  ^
    -DBUILD_ICU_EXTENSION=1  ^
    -DBUILD_PARQUET_EXTENSION=1  ^
    -DBUILD_TPCH_EXTENSION=1  ^
    -DBUILD_TPCDS_EXTENSION=1  ^
    -DBUILD_FTS_EXTENSION=1  ^
    -DBUILD_JSON_EXTENSION=1  ^
    -DBUILD_EXCEL_EXTENSION=1  ^
    -DBUILD_ODBC_DRIVER=1  ^
    -DDISABLE_UNITY=0 ^
    -DBUILD_PYTHON=0
cmake --build . --config Release
```

> `build/debug/test/unittest "Basic ODBC usage"`.

Tried that with release build and it does nothing. I checked the "Basic ODBC usage" in test_odbc.cpp and it matches. 
```
M:\github\duckdb-bucweat\build\release\test>unittest.exe "Basic ODBC usage"
Filters: Basic ODBC usage
No test cases matched 'Basic ODBC usage'
===============================================================================
No tests ran
```

`unit_test.exe` run from release by itself runs successfully.
```
M:\github\duckdb-bucweat\build\release\test>unittest.exe
[2041/2328] (87%): test/sql/copy/csv/overwrite/test_overwrite_pipe_windows.test 42
[2328/2328] (100%): test/sql/table_function/icu_range_timestamptz.test
===============================================================================
All tests passed (229948 assertions in 2328 test cases)
```

I noticed debug in the path in your response so I  built the debug version. It built successfully, but the installer fails to install the ODBC .dll file. I tried to do that manually and it fails with `The module "M:\github\duckdb-bucweat\build\debug\tools\odbc\bin\duckdb_odbc.dll" was loaded but the entry-point DllRegisterServer was not found. Make sure that "M:\github\duckdb-bucweat\build\debug\tools\odbc\bin\duckdb_odbc.dll" is a valid DLL or OCX file and then try again.`. 

I tried `unittest.exe "Basic ODBC usage"` but no test ran. I tried `unit_test.exe`...this ran... take a lot longer than release and it runs successfully
```
```

Looking at the CI it seems like it builds the release version and runs unit_test.exe from Release folder so not sure if debug version is required for ODBC unit tests.

**Comment by bucweat** [comment]
I think I may have messed up and merged [Fixes issue with .Net 4.8 System.Data.Odbc GetSchema()](https://github.com/duckdb/duckdb/pull/6875/commits/976ceec3afb4403bc8087d61184a731dfce145bf) into this push request. Not sure if that is fixable so may have to redo push request.

**Comment by bucweat** [comment]
OK I reverted so that this pull request only references the subject fix.

**Comment by bucweat** [comment]
> Indeed, it looks like the ODBC tests are not yet currently build for Windows. I'm fine with merging this PR, but for more complex PRs it would be great to get that working and add tests as well.

Yeah the standard tests are not but the psqlodbc tests are (which I figured out in #6321). Thanks for the merge and I'll see if I can't figure out something for the tests.

**Pull request merged**
