### PR TITLE
Julia: Support change timezone config

### PR DESCRIPTION
**Pull request by xcaptain**
1. ensure timezone can be set
2. added some examples on querying timestamp and timestamptz

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR. The PR title is not descriptive of what is changed here. Also, could you please ensure the [CI passes on your fork](https://github.com/xcaptain/duckdb/actions) prior to opening a PR?

**Comment by xcaptain** [comment]
Sorry, didn't realized these CIs runs so long, I made some changes, now format check passed, and unit test passed in nightly.
julia 1.6 and 1.7 failed, I think they have nothing to do with my change.

**Comment by xcaptain** [comment]
Since https://github.com/JuliaPackaging/Yggdrasil/pull/6282 was merged, we also need to update `DuckDB_Jll`'s version at https://github.com/duckdb/duckdb/blob/master/tools/juliapkg/Project.toml#L10 for use where `JULIA_DUCKDB_LIBRARY` is not set.

**Comment by Mytherin** [comment]
Thanks

**Pull request merged**
