### PR TITLE
Support RLE, DELTA_BYTE_ARRAY and DELTA_LENGTH_BYTE_ARRAY Parquet encodings

### LINKED ISSUE #3981: Unsupported page encoding when reading Parquet
Hi Team, We are unable to read some of the parquet files like aws2.parquet and complex.parquet from this repository

#### What happens?
When we trigger a select query such as select * from aws2.parquet limit 5, we are able to see **Unsupported page encoding when reading Parquet**

#### To Reproduce
1) Download the aws2.parquet file from https://github.com/duckdb/duckdb/blob/master/data/parquet-testing/aws2.parquet
2) Go to https://shell.duckdb.org/
3) Execute the **.files add** command to select the downloaded aws2.parquet file
4) Execute the **.files list** command to see the list of files uploaded (at present we only uploaded aws2.parquet)
5) Execute a select command **SELECT * FROM 'aws2.parquet' limit 2;**
6) Now we are able to see the exception Unsupported page encoding when reading Parquet
image

#### Environment (please complete the following information):
 - OS: Mac OS 12.4 (21F79) - Mac M1 (in my local setup for JDBC) and tried in Chrome DuckDB shell
 - DuckDB Version: We are using https://shell.duckdb.org/ and in my local setup I'm was 0.4.0
 - DuckDB Client: Shell wasm and JDBC (In my local)

#### Identity Disclosure:
 - Full Name: Adithya Jalda

Team, We are getting this exception when we perform the same steps in the JDBC client as well, But when we tried parsing with Java code using Apache parquet Reader it's working fine
We tried aws2.parquet, complex.parquet from this location https://github.com/duckdb/duckdb/blob/master/data/parquet-testing/

### PR DESCRIPTION
**Pull request by Mytherin**
Fixes #3981

This should implement all remaining Parquet encoding types - aside from `Byte Stream Split` which does not appear to be used by anyone anywhere.

### CODE REVIEW

**Comment by dselivanov** [comment]
@Mytherin what is the way to try it in python? Should I follow build steps from "python" [github actions](https://github.com/duckdb/duckdb/blob/master/.github/workflows/Python.yml) or there is a simpler way?

**Comment by Mause** [comment]
> @Mytherin what is the way to try it in python? Should I follow build steps from "python" [github actions](https://github.com/duckdb/duckdb/blob/master/.github/workflows/Python.yml) or there is a simpler way?

You can install the Python prerelease using the pip `--pre` flag

**Comment by dselivanov** [comment]
Thanks @Mause. I believe `--pre` installs from master branch (and current feature is still in `feature` branch)? I've tried `pip install duckdb --pre --upgrade` and see `Unsupported page encoding` while reading parquet.

**Comment by dselivanov** [comment]
I was able to build package on linux machine just by running `python3 -m build` from within `./tools/pythonpkg`. Reading parquet files with `DELTA_LENGTH_BYTE_ARRAY` encoded columns works smooth now.
On my local OSX machine, however, package built from `feature` branch throws `segmentation fault` when running `import duckdb`. Mb something with my environment - not sure.

**Comment by Mytherin** [comment]
That sounds like something funky with your environment indeed, perhaps try uninstalling all versions of duckdb (repeat `pip uninstall duckdb` until no more versions remain) and doing a clean build?

**Pull request merged**
