### PR TITLE
Add exact MEDIAN and QUANTILE functions

### PR DESCRIPTION
**Pull request by hannes**
This PR adds the SQL aggregate functions `MEDIAN` and `QUANTILE`. Use them like so:
````SQL
SELECT MEDIAN(range) from range(10);
-- 4
SELECT QUANTILE(range, 0.1), QUANTILE(range, 0.5), QUANTILE(range, 0.9) from range(10);
--  0 4 8
````
Keen students of statistics will quickly realise that `MEDIAN(x)` is just short for `QUANTILE(x, 0.5)`. We should note that we do not perform re-scaling of median values *between* actual data points in the table. This seems much saner anyway. The implementations use partial sorting and produce *exact* results. In a next step, we will also add approximate quantiles.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
See also #1125

**Comment by hannesmuehleisen** [comment]
CC @willium

**Comment by willium** [comment]
@hannesmuehleisen what's the best way to test these as they are being developed? I tried after Make/configure, then the CLI, and finally the Node.js tool. Might just missing something trivial :)

**Comment by hannesmuehleisen** [comment]
@willium what's the issue? The function is not found?

**Comment by willium** [comment]
Yes, roughly:
```
D SELECT origin, MEDIAN(delay) from flights3m GROUP BY origin;
Error: Catalog Error: Scalar Function with name median does not exist!
Did you mean "radians"?
LINE 1: SELECT origin, MEDIAN(delay) from flights3m GROUP BY o...
                       ^
```

This is from running `make` and then running the duckdb binary from the build/release dir.

**Comment by willium** [comment]
Ah! never mind. I was running `duckdb` from within the directory without thinking. I also have duckdb in my PATH :). I ran `./duckdb` from that release, and all worked as expected.

I'm curious what your general release schedule is for things like this? I'd like to test it in our app, but it's not trivial to wire our app to CMAKE (much easier to `npm install duckdb`)

**Comment by hannesmuehleisen** [comment]
You can install the latest builds from the master branch via npm as well: If you look at https://www.npmjs.com/package/duckdb you will see the latest dev builds, as of now the last is

npm i duckdb@0.2.3-dev442.0

**Comment by willium** [comment]
ah, thank you! I hadn't noticed that.

I must say, after playing with this for 15 minutes, I am _incredibly_ impressed with the performance. Very excited to play with this more

**Pull request merged**
