### PR TITLE
[Fix] Track correct allocation size of evicted memory

### PR DESCRIPTION
**Pull request by taniabogatsch**
Fix https://github.com/duckdblabs/duckdb-internal/issues/3759

### CODE REVIEW

**Comment by taniabogatsch** [comment]
I think these Python errors are unrelated: https://github.com/duckdb/duckdb/actions/runs/12434007615/job/34716770272?pr=15433#step:8:14463

**Comment by Tishj** [comment]
Yea that should be rerun or ignored

**Comment by taniabogatsch** [comment]
I think it's unrelated, but rerunning didn't fix it. So, I'll leave it as-is.

**Comment by Tishj** [comment]
> I think it's unrelated, but rerunning didn't fix it. So, I'll leave it as-is.

<https://github.com/duckdblabs/duckdb-internal/issues/3815> fix is up as well, you can ignore it 👍

**Pull request merged**
