### PR TITLE
Making the deliminator more flexible and Q 02/17/20 of TPC-H for Substrait

### PR DESCRIPTION
**Pull request by pdet**
In this PR the rules to transform delim joins to regular comparison joins are made more flexible and the ```null_values_are_equal``` was removed, now ExpressionType::COMPARE_NOT_DISTINCT_FROM is used instead.

### CODE REVIEW

**Comment by hannes** [comment]
lgtm

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. Some comments:

**Comment by Mytherin** [comment]
The CI seems to not have started, could you push another commit?

**Comment by Mytherin** [comment]
Thanks for the updates! Playing around with it a bit I found this issue still persists:

```sql
CREATE TABLE integers(i INTEGER);
INSERT INTO integers VALUES (1), (2), (3), (NULL);

SELECT i, (SELECT SUM(i) IS NOT NULL FROM integers i2 WHERE i2.i>i1.i) FROM integers i1 ORDER BY i;
-- returns NULL when false should be returned
```

There is a test with `IS NOT NULL` but it does not trigger this bug.

The following also does not work with any expressions, likely because of the added subquery:

```sql
SELECT i, (SELECT sum IS NULL FROM (SELECT SUM(i) sum FROM integers i2 WHERE i2.i>i1.i)) t1 FROM integers i1 ORDER BY i;
SELECT i, (SELECT sum IS NOT NULL FROM (SELECT SUM(i) sum FROM integers i2 WHERE i2.i>i1.i)) t1 FROM integers i1 ORDER BY i;
SELECT i, (SELECT [sum] FROM (SELECT SUM(i) sum FROM integers i2 WHERE i2.i>i1.i)) t1 FROM integers i1 ORDER BY i;
...
```

Neither does the following:

```sql
SELECT i, (SELECT (SELECT SUM(i) IS NOT NULL) FROM integers i2 WHERE i2.i>i1.i) FROM integers i1 ORDER BY i;
SELECT i, (SELECT (SELECT [SUM(i)]) FROM integers i2 WHERE i2.i>i1.i) FROM integers i1 ORDER BY i;
...
```

I would also like to see these test cases added (that do currently work):

```sql
SELECT i, (SELECT SUM(i) AND false FROM integers i2 WHERE i2.i>i1.i) FROM integers i1 ORDER BY i;
SELECT i, (SELECT SUM(i) OR true FROM integers i2 WHERE i2.i>i1.i) FROM integers i1 ORDER BY i;
SELECT i, (SELECT COUNT(*) FROM (SELECT SUM(i) FROM integers i2 WHERE i2.i>i1.i)) t1 FROM integers i1 ORDER BY i;

```

**Comment by Mytherin** [comment]
Thanks for the fixes! Looks good now. Could you just resolve the merge conflict?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
