### PR TITLE
Update testthat snapshots

### PR DESCRIPTION
**Pull request by krlmlr**
~~Had to disable arrow tests to be able to create them. Need further investigation.~~

Arrow tests now work also locally, with arrow 8.0.0.

### CODE REVIEW

**Comment by krlmlr** [comment]
I do wonder why this error is coming back here:

```
File ‘duckdb/libs/duckdb.so’:
  Found ‘stderr’, possibly from ‘stderr’ (C)
    Object: ‘duckdb/third_party/libpg_query/src_backend_parser_scan.o’
```

https://github.com/duckdb/duckdb/runs/6847623982?check_suite_focus=true#step:12:3137

**Comment by Mytherin** [comment]
> I do wonder why this error is coming back here:
> 
> ```
> File ‘duckdb/libs/duckdb.so’:
>   Found ‘stderr’, possibly from ‘stderr’ (C)
>     Object: ‘duckdb/third_party/libpg_query/src_backend_parser_scan.o’
> ```
> 
> https://github.com/duckdb/duckdb/runs/6847623982?check_suite_focus=true#step:12:3137

The grammar (and to a lesser extend the flex files) frequently get re-generated, sometimes with different versions of yacc/bison. Likely it has gotten re-added by this.

**Comment by krlmlr** [comment]
R checks look good now.

**Comment by krlmlr** [comment]
This only makes the tests a bit stricter and *could* be good also in feature freeze, but no strong opinion.

**Review by hannes — APPROVED** [review]

**Comment by Mytherin** [comment]
Merging this now seems fine to me, @hannes?

**Pull request merged**
