### PR TITLE
Check coverage for R

### LINKED ISSUE #2929: [R]: Test coverage for R package
Possible with the covr package, we can upload results to codecov from GitHub Actions.

### PR DESCRIPTION
**Pull request by krlmlr**
with path fixing.

Closes #2929.

### CODE REVIEW

**Comment by krlmlr** [comment]
Good thing: install times are down to a few minutes, seen e.g. in https://github.com/duckdb/duckdb/runs/4863460020?check_suite_focus=true#step:5:1 .

**Comment by krlmlr** [comment]
Coverage now added correctly: https://codecov.io/gh/duckdb/duckdb/compare/c49927a998086420da4948be8479ea2b93e7a528...89fc158c897a4c9f19d54467a290be96d64e191c/changes.

Downside: this is using a patched version of the covr R package: https://github.com/r-lib/covr/pull/499. Would that be acceptable?

Before merging this, I'll bring back the other workflows and clean up.

**Comment by krlmlr** [comment]
The R part of the code is seeing 83% of coverage: https://codecov.io/gh/duckdb/duckdb/compare/c49927a998086420da4948be8479ea2b93e7a528...89fc158c897a4c9f19d54467a290be96d64e191c/tree.

**Comment by Mytherin** [comment]
> Coverage now added correctly: https://codecov.io/gh/duckdb/duckdb/compare/c49927a998086420da4948be8479ea2b93e7a528...89fc158c897a4c9f19d54467a290be96d64e191c/changes.
> 
> Downside: this is using a patched version of the covr R package: [r-lib/covr#499](https://github.com/r-lib/covr/pull/499). Would that be acceptable?
> 
> Before merging this, I'll bring back the other workflows and clean up.

Looks good to me. I'm fine with temporarily using a patched version of the covr R package. Ideally this would get merged upstream so we can use the main version afterwards, however.

One question: for coverage of the Python package, [we build the package with `BUILD_PYTHON=1` in the main coverage test](https://github.com/duckdb/duckdb/blob/master/.github/workflows/Main.yml#L235), and run the Python tests as-is. Perhaps that would also work for the R package (using `BUILD_R=1`)? That might simplify the CI somewhat since the coverage would be kept in one place, and no additional (patched) package would be necessary.

**Comment by krlmlr** [comment]
Thanks. With covr we get the coverage of both the R and the C++ code. We could get the C++ coverage using the default CI and then use covr only to get the coverage of the R code (with a second test run). We might then be able to use path fixing in codecov to avoid the dependency on the patched version.

I propose to use this PR as is for now and perhaps refactor later?

**Pull request merged**
