### PR TITLE
Several parser improvements

### PR DESCRIPTION
**Pull request by Mytherin**
* Allow using the `VALUES` clause in the `FROM` without brackets as long as an alias is specified
* Allow using string literals ('a') as identifiers in more places, including table aliases
* Remove the requirement for `WHERE` in filter expressions of aggregates

### CODE REVIEW

**Comment by djouallah** [comment]
what is this "Remove the requirement for WHERE in filter expressions of aggregates" ?

**Comment by Alex-Monahan** [comment]
Good question! It relates to the FILTER clause within the select statement. It allows you to apply a different row filter (where clause) to each aggregate in your select statement! This is just removing the need to have the keyword `WHERE` as a part of that FILTER clause.
https://duckdb.org/docs/sql/query_syntax/filter

**Comment by djouallah** [comment]
are you telling me this is legit ? Oh Boy, we are now in DAX territory :) 

SELECT 
    sum(i) FILTER (i <= 5) as lte_five_sum from xxx

**Comment by Alex-Monahan** [comment]
> are you telling me this is legit ? Oh Boy, we are now in DAX territory :)
> 
> SELECT sum(i) FILTER (i <= 5) as lte_five_sum from xxx

Yup! It even works in Window functions: #3696

**Comment by djouallah** [comment]
That's fantastic !!!!, so all we need is a way to run a query using existing relationship and DuckDB will behave as full Data Model, Joking, joking maybe not , thank you !!!

**Pull request merged**
