### PR TITLE
Added a fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer that targets `Query`.
Fuzzing is a way of testing applications, where pseudo-random data is passed to the target function - which in this particular fuzzer is `Query()` - with the goal of uncovering bugs and security vulnerabilities.

I will furthermore suggest to set up continuous fuzzing of duckdb by way of oss-fuzz. This will allow Google to run the fuzzers and notify maintainers if any bugs are found. OSS-fuzz is a free service that is offered with an implied expectation that bugs are fixed, so the resources spent on fuzzing DuckDB go towards resolving bugs.
There are several benefits of continuous fuzzing, some of which are:

- Some bugs have been reported to be found after several CPU years of continuous fuzzing.
- The fuzzers are actually run. It happens often that effort is put into writing the fuzzing test suite, but it is only rarely run if it is run at all.
- The bug reports provide detailed stack traces and reproducer test cases.

The fuzzer runs on OSS-fuzz's infrastructure. I have the complete integration build ready, and I will be happy to complete the integration of DuckDB. For this, all I need are the email addresses for maintainers to receive potential bug reports. These will be added to a public list that can be changed at any time.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Thanks for your PR, could you perhaps clarify for me how to run this fuzzer specifically?

**Comment by AdamKorcz** [comment]
Thank you for your quick response! 
At this time I have worked on making this fuzzer run continuously through OSS-fuzz. After integration I would integrate the fuzzer into the DuckDB build system. As this is additional work, my thought was to first get confirmation from both the DuckDB maintainers and OSS-fuzz that there is interest in fuzzing DuckDB.

For "proof" that it does work at this point, I can suggest setting up DuckDB on OSS-fuzz without merging the fuzzer upstream first. OSS-fuzz runs a bunch of integration tests that should pass.

Let me know if you can proceed in either of the ways described above.

**Comment by hannesmuehleisen** [comment]
Does OSS-fuzz understand that this `Query` method takes SQL strings and creates those?

**Comment by AdamKorcz** [comment]
Just a bit of clarification, and I should have mentioned this earlier, sorry for that. The fuzzer is implemented by way of [LibFuzzer](https://llvm.org/docs/LibFuzzer.html) and runs continuously on Googles [OSS-fuzz](https://github.com/google/oss-fuzz) infrastructure. 

To answer your question: No, the fuzzer does not understand that the input is structured SQL queries. However, this is not an issue if given enough time (which it will be if it runs continuously). LibFuzzer is a coverage-guided fuzz engine which means that it passes pseudo-random data to the target function, and when the fuzzer reaches new coverage it uses the feedback from this in its input-generation. This means that over time, the fuzzer will generate input-queries that by the target application are considered valid. 

In case anyone would like a good introductory presentation on fuzzing, I can recommend [this video](https://www.youtube.com/watch?v=FzaR3iH2iZs).

**Comment by hannesmuehleisen** [comment]
Thanks for the clarification, it says on https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/ that "To be accepted to OSS-Fuzz, an open-source project must have a significant user base and/or be critical to the global IT infrastructure." Do you think this is feasible to setup for DuckDB?

**Comment by hannesmuehleisen** [comment]
Yes, DuckDB is used in production, see #1172 for example :) We should perhaps collect a list somewhere. I have another question regarding the fuzzer function. It looks like it always returns 1, should there not be some way for the fuzzer to distinguish valid/invalid input somehow?

**Comment by exaatto** [comment]
> Yes, DuckDB is used in production, see #1172 for example :) 

We are overwhelmed that we might be the very first production (or semi-production as I think) use case of duckdb. Although it's quite not a convention use case and I cannot disclose too many details for the time been, I may be able to elaborate our situation a little bit.

We are in some kind of manufacturing industry that using some commercial desktop data processing and analysis tool for decades. It's good and sound, running tons of legacy scripts written by non-IT stuff such as QA or equipment maintenance engineers all these years for reporting/statistical-modeling/... However, recently we are considering replacing it with some more modern and open stack such as python/R/etc., for both tech and business reason. All the other parts seems easy to pick but we just fail to find a good on-disk data store with SQL support until we came across duckdb.

Currently, we are running a pilot project encouraging those non-IT engineers to port their legacy reporting scripts to our home-grown platform, basically a wrapper of python and SQL on duckdb. Feedback is collected bit by bit and seems prospective.

**Comment by hannesmuehleisen** [comment]
@exaatto Sorry, you're not the first, but I just mentioned you there because you just had written about your production use. Thanks for describing your use case!

**Comment by AdamKorcz** [comment]
@exaattoo Thank you describing your use case. In terms of setting up continuous fuzzing for DuckDB which help harden the project by finding bugs, it will be a great help to name a few companies that use the project in production. Are you able to share the name of your company publicly?
It is a policy of OSS-fuzz to integrate projects that are used in production, and naming adopters/users in the integration process is a helping factor in getting integrated.

**Comment by exaatto** [comment]
@AdamKorcz I'd like to but I'm afraid it's not allowed to reveal more information for the time been due to our company policy. Maybe like Hannes said a list could be setup and I'll be more than happy to put our company's name into it in due course.

**Comment by AdamKorcz** [comment]
@exaatto Duly noted. I think it is a great idea to set up a list of adopters. I have seen other projects do it for example [this one](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/ADOPTERS.md).

**Comment by hannesmuehleisen** [comment]
Closing this for now.

**Comment by AdamKorcz** [comment]
If there is anything I can help with in this regards, do let me know.

We could set up an application on the OSS-fuzz side and see if they require more information than has been provided in this thread.

**Pull request closed without merging**
