### PR TITLE
Add `map_contains`, `map_contains_entry` and `map_contains_value` functions, `list_position` now returns null.

### PR DESCRIPTION
**Pull request by Maxxen**
This PR adds 3 new map functions,
- `map_contains(m, key)` check if a map contains a given key
- `map_contains_entry(m, entry)` check if a map contains a given "entry" (key-value pair struct)
- `map_contains_value(m, v)` check if a map contains a given value

The last two of these are implemented as macros, which is now actually pretty performant as the underlying list_contains function has been optimized to use sort key-serialization for nested types. We also reuse that code in `map_contains` making the implementation pretty small.

`map_contains` is also an alias for the now-overloaded `contains` function, so that it is now possible to check key-containment using the new `IN` operator, e.g. `SELECT 'my_key' IN map(['my_key'], ['my_value'])` now works.

We also handle the special-case when a constant `map([],[])` is given as input and return constant false.

Additionally, this PR changes the semantics of `list_position`. Instead of returning 0 when the element is not found, it now returns null. This is also how the equivalent function in PostgreSQL works.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! I wonder about the naming. `map_contains` to me seems like it should be looking up the `key` - IIRC all program languages I can think of have `contains` refer to a key lookup (e.g. `::find` in `unordered_map`, `in` in Python dictionaries, etc). 

I also wonder if we can implement `map_contains_keys` and `map_contains_values` as a macro by running `contains` on `map_keys` or `map_values`, e.g.:

```sql
select contains(map_keys(map {'a': 42, 'b': 84}), 'a') AS result;
┌─────────┐
│ result  │
│ boolean │
├─────────┤
│ true    │
└─────────┘
```

**Comment by Maxxen** [comment]
How about we implemented `map_contains` and `map_contains_key` as overloads of the same `map_contains`, making the `value` parameter optional?

**Comment by Mytherin** [comment]
That's fine by me as well

**Comment by Maxxen** [comment]
Ok this pr now implements all three functions as macros.
But I've also reworked map_extract/list_contains/list_position to use sortkey serialization for nested types (instead of the value api), and list_position now returns NULL if the value is not found (instead of 0 like it used to do). 

Additionally, `map_contains` now has two overloads, one taking a kv-struct (basically, a "entry") and another taking two arguments, "k" and "v" (that internally get grouped into an entry). This makes it trivial to implement as a macro `map_contains(m, kv) = list_contains(map_entries(m), kv)` but in the future we could also make this a proper function and overload the `contains` call so that you can use the new `IN` operator e.g. `SELECT {'key': 'a', 'value': 10} IN my_map`. But ill leave that for the future.

**Comment by Mytherin** [comment]
Thanks!

**Comment by szarnyasg** [comment]
`map_contains_entry` expects a key and a value, not a struct:

```sql
select map_contains_entry(MAP {'key1': 10, 'key2': 20, 'key3': 30}, {'key2': 20});
```
```console
Binder Error: Macro function map_contains_entry(map, key, value) requires 3 positional arguments, but 2 positional arguments were provided.
LINE 1: select map_contains_entry(MAP {'key1': 10, 'ke...
```
```sql
SELECT map_contains_entry(MAP {'key1': 10, 'key2': 20, 'key3': 30}, 'key2', 20);
```
```text
true
```

**Comment by Maxxen** [comment]
Right, that's intended just me rushing the docs. If you want key-value struct you can just do `{'k': 'v'} in map_entries(m)`

**Pull request merged**
