### PR TITLE
Fix for extract quarter

### PR DESCRIPTION
**Pull request by Mytherin**
This fixes issue #975

### CODE REVIEW

**Comment by nmichaud** [comment]
Shouldn't the math be: (Date::ExtractMonth(input) / 4) + 1 to shift the range from [0,3] to [1,4]?

**Comment by Mytherin** [comment]
> Shouldn't the math be: `(Date::ExtractMonth(input) / 4) + 1` to shift the range from [0,3] to [1,4]? `(Date::ExtractMonth(input) - 1) / 3 + 1` gives the correct result but that's coincidental (because 12 is also divisible by 3).

A quarter has three months, not four months, hence division by three is correct here. We subtract by 1 (because Date::ExtractMonth gives us January as month 1, rather than month 0). Then we divide by three to divide the months into four discrete blocks.

[Jan, Feb, Mar] -> 0
[Apr, May, Jun] -> 1
[Jul, Aug, Sep] -> 2
[Oct, Nov, Dec] -> 3

Then add 1 to get the range [0, 4].

Dividing by four and adding one gives the wrong result, in that case the following division would be made:

[Jan, Feb, Mar] -> 1 (1,2,3)
[Apr, May, Jun, Jul] -> 1 (4,5,6,7)
[Aug, Sep, Oct, Nov] -> 2 (8,9,10,11)
[Dec] -> 4 (12)

**Comment by nmichaud** [comment]
Ah sorry, you are correct. I had incorrectly assumed Date::ExtractMonth was from 0-11 (although that would still give the wrong result, bucketing the year into thirds).

**Comment by Mytherin** [comment]
No worries, a quarter being three months is a bit confusing :) I assume I made the same mistake before, hence why there was a division by four before (which was the source of this bug).

**Pull request merged**
