### PR TITLE
[Dev] Fix py override describe

### PR DESCRIPTION
**Pull request by carlopi**
Minor fixes, plus adding `import subprocess` to [tools/pythonpkg/setup.py](https://github.com/duckdb/duckdb/compare/main...carlopi:duckdb:fix_py_override_describe?expand=1#diff-608521909520afae03d3521283535b13782b4ccee56cfd0462d40f8314bcb8c2) that would otherwise be broken in the default setup in https://github.com/duckdb/duckdb/pull/11179.

### CODE REVIEW

**Comment by carlopi** [comment]
Checked with @Tishj, that had pinged me since changes I sent on Friday broke their development setup.
He also recommended adding more specific catch, added as the last commit, that would have helped catch the missing import or future problem that will be added in the future.

Refactor/ unification of scripts/package_build.py and tools/pythonpkg/setup.py still to come, to be looked at after patch release.

**Comment by carlopi** [comment]
Those two runs of the duckdb-test-staging:
https://github.com/duckdb/duckdb-test-staging/actions/runs/8314855851
https://github.com/duckdb/duckdb-test-staging/actions/runs/8314855036

will test this

**Comment by carlopi** [comment]
Another round of small changes after some more testing.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
