### PR TITLE
Default argument support for Macro's

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR implements support for default arguments created with `CREATE MACRO`. For example:
```
D CREATE MACRO add_default5(a, b=5) AS a + b;
D SELECT add_default5(10);
┌──────────────────┐
│ add_default5(10) │
├──────────────────┤
│ 15               │
└──────────────────┘
D SELECT add_default5(10, b=6);
┌───────────────────────┐
│ add_default5(10, b=6) │
├───────────────────────┤
│ 16                    │
└───────────────────────┘
```

I've added some tests in test/sql/catalog/function/test_simple_macro.test

There is one edge case that I'm unsure how to handle. Could you take a look at the last few test cases under test_simple_macro.test? @Mytherin

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! The PR looks good. In my opinion we should restrict default parameters to constants only; having column expressions as default parameters feels unintuitive (and also wouldn't be possible in a regular function). I think that also resolves the edge case you mentioned.

**Comment by lnkuiper** [comment]
Good call. Disallowed non-constant default values

**Comment by lnkuiper** [comment]
Also checking constant types at create time now:
```
D CREATE MACRO test(s='not a number') AS 1 + s;
Error: Binder Error: No function matches the given name and argument types '+(INTEGER, VARCHAR)'. You might need to add explicit type casts.
```

**Comment by Mytherin** [comment]
Looks great, thanks!

**Pull request merged**
