### PR TITLE
duckdb_*() tags to go from MAP(VARCHAR,VARCHAR) to VARCHAR

### PR DESCRIPTION
**Pull request by carlopi**
Support for nested types are not completely obvious to support, and I feel types of `FROM duckdb_functions()` should be as plain as possible, and `MAP(VARCHAR, VARCHAR)` can be transformed without information loss to `VARCHAR` and back.

Original issue I bumped against is that MAP support in duckdb-wasm shell is not present (see issue), but I think this might be a more general problem, say if those results are saved to CSV or JSON typing information are lost, or say as output of duckdb-python's `fetchmany()`:
```bash
python3
>>> import duckdb
>>> duckdb.sql("SELECT tags FROM duckdb_functions()").fetchmany()
[({'key': [], 'value': []},)]
>>> duckdb.sql("SELECT tags::VARCHAR FROM duckdb_functions()").fetchmany()
[('{}',)]
```

I think forcing type to be VARCHAR, while accesses are performed via casting to MAP(VARCHAR, VARCHAR) might be somewhat better here.
Note that those columns where introduced in 0.10.3 (I should have raised this in the PR), and I believe there are no actual uses (yet) of the tags outside duckdb_spatial's documentation where, I just noticed, it marshal data to JSON first and then into STRUCT(key VARCHAR, value VARCHAR)[] (see https://github.com/duckdb/duckdb_spatial/blob/main/generate_function_reference.py#L21).
Also, spatial documentation is currently run manually, so I believe this to have no impact on existing workflows.

I would propose to keep it to a macro like:
```
CREATE MACRO tag_extract(a,b) AS list_first((a::MAP(VARCHAR,VARCHAR))[b]);
```
defined where needed. I had not added this to duckdb since it can for now defined where useful (possibly with a different semantic) or it can be considered for a future docs-related extension.

### CODE REVIEW

**Comment by Maxxen** [comment]
Disagree, why not just cast when accessing? or do an UNNEST? Havibg to convert from string is going to make "searching"/filtering tags a lot slower. Ideally all clients _should_ support maps, just like they do lists and structs.

If we return the tags as string then we might as well just change it so that instead of storing a unordered_map<string, string> its unordered_map<string, Value> instead too.

**Comment by Mytherin** [comment]
I agree with @Maxxen - lacking `MAP` support in WASM/Python is not a good reason to change the return type of this function. Maps can be created in different ways anyway. If anything this is good motivation to improve MAP support in those clients. 

> say if those results are saved to CSV or JSON typing information are lost

This is not the case in JSON, the map type is preserved:

```
copy (select map {'key': 'value'} as map_val) to 'file.json';
```

####### file.json
```
{"map_val":{"key":"value"}}
```

This is the case in CSV - but that applies to all types equally.

**Comment by carlopi** [comment]
Sure, this also makes sense.

Just to be slightly more clear, my main point is that returns types of functions are more visible than generic types, and saying interacting with DuckDB (say some tools on top of it) means having to support arbitrary types might be a bit too much.

For test_all_types() some clients have workarounds, and I wanted to move those checks within duckdb since doing them externally is not super doable (or at least I don't see a way).

Examples:
* duckdb-rs skips them in test_all_types tests (might be outdated)
* duckdb-wasm shell do not support maps (I think tied to arrow-rs problem, unsure if outdated)
* sqlite_scanner/postgres_scanner do not support writing maps (or at least are at the moment skipped in the tests for test_all_types)
Unsure if there are others.

Would a global DB setting to toggle between MAP(VARCHAR, VARCHAR) and VARCHAR might be a possibility at all here?

**Comment by Mytherin** [comment]
We could perhaps think of a more generic return type remap of sorts, or a callback, that could be interesting. In any case that is future work (i.e. not going to be in 1.0).

**Pull request closed without merging**
