### PR TITLE
Add building, testing and distributing for Python 3.13

### PR DESCRIPTION
**Pull request by carlopi**

### CODE REVIEW

**Comment by carlopi** [comment]
More complete CI here: https://github.com/carlopi/duckdb/actions/runs/10987525598/job/30502510946#step:9:12694

**Comment by Mytherin** [comment]
Thanks!

**Comment by nullas** [comment]
Just curious, when will this be available in conda?  I am not able to install duckdb with python 3.13.

**Comment by carlopi** [comment]
We don't maintain the conda packaging of duckdb python client, it's done by external (and wonderful) contributors at https://github.com/conda-forge/python-duckdb-feedstock.

I had seen some interactions with @xhochy, they might know more.
And it seems there is a PR in flight for this at https://github.com/conda-forge/python-duckdb-feedstock/pull/118

**Comment by xhochy** [comment]
Didn't have time to catch up on this. The PR is merged and 3.13 should be available in 90min.

**Pull request merged**
