### PR TITLE
Issue #2348: Support bankers rounding as default function

### LINKED ISSUE #2348: Support Bankers rounding
DuckDB's rounding right now rounds tries up. While it's the common rounding method for programming languages, it is not as numerically stable as rounding ties to the next even: https://stackoverflow.com/questions/45223778/is-bankers-rounding-really-more-numerically-stable. It would be great if you could consider changing the default rounding algorithm or adding `round_to_even` as an expression function. Note that R's default rounding is rounding to even. It's also the IEC 60559 standard and [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754#Rounding_rules). https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Round

### PR DESCRIPTION
**Pull request by Mytherin**
Support the `round_even` (and `roundBankers` alias) function as created by @hawkfish.

```sql
select i, round_even(i + 0.5, 0) from generate_series(-2,4) tbl(i);
----
-2	-2
-1	0
0	0
1	2
2	2
3	4
4	4
```

### CODE REVIEW

**Comment by domoritz** [comment]
Fixes #2348

**Comment by domoritz** [comment]
Just wondering about the names here. What's the pattern? Why don't we name the functions `round_to_even` and `bankers_round` or `round_bankers` instead?

**Comment by Mytherin** [comment]
> Just wondering about the names here. What's the pattern? Why don't we name the functions `round_to_even` and `bankers_round` or `round_bankers` instead?

I'm using `roundBankers` for compatibility with [Clickhouse](https://clickhouse.com/docs/en/sql-reference/functions/rounding-functions/). I couldn't find any other system that provides this function.

**Comment by domoritz** [comment]
I see. It would probably be good to establish a DuckDB expression naming convention for expression functions since different systems may have different conventions and we could end up with an inconsistent set of function names.

Anyway, this is beyond this pull request. Thanks again for implementing round to even.

**Comment by Mytherin** [comment]
> I see. It would probably be good to establish a DuckDB expression naming convention for expression functions since different systems may have different conventions and we could end up with an inconsistent set of function names.

We have a naming convention, it is in snake case (`round_even`). For some functions we add aliases to match the functions found in other systems (which might have different naming conventions, e.g. ClickHouse), but the snake_case function should be considered the "canonical" version.

**Comment by domoritz** [comment]
Ahh, makes sense. Thanks for the explanation!

**Pull request merged**
