### PR TITLE
Add support for materialized CTEs in INSERT/UPDATE/DELETE statements

### PR DESCRIPTION
**Pull request by kryonix**
With this PR it is possible to use materialized CTEs in context of INSERT/UPDATE/DELETE statements. This was missing in https://github.com/duckdb/duckdb/pull/7126.

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks good. Could you perhaps expand a bit on the introduction of the `MaterializedCTEStatement`? I feel that this might be the wrong level of abstraction - i.e. I wouldn't consider an insert statement to no longer be an insert statement just because it has a materialized CTE attached to it. Could this use the existing CTE map in some capacity?

**Comment by kryonix** [comment]
Hi @Mytherin, I understand your concerns. You are right, it is possible to reconstruct the required information from the CTE map. But I did feel like the solution would be more _hacky_, especially in the binding phase. The nesting of  `MaterializedCTEStatements` establishes the correct Binder contexts for subsequent statements (which is important for scoping of the CTEs). This allows to keep the binding phase more or less straightforward and almost identical to the binding of `CTENode`s. The call-stack looks like this:

```
Bind({Update/Delete}Statement)
Bind(MaterializedCTEStatement) ⎫
⋮                              ⎬ one or many materialized CTEs
Bind(MaterializedCTEStatement) ⎭
⋮
```

With this solution `Bind({Update, Delete}Statement)` remains unchanged.

Without `MaterializedCTEStatement`, we would enter `Bind({Update, Delete}Statement)` immediately, and we would have to
1. reconstruct the materialized CTEs from the CTE map (that's easy)
2. bind the materialized CTEs to establish the correct binding contexts (we would need a special version of `BindNode(CTENode &statement)`—I think).
3. finish binding of the {Update, Delete}Statement using the correct Binder instance.

Instead of an explicit representation of the materialized CTE in the statement AST, we would instead rely on kind of a 'side effect'.

Btw. all of this is not necessary for `InsertStatements`, because here, we have a `QueryNode` to which we can just add the materialized `CTENode`s.

Let me know what you think. I can have a look at the alternative version using the CTE map. But personally, I'm a fan of explicit representations, if possible.

**Comment by Mytherin** [comment]
Statements are user-facing (e.g. using `ExtractStatements` in C++, `duckdb_extract_statements` in the C API or the new `extract_statements` in Python (https://github.com/duckdb/duckdb/pull/10891). As a user it would be rather confusing to have this query return an `UPDATE_STATEMENT`:

```sql
with cte as (select 42) delete from tbl where id in (from cte);
```

But to have this query return a `MATERIALIZED_CTE_STATEMENT`:

```sql
with materialized cte as (select 42) delete from tbl where id in (from cte);
```

As such I would prefer the other approach. Perhaps we could extract/unify the code in a different manner?

Another perhaps related question is - in the future we might want to make the CTE materialization automatic. For example, an idea that has been thrown around is to automatically add `MATERIALIZED` to a CTE if it is referenced multiple times in the query. I wonder how that would work with the current way of binding CTEs?

**Comment by kryonix** [comment]
I see. I was not aware of this interface. 

Alright I will have a look at the alternative version. I kind of started already 😉 And yeah, maybe the code paths can be combined. That would be the best case. 

I did have the same idea regarding automatic placement of materialized CTEs. Actually, I intend to have a student of mine explore this idea in the next semester. Multiple references could be one heuristic to place materialization, maybe there could be more? If you have concrete plans to let someone work on that please let me know. But generally you are right, if we would use the CTE map, this idea should become much easier to implement.

**Comment by Mytherin** [comment]
There's no immediate plans to work on it - would be great if your student can pick it up :)

**Comment by Mytherin** [comment]
Unrelated to this PR - but we have been seeing some spurious CI failuers in the `test/sql/cte/materialized/recursive_cte_correlated_subquery_materialized.test_slow` test:

```bash
Wrong row count in query! (test/sql/cte/materialized/recursive_cte_correlated_subquery_materialized.test_slow:7)!
Expected 1 rows, but got 0 rows
================================================================================
WITH RECURSIVE
input(sud) AS MATERIALIZED (
VALUES('53..7....6..195....98....6.8...6...34..8.3..17...2...6.6....28....419..5....8..79')
),
digits(z, lp) AS MATERIALIZED (
SELECT CAST(lp+1 AS TEXT), lp::int+1 FROM generate_series(0,8,1) t(lp)
),
x(s, ind) AS MATERIALIZED (
SELECT sud, instr(sud, '.') FROM input
UNION ALL
SELECT
substr(s, 1, ind::int-1) || z || substr(s, ind::int+1),
instr(substr(s, 1, ind::int-1) || z || substr(s, ind::int+1), '.' )
FROM x, digits AS z
WHERE ind::int>0
AND NOT EXISTS (
SELECT 1
FROM digits AS lp
WHERE z.z = substr(s, ((ind::int-1)//9)*9 + lp, 1)
OR z.z = substr(s, ((ind::int-1)%9) + (lp-1)*9 + 1, 1)
OR z.z = substr(s, (((ind::int-1)//3) % 3) * 3
+ ((ind::int-1)//27) * 27 + lp
+ ((lp-1) // 3) * 6, 1)
)
)
SELECT s FROM x WHERE ind::int=0;
================================================================================
Expected result:
================================================================================
534678912672195348198342567859761423426853791713924856961537284287419635345286179
================================================================================
Actual result:
================================================================================
s	
VARCHAR	
[ Rows: 0]


```

This seems to be a race condition, adding a loop to the test makes it produce consistently on my laptop:

```
# name: test/sql/cte/materialized/recursive_cte_correlated_subquery_materialized.test_slow
# description: Issue #2713: reports struct_extract error when run a sql
# group: [materialized]

loop i 0 10000

query I
WITH RECURSIVE
input(sud) AS MATERIALIZED (
VALUES('53..7....6..195....98....6.8...6...34..8.3..17...2...6.6....28....419..5....8..79')
),
digits(z, lp) AS MATERIALIZED (
SELECT CAST(lp+1 AS TEXT), lp::int+1 FROM generate_series(0,8,1) t(lp)
),
x(s, ind) AS MATERIALIZED (
SELECT sud, instr(sud, '.') FROM input
UNION ALL
SELECT
substr(s, 1, ind::int-1) || z || substr(s, ind::int+1),
instr(substr(s, 1, ind::int-1) || z || substr(s, ind::int+1), '.' )
FROM x, digits AS z
WHERE ind::int>0
AND NOT EXISTS (
SELECT 1
FROM digits AS lp
WHERE z.z = substr(s, ((ind::int-1)//9)*9 + lp, 1)
OR z.z = substr(s, ((ind::int-1)%9) + (lp-1)*9 + 1, 1)
OR z.z = substr(s, (((ind::int-1)//3) % 3) * 3
+ ((ind::int-1)//27) * 27 + lp
+ ((lp-1) // 3) * 6, 1)
)
)
SELECT s FROM x WHERE ind::int=0;
----
534678912672195348198342567859761423426853791713924856961537284287419635345286179

endloop


```

Could you perhaps have a look at that (in a separate PR)?

**Comment by kryonix** [comment]
I think you are right, this is a race condition. If I add `PRAGMA threads=1`, I can no longer reproduce the error.
There might be a pipeline dependency missing—And I think I already have a fix for that. I will open a separate PR for it.

**Comment by Mytherin** [comment]
Thanks for the updates! LGTM

**Comment by Tmonster** [comment]
Hi @kryonix ,

It seems that this PR has created a regression for one of our customers that uses a lot of CTEs. Specifically commit `3f3f7b2c2c54bda30f76108c7ec5737c53e601b4` is causing the regression. Do you know what might be the issue? 

Here is a small example to reproduce it
```
create table t1 as select range id from range(1000000);
with 
mat_t1 as materialized (select * from t1),
mat_t2 as materialized (select * from mat_t1),
mat_t3 as materialized (select * from mat_t2 where id not in (
                        select id % 20 from mat_t2
                        )),
mat_t4 as materialized (select * from mat_t1 where id not in (
						select (id % 20) + 20 from mat_t2
						UNION ALL
						select (id % 20) + 40 from mat_t3
						)),
mat_t5 as materialized (select * from mat_t1 where id not in (
						select (id % 20) + 20 from mat_t2 
						UNION ALL
						select (id % 20) + 40 from mat_t3
						UNION ALL
						select (id % 20) + 60 from mat_t4
						)),
mat_t6 as materialized (select * from mat_t1 where id not in (
						select (id % 20) + 20 from mat_t2 
						UNION ALL
						select (id % 20) + 40 from mat_t3
						UNION ALL
						select (id % 20) + 60 from mat_t4
						UNION ALL
						select (id % 20) + 80 from mat_t5
						)),
mat_t7 as materialized (select * from mat_t1 where id not in (
						select (id % 20) + 20 from mat_t2 
						UNION ALL
						select (id % 20) + 40 from mat_t3
						UNION ALL
						select (id % 20) + 60 from mat_t4
						UNION ALL
						select (id % 20) + 80 from mat_t5
						UNION ALL
						select (id % 20) + 80 from mat_t6
						)),
mat_t8 as materialized (select * from mat_t1 where id not in (
						select (id % 20) + 20 from mat_t2 
						UNION ALL
						select (id % 20) + 40 from mat_t3
						UNION ALL
						select (id % 20) + 60 from mat_t4
						UNION ALL
						select (id % 20) + 80 from mat_t5
						UNION ALL
						select (id % 20) + 80 from mat_t6
						UNION ALL
						select (id % 20) + 80 from mat_t7
						))
Select * from mat_t1 UNION ALL
select * from mat_t2 UNION ALL
select * from mat_t3 UNION ALL
select * from mat_t4 UNION ALL
select * from mat_t5 UNION ALL
select * from mat_t6 UNION ALL
select * from mat_t7 UNION ALL
select * from mat_t8;
```
These are run times on my machine (just for the script not the table creation).
```
v0.10.1
Run Time (s): real 0.318 user 0.733344 sys 0.111851
```
```
v0.10.2
Run Time (s): real 1.170 user 4.963339 sys 1.108641
```

**Comment by kryonix** [comment]
Hi @Tmonster, I will have a look.

**Pull request merged**
