### PR TITLE
Add SQL:2016 listagg

### PR DESCRIPTION
**Pull request by renevdzee**
This pull request adds the SQL:2016 standard LISTAGG as an alias for STRING_AGG

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! LGTM

**Comment by renevdzee** [comment]
I do not understand why the CodeQuality check is failing. I assumed I solved it by renaming the function to ListaggFun with a lower case 'a'. Can somebody explain me why it is still failing so I can resolve that?

**Comment by Mytherin** [comment]
Looks like the function is placed in the wrong place in the function list. Instead of manually editing `function_list.hpp` you should run `python3 scripts/generate_functions.py` to generate the list of functions.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
