### PR TITLE
Bump spatial

### PR DESCRIPTION
**Pull request by Maxxen**
Apart from new features I've also fixed a bunch of issues, including a pretty severe memory leak so it would be good to have this in the next bugfix release.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks! LGTM - could you just re-generate the extension functions?

**Comment by Maxxen** [comment]
@Mytherin I don't understand why the CI complains, `st_numpoints` is added to the extension function list?

**Comment by Mytherin** [comment]
Looks like the [regex fails](https://github.com/duckdb/duckdb/blob/f198a863cacc778d9c3bacd2cdaac0acda31d173/scripts/generate_extensions_function.py#L91) because of formatting. Can you perhaps adjust the regex to `"{\"(.*?)\", \"(.*?)\"}[,}\n]"` (i.e. accept trailing comma, bracket or newline).

**Comment by Maxxen** [comment]
@Mytherin I'm failing on an unrelated CSV error. Could you rerun the check?

**Comment by Maxxen** [comment]
Thanks!

**Pull request merged**
