### PR TITLE
[Python] Don't clog the `tools/pythonpkg/duckdb` folder on build

### PR DESCRIPTION
**Pull request by Tishj**
Previously we dumped the amalgamation build to the "duckdb" folder in the python pkg folder, because we didn't use it.
Since #8189 we now use the "duckdb" folder, but it was still being clogged with all the amalgamation build files when we built using `python3 setup.py install`.

Now we write these files to "build" instead.

### CODE REVIEW

**Comment by Mause** [comment]
The build folder is already used by python, we'll need to use something else

**Comment by Tishj** [comment]
> The build folder is already used by python, we'll need to use something else

Ah, I'll go for duckdb_build then

**Review by Mause — CHANGES_REQUESTED** [review]
Let's amend the gitignore while we're here too

**Comment by hawkfish** [comment]
I'm not competent to review this, but it would really make my editors happy not to have to scan irrelevant copies of the code.

**Review by Mause — APPROVED** [review]

**Pull request merged**
