### PR TITLE
[Python] Fix memory leaks caused by mismanaging retrieved PyObject* references

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #7039 

I'm not really sure how to make tests for this, and also `py::cast<py::object>(<some PyObject pointer>)` looks like it should properly take the reference, but it doesn't.
So that's kind of a foot gun I would like to remove, I think after the Pandas2.0.0 PR is merged I can make that change, will make an issue for it.

### CODE REVIEW

**Comment by Tishj** [comment]
I saw in another thread Pedro mentioned something like
```py
import pandas as pd
import duckdb
import numpy as np

import os, psutil
process = psutil.Process(os.getpid())
mem_usage = process.memory_info().rss

for __ in tqdm(range(10_000_000)):
    df = pd.DataFrame({"x": np.random.rand(1_000_000)})
    duckdb.query_df(df, "df", "SELECT * FROM df")

cur_mem_usage = process.memory_info().rss
assert that cur_mem_usage is on the same order of magnitude of mem_usage
```

I'll have a go at writing a test for this 👍

**Comment by Mytherin** [comment]
One of the leak tests seems to have flagged something - I have restarted it but there’s a good chance it’s not a false positive. Perhaps have a look?

**Comment by Tishj** [comment]
Both locally and on Linux I can't reproduce this with a regular debug build.
I've tried building python with address sanitizers following the `Python Address Sanitizer (Linux)` CI workflow, but I ran into issues that I couldn't figure out.
I'll try again later, but as of yet I can't seem to debug this

**Comment by Mytherin** [comment]
Considering it is only failing in the address sanitizer case - the issue is likely related to the extra memory taken up by the address sanitizers for memory tracking and such. Perhaps we can just disable the test in this case?

**Comment by Mytherin** [comment]
Failures are unrelated - LGTM!

**Comment by Mytherin** [comment]
Actually looks like there are some merge conflicts that must be resolved - could you merge with master?

**Pull request closed without merging**
