### PR TITLE
Add signbit function for floating point values

### PR DESCRIPTION
**Pull request by carlopi**

### CODE REVIEW

**Comment by hawkfish** [comment]
Thanks for the PR!  is there a reason you can't just use [the existing `SIGN` function](https://duckdb.org/docs/sql/functions/numeric#numeric-functions)?

**Comment by carlopi** [comment]
Hi! This should address the discussion here: https://github.com/duckdb/duckdb/discussions/5846.

Unsure of the exact relevance/use case, but there might be occasion where negative and positive 0 needs to be kept separate, plus potentially some classifications of NaN (even though it's probably not portable).

**Review by hawkfish — APPROVED** [review]
Looks great!

**Comment by carlopi** [comment]
This should address the discussion at https://github.com/duckdb/duckdb/discussions/5846, implementing signbit for floating point types and adding a relative relative SQL test.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
