### PR TITLE
Add wildcard to JSON Path

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR adds wildcards (`*`) to JSON Path expressions. Wildcards work for JSON object fields, and for JSON array elements. For example:
```sql
select json_extract('[{"duck":42},{"duck":43}]', '$[*].*')
-- [42, 43]
```

If a wildcard occurs in a JSON Path, the result is `LIST(JSON)` instead of `JSON`.

Wildcards cannot occur when extracting multiple JSON, e.g.:
```sql
select json_extract('[{"duck":42},{"goose":43}]', ['$[*].duck', '$[*].goose',])
```

As we cannot add a `LIST(JSON)` element to what already would be a `LIST(JSON)`. An alternative implementation would just create a JSON array of the elements found by the wildcard, then this would work. However, it would be significantly less efficient.

Fixes #5763, #6921

### CODE REVIEW

**Comment by lnkuiper** [comment]
Going to write some more tests to improve coverage

**Comment by Mytherin** [comment]
Thanks!

**Comment by chowsanthony** [comment]
Can you please update the documentation how wildcards is supported? For example, on this page: https://duckdb.org/docs/extensions/json

**Comment by Mytherin** [comment]
Could you file an issue in the [duckdb-web](https://github.com/duckdb/duckdb-web/issues) repo instead?

**Pull request merged**
