### PR TITLE
Extensible Replacement Scans & Automatic Pandas Scans

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds the concept of extensible replacement scans. Replacement scans are table functions that are automatically substituted when a base table is not found. For example, this allows you to run the following query:

```sql
SELECT * FROM 'data/test.csv';
```

When the table with the name "data/test.csv" is not found, the system will look at the extension (.csv) and replace this with a `read_csv_auto` scan. This makes the above query equivalent to:

```sql
SELECT * FROM read_csv_auto('data/test.csv');
```

This functionality already existed before, but was previously hard-coded for CSV files and parquet files. In this PR, we make this extensible rather than hard-coded, as this is generally useful beyond just these two cases.

One case for which this is useful is for the Python extension. For the Python extension, we support scanning of Pandas DataFrames. However, currently they need to be manually registered to be used, e.g. you can run the following code to scan a Pandas DataFrame:

```py
import duckdb
con = duckdb.connect()
df_in = pd.DataFrame({
	'float': [1.0, 2.0, 1.0],
	'string': ["Hello", "World", "123"]
})
con.register('data', df_in)
print(con.execute('select * from data').fetchall())
```

This is semi-elegant, but the explicit 'register' step is annoying, especially when doing ad-hoc analysis. Instead, using these extensible replacement scans, we now support directly querying the Pandas DataFrame:

```py
import duckdb
con = duckdb.connect()
df_in = pd.DataFrame({
	'float': [1.0, 2.0, 1.0],
	'string': ["Hello", "World", "123"]
})
print(con.execute('select * from df_in').fetchall())
```

The way it works is that when a table is not found (`df_in`), it instead looks first (1) in the local variables of the Python scope, and (2) in the global Python scope, for an object with that name. If that exists, it instead initiates a Pandas scan over that object. This allows you to directly execute SQL on Pandas DataFrames without having to register anything: if the object exists in your local scope you can query it directly.

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
I mentioned this feature to my team, and they were thinking that it might be a bit of a security risk if DuckDB were used in a server environment like ours... Would you mind exposing a flag to the Python client to disable this feature? It's perfect for analytical tasks, but folks using DuckDB as a processing engine may not want to grant access to all Dataframes by default.

**Comment by Mytherin** [comment]
@Alex-Monahan 
Another potential safety consideration could be the `read_csv` and `read_csv_auto`, since these allow you to read arbitrary files from disk, e.g. this will work:

```sql
select * from read_csv_auto('/etc/passwd');
────────────────────────────────────────────────────────────────────────────────────┐
│                                      column0                                       │
├────────────────────────────────────────────────────────────────────────────────────┤
│ ##                                                                                 │
│ # User Database                                                                    │
│ #                                                                                  │
│ # Note that this file is consulted directly only when the system is running        │
│ # in single-user mode.  At other times this information is provided by             │
│ # Open Directory.                                                                  │
│ #                                                                                  │
│ # See the opendirectoryd(8) man page for additional information about              │
│ # Open Directory.                                                                  │
│ ##                                                                                 │
....
```

**Comment by Alex-Monahan** [comment]
You are correct! I still owe you an issue! There was one in the past for
the csv portion - I'll dig it up and link it.

Thanks,
Alex

**Comment by Alex-Monahan** [comment]
I added an issue on this topic here: [1771](https://github.com/duckdb/duckdb/issues/1771)

Please let me know if I missed a feature I should have included!

Thanks again for your help!

**Pull request merged**
