### PR TITLE
Always parallelize CSV reader when run over multiple files, and several other fixes

### PR DESCRIPTION
**Pull request by Mytherin**
This PR includes the following fixes related to the CSV reader:

* Always parallelize the CSV reader when run over multiple files, including when `experimental_parallel_csv_reader` is turned off. We can always safely parallelize multi-file reads without loss of functionality.
* Avoid re-running the auto-detection on each file when `union_by_name` is not enabled. When running on multiple files each file is required to have the same schema and types - so avoid running the expensive auto-detection on each file unnecessarily.
* Fix the progress bar for the CSV reader when reading multiple files
* Remove `INTEGER` from the auto-detect options, much like why we don't have `SMALLINT` and `TINYINT` auto-detecting integers can lead to problems if we encounter values that are larger than `INT_MAX` later on. `BIGINT` is always chosen instead now, as it is the safer option without sacrificing significantly in terms of performance.

### CODE REVIEW

**Comment by domoritz** [comment]
This change creates a regression for JavaScript and WASM users since numbers is JavaScript are Int32. See https://github.com/observablehq/stdlib/pull/350#issuecomment-1452684540 for an example. BigInts introduce huge performance and usability penalties unfortunately.

I think it would be good to have an option on the CSV reader to infer the data types purely based on the sample and crash if invalid values are encountered later.

**Comment by Mytherin** [comment]
> This change creates a regression for JavaScript and WASM users since numbers is JavaScript are Int32. See [observablehq/stdlib#350 (comment)](https://github.com/observablehq/stdlib/pull/350#issuecomment-1452684540) for an example. BigInts introduce huge performance and usability penalties unfortunately.
> 
> I think it would be good to have an option on the CSV reader to infer the data types purely based on the sample and crash if invalid values are encountered later.

Hm, that is interesting. Perhaps it would make sense to use doubles instead of bigints as @kimmolinna suggested? Doubles can exactly store integer values until 2^53, which is still larger than int32 can.

We could also solve this by making the types the auto-detector considers user-configurable, e.g.:

```sql
SET csv_auto_detect_types='VARCHAR,TIMESTAMP,DATE,TIME,DOUBLE,BIGINT,INTEGER,BOOLEAN'
```

**Comment by kimmolinna** [comment]
@Mytherin The user-configurable auto-detector sounds good. Then you can still use "just" integers but you can decide yourself what is the biggest number.

**Comment by domoritz** [comment]
I like the option idea of providing a list of types to the parser. 

Parsing into small numbers can be important when exporting arrow or parquet. 

Another useful feature would be to cast columns in a table to the smallest (in terms of bytes) possible integer or decimal type. With the right statistics that could be done easily. One could then import a csv first and then process it before doing more processing or exporting it to a file where size matters.

**Comment by domoritz** [comment]
I created https://github.com/duckdb/duckdb/discussions/6556 and https://github.com/duckdb/duckdb/discussions/6555 as feature requests.

**Pull request merged**
