### PR TITLE
Move WebAssembly workflows to separate yml file

### PR DESCRIPTION
**Pull request by carlopi**

### CODE REVIEW

**Comment by carlopi** [comment]
Blocked on https://github.com/duckdb/duckdb/issues/6954

**Comment by Tishj** [comment]
Looks like all CI is borked by it, because of `pandas>=0.24`. We should really lock versions, so CI doesnt break randomly because of an update

**Comment by carlopi** [comment]
Unsure if it was the right call in merging PRs, but added also some commits on moving WebAssembly CI runs into separate workflow + having a separate tools/wasm folder to keep stuff only relevant for wasm. Idea is that changes there will not trigger full-CI work.

**Comment by carlopi** [comment]
This has some conflict with safe-vector, waiting for https://github.com/duckdb/duckdb/pull/6927 to go in, then I will reopen and this should then be trivial.

**Pull request closed without merging**
