### PR TITLE
adding configuration flag to disable copy from/to and read_csv/read_c…

### PR DESCRIPTION
**Pull request by hannes**
…sv_auto functions

### CODE REVIEW

**Comment by ak2k** [comment]
Hi guys, Purely for curiosity sake, was this added to offer more control in an embedded context or for another reason?

**Comment by Mytherin** [comment]
We will tell you a bit later, it's for security purposes :)

**Comment by hannesmuehleisen** [comment]
So the online demo allowed queries like `SELECT * FROM read_csv_auto('/etc/passwd');`, which is a bit of a security issue. With the new flag it is possible to disable loading / writing any file on the server.

**Comment by Alex-Monahan** [comment]
Can this feature be used through the Python API? We have the same security issue.

Thanks!

**Comment by hannesmuehleisen** [comment]
@Alex-Monahan not yet, but we can expose it.

**Comment by Alex-Monahan** [comment]
That would be great! In the meantime we're likely to just sanitize it from our SQL input string. What list of functions should we filter out? Will just removing read_csv cut it, or is the parquet reader impacted?

**Pull request merged**
