### PR TITLE
BenchmarkRunner: Wildcard support for benchmark names

### PR DESCRIPTION
**Pull request by mweisgut**
This PR integrates a small refactoring and the possibility to pass wildcards instead of benchmark names only.
Example: `./build/release/benchmark/benchmark_runner DS.*` would only execute the TPC-DS queries since they start with `DS`.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Looks great, thanks for you contribution! @Mytherin do you need to adapt the website when the TPCH benchmark names change?

**Comment by Mytherin** [comment]
The benchmarks already have groups though, wouldn't it be better to support executing all benchmarks in a group (e.g. all benchmarks in "`[tpch-sf1]`")?

Instead of the "--starts-with" syntax I would also much prefer supporting wildcards in the name, e.g. `benchmark_runner DS%` instead of `benchmark_runner DS --starts-with`. As the benchmark_runner is already linked against DuckDB it should be quite easy to implement that by using the LIKE or REGEX functionality.
> Looks great, thanks for you contribution! @Mytherin do you need to adapt the website when the TPCH benchmark names change?

The website should self-correct but it will look a bit ugly for a while, as it will display both side by side.

**Comment by mweisgut** [comment]
> The benchmarks already have groups though, wouldn't it be better to support executing all benchmarks in a group (e.g. all benchmarks in "`[tpch-sf1]`")?

Good point, isn't addressed in this PR yet.

> Instead of the "--starts-with" syntax I would also much prefer supporting wildcards in the name, e.g. `benchmark_runner DS%` instead of `benchmark_runner DS --starts-with`. As the benchmark_runner is already linked against DuckDB it should be quite easy to implement that by using the LIKE or REGEX functionality.

Addressed in 90818d98ebea87b14ed61871236d6390c4354b46

**Comment by Mytherin** [comment]
Thanks! Could you just revert the names of the TPC-H benchmarks to the original form? I don't think the renames are necessary and they will mess with the website. After that everything looks good and can be merged.

**Comment by Mytherin** [comment]
Thanks! Looks great.

**Pull request merged**
