### PR TITLE
Fuzzer Fixes

### PR DESCRIPTION
**Pull request by Mytherin**
This PR fixes many fuzzer issues found by oss-fuzz, sqlsmith and by @PedroTadim in #4067

Most fixes are relatively straightforward/obvious - below are some highlights:

* Rework the ANALYZE operator to emit a projection with the desired columns, which simplifies the implementation and fixes some issues
* Disable the streaming window when there is a regular window required for other window functions, i.e. avoid mixing streaming and regular windows (@lnkuiper - perhaps you want to have a look at re-enabling this and fixing the underlying issue)
* Clean up foreign key constraint detection and fix several issues there
* Disable perfect hash joins when dealing with complex types in the payload

### CODE REVIEW

**Comment by Mytherin** [comment]
Failures are unrelated, see #4140

**Comment by PedroTadim** [comment]
I am still confused about this query: SELECT count(x) OVER () FROM (SELECT 1) x(x) GROUP BY ALL;

If the ALL clause means grouping from the FROM columns, shouldn't this query be valid? That's because the window function is computed over the grouping.

**Comment by Mytherin** [comment]
`GROUP BY ALL` means "group by all expressions in the `SELECT` clause that do not contain aggregates", e.g.:

```sql
SELECT g, SUM(v) FROM tbl GROUP BY ALL;     -- group by g
SELECT g % 2, SUM(v) FROM tbl GROUP BY ALL; -- group by g % 2
SELECT g, h, SUM(v) FROM tbl GROUP BY ALL;  -- group by g, h
```

In this case, the query is as follows:

```sql
SELECT count(x) OVER () FROM (SELECT 1) x(x) GROUP BY count(x) OVER ();
```

Which is not allowed, since we cannot group by window functions directly.

**Comment by PedroTadim** [comment]
Sure, because window functions are computed after aggregates, I thought it should be allowed

**Comment by Mytherin** [comment]
Precisely because window functions are computed after aggregates you cannot group on them, if you group by x explicitly the above query does work.

**Pull request merged**
