### PR TITLE
[Python] Fix lifetime issue with MaterializedRelation

### LINKED ISSUE #12987: Lifetime issue with view created in experimental Spark API
### What happens?

The context is that I am trying to change my application to be able to use either pyspark or your experimental Spark API. There are many cases where I am using Spark functions that you haven't implemented. In these cases, instead of using the DataFrame API, I am doing the following: (1) create a view (2) send a direct SQL query to that view, (3) delete all temp views eventually.

Querying a view when re-using a variable name fails in v1.0.0. It passes in v0.10.2. If I am doing something wrong, or if there is a better way, please let me know.

A workaround is to:
1. Create a view, as shown
2. Create a table from that view (`CREATE TABLE my_table AS SELECT * from tmp_view`).
3. Use the table going forward.

### To Reproduce

Copy this code into a script, such as `view.py`. 
```
from uuid import uuid4

from duckdb.experimental.spark.sql import DataFrame, SparkSession
import duckdb.experimental.spark.sql.functions as F

def create_tmp_view(df: DataFrame) -> str:
    view = f"tmp_{uuid4().hex}"
    df.createOrReplaceTempView(view)
    return view

def main():
    df = spark.createDataFrame([(2, "Alice"), (2, "Bob"), (2, "Bob"), (5, "Bob")], schema=["age", "name"])
    view = create_tmp_view(df)
    df = spark.sql(f"SELECT * FROM {view} WHERE name = 'Alice'")
    print(df.collect())

if __name__ == "__main__":
    spark = SparkSession.builder.getOrCreate()
    main()
```

Run `python view.py` in the terminal.
```
Traceback (most recent call last):
  File "./view.py", line 19, in <module>
    main()
  File "./view.py", line 15, in main
    print(df.collect())
          ^^^^^^^^^^^^
  File "/Users/dthom/python-envs/duckdb/lib/python3.11/site-packages/duckdb/experimental/spark/sql/dataframe.py", line 981, in collect
    result = self.relation.fetchall()
             ^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Invalid Error: vector
```
If I change the variable name of the result of the query to `df2`, as in
```
    df2 = spark.sql(f"SELECT * FROM {view} WHERE name = 'Alice'")
    print(df2.collect())
```
it works.

The original code works in v0.10.2. It seems to me that the view should not be tied to the variable instance.

### OS:

MacOS aarch64

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Daniel Thom

### Affiliation:

National Renewable Energy Laboratory (NREL)

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #12987 

The ColumnDataCollection (CDC) was stored in the MaterializedRelation, and the produced ColumnDataRef has a reference to this CDC.

We previously blocked creating views from MaterializedRelations (#12163) but this did not take into account nested relations, such as `ProjectionRelation`, which is the case here.
```py
import duckdb

rel = duckdb.sql("select * from (values ($1, $2))", params=[
    (2,),
    ("Alice",)
])

rel = rel.project("col0, col1")

rel.create_view("test", True)
rel = duckdb.sql("select * from test")
rel.show()
```

I've changed the ownership semantics here to fix the issue and removed the previously put in limitation.
The MaterializedRelation no longer owns the CDC, instead it is stored in the ExternalDependency, as a MaterializedDependency.

We recently made it so that TableRefs can have an ExternalDependency.
Because of this, the created VIEW will contain the ColumnDataRef that will keep the CDC alive through its ExternalDependency.

----------------------

This could also be achieved through a regular shared_ptr I think, which might be cleaner than involving the ExternalDependency mechanism into this

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Maybe the `optionally_owned_ptr` can be extended so that it takes an additional template parameter - whether or not the pointer to the owned object is a `unique_ptr` or a `shared_ptr`. Then we could keep the rest of the code in-tact and wouldn't need to use the external dependencies?

**Comment by Tishj** [comment]
> Thanks for the PR!
> 
> Maybe the `optionally_owned_ptr` can be extended so that it takes an additional template parameter - whether or not the pointer to the owned object is a `unique_ptr` or a `shared_ptr`. Then we could keep the rest of the code in-tact and wouldn't need to use the external dependencies?

Perhaps, but I was quite happy to get away from the `optionally_owned_ptr`, it complicates working with the data and was only really necessary because of the serialization, which should never be a reality anyways

**Comment by Mytherin** [comment]
> Perhaps, but I was quite happy to get away from the optionally_owned_ptr, it complicates working with the data and was only really necessary because of the serialization, which should never be a reality anyways

Why would the serialization never occur? This should be able to happen if you create a view in a persistent database with a materialized query relation. Perhaps this is missing from the tests?

**Comment by Mytherin** [comment]
> The problem with the optionally_owned_ptr here is also that we can't be sure that it can just reference, that depends on the lifetime of the Relation, which is not guaranteed when we create a VIEW from it, so always using shared_ptr makes the most sense to me here

I'm also fine with just turning it into a `shared_ptr`, maybe that makes more sense in general indeed

**Comment by Tishj** [comment]
I changed the test from `call range(10)` to `select * from range(?)` `params=[10]`, which should have the exact same properties, just works around <https://github.com/duckdblabs/duckdb-internal/issues/2549>

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
