### PR TITLE
[Python] Use nullable dtypes in Pandas `DataFrame` creation when possible

### LINKED ISSUE #14340: Can not cast field type to Int64 when querying nullable Int64 fields from a Pandas.DataFrame
### What happens?

As indicated in the title and attachment, even when using the cast function, it is impossible to maintain the cc_id in the dataframe returned by duckdb.query as Int64; the cc_id has been converted to a float64 type.
image

### To Reproduce

```
import pandas as pd
import duckdb

df = pd.DataFrame({
    'cc_id': pd.Series([1844743171901218817, 1844691776961568771, None, None], dtype='Int64'),
    'other_column': [10, 20, 30, 40]
})

result = duckdb.query("SELECT CAST(cc_id AS Int64) AS cc_id, other_column FROM df WHERE other_column > 10").df()
result['cc_id']
```

### OS:

macOS 12.7.6

### DuckDB Version:

0.10.2, 1.1.1

### DuckDB Client:

Python

### Hardware:

_No response_

### Full Name:

Kafka Liu

### Affiliation:

Freelancer

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #14340

Pandas by default turns numeric `np.ma.masked_array` columns into `float32` or `float64` when they contain nulls.
We now wrap these in `pd.Series` with one of these explicit nullable dtype variants;

```
pandas.BooleanDtype
pandas.UInt8Dtype
pandas.UInt16Dtype
pandas.UInt32Dtype
pandas.UInt64Dtype
pandas.Int8Dtype
pandas.Int16Dtype
pandas.Int32Dtype
pandas.Int64Dtype
pandas.Float32Dtype
pandas.Float64Dtype
```

### CODE REVIEW

**Comment by Tishj** [comment]
I can't reproduce the test failures, I'm aware that pandas causes a RuntimeWarning here, but I've suppressed those in the test (and made an issue upstream).
I don't know why these are errors and I can't reproduce that on mac or linux (arm 64)

**Comment by Tishj** [comment]
I think the regression is not just spurious this time, extra conversion has to be done but I don't think there's a way around that.

Because we create numpy arrays and these are dtypes that are not supported by numpy, they have to be converted afterwards

**Comment by Tishj** [comment]
@Mytherin do we perhaps want to make this a setting that is opt-in?
To not affect the base cost for conversion from duckdb->pandas ?

**Comment by Mytherin** [comment]
If the performance degradation is unavoidable that sounds like a good idea - but I wonder if we can directly construct the Series to avoid having to go through numpy at all? That way we can maybe avoid the degradation here?

**Comment by Tishj** [comment]
```py
import numpy as np
import numpy.ma
import pandas as pd

# Takes 2 seconds for the script to run
#columns = {
#	'a': [29348234234] * 10_000_000
#}

# Takes 1 second for the script to run
columns = {
	'a': np.ma.masked_array(
			data=[29348234234] * 10_000_000,
			mask=[False] * 10_000_000
		)
}

df = pd.DataFrame.from_dict(columns)
print(df)
```

It looks like we should always be constructing numpy masked arrays, the conversion to pandas appears to be faster with it, even when the mask is redundant

**Comment by Mytherin** [comment]
That's not really a good comparison, given that `'a'` is not a numpy array in the first example, no?

```sql
In [10]: columns = {
           'a': np.array([29348234234] * 10_000_000, dtype=np.int64)
           }
In [12]: %timeit df = pd.DataFrame.from_dict(columns)

3.28 ms ± 160 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [2]:  columns = {
   ...: 'a': np.ma.masked_array(
   ...: data=[29348234234] * 10_000_000,
   ...: mask=[False] * 10_000_000
   ...: )
   ...: }
   ...: 

In [3]: %timeit df = pd.DataFrame.from_dict(columns)

7.01 ms ± 257 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


```

**Comment by Tishj** [comment]
Thanks 👍 

That helped, creating a Series is *very* expensive, even when this is the data:
```py
# SIZE = 100_000_000
data = [29348234234] * SIZE
mask = [True] * SIZE

data = np.ma.masked_array(
	data=data,
	mask=mask
)
```

**Comment by Tishj** [comment]
measuring the time it takes to create `pd.DataFrame.from_dict()` for 100_000_000 tuples

from regular np.array:
`0.09`

from masked np.ma.masked_array (all true)
`0.275`

from masked np.ma.masked_array (all false)
`0.20`

from np.ma.masked_array (all false) wrapped in Series
`0.07`*

* This time is only so short because the time it takes to create this Series is `7.2` seconds

**Comment by Mytherin** [comment]
It seems like Pandas has no optimized code for converting from a masked array to a pd.Series - it likely falls back on regular Python objects. This seems to be much faster:

```py
series = pd.Series(columns.data, dtype=pd.Int64Dtype())
series[columns.mask] = pd.NA
```

**Comment by Tishj** [comment]
That is indeed much faster:
all true:
```
➜  duckdb git:(pandas_dtype_correction) ✗ python3 tmp/int64_test.py
Series 0.33167219161987305
DataFrame 0.11038994789123535
```

all false:
```
➜  duckdb git:(pandas_dtype_correction) ✗ python3 tmp/int64_test.py
Series 0.28539395332336426
DataFrame 0.09841012954711914
```

**Comment by Mytherin** [comment]
The `Series` approach is actually faster for me end-to-end:

```py
import pandas as pd
import numpy as np
import time

SIZE = 100_000_000
data = [29348234234] * SIZE
mask = [False, True] * (SIZE // 2)

columns = np.ma.masked_array(
    data=data,
    mask=mask
)
start = time.time()
series = pd.Series(columns.data, dtype=pd.Int64Dtype())
series[columns.mask] = pd.NA
df = pd.DataFrame.from_dict({'a': series})
end = time.time()

print('Series', end - start)

start = time.time()
df = pd.DataFrame.from_dict({'a': columns})
end = time.time()

print('DataFrame.from_dict', end - start)
```

```
Series 0.30571603775024414
DataFrame.from_dict 0.5037591457366943
```

**Comment by Mytherin** [comment]
Looks like the original regression is gone - but there's still a big regression in `pandas_analyze`. Could you have a look?

**Comment by Tishj** [comment]
I opted to turn this into a setting, I don't think that regression can be solved, pandas conversion logic is too convoluted to make this work, and they don't offer a more granular API.

The keyword argument `prefer_nullable_dtypes` is introduced to `df`, `fetchdf` and friends, defaulting to `False`.

**Comment by Mytherin** [comment]
Playing around with this, it seems that the regression is exclusive to floating point numbers, and integer numbers actually get faster:

```
> Benchmark type  Float32
   - from_dict: 0.10522818565368652 sec
      - Series: 5.216932773590088 sec

> Benchmark type  Float64
   - from_dict: 0.13197684288024902 sec
      - Series: 4.804763317108154 sec

> Benchmark type  UInt8
   - from_dict: 0.15900230407714844 sec
      - Series: 0.043244123458862305 sec

> Benchmark type  UInt16
   - from_dict: 0.15853619575500488 sec
      - Series: 0.0448460578918457 sec

> Benchmark type  UInt32
   - from_dict: 0.16467523574829102 sec
      - Series: 0.06949877738952637 sec

> Benchmark type  UInt64
   - from_dict: 0.16246604919433594 sec
      - Series: 0.08938765525817871 sec

> Benchmark type  Int8
   - from_dict: 0.16232800483703613 sec
      - Series: 0.043081045150756836 sec

> Benchmark type  Int16
   - from_dict: 0.1643669605255127 sec
      - Series: 0.04436302185058594 sec

> Benchmark type  Int32
   - from_dict: 0.16463518142700195 sec
      - Series: 0.07227373123168945 sec

> Benchmark type  Int64
   - from_dict: 0.17934799194335938 sec
      - Series: 0.09908819198608398 sec

```

```py

import numpy
import pandas as pd
import numpy
import time

type_list = [
    (numpy.float32, pd.Float32Dtype()),
    (numpy.float64, pd.Float64Dtype()),
    (numpy.uint8, pd.UInt8Dtype()),
    (numpy.uint16, pd.UInt16Dtype()),
    (numpy.uint32, pd.UInt32Dtype()),
    (numpy.uint64, pd.UInt64Dtype()),
    (numpy.int8, pd.Int8Dtype()),
    (numpy.int16, pd.Int16Dtype()),
    (numpy.int32, pd.Int32Dtype()),
    (numpy.int64, pd.Int64Dtype())
]

nruns = 10

for types in type_list:
    numpy_type = types[0]
    pandas_type = types[1]
    print('> Benchmark type ', pandas_type)

    arr = numpy.ma.masked_array([1] * 10000000, mask = [True] * 9999999 + [False], dtype=numpy_type)
    start = time.time()
    for i in range(nruns):
        pd.DataFrame.from_dict({'arr': arr})

    end = time.time()
    print('   - from_dict:', end - start, 'sec')

    start = time.time()
    for i in range(nruns):
        series = pd.Series(arr.data, dtype=pandas_type)
        series[arr.mask] = pd.NA
        pd.DataFrame.from_dict({'arr': series})
    end = time.time()

    print('      - Series:', end - start, 'sec')
    print('')

```

Given that the original issue is about integer values - and floating point numbers have a "nice" way of representing NULL values anyway in `NaN`, maybe we can instead apply this PR to only integer numbers? That way we don't need to add the option either.

**Comment by Tishj** [comment]
I think we want the option internally anyways for `fetchnumpy`, I can change it to default to `True` for `fetchdf`, but I think there will be people that don't want this behavior.

I'll remove the treatment for floats and see how the regression test responds

**Comment by Mytherin** [comment]
Looks good from my side - can you just fix the CI failure?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
