### PR TITLE
Add parse_path(), parse_dirname() and parse_filename() functions

### PR DESCRIPTION
**Pull request by chrisiou**
This PR introduces the following functions, as discussed [here](https://github.com/duckdb/duckdb/discussions/9530) and through this PR's review:

```
# Returns a list of the components (directories and filename) in the path similarly to Python's pathlib.PurePath::parts
VARCHAR[] parse_path(VARCHAR path [, VARCHAR separator])

# Returns the last component of the path similarly to Python's os.path.basename.
VARCHAR parse_filename(VARCHAR path [, BOOLEAN trim_extension] [, VARCHAR separator])

# Returns the top-level directory name
VARCHAR parse_dirname(VARCHAR path [, VARCHAR separator])

# Returns the head of the path (the pathname until the last slash) similarly to Python's os.path.dirname
VARCHAR parse_dirpath(VARCHAR path [, VARCHAR separator])
```
Optional arguments:
`trim_extension` defaults to `false`. If it is `true`, the file extension is removed.
`separator` options: `system`, `both_slash` (default), `forward_slash`, `backslash`

more details to Python's functions: [pathlib.PurePath::parts](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parts), [os.path.basename](https://docs.python.org/3.7/library/os.path.html#os.path.basename), [os.path.dirname](https://docs.python.org/3.7/library/os.path.html#os.path.dirname)

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good - could you have a look at the CI failures? They might be related to some recent changes on main so you might need to merge with main locally.

**Review by samansmink — COMMENTED** [review]
Hey @chrisiou thanks for the PR, the code LGTM! I agree with @szarnyasg that it makes sense to double check if that behaviour makes sense, maybe you could check how other libraries handle that case?

**Comment by chrisiou** [comment]
> Hey @chrisiou thanks for the PR, the code LGTM! I agree with @szarnyasg that it makes sense to double check if that behaviour makes sense, maybe you could check how other libraries handle that case?

So, based on POSIX standards (looking on the definitions of [path - pathname components](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_271), [filename](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_170) and [root directory](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_330)), I think we should avoid empty entries for paths starting with a separator or containing consecutive separators, cause
- beginning slash characters are considered optional for a path (only the root directory should begin with one)
- consecutive slashes should be treated as one, following the [path - pathname components](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_271)

Now, for other libraries and languages, the closest functionality I found to the functions we need
1.  (Python) [os.path.split](https://docs.python.org/3.7/library/os.path.html#os.path.split): `os.path.split('/path/to/file.csv')` returns `('/path/to', 'file.csv')`
2. (Python) [pathlib.PurePath::parts](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parts) which returns a list of  the components (not exactly what we want though):  `pathlib.PurePath('/usr/bin/python3').parts` returns `(‘/‘, 'usr', 'bin', 'python3’)` 
BUT: `pathlib.PurePath('usr/bin/python3’).parts` returns `(‘usr', 'bin', 'python3’)`
3. (Java) [java.nio.file.Path::get()](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.net.URI-) and (Azure) [parse_path()](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-path-function) create an object representing the entire path, which for the directory name they remove the separator character and the root path.

**Comment by samansmink** [comment]
@chrisou I would say the pathlib.PurePath behaviour looks pretty clean, what do you think? We could in some point look into supporting more of what the python pathlib implements, but I think keeping it simple is better for now

**Comment by chrisiou** [comment]
> @chrisou I would say the pathlib.PurePath behaviour looks pretty clean, what do you think? We could in some point look into supporting more of what the python pathlib implements, but I think keeping it simple is better for now

Great! I'll follow this direction. 
Should the `parse_dirname('/path/to/file.csv')` return `/` as well?

Python has [os.path.dirname](https://docs.python.org/3.7/library/os.path.html#os.path.dirname), which 
`os.path.dirname('/path/to/file.csv')` returns `'/path/to'` (not our case).

**Comment by samansmink** [comment]
> Should the parse_dirname('/path/to/file.csv') return / as well?

I would vote yes here


> `os.path.dirname('/path/to/file.csv')` returns `'/path/to'` (not our case).

Maybe that is indeed a more sensible behaviour, what do you think?

**Comment by samansmink** [comment]
```
parse_dirname() -> a VARCHAR with the top-level directory
parse_dirpath() -> a VARCHAR with the whole path until a filename with extension(?)
```
I think this sounds great

With regards to following azure's parse_path behaviour, I would keep things simple for this PR. I don't think we need to offer extensive support for handling the different types of (windows) paths that azure needs to.

**Review by samansmink — APPROVED** [review]
Thanks for the changes @chrisiou I think this is good to go!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
