### PR TITLE
Rework generated EnumUtil code

### PR DESCRIPTION
**Pull request by Mytherin**
This PR reworks the generated `EnumUtil` code to have a smaller code and binary footprint, and to allow better error messages to be emitted when no matching values are found.

Previously we would generate the matching logic for each enum. This change moves the actual matching logic into a generic method in the `StringUtil` class (`StringUtil::EnumToString` and `StringUtil::StringToEnum`). The generated code only includes a list of mappings between enums and strings and a call to these methods.

###### New
```cpp
struct EnumStringLiteral {
	uint32_t number;
	const char *string;
};

const StringUtil::EnumStringLiteral *GetCTEMaterializeValues() {
	static constexpr StringUtil::EnumStringLiteral values[] {
		{ static_cast<uint32_t>(CTEMaterialize::CTE_MATERIALIZE_DEFAULT), "CTE_MATERIALIZE_DEFAULT" },
		{ static_cast<uint32_t>(CTEMaterialize::CTE_MATERIALIZE_ALWAYS), "CTE_MATERIALIZE_ALWAYS" },
		{ static_cast<uint32_t>(CTEMaterialize::CTE_MATERIALIZE_NEVER), "CTE_MATERIALIZE_NEVER" }
	};
	return values;
}

template<>
const char* EnumUtil::ToChars<CTEMaterialize>(CTEMaterialize value) {
	return StringUtil::EnumToString(GetCTEMaterializeValues(), 3, "CTEMaterialize", static_cast<uint32_t>(value));
}

template<>
CTEMaterialize EnumUtil::FromString<CTEMaterialize>(const char *value) {
	return static_cast<CTEMaterialize>(StringUtil::StringToEnum(GetCTEMaterializeValues(), 3, "CTEMaterialize", value));
}
```

###### Old
```cpp

template<>
const char* EnumUtil::ToChars<CTEMaterialize>(CTEMaterialize value) {
	switch(value) {
	case CTEMaterialize::CTE_MATERIALIZE_DEFAULT:
		return "CTE_MATERIALIZE_DEFAULT";
	case CTEMaterialize::CTE_MATERIALIZE_ALWAYS:
		return "CTE_MATERIALIZE_ALWAYS";
	case CTEMaterialize::CTE_MATERIALIZE_NEVER:
		return "CTE_MATERIALIZE_NEVER";
	default:
		throw NotImplementedException(StringUtil::Format("Enum value: '%d' not implemented in ToChars<CTEMaterialize>", value));
	}
}

template<>
CTEMaterialize EnumUtil::FromString<CTEMaterialize>(const char *value) {
	if (StringUtil::Equals(value, "CTE_MATERIALIZE_DEFAULT")) {
		return CTEMaterialize::CTE_MATERIALIZE_DEFAULT;
	}
	if (StringUtil::Equals(value, "CTE_MATERIALIZE_ALWAYS")) {
		return CTEMaterialize::CTE_MATERIALIZE_ALWAYS;
	}
	if (StringUtil::Equals(value, "CTE_MATERIALIZE_NEVER")) {
		return CTEMaterialize::CTE_MATERIALIZE_NEVER;
	}
	throw NotImplementedException(StringUtil::Format("Enum value: '%s' not implemented in FromString<CTEMaterialize>", value));
}

```

### CODE REVIEW

**Comment by Mytherin** [comment]
@carlopi one thing I'm worried about here is that the static arrays are not stripped by the compiler. I've wrapped them in methods (i.e. `GetCTEMaterializeValues()`, etc), but perhaps it would be worth verifying this does not accidentally increase the size of the WASM build.

**Comment by Maxxen** [comment]
I like it! I guess the only question is do we always want to check `CIEquals` in `FromString`? I don't think we have any case-sensitive enums but maybe that's something the generation script can verify.

**Comment by Mytherin** [comment]
> I like it! I guess the only question is do we always want to check `CIEquals` in `FromString`? I don't think we have any case-sensitive enums but maybe that's something the generation script can verify.

Enums should be only upper-case, so I would think there are no conflicts.

**Comment by carlopi** [comment]
Orthogonal, but why 'Regression' has not been triggered here?

I think this might need a `__attribute__((noinline))` or something, I need to check, since a smart enough compiler might (and I would expect will) inline the calls of the generic EnumToString back into the various templated `EnumUtil::ToChars<>`.

This is still not a blocker, can always looked at independently.

**Review by carlopi — APPROVED** [review]
Thanks!!

**Pull request merged**
