### PR TITLE
Move excel extension out of tree

### PR DESCRIPTION
**Pull request by carlopi**
Copy of excel folder (with snapshot of history) is at [duckdb/duckdb_excel](https://github.com/duckdb/duckdb_excel/). Needs a REAME / some polishing, but it should be already functional for what regards duckdb's CI.

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by carlopi** [comment]
There is a CI failure that needs looking at, `LinuxRelease / Checks extension entries (pull_request)`

**Comment by carlopi** [comment]
Fixed minor merge conflict (extension updated touched the same file), git is unsure on what to do on modifying a deleted file, bumped to current duckdb_excel main.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
