### PR TITLE
[Dev] Clean up TreeRenderer code

### PR DESCRIPTION
**Pull request by Tishj**
This PR is doing some yak-shaving in preparation of introducing JSON as a formatting option to the EXPLAIN statement.

I have separated RenderTree from the TreeRenderer, and have moved all tree-creation related methods to the RenderTree class.
I've also removed raw pointers in favor of `optional_ptr`, `unique_ptr<....>[]` in favor of `unique_array` and replaced a `vector<pair<idx_t, idx_t>>` with a struct in place of the `pair`.

## Future work

- Introduce the TreeRenderer interface
- Rename the existing TreeRenderer into TextTreeRenderer
- Add `JSONTreeRenderer` as a new implementation of the Interface
- Add support for `EXPLAIN (FORMAT JSON)`, using the new JSONTreeRenderer

### CODE REVIEW

**Comment by kryonix** [comment]
Hi @Tishj, do you have any plans to make, e.g., `maximum_render_width` and `node_render_width` configurable?

**Comment by Tishj** [comment]
@kryonix as said I am just moving stuff around preparing to add a JSONTreeRenderer, I haven't thought about the config for the TreeRenderer at all.

That being said, it is already a separate struct, they're not defines, so I think it shouldn't be too difficult to make these configurable through the client config settings

**Comment by kryonix** [comment]
Got it! Just wanted to throw that in as an idea. We have to change these values sometimes and recompile the system to see the full plan. The JSON format will certainly be helpful with that, and maybe some one will build something like pev2 for DuckDB? That would be awesome. Anyways, if you happen to find some time slices to add the configurability, great, otherwise we might give it a go after you've finished migrating to the new code structure.

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by Mytherin** [comment]
Could you have another look at the CI failure?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
