### PR TITLE
Change www.duckdb.org to duckdb.org

### PR DESCRIPTION
**Pull request by annainfo**

### CODE REVIEW

**Comment by Mytherin** [comment]
Could you perhaps provide some motivation behind making this change?

**Comment by Mause** [comment]
> > Could you perhaps provide some motivation behind making this change?
> 
> Yes.

What is the motivation?

**Comment by annainfo** [comment]
1) Reduce inconsistency
2) Save energy

**Comment by annainfo** [comment]
Why was this closed?

**Pull request closed without merging**
