### PR TITLE
DATE type handling for Python

### PR DESCRIPTION
**Pull request by lepennec**
DATE is converted as datetime.date for fetchall and numpy.datetime64 with second as units for fetchnumpy and fetchdf.
Do you agree with this choice?

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Looks great, could you please add a test case as well?

**Comment by lepennec** [comment]
That was my next task...

**Comment by hannesmuehleisen** [comment]
Great, thanks for the test, but at this moment this only checks that the result is of the correct type, not that it actually has the correct value. Would you mind adding that as well please?

**Comment by lepennec** [comment]
Sure!

**Comment by hannesmuehleisen** [comment]
Thank you!

**Pull request merged**
