### PR TITLE
fix: pin cython to work around bug

### PR DESCRIPTION
**Pull request by Mause**
This should hopefully fix the build

See https://github.com/scipy/scipy/issues/16718

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
LGTM

**Comment by Mause** [comment]
Okay, that should fix it for real. More painful than I was expecting

**Comment by Mause** [comment]
There are also a couple of `test_ibis_tpch` tests failing in the linux builds - these were failing prior to the Cython issue, and I'd prefer to fix those separately

**Comment by Mytherin** [comment]
Thanks for the fixes! Agreed that should be fixed separately.

**Pull request merged**
