### PR TITLE
Simplify detection of BLOBs

### PR DESCRIPTION
**Pull request by krlmlr**
Needed when duckdb supports BLOBs.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
I vaguely remember this check was as complex as it is for some corner cases. But its been a while. There are other cases where a column is a list, no?

**Comment by krlmlr** [comment]
List columns are always BLOB columns for now. Does DuckDB support BLOBs by now?

**Comment by hannesmuehleisen** [comment]
yes, it does

**Comment by hannesmuehleisen** [comment]
I'm still confused by this one. `dbWriteTable` can make any `data.frame`, and just because a column is a list does not mean it contains `raw` values? For example:

````R
df <- data.frame(a=seq.int(10))
df$b <- lapply(df$a, function(x) data.frame(c=x, d=x))
is.list(df$b)
# TRUE
````

Am I missing something?

**Comment by krlmlr** [comment]
For DBI, if it's a list, it must contains raw values at this time. If we were ever to extend this, we would require a class for other types.

I would suggest to check types when actually touching the data, in the C++ code.

**Comment by hannesmuehleisen** [comment]
Closing this here for now. Feel free to open a new PR whenever ready,

**Pull request closed without merging**
