### PR TITLE
Adding number of vectors in returned chunk from fetch_df_chunk

### PR DESCRIPTION
**Pull request by pdet**
This PR expands the python fetch_df_chunk function to accept a vectors_per_chunk parameter.

This function now returns vectors_per_chunk*STANDARD_VECTOR_SIZE per call.

By default that value is 1.

### CODE REVIEW

**Comment by pdet** [comment]
cc @Alex-Monahan 

Let me know if this suits your needs :-)

**Comment by Alex-Monahan** [comment]
Thank you! I will test it out shortly

**Comment by Alex-Monahan** [comment]
Looks like I need to wait for the Python wheels to get generated, so I'll have to wait for it to reach master I believe. Or is there another way for me to consume a pre-compiled wheel based on this PR?

**Comment by pdet** [comment]
Not that Im aware of.
@Mytherin can you review this PR?

**Comment by Mytherin** [comment]
Looks good to me. Thanks!

**Comment by Alex-Monahan** [comment]
It looks like this is throwing an error on the final chunk like it used to before your prior fix. Here is a Jupyter notebook that fails. I would expect it to return empty rather than fail even though I am asking for 1 chunk too many (otherwise I don't know how to see when all chunks have been pulled).
[DuckDB fetch_df_chunk performance timing-vectorMultiple.zip](https://github.com/duckdb/duckdb/files/6787765/DuckDB.fetch_df_chunk.performance.timing-vectorMultiple.zip)
image

**Pull request merged**
