### PR TITLE
Bug/substr

### PR DESCRIPTION
**Pull request by dioptre**
## FIXED
select substring('ABCDEF', 0, 1);
select substring('ABCDEF', 0, 2);

## WORKS
select substring('ABCDEF', 4, -2);
select substring('ABCDEF', 1, 2);

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Could you expand on what this fixes exactly, and add some tests for queries that used to be incorrect?

**Comment by dioptre** [comment]
Fixes:

Screenshot 2024-06-28 at 4 00 55 AM

**Comment by dioptre** [comment]
Should be:
Screenshot 2024-06-28 at 4 02 54 AM

**Comment by Mytherin** [comment]
DuckDB produces the same results as Postgres on these queries, so the original results seem correct to me:

```sql
postgres=# select substring('ABCDEF', 0, 2);
 substring 
-----------
 A
(1 row)

postgres=# select substring('ABCDEF', 0, 1);
 substring 
-----------
 
(1 row)

postgres=# select substring('ABCDEF', 2, 1);
 substring 
-----------
 B
(1 row)

postgres=# select substring('ABCDEF', 2, 2);
 substring 
-----------
 BC
(1 row)
```

DuckDB uses 1-based indexing (as mandated by the SQL standard and used by all other SQL systems). Perhaps that is what is causing the confusion here?

**Comment by dioptre** [comment]
Ah my bad, wondered how 0,2 only gave 1 character and thought it must be off.

1 indexing!

**Pull request closed without merging**
