### PR TITLE
Add SUM(BOOL) overload

### PR DESCRIPTION
**Pull request by Mytherin**
This is a useful overload that allows the user to quickly count the amount of matches for a boolean condition, it is essentially syntactic sugar for:

```sql
SELECT SUM(CASE WHEN [cond] THEN 1 END) FROM tbl
```

As an added bonus, it is also slightly faster than the above expression:

```sql
SELECT SUM(l_extendedprice > 500) FROM lineitem;
-- 0.020s
SELECT SUM(CASE WHEN l_extendedprice > 500 THEN 1 END) FROM lineitem;
-- 0.028s
```

### CODE REVIEW

**Comment by carlopi** [comment]
I guess this becomes equivalent to:
```
SELECT count(l_extendedprice > 500) FROM lineitem;
```
but nice to provide the overload.

**Comment by Mytherin** [comment]
No, `COUNT` counts the number of non-NULL values, so `count(l_extendedprice > 500)` is equivalent to `count(l_extendedprice)` (which is equivalent to `count(*)` as `lineitem` does not have `NULL` values).

**Comment by carlopi** [comment]
Thanks, again

**Comment by soerenwolfers** [comment]
Isn't 
```sql
SELECT count() FILTER (l_extendedprice > 500) FROM lineitem;
```
the canonical way of doing this? It's also faster than the `CASE WHEN` expression for me, and it has the advantage that there is no chance to footgun oneself into thinking the aggregation happens in the boolean algebra, i.e., modulo 2.

**Comment by Mytherin** [comment]
That's another alternative yeah, but [FILTER is supported in much fewer systems](https://modern-sql.com/feature/filter). It is around as fast as the `CASE` statement for me (i.e. still slightly slower than the `SUM(BOOL)` provided in this PR, but the difference is negligible since they are both fast).

**Comment by soerenwolfers** [comment]
By the way, the macro `count_if` should be rewritten to use this new function (or just be deleted), see https://github.com/duckdb/duckdb-web/issues/3294

**Comment by Mytherin** [comment]
Opened a PR for that here - https://github.com/duckdb/duckdb/pull/15061

**Pull request merged**
