### PR TITLE
Storage info update

### PR DESCRIPTION
**Pull request by szarnyasg**
Add v1.1.2 to storage info. Also regenerated `test/sql/storage_version/storage_version.db`.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - just one question: why do we need to re-generate `test/sql/storage_version/storage_version.db`?

**Comment by szarnyasg** [comment]
The instructions in the test request regenerating and committing the database file: https://github.com/duckdb/duckdb/blob/v1.1.2/test/sql/storage_version/storage_version.test_slow#L5-L8

**Comment by Mytherin** [comment]
That comment is outdated - that was back when we were still breaking the storage version. The comment instructs how to increment the storage version, but now that the storage version isn't being incremented anymore we shouldn't need to re-generate the file anymore either.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
