### PR TITLE
R: Skip Arrow tests on Valgrind

### LINKED ISSUE #4384: Valgrind errors in R tests
### What happens?

The GitHub Actions checks with valgrind fail consistently with "Illegal instruction (core dumped)", e.g. here: https://github.com/duckdb/duckdb/runs/7802323982?check_suite_focus=true#step:11:94.

From looking at the history of runs for the main branch at https://github.com/duckdb/duckdb/actions/workflows/R.yml?query=event%3Apush, it first appeared after merging #4347, though within the PR itself the tests ran without failures. Could be an external change.

I'll try to compare the runs and also issue a few runs in my fork

### To Reproduce

Review any GHA run, https://github.com/duckdb/duckdb/runs/7826259384?check_suite_focus=true at the time of writing.

### OS:

Linux

### DuckDB Version:

33d78e2362c0e786db46cde2c681a7917d89b1a5

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by krlmlr**
via env var.

Closes #4384.

### CODE REVIEW

**Comment by Tishj** [comment]
The name of the variable is kind of confusing in this case, if `DUCKDB_R_VALGRIND` is set, we skip valgrind
Maybe rename it to `DUCKDB_R_SKIP_VALGRIND` ?

**Comment by krlmlr** [comment]
Thanks, renamed to `DUCKDB_R_IN_VALGRIND` .

**Comment by krlmlr** [comment]
I'm still seeing spurious test failures (https://github.com/krlmlr/duckdb/runs/7828488062?check_suite_focus=true#step:13:145), taking measures here to isolate and perhaps skip for now.

**Comment by krlmlr** [comment]
Will be done differently.

**Pull request closed without merging**
