### PR TITLE
Wrapper for creating a virtual table for Parquet-files in the R-client

### PR DESCRIPTION
**Pull request by rsund**
There is an excellent native Parquet support in DuckDB and queries can be run on those files without copying data. Files can be accessed directly by using `parquet_scan()`-function in SQL-queries. This works nicely also in the R-client with the `DBI-backend`.

However, to use the native Parquet reader within `dbplyr-backend`, **files must first be registered as virtual tables** so that a suitable pointer to the database table can be given as a starting point to the backend.

This PR is a wrapper that generates and executes required SQL-statements to create a view for the Parquet-files. By following the steps already seen for the registration of R data frames and Arrow-data in the R-client, it clarifies the idea of having one engine that works directly with several different data formats without copying the data around and simplifies the process required to access Parquet-files with a native reader in the `dbplyr-backend`.

### CODE REVIEW

**Comment by hannes** [comment]
Thanks, but there is a better way to do this, with so-called replacement scans.

**Comment by rsund** [comment]
OK, this was just an extraction from my personal helper library as I have had a pragmatic need for this kind of functionality. And really cool if there is a better way to do this! Is it something I could try to contribute (e.g. that the machinery to do replacement scans in Parquet files lives already in the code and only a suitable wrapper is missing)?

**Comment by hannes** [comment]
Its already in the python client, I can dig up the exact lines if it helps

**Comment by hannes** [comment]
pyconnection.cpp

**Comment by rsund** [comment]
OK, thanks, found the Python client implementation and conversion to R client seemed to be relatively straightforward.

The `duckdb_unregister_parquet()` -function I kept as it was, because the Python implementation seemed also to be just an execution of `DROP`-statement.

In the query-version I had a boolean argument for replace defaulting to `FALSE`, but that argument is now removed and the view is always replaced.

One thing I could not get working similarly was the use of lists, i.e. `parquet_scan(['file1.parquet', 'file2.parquet'])`, but most likely that's not a big deal as wildcards should still work as expected.

**Comment by rsund** [comment]
I got replace and temporary arguments working and also added more tests.

**Comment by rsund** [comment]
Now the lists of paths to Parquet files can also be given.

Took a while to figure out how to convert R vector of strings to a list that worked with cpp11-headers and then convert those to a C++11 strings in a Value-vector that could be then inserted into a DuckDB LIST that was put to a Value-vector that was needed for the TableFunction.

More tests were also added.

Anything else, @hannes?

**Comment by rsund** [comment]
To keep the references up to date, this PR implements the idea #3189

**Comment by rsund** [comment]
I took another look into this and (hopefully) finally got what is meant by replacement scans 😳. I got mixed as the only reference for `parquet_scan()` in the pyconnection.cpp was in the creation of relation that was very close to creating a view (and potentially registering a view that way could be more efficient than using `CREATE VIEW x AS SELECT * FROM parquet_scan("file.parquet")`. In any case, the current implementation is not a replacement scan but (still) a registering of a view from Parquet-files even though that is now done at the C++ level.

So based on #1487 and #1534 there is automatic replacement scan for parquet and csv-files that takes place in all environments and in addition some client specific replacement scans in the Python client as well as Arrow replacement scan in the R client (#2408).

In relation to this PR, the idea was to register Parquet files as a (permanent) view in the DuckDB catalog for easier access to the files without writing the paths after registering. In my opinion, there are use cases in which this kind of option is beneficial and similar feature request was also presented in #3189.

In any case, there should not be a need for separate replacement scan for parquet-files in the R client (as it is already available in all environments), but that doesn't solve the issue that the files need to be referenced with paths. With relational API it seems to be possible to give an alias in the Python client, but I'm not sure how persistent that alias is (permanent, relation specific, or living until the connection is closed) and so far relational API for the R client is still under construction (#3047). So also from this perspective, this PR may have some value.

On the other hand, one common use case in the R client is to use `dplyr::tbl()` to "register" the table and then proceed with the processing with the dplyr-verbs (through the dbplyr backend). Especially without using permanent views this may lead to "double registering" even with this PR (first to register the view for parquet and then register to dplyr), but without this PR the view creation statements should be separately prepared and executed (that may feel to be a bit clumsy) to achieve the same functioning.

In fact, it should be possible to give the path to parquet file in `dplyr::tbl()` with the available general replacement scan. Unfortunately, that is not working, because `tbl()` seems to put quotation marks around the table name that prevents the general replacement scan to detect parquet file from the file extension. Actually it would be possible to use directly `parquet_scan()` there without the quotation mark problem that would then allow to use the list of paths/globs.

There are some possible pathways to fix that:
1. Filing a bug report to dplyr or dbplyr (or wherever the actual problems lies as that may not be obvious because of the complex evaluation of S3 and S4 methods), but that is unlikely to work or at least takes ages to get into action.
2. Another possibility is to tailor own S3 method for duckdb_connection for some of the generics used in the evaluation path (need to take a closer look what would be the best option) and that certainly should be doable relatively easily.
3. Third option would be to generalize the general parquet replacement scan a bit so that it can deal with quotation marks and even more preferable so that also `parquet_scan()` in quotes would be interpreted as actual function call if no table with that name cannot be found from the catalog.

I may send another issue/PR for that, but I would appreciate your opinion on the most suitable approach (option 2 or 3 or something else), @hannes and @Mytherin.

It would also be great to hear your judgement about this current PR. Do you see some value in this? If yes, I'll make the corrections required for the tests because of #3238 and maybe add a parameter to enable caching of parquet metadata. If you see no value, this PR can be closed.

I may also, if I happen to have time, take a look how easily it would be possible to implement actual replacement scans in the R client for the R data frames. Maybe the most challenging thing is to efficiently find the objects suitable for replacement scan within the R session, but let's see.

**Comment by rsund** [comment]
I close this PR in favor of #3264 that provides the required functionality in much simpler form.

**Pull request closed without merging**
