### PR TITLE
Add ClickBench to benchmark suite

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds a reduced version of ClickBench to the benchmark suite so this benchmark is easier for us to run. As the original data set size is quite large, the benchmark is reduced to 1/10th of the size (10M rows instead of 100M rows). This is around 800MB in Parquet format compressed with ZSTD.

We also make a few improvements to the benchmark suite, such as storing caches in Parquet format instead of CSV format and using DuckDB's CSV reader to read answer results.

Note that while we have run the benchmark in Postgres and used that to obtain reference results, a number of queries are underspecified. This is generally the case with `Top-N` queries with many ties, queries lacking an `ORDER BY` clause entirely, etc. We have opted not to change the queries, and instead ignore the result checking for those queries (they are marked as `clickbench-noresult.benchmark.in`).

### Regexp Replace
While running the benchmark a performance problem with `regexp_replace` was encountered - namely, it was not caching the regex in case a constant regex was used (which is almost always). This lead to poor performance on Q28. This PR fixes the issue and ensures we do not recompile the regex once per value unless required.

### Current Results (running on my laptop)

The main remaining performance optimization that needs to happen here is the parallelization of `COUNT(DISTINCT)` in the grouped scenario. The fact that we do not yet properly parallelize this causes performance hits for Q8, Q9, Q13. Aside from that, an improved/vectorized Top-N implementation would improve a good number of these queries.

| Query | Time (s) |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-------|----------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Q0    | 0.001s   | `SELECT COUNT(*) FROM hits;`                                                                                                                                                                                                                                                                                                                  |
| Q1    | 0.002s   | `SELECT COUNT(*) FROM hits WHERE AdvEngineID <> 0;`                                                                                                                                                                                                                                                                                           |
| Q2    | 0.001s   | `SELECT SUM(AdvEngineID), COUNT(*), AVG(ResolutionWidth) FROM hits;`                                                                                                                                                                                                                                                                          |
| Q3    | 0.002s   | `SELECT AVG(UserID) FROM hits;`                                                                                                                                                                                                                                                                                                               |
| Q4    | 0.049s   | `SELECT COUNT(DISTINCT UserID) FROM hits;`                                                                                                                                                                                                                                                                                                    |
| Q5    | 0.056s   | `SELECT COUNT(DISTINCT SearchPhrase) FROM hits;`                                                                                                                                                                                                                                                                                              |
| Q6    | 0.002s   | `SELECT MIN(EventDate), MAX(EventDate) FROM hits;`                                                                                                                                                                                                                                                                                            |
| Q7    | 0.002s   | `SELECT AdvEngineID, COUNT(*) FROM hits WHERE AdvEngineID <> 0 GROUP BY AdvEngineID ORDER BY COUNT(*) DESC;`                                                                                                                                                                                                                                  |
| Q8    | 0.515s   | `SELECT RegionID, COUNT(DISTINCT UserID) AS u FROM hits GROUP BY RegionID ORDER BY u DESC LIMIT 10;`                                                                                                                                                                                                                                          |
| Q9    | 0.357s   | `SELECT RegionID, SUM(AdvEngineID), COUNT(*) AS c, AVG(ResolutionWidth), COUNT(DISTINCT UserID) FROM hits GROUP BY RegionID ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                        |
| Q10   | 0.04s    | `SELECT MobilePhoneModel, COUNT(DISTINCT UserID) AS u FROM hits WHERE MobilePhoneModel <> '' GROUP BY MobilePhoneModel ORDER BY u DESC LIMIT 10;`                                                                                                                                                                                             |
| Q11   | 0.044s   | `SELECT MobilePhone, MobilePhoneModel, COUNT(DISTINCT UserID) AS u FROM hits WHERE MobilePhoneModel <> '' GROUP BY MobilePhone, MobilePhoneModel ORDER BY u DESC LIMIT 10;`                                                                                                                                                                   |
| Q12   | 0.06s    | `SELECT SearchPhrase, COUNT(*) AS c FROM hits WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                                                       |
| Q13   | 0.315s   | `SELECT SearchPhrase, COUNT(DISTINCT UserID) AS u FROM hits WHERE SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY u DESC LIMIT 10;`                                                                                                                                                                                                         |
| Q14   | 0.066s   | `SELECT SearchEngineID, SearchPhrase, COUNT(*) AS c FROM hits WHERE SearchPhrase <> '' GROUP BY SearchEngineID, SearchPhrase ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                       |
| Q15   | 0.061s   | `SELECT UserID, COUNT(*) FROM hits GROUP BY UserID ORDER BY COUNT(*) DESC LIMIT 10;`                                                                                                                                                                                                                                                          |
| Q16   | 0.121s   | `SELECT UserID, SearchPhrase, COUNT(*) FROM hits GROUP BY UserID, SearchPhrase ORDER BY COUNT(*) DESC LIMIT 10;`                                                                                                                                                                                                                              |
| Q17   | 0.105s   | `SELECT UserID, SearchPhrase, COUNT(*) FROM hits GROUP BY UserID, SearchPhrase LIMIT 10;`                                                                                                                                                                                                                                                     |
| Q18   | 0.196s   | `SELECT UserID, extract(minute FROM EventTime) AS m, SearchPhrase, COUNT(*) FROM hits GROUP BY UserID, m, SearchPhrase ORDER BY COUNT(*) DESC LIMIT 10;`                                                                                                                                                                                      |
| Q19   | 0.001s   | `SELECT UserID FROM hits WHERE UserID = 435090932899640449;`                                                                                                                                                                                                                                                                                  |
| Q20   | 0.051s   | `SELECT COUNT(*) FROM hits WHERE URL LIKE '%google%';`                                                                                                                                                                                                                                                                                        |
| Q21   | 0.02s    | `SELECT SearchPhrase, MIN(URL), COUNT(*) AS c FROM hits WHERE URL LIKE '%google%' AND SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                     |
| Q22   | 0.026s   | `SELECT SearchPhrase, MIN(URL), MIN(Title), COUNT(*) AS c, COUNT(DISTINCT UserID) FROM hits WHERE Title LIKE '%Google%' AND URL NOT LIKE '%.google.%' AND SearchPhrase <> '' GROUP BY SearchPhrase ORDER BY c DESC LIMIT 10;`                                                                                                                 |
| Q23   | 0.18s    | `SELECT * FROM hits WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10;`                                                                                                                                                                                                                                                                   |
| Q24   | 0.011s   | `SELECT SearchPhrase FROM hits WHERE SearchPhrase <> '' ORDER BY EventTime LIMIT 10;`                                                                                                                                                                                                                                                         |
| Q25   | 0.015s   | `SELECT SearchPhrase FROM hits WHERE SearchPhrase <> '' ORDER BY SearchPhrase LIMIT 10;`                                                                                                                                                                                                                                                      |
| Q26   | 0.015s   | `SELECT SearchPhrase FROM hits WHERE SearchPhrase <> '' ORDER BY EventTime, SearchPhrase LIMIT 10;`                                                                                                                                                                                                                                           |
| Q27   | 0.209s   | `SELECT CounterID, AVG(length(URL)) AS l, COUNT(*) AS c FROM hits WHERE URL <> '' GROUP BY CounterID HAVING COUNT(*) > 100000 ORDER BY l DESC LIMIT 25;`                                                                                                                                                                                      |
| Q28   | 1.638s   | `SELECT REGEXP_REPLACE(Referer, '^https?://(?:www\.)?([^/]+)/.*$', '\1') AS k, AVG(length(Referer)) AS l, COUNT(*) AS c, MIN(Referer) FROM hits WHERE Referer <> '' GROUP BY k HAVING COUNT(*) > 100000 ORDER BY l DESC LIMIT 25;`                                                                                                            |
| Q29   | 0.06s    | `SELECT SUM(ResolutionWidth), SUM(ResolutionWidth + 1), SUM(ResolutionWidth + 2), SUM(ResolutionWidth + 3), SUM(ResolutionWidth + 4), SUM(ResolutionWidth + 5), SUM(ResolutionWidth + 6), SUM(ResolutionWidth + 7), SUM(ResolutionWidth + 8), SUM(ResolutionWidth + 9), SUM(ResolutionWidth + 10), SUM(ResolutionWidth + 11), SUM(ResolutionW` |
| Q30   | 0.051s   | `SELECT SearchEngineID, ClientIP, COUNT(*) AS c, SUM(IsRefresh), AVG(ResolutionWidth) FROM hits WHERE SearchPhrase <> '' GROUP BY SearchEngineID, ClientIP ORDER BY c DESC LIMIT 10;`                                                                                                                                                         |
| Q31   | 0.114s   | `SELECT WatchID, ClientIP, COUNT(*) AS c, SUM(IsRefresh), AVG(ResolutionWidth) FROM hits WHERE SearchPhrase <> '' GROUP BY WatchID, ClientIP ORDER BY c DESC LIMIT 10;`                                                                                                                                                                       |
| Q32   | 0.625s   | `SELECT WatchID, ClientIP, COUNT(*) AS c, SUM(IsRefresh), AVG(ResolutionWidth) FROM hits GROUP BY WatchID, ClientIP ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                                |
| Q33   | 0.187s   | `SELECT URL, COUNT(*) AS c FROM hits GROUP BY URL ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                                                                                                  |
| Q34   | 0.2s     | `SELECT 1, URL, COUNT(*) AS c FROM hits GROUP BY 1, URL ORDER BY c DESC LIMIT 10;`                                                                                                                                                                                                                                                            |
| Q35   | 0.069s   | `SELECT ClientIP, ClientIP - 1, ClientIP - 2, ClientIP - 3, COUNT(*) AS c FROM hits GROUP BY ClientIP, ClientIP - 1, ClientIP - 2, ClientIP - 3 ORDER BY c DESC LIMIT 10;`                                                                                                                                                                    |
| Q36   | 0.029s   | `SELECT URL, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND DontCountHits = 0 AND IsRefresh = 0 AND URL <> '' GROUP BY URL ORDER BY PageViews DESC LIMIT 10;`                                                                                                           |
| Q37   | 0.015s   | `SELECT Title, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND DontCountHits = 0 AND IsRefresh = 0 AND Title <> '' GROUP BY Title ORDER BY PageViews DESC LIMIT 10;`                                                                                                     |
| Q38   | 0.008s   | `SELECT URL, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND IsRefresh = 0 AND IsLink <> 0 AND IsDownload = 0 GROUP BY URL ORDER BY PageViews DESC LIMIT 10 OFFSET 1000;`                                                                                                |
| Q39   | 0.05s    | `SELECT TraficSourceID, SearchEngineID, AdvEngineID, CASE WHEN (SearchEngineID = 0 AND AdvEngineID = 0) THEN Referer ELSE '' END AS Src, URL AS Dst, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND IsRefresh = 0 GROUP BY TraficSourceID, SearchEngineID, AdvEngineID,` |
| Q40   | 0.006s   | `SELECT URLHash, EventDate, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND IsRefresh = 0 AND TraficSourceID IN (-1, 6) AND RefererHash = 3594120000172545465 GROUP BY URLHash, EventDate ORDER BY PageViews DESC LIMIT 10 OFFSET 100;`                                  |
| Q41   | 0.006s   | `SELECT WindowClientWidth, WindowClientHeight, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-01' AND EventDate <= '2013-07-31' AND IsRefresh = 0 AND DontCountHits = 0 AND URLHash = 2868770270353813622 GROUP BY WindowClientWidth, WindowClientHeight ORDER BY PageViews DESC LIMIT 10 OFFSET 10000;`      |
| Q42   | 0.005s   | `SELECT DATE_TRUNC('minute', EventTime) AS M, COUNT(*) AS PageViews FROM hits WHERE CounterID = 62 AND EventDate >= '2013-07-14' AND EventDate <= '2013-07-15' AND IsRefresh = 0 AND DontCountHits = 0 GROUP BY DATE_TRUNC('minute', EventTime) ORDER BY DATE_TRUNC('minute', EventTime) LIMIT 10 OFFSET 1000;`                               |

### CODE REVIEW

**Comment by WoolenWang** [comment]
is that Q16~Q18 with origin data size will endup fail to query ?

**Comment by Mytherin** [comment]
What do you mean? None of these queries fail.

**Comment by WoolenWang** [comment]
> 

image

[https://benchmark.clickhouse.com](https://benchmark.clickhouse.com)

make them update the newest version duckdb result so that others like me  can known that chose duckdb is not going to make unacceptable queries fail.

**Comment by Mytherin** [comment]
The PR has been out for a while: ClickHouse/ClickBench#51

**Comment by jychen7** [comment]
> The main remaining performance optimization that needs to happen here is the parallelization of COUNT(DISTINCT) in the grouped scenario. The fact that we do not yet properly parallelize this causes performance hits for Q8, Q9, Q13

for reference, it is later fixed at https://github.com/duckdb/duckdb/pull/5146

> Aside from that, an improved/vectorized Top-N implementation would improve a good number of these queries.

I didn't find Issue/PR related to this, am I miss anything?

**Pull request merged**
