### PR TITLE
Restore serialization of BaseStatistics distinct count

### PR DESCRIPTION
**Pull request by bleskes**
That logic was lost as part of a great refactoring in https://github.com/duckdb/duckdb/pull/6560/

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by bleskes** [comment]
@Mytherin it seems that `test/sql/storage_version/storage_version.test_slow` broke, which kind of makes sense. That said, I don't feel comfortable just blindly generating a new file. Can you confirm my change is relevant? are those stats stored in the storage?

**Comment by bleskes** [comment]
Thanks @Mytherin . I re-generated the file. let's see how this goes.

**Comment by bleskes** [comment]
@Mytherin I can't see how my change relates to a python performance regression. Can I ignore that failure?

**Comment by Mytherin** [comment]
Yes, all looks fine to me

**Pull request merged**
