### PR TITLE
Support REGEX matches expected error message

### PR DESCRIPTION
**Pull request by ZuleykhaPavlichenkova-TomTom**
New variation of CompareValues() to match expected error messages in a format of regex like this:
```
statement error
LOAD 'Makefile';
----
<REGEX>:.*IO Error: Extension.*not found.*

statement error
LOAD NULL;
----
<REGEX>:.*Parser Error: syntax error.* ```

### CODE REVIEW

**Review by taniabogatsch — APPROVED** [review]
Great, thanks!

**Review by Tishj — APPROVED** [review]
Looks good to me 👍

**Review by Tmonster — APPROVED** [review]
LGTM too!

**Comment by Mytherin** [comment]
Thanks! Looks great

**Pull request merged**
