### PR TITLE
Issue #1676: Negative lag

### PR DESCRIPTION
**Pull request by hawkfish**
Clean up boundary checking for lead and lag.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Seems like this PR includes your other PR as well, however. I assume that's by accident?  The window function fix looks good to me.

**Comment by hawkfish** [comment]
Oh dear, that was not intentional. I thought I branched from `master`. Feel free to hold off until the other one is baked!

**Comment by hawkfish** [comment]
Should be simpler now!

**Comment by hawkfish** [comment]
Looks like a build machine issue:

```shell
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
17
```

**Comment by Mytherin** [comment]
Indeed seems unrelated to the PR. I will rerun the tests.

**Comment by Mytherin** [comment]
Looks like that fixed it. Thanks!

**Pull request merged**
