### PR TITLE
Add feature request link

### PR DESCRIPTION
**Pull request by Mause**
This is very much a first attempt and probably needs revising

This also tweaks the config to **forbid** issues not based on one of the two templates, which will hopefully improve the quality of submitted issues

### CODE REVIEW

**Comment by Mause** [comment]
If you'd like to preview what this looks like, you can have a look at my fork: https://github.com/Mause/duckdb/issues/new/choose

**Comment by hannes** [comment]
I am moving those to discussions. Is it possible to have a template here you can't actually open an issue but that just says "open a discussion thing"?

**Comment by Mause** [comment]
> I am moving those to discussions. Is it possible to have a template here you can't actually open an issue but that just says "open a discussion thing"?

image
Like this, which I also added in this pr?

**Comment by Mytherin** [comment]
Opening feature requests as issues is fine as long as we want the issue to be implemented - i.e. you have discussed this with us and we have agreed it is a good idea. That should be clear (and perhaps enforced through a checkbox or similar). We want to avoid people opening issues with "I want DuckDB to have X" - those should be discussions.

**Comment by Mause** [comment]
Could try to enforce it by asking for a link to the discussion as a required field?

**Comment by Mause** [comment]
Hopefully we'll get proper discussion templates soon: https://github.com/community/community/discussions/2838#discussioncomment-4103797

**Comment by Mytherin** [comment]
Looks fine to me - although we might still want to have feature requests with the caveat that they can only be opened either (1) by team members/foundation members/customers, or (2) after discussion with us

**Comment by Mytherin** [comment]
Thanks again for making this - we should give these templates a go as people are still confused.

**Pull request merged**
