### PR TITLE
fixes #6159

### LINKED ISSUE #6159: DuckDBJ: org.duckdb.DuckDBDatabaseMetaData.getTableTypes() should return a list of available table types - not the list of table types that happen to be currently in use.
### What happens?

Method `getTableTypes()` of class `org.duckdb.DuckDBDatabaseMetaData` returns a list of table types that happen to be in use in the current database rather than a list of all available types. 

According to Javadoc of `java.sql.DatabaseMetaData` (https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#getTableTypes()), method `getTableTypes()` should:

"Retrieves the table types available in this database. The results are ordered by table type."

The implementation `org.duckdb.DuckDBDatabaseMetaData.getTableTypes()` (https://github.com/duckdb/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java#L654) returns a unique list of table types from `information_schema.tables`. 

The method should return a static list to indicate what types are available, not what happens to be in use at some moment in time.

If it is possible that extensions provide new table types, then perhaps (de)installation of such an extension would require a refresh of the list. 

### To Reproduce

```
	public static void test_getTableTypes() throws Exception {
		String[] tableTypesArray = new String[]{"BASE TABLE", "LOCAL TEMPORARY", "VIEW"};
		List<String> tableTypesList = new ArrayList(Arrays.asList(tableTypesArray));
    
		Connection conn = DriverManager.getConnection("jdbc:duckdb:");
		DatabaseMetaData databaseMetaData = connection.getMetaData();
    
		ResultSet tableTypesResultSet = databaseMetaData.getTableTypes();
		while (tableTypesResultSet.next()) {
			String tableType = tableTypesResultSet.getString("TABLE_TYPE");
			if (tableTypesList.contains(tableType)){
				tableTypesList.remove(tableType);
			}
			else {
				throw new Exception("Unexpected table type " + tableType);
			}
    }
		assertTrue(
			availableTypes().size() == 0,
			"DatabaseMetaData.getTableTypes() should return " + String.join(",", tableTypesArray);
		);
	}

```

### OS:

Windows 10 Pro

### DuckDB Version:

v0.6.2-dev2100

### DuckDB Client:

DuckDBJ (jdbc)

### Full Name:

Roland Bouman

### Affiliation:

Just-Bi.nl (an EPAM company)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by rpbouman**
fixes #6159

Added test for DatabaseMetaData.getTableTypes()
Test reproduces https://github.com/duckdb/duckdb/issues/6159 
getTableTypes now returns a static list.

### CODE REVIEW

**Comment by rpbouman** [comment]
I'll pick it up later today. Test ran succesful for me, I will find out why there was a different result and fix it.

**Comment by Tishj** [comment]
Thanks for the PR!
I have one small nit: can you change the description to say `fixes #6159`
That way it automatically closes the referenced issue, not only mention it

**Comment by rpbouman** [comment]
> Thanks for the PR! I have one small nit: can you change the description to include `fixes #6159` That way it automatically closes the referenced issue, not only mention it

Sure! I'll think about that for the next time. I hope I changed it correctly here for now. Let me know if not and I'll try again.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
