### PR TITLE
Fix mingw

### PR DESCRIPTION
**Pull request by mattn**
duckdb is not possible to build on mingw.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

This looks good to me. Disabling the build of the loadable extension on MINGW is fine. The build of that is not particularly important and only used for testing loadable extensions.

We should add a CI run of a dedicated mingw build at some point. Currently we only build the R packages using mingw, but this only tests the core system and not the entire repo.

**Comment by Mytherin** [comment]
The Windows tests appear to be failing. Could you have a look?

**Comment by mattn** [comment]
I'll look in later.

**Comment by Mytherin** [comment]
I had a go at developing a CI run for MingW. You can see the test run [here](https://github.com/Mytherin/duckdb/runs/2508970149?check_suite_focus=true). This seems to fail in the same location as what your PR is trying to fix (the delayload extension). 

Here is the Github Actions CI integration:

```

  mingw:
    name: MingW (64 Bit)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja git
      # see here: https://gist.github.com/scivision/1de4fd6abea9ba6b2d87dc1e86b5d2ce
      - name: Put MSYS2_MinGW64 on PATH
        # there is not yet an environment variable for this path from msys2/setup-msys2
        run: export PATH=D:/a/_temp/msys/msys64/mingw64/bin:$PATH

      - name: Build
        run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_PARQUET_EXTENSION=1
          cmake --build . --config Release

      - name: Test
        run: test/Release/unittest.exe
```

Just documenting this here so we can include it after this PR is merged. Or if you want to include it in this PR, that would be great as well.

**Comment by mattn** [comment]
@Mytherin Could you please run CI again?

**Comment by Mytherin** [comment]
Thanks for the updates! There still seem to be some CI failures. Specifically it seems like the load_extension test now crashes on the regular MSVC compilers. Could you have a look there?

The MingW CI job also fails but that seems more benign. It appears to me that the test should be called with `test/unittest.exe` instead of `test/Release/unittest.exe` (which is how it needs to be called when compiled with MSVC).

**Comment by Mytherin** [comment]
Thanks for the changes again! It seems that the CI did not get triggered somehow (GH actions bug?). Could you perhaps push again when you have time?

**Comment by Mytherin** [comment]
I have taken the liberty of moving the MingW build fixes and CI run to #1824. Closing this PR.

**Pull request closed without merging**
