### PR TITLE
[CSV Reader] Apply projection on over buffer values.

### LINKED ISSUE #11040: CSV read, INTERNAL Error: Attempted to access index 1 within vector of size 1
### What happens?

Hi,
I try to read a big CSV file and I have INTERNAL Error.

### To Reproduce

I cannot attach a sample file, because it's big.

The source is a CSV, with delim=";" https://opencoesione.gov.it/media/open_data//progetti_esteso_20231231.zip

Decompress it and get the top 290k lines:

```bash
progetti_esteso_20231231.zip
<progetti_esteso_20231231.csv head -n 290000 >tmp.csv
```

Then I run

```
duckdb --csv -c "SET preserve_insertion_order=false;SELECT count(*) FROM read_csv_auto('tmp.csv',parallel=false,all_varchar=true)"
```

and I have 

```
Error: INTERNAL Error: Attempted to access index 1 within vector of size 1
```

### OS:

Debian 12

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

0.10.0

### Full Name:

Andrea Borruso

### Affiliation:

onData

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by pdet**
Fix #11040

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks!

**Comment by aborruso** [comment]
Thanks

**Comment by aborruso** [comment]
Hi @pdet and thank you for this fix. To use duckdb with this fix should I download the source code and compile it?

**Comment by pdet** [comment]
Hi @aborruso 

Thank you for giving an easy to run reproducible example!

Indeed building from the sources should work, we are also releasing a bug-fix version next week that will feature this PR!

**Comment by aborruso** [comment]
> we are also releasing a bug-fix version next week that will feature this PR!

@pdet When do you think it will be released? Thank you very much

**Comment by nileshtrivedi** [comment]
Is this fix part of the 0.10.2 release on homebrew?

**Comment by nileshtrivedi** [comment]
I still seem to be running into this bug: https://github.com/duckdb/duckdb/issues/11040#issuecomment-2098239050

**Pull request merged**
