### PR TITLE
Fix #8191 - build duckdb shell error with “DISABLE_UNITY=1” for link …

### LINKED ISSUE #8191: build duckdb shell error with  “DISABLE_UNITY=1” for link stage issue
### What happens?

when build duckdb with "DISABLE_UNITY=1" . it report link error：
[ 90%] Linking CXX executable ../../duckdb
/usr/bin/ld: ../../extension/parquet/libparquet_extension.a(parquet_extension.cpp.o): in function `duckdb::ParquetExtension::Load(duckdb::DuckDB&)':
/home/zhaozhou/duckdb/origin/extension/parquet/parquet_extension.cpp:936: undefined reference to `duckdb::ExtensionUtil::RegisterFunction(duckdb::DatabaseInstance&, duckdb::TableFunctionSet)'
/usr/bin/ld: /home/zhaozhou/duckdb/origin/extension/parquet/parquet_extension.cpp:938: undefined reference to `duckdb::ExtensionUtil::RegisterFunction(duckdb::DatabaseInstance&, duckdb::TableFunctionSet)'
/usr/bin/ld: /home/zhaozhou/duckdb/origin/extension/parquet/parquet_extension.cpp:942: undefined reference to `duckdb::ExtensionUtil::RegisterFunction(duckdb::DatabaseInstance&, duckdb::TableFunctionSet)'
/usr/bin/ld: /home/zhaozhou/duckdb/origin/extension/parquet/parquet_extension.cpp:946: undefined reference to `duckdb::ExtensionUtil::RegisterFunction(duckdb::DatabaseInstance&, duckdb::TableFunctionSet)'
/usr/bin/ld: /home/zhaozhou/duckdb/origin/extension/parquet/parquet_extension.cpp:965: undefined reference to `duckdb::ExtensionUtil::RegisterFunction(duckdb::DatabaseInstance&, duckdb::CopyFunction)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/shell/CMakeFiles/shell.dir/build.make:127: duckdb] Error 1
make[1]: *** [CMakeFiles/Makefile2:6744: tools/shell/CMakeFiles/shell.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### To Reproduce

DISABLE_UNITY=1 make reldebug

### OS:

linux

### DuckDB Version:

latest main branch

### DuckDB Client:

latest main branch

### Full Name:

zhao zhou

### Affiliation:

clickhouse

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by zzachimed**
…stage issue

libparquet_extension.a should link static duckdb lib

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! I think this should be done in `build_loadable_extension`, however. This fixes the issue only for the parquet extension rather than for all extensions.

**Comment by zzachimed** [comment]
> Thanks for the PR! I think this should be done in `build_loadable_extension`, however. This fixes the issue only for the parquet extension rather than for all extensions.

yes, my fix for this build issue is only in "extension/parquet/CMakeLists.txt" . other issue is my compiler warning for that duplicate descriptor , i just remove one of his.

**Comment by zzachimed** [comment]
> I understand - my comment was stating that that fix is not a generic fix for the problem, but rather a patch for when only the Parquet extension is enabled (which is the default configuration). The linking issues will still happen when other extensions are enabled (e.g. `BUILD_TPCH=1 DISABLE_UNITY=1`). In other to fix this generically could you move the `target_link_libraries` to the `build_loadable_extension` CMake function?

okay . I would :)

**Comment by zzachimed** [comment]
@Mytherin 
 hi all done！:)

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
