### PR TITLE
Faster PIVOT statement

### PR DESCRIPTION
**Pull request by Mytherin**
This PR reworks how pivots are computed internally to greatly improve the performance of pivots, particularly when there are many unique pivot groups.

##### Example Table
```
┌─────────┬───────────────┬───────┬────────────┐
│ Country │     Name      │ Year  │ Population │
│ varchar │    varchar    │ int32 │   int32    │
├─────────┼───────────────┼───────┼────────────┤
│ NL      │ Amsterdam     │  2000 │       1005 │
│ NL      │ Amsterdam     │  2010 │       1065 │
│ NL      │ Amsterdam     │  2020 │       1158 │
│ US      │ Seattle       │  2000 │        564 │
│ US      │ Seattle       │  2010 │        608 │
│ US      │ Seattle       │  2020 │        738 │
│ US      │ New York City │  2000 │       8015 │
│ US      │ New York City │  2010 │       8175 │
│ US      │ New York City │  2020 │       8772 │
└─────────┴───────────────┴───────┴────────────┘
```

#### Previous Pivot

In the previous implementation (#6387) we used to generate a set of filtered aggregates. So running the following query on the above dataset:

```sql
PIVOT Cities ON Year USING SUM(Population);
```

Runs the following query:

```sql
SELECT Country,
       Name,
       SUM(Population) FILTER (Year=2000) AS "2000",
       SUM(Population) FILTER (Year=2010) AS "2010",
       SUM(Population) FILTER (Year=2020) AS "2020"
FROM Cities
GROUP BY ALL;
```

Which produces the following result:

```sql
┌─────────┬───────────────┬────────┬────────┬────────┐
│ Country │     Name      │  2000  │  2010  │  2020  │
│ varchar │    varchar    │ int128 │ int128 │ int128 │
├─────────┼───────────────┼────────┼────────┼────────┤
│ NL      │ Amsterdam     │   1005 │   1065 │   1158 │
│ US      │ Seattle       │    564 │    608 │    738 │
│ US      │ New York City │   8015 │   8175 │   8772 │
└─────────┴───────────────┴────────┴────────┴────────┘
```

While that works, it does not scale well with the amount of pivots. That is because each filtered aggregate takes up a spot in the aggregate hash table. If we have, say, 2000 pivots, our hash table rows become very large (2000 * state_size). Because the filters are very selective (every row passes exactly one of the N filters) the performance also becomes very bad as the amount of pivots increases.

#### New Pivot
In this PR, we rework the pivot to instead execute the following query:

```sql
SELECT Country, Name, LIST(YEAR), LIST(population_sum)
FROM (
    SELECT Country, Name, Year, SUM(population) AS population_sum
    FROM Cities
    GROUP BY ALL
)
GROUP BY ALL;
```

This produces the following result:

```sql
┌─────────┬───────────────┬────────────────────┬──────────────────────┐
│ Country │     Name      │    list("YEAR")    │ list(population_sum) │
│ varchar │    varchar    │      int32[]       │       int128[]       │
├─────────┼───────────────┼────────────────────┼──────────────────────┤
│ NL      │ Amsterdam     │ [2000, 2010, 2020] │ [1005, 1065, 1158]   │
│ US      │ Seattle       │ [2000, 2010, 2020] │ [564, 608, 738]      │
│ US      │ New York City │ [2000, 2010, 2020] │ [8015, 8175, 8772]   │
└─────────┴───────────────┴────────────────────┴──────────────────────┘
```

We then have a dedicated **PhysicalPivot** operator that takes these lists and expands them into the actual columns, producing the desired pivot result.

#### Distinct On

We also fix a performance issue with the `DISTINCT` operator introduced by #6616, where a regular `DISTINCT` would be transformed into a `DISTINCT ON` when combined with an `ORDER BY` clause with rows not present in the `DISTINCT`. This was a problem for pivot because pivot uses `DISTINCT` to compute the unique values to pivot on - which was then transformed into `DISTINCT ON` instead. `DISTINCT ON` is many times slower because it computes a sorted aggregate, which became a performance bottleneck. Fixing this issue greatly improves the performance of all pivots.

##### 3 pivot columns, 2527 groups

```sql
PIVOT 'lineitem.parquet' ON l_returnflag USING SUM(l_extendedprice) GROUP BY l_shipdate;
```

|  New  | Old  |
|-------|------|
| 0.07s | 1.4s |

##### 2527 pivot columns, 3 groups

```sql
PIVOT 'lineitem.parquet' ON l_shipdate USING SUM(l_extendedprice) GROUP BY l_returnflag;
```

|  New  | Old  |
|-------|------|
| 0.12s | 4m16s |

##### 10000 pivot columns, 2526 groups

```sql
PIVOT 'lineitem.parquet' ON l_suppkey USING SUM(l_extendedprice) GROUP BY l_shipdate;
```

|  New  | Old  |
|-------|------|
| 2.1s | T |

##### 2527 pivot columns, 1500000 groups

```sql
PIVOT 'lineitem.parquet' ON l_shipdate USING SUM(l_extendedprice) GROUP BY l_orderkey;
```

|  New  | Old  |
|-------|------|
| 21.4s | T |

#### Pivot Column Limit

Because the pivot clause is now so much better at dealing with many columns, we also raise the pivot column limit from 10K to 100K.

### CODE REVIEW

**Comment by l1t1** [comment]
please add new content to https://duckdb.org/docs/sql/statements/pivot

**Comment by Alex-Monahan** [comment]
> please add new content to https://duckdb.org/docs/sql/statements/pivot

It's on my list!

**Comment by Alex-Monahan** [comment]
See duckdb/duckdb-web#790!

**Comment by l1t1** [comment]
could you add two features. 
1. add order option for on clause
2. add cube/rollup/grouping sets for group by clause, see https://github.com/duckdb/duckdb/discussions/7584

**Comment by l1t1** [comment]
can it be faster?
https://github.com/duckdb/duckdb/discussions/7798

**Pull request merged**
