### PR TITLE
Fix bug in parquet reader causing list columns to be parsed incorrectly (#2557)

### PR DESCRIPTION
**Pull request by FenrirWillow**
According to https://github.com/duckdb/duckdb/issues/2557 the parquet reader does not correctly deserialize columns, whose values are lists. This was caused by the incorrect assumption in the code that leaf nodes are only non-repeating types. Adding a branch that explicitly checks for repeating fields produces the correct results.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks great. Would it be possible to add some tests for this behavior?

**Comment by FenrirWillow** [comment]
Hiya @Mytherin , that was a blazingly swift reply! Yes, I will add a regression test to make sure that this doesn't return in nasty forms. Looks like some of the other checks are failing as well, I will take a look at them as well.

**Comment by Mytherin** [comment]
Great, thanks!

The format checker can be fixed by running `make format-fix`, this requires the following libraries:

```
cmake-format --version
0.6.13

clang-format -version
Homebrew clang-format version 12.0.1
```

You can also fix this manually by looking at the logs and fixing it from there.

**Comment by FenrirWillow** [comment]
Hi @Mytherin , I have fixed the formatting of the code as well as added a small test file + query to prevent regressions in the code. I believe this is ready for review now. Let me know if any more work needs to be done on this, thank you :)

**Comment by hannesmuehleisen** [comment]
Thanks for looking into this!

**Comment by Mytherin** [comment]
Thanks again for the PR! Looks great.

**Pull request merged**
