### PR TITLE
Fix issue 1987: decimal casts are only reversible if the scale is not decreased

### LINKED ISSUE #1987: Casting decimal column to integer requires explicit 0 decimal specifier
Casting a decimal column to an integer does not match rows without explicitly appending a ".0".  The SQL statement should not require a decimal specifier to match an integer value

**To Reproduce**
```
>>> con.execute("create table test (consumption decimal(14,5))")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> con.execute("insert into test values(17953.2)")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> con.execute("select * from test where cast(consumption as int) = 17953")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> print(con.fetchall())
[]
>>> con.execute("select * from test where cast(consumption as int) = 17953.0")
<duckdb.DuckDBPyConnection object at 0x1170f66f0>
>>> print(con.fetchall())
[(Decimal('17953.20000'),)]
```
I tried the same experiment with Postgres and it works as I would expect
postgres-sample

**Environment (please complete the following information):**
 - OS: [e.g. MacOS (M1)]
 - DuckDB Version  0.2.7 -> 8bc050d05

### PR DESCRIPTION
**Pull request by Mytherin**

### CODE REVIEW

**Comment by chrisfw** [comment]
@Mytherin ,  thanks for fixing this issue so quickly!  Do you have any ETA for when the next release that will include it will be delivered?

Thanks,
Chris

**Comment by Mytherin** [comment]
We should have a release relatively soon (in the next 1-2 weeks). In the meantime you could use `pip install duckdb --pre` to get the pre-release version and use that.

**Comment by chrisfw** [comment]
@Mytherin , thanks for the info.  Much appreciated!

Regards,
Chris

**Comment by chrisfw** [comment]
Hello Mark,

I just wanted to let you know that #1987 was not included in Release 0.2.8
Preview Release "Ceruttii" · duckdb/duckdb (github.com)
<https://github.com/duckdb/duckdb/releases/tag/v0.2.8>.  Can you please let
me know when you think it will be included?

Thanks,
Chris

**Comment by Mytherin** [comment]
That PR should have been included in the release. I suspect you are probably still using the old version. Could you check which version you are using? Perhaps explicitly delete the package and reinstall.

**Comment by chrisfw** [comment]
Apologies, I was just going by the list of issues identified in the release
notes expecting to see it listed.  I will do as you suggest and let you
know if the issue has/has not been addressed.

Regards,
Chris

**Comment by Mytherin** [comment]
> Apologies, I was just going by the list of issues identified in the release notes expecting to see it listed. I will do as you suggest and let you know if the issue has/has not been addressed. Regards, Chris
> […](#)

Ah I see the confusion. Any PR that has happened before the release is included in the release, the patch notes are just a list of highlights.

**Comment by chrisfw** [comment]
Great, thanks for clarifying!

Regards,
Chris

**Comment by chrisfw** [comment]
FYI Mark, I confirmed the issue is resolved.  Thanks for all of your
assistance and getting it fixed so quickly.

Regards,
Chris

**Pull request merged**
