### PR TITLE
PhysicalPiecewiseMergeJoin improvement

### PR DESCRIPTION
**Pull request by xuke-hat**
In merge sort, for two sorted array with length _n_ and _m_ respectively, we can merge them using _n + m_ times comparison. But in `MergeJoinComplexBlocks` function, it calls compare function for _n * m_ times. This is inefficient.

This PR removes redundant comparisons by using the same idea in merge sort, and a small refactor that removes unnecessary check in `MergeSorter::ComputeMerge`.

In my computer, this optimization can reduce about 50% time when join condition has high selectivity.

```
benchmark/micro/join/range_join_big_result.benchmark       1       14.491618
benchmark/micro/join/range_join_big_result.benchmark       2       15.580933
benchmark/micro/join/range_join_big_result.benchmark       3       15.625284
benchmark/micro/join/range_join_big_result.benchmark       4       15.702231
benchmark/micro/join/range_join_big_result.benchmark       5       15.571635
```

```
benchmark/micro/join/range_join_big_result.benchmark       1       7.537545
benchmark/micro/join/range_join_big_result.benchmark       2       7.540828
benchmark/micro/join/range_join_big_result.benchmark       3       7.678278
benchmark/micro/join/range_join_big_result.benchmark       4       8.034369
benchmark/micro/join/range_join_big_result.benchmark       5       8.167570
```

### CODE REVIEW

**Review by lnkuiper — CHANGES_REQUESTED** [review]
Hi @xuke-hat, thanks for the contribution and great results! The changes to the sort code look good to me.

The changes to the physical piecewise are harder to judge for me since I've never touched that operator, but I can see that you have properly implemented what you explained.

Just as a final check, I ran two other benchmarks:

Old
```
benchmark/micro/join/range_join.benchmark	1	0.016442
benchmark/micro/join/range_join.benchmark	2	0.016140
benchmark/micro/join/range_join.benchmark	3	0.015836
benchmark/micro/join/range_join.benchmark	4	0.015820
benchmark/micro/join/range_join.benchmark	5	0.015634
```

New:
```
benchmark/micro/join/range_join.benchmark	1	0.020688
benchmark/micro/join/range_join.benchmark	2	0.021087
benchmark/micro/join/range_join.benchmark	3	0.020466
benchmark/micro/join/range_join.benchmark	4	0.020522
benchmark/micro/join/range_join.benchmark	5	0.020755
```

Old:
```
benchmark/micro/join/range_join_small_rhs.benchmark	1	0.523022
benchmark/micro/join/range_join_small_rhs.benchmark	2	0.536489
benchmark/micro/join/range_join_small_rhs.benchmark	3	0.548325
benchmark/micro/join/range_join_small_rhs.benchmark	4	0.524254
benchmark/micro/join/range_join_small_rhs.benchmark	5	0.523368
```

New:
```
benchmark/micro/join/range_join_small_rhs.benchmark	1	0.531468
benchmark/micro/join/range_join_small_rhs.benchmark	2	0.533025
benchmark/micro/join/range_join_small_rhs.benchmark	3	0.524933
benchmark/micro/join/range_join_small_rhs.benchmark	4	0.528581
benchmark/micro/join/range_join_small_rhs.benchmark	5	0.532904
```

We seem to slightly regress on `benchmark/micro/join/range_join.benchmark`. I've increased the table size in this benchmark from `100000` to `1000000`, which shows the regression more clearly.

Old:
```
benchmark/micro/join/range_join.benchmark	1	0.196376
benchmark/micro/join/range_join.benchmark	2	0.199535
benchmark/micro/join/range_join.benchmark	3	0.199299
benchmark/micro/join/range_join.benchmark	4	0.191540
benchmark/micro/join/range_join.benchmark	5	0.192165
```

New:
```
benchmark/micro/join/range_join.benchmark	1	0.314207
benchmark/micro/join/range_join.benchmark	2	0.307995
benchmark/micro/join/range_join.benchmark	3	0.317040
benchmark/micro/join/range_join.benchmark	4	0.322981
benchmark/micro/join/range_join.benchmark	5	0.316267
```

 Do you know why this is happening? Is there any way to prevent this regression?

**Comment by xuke-hat** [comment]
@lnkuiper Thanks for your review! Sorry I didn't notice the regression.

The optimization doesn't work for `range_join.benchmark` because in this case `prev_left_index` is always zero. But the only extra overhead is the check in while loop `if (l.entry_idx < prev_left_index)`. This should not lead to such a big regression.

After profiling I found the new code runs 50% more instructions than before. It seems that the check `if(left_smaller)` prevents compiler optimization. I tried to remove it, duplicate the code that adds the result, and then the code runs much faster, although I'm not sure why.

Can you check this again? In my computer the difference is small now.

Old:

```
benchmark/micro/join/range_join.benchmark       1       0.592475
benchmark/micro/join/range_join.benchmark       2       0.618149
benchmark/micro/join/range_join.benchmark       3       0.631459
benchmark/micro/join/range_join.benchmark       4       0.632031
benchmark/micro/join/range_join.benchmark       5       0.657024
```

New:

```
benchmark/micro/join/range_join.benchmark       1       0.585060
benchmark/micro/join/range_join.benchmark       2       0.619822
benchmark/micro/join/range_join.benchmark       3       0.605059
benchmark/micro/join/range_join.benchmark       4       0.590049
benchmark/micro/join/range_join.benchmark       5       0.618771
```


Old:

```
benchmark/micro/join/range_join_big_result.benchmark    1       16.736743
benchmark/micro/join/range_join_big_result.benchmark    2       16.490013
benchmark/micro/join/range_join_big_result.benchmark    3       16.687082
benchmark/micro/join/range_join_big_result.benchmark    4       16.515909
benchmark/micro/join/range_join_big_result.benchmark    5       16.596720
```

New:

```
benchmark/micro/join/range_join_big_result.benchmark    1       8.841478
benchmark/micro/join/range_join_big_result.benchmark    2       8.572311
benchmark/micro/join/range_join_big_result.benchmark    3       8.592798
benchmark/micro/join/range_join_big_result.benchmark    4       9.131125
benchmark/micro/join/range_join_big_result.benchmark    5       8.553141
```

**Comment by xuke-hat** [comment]
How does regression test work? I looked q07c and there is no merge join.

**Review by lnkuiper — APPROVED** [review]
Thanks for the changes! The regression is no longer noticeable on my laptop:

Old
```
benchmark/micro/join/range_join.benchmark	1	0.200453
benchmark/micro/join/range_join.benchmark	2	0.194145
benchmark/micro/join/range_join.benchmark	3	0.192344
benchmark/micro/join/range_join.benchmark	4	0.195178
benchmark/micro/join/range_join.benchmark	5	0.199881
```

New:
```
benchmark/micro/join/range_join.benchmark	1	0.214820
benchmark/micro/join/range_join.benchmark	2	0.216098
benchmark/micro/join/range_join.benchmark	3	0.228246
benchmark/micro/join/range_join.benchmark	4	0.229273
benchmark/micro/join/range_join.benchmark	5	0.233986
```

This PR is ready to be merged :)

**Review by hawkfish — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
