### PR TITLE
Implement more string functions

### PR DESCRIPTION
**Pull request by hawkfish**
Add implementations and tests for:

- `LPAD` / `RPAD`
- `LTRIM` / `RTRIM`
- `REPEAT`
- `REPLACE`
- `UNICODE`

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! The code looks good, but it looks like there are some compilation errors on some platforms. Could you have a look?

**Comment by hawkfish** [comment]
Looks like just a `max` argument deduction issue. Is there a way I can check this on my fork (I only have a Mac laptop) or should I just resubmit the request?

**Comment by Mytherin** [comment]
Just push a commit and it should rerun the travis tests I think. Otherwise you can set up travis testing on your fork yourself I believe, just check [here](https://travis-ci.org).

**Comment by Mytherin** [comment]
Looks great now, thanks for the effort! Shall I merge it in?

**Comment by hawkfish** [comment]
Yes please!  I was going to start on the bit functions next. It's hard to do anything to involved right now because all I have is a Mac laptop and no real workspace, but maybe things will improve in the next few weeks.

**Comment by Mytherin** [comment]
Alright, I will merge it then :) Thanks again

**Pull request merged**
