### PR TITLE
Block verification run and FixedSizeBuffer fix

### PR DESCRIPTION
**Pull request by taniabogatsch**
Attempts to solve https://github.com/duckdb/duckdb/issues/13311.

The original file does not contain SQL commands, etc., to generate the data, so I cannot confirm that this PR fixes the original issue. However, we did notice irregularities in the block counters in some cases, potentially related to the issue, so this PR adds a verification pass to the block usage counters. And a fix for the irregular counters.

### CODE REVIEW

**Comment by taniabogatsch** [comment]
Overview (unrelated) nightly failures.

**Python SQLLogicTest Library (Linux)**
```
[167/3017] /home/runner/work/duckdb/duckdb/tools/pythonpkg/scripts/../../../test/fuzzer/duckfuzz/duck_fuzz_column_binding_tests.test
/home/runner/work/duckdb/duckdb/tools/pythonpkg/scripts/../../../test/fuzzer/duckfuzz/duck_fuzz_column_binding_tests.test:36 Query unexpectedly succeeded
```

**Storage Initialization Verification**
```
------------------------------------------------------------------
FAIL - Mismatch between one-initialized and zero-initialized databases at byte position 274515
------------------------------------------------------------------
One-initialized database test_standard_db/test_store_list_of_structs.db - byte value 155
Zero-initialized database test_zero_init_db/test_store_list_of_structs.db - byte value 250
This byte is in block id 1 at byte position 75 (position 83 including the block checksum)
------------------------------------------------------------------
This error likely means that memory was not correctly zero-initialized in a block before being written out to disk.
```

**Linux (32 Bit)**
Same as in the [nightly run](https://github.com/duckdb/duckdb/actions/runs/10587966051/job/29352188938).
**Extension updating test**
Unrelated - incorrect extension update result.
**Thread Sanitizer**
Same as in the [nightly run](https://github.com/duckdb/duckdb/actions/runs/10587966051/job/29352194243).

**Comment by taniabogatsch** [comment]
Unsure about this one: https://github.com/duckdb/duckdb/actions/runs/10595598428/job/29362386688?pr=13607

**Comment by Mytherin** [comment]
I have a fix up for the broken test in https://github.com/duckdb/duckdb/compare/main...Mytherin:duckdb:trackoverflowstrings?expand=1 - I will PR it after this is merged

**Comment by taniabogatsch** [comment]
local latest storage run results

```sql
[2901/3969] (73%): test/sql/storage/optimistic_write/optimistic_write_large_s...================================================================================
Query unexpectedly failed! (test/sql/storage/optimistic_write/optimistic_write_large_strings_deletes.test_slow:46)!
================================================================================
COMMIT;
================================================================================
FATAL Error: Failed to create checkpoint because of error: Blocks 2 were neither present in the free list or in the block_usage_count (max block 5)
```
Should be the same as the fix for the other test (@Mytherin)?

```sql
[3076/3969] (77%): test/sql/attach/attach_index.test                            ================================================================================
Wrong row count in query! (test/sql/attach/attach_index.test:42)!
Expected 1 rows, but got 0 rows
================================================================================
SELECT * FROM index_db.tbl_a WHERE a_id=2;
================================================================================
Expected result:
================================================================================
2	y
================================================================================
Actual result:
================================================================================
a_id	value	
INTEGER	VARCHAR	
[ Rows: 0]
```
Should be the same cause as https://github.com/duckdb/duckdb/pull/13610.

```sql
[3330/3969] (83%): test/sql/index/art/storage/test_art_duckdb_versions.test     ================================================================================
Wrong result in query! (test/sql/index/art/storage/test_art_duckdb_versions.test:122)!
================================================================================
SELECT used_blocks < 2621440 / get_block_size('test_art_import') FROM pragma_database_size();
================================================================================
Mismatch on row 1, column 1
0 <> 1
================================================================================
Expected result:
================================================================================
1
================================================================================
Actual result:
================================================================================
0
```
Introduced in https://github.com/duckdb/duckdb/pull/12768. I'm working on a fix. Related issue: https://github.com/duckdblabs/duckdb-internal/issues/2532.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
