### PR TITLE
Throw exception on type error in JsonDeserializer

### PR DESCRIPTION
**Pull request by Maxxen**
Found by @Wang-Ji20 in #6919

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! LGTM - but it seems this breaks one of the existing tests.

**Comment by Wang-Ji20** [comment]
That's caused by the type check during json deserialization. 
seems when the number is positive, 3 in this case, the number is recognized as unsigned number, rather than signed integer. so the test case failed.

**Comment by Maxxen** [comment]
Ill continue with this once I pick up the serialization work again next week.

**Comment by Maxxen** [comment]
@taniabogatsch This also now fixes the ugly `(void)field_id` in the JsonDeserializer

**Comment by taniabogatsch** [comment]
Ah, that's a neat solution!

**Pull request merged**
