### PR TITLE
Add functions for handling null duckdb_values

### PR DESCRIPTION
**Pull request by Giorgi**

### CODE REVIEW

**Review by Tishj — APPROVED** [review]
Thanks!

**Comment by Maxxen** [comment]
Thinking about the API consistency, would it be more fitting if these were called `duckdb_create_null_value` (like e.g. `duckdb_create_list_value`) and, presumably, something like `duckdb_is_null_value`?

**Comment by Giorgi** [comment]
@Maxxen Those names sound better, renamed.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
