### PR TITLE
[ParquetWriter] Prevent creating broken parquet files

### LINKED ISSUE #6067: Parquet writer allows duplicate columns
### What happens?

When writing to Parquet there is no error if there are duplicate column names.

This causes exception when Parquet file is read. It would be better if exception was thrown before writing the file instead of producing broken file.

### To Reproduce

```sql
COPY (SELECT 1 as a, 2 as a) TO '/tmp/duckdb-test/bad.parquet';
SELECT * FROM '/tmp/duckdb-test/bad.parquet';
```

### OS:

Linux

### DuckDB Version:

0.6.2-dev1770

### DuckDB Client:

Python

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6067

As the issue pointed out, previously we did not check for duplicates in column names, writing them to the parquet file created a broken parquet file.

Now we rename the duplicate column names in a way that's consistent with the way it is done in other parts of the code before writing the parquet file

### CODE REVIEW

**Comment by hannes** [comment]
Can we double check duplicate column names are actually not allowed in the parquet format spec?

**Comment by Mytherin** [comment]
Thanks for the PR! Perhaps we can do this in the bind copy so this works for the CSV writer as well?

**Comment by Tishj** [comment]
> Can we double check duplicate column names are actually not allowed in the parquet format spec?

`pyarrow.lib.ArrowInvalid: Multiple matches for FieldRef.Name(a) in a: int32`
I have not checked the spec, but I have checked pandas, and they throw this error, through `pyarrow`

**Comment by hannes** [comment]
From this it looks like it has to be unique 
 (from 
https://parquet.apache.org/images/FileFormat.gif)

**Comment by Tishj** [comment]
> Thanks for the PR! Perhaps we can do this in the bind copy so this works for the CSV writer as well?

Yes I can do that, though for CSV the file can be written with duplicate column names just fine, just when reading them we seem to dedupe them:
```
Binder Error: Referenced column "a:1" not found in FROM clause!
Candidate bindings: "duckdb_unittest_tempdir/10328/dupe_cols.csv.a_1", "duckdb_unittest_tempdir/10328/dupe_cols.csv.a", "duckdb_unittest_tempdir/10328/dupe_cols.csv.a_2"
```

**Comment by Mytherin** [comment]
Other libraries would probably not be so happy with duplicate column names - so I would say de-duplicating on write is a better idea. Also for the (future) JSON write this would be required/useful.

**Pull request merged**
