### PR TITLE
Check prefix length, not string_t::INLINE_LENGTH when comparing strings while sorting

### LINKED ISSUE #4822: Postgres <> DuckDB Window Function Inconsistency
### What happens?

Window function results are inconsistent between DuckDB (running on CSV) and Postgres and also somehow dependent on DuckDB thread count.

### To Reproduce

Run the following query in Postgres

```SQL
create table window_test as
select
    x as unique_id
    ,current_timestamp - x * interval '1 minute' as timestamp_column
    ,'varchar2_' || cast(mod(x,100000) as varchar) as varchar_2 
from generate_series(1,1000000) t(x);
```

the following query should return `100000`

```SQL
select count(*) from (
  select *, row_number() over (partition by varchar_2 order by timestamp_column desc, unique_id desc) as sort_id 
  from window_test
) sq WHERE sort_id = 1;
```

Now export to CSV
```SQL
copy (select * from window_test) to '/tmp/window_test.csv' with (format csv, header 1);
```

And run the query in DuckDB using the CSV reader
```SQL
select count(*) from (
  select *, row_number() over (partition by varchar_2 order by timestamp_column desc, unique_id desc) as sort_id 
  from '/tmp/window_test.csv'
) sq WHERE sort_id = 1;
```
This returns something that's decidedly not `100000` depending on the thread count. For me for one thread I get `129880`.

Interestingly, the issue disappears when I import the data into DuckDB first, e.g.

```SQL
create table window_test as select * from '/tmp/window_test.csv';
```

Then, DuckDB also correctly computes `100000`. The issue might be down to missing statistics. This originally surfaced here: https://github.com/duckdblabs/postgres_scanner/issues/8

### OS:

Mac OS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Hannes Mühleisen

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by lnkuiper**
Incredible that we did not catch this before! Fixes issue #4766

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! There appears to be a remaining test failure (`test/sql/order/order_parallel_complex.test_coverage`). Could you have a look?

**Comment by lnkuiper** [comment]
Think I fixed it properly now. Fingers crossed for the CI

**Comment by Mytherin** [comment]
Looks like the force storage is reliably failing still, could you have a look?

**Comment by lnkuiper** [comment]
Can't reproduce the issue with force storage. I figured that the CI runner has low memory, so I tried running with `PRAGMA debug_force_external=true`,  but it still succeeds. Timing/memory usage is exactly the same as master. Going to investigate more

**Comment by Mytherin** [comment]
Thanks for looking into it - somehow this has been fixed. Perhaps it had nothing to do with this PR after all.

**Pull request merged**
