### PR TITLE
JSON bugfixes and new functions

### LINKED ISSUE #13436: JSON_TYPE function produces wrong result if path is a column expression
### What happens?

The `JSON_TYPE` function produces wrong results depending on how I'm passing the path argument

### To Reproduce

Run this query:

```sql
SELECT 
  json_type (json '{"a":1,"b":null}', p),
  json_type (json '{"a":1,"b":null}', 'b')
FROM (VALUES ('b')) AS t (p);
```

This produces:

```
|json_type(CAST('{"a":1,"b":null}' AS "json"), p)|json_type(CAST('{"a":1,"b":null}' AS "json"), 'b')|
|------------------------------------------------|--------------------------------------------------|
|                                                |NULL                                              |
```

The first result is wrong (SQL `NULL`). It should be just like the second result `'NULL'`

### OS:

Microsoft Windows [Version 10.0.22631.3880]

### DuckDB Version:

1.0.0

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by lnkuiper**
This PR fixes https://github.com/duckdb/duckdb/issues/13436. Now, the extraction result should be the same whether the path is constant or not.

After a discussion in https://github.com/duckdb/duckdb/issues/13437, I've decided to revert the behavior implemented in #6779 to allow JSON `null` and SQL `NULL` to be distinguished again.

I've also implemented `json_exists` that returns `true` if the supplied path exists in the JSON, and `false` otherwise. I saw that BigQuery also supports the `json_value` function that is essentially the same as `json_extract`, except it sets the result to `NULL` if the JSON at the supplied path is not a scalar value.

### CODE REVIEW

**Review by Mytherin — COMMENTED** [review]
Thanks! LGTM - one comment:

**Comment by Mytherin** [comment]
Thanks!

**Comment by arifsaslam** [comment]
@lnkuiper After this change, I have difficulty distinguishing the absence of values(null) from the literal 'null' string
eg.
```sql
select '["null",2]'::json->>'0' as v;
select '[null,2]'::json->>'0' as v;
```
both retun null as string
```sql
┌─────────┐
│    v    │
│ varchar │
├─────────┤
│ null    │
└─────────┘
```

**Comment by lnkuiper** [comment]
Hi @arifsaslam, the behavior of this query hasn't changed with this PR. It may have been different in 1.0.0 vs 1.1.0.

I've taken a closer look at how JSON `null` values are handled in other systems, and found some differences, so I've opened a PR [here](#14032).

**Pull request merged**
