### PR TITLE
Allow DuckDB execution without implicit main thread

### PR DESCRIPTION
**Pull request by ywelsch**
When determining the degree to which pipelines should be parallelized, DuckDB currently assumes that there is always a main thread participating in the execution. For example, when configuring DuckDB to use 5 threads, it only spawns 4 background worker threads, and assumes that there is another thread (the main thread) participating in the query execution.

We're running DuckDB exclusively with background worker threads, which leads to the odd effect that pipelines are always parallelized to the N+1 level even though we only have N executors.

I'm opening this PR to show one possible solution to this problem (and will add tests if this is considered a direction worth pursuing).

The idea here is to change the semantics of "external_threads" so that it encompasses the main thread (that DuckDB currently implicitly assumes to always exist). Beside enabling DuckDB to run with only background worker threads I believe that it makes the system configuration easier to understand.

Before this PR, `external_threads` (default was 0) were counted in addition to the main thread, and we had the following:

| Settings | Number of background worker threads | Pipeline parallelism | Comment |
| --- | --- | --- | --- |
| `threads = default, external_threads = default` | `#cores - 1` | `#cores` | One main thread is implicitly assumed, `external_threads` defaults to 0
| `threads = X, external_threads = default` | `X - 1` | `X`  | `external_threads` defaults to 0
| `threads = 0` | invalid | invalid |
| `threads = default, external_threads = 0` | `#cores - 1` | `#cores` | There is always still the one main thread that is implicitly assumed
| `threads = X, external_threads = Y` | `X - 1` | `X + Y` |

In particular, the level of parallelism would be influenced by the combination of `threads` and `external_threads`. The single main thread was always assumed to be present. In a configuration where all threads were external (e.g. Julia), it was configured with `threads = 1, `external_threads = #cores - 1`,
see https://github.com/duckdb/duckdb/blob/d58cd19d5e70fb60ab5f9ea7ae01556c0a02e60c/tools/juliapkg/src/database.jl#L81

After this PR, the main thread is counted as part of `external_threads` (which now defaults to 1) we have the following:

| Settings | Number of background worker threads | Pipeline parallelism | Comment |
| --- | --- | --- | --- |
| `threads = default, external_threads = default` | `#cores - 1` | `#cores` | `external_threads` defaults to 1
| `threads = X, external_threads = default` | `X - 1` | `X` | `external_threads` defaults to 1
| `threads = 0` | invalid | invalid |
| `threads = default, external_threads = 0` | `#cores` | `#cores` | This config now allows running without main thread
| `threads = X, external_threads = Y` | `X - Y` | `X` | `external_threads` are now considered as a part of `threads` (i.e. must be smaller or equal to `threads`

The main difference is that `threads` now always controls the level of parallelism. `external_threads` allows configuring how many of those threads are external (i.e. not worker threads). In a configuration where all threads are external (e.g. Julia), it is now configured with `threads = #cores, `external_threads = #cores`, i.e., all threads are external threads.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! I agree this cleans up the thread configuration - considering the main thread as an external thread makes logical sense to me. If you could fix the CI we can get this in.

**Comment by Tishj** [comment]
Looks good to me, it does look like more of a code clean up without too many behavior consequences?

I had a question regarding the "We're running DuckDB exclusively with background worker threads" part though.
That is essentially what Julia does as well when `Threads.nthreads() > 1` but that broke a little bit with the recent changes to the stream query result.

Since it checks `ClientContext::ExecutionIsFinished` it never detected when all tasks had blocked, and needed a call to `Executor::ExecuteTask(dry_run = true)` to determine that was the case.

So I was just wondering if that is something you've taken into account

**Comment by ywelsch** [comment]
> I had a question regarding the "We're running DuckDB exclusively with background worker threads" part though.
That is essentially what Julia does as well when Threads.nthreads() > 1 but that broke a little bit with the recent changes to the stream query result.

The short answer is that we're not using the combination of running purely on background worker threads + streaming export. The former is purely a server thing, and the latter something we want to purely leverage in the client (e.g. WASM). Streaming data from server to client is done via a custom operator, not using DuckDB's streaming export.

> Since it checks ClientContext::ExecutionIsFinished it never detected when all tasks had blocked, and needed a call to Executor::ExecuteTask(dry_run = true) to determine that was the case.

> So I was just wondering if that is something you've taken into account

It's not immediately clear to me why this machinery is needed (I assume it's an effect of the current API design of QueryResult / PendingQueryResult that is not friendly to streaming export, given that there is still a distinction between query/fetch phase). If you walk me a bit through it, I can provide feedback.

**Comment by Tishj** [comment]
Just that in Julia we don't let the main thread contribute to execution of the query and instead loop until ExecutionIsFinished returns true, but this method is a little naive in that it only checks completed_pipelines >= total_pipelines.

So it does not catch the situation where a streaming query result is ready to be created (all tasks in the final pipeline are blocked)
At which point we should return from the execution call, letting the calls to Fetch on the StreamQueryResult be responsible for unblocking and finishing the last pipeline.

**Comment by ywelsch** [comment]
> Just that in Julia we don't let the main thread contribute to execution of the query and instead loop until ExecutionIsFinished returns true, but this method is a little naive in that it only checks completed_pipelines >= total_pipelines.
> 
> So it does not catch the situation where a streaming query result is ready to be created (all tasks in the final pipeline are blocked) At which point we should return from the execution call, letting the calls to Fetch on the StreamQueryResult be responsible for unblocking and finishing the last pipeline.

Thanks for the explanation. That sounds very unique to Julia then (for the time being at least). In DuckDB-WASM, for example, the main DuckDB worker thread participates in the execution as well.

**Comment by ywelsch** [comment]
PR is green now

**Comment by Mytherin** [comment]
Thanks! LGTM

**Pull request merged**
