### PR TITLE
feed table function into multifilereader initialization

### PR DESCRIPTION
**Pull request by samansmink**
perhaps a little (too?) hacky, but this allows injecting state into the MultiFileReader through the table function

This is useful when you want to implement `ATTACH` on a delta tables:

The `GetScanFunction` for the tableentry can then store additional information (for example a DeltaSnapshot object) in the `shared_ptr<TableFunctionInfo> TableFunction::function_info;` which the delta extension can then store in the multifilereader. This allows pinning a delta snapshot during a transaction.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

> The GetScanFunction for the tableentry can then store additional information (for example a DeltaSnapshot object) in the shared_ptr<TableFunctionInfo> TableFunction::function_info; which the delta extension can then store in the multifilereader. This allows pinning a delta snapshot during a transaction.

Am I reading this right that this passes in a `const TableFunction`, but we then modify one of the members of the `TableFunction`?

**Comment by samansmink** [comment]
No the idea is that we inject some extra info in the TableFunction object we get: https://github.com/samansmink/duckdb_delta/blob/03ed79b2d49fcef28eab9081d28b8105f51f8fb6/src/storage/delta_table_entry.cpp#L44

Then later, the parquet scan calls back into delta like this https://github.com/samansmink/duckdb_delta/blob/03ed79b2d49fcef28eab9081d28b8105f51f8fb6/src/functions/delta_scan.cpp#L550

**Comment by Mytherin** [comment]
Thanks, makes sense after discussion - good to go from my side after CI passes

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
