### PR TITLE
Add `map_concat` function

### PR DESCRIPTION
**Pull request by Tishj**
This PR adds the `map_concat` function, as described here: #1466

This also fixes a bug in `map` that was introduced in the rework of the internal Vector representation of a MAP type.
Essentially we were using the wrong selection vector

### CODE REVIEW

**Comment by pdet** [comment]
cc: @cpcloud

**Comment by Mytherin** [comment]
Thanks! LGTM

**Comment by blacelle** [comment]
Though https://github.com/duckdb/duckdb/issues/1466 is closed, is this live? If yes, should it be referenced in https://duckdb.org/docs/sql/functions/map.html?

**Comment by Mytherin** [comment]
Yes, this is implemented

**Pull request merged**
