### PR TITLE
[Catalog] Improve error message on catalog-qualified catalog-entry lookup

### LINKED ISSUE #6906: Cannot use qualified table name with pragma_storage_info
### What happens?

Calling `pragma_storage_info` with qualified table name, that is, with the database prepended, fails saying that the table doesn't exist.

### To Reproduce

```
$ ./build/release/duckdb
v0.7.2-dev1244 ab5c07cb68
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D ATTACH '/tmp/database.db' as persistent;
D CREATE TABLE persistent.T1 (A0 int);
D select * from duckdb_tables();
┌───────────────┬──────────────┬─────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬─────────────────┬────────────────┬──────────────┬─────────────┬──────────────────────┬───────────────────────────────┐
│ database_name │ database_oid │ schema_name │ schema_oid │ table_name │ table_oid │ internal │ temporary │ has_primary_key │ estimated_size │ column_count │ index_count │ check_constraint_c…  │              sql              │
│    varchar    │    int64     │   varchar   │   int64    │  varchar   │   int64   │ boolean  │  boolean  │     boolean     │     int64      │    int64     │    int64    │        int64         │            varchar            │
├───────────────┼──────────────┼─────────────┼────────────┼────────────┼───────────┼──────────┼───────────┼─────────────────┼────────────────┼──────────────┼─────────────┼──────────────────────┼───────────────────────────────┤
│ persistent    │          968 │ main        │        966 │ T1         │       970 │ false    │ false     │ false           │              0 │            1 │           0 │                    0 │ CREATE TABLE "T1"("A0" INTE…  │
└───────────────┴──────────────┴─────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴─────────────────┴────────────────┴──────────────┴─────────────┴──────────────────────┴───────────────────────────────┘
D SELECT (COUNT(DISTINCT block_id) * 262144) as size from pragma_storage_info('persistent.T1');
Error: Catalog Error: Table with name T1 does not exist!
Did you mean "persistent.T1"?
D SELECT (COUNT(DISTINCT block_id) * 262144) as size from pragma_storage_info('T1');
Error: Catalog Error: Table with name T1 does not exist!
Did you mean "persistent.T1"?
D select * from persistent.T1;
┌────────┐
│   A0   │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
```

### OS:

MacOS

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI, JDBC

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes #6906 

Our QualifiedName struct parses 2 part names as `schema.name`, which causes us to look for `main.schema.name` which doesn't exist.
The error message then suggests us to do exactly what we're already doing.

PR #5764 introduced the functionality that allows us to disambiguate this, but when first parsed as a QualifiedName, we lose this ability because the decision already gets made.

### CODE REVIEW

**Comment by Tishj** [comment]
@Mytherin 
This probably isn't the right fix, but I wasn't sure how to handle this ambiguity.
Maybe we should instead store the ambiguity in the QualifiedName and allow passing the QualifiedName to Catalog::GetEntry directly - so we can read this flag

**Comment by Mytherin** [comment]
I think the issue here is actually that `pragma_storage_info('persistent.T1')` does not work. When doing table lookups we allow for both `schema.table` and `catalog.table` as long as there is no ambiguity - `pragma_storage_info` is likely taking a different code path which causes this to not work.

**Comment by Mytherin** [comment]
The issue is that `Binder::BindSchemaOrCatalog` is not being called in `pragma_storage_info`. We should probably move that out of the binder and into the catalog and call it here as well.

**Comment by Mytherin** [comment]
Ah no we can already call it - see [pragma_table_info](https://github.com/duckdb/duckdb/blob/ab5c07cb689d2b899b6abf738284baeae6ba0046/src/function/table/system/pragma_table_info.cpp#L56). That one line fix should be all that is required here

**Comment by Tishj** [comment]
I really hate git sometimes..
I `git checkout master -- .` and it messes up LinuxRelease.yml - I never touched that 🙃

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
