### PR TITLE
Add pragma extension versions

### PR DESCRIPTION
**Pull request by samansmink**
The problem is that its not always easy for a user to determine which extensions are involved in a bug. Additionally, release cycles of extensions are increasingly out of sync with DuckDB. Therefore I think we can improve the quality of our bugreports asking every user for the all extension versions along with the duckdb version. To make this easy to read for us I think we can just ask users to run a few pragmas and paste the output in a code block. This will provide us with:
- platform
- duckdb version
- extension
    - version
    - repo (core, core_nightly, community, custom)
    - statically linked/dynamically loaded 

Basically with this PR, we can ask for users to run the following three pragmas to get all relevant info for a bug report:

```SQL
 pragma platform;
 pragma version;
 pragma extension_versions;
 ```
 In my case:
 ```
 ┌───────────┐
│ platform  │
│  varchar  │
├───────────┤
│ osx_arm64 │
└───────────┘
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v1.0.1-dev2991  │ 85a82d86aa │
└─────────────────┴────────────┘
┌────────────────┬───────────────────┬───────────────────┬────────────────┐
│ extension_name │ extension_version │   install_mode    │ installed_from │
│    varchar     │      varchar      │      varchar      │    varchar     │
├────────────────┼───────────────────┼───────────────────┼────────────────┤
│ httpfs         │ 85a82d86aa        │ STATICALLY_LINKED │                │
│ parquet        │ 85a82d86aa        │ STATICALLY_LINKED │                │
│ shell          │                   │ STATICALLY_LINKED │                │
└────────────────┴───────────────────┴───────────────────┴────────────────┘
```

Asking this ahead of any bugreports will allow us to quickly determine what version the bugreport was on. Additionally, our bug report template should probably ask to run `UPDATE EXTENSIONS`. I can pick this up with @szarnyasg as followup.

An even cooler follow-up would be to have a `CREATE BUGREPORT` statement in DuckDB that prefills all these fields by automatically opening your browser with this info prefilled.

### CODE REVIEW

**Comment by carlopi** [comment]
Would it not make more sense to have a single pragma return a table of facts about state of ducdkb?

I tough about something like:
```
PRAGMA duckdb_status
```

| item | kind | version | field 1 | field 2 | field 3 |
|--|--|--|--|--|--|
| duckdb | main library | 85a82d86aa | v1.0.1-dev2991 | osx_arm64 | |
| python | user-agent |  | | | 
| httpfs | extension | 85a82d86aa |  static |  | |
| fts | extension | 85a82d86aa | loaded | repo: build/release/repository | |

Idea is that it's a single table (= can be copied as CSV / else) + we can add more fields as we see necessary.

Unsure how to name the extra fields to allow flexibiltiy.

This do not exclude ` pragma extension_versions;` per se, but I think it would make sense to have.

**Comment by samansmink** [comment]
@carlopi That was my original idea, but I thought it would get kind of messy with either a lot of empty columns or poorly named columns

**Comment by Tishj** [comment]
It could also be a MultiStatement, running multiple individual queries, then everything is still somewhat bundled but you don't get horizontal explosion and unrelated column names

**Comment by carlopi** [comment]
I played around SQL and got this:
```sql
SELECT * EXCLUDE (prio) FROM(
    FROM (select extension_name as name, 'extension' as kind, extension_version as 'version', case when loaded then 'loaded, ' else '' end || case when install_mode != 'REPOSITORY' AND install_mode != 'CUSTOM' then lower(install_mode) else lower(install_mode) || ' from ' || installed_from  end as extra_info, case when loaded then 4 else 5 end as prio from duckdb_extensions() where installed)
    UNION ALL
    FROM (SELECT 'duckdb' as name, 'main_library' as kind, library_version as version, user_agent || ' | ' || source_id || ' | '||platform, 0 as prio FROM pragma_version(), pragma_platform(), pragma_user_agent())
    UNION BY NAME
    FROM (SELECT 'threads' as name, 'setting' as kind, current_setting('threads') AS extra_info, 2 as prio)
    UNION BY NAME
    FROM (SELECT 'memory_limit' as name, 'setting' as kind, current_setting('memory_limit') as extra_info, 2 as prio)
    ORDER BY prio, extra_info, name);
```
that returns:
```
┌──────────────────────┬──────────────┬────────────┬─────────────────────────────────────────────────────────┐
│         name         │     kind     │  version   │                       extra_info                        │
│       varchar        │   varchar    │  varchar   │                         varchar                         │
├──────────────────────┼──────────────┼────────────┼─────────────────────────────────────────────────────────┤
│ duckdb               │ main_library │ v1.0.0     │ duckdb/v1.0.0(osx_arm64) cli | 1f98600c2c | osx_arm64   │
│ memory_limit         │ setting      │            │ 12.7 GiB                                                │
│ threads              │ setting      │            │ 8                                                       │
│ h3                   │ extension    │ 8f2ebc1    │ loaded, repository from community                       │
│ delta                │ extension    │ a2d6601    │ loaded, repository from core                            │
│ iceberg              │ extension    │ fe04716    │ loaded, repository from core                            │
│ tpch                 │ extension    │ 1f98600c2c │ loaded, repository from core                            │
│ autocomplete         │ extension    │            │ loaded, statically_linked                               │
│ icu                  │ extension    │ 1f98600c2c │ loaded, statically_linked                               │
│ json                 │ extension    │ 1f98600c2c │ loaded, statically_linked                               │
│ parquet              │ extension    │ 1f98600c2c │ loaded, statically_linked                               │
│ shell                │ extension    │            │ loaded, statically_linked                               │
│ dynamic_sql_examples │ extension    │ 2675cc8    │ repository from build/release/repository                │
│ duckpgq              │ extension    │ 6c06589    │ repository from community                               │
│ quack                │ extension    │ 09680a9    │ repository from community                               │
│ scrooge              │ extension    │ fc7ef9c    │ repository from community                               │
│ shellfs              │ extension    │ d01c73d    │ repository from community                               │
│ excel                │ extension    │ 391b36d    │ repository from core                                    │
│ fts                  │ extension    │ 1f98600c2c │ repository from core                                    │
│ httpfs               │ extension    │ 1f98600c2c │ repository from core                                    │
│ inet                 │ extension    │ 1f98600c2c │ repository from core                                    │
│ mysql_scanner        │ extension    │ 4dd5963    │ repository from core                                    │
│ postgres_scanner     │ extension    │ 120c0b1    │ repository from core                                    │
│ sqlsmith             │ extension    │ 1f98600c2c │ repository from core                                    │
│ vss                  │ extension    │ 690bfc5    │ repository from core                                    │
│ prql                 │ extension    │ v0.0.19    │ repository from https://community-extensions.duckdb.org │
├──────────────────────┴──────────────┴────────────┴─────────────────────────────────────────────────────────┤
│ ? rows                                                                                          4 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

I'd say we probably want to have both the extension only (this PR) and a general one built on top that does UNION ALL of other PRAGMAs, so it's more composable.

---

One thing that touches this PR: would it make sense to go from install_mode / install_from fields to a line with text that encodes the same info in a readable way (see the example, but I am not sure the logic is complete) ?

Reasoning is: easier to compose with other info-generating pragma if it's just a VARCHAR `info` field, and can be expanded / adapted (say we might want to add fit other informations here, like whether is loaded or not), and can be made more user friendly (say if statically_linked it doesn't need to say where is from / with basically the `duckdb_extensions()` keeping the source of truth and this translating to more user-friendly language).

**Comment by Mytherin** [comment]
Looks good from my side - only the format CI is failing.

**Pull request merged**
