### PR TITLE
WASM hello world test

### PR DESCRIPTION
**Pull request by ankoh**
This PR adds a first hello world WASM test.
The scripts take care of the emsdk setup and compile the amalgamation build.

More precisely:
- `./scripts/wasm_configure.sh` prepares the emscripten sdk in .wasm/emsdk
- `./scripts/wasm_build_lib.sh` compiles the amalgamation build in .wasm/build
- `./scripts/wasm_build_test.sh` compiles a hello world test module
- `node ./test/wasm/hello_wasm_test.js` with a recent enough node will run the test

The concurrentqueue is still causing some trouble at the moment.
This PR also adds `/include/duckdb/parallel/concurrentqueue.hpp` that acts as simple stub in case DUCKDB_NO_THREADS is set.
This patches the recent queue references in the buffer_manager.
The other user of concurrentqueue is the task_scheduler that has its own stub at the moment.
If you're ok with it, I can replace that as well.

This PR still lacks the GitHub action.
I'll add it here if you want to merge the scripts upstream.
In the long run, this should totally be part of a dedicated CMakelists but bash would suffice for the CI for now.

Note that the single wasm build is very slow (single threaded, ~10 min).
Compiling the test will add a few more minutes.
The output of the test should be the following:
```
> node test/wasm/hello_wasm_test.js
Hello from WASM
expected 50005000, received 50005000
result ok
```

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Yeah let’s add a GH action immediately!

**Comment by hannesmuehleisen** [comment]
Great, it passed. Cloud you please also add a `depends:` entry to the WASM build step? This ensures it only runs when the basic build succeeds, which keeps the amount of builds down for hopeless cases. Will merge afterwards.

**Comment by hannesmuehleisen** [comment]
Hooray its a merge!

**Comment by hannesmuehleisen** [comment]
I'm going to run another PR where we add the resulting JS file for the lib to the build artefacts and release "binaries"

**Comment by ankoh** [comment]
Awesome!

Two notes here though:
The generated JS is actually less relevant since it is specific to the hello world test.
The only file that is useful is the library module `.wasm/build/duckdb.o`.
But right now, the script compiles the module with `-O2 -g` which results in 84M of mostly debug symbols.
Without debug symbols, however, it will be very hard to figure out what went wrong when the node test crashes.
Debugging WASM is still a nightmare since there's not enough tooling out there yet.

We are also interested in a wasm that we can grab directly from your releases but then it should probably a dedicated build with O3 and without -g.

**Comment by ankoh** [comment]
I can just parameterise the bash script up there and add a dedicated build for the release artefact if you want.

**Comment by domoritz** [comment]
> I can just parameterise the bash script up there and add a dedicated build for the release artefact if you want.

That would be awesome. I also found that https://github.com/WebAssembly/binaryen#wasm-opt often removes unused code so it could make sense to run it over the wasm output as well (if emscripten doesn't do that already).

**Comment by hannesmuehleisen** [comment]
> build for the release artefact if you want.

Yeah lets

**Comment by ankoh** [comment]
@domoritz Emscripten runs a very aggressive DCE when generating the final javascript module. Everything that is not reachable by functions specified in EXPORTED_FUNCTIONS (https://github.com/cwida/duckdb/blob/master/scripts/wasm_build_test.sh#L31) is stripped from the output.
But that also means that the process of actually using this release artefact is actually fairly messy right now unless you are using emscripten yourself.
You can just link the duckdb.o in an existing emscripten build but very likely won't be able to, for example, link it with wasm32-unknown-unknown modules of rust.
At least I don't expect that to work out of the box.

You can find a decent amount of information on the current problem in this post here: https://stackoverflow.com/questions/46258900/linkerror-when-trying-hello-world-in-rust-with-webassembly

In the end, DuckDB just needs a JS-affine FFI interface that solves some of the annoying js interop problems.

**Comment by hannesmuehleisen** [comment]
You could export the C API by default?

**Comment by ankoh** [comment]
Yes, that is what the sql.js people do after all.
But the js<->wasm interop is not exactly cheap so a functioncall-per-attribute-per-row api has a tremendous overhead.
We played around with this a little bit and WASM pretty much forces you to map the DuckDB vectors to javascript NativeArrays (Uint8Array, Uint32Array, Float32Array, ...).
We're talking about a difference of < 1 MB/s vs 500 MB/s when reading larger result tables.

**Comment by domoritz** [comment]
Can you provide views into the native arrays? I was able to get pretty good performance when I did this in https://github.com/domoritz/arrow-wasm.

**Comment by ankoh** [comment]
Yes, I saw your repository already, cool work! :+1:
You can just create referencing native arrays on top of the WASM memory.
Even a plain copy of the respective WASM memory wont hurt too much as long as you're consuming the output in a column-major fashion with native arrays.

**Comment by domoritz** [comment]
Ahh, I misread your comment. I now understand it as that perf is bad if one uses the per row API but when using the column major API, perf is good.

**Comment by ankoh** [comment]
For the record, linking the prebuilt wasm library works like a charm now.
Here an example:

```
# Load duckdb.wasm archive
include(FetchContent)
FetchContent_Declare(
    duckdb_wasm
    URL "https://github.com/dashql/duckdb/releases/download/0.2.4.1/duckdb-wasm32-nothreads.zip"
    URL_HASH "SHA256=1ac85c1e2e7fadcd86a5a3befff87aae2d1d2ad615d664e2228357777ff8a2a9"
)
FetchContent_GetProperties(duckdb_wasm)
if(NOT duckdb_wasm_POPULATED)
    FetchContent_Populate(duckdb_wasm)
endif()

# Add command to extract the archive
set(DUCKDB_WASM_ARCHIVE ${duckdb_wasm_SOURCE_DIR}/duckdb-wasm32-nothreads.zip)
set(DUCKDB_WASM_OUT ${CMAKE_BINARY_DIR}/duckdb.wasm)
add_custom_target(
    duckdb_wasm
    COMMAND ${CMAKE_COMMAND} -E remove ${DUCKDB_WASM_OUT}
    COMMAND ${CMAKE_COMMAND} -E tar xvz ${DUCKDB_WASM_ARCHIVE}
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

# Add library
add_library(duckdb INTERFACE)
add_dependencies(duckdb duckdb_wasm)
target_compile_options(duckdb INTERFACE -DDUCKDB_NO_THREADS=1)
target_link_libraries(duckdb INTERFACE ${CMAKE_BINARY_DIR}/duckdb.wasm)
```

**Comment by Alex-Monahan** [comment]
I am hoping to do some WASM testing this weekend! However, I am struggling to find a full example. What is the full process to get WASM up and running? Do I need to compile from source, or are there pre-compiled files? 

I tried to follow test/wasm/hello_wasm_test.js, but I could not find this file that it references: require('../../.wasm/build/hello_wasm.js'). 

I may also try to run this in a shared worker - has anyone done that just yet? Any advice if that is a good idea?

**Comment by Alex-Monahan** [comment]
As an update, I realized that I would need to run a few build steps to do this today. I'm on Windows, and I'm a Python/JS/SQL developer. Is there a way to do this without having to do any C++ compilation? I've used sql.js and it didn't require any build steps. Thank you for your help!

**Comment by ankoh** [comment]
@Alex-Monahan This still requires you to build the module yourself. Here's a cmake snippet that shows how we integrate the prebuilt wasm into our project right now.

```
# Load duckdb.wasm archive
include(FetchContent)
FetchContent_Declare(
    duckdb_wasm
    URL "https://github.com/dashql/duckdb/releases/download/0.2.4.1/duckdb-wasm32-nothreads.zip"
    URL_HASH "SHA256=1ac85c1e2e7fadcd86a5a3befff87aae2d1d2ad615d664e2228357777ff8a2a9"
)
FetchContent_GetProperties(duckdb_wasm)
if(NOT duckdb_wasm_POPULATED)
    FetchContent_Populate(duckdb_wasm)
endif()

# Command to extract archive
set(DUCKDB_WASM_ARCHIVE ${duckdb_wasm_SOURCE_DIR}/duckdb-wasm32-nothreads.zip)
set(DUCKDB_WASM_OUT ${CMAKE_BINARY_DIR}/duckdb.wasm)
add_custom_target(
    duckdb_wasm
    COMMAND ${CMAKE_COMMAND} -E remove ${DUCKDB_WASM_OUT}
    COMMAND ${CMAKE_COMMAND} -E tar xvz ${DUCKDB_WASM_ARCHIVE}
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

# Interface library to link prebuilt wasm
add_library(duckdb INTERFACE)
add_dependencies(duckdb duckdb_wasm)
target_compile_options(duckdb INTERFACE -DDUCKDB_NO_THREADS=1)
target_link_libraries(duckdb INTERFACE ${CMAKE_BINARY_DIR}/duckdb.wasm)
```

**Comment by Alex-Monahan** [comment]
Thanks, I will try to learn a bit about that and give it a shot! 

I had one other thought - have you experimented with sending a DuckDB instance straight over the network and just converting that binary blob into a DuckDB instance on the JS/WASM side? I did that with SQL.js as well where we just streamed a SQLite db straight from our server. That could help with larger DB's!

**Comment by domoritz** [comment]
I think parquet would work even better since it can be compressed efficiently.

**Comment by Alex-Monahan** [comment]
We have an option for a parquet endpoint on our API as well, so we could do that for sure! I can experiment with that, but if anyone gets that working in browser, that would be great to share.

**Pull request merged**
