### PR TITLE
Allow to explicitly set the version via DUCKDB_EXPLICIT_VERSION

### PR DESCRIPTION
**Pull request by xhochy**
This is needed if you build duckdb from a git version tarball. Then no version can be determined through git.

### CODE REVIEW

**Comment by xhochy** [comment]
Context of this change was that I needed to set the version in https://github.com/conda-forge/duckdb-split-feedstock/pull/2 For Linux, it used the fallback 0.0.1 version but the build failed on OSX as `git` was available but we were not in a git repository and thus `DUCKDB_VERSION` got set to "" which lead to other issues in the build.

**Comment by carlopi** [comment]
This makes a lot of sense in general, currently there are a few cases where we rely on git (= full history with tags available) where a single snapshot in time + explicit GIT_COMMIT_HASH and DUCKDB_EXPLICIT_VERSION would be enough.

I would consider doing this a couple of steps earlier in the cmake logic, structuring it like:
```
ifndef GIT_COMMIT_HASH
   -> ask git, set GIT_COMMIT_HASH
fi
ifndef DUCKDB_EXPLICIT_VERSION
    -> ask git, set DUCKDB_VERSION
else
    -> set DUCKDB_VERSION equal to DUCKDB_EXPLICIT_VERSION
fi
decide if release (folder is v0.x.y) or not (folder is the git hash)
```

This would make this work also for non releases in the same way, since otherwise there are a bunch of corner-cases where its' not true any more the assumption that both GIT_COMMIT_HASH and DUCKDB_VERSION are set properly, and I think it's also a better way to structure the code.

Would you be open to send this change?

**Comment by carlopi** [comment]
To test this (at least locally), goal would be having a way to set `PRAGMA version` and `PRAGMA user_agent` to the right values (both for releases and not) while passing values externally.

**Comment by xhochy** [comment]
I'm a bit confused here as I don't see the difference to what I have implemented. It seems like it would mainly mean skipping the `if(GIT_RESULT EQUAL "0")` block if `DUCKDB_EXPLICIT_VERSION` is already set?

**Comment by carlopi** [comment]
@xhochy: if you have a duckdb binary / library, through SQL you can get two pieces of informations:
```
D PRAGMA version;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v0.10.0         │ 20b1486d11 │
└─────────────────┴────────────┘
```

Both are computed using git describe in the case you are building from a git repository (and have tags properly set).

If the goal is enable distributing duckdb-packages without the use of GIT, both pieces of informations needs to be propagated, and ideally the logic should work both for releases and non-release builds.

I can look at integrating this PR and ideally use this in a couple of CI jobs (and somehow check results make sense / are equivalent).

**Comment by carlopi** [comment]
https://github.com/duckdb/duckdb/pull/10977 landed, that should be an alternative to this PR.
https://github.com/duckdb/duckdb/pull/10994 improves also on that, I think this should cover this PR goal.

I went for a separate PR since the CMake logic around this was not super stable, and adding another special case looked (to me) to add more (potential) corner cases.

Thanks a lot for your contribution! @xhochy: if you have any feedback, both on the code or how this can work on your setup, it would be great.

**Comment by Mytherin** [comment]
@carlopi thinks this should now be addressed on main via the addition of the `OVERLOAD_GIT_DESCRIBE` parameter in https://github.com/duckdb/duckdb/pull/10977. If that isn't the case feel free to re-open.

**Pull request closed without merging**
