### PR TITLE
Issue #7969: Prefer Range Join 

### PR DESCRIPTION
**Pull request by hawkfish**
* Make sure IEJoin is ready for right side projections.
* Add PRAGMA for preferring range joins.
* Disable PRAGMA in benchmark because it doesn't help when the code is correct(!)

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! Looks good to me in principle - but I wonder if this will not regress other queries. Which join is better to use (hash join vs range join) is likely heavily dependent on the selectivity of the join predicates. If the range predicate is non-selective then this will cause large regressions.

Could we run some more benchmarks testing the various scenarios?

Could we also add some more tests that trigger the various projection map scenarios with the IE Join?

**Comment by hawkfish** [comment]
> Thanks for the PR! Looks good to me in principle - but I wonder if this will not regress other queries. Which join is better to use (hash join vs range join) is likely heavily dependent on the selectivity of the join predicates. If the range predicate is non-selective then this will cause large regressions.
> 
> Could we run some more benchmarks testing the various scenarios?

Right now this is behind a pragma that is off by default. It's really just for users to force the issue if perf is terrible.

My thinking on how to make this smarter is to check the selectivity of the equality predicates and switch if they are obviously horrible. We could throw in some estimates from [here](https://arxiv.org/pdf/2206.07396) but they specifically don't work in the common case (intervals) so it would be another vague heuristic. Ideally we would have something sort of smart but extend the pragma to force either way if we guess wrong.

> Could we also add some more tests that trigger the various projection map scenarios with the IE Join?

AFAICT there is only one case here where we remove unused RHS columns so I have added a test for that (just a really small version of the benchmark). All the other cases seemed to be for indexed loop joins and the like.

**Comment by hawkfish** [comment]
Think the only thing that failed was Node download.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
