### PR TITLE
feat(httpfs): custom http header support

### PR DESCRIPTION
**Pull request by Mause**
~~Still working on tests for this - right now it seems like the parser doesn't support nested types in a `SET` call?~~

~~Pointers on where to start with fixing that in the parser would be appreciated.~~

Fixes #5972, #8344, #6782, https://github.com/duckdb/duckdb/discussions/4963

### CODE REVIEW

**Comment by Tishj** [comment]
I think you need to look here to add support for this to SET
https://github.com/duckdb/duckdb/blob/a868375e85b0297c2ad87b29e59463a9f9dac89e/third_party/libpg_query/grammar/statements/variable_set.y#L103

Looks like it only supports numerics, booleans or strings

**Comment by Mause** [comment]
> I think you need to look here to add support for this to SET
> https://github.com/duckdb/duckdb/blob/a868375e85b0297c2ad87b29e59463a9f9dac89e/third_party/libpg_query/grammar/statements/variable_set.y#L103
> 
> Looks like it only supports numerics, booleans or strings
> 
> Maybe it should be an a_expr, and then in transform only accept a ConstantExpression

`a_expr` looks really general? I'm trying out `indirection_expr`, and it seems to be working okay

**Comment by Tishj** [comment]
`indirection_expr` includes `'(' a_expr ')'` as one of its variants

**Comment by Mause** [comment]
> `indirection_expr` includes `'(' a_expr ')'` as one of its variants

Oops, mb

**Comment by hannes** [comment]
LGTM, will merge once tests pass

**Review by hannes — APPROVED** [review]

**Comment by hannes** [comment]
@mause Can you please look at the coverage?

**Review by Mytherin — COMMENTED** [review]
Thanks for the PR! Looks great - could you just have a look at the coverage? Note that coverage only runs the fast tests (i.e. `.test`) and doesn't run HTTPFS tests.

**Comment by ericemc3** [comment]
I guess that what you have in mind is something like:
SET http_headers = MAP {'Authorization': 'Bearer 1WEjMTAEeB8ilbE3TwHZkp2CgMC'};
And it is fine. It would be great.

But what if, in the same query, i need to fetch data from different sources with some requiring authorization, others not?
It would be convenient also to benefit from a new parameter in read_csv(), read_json_auto(), such as:
read_json_auto('....', http_headers={Authorization: 'Bearer 1WEjMTAEeB8ilbE3TwHZkp2CgMC'})

**Comment by ericemc3** [comment]
> > I guess that what you have in mind is something like: SET http_headers = MAP {'Authorization': 'Bearer 1WEjMTAEeB8ilbE3TwHZkp2CgMC'}; And it is fine. It would be great.
> > But what if, in the same query, i need to fetch data from different sources with some requiring authorization, others not? It would be convenient also to benefit from a new parameter in read_csv(), read_json_auto(), such as: read_json_auto('....', http_headers={Authorization: 'Bearer 1WEjMTAEeB8ilbE3TwHZkp2CgMC'})
> 
> We can definitely look at adding that feature in the future, but for now, I want to get it working and in

Of course, i understand. Thanks for your hard work!

**Comment by Mytherin** [comment]
Could you merge this with feature?

**Comment by Mause** [comment]
It was rendered invalid with the new secret functionality - it should be rewritten based on that instead

**Pull request closed without merging**
