### PR TITLE
impl gen_random_uuid function

### PR DESCRIPTION
**Pull request by wangfenjin**
This implementation is adapted from https://github.com/graeme-hill/crossguid

address #2343

### CODE REVIEW

**Comment by wangfenjin** [comment]
@Mytherin For linux it will requires uuid-dev be installed, do you think we can add the dependency in github-actions?

**Comment by Mytherin** [comment]
Thanks for the PR!

Unfortunately, we have a very strict no external dependencies policy, so as-is this PR cannot be merged. See [here](https://github.com/duckdb/duckdb/issues/97#issuecomment-516816980) for some rationale behind that decision.

Can we implement this function without the dependency? It seems like that [should be possible](https://stackoverflow.com/questions/24365331/how-can-i-generate-uuid-in-c-without-using-boost-library/58467162) without too much problems.

**Comment by Mytherin** [comment]
We can also [use this implementation here](https://github.com/mariusbancila/stduuid/blob/4959d46eb494f8eddd4a37a1c8c6434b41d56ca8/include/uuid.h#L713) and adopt it to use our own random number generator (`context.random_engine`).

**Comment by wangfenjin** [comment]
OK I'll close this PR and generate the uuid by ourselves

**Pull request closed without merging**
