### PR TITLE
doc(nodejs): amend arrow stream type docs

### PR DESCRIPTION
**Pull request by Mause**
Once this is merged, we should be able to update the tests in the https://github.com/duckdblabs/arrow repo to typescript

### CODE REVIEW

**Comment by Mause** [comment]
@antonycourtney again, would be great if you could review this 😁

**Review by antonycourtney — APPROVED** [review]
This change looks good to me!

A few thoughts, none of them blocking:
1. Should the type name `ArrowBuffer` perhaps be `ArrowIterable`?  
2. Ideally basic tests for the new API points could be part of the same PR.
3. We should also update `duckdb-async` with support for this!  PR welcome there. 🙂
Hopefully we can upstream `duckdb-async` soon so it's easier to keep them in sync. In the meantime, of course, makes sense to land this change here first.

**Comment by Mause** [comment]
1. good suggestion, done
2. none of these functions are new in this pr, they're all tested over in the arrow extension repository. I'll update them to consume these types next though
3. I've been looking into what would be required for the c++ bindings to natively support both callbacks and promises, and it doesn't look unreasonably difficult. I'll probably look at submitting a pr in the coming days to update the new arrow functions, as they are the newest and least likely to cause breakage with change

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
