### PR TITLE
Unskip, attach HTTPFS test, and create HTTPState when the opener is not available

### LINKED ISSUE #7998: Can't attach a remote database in 0.8.1
### What happens?

I can't attach a remote database.

Although it was added in 0.7.0 with https://github.com/duckdb/duckdb/pull/6141

But the tests was skipped in https://github.com/duckdb/duckdb/pull/6141

Related to https://github.com/duckdb/duckdb/discussions/7781

### To Reproduce

I created a database using duckdb 0.8.1 with a fts index and hosted on Hugging Face (also fails without fts)

Now running this code fails:
```
LOAD httpfs;
LOAD fts;
ATTACH 'https://huggingface.co/datasets/lhoestq/remote-duckdb/resolve/main/test-fts-0.8.1.duckdb';
```
It raises:
```
Error: Invalid Error: INTERNAL Error: State was not defined in this HTTP File Handle
```

### OS:

MacOS (macbook pro m2)

### DuckDB Version:

0.8.1

### DuckDB Client:

python, brew

### Full Name:

Quentin Lhoest

### Affiliation:

Hugging Face

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by pdet**
fix: #7998

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR! The reason the test is skipped is that the test will fail if the storage version is upgraded and I found no good alternative to that problem. I discussed with @samansmink at some point about uploading a database file into the minio server but did not have time to pursue that.

**Comment by carlopi** [comment]
I am touching similar code in https://github.com/duckdb/duckdb/blob/master/.github/workflows/Regression.yml#L240 where I test storage compatibility, could then this test be run hand-rolled there in the branch where compatibility is expected ?

Or otherwise somehow expose the same logic (check one db, check other db, use difference as proxy of different versions) here.

**Comment by pdet** [comment]
> Thanks for the PR! The reason the test is skipped is that the test will fail if the storage version is upgraded and I found no good alternative to that problem. I discussed with @samansmink at some point about uploading a database file into the minio server but did not have time to pursue that.

I see. That makes sense. I can have a go at the minio server.

**Comment by samansmink** [comment]
@pdet We also upload other test data to the minio server since https://github.com/duckdb/duckdb/pull/6467, we could in a similar way upload a db before the tests i think?

**Review by samansmink — APPROVED** [review]
Lookin good!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
