### PR TITLE
Add support for LATERAL joins

### PR DESCRIPTION
**Pull request by Mytherin**
This PR adds support for LATERAL joins to DuckDB. Lateral joins work by allowing the right-side of a join or cross product to refer to columns on the left-side. For example:

```sql
select * from generate_series(0, 3, 1) t(i), LATERAL (SELECT i + 1) t2(j);
┌───────┬───────┐
│   i   │   j   │
│ int64 │ int64 │
├───────┼───────┤
│     0 │     1 │
│     1 │     2 │
│     2 │     3 │
│     3 │     4 │
└───────┴───────┘
```

This works similar to a correlated scalar subquery - where the sub-query on the right-hand-side is logically executed once for every correlated value. The above code is logically identical to the following:

```sql
select i, (SELECT i + 1) AS j from generate_series(0, 3, 1) t(i);
┌───────┬───────┐
│   i   │   j   │
│ int64 │ int64 │
├───────┼───────┤
│     0 │     1 │
│     1 │     2 │
│     2 │     3 │
│     3 │     4 │
└───────┴───────┘
```

Lateral joins are somewhat of a generalization of correlated subqueries, as they can return *multiple* values per input value rather than only a single value, for example:

```sql
select * from generate_series(0, 1, 1) t(i), LATERAL (SELECT i + 10 UNION ALL SELECT i + 100) t2(j);
┌───────┬───────┐
│   i   │   j   │
│ int64 │ int64 │
├───────┼───────┤
│     0 │    10 │
│     1 │    11 │
│     0 │   100 │
│     1 │   101 │
└───────┴───────┘
```

In this case the lateral join returns two rows per input value (`i + 10` and `i + 100`), and the result has twice as many rows with the left-hand side duplicated per input row.

## LATERAL syntax

In Postgres, the explicit `LATERAL` syntax is required in order to perform a lateral join. Leaving out the `LATERAL` syntax results in an error being thrown:

```sql
myth=# select * from generate_series(0, 3, 1) t(i), (SELECT i + 1) t2(j);
ERROR:  column "i" does not exist
LINE 1: ...ect * from generate_series(0, 3, 1) t(i), (SELECT i + 1) t2(...
                                                             ^
HINT:  There is a column named "i" in table "t", but it cannot be referenced from this part of the query.
```

As this syntax is not strictly required - and the system can detect whether or not a join is a lateral join by looking at which columns have been bound - we have opted to make the `LATERAL` syntax optional. The following query will run in DuckDB - the system will implicitly convert this into a LATERAL join:

```sql
SELECT * FROM (SELECT 42) t(i), (SELECT i * 2) t2(j);
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘
```

## Current Restrictions

* Nested lateral joins or mixing of lateral joins with correlated subqueries are not yet supported. That means the following query does not yet work:

```sql
SELECT * FROM (SELECT 42) t(i), (SELECT * FROM (SELECT 142 k) t3(k), (SELECT k+i) t4(l)) t2(j);
# Binder Error: Nested lateral joins are not supported yet
```

Chains of lateral joins are supported, so the following does work:

```sql
D SELECT * FROM (SELECT 42) t(i), (SELECT i * 2) t2(j), (SELECT i + j) t3(k);
┌───────┬───────┬───────┐
│   i   │   j   │   k   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│    42 │    84 │   126 │
└───────┴───────┴───────┘
```

* Table in-out functions do not yet work with lateral joins (or correlated subqueries in general) - this is a restriction that has to do with how the table-in-out functions are implemented and how that interfaces with the handling of correlated columns.

That means the following does not yet work:

```sql
SELECT * FROM (SELECT ARRAY[1, 2, 3]) t(i), LATERAL unnest(i);
-- Error: Not implemented Error: LATERAL not implemented
```

And neither does the following:
```sql
D SELECT * FROM (SELECT ARRAY[1, 2, 3]) t(i), (SELECT * FROM unnest(i));
Error: Binder Error: Table-in table-out functions not (yet) supported in correlated subqueries
```

For `UNNEST` you can use `(SELECT UNNEST(x))` subquery as a work-around for now:

```sql
D SELECT * FROM (SELECT ARRAY[1, 2, 3]) t(i), (SELECT UNNEST(i));
┌───────────┬───────────┐
│     i     │ unnest(i) │
│  int32[]  │   int32   │
├───────────┼───────────┤
│ [1, 2, 3] │         3 │
│ [1, 2, 3] │         2 │
│ [1, 2, 3] │         1 │
└───────────┴───────────┘
```

For `GENERATE_SERIES`/`RANGE`, you can use unnest together with the scalar `generate_series` query:

```sql
D SELECT * FROM (SELECT 5) t(i), (SELECT UNNEST(range(i))) t2(k) ORDER BY k;
┌───────┬───────┐
│   i   │   k   │
│ int32 │ int64 │
├───────┼───────┤
│     5 │     0 │
│     5 │     1 │
│     5 │     2 │
│     5 │     3 │
│     5 │     4 │
└───────┴───────┘

```

### CODE REVIEW

**Comment by lloydtabb** [comment]
Adding a comment so I can watch this.

**Comment by Alex-Monahan** [comment]
This is awesome! ~2 days to lateral joins???Amazing! Lots of SQLite fans will be excited, and I'm looking forward to the json each possibilities!!

**Comment by lnkuiper** [comment]
This is awesome! So, does this open up the door to using column references as parameters to table functions? Like Alex says, `json_each` or `select i, range from tbl_with_i, range(i)`?

**Comment by Mytherin** [comment]
> This is awesome! So, does this open up the door to using column references as parameters to table functions? Like Alex says, `json_each` or `select i, range from tbl_with_i, range(i)`?

Not yet, but that’s one of the next steps, see the PR description

**Pull request merged**
