### PR TITLE
CSV Parallel Tests CI

### PR DESCRIPTION
**Pull request by pdet**
This PR fixes nightly issues with the CI running the Parallel CSV Tests.

The parallel CSV tests basically run all csv files we have in DuckDB under a variety of configurations to stress test the parallel reader.

These configurations are quite extreme (as in, small buffers) which can make the parsing process very slow. Particularly in CIs that run DuckDB with any debug flags (e.g., No Strings Inline).

In this PR, I skip these tests if the `DUCKDB_RUN_PARALLEL_CSV_TESTS` environmental variable is not set. And add it to `Linux (x64)` CI.

These tests have also been silently failing due to a bug in the assertions, this is now fixed.

Some of the files are also currently breaking, which I've added to the skipping mechanism. A lot of these files have already been corrected in the PR #8852 and the remaining will be corrected as soon as #8852 is merged.

### CODE REVIEW

**Review by carlopi — APPROVED** [review]

**Comment by carlopi** [comment]
Only potential improvement that I see might be worth doing is documenting the behaviour of DUCKDB_RUN_PARALLEL_CSV_TESTS, maybe in a test/README.md or elsewhere.

**Comment by pdet** [comment]
> Only potential improvement that I see might be worth doing is documenting the behavior of DUCKDB_RUN_PARALLEL_CSV_TESTS, maybe in a test/README.md or elsewhere.

I thought about creating a special char to run these (as we have `[.]` instead of adding an env variable, but it seemed an overkill), I'm happy to add it to the readme.

**Comment by pdet** [comment]
@Mytherin, is this good to go?

**Comment by Mytherin** [comment]
Yes LGTM

**Pull request merged**
