### PR TITLE
[Jdbc] use gradle to build jdbc

### PR DESCRIPTION
**Pull request by jimexist**
## Motivation

CMake is perfect for C++ projects, but for a non-trivial Java project that span multiple files, gradle / maven is the right tool. We should set up this earlier to allow more developers to join efforts on JDBC and more Java-rick APIs.

### use gradle wrapper to setup gradle

Using [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) is the easiest and most convenient way to setup in both CI and dev machine.

To make sure the `.jar` binary file is free from malicious code, [gradle wrapper validator](https://github.com/marketplace/actions/gradle-wrapper-validation#usage) is used in CI to guard its integrity.

### use gradle to build jar file and generate JNI headers

`javah` is now deprecated. To generate headers, one should use `-h` flag of `javac`, this is demonstrated as the `compileJava` task in the gradle build file.

### incorporate gradle workflow into the original CMake procedures

Existing `CMake` procedure uses `javac`, `jar`, etc. raw commands, which is fine. But using gradle can simplify further configurations so that future work can happen more naturally for Java background developers.

For examples, consider these tasks:
- publishing sources jar and javadoc jar
- using [maven artifact classifier](https://www.baeldung.com/maven-artifact-classifiers) to product multiple os-arch dependent jars so the final uber jar can be split into smaller ones for downstream to use
- enforce a consistent formatting style using [Google Java Format](https://github.com/google/google-java-format) and [Spotless plugin](https://github.com/diffplug/spotless)
- adopt more unit tests (and parallel runs) beyond just one big `.class` test run
- use mocking libraries like mockito 5
- consider introducing a more object oriented API and Kotlin support
- support for more complex java compilation setup, e.g. multiple Java versions and `-release` flag

### configure maven publish plugin and version detection logic

This is more naturally done via gradle and its maven plugin, than a script.

### CODE REVIEW

**Comment by manticore-projects** [comment]
Greetings,

great work and I am very interested in this (although I am just a user, not a developer).
A few thoughts from my end:

1) maybe use (traditional) Groovy DSL instead of the Kotlin DSL
2) maybe check if [UPX](https://upx.github.io/) is available and then compress the Native Binaries before packing it into the JAR. UPX reduces the size of the Binary by more than 50% here.
3) I would not remove the finalizers, maybe in a second PR
4) I did not see any `publishing` task for deployment? How does the Artifact get published to SonaType?

```groovy
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

repositories {
    // Sonatype OSSRH
    maven {
        url = uri('https://s01.oss.sonatype.org/content/repositories/snapshots/')
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'duckdb_jdbc'
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'DuckDB JDBC Driver'
                description = 'A JDBC-Compliant driver for the DuckDB data management system'
                url = 'https://www.duckdb.org'
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://raw.githubusercontent.com/duckdb/duckdb/master/LICENSE'
                    }
                }
                developers {
                    developer {
                        id = 'mra'
                        name = 'Mark Raasveldt'
                        email = 'mark@duckdblabs.com'
                    }
                    developer {
                        id = 'hmu'
                        name = 'Hannes Muehleisen'
                        email = 'hannes@duckdblabs.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/duckdb/duckdb.git'
                    developerConnection = 'scm:git:ssh://github.com:duckdb/duckdb.git'
                    url = 'http://github.com/duckdb/duckdb/tree/master'
                }
            }
        }
    }
    repositories {
        maven {
            name "ossrh"

            def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl= "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials(PasswordCredentials)
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}
```

with private `gradle.properties` like:
```properties
ossrhUsername=.....
ossrhPassword=.....

signing.keyId=(last 8 characters of the key)
signing.password=
signing.secretKeyRingFile=( home folder )/.gnupg/secring.gpg
```

5) maybe derive the Version Number from GIT Tags and Describe in order to avoid touching the Build File every single time
```groovy
def getVersion = { boolean considerSnapshot ->
    int major = 0
    int minor = 0
    int patch = 0
    String commit = ""
    String snapshot = ""
    new ByteArrayOutputStream().withStream { os ->
        exec {
            workingDir "$projectDir"
            args = [
                    "--no-pager"
                    , "describe"
                    , "--tags"
                    , "--always"
                    , "--dirty=-SNAPSHOT"
            ]
            executable "git"
            standardOutput = os
        }
        def matcher = os.toString() =~ /(\d*)\.(\d*)\.(\d*)(-(\d*)-([a-zA-Z\d]*))?/
        matcher.find()

        major = matcher[0][1] as int
        minor = matcher[0][2] as int
        patch = matcher[0][3] as int
        commit = matcher[0][5]

        if (considerSnapshot && os.toString().endsWith("SNAPSHOT")) {
            minor++
            patch = 0
            snapshot =  "-SNAPSHOT"
        }
    }
    return "${major}.${minor}.${patch}${snapshot}"
}
version = getVersion(true)
```

**Comment by manticore-projects** [comment]
One more thing: Do we really need to include the Gradle Wrapper stuff? For some sentimental reason I would always like to recommend to include as little as possible and to trust in the provided/installed Gradle version.

I would exclude `gradle`, `.gradle` and the Wrapper and only check-in `gradle.build` although this was not the hill I would die on.

**Comment by manticore-projects** [comment]
> Hey thanks for the PR, could you maybe expand a bit on why it would be a good idea to switch away from the current workflow? I also see that the PR adds a bunch of tooling and has a lot of changes in the test cases (which should be unrelated to this). Could you provide some more context please?

Over-simplified: Any Java developer (like me) is lost without a Gradle build file and we do not (want to) know how to use CMAKE or MAKE.
Since the JDBC stuff is meant for us, please give us our tools and comfort!

On the more serious side: with a Maven or Gradle File I could just open the project in any IDE. Without that, I am forced working on that JDBC stuff in GEDIT/VIM.

**Comment by Jimexist** [comment]
@manticore-projects thanks for the tips, i have incorporated some of them into the change.

**Comment by Jimexist** [comment]
refer to 
- https://github.com/duckdb/duckdb/pull/7304
instead

**Pull request closed without merging**
