### PR TITLE
add duckdb-httpfs python package

### PR DESCRIPTION
**Pull request by pkit**
- refactor `setup.py`
- add `httpfs_package/setup.py`
- speed up compilation for linux/darwin by using multiprocess
- hack `sdist` to reduce copy/paste amounts...
- add a github action for python3 wheels
- enforce PEP8 where possible

### CODE REVIEW

**Comment by pkit** [comment]
The resulting `*.whl` uses local `site-packages`-based `libssl` installation, which means it should solve #1741

**Comment by Mytherin** [comment]
Thanks for the PR!

This essentially duplicates the `duckdb` package build entirely, and adds a second package that has httpfs enabled, right?

Could this be changed so that the duplicated code is not necessary? Perhaps we could read extra extensions from parameters to the main setup.py script (e.g. `python3 setup.py install --httpfs`), and add OpenSSL linking only if httpfs is enabled?

I would also like to see the refactor in a separate PR if possible. Adding features while refactoring makes reviewing difficult, especially as the refactor seems quite involved.

**Comment by pkit** [comment]
> Could this be changed so that the duplicated code is not necessary? Perhaps we could read extra extensions from parameters to the main setup.py script (e.g. python3 setup.py install --httpfs), and add OpenSSL linking only if httpfs is enabled?

That's kind of a "non-pythonic" way to build stuff. Although some people (ehm, `tensorflow`) do use it, it's considered bad that one `setup.py` is used to make a differently named package. 

> I would also like to see the refactor in a separate PR if possible. Adding features while refactoring makes reviewing difficult, especially as the refactor seems quite involved.

Yup, can do that.

**Comment by pkit** [comment]
P.S. if you're ok with the non-pythonic setup I can do it, it should be way easier. But bear in mind that people who integrate it into their build process later may think it's bad. :)
Although it looks ugly either way, IMHO.

**Comment by Mytherin** [comment]
> > Could this be changed so that the duplicated code is not necessary? Perhaps we could read extra extensions from parameters to the main setup.py script (e.g. python3 setup.py install --httpfs), and add OpenSSL linking only if httpfs is enabled?
> 
> That's kind of a "non-pythonic" way to build stuff. Although some people (ehm, `tensorflow`) do use it, it's considered bad that one `setup.py` is used to make a differently named package.

The package shouldn’t be named differently, it should just change the extensions that are installed by default.

Eventually we want to move to a setup where you can install extensions separately (e.g. pip install duckdb_httpfs) but that should not involve duplicating the entire system. Instead it should involve only the extension itself, which can then be loaded using our LOAD EXTENSION command.

But that is more involved than just including an extra built-in extension, so for now that should be easier.

**Comment by pkit** [comment]
> The package shouldn’t be named differently, it should just change the extensions that are installed by default.

Ok. 
But the only problem with httpfs is that it requires openssl to be present, am I right?
If so, then it shouldn't be a problem enabling it for every duckdb build, because the wheels that my PR produces bring their own copy of openssl with them, and do not depend on system openssl at all.
I'm not sure if that's the case for Darwin though, and there is no support for httpfs in Windows anyway, it seems.

**Comment by hannesmuehleisen** [comment]
Yeah this openssl linkage is a big problem. Have not found a good solution for it except shipping the httpfs extension as a separate package/module/binary/whatever

**Comment by pkit** [comment]
Is it a problem if it will bring openssl in wheel itself?
As you can see below it brings everything with it.
```
Archive:  wheelhouse/duckdb_httpfs-0.2.8.dev312+g9f460469f.d20210626-cp38-cp38-manylinux2010_i686.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
 38489812  2021-06-26 10:46   duckdb.cpython-38-i386-linux-gnu.so
  1013836  2021-06-26 10:46   duckdb_httpfs.libs/libkrb5-d3a1a4c9.so.3.3
   134316  2021-06-26 10:46   duckdb_httpfs.libs/libselinux-10a8adc8.so.1
   183096  2021-06-26 10:46   duckdb_httpfs.libs/libk5crypto-3e7ee1bc.so.3.1
   331956  2021-06-26 10:46   duckdb_httpfs.libs/libgssapi_krb5-c362d938.so.2.2
    17408  2021-06-26 10:46   duckdb_httpfs.libs/libcom_err-20437120.so.2.1
    55556  2021-06-26 10:46   duckdb_httpfs.libs/libkrb5support-985cac75.so.0.1
   567328  2021-06-26 10:46   duckdb_httpfs.libs/libssl-227cedef.so.1.0.1e
    79808  2021-06-26 10:46   duckdb_httpfs.libs/libz-9f7255d3.so.1.2.3
  2061088  2021-06-26 10:46   duckdb_httpfs.libs/libcrypto-526a6201.so.1.0.1e
    13236  2021-06-26 10:46   duckdb_httpfs.libs/libkeyutils-94914291.so.1.3
     2700  2021-06-23 12:08   duckdb_query_graph/__init__.py
      532  2021-06-26 10:46   duckdb_httpfs-0.2.8.dev312+g9f460469f.d20210626.dist-info/METADATA
      109  2021-06-26 10:46   duckdb_httpfs-0.2.8.dev312+g9f460469f.d20210626.dist-info/WHEEL
       26  2021-06-26 10:42   duckdb_httpfs-0.2.8.dev312+g9f460469f.d20210626.dist-info/top_level.txt
     1673  2021-06-26 10:46   duckdb_httpfs-0.2.8.dev312+g9f460469f.d20210626.dist-info/RECORD
---------                     -------
 42952480                     16 files
```

**Comment by pkit** [comment]
closed in favor of #1936

**Pull request closed without merging**
