### PR TITLE
[Dev] Fix CI failure related to pandas and timezones

### PR DESCRIPTION
**Pull request by Tishj**
Failure encountered in:
https://github.com/duckdb/duckdb/actions/runs/5945486712/job/16125920975#step:9:10170

The test fails because it's run on python 3.7 with pandas 1.3.5

Solution:
We just skip the test on pandas versions below 2.0.0

### CODE REVIEW

**Comment by Tishj** [comment]
The CI on my fork fails:
https://github.com/Tishj/duckdb/actions/runs/5960803626/job/16168778202

I've tested on Mac with python3.8, 3.9, 3.11
pandas 2.0.0, 2.0.2 (test is already disabled on < 2.0.0)

I've also tested on a Linux docker container which runs Python 3.9.12
tested with pandas 2.0.0 and 2.0.3 (the version the CI failure is using)

TL;DR
I can't reproduce the failure

Hmm maybe it's related to the pyarrow version actually, since these use the ArrowPandas

**Comment by Tishj** [comment]
The CI failure is unrelated to these changes, should be addressed in a separate PR

**Review by pdet — APPROVED** [review]
I'm fine with the PR.

This makes me think: what kind of policy should we have regarding integrating with 3rd party libraries?
 I think our latest version should always work as best as possible to the latest release of a 3rd party library, but otherwise, no guarantees should be given.

@Mytherin opinions on this?

**Comment by Mytherin** [comment]
> I'm fine with the PR.
> 
> This makes me think: what kind of policy should we have regarding integrating with 3rd party libraries? I think our latest version should always work as best as possible to the latest release of a 3rd party library, but otherwise, no guarantees should be given.
> 
> @Mytherin opinions on this?

The policy is best effort to be compatible with all versions that are supported (i.e. not deprecated) by them - we can't guarantee being compatible with third party libraries if they make breaking changes.

**Pull request merged**
