### PR TITLE
Refactor csv reader includes because of r path length limitations

### PR DESCRIPTION
**Pull request by hannes**
R complains:

```
Found the following non-portable file paths:
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/buffer_manager/csv_buffer_manager.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/buffer_manager/csv_file_handle.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/options/state_machine_options.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/state_machine/csv_state_machine_cache.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/table_function/csv_file_scanner.hpp
  duckdb/src/duckdb/src/include/duckdb/execution/operator/csv_scanner/table_function/global_csv_state.hpp
```

This PR removes the subfolders in the csv_scanner includes folder, should fix it. Longest files now:

```
src/include/duckdb/catalog/catalog_entry/dependency/dependency_dependent_entry.hpp
src/include/duckdb/execution/operator/aggregate/physical_perfecthash_aggregate.hpp
src/include/duckdb/execution/operator/projection/physical_tableinout_function.hpp
src/include/duckdb/catalog/catalog_entry/dependency/dependency_subject_entry.hpp
src/include/duckdb/common/progress_bar/display/terminal_progress_bar_display.hpp
src/include/duckdb/execution/operator/persistent/physical_batch_copy_to_file.hpp
src/include/duckdb/execution/operator/aggregate/physical_ungrouped_aggregate.hpp
src/include/duckdb/execution/operator/helper/physical_materialized_collector.hpp
src/include/duckdb/storage/compression/chimp/algorithm/leading_zero_buffer.hpp
src/include/duckdb/execution/operator/persistent/physical_fixed_batch_copy.hpp
```

### CODE REVIEW

**Review by pdet — APPROVED** [review]
Thanks for the change! Fine with me. 
I think the folder structure makes it cleaner, but I can rethink it in the future to keep the r-path length in check.

**Comment by hannes** [comment]
There was a missing header in non-unity builds (somehow?)

**Comment by krlmlr** [comment]
This now has conflicts.

**Comment by hannes** [comment]
Should be fixed

**Comment by hannes** [comment]
merged again

**Pull request merged**
