### PR TITLE
fix convert uuid to arrow str error

### PR DESCRIPTION
**Pull request by wangfenjin**
Fix the bug in current implementation. I use the data in [here](https://github.com/duckdb/duckdb/blob/27c81ef25a86553ae5e5d23278d4a4b473732bba/test/sql/types/uuid/test_uuid.test#L8-L32) to export the parquet file for testing

```shell
D describe select * from 'data/parquet-testing/arrow/uuid-arrow.parquet';
┌───────┬──────┬──────┬─────┬─────────┬───────┐
│ Field │ Type │ Null │ Key │ Default │ Extra │
├───────┼──────┼──────┼─────┼─────────┼───────┤
│ u     │ UUID │ YES  │     │         │       │
└───────┴──────┴──────┴─────┴─────────┴───────┘
D select * from 'data/parquet-testing/arrow/uuid-arrow.parquet';
┌──────────────────────────────────────┐
│                  u                   │
├──────────────────────────────────────┤
│ a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 │
│                                      │
│ 47183823-2574-4bfd-b411-99ed177d3e43 │
│ 10203040-5060-7080-0102-030405060708 │
│ a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 │
│                                      │
│ 47183823-2574-4bfd-b411-99ed177d3e43 │
│ 10203040-5060-7080-0102-030405060708 │
│ 00000000-0000-0000-0000-000000000000 │
│ 00000000-0000-0000-0000-000000000001 │
│ 00000000-0000-0000-8000-000000000001 │
│ 80000000-0000-0000-0000-000000000000 │
│ 80000000-0000-0000-8000-000000000000 │
│ 80000000-0000-0000-8fff-ffffffffffff │
│ 80000000-0000-0000-ffff-ffffffffffff │
│ 8fffffff-ffff-ffff-0000-000000000000 │
│ 8fffffff-ffff-ffff-8000-000000000000 │
│ 8fffffff-ffff-ffff-8fff-ffffffffffff │
│ 8fffffff-ffff-ffff-ffff-ffffffffffff │
│ ffffffff-ffff-ffff-ffff-ffffffffffff │
│ a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 │
│                                      │
│ 47183823-2574-4bfd-b411-99ed177d3e43 │
│ 10203040-5060-7080-0102-030405060708 │
│ a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 │
│                                      │
│ 47183823-2574-4bfd-b411-99ed177d3e43 │
│ 10203040-5060-7080-0102-030405060708 │
│ 00000000-0000-0000-0000-000000000000 │
│ 00000000-0000-0000-0000-000000000001 │
│ 00000000-0000-0000-8000-000000000001 │
│ 80000000-0000-0000-0000-000000000000 │
│ 80000000-0000-0000-8000-000000000000 │
│ 80000000-0000-0000-8fff-ffffffffffff │
│ 80000000-0000-0000-ffff-ffffffffffff │
│ 8fffffff-ffff-ffff-0000-000000000000 │
│ 8fffffff-ffff-ffff-8000-000000000000 │
│ 8fffffff-ffff-ffff-8fff-ffffffffffff │
│ 8fffffff-ffff-ffff-ffff-ffffffffffff │
│ ffffffff-ffff-ffff-ffff-ffffffffffff │
└──────────────────────────────────────┘
```

### CODE REVIEW

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! Looks good to me.

**Comment by Mytherin** [comment]
Looks like there is a test failure in the arrow tests. Could you have a look?

**Comment by Mytherin** [comment]
@pdet any ideas?

**Comment by wangfenjin** [comment]
I push another commit to highlight my finds:
1. For the runtime error, seems we need 2 more params for the CreateStream() method? I check the code in other place and also the place call this function, should have 3 params. But not sure why previously it worked.
2. For the test failed, it's because after we read from parquet file and convert to duckdb and then convert to arrow, the uuid type infomation lost. But I'm not sure what's the preferred way to fix this.

@pdet Please help take a look

**Comment by wangfenjin** [comment]
hello @pdet , any thoughts about this?

**Comment by wangfenjin** [comment]
Hi @Mytherin , since I got no response from @pdet , do you think I can revert all the changes except for [src/common/types/data_chunk.cpp](https://github.com/duckdb/duckdb/pull/3136/files#diff-040a4ea9862d4208dda62ee9e6ff9890b1508ea693f667b63c3c57167724fed1) this file?

This file change should definitely work and fix the issue

**Comment by wangfenjin** [comment]
UUID is not a builtin  type in arrow, there is no standard way to represent it, it depends on ourselves

**Comment by Mytherin** [comment]
> Hi @Mytherin , since I got no response from @pdet , do you think I can revert all the changes except for [src/common/types/data_chunk.cpp](https://github.com/duckdb/duckdb/pull/3136/files#diff-040a4ea9862d4208dda62ee9e6ff9890b1508ea693f667b63c3c57167724fed1) this file?
> 
> This file change should definitely work and fix the issue
 
Yes please revert the other changes.

@pdet could you have a look at why the original commit lead to the failing tests?

**Comment by pdet** [comment]
Hey guys, sorry, for some reason github didn't properly give me the heads up on this PR.

So, the factory doesn't have the additional parameters there, since it is a different factory than the ones used in R and Python, should still produce the correct arrow objects (It just can't push filters/projections down). I think you can revert this stuff you pushed after your initial commit.

It looks correct to me, so by the failing CI test I can't really tell what's going on, I can check it out this afternoon.

**Comment by wangfenjin** [comment]
In favour of #3197

**Pull request closed without merging**
