### PR TITLE
fix some nodejs tests in some envs

### PR DESCRIPTION
**Pull request by jraymakers**
This fixes two different environment-specific problems with the Node JS tests that I encountered:

- Some tests (in `test_all_types.test.ts`) are timezone-dependent. When I ran them as-is in my local timezone (Pacific), they fail consistently, with expected and actual time strings differing by exactly that timezone difference. The fix is to ensure the tests always run in the same timezone (UTC) regardless of the settings of the platform on which they are run. I used the `cross-env` package to ensure this environment configuration will work on all platforms.

- One test (the "kurtosis" test in the change) failed, on my M2 MacBook but not my Intel MacBook, with the expected and actual floating-point values differing by very small amounts (about 10 * EPSILON). The existing expected was already different from the exact correct value by a small multiple of EPSILON. I changed the test case to accept values within a small tolerance range; I set this range to the smallest multiple of EPSILON that worked on my M2 MacBook.

### CODE REVIEW

**Comment by Mause** [comment]
Are you able to see if setting the `timezone` config param fixes the timezone issues instead? That would be preferable I think

**Comment by jraymakers** [comment]
> Are you able to see if setting the `timezone` config param fixes the timezone issues instead? That would be preferable I think

Good question. I looked into doing that. However, the problem is not in the results coming from DuckDB; the test cases are generating SQL using hard-coded values with UTC time offsets (see `replacement_values` in `test_all_types.test.ts`). The problem is with the expected values, which are constructed in JS using `new Date(...)` (see `correct_answer_map`). `Date` uses the current timezone of Node JS. So the solution to this problem has to be in the Node JS layer, not the DuckDB layer. And the only way to set the Node JS timezone that I'm aware of is through environment variables.

Before I figured out the above, I did try setting DuckDB's "TimeZone" parameter, both through the `Database` constructor and using the `SET` command, but neither addressed this problem.

**Comment by carlopi** [comment]
On nodejs test one possibility is just change in `tools/nodejs/test/test_all_types.test.ts`
from `new Date("1990-01-01T00:00")`
to `new Date(Date.parse("1990-01-01T00:00 UTC"))`.
Or to `new Date(Date.UTC(1990,?,?))`

Basically as explained at the bottom of this paragraph: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_epoch_timestamps_and_invalid_date, first option is system setting dependent, third is UTC only, second depends on the given reference.

I see `new Date(Date.UTC())` syntax is already used in `tools/nodejs/test/serialization.test.ts` file.

**Comment by jraymakers** [comment]
Regarding the suggestion to use `new Date(Date.UTC(...))`: This sounds like a reasonable idea, and I'll give it a try when I get a chance.

**Comment by jraymakers** [comment]
Using `new Date(Date.UTC(...))` worked well. I've updated this PR, so now there are no package.json changes, just test code changes.

**Review by carlopi — APPROVED** [review]

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
