### PR TITLE
Use M1 (ARM) OSX runners

### PR DESCRIPTION
**Pull request by hannes**
more than twice as fast..

### CODE REVIEW

**Comment by hannes** [comment]
@carlopi can you have a look at this maybe? should be close

**Comment by carlopi** [comment]
I am testing on my fork, I think only problem was Swift (bumped back to macos-12), but will check and then update the PR.

**Comment by hannes** [comment]
Looks like the `test_block_sizes.py` script does not work with new Python, maybe @taniabogatsch can check what's going on there?

**Review by carlopi — APPROVED** [review]

**Comment by taniabogatsch** [comment]
It looks like it is the same reason that, e.g., the `Vector Sizes` script is failing, which is that the `execute_system_command` fails. As in, not all tests pass. This should not be related to the Python version.

The [current nightly runs](https://github.com/duckdb/duckdb/actions/runs/8073321780) seem to have the same behavior. Or am I missing something?

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
