### PR TITLE
Don't leak memory in duckdb.query_df

### PR DESCRIPTION
**Pull request by alanhdu**
My C++ is not the best, but I think this should solve the surface-level problem from https://github.com/duckdb/duckdb/issues/3144 around `query_df`-- in this particular case, we know that no one can have called `SetAlias` on the `DuckDBPyRelation`, so we can use it to unregistered the Python object when we're done. This, of course, does not address the underlying problem with this `conn->FromDF` API.

My main concern is whether `DuckDBPyResult` somehow relies on the memory of the registered object or not -- I don't quite understand the `QueryResult`/`DataChunk` code to be fully confident, but at the very least all tests pass locally for me and 

```python
import pandas as pd
import duckdb
import numpy as np

from tqdm import tqdm

for __ in tqdm(range(10_000_000)):
    df = pd.DataFrame({"x": np.random.rand(1_000_000)})
    duckdb.query_df(df, "df", "SELECT * FROM df")
```

no longer seems to leak memory.

### CODE REVIEW

**Comment by pdet** [comment]
Thanks for the report and the PR :-).
I see the issue. We should probably run the address sanitizer on the Python/R clients at some point.

In any case, maybe we should check this in the destructor of the PyRelation? 
I'm adding a pointer to the PyConnection to fix #3141, so you can use that pointer to unregister pyobjects in the connection upon rel destruction as well.

**Comment by alanhdu** [comment]
> In any case, maybe we should check this in the destructor of the PyRelation?

I think I can do that -- let me know what to rebase onto to pull in the PyConnection pointer.

**Comment by Mytherin** [comment]
@pdet can this be merged?

**Comment by pdet** [comment]
The code seems fine, I think we are just missing a test for it.
Maybe something like:
```python
import pandas as pd
import duckdb
import numpy as np

import os, psutil
process = psutil.Process(os.getpid())
mem_usage = process.memory_info().rss

for __ in tqdm(range(10_000_000)):
    df = pd.DataFrame({"x": np.random.rand(1_000_000)})
    duckdb.query_df(df, "df", "SELECT * FROM df")

cur_mem_usage = process.memory_info().rss
assert that cur_mem_usage is on the same order of magnitude of mem_usage
```

**Comment by Mytherin** [comment]
Closing this due to the lack of activity, @pdet will work on a fix for the problem

**Pull request closed without merging**
