### PR TITLE
Return smaller cardinality for Top N operator

### PR DESCRIPTION
**Pull request by jeewonhh**

### CODE REVIEW

**Review by Tmonster — COMMENTED** [review]
Makes sense to me. @jeewonhh do you have any micro benchmarks that can show this is a good change?

**Comment by Mytherin** [comment]
Thanks!

> Makes sense to me. @jeewonhh do you have any micro benchmarks that can show this is a good change?

I would argue this is just a bug-fix, the flipped order is not intended

**Comment by Mytherin** [comment]
But it doesn't really make sense to return the `child_cardinality` if `child_cardinality >= limit`, right? Then if you have a TopN with N=5 over a table with 6M rows, you return 6M as expected cardinality. I think these conditions were just inverted by accident.

**Comment by Tmonster** [comment]
Oh yea, that makes more sense, nevermind 😅

**Pull request merged**
