### PR TITLE
Enable building for Python 3.10

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by Mause** [comment]
Looks like it's still used in some places: https://pypistats.org/packages/duckdb

Numpy has just dropped support for it though, and at the same time added support for 3.10

**Comment by Mytherin** [comment]
It seems this doesn't quite work yet because of NumPy:

>     ERROR: Command errored out with exit status 1:
>     setup.py:67: RuntimeWarning: NumPy 1.19.4 may not yet support Python 3.10.

Perhaps we need to wait until NumPy pushes a new release to pip?

**Comment by Mause** [comment]
Numpy 1.21.2 supports python 3.10, but drops support for 3.6 - may have to select the right numpy version for each build

**Comment by Mytherin** [comment]
This is implemented now in #2684

**Pull request closed without merging**
