### PR TITLE
Integer types now correctly increase `width` of DECIMAL type.

### PR DESCRIPTION
**Pull request by Tishj**
This PR fixes the issue addressed in #4106

### CODE REVIEW

**Comment by Tishj** [comment]
Hmm some of the CI is failing because HUGEINT and DECIMAL are being mixed
Since hugeint can be even bigger than 38 decimals, this results in an invalid input exception, because the DECIMAL type cant hold a width of > 38

Not sure what the correct answer is here

**Comment by taniabogatsch** [comment]
So if `width + scale` exceeds the `HUGEINT` size/maximum size, I would throw an error instead of loosing precision silently? This seems the sane thing to do, no? Then the user can update the data to loose precision intentionally haha

**Comment by Mytherin** [comment]
> So if `width + scale` exceeds the `HUGEINT` size/maximum size, I would throw an error instead of loosing precision silently? This seems the sane thing to do, no? Then the user can update the data to loose precision intentionally...

I would say this should happen only if there exists data which would cause this loss of precision. Most usages of hugeint won't come close to the maximum value in the domain, after all. We can just set the width to the maximum width of decimals (38), and an error will be thrown if a data point exceeds that value.

**Comment by Tishj** [comment]
Thanks Mytherin, that's clearly the right answer, fixed it :)

**Comment by Mytherin** [comment]
Thanks! Looks good.

**Pull request merged**
