### PR TITLE
Add coverage check to R workflow

### LINKED ISSUE #2929: [R]: Test coverage for R package
Possible with the covr package, we can upload results to codecov from GitHub Actions.

### PR DESCRIPTION
**Pull request by krlmlr**
and use RStudio Package Manager for fast installs.

Closes #2929.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
nice where can I see coverage reports?

**Comment by krlmlr** [comment]
They will be uploaded to codecov once the builds are fixed.

**Comment by krlmlr** [comment]
Blocked by https://github.com/r-lib/covr/issues/497. We could work around here, but it's not going to be pretty.

**Comment by krlmlr** [comment]
Superseded by #2952.

**Pull request closed without merging**
