### PR TITLE
Fix (de)serialization + enable serialization verification for more operators

### PR DESCRIPTION
**Pull request by Mytherin**
Follow-up from #4420 - this PR enables serialization verification and fixes serialization for the following logical operators:

```
INSERT
UPDATE
DELETE
PREPARE
EXECUTE
ALTER
CREATE_TABLE
CREATE_INDEX
CREATE_SEQUENCE
CREATE_VIEW
CREATE_SCHEMA
CREATE_MACRO
PRAGMA
TRANSACTION
CREATE_TYPE
EXPLAIN
COPY_TO_FILE
VACUUM
```

Note that the serialization is not complete yet - the following operators are still disabled for verification:

```
EXPLAIN
COPY_TO_FILE
PRAGMA
PREPARE
EXECUTE
```

In addition a `NotImplementedException` can still be thrown by operators to signify that serialization of an operator is not currently possible - which is still used by several functions/aggregations.

### CODE REVIEW

**Comment by Mytherin** [comment]
CC @bleskes @stephaniewang526

**Comment by stephaniewang526** [comment]
Thank you for working on this!

Wonder if it's possible to also get `sorted_aggregate_function`, `list_aggregates`, `list_lambda`, and `quantiles` handled as well? We're seeing test failures on these.

**Comment by Mytherin** [comment]
> Thank you for working on this!
> 
> Wonder if it's possible to also get `sorted_aggregate_function`, `list_aggregates`, `list_lambda`, and `quantiles` handled as well? We're seeing test failures on these.

Those are indeed expected not to work yet as per the list in #4420. I won't have time to work on this before 0.8.0 but we can discuss later.

**Comment by gitccl** [comment]
@Mytherin Hi, it seems that `expected_set_types` and `source_columns` fields in `LogicalInsert` are not used. Can we remove them?

**Pull request merged**
