### PR TITLE
Throw error if attempting to delete from table without physical columns

### PR DESCRIPTION
**Pull request by Tishj**
Fixes issue #4685

This would previously die in DataChunk::Initialize because it would attempt to create a datachunk without any types.
Since this operation doesn't do anything and in my opinion isn't valid, I have opted to turn this into an error.

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

Perhaps the error should instead be on creating a table with only generated columns? I can imagine multiple issues occurring with tables without physical columns (e.g. what about inserts? updates? alter statements?). Such tables don't seem particularly useful to me either.

**Comment by Tishj** [comment]
Ah good point, address the problem at the source!
I will do that instead 👍

**Review by Mytherin — APPROVED** [review]
Thanks! LGTM

**Comment by Tishj** [comment]
I'm not entirely sure why this regression is failing, when I run it locally it also happens for the first init_db (the OLD_DB)
So it seems like it wasn't able to find the old database file ?

**Comment by Mytherin** [comment]
Likely a HTTP error, will rerun

**Pull request merged**
