### PR TITLE
Fix a TSAN error for test/sql/window/test_partition_flushing.test

### PR DESCRIPTION
**Pull request by omo**
This fixes the TSAN error caught by "Thread Sanitizer" GitHub check.
The Pipeline instance is (in theory) deleted by the main thread
so the worker has to own the lifetime when using it.

I'm not sure if this happens in practice, but probably it's a good
idea to just make TSAN happy and the tests green.

### CODE REVIEW

**Comment by omo** [comment]
Let's make the check green(er)!

**Comment by omo** [comment]
Updated to make it less awkward.

**Review by hawkfish — APPROVED** [review]

**Review by Mytherin — APPROVED** [review]
Thanks for the PR! Looks great.

**Comment by omo** [comment]
Thanks for the reviews! Would you mind merging this for me?

**Comment by hawkfish** [comment]
> Thanks for the reviews! Would you mind merging this for me?

@omo The people with merge permission are in Amsterdam/CET, so it is about midnight there.

**Comment by omo** [comment]
Oh right. I just wanted to make sure to get this in.
Thanks for he reminder Richard!

**Pull request merged**
