### PR TITLE
build: swap libclang for cxxheaderparser

### PR DESCRIPTION
**Pull request by Mause**
A gift for @Tishj. Much easier to use and install

### CODE REVIEW

**Review by Tishj — APPROVED** [review]
This looks about a million times more sane than the original, thank you :pray:

**Comment by Tishj** [comment]
```patch
diff --git a/tools/pythonpkg/scripts/generate_connection_wrapper_methods.py b/tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
index a5d77e60fa..9604e2ed9e 100644
--- a/tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
+++ b/tools/pythonpkg/scripts/generate_connection_wrapper_methods.py
@@ -1,19 +1,9 @@
 import os
 import json
 
-# Requires `python3 -m pip install libclang==16.0.6`
-from get_cpp_methods import test_clang, get_methods, FunctionParam, ConnectionMethod
+from get_cpp_methods import get_methods, FunctionParam, ConnectionMethod
 from typing import List, Tuple
 
-if not test_clang():
-    print(
-        """'generate_connection_wrapper_methods.py' skipped because of a Clang error.
-This is likely caused by not having, or not having the right version of 'libclang' installed.
-You can ignore this warning if you made no changes to Python code, it should not be ignored in CI.
-"""
-    )
-    exit(0)
-
 os.chdir(os.path.dirname(__file__))
 
 JSON_PATH = os.path.join("connection_methods.json")
```

**Comment by Tishj** [comment]
<https://github.com/duckdb/duckdb/actions/runs/9561126259/job/26354639883?pr=12567> requires a merge, has been fixed by the last numpy-related PRs

**Comment by carlopi** [comment]
I love you all, but I really don't see why we are hand-rolling this.

And I am not sure why the changes to `duckdb.h` are needed. They might make sense, but I would reason independently, not do this to make the tool happy.

**Comment by Tishj** [comment]
We're not handrolling anything?
The enum verification is to make sure we don't break the ABI again

The C++ code gen is so we can have the `duckdb` module in Python act as a wrapper for a default connection.
Which is possible without generating anything, but that introduces human error

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
