### PR TITLE
SQLite: Avoid parsing queries twice

### LINKED ISSUE #946: SQLite: Double query parsing
From sqlite3_api_wrapper.cpp:

`ExtractStatements` and `Prepare` are both eventually calling `ParseStatements()` which means that queries are parsed twice.

### PR DESCRIPTION
**Pull request by jdahlin**
Introduce and APIs that allows the SQLite3 wrapper to parse queries
into statements and then prepare them without reparsing.

Also includes minor cleanups: vector.empty.

Fixes #946

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
There seems to be an issue in the tests with the shell. Run those tests like so: `python3.7 tools/shell/shell-test.py build/debug/duckdb`

**Comment by jdahlin** [comment]
> There seems to be an issue in the tests with the shell. Run those tests like so: `python3.7 tools/shell/shell-test.py build/debug/duckdb`

Thanks, I was able to track down the issue using that. As a site note, building with clang and enabling AddressSantitizer (ASAN_OPTIONS=detect_leaks=1) will detect plenty of leaks when running that.

**Comment by jdahlin** [comment]
Errors is in SQLancer and the message is:
**The job exceeded the maximum log length, and has been terminated.**

**Comment by Mytherin** [comment]
Apologies for the slight delay, initially I thought the test failure was unrelated to the patch but looking at it some more it does seem related. The SQLancer test is failing with the following error:

```
Not implemented: Cannot convert VIEW to SQL because it was not created with a SQL statement
```

This seems to be caused by the separation of the statement extraction from the execution of the query. The view info gets the SQL query in `bind_create.cpp:55`:
```cpp
// extract the SQL from the query, if any
if (stmt.stmt_location + stmt.stmt_length <= context.query.size()) {
	base.sql = context.query.substr(stmt.stmt_location, stmt.stmt_length);
}
```

The reason it does it this way is because the entire SQL string can contain multiple statements, so the correct statement needs to be extracted (e.g. if the query is `CREATE TABLE t1(i INTEGER); CREATE VIEW v1 AS SELECT * FROM v1;`, we need to extract only the second part).

Ideally this code would be moved from the binder to the transformer (i.e. this should be handled in `transform_create_view.cpp`), that should resolve the issue here.

**Comment by hannesmuehleisen** [comment]
@jdahlin any update here?

**Comment by Mytherin** [comment]
Closing this issue because of lack of activity, feel free to re-open.

**Pull request closed without merging**
