### PR TITLE
R: Fix core dump when failing to evaluate ALTREP query

### PR DESCRIPTION
**Pull request by krlmlr**
This affects ~100 of 4500 of dplyr's reverse dependencies.

### CODE REVIEW

**Comment by krlmlr** [comment]
We can only use `cpp11::stop()` in functions that are wrapped by cpp11.

**Review by Tmonster — APPROVED** [review]
lgtm. Looks like the `test_relational.R` file is all whitespace changes

**Comment by hannes** [comment]
Thanks, do we call cpp11::stop in other unwrapped functions?

**Comment by krlmlr** [comment]
This is going to need some investigation. I've put it on my list.

**Pull request merged**
