### PR TITLE
Allow WHERE clause referring aliases defined in SELECT clause.

### LINKED ISSUE #699: column aliases in WHERE
Hi!
What are your thoughts regarding support for the use of column aliases in WHERE?

```sql
CREATE TABLE integers(i INTEGER); 
INSERT INTO integers VALUES (1), (2), (3), (NULL);
SELECT i AS k FROM integers WHERE k=1 ORDER BY k;
Error: near line 1: Unknown: Referenced column "k" not found in FROM clause!
```

It looks like it's supported in GROUP BY and ORDER BY
```sql
SELECT i AS k FROM integers GROUP BY k ORDER BY k;
k
----------

1
2
3
```

### PR DESCRIPTION
**Pull request by omo**
This adds alias handling to WhereBinder. The logic is extracted from
HavingBinder as ColumnAliasBinder and shared between them.

Note that what it does is to expand the aliased expression inline,
so the computation isn't shared between these two clauses.

This fixes #699.

### CODE REVIEW

**Comment by omo** [comment]
Thanks for the review Mark!

> SELECT 1 AS i, COUNT(*) FROM integers GROUP BY i HAVING i=2;
> --- DuckDB returns empty set (i binds to the alias), whereas SQLite returns the row with i=2 in integers

Interesting. The `GROUP BY` seems to have some side effect? Let me look at that.
Also, a test is failing for some reason :-( Needs a bit more iteration.
Will let you know once it's ready for the another round.

**Comment by omo** [comment]
> There still seems to be some failing tests, could you have a look at those?
> 
Oops. Fixed.

> 
> This happens in a separate step by calling `ExpressionBinder::BindTableNames`. That is because the groups and orderings etc should match regardless of qualification, i.e. the following queries should all work/be the same:
> 
Thanks for the tip!
Looking closer, it seems like how `BindTableNames` is implemented is the problem.
It explicitly prioritize alias over the column name.

I fixed it in a separate commit as an FYI.
Some tests on test_having_alias.test have to be updated.
We can leave it unchanged, or we can do change it in this way.
I don't have strong opinion which we should take.

**Review by Mytherin — COMMENTED** [review]
Thanks for the changes! The test changes look good to me. Some minor comments, otherwise I think it is good to go.

**Review by Mytherin — APPROVED** [review]
Thanks for all the fixes! Looks good to me now. I will merge it after the tests pass.

**Pull request merged**
