### PR TITLE
Include guard renaming for amalgamation export

### PR DESCRIPTION
**Pull request by jwyles-ahana**
This updates the scripts/parquet_amalgamation.py script to prepend the include guard variables with _DUCKDB to avoid conflicts in other projects that may also use Thrift.

### CODE REVIEW

**Comment by yingsu00** [comment]
@Mytherin will you be able to review this? Thank you.

**Comment by Mytherin** [comment]
Thanks for the PR! Could we perhaps just inline the include guard fixes into the thrift files themselves, rather than patch them with a script?

**Comment by jwyles-ahana** [comment]
@Mytherin Changing the include guards and wrapping the bitwise_cast function in the right namespace could be done on the original files instead of by the script. We already had the scripts ready to use on our end so that seemed easiest.

**Comment by yingsu00** [comment]
> Could we perhaps just inline the include guard fixes into the thrift files themselves, rather than patch them with a script?

@Mytherin Could you please elaborate a bit on what "thrift files" you meant? Did you mean you want the files  in https://github.com/duckdb/duckdb/tree/d03176469cbb03ea557be1fc04475ca7115160f7/third_party/thrift/thrift to be modified directly to have the updated include guards?

**Comment by Mytherin** [comment]
Thanks, looks good to me.

**Pull request merged**
